### PR TITLE
[WFLY-4756] Removing jboss-ejb-iiop_1_0.xsd from WFLY proper to move to metadata project

### PR DESCRIPTION
**Pull request by wprice**
Requesting to move jboss-ejb_1_0.xsd from WFLY project to move to the metadata project as the IIOP information is embedded in the metadata classes etc.

### CODE REVIEW

**Comment by bstansberry** [comment]
this is ok to test

**Comment by wprice** [comment]
full testsuite was run with no issues

**Comment by wprice** [comment]
Note, not be as familiar with the test suite as I used to be, I simply did 

mvn clean install

If there are other suites I missed, or other flags I did not include, please let me know.

**Comment by wprice** [comment]
I'm not sure if I have access to TeamCity or not, could someone take a look? I am not seeing this failure locally and I can't imagine it uses the IIOP stuff, but it might. Thanks.

**Comment by wprice** [comment]
Ok, quick check of the test case, nothing appears to relate to IIOP so it looks like it might either be a transient failure, or a failure in another area of the suite. Again, without access to TeamCity I can't be more specific.

**Comment by bstansberry** [comment]
@ctomc Can you tell Weston what he needs to know to use TeamCity?

Weston, the failure is unrelated.

But this looks to be the same thing as #7706, which Carlo already rejected.

**Comment by wprice** [comment]
It's not being rejected, there isa a format issue that I'm chasing down but doesn't effect this particular pull request.

**Comment by wprice** [comment]
Note, any issues that effect #7706 are due from additions to the XSD.Since in this pull request the xsd is being removed, it is not the same issue at all.

**Comment by wolfc** [comment]
Same issue as https://github.com/wildfly/wildfly/pull/7706. First jboss-ejb-iiop_1_0.xsd needs to be within metadata. Then metadata needs to be upgraded to bring back in jboss-ejb-iiop_1_0.xsd for docs/schema.

**Comment by wprice** [comment]
But again, this should not effect Wildfly per se, it's just that it needs to be in metadata to be correct.

**Comment by scottmarlow** [comment]
@wprice I am using the following command (from wildfly root folder) to run the wildfly/testsuite/integration/basic tests:

 ./integration-tests.sh -Dts.basic -Dmaven.test.failure.ignore=true -DfailIfNoTests=false > /tmp/test.txt

After the test run, I manually read the test.txt for failures.  I used to do a "mvn clean install" in the wildfly/testsuite/integration/folder also but that doesn't seem to work as well any more.  I think that the key of the two flags being passed is to not stop testing on the first failure.  Which is important when you want to run all of the tests.

**Comment by wprice** [comment]
Thanks much Scott. Sort of was wondering about this.

**Comment by stuartwdouglas** [comment]
Metadata has been upgraded to 1.0.0.Beta3 which includes this commit, so it should be ready to merge.

**Pull request merged**
