### PR TITLE
WFLY-4214 Update the version of maven to 3.2.5

### PR DESCRIPTION
**Pull request by tomjenkinson**
https://issues.jboss.org/browse/WFLY-4214

### CODE REVIEW

**Comment by langfr** [comment]
Version number in download-maven.ps1 has to be changed too from 3.2.3 to 3.2.5.
As of https://github.com/wildfly/wildfly/pull/7058 a rebase is probably needed.

**Comment by kabir** [comment]
@tomjenkinson FYI my merged https://github.com/wildfly/wildfly/pull/7058 also handles this, although it looks in a different location for 3.2.3 (driven by downstream where we need to be more conservative). The new location also seems to contain the latest 3.2.5, so this PR should be ok.

**Comment by ctomc** [comment]
do not merge this yet! We need to verify that newer maven doesn't break anything.
In short hold for few more days.

**Comment by kabir** [comment]
Adding hold label in line with Tomaz's comments. @ctomc please let me know when you are happy

**Comment by ctomc** [comment]
this is ok to be merged

**Comment by ctomc** [comment]
A good thing would be to also have PR that upgrades maven in wildfly-core

**Comment by ctomc** [comment]
@tomjenkinson you are right, i am thinking about too many branches and repos :( 
There is no such script there (yet), it is in EAP repo but that is different story. 
I have some branch somewhere to add it to core as well, i knew i should quit coffee over the holidays :)

aka @kabir please merge this.

**Comment by kabir** [comment]
Retest this please

**Comment by wolfc** [comment]
Can someone clean up that 'hold' label?

**Pull request merged**
