### PR TITLE
[WFLY-6085] Add a mapping for 'AdvancedADLdap' to the login modules map as this is how it has been documented.

### PR DESCRIPTION
**Pull request by darranl**

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
I was just thinking about this and I was wondering if there are any compatibility concerns here? If a config references the new name it will not work on older servers in mixed domain scenarios

**Comment by bstansberry** [comment]
I believe a transformer could be added for that.

**Comment by bstansberry** [comment]
I moved this to 11.x. It doesn't seem time critical and we are at the end of 10.x work.

**Comment by stuartwdouglas** [comment]
@bstansberry do you think this actually needs a transformer, or is it ok to merge as is?

**Review by dmlloyd — DISMISSED** [review]

**Comment by bstansberry** [comment]
@stuartwdouglas @dmlloyd I'm ok with letting the transformer bit slide as it would be a fairly significant hassle and this whole issue IMO is really minor.

If people are using this on a legacy server they must already have the right value, so changing the value to one that doesn't work is a corner case.

**Comment by kabir** [comment]
@darranl As this pull request has  been held up for a long time, I am closing it to get the pull request queue under control again. Since this is very old now, it will be a very long time until this one will be addressed. Also, I don't have much time to spend on this to evaluate on a case by case basis.

If this is something important to you or the project please feel free to recreate the pull request. That way it will come on top of the pile again, and be looked at again sooner. 

If it is a new **feature**, please follow the new process for features. Ping @kabir or @jamez if you are unsure what this means, and we can help. Please do that before opening the pull request though.

Sorry for any inconvenience!

**Pull request closed without merging**
