### PR TITLE
WFLY-11315 Remove unused dependencies from org.jboss.as.jpa

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
https://issues.redhat.com/browse/WFLY-11315

### CODE REVIEW

**Comment by scottmarlow** [comment]
test this please

**Comment by bstansberry** [comment]
this is ok to test

**Comment by bstansberry** [comment]
@scottmarlow Is this ok?

**Review by scottmarlow — APPROVED** [review]

**Comment by scottmarlow** [comment]
Yes, looks good  @bstansberry

**Pull request merged**
