### PR TITLE
[WFLY-9850] switched to using sed to edit JAVA_OPTS

### PR DESCRIPTION
**Pull request by rsearls**
Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [x] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue(s)
- [x] Pull Request contains description of the issue(s)
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

### CODE REVIEW

**Comment by rsearls** [comment]
https://issues.jboss.org/browse/WFLY-9850 wsprovide fails on HPUX machines

**Review by ctomc — APPROVED** [review]

**Comment by rsvoboda** [comment]
Is `sed` available on all platforms we care about ?

@marekkopecky fyi

**Comment by rsearls** [comment]
Typically sed is available on unix OS and this script is only used on unix.

On Wed, Feb 21, 2018 at 2:28 PM, Rostislav Svoboda <notifications@github.com

**Comment by kabir** [comment]
@marekkopecky Can you please check it?

**Comment by marekkopecky** [comment]
@kabir Works correctly on Solaris and HPUX

**Pull request merged**
