### PR TITLE
[WFLY-10912] CodecSessionConfig#findSessionId() causes an incorrect JSESSIONID Set-Cookie header

### PR DESCRIPTION
**Pull request by petrberan**
https://issues.redhat.com/browse/WFLY-10912

### CODE REVIEW

**Comment by bstansberry** [comment]
@petrberan This breaks some clustering tests. @pferraro FYI

**Comment by petrberan** [comment]
Thanks @bstansberry Noticed that already on Fri, managed to fix some over the weekend, but others are failing instead. Will look into that

**Review by pferraro — CHANGES_REQUESTED** [review]
As mentioned in the associated jira, it is not the responsibility of the SessionConfig implementations to validate the incoming session ID.  WFLY-10912 must be fixed within Undertow itself, which should never include a JSESSIONID cookie in the response unless the request references a valid session.

**Comment by pferraro** [comment]
Superseded by https://github.com/wildfly/wildfly/pull/16019

**Pull request closed without merging**
