### PR TITLE
WFLY-8449 Return specified EJB context data keys

### PR DESCRIPTION
**Pull request by stuartwdouglas**
https://github.com/wildfly/wildfly-proposals/pull/42
https://issues.jboss.org/browse/EAP7-976
https://issues.jboss.org/browse/WFLY-8449

### CODE REVIEW

**Comment by kabir** [comment]
@dmlloyd please approve, I've seen long discussions between you two :)

**Comment by kabir** [comment]
I am putting the hold label on this until the analysis is cleaned up/approved

**Comment by dmlloyd** [comment]
Yeah we'll hold it for now.

**Comment by stuartwdouglas** [comment]
I belive I have now address all of the concerns raised by @dmlloyd

**Comment by kabir** [comment]
Retest this please

**Pull request merged**
