### PR TITLE
[9.x] WFLY-4812 Upgrade Infinispan to 7.2.3.Final

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-4812

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Does this remove the need for https://github.com/wildfly/wildfly/pull/7629 ?

**Comment by pferraro** [comment]
@stuartwdouglas It does not remove the need for #7629.  This only changes the isolation of the ejb cache.

**Comment by stuartwdouglas** [comment]
I thought the isolation of the cache was the problem (at least the problem started appearing after it was changed). If you have REPEATABLE_READ does this mean that web requests will wait until the previous request has finished and the changes are commited to the cache? If so then this should be all that is required to fix the test.

**Comment by pferraro** [comment]
I had initially widened the isolation to improve concurrent read access a session.  Let me revert that until I find a better solution.

**Pull request merged**
