### PR TITLE
security subsystem - Remove deprecated code together with transformers for 7.2 & 7.1 series

### PR DESCRIPTION
**Pull request by ctomc**
remove all legacy & deprecated code that emulated model from 7.1.1 series

### CODE REVIEW

**Comment by ctomc** [comment]
retest this please

**Comment by ctomc** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
compile issue on master-ignore; retest should show it

http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35480&buildTypeId=WF_MasterIgnoreWindows&tab=buildLog

**Pull request closed without merging**
