### PR TITLE
WFLY-4452 Use Flag.RESTART_RESOURCE_SERVICES for child resources of cache

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-4575

This PR addresses 2 primary issues:
1. Most resource attributes in the Infinispan subsystem use Flag.RESTART_ALL_SERVICES.  This is overly coarse/intrusive.  Changing any attribute of a cache configuration should only require the restart of a minimal set of services.
2. The subsystem currently uses an awkward mechanism of loading attribute defaults from an external file.  This is because child resources of a cache are currently optional.  This is a major source of confusion for new users.  For example, if I create a local-cache, but do not define a transaction child resource, what will be the default behavior?  The defaults in the model are not applied unless the corresponding resource is created.  This PR makes these child resources required. Every child resource of a cache installs a service which encompasses its configuration:
https://issues.jboss.org/browse/WFLY-4146
The cache resource only needs to depend on the requisite child configuration components for that cache type.  This means that the child resources of a cache are no longer just blocks of configuration, but now create fine-grained services.  This also serves to reduce the number of service restarts required for (1).  This reduces complexity immensely (e.g. no more monolithic CacheAddHandler).

Additionally, I've made a number of tangential changes to the Infinispan subsystem, including:
- Eliminate loading of cache configuration defaults from an external a file.  Because all components of a cache configuration are required, we no longer have a need for this (i.e. infinispan-defaults.xml).  All defaults are explicitly determined by the model.  This also improves subsystem startup time.
- Use better path names for cache and cache container components, e.g. /local-cache=test/component=transaction instead of /local-cache=test/transaction=TRANSACTION.  Paths are transformed to legacy path to support mixed domains. Added resource aliases for legacy paths.
- Use better path names for cache stores, e.g. /local-cache=test/store=file instead of /local-cache=test/file-store=FILE_STORE. Paths are transformed to legacy path to support mixed domains. Added resource aliases for legacy paths.
- Refactor indexing related cache attributes into an Indexing child resource, including requisite transformers.
- Refactor string-table/binary-table properties of jdbc cache stores into child resources, including requisite transformers.  This simplifies the corresponding jdbc store management operations significantly. e.g. /local-cache=test/store=mixed-jdbc/table=binary
- Enumerated resource attributes.  This allows us to more easily operate on all attributes of a resource, and allows us to more easily do clever things with generic resource handlers.  This also minimizes the work required to add a new attribute to a resource.
- Enhanced generic resource description resolver that looks for the description of a given key from a set of prefixes.  This prevents the need to duplicate descriptions when using resource hierarchies.

To facilitate these changes, I've introduced a number of controller abstractions (found in org.wildfly.clustering.common) that reduce the amount of boilerplate code required to instrument a resource:
- ResourceServiceBuilder<T>, an extension of org.wildfly.clustering.service.Builder<T> that allows the builder to configure itself via a resource model.
- ResourceServiceHandler, an abstraction that encapsulates logic for installing and removing services for a resource
- A simple ResourceServiceHandler implementation that installs/removes a single service via a ResourceServiceBuilder<T> factory
- Generic resource add/remove operation handlers that delegate to a ResourceServiceHandler
- Generic RestartParent*Handlers that delegate to a ResourceServiceBuilder factory.

### CODE REVIEW

**Comment by pferraro** [comment]
The above failure is due to https://issues.jboss.org/browse/WFCORE-692
and is fixed by: https://github.com/wildfly/wildfly-core/pull/728

**Comment by pferraro** [comment]
Hmm - this works fine for me.  Rebasing again...

**Comment by pferraro** [comment]
Finally.  Ready for review.

**Comment by pferraro** [comment]
I just realized that I need to bump the management api version (since this was originally for WF9, but is now for WF10).

**Comment by pferraro** [comment]
Ready for review.

**Comment by pferraro** [comment]
Retest this please.

**Comment by pferraro** [comment]
Please remove rebase-this flag.  Ready for review.

**Comment by bstansberry** [comment]
Based on chat today I think you know this, but in case not it still needs a rebase. Ping me when it's done so I can try and not let it sink from the mantle into the core.

**Comment by bstansberry** [comment]
The Build 7045 failure:

```
[21:37:14][org.wildfly:wildfly-ts-integ-clustering] Running org.jboss.as.test.clustering.cluster.ejb.remote.RemoteFailoverTestCase
[22:01:20][org.wildfly:wildfly-ts-integ-clustering] 
[22:01:20][org.wildfly:wildfly-ts-integ-clustering] Results :
[22:01:20][org.wildfly:wildfly-ts-integ-clustering] 
[22:01:20][org.wildfly:wildfly-ts-integ-clustering] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[22:01:20][org.wildfly:wildfly-ts-integ-clustering] 
[22:01:20][org.wildfly:wildfly-ts-integ-clustering] [ERROR] There was a timeout or other error in the fork
```

This is happening regularly now. If you look at the history of the various CI jobs, most, maybe all recent cases of large #s of failures are due to this test not completing.

I was hoping this PR would fix it. Guess not. :( That test needs to be disabled until it works.

**Comment by rhusar** [comment]
@bstansberry Fixing of RemoteFailoverTestCase is beined tracked on https://issues.jboss.org/browse/WFLY-3532 and richard has been working on that past weeks so IMHO it won't get forgotten if we go ahead and ignore it..

**Comment by bstansberry** [comment]
https://github.com/wildfly/wildfly/pull/7769 @Ignores that test

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by Maxoid** [comment]
Dear Paul,
I need your help, please. I've spent two days to clarify, why my WildFly9 Infinispan configuration stop working in WildFly10. 

I just uses a cache with a custom store configuration. Cache configured through the jboss-cli like this:
```
/profile=full-ha/subsystem=infinispan/cache-container=cacheContainer:add()
/profile=full-ha/subsystem=infinispan/cache-container=cacheContainer/transport=TRANSPORT:add(lock-timeout=60000)
/profile=full-ha/subsystem=infinispan/cache-container=cacheContainer/replicated-cache=test:add(mode=ASYNC)
/profile=full-ha/subsystem=infinispan/cache-container=cacheContainer/replicated-cache=test/store=STORE:add(class=org.infinispan.persistence.sifs.configuration.SoftIndexFileStoreConfigurationBuilder,passivation=false,preload=false,purge=false,properties={dataLocation=${jboss.server.data.dir}/infinispan/container/testData,indexLocation=${jboss.server.data.dir}/infinispan/container/testIndex})
```
Ok, I read your comments and changed scripts accordingly. Nothing changed.

I know, that to start my Infinispan container in WF9 I need to inject CacheContainer instance inside the EJB container and after that, I can use CacheContainer.getCache("test") to get access to a properly configured cache instance.

```
@Singleton
@Startup
public class CacheAccessBean {

@Resource(lookup = "java:jboss/infinispan/container/cacheContainer")
private CacheContainer cc;

@PostConstruct
public void init() {
    Cache cache = cc.getCache("test");
...
}
```
This is not work in WilfFly10. As I can see, CacheContainer injected into the EJB container without named configuration "test", so the invocation of CacheContainer.getCache("test") returns default cache. Injection of the Cache instance itself by the JNDI link like "java:jboss/infinispan/container/cacheContainer/test" didn't work in WL9 and here too.

What did I wrong? Is there any special trick to start Cache service with the defined configuration?

Thank you for any advice.

**Comment by pferraro** [comment]
@Maxoid This is not the appropriate place to ask support questions.  Please use the forums.

**Pull request merged**
