### PR TITLE
WFLY-15028 Move WildFly Preview to a native jakarta namespace variant…

### PR DESCRIPTION
**Pull request by chengfang**
… of the JBoss EJB Client jar

[WFLY-15028](https://issues.redhat.com/browse/WFLY-15028) Move WildFly Preview to a native jakarta namespace variant of the JBoss EJB Client jar

[WFLY-15626](https://issues.redhat.com/browse/WFLY-15626) Upgrade jboss-ejb-client from 4.0.43.Final to 4.0.44.Final

### CODE REVIEW

**Comment by bstansberry** [comment]
@chengfang This looks good. Ping me whenever you switch it to a non-SNAPSHOT and I'll make sure it gets in.

**Comment by chengfang** [comment]
@bstansberry it will take a day or two, as I'm trying the new ejb-client versions on http-client first before releasing it.

**Comment by chengfang** [comment]
It should be ready to merge now.

**Review by bstansberry — APPROVED** [review]
Merge conflict aside, looks good!

**Pull request merged**
