### PR TITLE
[WFLY-5810] Move JndiPermission to its own package & cleanroom rewrite

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
https://issues.jboss.org/browse/WFLY-5810

**Comment by bstansberry** [comment]
Since master is targeting a 10.1 and this will get merged before any move to 11.x, should the old org.jboss.as.naming.JndiPermission be kept and deprecated? As a subclass, just keeping the constructors (mapping the old Action enum to the new stuff) and perhaps the 'public static void check(Name name, Action... actions)' method.

Hmm, the Serializable stuff would break though, and keeping that is too much trouble.

**Comment by dmlloyd** [comment]
I worried a little about compatibility but I came to the conclusion that the whole reason I had to do this was because the class was unsupported in the first place.  But if you think I should try and do something with compatibility, I could probably come up with something given a little time.

**Comment by bstansberry** [comment]
Yeah, if anyone was using this class they had to have turned off or ignored the WARN logging. So now they'd have to tweak their security manager config, which is the kind of migration step the WARN was telling them about.

**Pull request merged**
