### PR TITLE
[RESTEASY-2042] Fix resteasy-jaxrs module dependencies

### PR DESCRIPTION
**Pull request by asoldano**
https://issues.jboss.org/browse/RESTEASY-2042

### CODE REVIEW

**Comment by bstansberry** [comment]
Is this optional? 

Reading the JIRA I don't understand why this is needed at all. Looking at the code in the description I don't see any MP config API involvement directly or transitively. Is there something about our mp-config subsystem integration with CDI that causes the need for it?

@jmesnil @jfdenise FYI.

**Comment by asoldano** [comment]
@bstansberry , the way the MicroprofileClientBuilder currently is implies that the dependency has to be there is the MP REST client is used. See https://github.com/resteasy/Resteasy/blob/3.6.1.Final/resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MicroprofileClientBuilder.java#L53 .

**Review by bstansberry — APPROVED** [review]
I'm crying a tiny bit.

**Comment by kabir** [comment]
@asoldano we should probably use WFLY commit ids rather than RESTEASY

**Pull request closed without merging**
