### PR TITLE
WFLY-17558 upgrade to Hibernate ORM 6.2.0.CR2

### PR DESCRIPTION
**Pull request by scottmarlow**
https://issues.redhat.com/browse/WFLY-17558

Signed-off-by: Scott Marlow <smarlow@redhat.com>

Depends on https://github.com/wildfly/wildfly/pull/16490 (Upgrade to Hibernate Commons Annotations 6.0.6.Final) being merged.

### CODE REVIEW

**Comment by scottmarlow** [comment]
I saw some test deployment failures caused by
 ```
  Suppressed: java.lang.IllegalArgumentException: Parameter 'authenticationContext' may not be null
    at org.wildfly.common.Assert.checkNotNullParamChecked(Assert.java:71)
    at org.wildfly.common.Assert.checkNotNullParam(Assert.java:49)
    at org.wildfly.security.auth.client.AuthenticationContextConfigurationClient.getAuthenticationConfiguration(AuthenticationContextConfigurationClient.java:116)
```

I'll sync with `main` after https://github.com/wildfly/wildfly/pull/16490 is merged and push again which should trigger a new test run.

**Comment by vsalbaba** [comment]
This IIUC implements https://github.com/wildfly/wildfly-proposals/pull/503

**Comment by scottmarlow** [comment]
> This IIUC implements [wildfly/wildfly-proposals#503](https://github.com/wildfly/wildfly-proposals/pull/503)

Yes this does implement [wildfly/wildfly-proposals#503](https://github.com/wildfly/wildfly-proposals/pull/503).

I'm running the Jakarta EE 10 Full Platform TCK tests tonight to see if we pass.

**Comment by scottmarlow** [comment]
The `linux-JDK 17` failure `org.jboss.as.test.clustering.cluster.web.CoarseWebFailoverTestCase.testGracefulSimpleFailover` doesn't seem related to this change.

**Comment by scottmarlow** [comment]
> 
> I'm running the Jakarta EE 10 Full Platform TCK tests tonight to see if we pass.

I'm running the Jakarta EE 10 Full Platform TCK tests again.

**Comment by scottmarlow** [comment]
> I'm running the Jakarta EE 10 Full Platform TCK tests again.

We are passing now.

**Comment by bstansberry** [comment]
Thanks @scottmarlow

**Pull request merged**
