### PR TITLE
[WFLY-13739] WeldJpaInjectionTestCase fails in the jpa layer test suite

### PR DESCRIPTION
**Pull request by yersan**
Jira issue: https://issues.redhat.com/browse/WFLY-13739

### CODE REVIEW

**Review by darranl — APPROVED** [review]

**Comment by yersan** [comment]
Closing this for further investigation. The error in a local tests is different than the error on TC.

**Comment by yersan** [comment]
retest this please

**Review by bstansberry — APPROVED** [review]
OK, so even though BV is not needed this change is needed in order to bring in CDI.

**Comment by yersan** [comment]
@bstansberry right

**Pull request merged**
