### PR TITLE
WFLY-20138 Update Weld 5 and Weld 6

### PR DESCRIPTION
**Pull request by manovotn**
JIRA - https://issues.redhat.com/browse/WFLY-20138

### CODE REVIEW

**Comment by bstansberry** [comment]
Mergers; please review CI results in #18548 before merging! (Note; if those are problematic if need be we can split out the Weld 5 part.)

**Comment by manovotn** [comment]
Sure, I can split them if need be; only kept them together because Weld 6 Final is no different from the CR2 that's already in place :)

**Comment by bstansberry** [comment]
Note: CI is wacky this week and thus the result reported in the status box are wacky too.

I'll use this to see the Team City job results for this PR:  https://ci.wildfly.org/project.html?projectId=WF_PullRequest&branch_WF_PullRequest=pull%2F18547

**Comment by bstansberry** [comment]
The results on #18548 are fine.

**Comment by bstansberry** [comment]
Thanks @manovotn

**Pull request merged**
