### PR TITLE
[WFLY-5842]: Upgrade google guava from 18 to 19.

### PR DESCRIPTION
**Pull request by langfr**
https://issues.jboss.org/browse/WFLY-5842

### CODE REVIEW

**Comment by langfr** [comment]
Retest this please.

**Comment by langfr** [comment]
retest this please

**Comment by codylerum** [comment]
:+1:

**Comment by n1hility** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by jamezp** [comment]
5th time is the charm right? retest this please

**Comment by jamezp** [comment]
I labeled this for 11 because Weld still uses 18. Holding off until 11.x just gives some more testing time.

**Comment by ctomc** [comment]
no longer needed, as weld 2.4.0 stopped using it.
PR #9185 is removing it from build all together.

**Pull request closed without merging**
