### PR TITLE
[WFLY-16119] Upgrade google guava 31.1-jre

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFLY-16119

### CODE REVIEW

**Comment by boris-unckel** [comment]
@chengfang @jasondlee @ehsavoie @jamezp @ronsigal @jimma @fl4via I have taken your names from the previous PR as reviewers. Could you please review and approve? Please find the links in the Jira.

**Review by jamezp — APPROVED** [review]
This seems fine for RESTEasy. Looking at the `com.github.fge.json-patch` module I don't think this dependency is actually required here. I'll take a closer look and file a JIRA if it's not.

**Comment by boris-unckel** [comment]
@chengfang @jasondlee @ehsavoie @ronsigal @jimma @fl4via Normally I would avoid a reminder, but Tuesday 22nd March is closing for 26.x - it would be great if you can review and approve here, to get it in the beta.

**Review by chengfang — APPROVED** [review]

**Review by fl4via — APPROVED** [review]

**Review by jasondlee — APPROVED** [review]

**Review by ehsavoie — APPROVED** [review]

**Comment by boris-unckel** [comment]
@bstansberry Could you have a look at this PR for main and the 26.x counterpart of it, please? I hope it has enough positive votes to be acceptable for the 26beta. Tests passed.

**Comment by jimma** [comment]
@boris-unckel  @bstansberry  I upgraded this version in wss4j and everything works, so this change looks good for webservice subystem.

**Pull request merged**
