### PR TITLE
JBEAP-8573: remove all ignores and assumes, OpenJDK works fine now

### PR DESCRIPTION
**Pull request by wolfc**
https://issues.jboss.org/browse/WFLY-8006
downstream: https://issues.jboss.org/browse/JBEAP-8573

### CODE REVIEW

**Comment by darranl** [comment]
This one should really be referencing a community WFLY Jira and not a product Jira.

Also can we please hold this to check with the invocation integration work.

**Comment by wolfc** [comment]
This should precede any refactoring or integration to guard against regression.

**Comment by bstansberry** [comment]
retest this please

**Review by rhusar — CHANGES_REQUESTED** [review]
Always reference upstream Jira issue in the git commit message. Please help us create sustainable software.

**Comment by darranl** [comment]
Our bulk of changes are now in - don't think this needs holding up for invocation integration work anymore.

**Pull request merged**
