### PR TITLE
WFLY-19303 EJB remote service requires capability of deprecated "cluster" attribute

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-19303

____

More information about the [wildfly-bot[bot]](https://github.com/wildfly/wildfly-github-bot)

### CODE REVIEW

**Review by rachmatowicz — APPROVED** [review]
I approve these changes.

**Comment by pferraro** [comment]
@rachmatowicz Can you give this another look?  Yesterday, I realized that the add operation handler for the subsystem resource was relying on the deprecated "cluster" attribute to resolve the Registry services used by the AssociationService.

**Comment by soul2zimate** [comment]
@rachmatowicz @tadamski could you review this ? downstream also requires this fix. Thanks.

**Comment by pferraro** [comment]
Rebased.

**Comment by pferraro** [comment]
@rachmatowicz Any other comments?  Otherwise, I'd like to get this merged.

**Pull request merged**
