### PR TITLE
[WFLY-9300] Add test for ejb security propagation using PLAIN

### PR DESCRIPTION
**Pull request by bmaxwell**
https://issues.jboss.org/browse/WFLY-9300

### CODE REVIEW

**Review by rsvoboda — CHANGES_REQUESTED** [review]
Please change log.info to log.debug, @ctomc doesn't like too much output on CI servers ;)

Looking at test scenarios it feels to me a bit optimistic, just one user & role for web / ejb. Historically there were issues (I think login modules or krb stuff) when more users with different roles hit the test deployment.
I would prefer more defensive tests with 2+ users with different roles or multiple roles per user for both ejb and web way to make sure all the things are properly propagated.

**Comment by bmaxwell** [comment]
I think I have all of the log.infos out.  There are actually 2 users with different roles.  ejbUser has ejbRole, webUser has ejb and web role.  I started some more changes to validate the roles further.

**Comment by bstansberry** [comment]
retest this please

**Comment by rsvoboda** [comment]
@bmaxwell I meant 2 web users + 2 ejb users to be sure first web/ejb authenticated user is not sharing permissions with second web/ejb user. In any case thanks for increasing the coverage!

**Comment by kabir** [comment]
@bmaxwell Closing due to inactivity on fixing this

**Comment by rpelisse** [comment]
@kabir I've rebased on behalf of @bmaxwell who appears to have not has the time to do it. I've setup a new PR that thus superseeds this [PR11527](https://github.com/wildfly/wildfly/pull/11527) .

**Pull request closed without merging**
