### PR TITLE
[WFLY-19064] Update EE 11 components to late March releases

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFLY-19064

This follows up on #17677 with TS tweaks needed to support the removal of @ManagedBean, and the component updates to more recent releases.
____

<--- THIS SECTION IS AUTOMATICALLY GENERATED BY WILDFLY GITHUB BOT. ANY MANUAL CHANGES WILL BE LOST. --->

> Wildfly issue links:
> * [WFLY-19065](https://issues.redhat.com/browse/WFLY-19065)

<--- END OF WILDFLY GITHUB BOT REPORT --->

More information about the [wildfly-bot[bot]](https://github.com/wildfly/wildfly-github-bot)

____

<--- THIS SECTION IS AUTOMATICALLY GENERATED BY WILDFLY GITHUB BOT. ANY MANUAL CHANGES WILL BE LOST. --->

> Wildfly issue links:
> * [WFLY-19184](https://issues.redhat.com/browse/WFLY-19184)

<--- END OF WILDFLY GITHUB BOT REPORT --->

### CODE REVIEW

**Review by jamezp — COMMENTED** [review]
Not that I think the categories are a bad idea, but since we moved the tests to an `ee10` directory we could do something like:
```xml
<excludes>
    <exclude>**/ee10/**</exclude>
 </excludes>
 ```
 
 Or maybe use an [`ecludesFile`](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#excludes).

**Comment by darranl** [comment]
This feels relevant for Beta so adding labels to consider.

**Comment by bstansberry** [comment]
> Not that I think the categories are a bad idea, but since we moved the tests to an `ee10` directory we could do something like:
> 
> ```
> <excludes>
>     <exclude>**/ee10/**</exclude>
>  </excludes>
> ```
> 
> Or maybe use an [`ecludesFile`](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#excludes).

The src/test/ee10/java folder isn't even visible when we're testing EE 11. And src/test/ee11/java isn't visible when we're not testing EE 11.  The build-helper-maven-plugin adds one or the other as a source dir, depending on profiles. So TestCase.java classes in one or the other don't execute. That's why the whole category thing wasn't really needed. I created those folders to hold classes that could only compile against one API or the other, but then I realized they could also hold test cases that should only execute in some conditions.

**Comment by darranl** [comment]
@jamezp you have had a look through this one, any objections to us merging so we can run CI against main?

**Comment by bstansberry** [comment]
Note that going through this one commit by commit is useful. It's mostly test-reorganization stuff that makes more sense when looked at commit by commit.

**Comment by bstansberry** [comment]
@darranl @jamezp I merged this into EE11. That's just a topic branch, so code review of it can be done via the PR merging the topic branch into main: #17784

**Pull request merged**
