### PR TITLE
[WFLY-6899] Upgrade to RESTEasy 3.1.0.Beta2

### PR DESCRIPTION
**Pull request by asoldano**
https://issues.jboss.org/browse/WFLY-6899

### CODE REVIEW

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
@asoldano The artifacts are in the CI maven repo now, so this should work.

**Comment by ctomc** [comment]
@asoldano this could probably be updated to CR1 now

**Comment by asoldano** [comment]
@ctomc I'm not spending time on upgrading this again, as it looks like this is not going to be merged. Once this is merged I'll create a new one for moving to CR1.

**Comment by asoldano** [comment]
This is superceded by https://github.com/wildfly/wildfly/pull/9252

**Pull request closed without merging**
