### PR TITLE
[WFLY-9346] IIOP: elytron capabilities refactor

### PR DESCRIPTION
**Pull request by tadamski**

### CODE REVIEW

**Comment by bstansberry** [comment]
This looks fine, but can you reference a JIRA in the commit message and PR title?

**Comment by tadamski** [comment]
Actually, there was no direct JIRA regarding this but I saw it is a necessary fix when working on WFLY-9346 so I guess I will connect it to that one.

**Comment by kabir** [comment]
@tadamski This needs a rebase

**Comment by kabir** [comment]
@tadamski Please ping `wildfly/mergers-full` when fixed, and I'll remove the fixme label

**Pull request merged**
