### PR TITLE
[WFLY-11768] Upgrade libthrift from 0.11.0 to 0.12.0.

### PR DESCRIPTION
**Pull request by jamezp**
https://issues.jboss.org/browse/WFLY-11768

This requires approval from @jmesnil or @jpkrohling. For this reason I've placed a hold on the PR.

### CODE REVIEW

**Comment by jmesnil** [comment]
[0.12.0 Release Notes](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310800&version=12339174)

**Comment by jpkrohling** [comment]
I would feel more comfortable with a positive confirmation from QE that it indeed works. We had a similar change upstream merged a couple of weeks ago:

https://github.com/jaegertracing/jaeger-client-java/pull/587

If possible, I'd rather wait for a release and bump both the Thrift and Jaeger's version.

**Comment by jstourac** [comment]
There is a bunch of tests included in WildFly testsuite that cover MP OpenTracing feature integration with WildFly [1,2]. Looking in the test job execution linked in this PR, I can see that those tests have been executed and passed. Thus the MP OpenTracing seems to be working with this PR.

Still, I guess that it is safer to wait for a version bump of `jaegertracing` dependencies that include this new version of `thrift` already. @jpkrohling for when is planned release of  jaegertracing/jaeger[core|client|thrift]? If we decided to update `jaegertracing` deps, we would have to do that quite soon as there is a freeze for WildFly this Wednesday, if I am not mistaken.

----
1. https://github.com/wildfly/wildfly/tree/master/testsuite/integration/microprofile-tck/opentracing
2. https://github.com/wildfly/wildfly/tree/master/testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/microprofile/opentracing

**Comment by jpkrohling** [comment]
True, I think we do have an e2e test ensuring a span could be reported and is available in the backend. This would be sufficient to ensure that everything is still working.

I'm not sure we have a plan for a release yet, but I think we could perform one this week. 

cc @pavolloffay

**Comment by jamezp** [comment]
Closing this as it likely needs to be integrated differently.

**Pull request closed without merging**
