### PR TITLE
[WFLY-9789] Move to RESTEasy 3.5 in a EE7 compatible way

### PR DESCRIPTION
**Pull request by asoldano**
This is a preview of the upgrade that I'm soon submitting for bringing JAX-RS 2.1 RESTEasy implementation in WildFly. I'd like the reviewers to start having a look and letting me know of any additional requirements / changes needed for merging before I tag 3.5.0.Final.
I'm dealing with the needed analysis / test plan in the mean time; besides JSR 370 (JAX-RS 2.1), the RESTEasy component upgrade also pulls few other planned new features.

Few JIRA links:
https://issues.jboss.org/browse/WFLY-9789
https://issues.jboss.org/browse/WFLY-6459
https://issues.jboss.org/browse/WFLY-9786
https://issues.jboss.org/browse/WFLY-9787

Dev analysis:
https://github.com/wildfly/wildfly-proposals/pull/16
https://github.com/wildfly/wildfly-proposals/pull/18
https://github.com/wildfly/wildfly-proposals/pull/19

Note this is related to WFLY-6460 and WFLY-7185 too.

@jamezp @n1hility @bstansberry @kabir @rsvoboda @stuartwdouglas @kanovotn

### CODE REVIEW

**Comment by jamezp** [comment]
@asoldano I'll try to get PR's together today for both the JSON-P and JSON-B too. This will likely conflict with this PR, but I do think at the least they need to be separate commits.

**Comment by kabir** [comment]
@psakar @Skullman some more upgrades for you guys, can you please check you can build it + licenses?

**Comment by marekkopecky** [comment]
Hi @kabir (cc @rsvoboda), please don't merge this PR right now, we (me and @kanovotn) need to discuss a few things about this with @asoldano on IRC before merging of this. Thanks ...

**Comment by asoldano** [comment]
@marekkopecky as said above, this is PR not meant to be merged (the resteasy dependency is CR level, not final), but for review only.

**Comment by kabir** [comment]
The 'feature' label is a signal to the mergers to do extra checks before merging. I see Jeff has also added the 'hold' label to make extra sure :)

**Comment by asoldano** [comment]
Just rebased, as there was a conflict

**Comment by rsvoboda** [comment]
@jamezp what is the estimation for JSON-P/JSON-B inclusion? Please include to your estimation needed analysis / test plan, though they could probably happen in parallel with PR creation to get feedback from TS execution and possibly from TCK run if it can be prechecked.

I see https://github.com/jboss/jboss-json-api_spec/pull/6 which looks huge :) We will need to look into it too, hopefully tomorrow

**Comment by jamezp** [comment]
@rsvoboda I was hoping by the end of this week. I need one change in our maven build plugin and a release. The plan will be to ship both JSON-P 1.0 and 1.1 with the `ee8.preview.mode` property to control which one gets loaded.

For the JMS client we'll continue to use 1.1.

For JSON-B we'll have a module that will only include a resource if the `ee8.preview.mode` is set to true.

**Comment by asoldano** [comment]
@jamezp the sooner, the better :-) The freeze is on Wednesday next week and I understand we might have to solve conflicts once your changes are in.

**Comment by rsvoboda** [comment]
@jamezp 

> For the JMS client we'll continue to use 1.1.

Even if `ee8.preview.mode` is not set ? Or you wanted to say 1.0 ? No matter if ee8 mode is enabled...

**Comment by rsvoboda** [comment]
@wildfly/mergers-full where should be tests for EE8 features placed in the TS?
As special property is needed will be there ee8 module for all that stuff?
Or is there different plan?

If there will be ee8 module in TS it makes sense to move those tests to "proper" modules once WF is EE8 compliant.

**Comment by jamezp** [comment]
@rsvoboda Since the JMS client is just a packaged/shaded JAR we don't really have a choice other than to pick one version. I'm choosing 1.0 only because that's what the artemis client currently uses.

**Comment by rsvoboda** [comment]
@asoldano seems https://github.com/jboss/jboss-javaee-specs/blob/master/pom.xml#L81 and https://github.com/jboss/jboss-javaee-specs/blob/master/jboss-javaee-web/pom.xml#L123 will need to be upgraded to reference 2.1

**Pull request closed without merging**
