### PR TITLE
[WFLY-12608] Integration tests for OCSP followup

### PR DESCRIPTION
**Pull request by jstourac**
https://issues.jboss.org/browse/WFLY-12608

Followup integration tests for OCSP feature into WildFly testsuite to comply with the feature test-plan.

Note: to pass all tests in this PR, this issue has to be resolved first and integrated into wildfly-core and WildFly itself - https://issues.jboss.org/browse/ELY-1874

Please make sure your PR meets the following requirements:
- [x] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue(s)
- [x] Pull Request contains description of the issue(s)
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

### CODE REVIEW

**Comment by darranl** [comment]
Retest this please

**Comment by yersan** [comment]
Retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by darranl** [comment]
Just waiting for CI to kick off again, going to provisionally add the 20.x label but if it doesn't pass CI may need to retract it.

**Comment by darranl** [comment]
Five of the failed jobs are left over from prior CI configurations.

**Comment by bstansberry** [comment]
This seems to produce test failures pretty often, e.g. https://ci.wildfly.org/viewLog.html?buildId=206005&tab=buildResultsDiv&buildTypeId=WF_PullRequest_WindowsJdk11&branch_WF_PullRequest=pull%2F13307

**Comment by darranl** [comment]
@jstourac Are you able to have a look at the failing tests?  We may be able to get this included for WildFly 20.

**Comment by jstourac** [comment]
@darranl sorry that I abandoned this MR for so long. I'll find some time to check and fix current failures next week, is it okay for you?

**Comment by darranl** [comment]
Thank you @jstourac if you do manage to I think we can still get this into WildFly 20 as it is test cases only - then no more pings on the PR ;-)

**Comment by jstourac** [comment]
@darranl, @bstansberry, I've rebased this one and pushed a small fix that caused failures on Windows platform. Based on the test runs, it is okay now as OCSP tests passed successfully.

Not sure about the failed test on Windows JDK11 platform - I believe that my changes has nothing to do with its failure. Let me know if you suspect I am wrong.

Hope it is still possible to make this into WildFly 20 release.

**Comment by jstourac** [comment]
@darranl, @bstansberry, is this possible to push forward? shall I rebase and re-test?

**Comment by darranl** [comment]
There is no merge conflict, please do not rebase.  At the time of merging we will likely bundle with other PRs for a full round of CI.

**Review by darranl — APPROVED** [review]

**Pull request merged**
