### PR TITLE
[WFLY-17773] Eliminate the transitive BouncyCastle dependency which was pulling in an older version.

### PR DESCRIPTION
**Pull request by darranl**
https://issues.redhat.com/browse/WFLY-17773
https://issues.redhat.com/browse/WFLY-17775

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]
@darranl LGTM.

A side question is why org.jboss.as.test.integration.logging.syslogserver is in testsuite/shared as it seems like only ts/int/elytron uses it. And TBH I'm not sure ts/int/elytron uses it as I can't find any use of it via simple IDEA usage search techniques. I suspect that package may be cruft, with the stuff from core's testsuite/shared being all that's used these days.

**Comment by darranl** [comment]
TBH I didn't look I was more focused on the dependencies and compilation error, it does however sound like something only applicable to core.

**Review by jamezp — APPROVED** [review]

**Comment by bstansberry** [comment]
RE that package, I filed https://issues.redhat.com/browse/WFLY-17790.

**Comment by bstansberry** [comment]
Thanks @darranl and @jamezp

**Pull request merged**
