### PR TITLE
[WFLY-19607] Upgrade to Hibernate ORM 6.4.10.Final release

### PR DESCRIPTION
**Pull request by simkam**
https://issues.redhat.com/browse/WFLY-19607

https://github.com/hibernate/hibernate-orm/compare/6.4.4..6.4.10

### CODE REVIEW

**Comment by simkam** [comment]
@scottmarlow can you please review?

**Review by scottmarlow — APPROVED** [review]

**Comment by scottmarlow** [comment]
looks good to me pending testing completing successfully.

**Comment by bstansberry** [comment]
I restarted the Cloud Test -- that was the known issue discussed starting at https://wildfly.zulipchat.com/#narrow/stream/174184-wildfly-developers/topic/Cloud.20Test.20failures/near/456711214

@simkam @scottmarlow Are there other upgrades we could do along with this, e.g H2 or bytebuddy?

I ask because we usually align our version of those, maybe others, with whatever was used in the ORM release we use. So ORM upgrades are the time to check on those.

**Comment by scottmarlow** [comment]
> I restarted the Cloud Test -- that was the known issue discussed starting at https://wildfly.zulipchat.com/#narrow/stream/174184-wildfly-developers/topic/Cloud.20Test.20failures/near/456711214
> 
> @simkam @scottmarlow Are there other upgrades we could do along with this, e.g H2 or bytebuddy?

No, we are using the same H2, bytebuddy, and other artifacts that I checked as well.

> 
> I ask because we usually align our version of those, maybe others, with whatever was used in the ORM release we use. So ORM upgrades are the time to check on those.

**Comment by bstansberry** [comment]
Thanks @simkam and @scottmarlow

**Pull request merged**
