### PR TITLE
Ignore SingletonDeploymentDescriptorTestCase as it is failing intermi…

### PR DESCRIPTION
**Pull request by ctomc**
…ttently

@pferraro this is pretty much failing almost every time

### CODE REVIEW

**Comment by pferraro** [comment]
Don't disable tests without an associated jira!

**Comment by jamezp** [comment]
Putting a hold on this for now as we don need a JIRA, but @pferraro also said he'll be submitting a fix for it soon.

**Comment by ctomc** [comment]
@pferraro as per latest guidelines [1], that is up to component lead that test is related to, not the PR submitter.

> intermittent tests should be disabled immediately by anyone that is impacted by them (reviewers, contributors, whoever). To do this, a simple short independent PR should be sent in, and a note should be left in a comment to the component lead of the area tested (using github’s super cool @user syntax). The component lead can then act on the message and choose whether to open and assign a JIRA to have it fixed, to ignore it, to delete it, to rewrite, etc. The intention is that the process of disabling an intermittent test should be as minimal effort as possible.



http://lists.jboss.org/pipermail/wildfly-dev/2015-July/004246.html

**Comment by bstansberry** [comment]
Fix was merged.

**Pull request closed without merging**
