### PR TITLE
[WFLY-14815] Fix ForwardedHandlerTestCase to comply with UNDERTOW-1837

### PR DESCRIPTION
**Pull request by fl4via**
Jira: https://issues.redhat.com/browse/WFLY-14815

This is the second part of the fix required to make ForwardedHandlerTestCase compliant with UNDERTOW-1837.
The first part is #14314 
Requires upgrade of WildFly Core with Undertow upgrade: https://github.com/wildfly/wildfly-core/pull/4604

### CODE REVIEW

**Comment by bstansberry** [comment]
I'm going to kill the CI jobs on this as we know the tests won't pass yet.

**Comment by spyrkob** [comment]
@fl4via should the expected values be set to something like 
```
final InetAddress address = InetAddress.getByName(url.getHost());
final String localAddrName = address.getHostName();
final String localAddr = address.getHostAddress() + ":" + url.getPort();
``` 
to get the values of address server is bound to?

**Comment by fl4via** [comment]
@spyrkob possibly, I'm going to give it a try.

**Comment by spyrkob** [comment]
The SM testsuite fails because resolving hostname requires SocketPermission(host, "resolve")). Since that's expected behaviour is it OK to just add the permission to the test deployment?

**Comment by bstansberry** [comment]
@spyrkob @fl4via Yes, adding the permission to the deployment is the correct thing to do.

**Comment by fl4via** [comment]
@spyrkob  thanks for your commit! @bstansberry I hope the tests will pass now :-)

**Pull request merged**
