### PR TITLE
[WFLY-17324] Add documentation for the new wildfly.elytron.oidc.allow.query.params system property

### PR DESCRIPTION
**Pull request by fjuma**
https://issues.redhat.com/browse/WFLY-19314

Upstream PR: https://github.com/wildfly/wildfly/pull/17865
Depends on https://github.com/wildfly/wildfly-core/pull/6002

____

<--- THIS SECTION IS AUTOMATICALLY GENERATED BY WILDFLY GITHUB BOT. ANY MANUAL CHANGES WILL BE LOST. --->

> Wildfly issue links:
> * [WFLY-17324](https://issues.redhat.com/browse/WFLY-17324)

<--- END OF WILDFLY GITHUB BOT REPORT --->

More information about the [wildfly-bot[bot]](https://github.com/wildfly/wildfly-github-bot)

### CODE REVIEW

**Comment by bstansberry** [comment]
@fjuma if you want to update the WildFly 32 docs please send a PR to https://github.com/wildfly/wildfly.github.io.

If you then want to update the 32.x branch here to have it be consistent, that's fine, but updating here and not there doesn't do much.

**Comment by fjuma** [comment]
Thanks @bstansberry!

@PrarthonaPaul has submitted a wildfly.github.io PR for this here (thanks very much @PrarthonaPaul):

https://github.com/wildfly/wildfly.github.io/pull/77

**Comment by bstansberry** [comment]
Thanks @fjuma . As I commented on https://github.com/wildfly/wildfly.github.io/pull/77, if the change is only applicable to 32.0.1 the 32.x docs should state that.

**Comment by bstansberry** [comment]
@fjuma This is out of sync a bit with what got merged into wildfly.github.io, so I'm going to close it. If you still want to get this into the 32.x branch, please update and re-open.

**Pull request closed without merging**
