### PR TITLE
[WFLY-5978] Upgrade Artemis 1.1.0.wildfly-011

### PR DESCRIPTION
**Pull request by jmesnil**
JIRA: https://issues.jboss.org/browse/WFLY-5978

### CODE REVIEW

**Comment by jmesnil** [comment]
fyi, the diff to previous 1.1.0.wildfly-010 release https://github.com/rh-messaging/jboss-activemq-artemis/compare/1.1.0.wildfly-010...rh-messaging:1.1.0.wildfly-011

**Comment by jmesnil** [comment]
failure is not related to the PR

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Pull request merged**
