### PR TITLE
Eliminate duplicated code in catch blocks of the LazyConnectionContextSelector.java

### PR DESCRIPTION
**Pull request by alexVengrovsk**

### CODE REVIEW

**Comment by alexVengrovsk** [comment]
I don't know

**Comment by ctomc** [comment]
this is ok to test

**Comment by bstansberry** [comment]
Thanks for the contribution. We require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to the these terms?

**Comment by alexVengrovsk** [comment]
@bstansberry I read the MIT License agreament. I agree to these terms.

**Pull request merged**
