### PR TITLE
[WFLY-13953] Upgrade WildFly Arquillian to 3.0.1.Final

### PR DESCRIPTION
**Pull request by jamezp**
https://issues.redhat.com/browse/WFLY-13953

This includes #13639. This also may require a new JIRA.

### CODE REVIEW

**Comment by bstansberry** [comment]
@jamezp Needs a rebase. We should probably get this in fairly soon so it bakes.

**Comment by bstansberry** [comment]
@jamezp Is there any reason not to move forward with this?

**Comment by jamezp** [comment]
Other thank I forgot about it? Nope :)

**Pull request merged**
