### PR TITLE
WFLY-10173 Fix EjbInvocationStatisticsTestCase#testSingletonWaitTime …

### PR DESCRIPTION
**Pull request by chengfang**
JIRA: https://issues.redhat.com/browse/WFLY-10173

This should fix the intermitten test failure `EjbInvocationStatisticsTestCase#testSingletonWaitTime`

### CODE REVIEW

**Comment by chengfang** [comment]
Windows JDK11 job has 1 failure in Artemis/jms: `ReplicatedFailoverTestCase.testBackupFailoverAfterFailback`, which is not related to my changes. Will re-run this job.

**Review by bstansberry — DISMISSED** [review]

**Comment by chengfang** [comment]
`EjbInvocationStatisticsTestCase#testSingletonWaitTime` test failed on Windows JDK11 job.  Will look into it.

**Comment by bstansberry** [comment]
@chengfang Perhaps something like the "Example" at https://openejb.apache.org/examples-trunk/access-timeout/?

What you have here is conceptually pretty similar though.

**Comment by chengfang** [comment]
I tried the above sample way of testing wait time, but didn't seem to work consistently. WF thread scheduling is undeterminstic and has a tendency to minimize context switching. Now I'm trying some mix of competing timer and method invocations, which theoretically should guarantee a postive wait time for business method invocations.

**Comment by chengfang** [comment]
Windows JDK11 job has 2 test failures (unrelated): `eap710.DomainHostExcludes710TestCase` and `DomainHostExcludes700TestCase.test003PostBootUpdates`.  Will rerun this build.

**Comment by chengfang** [comment]
Windows JDK11 failed again with 2 unrelated tests:

MissingClosingTagTestCase.commentIsNotClosed:
```
java.nio.file.FileSystemException: 
C:\BuildAgent\work\f5da3564a57e9d74\testsuite\integration\vdx\target\wildfly\standalone\log\server.log: The process cannot access the file because it is being used by another process.
at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274)
at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
at java.base/java.nio.file.Files.delete(Files.java:1141)
at org.wildfly.test.integration.vdx.TestBase.archiveServerLogAndDeleteIt(TestBase.java:91)
at org.wildfly.test.integration.vdx.TestBase.tearDown(TestBase.java:71)
```

eap720.MixedDomainDeployment720TestCase:
```
[ERROR] org.jboss.as.test.integration.domain.mixed.eap720.MixedDomainDeployment720TestCase  Time elapsed: 120.548 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Could not start container
    at org.jboss.as.test.integration.domain.mixed.MixedDomainTestSuite.getSupport(MixedDomainTestSuite.java:161)
    at org.jboss.as.test.integration.domain.mixed.MixedDomainTestSuite.getSupport(MixedDomainTestSuite.java:133)
    at org.jboss.as.test.integration.domain.mixed.MixedDomainTestSuite.getSupport(MixedDomainTestSuite.java:78)
    at org.jboss.as.test.integration.domain.mixed.MixedDomainTestSuite.getSupport(MixedDomainTestSuite.java:68)
    at org.jboss.as.test.integration.domain.mixed.eap720.MixedDomain720TestSuite.initializeDomain(MixedDomain720TestSuite.java:44)
    at org.jboss.as.test.integration.domain.mixed.eap720.MixedDomainDeployment720TestCase.beforeClass(MixedDomainDeployment720TestCase.java:38)
Caused by: java.util.concurrent.TimeoutException: HostController was not started within [120] seconds
    at org.jboss.as.test.integration.domain.management.util.DomainLifecycleUtil.awaitHostController(DomainLifecycleUtil.java:599)
    at org.jboss.as.test.integration.domain.management.util.DomainLifecycleUtil.awaitHostController(DomainLifecycleUtil.java:573)
    at org.jboss.as.test.integration.domain.management.util.DomainLifecycleUtil.start(DomainLifecycleUtil.java:288)

    
```

**Comment by chengfang** [comment]
Windows JDK11 failed again with unrelated test failure: `BulkheadAsynchTest.testBulkheadExceptionThrownWhenQueueFullAsync`.

**Comment by rhusar** [comment]
@chengfang Regarding the MP FT failure I have opened https://github.com/smallrye/smallrye-fault-tolerance/issues/244 - though this appears the only time it failed.

**Comment by rhusar** [comment]
@chengfang Can you kick in multiple runs on the CI to make sure with reasonable level of confidence that the intermittent failure is indeed fixed?

**Comment by chengfang** [comment]
Retest this please.

**Comment by chengfang** [comment]
> @chengfang Can you kick in multiple runs on the CI to make sure with reasonable level of confidence that the intermittent failure is indeed fixed? (I would but I am not sure which job reproduces this the most which I assume you would know).

Sure, I just restarted all jobs for this PR.

**Comment by rhusar** [comment]
Just FYI I have opened https://issues.redhat.com/browse/WFLY-13569 to deal with the failure mentioned in https://github.com/wildfly/wildfly/pull/13346#issuecomment-640089784

**Comment by chengfang** [comment]
2 jobs failed with unrelated tests:

Linux with sec JDK8 failed with:
SingletonDeploymentJBossAllTestCase.test
```
    java.lang.AssertionError: expected:<200> but was:<404>
06:49:34
    	at org.junit.Assert.fail(Assert.java:88)
06:49:34
    	at org.junit.Assert.failNotEquals(Assert.java:834)
06:49:34
    	at org.junit.Assert.assertEquals(Assert.java:645)
06:49:34
    	at org.junit.Assert.assertEquals(Assert.java:631)
06:49:34
    	at org.jboss.as.test.clustering.cluster.singleton.SingletonDeploymentTestCase.test(SingletonDeploymentTestCase.java:127)
```

Windows JDK11 failed with 422 failures (all unrelated)

I will rerun these 2 builds.

**Comment by chengfang** [comment]
All CI jobs passed. So with my latest fix, the test in question (`EjbInvocationStatisticsTestCase#testSingletonWaitTime`) has always passed during all these rounds of CI jobs.

**Pull request merged**
