### PR TITLE
[WFCORE-2805] Use Xalan from JRE rather than our own fork

### PR DESCRIPTION
**Pull request by ppalaga**
https://issues.jboss.org/browse/WFCORE-2805

### CODE REVIEW

**Comment by heiko-braun** [comment]
@ppalaga I'd very much interested in the outcome of this.  Is it likely that you find the time rebase and verify this PR in the near future?

**Comment by ctomc** [comment]
@heiko-braun this PR is just maybe 50% of work, to completly move to jdk provided jaxp impls changes need to be done at least to also wildfy-core & jboss-modules.
One of the problems we found later on when we tried that some time ago https://github.com/jboss-modules/jboss-modules/pull/68 is that problems are in not-so-common xml related components.
such as saaj, jax-ws and others. and there ware at the time no feasable solutions possible.

**Comment by ppalaga** [comment]
@heiko-braun any further steps here and in the dependency PR https://github.com/wildfly/wildfly-core/pull/2551 were put on hold by @n1hility . 

@ctomc note that the present PR is related solely to Xalan. As long as my knowledge reaches, Xalan can be removed. The points you made about saaj & Co are rather related to Xerces and I agree that the situation there is indeed very complicated there.

**Comment by kabir** [comment]
@ppalaga As this pull request has  been held up for a long time, I am closing it to get the pull request queue under control again. Since this is very old now, it will be a very long time until this one will be addressed. Also, I don't have much time to spend on this to evaluate on a case by case basis.

If this is something important to you or the project please feel free to recreate the pull request. That way it will come on top of the pile again, and be looked at again sooner. 

If it is a new **feature**, please follow the new process for features. Ping @kabir or @jamez if you are unsure what this means, and we can help. Please do that before opening the pull request though.

Sorry for any inconvenience!

**Comment by ppalaga** [comment]
cc @wolfc

**Pull request closed without merging**
