### PR TITLE
WFLY-15391 Update observability module with a dependency on wildfly-elytron to use individual modules

### PR DESCRIPTION
**Pull request by parsharma**
Issue: https://issues.redhat.com/browse/WFLY-15391

### CODE REVIEW

**Comment by bstansberry** [comment]
@jasondlee Please review

**Review by jasondlee — APPROVED** [review]

**Comment by jasondlee** [comment]
It looks good, but, just to make sure I understand, this is just narrowing down the scope of the dependency?

**Comment by parsharma** [comment]
Yes, @jasondlee. Instead of using the whole elytron dependency, we can use an individual module.

**Review by yersan — COMMENTED** [review]
This is reducing the needed dependencies at build time, and indeed can be done for runtime as well. The `org.wildfly.extension.opentelemetry-api`JBoss Modules module can also be narrowed down and use `org.wildfly.security.manager` instead of `org.wildfly.security.elytron`. `org.wildfly.extension.opentelemetry` looks fine.

**Review by jasondlee — APPROVED** [review]

**Pull request merged**
