### PR TITLE
[WFLY-18763] Add an example standalone-core-microprofile.xml example configuration.

### PR DESCRIPTION
**Pull request by jamezp**
https://issues.redhat.com/browse/WFLY-18763

### CODE REVIEW

**Review by bstansberry — CHANGES_REQUESTED** [review]
@jamezp This package should be in galleon-pack/galleon-shared, not galleon-local. Otherwise it will not be included in the wildfly-preview feature pack.

**Comment by bstansberry** [comment]
Replying to myself -- no it shouldn't be in galleon-shared because the wildfly-preview FP itself has the same package with its own WFP-specific tasks.xml file. So the fix is to duplicate the tasks.xml 'config' element into the WFP file.

**Review by bstansberry — APPROVED** [review]

**Comment by darranl** [comment]
@jamezp The test failure looks related

**Comment by jamezp** [comment]
@darranl It was indeed. This should fix it https://github.com/wildfly/wildfly/pull/17420/files#diff-56647cdad56f631ce6554abcb6ab804f04f61cabed523e74b29d1b6c996dafcdR334-R336

**Pull request merged**
