### PR TITLE
[WFLY-15463]:  End transformation of messaging components during buil…

### PR DESCRIPTION
**Pull request by ehsavoie**
…d and use of the wildfly-preview feature pack.

 * Using the new internal module for json provided through WFCORE-5590.
 * Excluding artemis artefacts from transformation.

Jira: https://issues.redhat.com/browse/WFLY-15463
Related Jira: https://issues.redhat.com/browse/WFCORE-5590

Requires https://github.com/wildfly/wildfly-core/pull/4882

### CODE REVIEW

**Comment by darranl** [comment]
Just running CI - should we have the core upgrade in now?

**Comment by ehsavoie** [comment]
@darranl I don't think this is required as the required core PR wasn't merged

**Comment by darranl** [comment]
@ehsavoie Are you saying we don't need the changed in core?

FYI I have added the rebase label as this has a conflict but I am just bundling up another batch which may lead to more conflicts,

**Comment by ehsavoie** [comment]
@darranl no, that the current core release doesn't have the code update required.

**Comment by bstansberry** [comment]
@ehsavoie I'm going to close this as I think your other PR might have already handled this.

**Comment by ehsavoie** [comment]
@bstansberry I disagree :) I have updated the PR to remove even more transformation

**Pull request merged**
