### PR TITLE
[WFLY-9403] Tests if clusered EJB deployment deployed on mixed domain is successfully deployed

### PR DESCRIPTION
**Pull request by yersan**
Additional tests for mixed domain and clustered EJB application
cc: @dcihak 

Jira issue: https://issues.jboss.org/browse/WFLY-9403

### CODE REVIEW

**Review by dcihak — APPROVED** [review]
Looks OK, thanks.

**Comment by bstansberry** [comment]
This is ok because I figure we're in a rush, but in the future I'd much prefer that we prove the transformation in the subsystem test suite, which is far cheaper than expensive integration tests.

**Comment by yersan** [comment]
I do not get this error in my local tests, but it seems related to this PR. I'm checking it.

**Comment by yersan** [comment]
Retest this please

**Comment by istudens** [comment]
The test is failing. It is not going to be merged downstream.

**Comment by yersan** [comment]
Closed, fix was already merged into downstream. Integration test is still pending but I'm closing this PR due to previous comments; not in a rush and expensive test for this issue.
See downstream issue for more details: https://issues.jboss.org/browse/JBEAP-13295

**Pull request closed without merging**
