### PR TITLE
WFLY-13044: fix extension matching in security constraints

### PR DESCRIPTION
**Pull request by michpetrov**
Issue: [WFLY-13044](https://issues.redhat.com/browse/WFLY-13044)

### CODE REVIEW

**Comment by bstansberry** [comment]
This PatternInfo class looks like an excellent candidate for some unit testing. It's static and package protected so a test class can easily manipulate instances of it.

**Comment by darranl** [comment]
@michpetrov The last comment was regarding adding some testing, is that something you can add to this PR?

**Comment by michpetrov** [comment]
@darranl I can add a test for the affected method but I don't feel confident about testing the entire class.

**Comment by bstansberry** [comment]
@michpetrov That's fine. The most important thing is demonstrating the bug, and then other scenarios for the method.  I read the JIRA and then saw the fix and without doing a lot of analysis I have no clue if it's right, wrong, other effects it might have etc. It seemed like a unit test with some simple comments explaining the cases being tested would solve that.

**Review by bstansberry — APPROVED** [review]
Great; thanks @michpetrov !

**Comment by bstansberry** [comment]
Thanks, @michpetrov

**Pull request merged**
