### PR TITLE
[WFLY-2102] Sanitizing name resource for env and adding warning log

### PR DESCRIPTION
**Pull request by lvydra**
Sanitizing name prefixed with a '/' and logging warning message

Issue: https://issues.redhat.com/browse/WFLY-2102

### CODE REVIEW

**Comment by bstansberry** [comment]
this is ok to test

**Comment by bstansberry** [comment]
@emmartins Please review.

**Comment by darranl** [comment]
@emmartins Are you able to provide the requested review on this PR?  This looks like if approved it should be fairly straightforward to merge to get it out of the queue and into WildFly.

**Comment by darranl** [comment]
FYI also kicked off CI again to double check we are Ok there.

**Comment by emmartins** [comment]
@darranl @bstansberry the patch looks ok, just not sure if the issue should be solved like this, silently (fix the env/ concat to name without warning), or continue to fail with a better error msg. May be worth to re-check specs and how RI handles such names, I'm not currently naming comp leader but can do it, may take some time tho... Thoughts?

**Comment by emmartins** [comment]
Thinking a bit more on it, if opting for this new behaviour, it would be preferable performance wise to address the issue when env/ is added to the name string

**Comment by lvydra** [comment]
@emmartins  Hi, OK, I will modify it accordingly. Thank you

**Comment by lvydra** [comment]
Cc @emmartins

**Comment by emmartins** [comment]
@lvydra @darranl @bstansberry LGTM

**Comment by bstansberry** [comment]
Thanks, @lvydra !

**Pull request merged**
