### PR TITLE
[WFLY-12125] Integration test for PLINK-793

### PR DESCRIPTION
**Pull request by tmiyargi**
Issue: https://issues.jboss.org/browse/WFLY-12125

Related Issues: https://issues.jboss.org/browse/PLINK-793, https://issues.jboss.org/browse/WFLY-12111

This is blocked by Picketlink update

### CODE REVIEW

**Comment by bstansberry** [comment]
@tmiyargi perhaps these failures are because the CI runs use -Dipv6 to force IPv6 testing? When tests fail globally like this that's often the problem, as before sending up the PR the dev typically ran the test locally using IPv4 and it passed.

**Comment by tmiyargi** [comment]
@Brian It fails because it depends on Picketlink update, not sure how you want to proceed with this, maybe just close as I'm not sure you will update Picketlink anymore

**Comment by bstansberry** [comment]
@tmiyargi When the update is available, please combine that commit into this PR or this commit into its PR and ping me or James or any of the mergers.

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
I'm not sure but I think the Picketlink version WF is now using has this fix so I'm removing the 'hold' label.

**Pull request merged**
