### PR TITLE
[WFLY-18406] Upgrade ironjacamar to 3.0.6.Final

### PR DESCRIPTION
**Pull request by tadamski**
https://issues.redhat.com/browse/WFLY-18406

Upgrade because of refactor in IronJacamar which removes usage on jboss-threads blocking API

### CODE REVIEW

**Comment by tadamski** [comment]
@bstansberry ok, I will make some notes about it in my docs

**Comment by bstansberry** [comment]
@tadamski It looks like it was the GH actions that were affected by the artifact not being available when they ran. It looks like  the TeamCity jobs had lots of ordinary test failures.

**Pull request merged**
