### PR TITLE
[WFLY-14968] Collapse if-statements (Connector)

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFLY-14968

### CODE REVIEW

**Comment by boris-unckel** [comment]
Please review/approve/merge [https://github.com/wildfly/wildfly/pull/14450](https://github.com/wildfly/wildfly/pull/14450) first. I expect a merge conflict and have fixed version already prepared.

**Comment by boris-unckel** [comment]
Hello @tadamski tests passed for this PR. Could you review and approve, please?

**Review by tadamski — APPROVED** [review]

**Comment by tadamski** [comment]
LGTM, thanks

**Comment by boris-unckel** [comment]
Good Morning @bstansberry another one of the series is tested and approved. Could you check and merge, please?

**Pull request merged**
