### PR TITLE
[WFLY-18544] managed deployment in content repository duplicated in tmp/vfs/temp directory

### PR DESCRIPTION
**Pull request by gaol**
Issue: https://issues.redhat.com/browse/WFLY-18544

This PR needs https://github.com/wildfly/wildfly-core/pull/5689 to pass, so I am making it as a draft PR for the moment.

Updated: the wildfly-core pr has been merged, and wildfly-core has been upgraded, so this PR is ready for review and merge

### CODE REVIEW

**Comment by gaol** [comment]
@bstansberry @fl4via @tadamski would any of you please review? thanks :)

**Comment by gaol** [comment]
@bstansberry can we merge this if it is OK for you ? the downstream one needs it, thanks :)

**Comment by bstansberry** [comment]
Thanks @gaol

**Pull request merged**
