### PR TITLE
[WFLY-9538] support for -secmgr replaces old flag

### PR DESCRIPTION
**Pull request by rsearls**

### CODE REVIEW

**Comment by rsearls** [comment]
retest this please

**Comment by rsearls** [comment]
This is consistently failing on Linux only and on clustering test, SingletonPartitionTestCase.  As far an I can tell this test has no interaction with utility wsproduce.sh.

**Comment by asoldano** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Pull request merged**
