### PR TITLE
WFLY-13167 Upgrade JGroups to 4.2.0.Final

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-13167

### CODE REVIEW

**Comment by luck3y** [comment]
retest this please

**Comment by rhusar** [comment]
retest this please

**Comment by pferraro** [comment]
The above jobs have indeed finished (successfully).  Not sure why they are not reporting as such.

**Comment by luck3y** [comment]
> The above jobs have indeed finished (successfully). Not sure why they are not reporting as such.

@pferraro We had an issue with one of the status reporters failing on some PRs at the end of last week, so they were all switched to the one that works more reliably. If you scroll down on the job list you'll see those jobs have completed. Theres no way to remove the previous ones though.

Note that this will only apply to a handful of PRs, new ones will only have the new job status on them.

**Comment by bstansberry** [comment]
Here are the actual results:

https://ci.wildfly.org/project.html?projectId=WF_PullRequest&branch_WF_PullRequest=pull%2F13054

All passed.

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
