### PR TITLE
[WFLY-13003] Add SameSiteCookieHandler test

### PR DESCRIPTION
**Pull request by fl4via**
Jira: https://issues.redhat.com/browse/WFLY-13003

master PR: https://github.com/wildfly/wildfly/pull/13239

This requires Undertow 2.1.0.Final: https://issues.redhat.com/browse/WFCORE-4934

### CODE REVIEW

**Review by jstourac — COMMENTED** [review]
I've added just a comment regarding the missing license header. It LGTM otherwise.

**Comment by jmesnil** [comment]
This can be tested with #13250 that contains the WildFly Core upgrade for WildFly 19.0.x

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
retest this please

**Comment by jamezp** [comment]
retest this please

**Pull request merged**
