### PR TITLE
[WFLY-15204] Updating JAXP error log processing tests to be JAXP implementation independent

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-15204

### CODE REVIEW

**Comment by darranl** [comment]
Sorry @ropalka a rebase is needed on this one.

**Comment by ropalka** [comment]
Fixed @darranl

**Comment by ropalka** [comment]
@bstansberry , please review this one too, please.

**Comment by jmesnil** [comment]
@ropalka Hi, this PR is causing issue for the release of WildFly Core 18.0.0.Beta1. The XSD is bumped to `{urn:jboss:domain:19.0}` in https://github.com/wildfly/wildfly-core/pull/4785 and this makes this test fail.

Are the assertions `assertContains(errorLog, "'{urn:jboss:domain:18.0}unexpectedElement' encountered");` really necessary?

**Comment by ropalka** [comment]
No, it isn't @jmesnil

**Comment by jmesnil** [comment]
I opened #14760 to update the assertions

**Pull request merged**
