### PR TITLE
WFLY-14698 Caching of managed beans in WebInjectionContainer can cause memory leaks in distributed JSF applications following session timeout

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-14698

### CODE REVIEW

**Comment by pferraro** [comment]
@bstansberry Please review.  This mostly affects the EE component.

**Comment by bstansberry** [comment]
@pferraro Could you post on the JIRA a brief description of the concept behind the fix? Thanks.

One question to answer there is why SimpleWebInjectionContainer is appropriate for the distributable use case but isn't appropriate in general.  Is that just a matter of being careful and limiting the change to the use case that exhibits the bug? Or perhaps it's the caching container would be more performant (map lookup vs component creation), so use that if possible?

**Comment by pferraro** [comment]
@bstansberry See https://issues.redhat.com/browse/WFLY-14698?focusedCommentId=16055482&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16055482

**Comment by bstansberry** [comment]
Thanks, Paul!

**Comment by bstansberry** [comment]
@pferraro LGTM

**Comment by pferraro** [comment]
@fl4via @fjuma Any comments/feedback?

**Review by fjuma — APPROVED** [review]

**Pull request merged**
