### PR TITLE
[WFLY-13844] Upgrade jboss-ejb-client to 4.0.34.Final

### PR DESCRIPTION
**Pull request by tadamski**
https://issues.redhat.com/browse/WFLY-13844

https://github.com/wildfly/jboss-ejb-client/compare/4.0.33.Final...4.0.34.Final

### CODE REVIEW

**Comment by chengfang** [comment]
Many failures due to execution timeout. Will rerun them.

**Comment by darranl** [comment]
@chengfang / @tadamski It looks like CI failed again, is anyone checking if these failures are reproducible locally?  I can kick off CI again if needed but as we are in feature freeze week CI becomes very overloaded.

**Comment by chengfang** [comment]
@darranl I was looking into these failures and they look real (about 145 failures, pretty consistent in 3 rounds). Will try to narrow it down.

**Comment by bstansberry** [comment]
@chengfang Did you discover anything? This PR seems to be passing now, but I remember in the past I thought the failures were relevant looking too. But it seems fine now. 

CI was quite overloaded for about a week so odds are decent that was it. I'll run this again and if it's ok and none of us having any specific thought on something wrong we can merge it Monday.

**Comment by chengfang** [comment]
@bstansberry that sounds good. I tried a couple of failed tests locally but couldn't reproduce it. Nothing obvious stands out.

**Comment by bstansberry** [comment]
Superseded by #13603

**Pull request closed without merging**
