### PR TITLE
WFLY-9413 remove unneeded asm/javassist dependencies from eclipselinkmodule, in support of upgrading asm

### PR DESCRIPTION
**Pull request by scottmarlow**

### CODE REVIEW

**Comment by bstansberry** [comment]
@scottmarlow Should this be independent of WFLY-9406? That JIRA is about doing a component upgrade, one that might not be the right thing to do for reasons unrelated to this change. Should these dependencies should be removed regardless of what ASM version is used elsewhere?

**Comment by scottmarlow** [comment]
@bstansberry good point, I'll separate this pr into a different jira.

**Comment by scottmarlow** [comment]
Thanks @bstansberry, just added https://issues.jboss.org/browse/WFLY-9413 to track removing asm/javassist dependencies from the EclipseLink persistence provider module.

**Comment by scottmarlow** [comment]
The TLSSyslogAuditLogTestCase.testFailedAuthWrongPassword failure doesn't seem related to this pull request:
  java.lang.AssertionError: Failed authentication with wrong password was not logged

**Comment by bstansberry** [comment]
@scottmarlow Great. Can you update the title of this PR and the commit message?

That TLSSyslogAuditLogTestCase.testFailedAuthWrongPassword  fails intermittently, so don't worry about it.

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
