### PR TITLE
[WFLY-14754] Upgrade ASM to 9.1

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFLY-14754

### CODE REVIEW

**Review by ropalka — APPROVED** [review]
LGTM

**Comment by bstansberry** [comment]
@scottmarlow WDYT?

**Comment by scottmarlow** [comment]
Test results look good!

Dependencies on asm.asm module in WildFly appear to be:

1. io/smallrye/config/main/module.xml - Does anyone else need to review this dependency?
2. net/bytebuddy/main/byte-buddy-1.9.11.jar - ByteBuddy has its own shaded copy of ASM (https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.10.21 contains JDK11 support but Hibernate ORM still uses ByteBuddy 1.9.11).
3. org/jboss/as/webservices/server/integration/main/module.xml - Does anyone else need to review this dependency?
4. org/hibernate/bytecodetransformer/main/module.xml - the unit test passed so we are good.
5. org/apache/cxf/ws-security/main/module.xml - Does anyone else need to review this dependency?
6. org/apache/cxf/main/module.xml - Does anyone else need to review this dependency?
7. org/apache/cxf/services-sts/main/module.xml - Does anyone else need to review this dependency?
8. org/apache/cxf/impl/main/module.xml9 - Does anyone else need to review this dependency?

**Comment by bstansberry** [comment]
Thanks, @scottmarlow. I wasn't aware of the byte-buddy shading. But our module for it has no dep on the asm.asm module, so any calls that go into bytebuddy are going to load it's own shaded classes, so we're good there.

@jimma WDYT?  My look at CXF led me to believe the version we use already depends on ASM 9.1, so this basically brings us into alignment.

Smallrye Config 2.0.2's pom actually depends on ASM 9.0, so this PR would bring us to a closer match than we currently have.

**Comment by jimma** [comment]
> @jimma WDYT? My look at CXF led me to believe the version we use already depends on ASM 9.1, so this basically brings us into alignment.

+1. We are good to align this version to 9.1.

**Pull request merged**
