### PR TITLE
[WFLY-12059] Upgrade wildfly-common to 1.5.1.Final

### PR DESCRIPTION
**Pull request by tadamski**
https://issues.jboss.org/browse/WFLY-12059

(We have to keep it consistent with core: https://issues.jboss.org/browse/WFCORE-4426)

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

### CODE REVIEW

**Comment by darranl** [comment]
How do we have a WildFly Common override in WildFly - shouldn't this just come in via WildFly Core?

**Comment by tadamski** [comment]
It is used as Galeon dependency - I'm not sure if we can remove it directly.

**Comment by bstansberry** [comment]
@tadamski This needs a rebase.

Note that this is not needed to result in 1.5.1 being used in the server. This property controls a maven plugin dependency only.  The server compile and runtime dependency comes from core. 

The property should be moved up with the other plugin dependency properties in the pom (and a comment added clarifying that's what those properties are about.)

But that doesn't need to happen for this PR. I'm just saying all this to clarify things a bit. The PR's fine so long as it's rebased and CI passes.

**Review by jamezp — APPROVED** [review]

**Comment by jamezp** [comment]
IMO plugins should ensure all dependencies are provided. I filed https://issues.jboss.org/browse/WFCORE-4465 as I do think the embedded server should provide the dependencies required for it to work.

**Comment by tadamski** [comment]
Rebased.

**Review by jamezp — APPROVED** [review]

**Pull request merged**
