### PR TITLE
[WFLY-12207] Upgrade RESTEasy 3.7.0.Final -> 3.8.0.Final

### PR DESCRIPTION
**Pull request by ronsigal**
https://issues.jboss.org/browse/WFLY-12207

Incorporates RFEs:
https://issues.jboss.org/browse/WFLY-11737
https://issues.jboss.org/browse/WFLY-12138

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

### CODE REVIEW

**Review by asoldano — CHANGES_REQUESTED** [review]
Hi @ronsigal , there're additional changes needed in this upgrade, see the diff https://github.com/resteasy/Resteasy/compare/3.7.0.Final...3.8.0.Final?expand=1 (in particular resteasy-dependencies-bom/pom.xml):
* yasson needs to be upgraded to 1.0.4
* microprofile rest client api needs to be upgraded to 1.3.2
Thanks!

**Comment by ronsigal** [comment]
Aaarrgghh. I looked at jboss-modules and didn't see anything new ... . Ok, thanks.

**Comment by darranl** [comment]
@asoldano / @ronsigal Are further changes needed before this one can be merged?  Also do we have any release notes for this component upgrade, is it just bug fixes or any new features which will be exposed to end users?

**Comment by asoldano** [comment]
@darranl at least the microprofile rest client version needs to be fixed. I believe Ron will be doing that tomorrow, he's away today.
https://issues.jboss.org/browse/WFLY-12207 has links to the features that are incorporated in this upgrade.

**Comment by asoldano** [comment]
@darranl 3.8.0.Final release notes: https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12310560&version=12341854

**Comment by ronsigal** [comment]
@asoldano, 

resteasy-dependencies/pom.xml in 3.8.0.Final has these updates:
```
<version.microprofile.restclient>1.3.1</version.microprofile.restclient>
<version.io.smallrye.smallrye-config>1.3.6</version.io.smallrye.smallrye-config>
```
I've pushed these changes, but they're not consistent with your list ...

-Ron

**Comment by ronsigal** [comment]
Note: smallrye-config is upgraded to 1.3.7 in https://github.com/wildfly/wildfly/pull/12369.

**Comment by asoldano** [comment]
> @asoldano,
> 
> resteasy-dependencies/pom.xml in 3.8.0.Final has these updates:
> 
> ```
> <version.microprofile.restclient>1.3.1</version.microprofile.restclient>

https://github.com/resteasy/Resteasy/blob/3.8.0.Final/resteasy-dependencies-bom/pom.xml#L71
Please update to pull 1.3.2 :-)


> <version.io.smallrye.smallrye-config>1.3.6</version.io.smallrye.smallrye-config>
> ```
> 

I'd say we should be fine with the 1.3.7 that's already in WFLY now.
Thanks

**Comment by ronsigal** [comment]
<version.org.eclipse.microprofile.rest.client.api> upgraded to 1.3.2.

**Comment by bstansberry** [comment]
#12376 had the smallrye-config upgrade. Best to let Jeff Mesnil handle those as he handle MP Config.

**Comment by asoldano** [comment]
@bstansberry @jamezp @darranl (cc @ronsigal ), is there anything still preventing this from being merged? The 2 RFEs that are coming with this upgrade should be in the proper state.

**Review by asoldano — APPROVED** [review]

**Pull request merged**
