### PR TITLE
[WFLY-6305] Add CXF artefacts required by Camel integration

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by tdiesler** [comment]
retest this please

**Comment by stuartwdouglas** [comment]
Why can't the camel integration just provide these in a different module (same for bouncycastle)?

**Comment by tdiesler** [comment]
We can, but it is easier to say "cxf comes from wildfly"

**Comment by stuartwdouglas** [comment]
We can't really distribute additional jars that are not required by Wildfly just because they may be useful downstream.

In the future we may have the facility to optionally include components as part of a provisioning system that we are discussing, but that is still some time away.

**Pull request closed without merging**
