### PR TITLE
Add doc for WFCORE-3447, CLI SSL security commands

### PR DESCRIPTION
**Pull request by jfdenise**
Community doc for https://issues.jboss.org/browse/WFCORE-3447

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by kabir** [comment]
@jfdenise please include this in https://github.com/wildfly/wildfly/pull/10811 and close this one. I think they are both followup on the same core functionality?

**Comment by jfdenise** [comment]
Closing it as it has been integrated in https://github.com/wildfly/wildfly/pull/10811 PR.

**Comment by jfdenise** [comment]
@kabir , thank-you, done.

**Pull request closed without merging**
