### PR TITLE
[WFLY-11690] Upgrade XML namespace for Galleon packages from 1.0 to 2.0

### PR DESCRIPTION
**Pull request by aloubyansky**
https://issues.jboss.org/browse/WFLY-11690

### CODE REVIEW

**Comment by bstansberry** [comment]
@jfdenise Does the galleon layers PR use the 2.0 namespace?

**Comment by jfdenise** [comment]
No, packages are in 1.0 namespace.

**Comment by bstansberry** [comment]
@jfdenise Then I think this should wait for that and we should update as needed.

**Comment by aloubyansky** [comment]
Yes, I'll rebase and apply the changes to the packages introduced by the layers PR as well.

**Comment by aloubyansky** [comment]
I rebased and re-applied the changes.

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
