### PR TITLE
[WFLY-12140]Set bridgeName while creating JMSBridge on server

### PR DESCRIPTION
**Pull request by shailendra14k**
JIRA:- https://issues.jboss.org/browse/WFLY-12140

### CODE REVIEW

**Review by ehsavoie — CHANGES_REQUESTED** [review]
I'd rather have the bridgeName being set when the bridge is created in createJMSBridge

**Comment by shailendra14k** [comment]
@ehsavoie That was my 1st thought but i didn't found a simple way to retrieve the bridgeName inside createJMSBridge method and I don't wanted to change its signature.

**Comment by ehsavoie** [comment]
context.getCurrentAddressValue();

**Comment by shailendra14k** [comment]
@ehsavoie Thank you; I have updated the PR, can you plz review?

**Review by ehsavoie — APPROVED** [review]

**Pull request merged**
