### PR TITLE
[WFLY-19478] Remove usage of deprecated SimpleResourceDefinition methods

### PR DESCRIPTION
**Pull request by lvydra**
https://issues.redhat.com/browse/WFLY-19478

### CODE REVIEW

**Review by bstansberry — COMMENTED** [review]
@lvydra This fix is correct, but reviewing it made me realize the entire JIRA is unnecessary. We can simply remove the deprecated method and when this code compiles against the updated class:

https://github.com/wildfly/wildfly-core/pull/6084

I'm going to put the 'hold' label on this for now, with the assumption we can close it and the JIRA once the core fix is integrated.

**Comment by bstansberry** [comment]
Oh, and thanks! This is helpful.

**Comment by bstansberry** [comment]
Ah, but this one does need to be changed to override the OperationStepHandler variant instead:

```
    /**
     * Overrides the default impl to use a special definition of the add op that includes additional parameter
     * {@link #DEFAULT_CLUSTERED_SFSB_CACHE}
     * {@inheritDoc}
     */
    @Override
    protected void registerAddOperation(ManagementResourceRegistration registration, AbstractAddStepHandler handler, OperationEntry.Flag... flags) {
        OperationDefinition od = new SimpleOperationDefinitionBuilder(ADD, getResourceDescriptionResolver())
                .setParameters(ATTRIBUTES)
                .addParameter(DEFAULT_CLUSTERED_SFSB_CACHE)
                .withFlags(flags)
                .build();
        registration.registerOperationHandler(od, handler);
    }
```

Perhaps revert what you have here and fix that instead?

**Comment by lvydra** [comment]
Hi @bstansberry, thank you for your review, I have updated PR accordingly.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @lvydra

**Pull request merged**
