### PR TITLE
[WFLY-18593] Upgrade Eclipse Yasson to 3.0.3

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFLY-18593

### CODE REVIEW

**Comment by bstansberry** [comment]
@jamezp Please review

**Review by jamezp — APPROVED** [review]
This would be the only [PR](https://github.com/eclipse-ee4j/yasson/pull/584) that concerns me as it's not backward compatible.  That said, this is a private impl

**Comment by bstansberry** [comment]
Thanks @jamezp

**Comment by jamezp** [comment]
This is causing a regression in the RESTEasy test suite due to https://github.com/eclipse-ee4j/yasson/issues/604.

**Comment by jamezp** [comment]
I'm taking this back and the "regression" will be solved in https://issues.redhat.com/browse/RESTEASY-3397

**Pull request merged**
