### PR TITLE
WFLY-15891 Duplicate dayOfWeek mapping in ejb3 DayOfWeek and DayOfMon…

### PR DESCRIPTION
**Pull request by chengfang**
…th classes

https://issues.redhat.com/browse/WFLY-15891

This PR makes ejb3 `DayOfWeek` and `DayOfMonth` classes share the same `DayOfWeek.DAY_OF_WEEK_ALIAS` mapping, and remove the one in `DayOfMonth` class.

And some general cleanup.

### CODE REVIEW

**Comment by chengfang** [comment]
@tadamski please review.

**Comment by pferraro** [comment]
@chengfang This needs a rebase.

**Comment by chengfang** [comment]
Rebased and all conflicts resolved.

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
