### PR TITLE
[WFLY-19783] Upgrade the keycloak-services and keycloak-core test dependencies to 25.0.6

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.redhat.com/browse/WFLY-19783
Elytron issue: https://issues.redhat.com/browse/ELY-2839
Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by luck3y** [comment]
Tests passing locally. FYI @fjuma.

**Comment by luck3y** [comment]
adding a hold pending a disussion about the elytron version of this PR.

**Comment by bstansberry** [comment]
@luck3y Can this move forward?

**Comment by luck3y** [comment]
@bstansberry I'll have to check, we wanted this version aligned with the same one in Elytron, but still haven't moved off JDK 11 for CI there yet so the Elytron update hasn't moved forward yet.

**Comment by bstansberry** [comment]
@luck3y @fjuma I'd prefer the WF TS not be aligned with Elytron over continuing to use this old Keycloak.

**Comment by fjuma** [comment]
> @luck3y @fjuma I'd prefer the WF TS not be aligned with Elytron over continuing to use this old Keycloak.

Makes sense, we can go ahead and get this merged.

@luck3y There's a conflict that needs to be fixed here and then this should be good to go.

**Comment by luck3y** [comment]
+1, will update get this resolved in a sec.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @luck3y and @fjuma

**Pull request merged**
