### PR TITLE
WFLY-13849 Decouple version.org.infinispan.server from version.org.in…

### PR DESCRIPTION
**Pull request by rhusar**
…finispan

Resolves
https://issues.redhat.com/browse/WFLY-13849

### CODE REVIEW

**Comment by rhusar** [comment]
@pferraro FYI

**Review by pferraro — APPROVED** [review]

**Comment by bstansberry** [comment]
@rhusar JIRA is down now so I can't resolve the JIRA after merging, so please take care of that. Thanks!

**Comment by rhusar** [comment]
@bstansberry Will do. Thanks.

**Comment by rhusar** [comment]
Resolved in Jira now as well (Jira was out longer than they planned for).

**Pull request merged**
