### PR TITLE
WFLY-13131 Re-enable AbstractDatabasePersistenceWebFailoverTestCase#testGracefulSimpleFailover

### PR DESCRIPTION
**Pull request by rhusar**
Resolves
https://issues.redhat.com/browse/WFLY-13069
https://issues.redhat.com/browse/WFLY-13131

### CODE REVIEW

**Comment by rhusar** [comment]
@pferraro Hm, any thoughts on this? I reimplemented the test to use an external h2 server and connect to it with a tcp connection but it still fails. I assumed that the h2 AUTO_SERVER mode is not reliable but it looks like its something else.

**Comment by darranl** [comment]
@rhusar / @pferraro This has bee on hold since March, can this be continued or should we close for now and reopen when you are both ready?

**Comment by rhusar** [comment]
@darranl There should be nothing inherently wrong with this, but it doesn't seem to resolve the intermittent failures completely. Let me try to run the CI again and see where we stand. Also, the Infinispan 11.x upgrade might fix this.

**Comment by darranl** [comment]
Ok, I also kicked off CI for the failed job on the Infinispan job - if we do get clean runs maybe better get both in and if still intermittent failures try again.

**Comment by rhusar** [comment]
All passed, but kicked off a couple more Linux - JDK 8 and Windows - JDK 11  to see how stable this is now.

**Comment by rhusar** [comment]
Retesting after Infinispan 11.x upgrade.

**Comment by rhusar** [comment]
@pferraro I have been running this locally in a look for couple of hours and haven't seen a single failure. I think this is ready to go. Please approve/merge.

**Comment by rhusar** [comment]
@pferraro Also, I think we can remove the hold label.

**Review by pferraro — APPROVED** [review]

**Comment by pferraro** [comment]
Retest this please.

**Comment by pferraro** [comment]
Triggering another round of CI to validate test w/Infinispan 11.0.x.

**Comment by rhusar** [comment]
@pferraro Already ran this morning, but sure lets do more runs :)

**Pull request merged**
