### PR TITLE
WFLY-11906 Managed Executor Task Fails with CDI if created from Batch…

### PR DESCRIPTION
**Pull request by chengfang**
…let.
Need to propagate EE concurrency context to batch thread to support EE concurrency operations from batch artifacts.
Jira issue: https://issues.jboss.org/browse/WFLY-11906

### CODE REVIEW

**Comment by chengfang** [comment]
@jamezp  @emmartins please review.

**Comment by chengfang** [comment]
Retest it please.

**Comment by kabir** [comment]
Retest this please

@chengfang ^^ is the correct text to do a retest :)

**Comment by emmartins** [comment]
Looks ok to me.

**Review by jamezp — APPROVED** [review]

**Pull request merged**
