### PR TITLE
[WFLY-12647] Remove redundant 'rbac-soak' profile.

### PR DESCRIPTION
**Pull request by darranl**
https://issues.jboss.org/browse/WFLY-12647

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]

**Review by rhusar — APPROVED** [review]

**Comment by rhusar** [comment]
@darranl BTW its rbac-soak not rbak-soak.

**Comment by darranl** [comment]
I had enough trouble spelling soak without a 'c' now a 'k' has crept into RBAC !!

**Comment by rhusar** [comment]
:-D

**Comment by darranl** [comment]
FYI the commit I just pushed is identical to the prior push - I have just corrected the spelling mistake in the commit message.

**Pull request merged**
