### PR TITLE
[WFLY-8066] Make the config changes in the galleon feature pack, not …

### PR DESCRIPTION
**Pull request by bstansberry**
…just legacy

https://issues.jboss.org/browse/WFLY-8066

### CODE REVIEW

**Review by pferraro — APPROVED** [review]
Thanks for spotting (and fixing) this.

**Comment by kabir** [comment]
@bstansberry / @pferraro For [windows](https://ci.wildfly.org/viewType.html?buildTypeId=WF_PullRequest_Windows&tab=buildTypeHistoryList&branch_WF_PullRequest=pull%2F11585) it is either this PR, or the clustering tests are playing up again

**Comment by bstansberry** [comment]
@kabir @pferraro This same commit was included in #11586, which was merged, so if it's a problem that commit should be reverted.

I spotted this while doing the general "check for diffs" for #11586 but since it was more serious bug than the others I was correcting first thing I filed this separate PR.

**Comment by kabir** [comment]
@bstansberry @pferraro I opened https://github.com/wildfly/wildfly/pull/11588 to revert that commit

**Comment by kabir** [comment]
@bstansberry Closing since I think we ended up reverting the commit from #11586

**Pull request closed without merging**
