### PR TITLE
[WFLY-11351] Add resource address and attribute to the metric tags

### PR DESCRIPTION
**Pull request by jmesnil**
To improve query and aggregation of the metrics exposed by the
MicroProfile Metrics HTTP endpoints, the resource address' elements and
the attribute name are added to the tags in the metric' metadata.

Add test in MicroProfileMetricsApplicationTestCase to check WildFly
deployment metrics (using Undertow's request-count)

JIRA: https://issues.jboss.org/browse/WFLY-11351

### CODE REVIEW

**Comment by jmesnil** [comment]
@bstansberry this is directly related to https://github.com/jboss-openshift/cct_module/pull/314

**Comment by bstansberry** [comment]
LGTM but failure on currently running Windows CI run looks related:

```
11:21:31,851 INFO  [org.jboss.as.controller] (management-handler-thread - 1) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service org.wildlfy.extension.microprofile.metrics.wildfly-registrar: Failed to start service
```

That's from the logging for the first failing test: IronJacamarDeploymentStatisticsTestCase.testTwoConnectionsInOneRa

**Comment by jamezp** [comment]
I'm going to restart the Windows job. Just so we have the link for logs to the original job https://ci.wildfly.org/viewLog.html?buildId=128682&buildTypeId=WF_PullRequest_Windows&tab=buildResultsDiv.

**Comment by jamezp** [comment]
This doesn't seem to be failing again and I couldn't get it to fail on my Windows VM.

**Pull request merged**
