### PR TITLE
WFLY-18362 Upgrade Mojarra to 4.0.3

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-18362

This specifically pulls in a fix for https://github.com/eclipse-ee4j/mojarra/issues/5222, required to fix:
https://issues.redhat.com/browse/WFLY-17840

### CODE REVIEW

**Comment by jasondlee** [comment]
Looks good to me. Is this also a 29.0.1 candidate?

**Review by jasondlee — APPROVED** [review]

**Comment by pferraro** [comment]
> Is this also a 29.0.1 candidate?

It certainly could be.

**Comment by jasondlee** [comment]
> It certainly could be.

I guess the better question is whether or not the the clustering issue is a 29.0.1 issue. If that needs to go in the point release, this will need to as well, so i'll leave that to your discretion.

**Comment by pferraro** [comment]
> > It certainly could be.
> 
> I guess the better question is whether or not the the clustering issue is a 29.0.1 issue. If that needs to go in the point release, this will need to as well, so i'll leave that to your discretion.

This can wait until WF30, since this has a application-side workaround.

**Review by jasondlee — APPROVED** [review]
We discussed this in Zulip (https://wildfly.zulipchat.com/#narrow/stream/174184-wildfly-developers/topic/FlashScopeDistributedSessionTestCase.20fails.20in.20Mojarra.204.2E0.2E3)

Looks good to me. Thanks, @pferraro!

**Pull request merged**
