### PR TITLE
[WFLY-13730] Work around problem by hiding requirement relationship f…

### PR DESCRIPTION
**Pull request by bstansberry**
…rom Galleon

https://issues.redhat.com/browse/WFLY-13730

### CODE REVIEW

**Comment by darranl** [comment]
If you create a follow up issue I can remove the dependency on the JACC service entirely meaning the resource will no longer need a capability reference.

**Comment by bstansberry** [comment]
@chengfang @tadamski FYI in case this is causing you any problems with your layers work.

**Comment by bstansberry** [comment]
@darranl I filed https://issues.redhat.com/browse/WFLY-13733.

**Comment by darranl** [comment]
@jmesnil can you see about combining this with the core upgrade, I then need to follow up and delete the capability dependency entirely.

**Comment by bstansberry** [comment]
This was included in #13467 13467

**Pull request closed without merging**
