### PR TITLE
WFLY-17216 Upgrade JGroups to 5.2.9.Final

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-17216

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]

**Comment by pferraro** [comment]
Adding hold label - I want to validate the reliability of the restored port_range restrictions with several CI runs.

**Review by rhusar — APPROVED** [review]
LGTM

**Review by bstansberry — CHANGES_REQUESTED** [review]
I'm putting a 'Request changes' on this not for any particular change but because the no available port problem still appeared in one of the CI runs.

**Review by rhusar — CHANGES_REQUESTED** [review]
I don't have permission to dismiss my above review, but there are still failures in the manual mode suite.

**Comment by pferraro** [comment]
I'm done experimenting...  Removing hold label.

**Comment by bstansberry** [comment]
Thanks @pferraro

**Pull request merged**
