### PR TITLE
 [WFLY-12685] Updated Microprofile Health to 2.1

### PR DESCRIPTION
**Pull request by tobiasstadler**
Issue: https://issues.jboss.org/browse/WFLY-12685 and https://issues.jboss.org/browse/WFLY-12734

### CODE REVIEW

**Review by rhusar — CHANGES_REQUESTED** [review]
Please make sure your PR meets the requirements in the description (e.g. Jira).

**Comment by jmesnil** [comment]
@tobiasstadler thanks for the PR.

In WildFly, we track every component upgrade with separate WFLY issues.
You have already created WFLY-12685 for the MicroProfile Health upgrade. Could you create another one to track the smallrye-health upgrade please?
That's fine if there is a single commit for both but we need to be able to track the 2 upgrades separately in our issue tracker.

**Review by jmesnil — CHANGES_REQUESTED** [review]
@tobiasstadler thanks for the PR.

In WildFly, we track every component upgrade with separate WFLY issues.
You have already created WFLY-12685 for the MicroProfile Health upgrade. Could you create another one to track the smallrye-health upgrade please?
That's fine if there is a single commit for both but we need to be able to track the 2 upgrades separately in our issue tracker.

**Comment by tobiasstadler** [comment]
I created https://issues.jboss.org/browse/WFLY-12734

**Comment by jmesnil** [comment]
Dev analysis is at https://github.com/wildfly/wildfly-proposals/pull/258

**Comment by jmesnil** [comment]
@tobiasstadler thanks for the changes.
I was not clear enough in my review's instructions. We track component upgrade using the commit messages (not the PR itself). 
Could you please amend the commit message so that it references both https://issues.jboss.org/browse/WFLY-12685 and https://issues.jboss.org/browse/WFLY-12734?

thanks

**Comment by istraka** [comment]
The PR updates MP Metrics instead of MP Health.

**Comment by istraka** [comment]
Creating simple HealthCheck
```
@Liveness
@Readiness
@ApplicationScoped
public class BothHealthCheck implements HealthCheck {
    @Override
    public HealthCheckResponse call() {
        return HealthCheckResponse.down("two");
    }
}
```
and accessing http://localhost:9990/health results to 500 internal code
```
15:59:49,966 ERROR [io.undertow.request] (management I/O-1) UT005071: Undertow request failed HttpServerExchange{ GET /health}: java.lang.NoSuchMethodError: org.eclipse.microprofile.health.HealthCheckResponse.down(Ljava/lang/String;)Lorg/eclipse/microprofile/health/HealthCheckResponse;
	at health.BothHealthCheck.call(BothHealthCheck.java:16)
	at health.BothHealthCheck$Proxy$_$$_WeldClientProxy.call(Unknown Source)
	at org.wildfly.extension.microprofile.health.HealthReporter.jsonObject(HealthReporter.java:120)
	at org.wildfly.extension.microprofile.health.HealthReporter.fillCheck(HealthReporter.java:107)
	at org.wildfly.extension.microprofile.health.HealthReporter.processChecks(HealthReporter.java:96)
	at org.wildfly.extension.microprofile.health.HealthReporter.getHealth(HealthReporter.java:79)
	at org.wildfly.extension.microprofile.health.HealthReporter.getHealth(HealthReporter.java:60)
	at org.wildfly.extension.microprofile.health.HealthContextService$HealthCheckHandler.handleRequest(HealthContextService.java:100)
	at org.jboss.as.domain.http.server.security.RealmReadinessHandler.handleRequest(RealmReadinessHandler.java:51)
	at org.jboss.as.domain.http.server.security.ServerErrorReadinessHandler.handleRequest(ServerErrorReadinessHandler.java:35)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:91)
	at io.undertow.server.handlers.ChannelUpgradeHandler.handleRequest(ChannelUpgradeHandler.java:211)
	at io.undertow.server.handlers.cache.CacheHandler.handleRequest(CacheHandler.java:92)
	at io.undertow.server.handlers.error.SimpleErrorPageHandler.handleRequest(SimpleErrorPageHandler.java:78)
	at io.undertow.server.handlers.CanonicalPathHandler.handleRequest(CanonicalPathHandler.java:49)
	at org.jboss.as.domain.http.server.ManagementHttpRequestHandler.handleRequest(ManagementHttpRequestHandler.java:57)
	at org.jboss.as.domain.http.server.cors.CorsHttpHandler.handleRequest(CorsHttpHandler.java:75)
	at org.jboss.as.domain.http.server.ManagementHttpServer$UpgradeFixHandler.handleRequest(ManagementHttpServer.java:672)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer2.acceptTask(QueuedNioTcpServer2.java:178)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)
```

**Review by jmesnil — CHANGES_REQUESTED** [review]
I think you applied changes from #12719 to this one.

**Comment by istraka** [comment]
Thanks for the update. However the version must be `2.1` instead of `2.1.0`. See https://mvnrepository.com/artifact/io.smallrye/smallrye-health

**Review by jmesnil — APPROVED** [review]

**Comment by jmesnil** [comment]
> Creating simple HealthCheck
> and accessing http://localhost:9990/health results to 500 internal code

I'm not seeing any issue when I replicate your use case. Did you properly rebuild WildFly (it seems that there is an older version of microprofile-health that is used by your server)?

**Comment by istraka** [comment]
@jmesnil issue was valid for the old version of the PR (MP Metrics update instead of MP Health). It has been fixed.

**Comment by darranl** [comment]
This presently has a merge conflict that needs resolving.

**Comment by tobiasstadler** [comment]
I rebased the branch

**Comment by jmesnil** [comment]
@tobiasstadler we're finally ready to merge your PR. Could you please rebase it as the update of smallrye fault-tolerance introduced a conflict?

Once you have done it, I'll be able to merge it. Thanks

**Comment by tobiasstadler** [comment]
@jmesnil I did the rebase

**Comment by jmesnil** [comment]
@tobiasstadler thanks!

**Pull request merged**
