### PR TITLE
 [WFLY-15394]: WildFly does not allow setting of routing-type on core bridges

### PR DESCRIPTION
**Pull request by ehsavoie**
* Adding new routing-type attribute on core bridge.

Jira: https://issues.redhat.com/browse/WFLY-15394

### CODE REVIEW

**Comment by ehsavoie** [comment]
Requires: https://github.com/wildfly/wildfly/pull/14747

**Comment by gaol** [comment]
@bstansberry can this one be merged? thanks

**Comment by gaol** [comment]
@pferraro would you please review? thanks

**Review by ehsavoie — COMMENTED** [review]
LGTM

**Review by pferraro — APPROVED** [review]

**Pull request merged**
