### PR TITLE
WFLY-19282 Update HostExcludesTestCase configuration to work with WF33

### PR DESCRIPTION
**Pull request by rhusar**
Resolves
https://issues.redhat.com/browse/WFLY-19282

____

More information about the [wildfly-bot[bot]](https://github.com/wildfly/wildfly-github-bot)

### CODE REVIEW

**Comment by rhusar** [comment]
@yersan is this what needs to happen after every release?

**Review by yersan — APPROVED** [review]
Hello @rhusar , thanks for this. 

> is this what needs to happen after every release when we have added new extensions

Yes, for added or removed extensions. It is a pain, but it is the way how we do not forget to have the Enums updated with the list of extensions added or removed during the version recently released. Probably needs another thinking, this restriction is a pain and another task to do for the one who is releasing :(

> or if we want to add new ones and we have not moved it on to the next exclusion version?

If you want to add / remove more extensions and you have not moved it I think there is no restrictions there. But notice how it is expected to work: firstly the test discover whether there are extensions added/removed by checking the available extensions SPI implementations. The test will fail if it finds a new extension that is not tracked under the CURRENT Enum. If the test fails you are forced to add/removed the extension to/from the CURRENT enum, which is the enum that represents the current version under development. So, you usually add/remove extensions when you add or removed from the server certain extension. That will part of the extension PR development.

To sum us, the test forces us to track the extensions for the current release under development and forces us to add a new Enum with the added/removed extensions of the latest release if we have moved to a new release. Add to it all the details about the different distribution flavours ee, standard, preview. We only track the enums for ee and standard.

**Comment by yersan** [comment]
Thanks @rhusar

**Comment by rhusar** [comment]
@yersan, updating the HostExcludesTestCase seems to me to be a task worth mentioning in the release procedure document that @jmesnil @bstansberry use. Can you please consider adding it? Basically, almost after every release all nightly jobs that we run and all PRs that we test fail and generate lot of noise.

**Comment by yersan** [comment]
> Can you please consider adding it? 

Thanks for the suggestion @rhusar. This is already tracked in the release procedure.

**Comment by rhusar** [comment]
> > Can you please consider adding it?
> 
> Thanks for the suggestion @rhusar. This is already tracked in the release procedure.

Right - I saw Brian mention this on Zulip of Friday that we just missed it. All good 👍🏼

**Pull request merged**
