### PR TITLE
[WFLY-6038] Can not deploy a @ConnectionFactoryDefinition if the RA has more <connection-definitions>

### PR DESCRIPTION
**Pull request by gaol**
Jira: https://issues.jboss.org/browse/WFLY-6038

### CODE REVIEW

**Comment by gaol** [comment]
@jesperpedersen could you please review this? thank you.

**Comment by maeste** [comment]
LGTM

**Comment by jmesnil** [comment]
@gaol Could you open a JBEAP issue for this and open a PR for EAP7 please? This fix is required for https://issues.jboss.org/browse/JBEAP-624

**Comment by gaol** [comment]
@jmesnil done. :-)

**Comment by jmesnil** [comment]
This PR can be closed, its commit was merged in #8619

**Comment by gaol** [comment]
Close it according to comment above.

**Pull request closed without merging**
