### PR TITLE
[WFLY-11261] CLI unable to refer jberet resources after run PurgeBatc…

### PR DESCRIPTION
**Pull request by nagetsum**
…hlet

Please make sure your PR meets the following requirements:
- [x] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue(s)
- [x] Pull Request contains description of the issue(s)
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted

### CODE REVIEW

**Review by jamezp — APPROVED** [review]
My only concern here is performance which we may need to look into. For a small number of jobs this shouldn't be an issue.

**Comment by bstansberry** [comment]
@jamezp is hasJobExecution ok?  On the surface it seems like it would be vulnerable to similar problems, since it just assumes the current children set is ok. So uses of it could provide a child Resource but then the runtime handling of that child resource might fail.

I suppose in the end in that kind of situation there's a good chance the request would fail any way, and this is just a matter of failing cleanly in Stage.MODEL with an understandable NoSuchResourceException vs failing in RUNTIME with a more obscure exception.

Anyway, as I wrote this I've convinced myself that any problem there is a different enough use case that there's no reason to mandate solving it as part of fixing this issue.

**Comment by jamezp** [comment]
@bstansberry That's a good point and IIRC the reason it was done like that was for performance. I think it takes thousands, maybe tens of thousands, of jobs before performance is an issue though.

**Comment by jamezp** [comment]
This is okay to test

**Comment by jamezp** [comment]
I've filed a separate issue for this https://issues.jboss.org/browse/WFLY-11264

**Comment by jamezp** [comment]
this is okay to test

**Comment by jamezp** [comment]
this is ok to test

**Pull request merged**
