### PR TITLE
[WFLY-13834]/ [WFLY-18048] Document the new file encoding parameter added to Elytron audit logging. Add test for WFCORE-5106.

### PR DESCRIPTION
**Pull request by ivassile**
https://issues.redhat.com/browse/WFLY-13834

Documentation for https://issues.redhat.com/browse/WFCORE-5106

Requires https://github.com/wildfly/wildfly-core/pull/4319

Issue: https://issues.redhat.com/browse/WFLY-18048

This change depends on:
https://issues.redhat.com/browse/ELY-1211
https://issues.redhat.com/browse/WFCORE-5106

### CODE REVIEW

**Comment by bstansberry** [comment]
@ivassile Please file a WFLY for this and use that in the commit message and PR title. Thanks!

**Comment by Skyllarr** [comment]
@ivassile as @OndrejKotek mentioned, I would also expect to add a brief note about `encoding` attribute under `File audit log` (it is in the same file just above ) and mentions other attributes that can be specified.

**Comment by ivassile** [comment]
Corrected the document.

**Review by fjuma — APPROVED** [review]
Thanks @ivassile!

**Review by skyllarr — APPROVED** [review]

**Review by fjuma — APPROVED** [review]
Thanks @ivassile!

**Pull request merged**
