### PR TITLE
[WFLY-19346] Make 'org.wildfly.security.elytron-http-oidc' module public

### PR DESCRIPTION
**Pull request by soul2zimate**
Issue: https://issues.redhat.com/browse/WFLY-19346

Make 'org.wildfly.security.elytron-http-oidc' module public

____

More information about the [wildfly-bot[bot]](https://github.com/wildfly/wildfly-github-bot)

### CODE REVIEW

**Review by darranl — CHANGES_REQUESTED** [review]
Before changing the modules we should check the generate JavaDoc and ensure all of these classes get listed as public API and with that double check they are suitable to be classed as public API and make sure they are also included in the JAPICMP check as well.

**Comment by soul2zimate** [comment]
> Before changing the modules we should check the generate JavaDoc and ensure all of these classes get listed as public API and with that double check they are suitable to be classed as public API

Hi @darranl, Do you mean https://wildfly-security.github.io/wildfly-elytron/documentation/api/upstream/org/wildfly/security/http/oidc/package-summary.html ? I can not really tell all of them. but I can see downstream user want to use `OidcConfigurationServletListener` which is public class.

**Comment by bstansberry** [comment]
@soul2zimate @darranl I think this PR should be closed and the issue should be analyzed / discussed somewhere else, e.g. in JIRA comments, zulip, wildfly-dev etc. Then open a PR when there's agreement on what should be exposed as public and how.

**Comment by soul2zimate** [comment]
I was actually following @fjuma's suggestion in https://issues.redhat.com/browse/EAPSUP-1470.

Hi Elytron team, let me know if you need further discussion. then I will close this PR.

**Comment by fjuma** [comment]
> I was actually following @fjuma's suggestion in https://issues.redhat.com/browse/EAPSUP-1470.
> 
> Hi Elytron team, let me know if you need further discussion. then I will close this PR.

@soul2zimate I had mentioned there that we should make the module public but we do still need to check the JavaDoc first and ensure all of these classes get listed as public API and verify that they are suitable to be public API.

**Comment by bstansberry** [comment]
Sorry, @soul2zimate if my last comment came off a brusque. I have no complaints that you opened this. It just seems clear that from the comments it needs discussion that's better done elsewhere. Every now and then I dream of getting the PR queue in a manageable state. :)

**Comment by soul2zimate** [comment]
sure @bstansberry  @fjuma  I am closing this one. will reopen once we have an agreement. Thanks.

**Pull request closed without merging**
