### PR TITLE
[WFLY-6462] Add support for JSF 2.3 using the ee8.preview.mode switch

### PR DESCRIPTION
**Pull request by fjuma**
https://issues.jboss.org/browse/WFLY-6462
https://issues.jboss.org/browse/EAP7-893
https://github.com/wildfly/wildfly-proposals/pull/20

### CODE REVIEW

**Comment by fjuma** [comment]
retest this please

**Comment by fjuma** [comment]
retest this please

**Comment by fjuma** [comment]
retest this please

**Comment by kabir** [comment]
@fjuma This needs a rebase.

**Comment by fjuma** [comment]
This PR has been placed on "hold" for now since it needs an EE7 compatibility strategy.

**Comment by fjuma** [comment]
@kabir I've updated this PR so the 'hold' label can be removed now. Thanks.

**Comment by fjuma** [comment]
@kabir @jamezp I've added a smoke test for JSF 2.3 functionality in the EE8 testsuite. It verifies that JSF 2.3 injection works properly.

**Pull request merged**
