### PR TITLE
[WFLY-14968] Collapse if-statements (JPA)

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFLY-14968

### CODE REVIEW

**Comment by bstansberry** [comment]
@scottmarlow Please approve

**Review by scottmarlow — APPROVED** [review]

**Comment by scottmarlow** [comment]
Thanks @boris-unckel for these changes!

**Comment by boris-unckel** [comment]
@bstansberry the next tested and approved PR - Could you check and merge, please?

**Comment by bstansberry** [comment]
@boris-unckel This one has a merge conflict with the isEmpty() change. :)

**Comment by boris-unckel** [comment]
@bstansberry The merge conflict has been resolved, test passed. Ready to merge :-)

**Pull request merged**
