### PR TITLE
[WFLY-16869] Drop source transformation for the Transactions subsystem (with WFLY-17264)

### PR DESCRIPTION
**Pull request by jmfinelli**
This PR addresses [WFLY-16869](https://issues.redhat.com/browse/WFLY-16869) and the following jiras:

[WFLY-17264](https://issues.redhat.com/browse/WFLY-17264)
[WFLY-17290](https://issues.redhat.com/browse/WFLY-17290)
[WFLY-17265](https://issues.redhat.com/browse/WFLY-17265)
[WFLY-17258](https://issues.redhat.com/browse/WFLY-17258)

### CODE REVIEW

**Review by tadamski — APPROVED** [review]
This looks good regarding connector subsystem migration.

**Comment by jmfinelli** [comment]
A re-test of this PR would be good as there were some failures not related to my changes. I tried to `git commit --amend --no-edit` -> `git push -f` to trigger the CI again but that didn't happen. BTW, I cannot reproduce those failures locally

**Comment by bstansberry** [comment]
@jmfinelli a comment like my last one will trigger a retest without requiring a push. You can also click on the link to a failed job and then click the 'Run' button to run it again. That can be more efficient than re-running all the jobs.

That said there may be something not working right with the pull player that triggers the CI jobs.

Also, a /help comment lists the available commands that the pull player bot recognizes.

**Review by bstansberry — CHANGES_REQUESTED** [review]
Hi @jmfinelli 

Can you reorder the commits to put the connector one first? The existing order means the build is broken after the first commit, as it removes the transactions-legacy-namespace artifact that the connector module depends on. It's helpful to not break the build in a commit as it makes it easier to do bisecting.

Also, please add more information to https://issues.redhat.com/browse/WFLY-17291 as to why this change is necessary. It's not obvious why the RTS module needs that dependency and for any non-obvious deps we should have a good record why they exist.  @jamezp please approve that aspect.  If there's any question about it and doing it isn't required for the rest of the PR, please put it into a separate PR so we don't block this one.

**Comment by jmfinelli** [comment]
> Hi @jmfinelli
> 
> Can you reorder the commits to put the connector one first? The existing order means the build is broken after the first commit, as it removes the transactions-legacy-namespace artifact that the connector module depends on. It's helpful to not break the build in a commit as it makes it easier to do bisecting.

Done. Thanks @bstansberry!

> 
> Also, please add more information to https://issues.redhat.com/browse/WFLY-17291 as to why this change is necessary. It's not obvious why the RTS module needs that dependency and for any non-obvious deps we should have a good record why they exist. @jamezp please approve that aspect. If there's any question about it and doing it isn't required for the rest of the PR, please put it into a separate PR so we don't block this one.

I've removed WFLY-17291 from this PR to avoid blocking it. ASAP, I'll add more info to WFLY-17291 and I'll raise a new PR for it.

**Comment by jmfinelli** [comment]
> @jmfinelli a comment like my last one will trigger a retest without requiring a push. You can also click on the link to a failed job and then click the 'Run' button to run it again. That can be more efficient than re-running all the jobs.
> 
> That said there may be something not working right with the pull player that triggers the CI jobs.
> 
> Also, a /help comment lists the available commands that the pull player bot recognizes.

Thank you very much Brian! This helps a lot!

**Comment by jmfinelli** [comment]
The only check that fails is `Linux - JDK 17`. It fails for `SingletonPartitionTestCase.testSingletonService`, which is an already [known issue](https://issues.redhat.com/browse/WFLY-10233) (link to its [test history](https://ci.wildfly.org/test/-3163568781982631309?currentProjectId=WF_PullRequest&expandTestHistoryChartSection=true))

**Comment by bstansberry** [comment]
> > Also, please add more information to https://issues.redhat.com/browse/WFLY-17291 as to why this change is necessary. It's not obvious why the RTS module needs that dependency and for any non-obvious deps we should have a good record why they exist. @jamezp please approve that aspect. If there's any question about it and doing it isn't required for the rest of the PR, please put it into a separate PR so we don't block this one.
> 
> I've removed WFLY-17291 from this PR to avoid blocking it. ASAP, I'll add more info to WFLY-17291 and I'll raise a new PR for it.

Thanks; that info is helpful.

It's adding that info was good thing to do and I think handling it separately is good, but please note that my comment was prompted by my misreading the commit. I think I thought the dependency was being added to the org.wildfly.extension.rts module, not to org.jboss.narayana.rts. The 'not obvious why' part of my comment is because I couldn't see why org.wildfly.extension.rts would need it.  There's nothing non-obvious about why org.jboss.narayana.rts would need it as that module's artifacts have pom deps on resteasy client stuff.

**Review by bstansberry — APPROVED** [review]

**Comment by jmfinelli** [comment]
[The last two most recent executions](https://ci.wildfly.org/buildConfiguration/WF_PullRequest_WindowsJdk11?branch=pull%2F16310&buildTypeTab=overview&mode=builds) of Windows - JDK 11 passed. This PR is ready to be merged

**Comment by bstansberry** [comment]
Thanks @jmfinelli

**Pull request merged**
