### PR TITLE
[WFLY-10229] Ensure that the WFTC types are used for all interactions with JCA and JPA

### PR DESCRIPTION
**Pull request by dmlloyd**
https://issues.jboss.org/browse/WFLY-10229

### CODE REVIEW

**Comment by scottmarlow** [comment]
Not sure about the TestWildFlyTSR compile error, which I hacked locally to compile by removing the argument passed to the new TransactionSynchronizationRegistryWrapper ctor.  I'm building with -DskipTests=true, so I am skipping the test case anyway. 

I passed a basic JPA test with this change.  I'll manually run most of the WF JPA testsuite tests.  Then, I'll try running some other tests.

**Comment by dmlloyd** [comment]
I think you may run into other trouble (specifically the original problem where JCA+JPA synchs may run out of order), because ultimately the wrapper may not be utilized due to the way the TSR service is stubbed out.

I'm looking into other options now.

**Comment by scottmarlow** [comment]
for JCA custom sync ordering, could the new WF TSR service delegate to the current Narayana TM TSR?  That would be nice, as that helps avoid duplication of the ordering logic.

**Comment by dmlloyd** [comment]
No, it cannot; doing so is in fact the source of this problem (encapsulation violation).

**Comment by dmlloyd** [comment]
Closing this for now.

**Pull request closed without merging**
