### PR TITLE
[WFLY-14524][WFLY-14525] Prevent vendor metric registry modifications…

### PR DESCRIPTION
**Pull request by bstansberry**
… while scrapes are in progress

https://issues.redhat.com/browse/WFLY-14524
https://issues.redhat.com/browse/WFLY-14525

@soul2zimate does this fix the problems?

### CODE REVIEW

**Comment by soul2zimate** [comment]
Thanks for the quick update,  I have manually tested this patch.

For the same scenario with `standalone-microprofile.xml` in [WFLY-14524](https://issues.redhat.com/browse/WFLY-14524), the server can't not properly shutdown. Both server shutdown process side and the `/metrics/` endpoint request loop side stuck with a deadlock scene. I have to kill the server to stop it.

The `ConcurrentModificationException` described in [WFLY-14525](https://issues.redhat.com/browse/WFLY-14525) seems fixed, I don't see the error anymore.

**Comment by soul2zimate** [comment]
I have made a thread dump here https://gist.github.com/soul2zimate/550ff5432f82c18c5d4fef1032d5531e

**Comment by bstansberry** [comment]
@soul2zimate Thanks so much for that!  It was late for me last night to manually test this. I think I fixed the problem and I'll try and manually test it in the next couple days.

I changed the order such that https://github.com/wildfly/wildfly/pull/14079/files#diff-cbdce83e7542d6148696847c354fcac837ee1345f7ae32cee35ed6dd75d28788R83 is after acquiring the lock, not before. A reader thread would first acquire the read lock and then do the synchronization on the registry that your thread dump revealed, so a writer thread should follow the same order.

**Comment by soul2zimate** [comment]
The deadlock doesn't appear anymore with the latest change. :+1:

**Review by jmesnil — APPROVED** [review]

**Pull request merged**
