### PR TITLE
WFLY-15864 Replace new Date().getTime() with System.currentTimeMillis()

### PR DESCRIPTION
**Pull request by clara0**
https://issues.redhat.com/browse/WFLY-15864

### CODE REVIEW

**Review by chengfang — APPROVED** [review]

**Review by bstansberry — CHANGES_REQUESTED** [review]
Hi @clara0 -- this fails CI due to a checkstyle violation:

[06:02:13] :	 [Step 2/3] [INFO] --- maven-checkstyle-plugin:3.1.1:checkstyle (check-style) @ wildfly-ts-integ-basic ---
[06:02:22] :	 [Step 2/3] [INFO] Starting audit...
[06:02:22]W:	 [Step 2/3] [ERROR] /store/work/tc-work/f5da3564a57e9d74/testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/annotatedejbclient/AnnotatedEJBClientInterceptorTestCase.java:26:8: Unused import - java.util.Date. [UnusedImports]

**Comment by clara0** [comment]
@bstansberry fixed

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @clara0

**Pull request merged**
