### PR TITLE
WFLY-14990 Inside EJB remove unnecessary unboxing to clean code

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/WFLY-14990

### CODE REVIEW

**Comment by RanabirChakraborty** [comment]
@chengfang please take a look

**Comment by bstansberry** [comment]
@RanabirChakraborty for others of these, before filing the PR can you privately ping the relevant component lead and have them review your branch in your own github repo. Then submit the PR when it looks good so they can quickly approve the PR here,

We have 96 open PRs right now and that's too many for efficient work.

**Comment by RanabirChakraborty** [comment]
@bstansberry Okay, sure! I'll do that. Though I have texted the component lead separately but from next PR I'll sent them the link before sending the PR.

**Review by chengfang — APPROVED** [review]

**Comment by bstansberry** [comment]
@RanabirChakraborty this has a a trivial merge conflict now.

**Comment by RanabirChakraborty** [comment]
@bstansberry thanks! Done

**Pull request merged**
