### PR TITLE
[WFLY-16290] DatabaseTimerPersistence loadSqlProperties should be cal…

### PR DESCRIPTION
**Pull request by bmaxwell**
https://issues.redhat.com/browse/WFLY-16290

### CODE REVIEW

**Comment by chengfang** [comment]
`investigateDialect` and `loadSqlProperties` methods currently have circular dependency: `investigateDialect` needs to adjust certain property in `sql` properties; and `loadSqlProperties` needs to check `database` attribute which may be set in `investigateDialect`.

`database` attribute is optional in ejb3 subsystem configuration, though most users would explicitly set it. When not set in configuration, its value is determined in `investigateDialect`.  In the proposed fix,  when `loadSqlProperties` is called first, and this method may access `database`, which is not initialized yet.

How about we don't change the order of `investigateDialect` and `loadSqlProperties`; instead, we move the 2 calls of `adjustCreateAutoTimerStatement` (root of NPE) out of `identifyDialect`, and into the first half of `loadSqlProperties`?

Inside `loadSqlProperties`, we can safely check `database` value, if it's `oracle` or `db2`, call the appropriate `adjustCreateAutoTimerStatement(...)'. `loadSqlProperties` is also a logically better place to adjust certain sql properties.

**Comment by bmaxwell** [comment]
@chengfang  I have updated the PR

**Comment by chengfang** [comment]
There are compilation failures due to some removed imports.

**Comment by bmaxwell** [comment]
@chengfang  yes sorry, I was trying to switch to VSCode and it seems to remove stuff for reasons I do not understand :(

**Review by chengfang — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @bmaxwell

**Comment by rikcarve** [comment]
Any chance this get's back-ported to 26.1?

**Pull request merged**
