### PR TITLE
[WFLY-13994] Distribution xml validation improvements

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFLY-13994

### CODE REVIEW

**Comment by bstansberry** [comment]
Note that the fix for the CI failures on the EE 9 branch (#13453) depends on this change. Which I why I spent the time on an otherwise minor refactor. :)

**Comment by bstansberry** [comment]
@jamezp @jmesnil @kabir @asoldano @darranl @pferraro 

Is this ok? Looking at it by commit may be useful.  The first commit is the bulk of the change but is just a code reorg to share code. The other two are conceptually simple.

I have this in my ee-9 branch but I'd like to get it into master. That will help a lot to simplify conceptually the diff between my ee-9 branch and master, making it easier for people looking at that branch to focus on the main purpose of the branch. The first commit here touches on a bunch of maven modules that otherwise would not need be touched by the ee-9 work.

**Review by jamezp — APPROVED** [review]
This makes sense to me and looks good.

**Comment by kabir** [comment]
I took a glance and it looks ok

**Pull request merged**
