### PR TITLE
Ee api aliases

### PR DESCRIPTION
**Pull request by bstansberry**
CI experiment to check WIP

### CODE REVIEW

**Comment by bstansberry** [comment]
@jfdenise Any idea what causes this failure?

https://ci.wildfly.org/viewLog.html?buildId=205501&tab=buildResultsDiv&buildTypeId=WF_PullRequest_GalleonLinuxJdk11&branch_WF_PullRequest=pull%2F13296

**Comment by jfdenise** [comment]
@bstansberry , you ran into a Layers tests bug, module aliases were not handled. I logged https://issues.redhat.com/browse/WFCORE-4972

**Comment by bstansberry** [comment]
@jfdenise Excellent; thanks!

**Comment by bstansberry** [comment]
Closing; I got the info I wanted.

**Pull request closed without merging**
