### PR TITLE
JSON-P, JSON-B and JAX-RS upgrades (2nd attempt)

### PR DESCRIPTION
**Pull request by asoldano**
This should replace #10834 and fix the jaxrs failures in that.

# Overview
This PR includes changes for JSON-P, JSON-B and JAX-RS with the Java EE 8 tech preview.  @stuartwdouglas please let me know if the module configurations look correct as well.

## JSON-P 1.1 [WFLY-6460](https://issues.jboss.org/browse/WFLY-6460)
This replaces JSON-P 1.0 with JSON-P 1.1 when the `ee8.preview.mode` system property is set to `true`. One thing to note about this is the system property only seems to work when the user specifies it in the `JAVA_OPTS`. This may be because elytron accesses the module before the property is set.

Also note that in the JMS client we hard-code the version to 1.0.4 since client itself still relies on JSON-P 1.0. This library is shaded into the client which is the reason for doing this.

Also note that JSON-P 1.0 implementation library includes both the API and the implementation which is my the `module.xml` exports only the `javax.json.*` packages.

## JSON-B 1.0 [WFLY-7185](https://issues.jboss.org/browse/WFLY-7185)
This introduces the new JSON-B 1.0 API. The module itself will be added to all deployments however the resource will only be added if the `ee8.preview.mode` system property is set to `true`.

There are currently not tests for JSON-B however I did test manually and I will follow up with tests after #10833 gets merged.

## JAX-RS Upgrade Information
This is a preview of the upgrade that I'm soon submitting for bringing JAX-RS 2.1 RESTEasy implementation in WildFly. I'd like the reviewers to start having a look and letting me know of any additional requirements / changes needed for merging before I tag 3.5.0.Final.
I'm dealing with the needed analysis / test plan in the mean time; besides JSR 370 (JAX-RS 2.1), the RESTEasy component upgrade also pulls few other planned new features.

Few JIRA links:
https://issues.jboss.org/browse/WFLY-9789
https://issues.jboss.org/browse/WFLY-6459
https://issues.jboss.org/browse/WFLY-9786
https://issues.jboss.org/browse/WFLY-9787

Dev analysis:
wildfly/wildfly-proposals#16
wildfly/wildfly-proposals#18
wildfly/wildfly-proposals#19

### CODE REVIEW

**Comment by jimma** [comment]
retest this please

**Comment by asoldano** [comment]
rebased to solve conflict, for the records all test runs passed before.

**Comment by rsvoboda** [comment]
Execution timeout for Elytron run.

Linux run has one failed test - failed org.jboss.as.test.clustering.cluster.web ConcurrentFineWebFailoverTestCase.testGracefulSimpleFailover. Probably related to JGroups + ISPN upgrade which was merge lately.

**Comment by jamezp** [comment]
I've merged #10872 which is going to make this out of date. It includes the 2 JSON commits and the 2 JSON test commits. I'll create a new branch on my repo where I'll handle the rebase for this so that it's easier of you guys to rebase in the future. I'll leave this open for now and we can close once a new PR is opened or you can just force push to this branch.

**Comment by rsvoboda** [comment]
This can be closed as @asoldano created https://github.com/wildfly/wildfly/pull/10876 for JAX-RS 2.1

**Pull request closed without merging**
