### PR TITLE
WFLY-5188 DistributedWorkManager needs to handle unknown fork responses

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-5188

Needs review by JCA team.

### CODE REVIEW

**Comment by jesperpedersen** [comment]
@pferraro Lets reopen once IronJacamar 1.2.6 is integrated, and hence https://issues.jboss.org/browse/JBJCA-1289

**Comment by pferraro** [comment]
Gotcha.

**Comment by pferraro** [comment]
@jesperpedersen https://github.com/ironjacamar/ironjacamar/pull/381

**Comment by jesperpedersen** [comment]
@pferraro FYI, #8044

**Pull request closed without merging**
