### PR TITLE
[WFLY-14567] Prohibit "jboss.ejb" service connections to connectors not listed in <remote/> connectors attribute.

### PR DESCRIPTION
**Pull request by rachmatowicz**
This PR does the following:
- modifies EJBRemoteConnectorService to use a Remoting service validation predicate to prevent EJB clients connecting to Remoting connectors which are not properly configured for serving EJB invocations

This PR depends on an upgrade to Remoting 5.1.0.Final and consequently to Wildfly Core.

For more details, see: https://issues.redhat.com/browse/WFLY-14567

### CODE REVIEW

**Comment by rachmatowicz** [comment]
These tests are failing as I need a version of Wildfly Core with Remoting 5.1.0.Final

**Comment by darranl** [comment]
@rachmatowicz Do we have a PR to upgrade JBoss Remoting in WildFly Core?  It looks like core is still on 5.0.21.Final.

**Comment by rachmatowicz** [comment]
> @rachmatowicz Do we have a PR to upgrade JBoss Remoting in WildFly Core? It looks like core is still on 5.0.21.Final.

Probably not.

**Comment by darranl** [comment]
@rachmatowicz are we ready to give this one another go?

**Comment by fjuma** [comment]
@rachmatowicz Just wanted to check on the status of this PR. There's also some conflicts that need to be resolved.

**Comment by darranl** [comment]
@rachmatowicz I am going to close this for now as we are well over a year since it was updated, please reopen or submit a new PR if we are ready to continue this work.

**Comment by rachmatowicz** [comment]
@darranl Can we reopen this? The remoting changes are available for it to be completed.

**Pull request closed without merging**
