### PR TITLE
WFLY-4275 EE components from WEB-INF/classes should not be ignored

### PR DESCRIPTION
**Pull request by mkouba**
Follows up https://github.com/wildfly/wildfly/pull/7120 - the original fix was not entirely correct.

### CODE REVIEW

**Comment by scottmarlow** [comment]
I'm building this change locally so I can run a few tck tests...

**Comment by scottmarlow** [comment]
The jaxrs TCK tests that previously failed, are now passing with this change.

**Comment by mkouba** [comment]
@scottmarlow Thanks for info.

**Comment by n1hility** [comment]
retest this please

**Pull request merged**
