### PR TITLE
[WFLY-10655] SEVERE error on deploy of ear: "Unable to obtain CDI 1.1…

### PR DESCRIPTION
**Pull request by treblereel**
… utilities for Mojarra"
JIRA: https://issues.jboss.org/browse/WFLY-10655
regression against wildfly 13, commit 61f1f7d6dd

### CODE REVIEW

**Comment by treblereel** [comment]
@jamezp @fjuma ? may i ask to take a look

**Review by fjuma — APPROVED** [review]
Looks ok to me but let's check with @jamezp too since he worked on the changes for https://issues.jboss.org/browse/WFLY-10435.

**Comment by treblereel** [comment]
retest this please

**Comment by jamezp** [comment]
I'm not too sure about this. It essentially reverts the fix for #11273. I'm going to test his PR locally against a reproduce I had, but activating JSF if there is an `@Resource` annotation does not seem correct.

Also this should really be rebased on to master. The version is 13.0.0 which is why you're likely seeing test failures.

**Comment by jamezp** [comment]
This does break with my reproducer.
```
10:02:07,341 SEVERE [javax.enterprise.resource.webcontainer.jsf.config] (ServerService Thread Pool -- 12) Critical error during deployment: : com.sun.faces.config.ConfigurationException: Factory 'javax.faces.application.ApplicationFactory' was not configured properly.
	at com.sun.faces.config.processor.FactoryConfigProcessor.verifyFactoriesExist(FactoryConfigProcessor.java:357)
	at com.sun.faces.config.processor.FactoryConfigProcessor.process(FactoryConfigProcessor.java:243)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:443)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:237)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:216)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:185)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:250)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:96)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: javax.faces.FacesException: com.sun.faces.application.ApplicationFactoryImpl
	at javax.faces.FactoryFinderInstance.getImplGivenPreviousImpl(FactoryFinderInstance.java:393)
	at javax.faces.FactoryFinderInstance.getImplementationInstance(FactoryFinderInstance.java:255)
	at javax.faces.FactoryFinderInstance.getFactory(FactoryFinderInstance.java:529)
	at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:292)
	at com.sun.faces.config.processor.FactoryConfigProcessor.verifyFactoriesExist(FactoryConfigProcessor.java:354)
	... 24 more
Caused by: java.lang.ClassNotFoundException: com.sun.faces.application.ApplicationFactoryImpl from [Module "deployment.batch-ear.ear.batch-war.war" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at javax.faces.FactoryFinderInstance.getImplGivenPreviousImpl(FactoryFinderInstance.java:387)
	... 28 more

10:02:07,346 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 12) MSC000001: Failed to start service jboss.deployment.subunit."batch-ear.ear"."batch-war.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.subunit."batch-ear.ear"."batch-war.war".undertow-deployment: java.lang.RuntimeException: java.lang.RuntimeException: com.sun.faces.config.ConfigurationException: Factory 'javax.faces.application.ApplicationFactory' was not configured properly.
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.sun.faces.config.ConfigurationException: Factory 'javax.faces.application.ApplicationFactory' was not configured properly.
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:252)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:96)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
	... 8 more
Caused by: java.lang.RuntimeException: com.sun.faces.config.ConfigurationException: Factory 'javax.faces.application.ApplicationFactory' was not configured properly.
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:315)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:216)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:185)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:250)
	... 10 more
Caused by: com.sun.faces.config.ConfigurationException: Factory 'javax.faces.application.ApplicationFactory' was not configured properly.
	at com.sun.faces.config.processor.FactoryConfigProcessor.verifyFactoriesExist(FactoryConfigProcessor.java:357)
	at com.sun.faces.config.processor.FactoryConfigProcessor.process(FactoryConfigProcessor.java:243)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:443)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:237)
	... 21 more
Caused by: javax.faces.FacesException: com.sun.faces.application.ApplicationFactoryImpl
	at javax.faces.FactoryFinderInstance.getImplGivenPreviousImpl(FactoryFinderInstance.java:393)
	at javax.faces.FactoryFinderInstance.getImplementationInstance(FactoryFinderInstance.java:255)
	at javax.faces.FactoryFinderInstance.getFactory(FactoryFinderInstance.java:529)
	at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:292)
	at com.sun.faces.config.processor.FactoryConfigProcessor.verifyFactoriesExist(FactoryConfigProcessor.java:354)
	... 24 more
Caused by: java.lang.ClassNotFoundException: com.sun.faces.application.ApplicationFactoryImpl from [Module "deployment.batch-ear.ear.batch-war.war" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at javax.faces.FactoryFinderInstance.getImplGivenPreviousImpl(FactoryFinderInstance.java:387)
	... 28 more

10:02:07,354 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) WFLYCTL0013: Operation ("add") failed - address: ([("deployment" => "batch-ear.ear")]) - failure description: {
    "WFLYCTL0080: Failed services" => {"jboss.deployment.subunit.\"batch-ear.ear\".\"batch-war.war\".undertow-deployment" => "java.lang.RuntimeException: java.lang.RuntimeException: com.sun.faces.config.ConfigurationException: Factory 'javax.faces.application.ApplicationFactory' was not configured properly.
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.sun.faces.config.ConfigurationException: Factory 'javax.faces.application.ApplicationFactory' was not configured properly.
    Caused by: java.lang.RuntimeException: com.sun.faces.config.ConfigurationException: Factory 'javax.faces.application.ApplicationFactory' was not configured properly.
    Caused by: com.sun.faces.config.ConfigurationException: Factory 'javax.faces.application.ApplicationFactory' was not configured properly.
    Caused by: javax.faces.FacesException: com.sun.faces.application.ApplicationFactoryImpl
    Caused by: java.lang.ClassNotFoundException: com.sun.faces.application.ApplicationFactoryImpl from [Module \"deployment.batch-ear.ear.batch-war.war\" from Service Module Loader]"},
    "WFLYCTL0412: Required services that are not installed:" => [
        "jboss.deployment.subunit.\"batch-ear.ear\".\"batch-ejb.jar\".beanmanager",
        "jboss.deployment.subunit.\"batch-ear.ear\".\"batch-ejb.jar\".deploymentCompleteService"
    ],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => [
        "jboss.deployment.unit.\"batch-ear.ear\".deploymentCompleteService is missing [jboss.deployment.subunit.\"batch-ear.ear\".\"batch-ejb.jar\".deploymentCompleteService]",
        "jboss.deployment.subunit.\"batch-ear.ear\".\"batch-ejb.jar\".weld.weldClassIntrospector is missing [jboss.deployment.subunit.\"batch-ear.ear\".\"batch-ejb.jar\".beanmanager]",
        "jboss.deployment.subunit.\"batch-ear.ear\".\"batch-ejb.jar\".batch.artifact.factory is missing [jboss.deployment.subunit.\"batch-ear.ear\".\"batch-ejb.jar\".beanmanager]"
    ]
}
10:02:07,355 ERROR [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0021: Deploy of deployment "batch-ear.ear" was rolled back with the following failure message: 
{
    "WFLYCTL0080: Failed services" => {"jboss.deployment.subunit.\"batch-ear.ear\".\"batch-war.war\".undertow-deployment" => "java.lang.RuntimeException: java.lang.RuntimeException: com.sun.faces.config.ConfigurationException: Factory 'javax.faces.application.ApplicationFactory' was not configured properly.
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.sun.faces.config.ConfigurationException: Factory 'javax.faces.application.ApplicationFactory' was not configured properly.
    Caused by: java.lang.RuntimeException: com.sun.faces.config.ConfigurationException: Factory 'javax.faces.application.ApplicationFactory' was not configured properly.
    Caused by: com.sun.faces.config.ConfigurationException: Factory 'javax.faces.application.ApplicationFactory' was not configured properly.
    Caused by: javax.faces.FacesException: com.sun.faces.application.ApplicationFactoryImpl
    Caused by: java.lang.ClassNotFoundException: com.sun.faces.application.ApplicationFactoryImpl from [Module \"deployment.batch-ear.ear.batch-war.war\" from Service Module Loader]"},
    "WFLYCTL0412: Required services that are not installed:" => [
        "jboss.deployment.subunit.\"batch-ear.ear\".\"batch-ejb.jar\".beanmanager",
        "jboss.deployment.subunit.\"batch-ear.ear\".\"batch-ejb.jar\".deploymentCompleteService"
    ],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => [
        "jboss.deployment.unit.\"batch-ear.ear\".deploymentCompleteService is missing [jboss.deployment.subunit.\"batch-ear.ear\".\"batch-ejb.jar\".deploymentCompleteService]",
        "jboss.deployment.subunit.\"batch-ear.ear\".\"batch-ejb.jar\".weld.weldClassIntrospector is missing [jboss.deployment.subunit.\"batch-ear.ear\".\"batch-ejb.jar\".beanmanager]",
        "jboss.deployment.subunit.\"batch-ear.ear\".\"batch-ejb.jar\".batch.artifact.factory is missing [jboss.deployment.subunit.\"batch-ear.ear\".\"batch-ejb.jar\".beanmanager]"
    ]
}
```

I'll attach the reproducer to the JIRA.

**Comment by jamezp** [comment]
Actually we need a new JIRA for this if it's still an issue.

**Comment by treblereel** [comment]
retest this please

**Comment by treblereel** [comment]
retest this please

**Comment by treblereel** [comment]
retest this please

**Comment by jamezp** [comment]
See https://issues.jboss.org/browse/WFLY-10655?focusedCommentId=13635942&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13635942 for details on what the issue is. We need to decide what the solution should be. Either way we shouldn't activate JSF based on the `@Resource` annotation.

**Comment by jamezp** [comment]
I'm going to close this for now as it seems the PR can't build. Once fixed please feel free to reopen.

**Pull request closed without merging**
