### PR TITLE
[WFLY-6653] The default min and max pool size of -1 is confusing

### PR DESCRIPTION
**Pull request by bayern39**
https://issues.jboss.org/browse/WFLY-6653

### CODE REVIEW

**Comment by bayern39** [comment]
retest this please

**Comment by bstansberry** [comment]
This kind of change requires a management API version bump (which would probably happen for some other change in the same release anyway) and also requires implementation of a transformer to ensure that a slave host controller running a previous version ends up with a consistent config.

**Comment by bstansberry** [comment]
Never mind; I talked to Jeff and this is ok. No transformer is needed because a legacy server would use 0 and 20 if these attributes are undefined in the profile. The version bump is not needed.

**Comment by bstansberry** [comment]
Jeff, if you decide you'd like this in 10.1, just ping me and I'll change it.

**Comment by n1hility** [comment]
@jmesnil should we throw this into 10.1, it looks fairly harmless?

**Comment by jmesnil** [comment]
@n1hility let's wait for 11. The change is pretty harmless but I prefer to wait for 11 to update the management model for consistency sake.

**Comment by mnovak1** [comment]
@jmesnil Do you think this could be merged now?

**Comment by jmesnil** [comment]
@mnovak1 Yes, it can now be merged for WFLY11. 

A resource transformer is not needed and there will be a management version bump for the messaging-activemq (in another PR though).

**Comment by mnovak1** [comment]
@jmesnil Cool! Thanks for info

**Comment by jmesnil** [comment]
@bayern39 could you create a corresponding PR for EAP7 please? We require one before we can merge this PR in WildFly.

**Comment by bayern39** [comment]
@jmesnil  OK

**Comment by kabir** [comment]
Retest this please

**Comment by bayern39** [comment]
Retest this please

**Pull request merged**
