### PR TITLE
WFLY-9488: Do not overwrite existing services for additional BDAs.

### PR DESCRIPTION
**Pull request by mkouba**
- except for ResourceLoader of the eventual boostrap classloader BDA
- upstream issue: https://issues.jboss.org/browse/WFLY-9488

### CODE REVIEW

**Comment by mkouba** [comment]
@papegaaij @klaasjan It would be great if you could verify this PR with your application.

**Comment by klaasjan** [comment]
Tried to verify your PR "as is", but discovered a new bug in WF12 serialization.
I applied your PR's last commit (which contains the fix) on a 'vanilla' WF 11.0.0 tree and built that. This fixes the BDA problem from WFLY-9488.

**Comment by mkouba** [comment]
@klaasjan Ok, thanks! Did you file a new WF12 serialization issue? Is it Weld-related?

**Comment by klaasjan** [comment]
@mkouba currently looking into it. It looks jboss-marshalling related. Will file a report when we have more info

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
