### PR TITLE
WFLY-12150: make attributes with default values optional

### PR DESCRIPTION
**Pull request by michpetrov**
Wildfly issue: [WFLY-12150](https://issues.jboss.org/browse/WFLY-12150)
Wildfly Core issue: [WFCORE-2252](https://issues.jboss.org/browse/WFCORE-2252)
WFCORE PR: wildfly/wildfly-core#3773

this needs to be merged before the core PR

### CODE REVIEW

**Review by darranl — DISMISSED** [review]
As this PR is against the WildFly repository can you please create a WFLY Jira issue and use it for this PR and commit messages.

**Comment by michpetrov** [comment]
@darranl updated

**Comment by bstansberry** [comment]
retest this please

**Comment by kabir** [comment]
@michpetrov Needs a rebase

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
