### PR TITLE
[WFLY-10726] (Test) Need to override getParameterValues in SPFormAuth…

### PR DESCRIPTION
**Pull request by spyrkob**
…enticationRequestWrapper

JIRA: https://issues.jboss.org/browse/WFLY-10726

**Note: This is a test for a fix in picketlink and requires picketlink upgrade containing https://github.com/jbossas/redhat-picketlink-bindings/pull/49**
----

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

### CODE REVIEW

**Comment by kabir** [comment]
@spyrkob Adding the hold label until we have the upgrade

**Comment by kabir** [comment]
@spyrkob Why is this PR opened without the required upgrade?

**Comment by spyrkob** [comment]
@kabir sorry, I didn't know the process here - in future is it better to wait until the new version of component is released and merged before opening test PRs for it?

**Comment by kabir** [comment]
Yes

**Comment by jamezp** [comment]
I'm closing this based on the missing picketlink upgrade.

**Pull request closed without merging**
