### PR TITLE
[WFLY-16294] javax.orb.api module must explicitly define its dependency on jdk.unsupported module

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-16294

### CODE REVIEW

**Comment by ropalka** [comment]
@tadamski please review

**Comment by bunckelvhv** [comment]
@ropalka I can't comment on the line 24 `<module xmlns="urn:jboss:module:1.5" name="javax.orb.api">` Is 1.5 a must here? Or simply not updated to 1.9 yet?

**Comment by ropalka** [comment]
I would guess not updated to 1.9 yet @bunckelvhv

**Review by tadamski — APPROVED** [review]
LGTM

**Pull request merged**
