### PR TITLE
[WFLY-18353] Update TestCustomPrincipalTransformer to no longer rely on the Elytron subsystem

### PR DESCRIPTION
**Pull request by jessicarod7**
https://issues.redhat.com/browse/WFLY-18353

This fix is also needed to fully implement wildfly/wildfly-core#5561.

### CODE REVIEW

**Review by fjuma — CHANGES_REQUESTED** [review]
Thanks @cam-rod! Just a very minor comment, would be good to update the commit message and issue title to something like "Update the TestCustomPrincipalTransformer to no longer rely on the elytron subsystem".

Would you be able to check if we can also remove the `org.wildfly.core.wildfly-elytron-integration` test dependency now too?

**Comment by cam-rod** [comment]
> Thanks @cam-rod! Just a very minor comment, would be good to update the commit message and issue title to something like "Update the TestCustomPrincipalTransformer to no longer rely on the elytron subsystem".
> 
> Would you be able to check if we can also remove the `org.wildfly.core.wildfly-elytron-integration` test dependency now too?

Updated the title and removed the subsystem dependency

**Comment by fjuma** [comment]
@cam-rod Looks like there are some compilation failures.

**Comment by cam-rod** [comment]
Thanks for the heads up, looks like the CredentialStore tests were trying to reuse a subsystem error message. I directly copied the string over and everything seems fine now.

**Review by fjuma — APPROVED** [review]
Thanks @cam-rod!

**Comment by bstansberry** [comment]
Thanks @cam-rod and @fjuma

**Pull request merged**
