### PR TITLE
WFLY-10461 Infinispan component upgrade to 9.2.4.Final

### PR DESCRIPTION
**Pull request by scottmarlow**
https://issues.jboss.org/browse/WFLY-10461

Please merge after https://github.com/wildfly/wildfly/pull/11288, not a strict requirement but would be nice to have all of these changes together.

@pferraro are you okay with this upgrade getting merged?

### CODE REVIEW

**Comment by scottmarlow** [comment]
doesn't look like 9.2.4 is uploaded yet but is tagged https://github.com/infinispan/infinispan/releases

**Comment by pferraro** [comment]
@scottmarlow :+1:  The upgrade will also fix WFLY-10391.

**Comment by scottmarlow** [comment]
retest this please

**Review by rhusar — APPROVED** [review]

**Comment by rhusar** [comment]
@scottmarlow Please always link the change long in component upgrade Jiras. Makes everybody's live, especially reviewers, easier :-)

**Review by pferraro — APPROVED** [review]

**Comment by scottmarlow** [comment]
thanks @rhusar

**Pull request merged**
