### PR TITLE
WFLY-5418: start-delivery/stop-delivery operations descriptions are m…

### PR DESCRIPTION
**Pull request by treblereel**
…issing from MDB deployment in domain mode

### CODE REVIEW

**Comment by jmesnil** [comment]
this looks good to me except for the import changes. I am not sure but I think that our check style will complain if it has unused import (and Javadoc comments does not count)...

**Comment by bstansberry** [comment]
this is ok to test

**Comment by bstansberry** [comment]
We require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to the these terms?

**Comment by treblereel** [comment]
As a member of Jboss SET Team I would like to say, yes I am agree

**Comment by treblereel** [comment]
As a member of Jboss SET Team I would like to say, yes I am agree

**Comment by bstansberry** [comment]
Ah, sorry. I had a feeling I didn't need to ask that question and then was blind and didn't see the "Red Hat" when I looked at your profile. :(

**Comment by treblereel** [comment]
no worries, I like to think that -- #iamredhat :-)

**Pull request merged**
