### PR TITLE
[WFLY-5356] Upgrade Artemis to 1.1.0

### PR DESCRIPTION
**Pull request by jmesnil**
JIRA: https://issues.jboss.org/browse/WFLY-5356

**Please do not merge this PR. This depends on an Apache staging repository that provides the release candidate RC4 for Artemis 1.1.0**

Once Artemis is officially released, I'll update this PR to remove the Apache staging repository.

### CODE REVIEW

**Comment by scottmarlow** [comment]
thanks Jeff, I'll do some testing of this PR as well.

**Comment by scottmarlow** [comment]
I didn't see any failures, this would work if you merged it (after it is released of course)

**Comment by n1hility** [comment]
Oops got a little trigger happy with this one

**Comment by n1hility** [comment]
submit a new PR when it is ready

**Pull request merged**
