### PR TITLE
[WFLY-16468] The microprofile-opentracing layer is redundant

### PR DESCRIPTION
**Pull request by jasondlee**
https://issues.redhat.com/browse/WFLY-16468

Combine "open-tracing" and "microprofile-opentracing" into the latter
Remove the "open-tracing" layer
Adjust references to the "open-tracing" layer to point to new combined layer

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]

**Comment by jasondlee** [comment]
@jfdenise Would you mind taking a look at this to make sure we've not missed anything relevant?

**Comment by jfdenise** [comment]
@jasondlee , I am fine with the removal. We are not directly dealing with the open-tracing layer in the cloud context or bootable JAR context. I just found occurrence of it in some tests based on WF26.

**Review by jfdenise — APPROVED** [review]

**Comment by jasondlee** [comment]
> @jasondlee , I am fine with the removal. We are not directly dealing with the open-tracing layer in the cloud context or bootable JAR context. I just found occurrence of it in some tests based on WF26.

Which tests were they? I searched and didn't see anything that looked relevant, but I may not have used the right keywords.

**Comment by jfdenise** [comment]
Some cloud tests: https://github.com/wildfly/wildfly-s2i/blob/wf-26.0/wildfly-modules/tests/features/s2i.feature#L176, not related to WF.

**Comment by bstansberry** [comment]
Thanks, @jasondlee

**Pull request merged**
