### PR TITLE
WFLY-5945/WFLY-5946 immutable-entity and naturalid cache configurations are not started by the JPA subsystem

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-5945
https://issues.jboss.org/browse/WFLY-5946

### CODE REVIEW

**Comment by bstansberry** [comment]
Does pending-puts need to be included? AIUI the perf guys are overriding the pending-puts config to ensure SimpleCache is used.

**Comment by pferraro** [comment]
@bstansberry No, because the pending-puts cache configuration is effectively hard-coded and is not configurable.  I'm not sure what the perf guys are doing, but that isn't going to work according to how the hibernate region factory is currently implemented. See: https://github.com/hibernate/hibernate-orm/blob/master/hibernate-infinispan/src/main/java/org/hibernate/cache/infinispan/InfinispanRegionFactory.java#L224
https://github.com/hibernate/hibernate-orm/blob/master/hibernate-infinispan/src/main/java/org/hibernate/cache/infinispan/InfinispanRegionFactory.java#L392

**Comment by n1hility** [comment]
@pferraro pending puts was made configurable in the 5.0 branch

**Comment by n1hility** [comment]
@pferraro see https://github.com/hibernate/hibernate-orm/pull/1145

**Comment by rvansa** [comment]
@pferraro Yes, pending-puts cache configuration needs to be inserted into the cache manager, otherwise it will use the default configuration https://github.com/hibernate/hibernate-orm/blob/5.0/hibernate-infinispan/src/main/java/org/hibernate/cache/infinispan/InfinispanRegionFactory.java#L393 . And WF should always define this, there's no point in using the ORM's default (which is there because of ispn 7.x).

Not understanding the subsystem configuration too much, I wonder why these dependencies need to be defined explicitly - why aren't all cache configurations in WF config defined in given cache manager?

**Comment by pferraro** [comment]
@rvansa because cache configurations are installed on demand.  If nothing demands it to start, it is never installed.

**Comment by scottmarlow** [comment]
WFLY-5953 is for pending-puts

**Comment by rvansa** [comment]
@pferraro So, if I define in persistence.xml that class `foo.Bar` should use cache configuration `foos`, and define cache `foos` in WF config, it will still rather use default cache configuration (and I mean the default cache set from ISPN perspective) as ORM will request cache `foos` and as it has no special configuration (because nobody demanded `foos` to be installed)?

**Comment by pferraro** [comment]
@scottmarlow I had already opened https://issues.jboss.org/browse/WFLY-5951

**Comment by pferraro** [comment]
@rvansa Is there a particular reason why the pending-puts cache name is hardcoded? The other cache configuration names are configurable.

**Comment by scottmarlow** [comment]
@pferraro I have a local change to add pending-puts (its a little funky since Hibernate doesn't offer the same constants for pending-puts).   I also added some WF trace logging that is helpful for finding the cause, which is that we are only adding persistence unit service dependencies for entity/local-query/pending-puts.  Since we don't add dependencies on the immutable-entity/timestamps services, they don't start.

**Comment by scottmarlow** [comment]
In HibernateSecondLevelCache, I think that instead of:
cacheSettings.put(IMMUTABLE_ENTITY, mutableProperties.getProperty(InfinispanRegionFactory.IMMUTABLE_ENTITY_CACHE_RESOURCE_PROP, InfinispanRegionFactory.DEF_ENTITY_RESOURCE));

We need:
cacheSettings.put(IMMUTABLE_ENTITY, mutableProperties.getProperty(InfinispanRegionFactory.IMMUTABLE_ENTITY_CACHE_RESOURCE_PROP, InfinispanRegionFactory.DEF_IMMUTABLE_ENTITY_RESOURCE));

**Comment by pferraro** [comment]
@scottmarlow I'm anticipating https://github.com/hibernate/hibernate-orm/pull/1208
The immutable entity cache configuration should default to the entity cache configuration if no explicit immutable-entity cache configuration was defined.

**Comment by rvansa** [comment]
@pferraro Are you asking why is the *name* or *default configuration* hardcoded? Both were hard-coded historically, and I just did not change that (haven't seen any reason). In the past, there was only single pending-puts cache with hard-coded configuration. Now this is the configuration used in the same way as entity cache; the configuration is copied to a cache created per-entitiy, and this per-entity cache has name *entity-name*-pending-puts.
The configuration was hard-coded in the past, too, but since we've allowed to configure this in micro-release, I could not just add the default configuration into the default configuration file, because it would break with user-provided configuration file. So, the hard-coded configuration is inserted when it's not defined there.

Anyway, about the custom cache configuration - can the dependency be added anywhere in config?

**Comment by scottmarlow** [comment]
https://github.com/scottmarlow/wildfly/tree/2lc_setup has a hack for pending-puts.  @pferraro let me know if you have something different in mind.  We also need to add trace logging, so we don't have to debug next time.

**Comment by scottmarlow** [comment]
with my local testing, my above change is not right yet.  If I deploy the test (quickstart) app with default WildFly settings, I get missing dependency deployment errors:
 "jboss-as-hibernate4Test.war#primary\" is missing [jboss.infinispan.hibernate.pending-puts.config]"

If I add the following to the cache-contain for "hibernate", the error goes away:
                <local-cache name="pending-puts">
                    <transaction mode="NONE"/>
                    <eviction strategy="NONE"/>
                    <expiration max-idle="60000"/>
                </local-cache>

**Comment by scottmarlow** [comment]
https://github.com/wildfly/wildfly/pull/8549

**Pull request merged**
