### PR TITLE
Fix for WFLY-17854, WFLY-17855, Upgrade Galleon to 5.1.0.Final, Galleon Plugins to 6.4.0.Final and Bootable JAR to 9.0.0.Final

### PR DESCRIPTION
**Pull request by jfdenise**
Issue: https://issues.redhat.com/browse/WFLY-17854
Issue: https://issues.redhat.com/browse/WFLY-17855

### CODE REVIEW

**Comment by jfdenise** [comment]
The failues are caused by Bootable JAR and WildFly maven plugin (Cloud test suite) that need an upgrade. Working on it.

**Comment by jfdenise** [comment]
retest this please!

**Comment by bstansberry** [comment]
@jfdenise I put the 29.Alpha1 label on this, since AIUI it is not required for WF 28. If it is needed for 28, or you get Cloud Tests passing by my start of day on Monday April 10, then please change the label to 28.x and ping me in zulip.

**Comment by jfdenise** [comment]
retest this please!

**Comment by jfdenise** [comment]
retest this please!

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @jfdenise

**Pull request merged**
