### PR TITLE
WFLY-18399 Upgrade to Hibernate 6.2.8.Final release

### PR DESCRIPTION
**Pull request by scottmarlow**
https://issues.redhat.com/browse/WFLY-18399 for the Hibernate ORM upgrade to 6.2.8
https://issues.redhat.com/browse/WFLY-18307 for the ByteBuddy upgrade to 1.14.7

### CODE REVIEW

**Comment by Sanne** [comment]
@scottmarlow could we also upgrade ByteBuddy to match the version we build with?

It will improve some details regarding compatibility with Java 21.

**Comment by scottmarlow** [comment]
> @scottmarlow could we also upgrade ByteBuddy to match the version we build with? We're using version `1.14.7` in this version of Hibernate ORM.
> 
> It will improve some details regarding compatibility with Java 21.

@Sanne yes, definitely!  I just requested that on https://github.com/wildfly/wildfly/pull/17061 that was upgrading to `1.14.5`, so if that bumps to `1.14.7`, I think we are good.

**Comment by Sanne** [comment]
Ok that works for me, but considering ORM "owns" the Bytebuddy dependency (Last time I checked we were the only users), wouldn't it be simpler for you to regulalry update both at once in the same commit?

That way, should you need forwards/backwards ports, you'll also remember more easily that they need to go together.

As you wish though - just a suggestion ;)

**Comment by scottmarlow** [comment]
> Ok that works for me, but considering ORM "owns" the Bytebuddy dependency (Last time I checked we were the only users), wouldn't it be simpler for you to regulalry update both at once in the same commit?
> 
> That way, should you need forwards/backwards ports, you'll also remember more easily that they need to go together.
> 
> As you wish though - just a suggestion ;)

Done, thanks!

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
