### PR TITLE
[WFLY-7680] Reenable regression tests in MaximumPermissionsTestCase

### PR DESCRIPTION
**Pull request by kwart**
JIRA: https://issues.jboss.org/browse/WFLY-7680

This commit re-enables ignored security manager tests after fixing [WFLY-4882](https://issues.jboss.org/browse/WFLY-4882) in `MaximumPermissionsTestCase` class.

### CODE REVIEW

**Comment by jmesnil** [comment]
Failures look related to the PR

**Comment by kwart** [comment]
I'm going to check it.

**Comment by kwart** [comment]
I don't see a problem in my environment. I've just rebased the commit to latest master, lets see if it's enough.

**Comment by kwart** [comment]
Seems to be passing.

**Comment by kabir** [comment]
Retest this please

**Pull request merged**
