### PR TITLE
[WFLY-16307] Upgrade io.smallrye.config to 2.10.0

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFLY-16307

### CODE REVIEW

**Comment by boris-unckel** [comment]
@kabir This is the patch level update only. I have seen 2.10 is released, too. Shall we upgrade to 2.10 in main?
Second question: The 2.9.1 has not been backported to 26.x. Is this related to the MicroProfile version? Or can we go up to 2.9.2/2.10?

**Comment by kabir** [comment]
@boris-unckel We can upgrade to 2.10 in both places. The next MP version (aligned with jakarta.x) will be in the 3.x series of SmallRye Config. Thank you for looking into this :-)

**Comment by boris-unckel** [comment]
I have to fix the commit message.

**Comment by bstansberry** [comment]
Thanks, @boris-unckel

**Pull request merged**
