### PR TITLE
[WFLY-8138] Upgrade Apache CXF to 3.1.10

### PR DESCRIPTION
**Pull request by rsvoboda**
https://issues.jboss.org/browse/WFLY-8138

### CODE REVIEW

**Comment by asoldano** [comment]
+1

**Comment by rsvoboda** [comment]
exit code 137 (new); exit code 123 (new)  for Linux - @ctomc any idea if it's related to CI issues ?

**Comment by rsvoboda** [comment]
Linux run on Brontes passed without error

**Comment by bstansberry** [comment]
retest this please

**Comment by rsvoboda** [comment]
https://ci.wildfly.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=46743#_ says Caused by: java.io.IOException: No space left on device

**Pull request merged**
