### PR TITLE
WFLY-6363 Upgrade Infinispan to 8.2.2.Final

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-6363

### CODE REVIEW

**Comment by bstansberry** [comment]
If QUEUE_SIZE and QUEUE_FLUSH_INTERVAL were used in 10.0.0.Final, and particularly if they were used in EAP 7.0.0.GA, we can't just ignore them on a domain controller, as the DC has to be able to manage legacy slaves.

**Comment by pferraro** [comment]
@bstansberry Fixed

**Comment by Ladicek** [comment]
Should the commit also include a new XSD, if there's new subsystem version?

Unrelated: I think EAP documentation mentions the replication queue on one or two places. We should probably change that. Suggestions?

**Comment by pferraro** [comment]
@Ladicek There is no change to the schema - only to the model.
As of WF10, we want to discourage users from configuring an Infinispan replication queue, as this functionality is more efficiently handled by the JGroups bundler.

**Comment by pferraro** [comment]
FYI, I've opened https://issues.jboss.org/browse/WFLY-6624 to address these intermittent failures of the web session passivation tests.

**Comment by Ladicek** [comment]
@pferraro Thanks Paul. I think all mgmt model versions have a schema file, but I really don't know the rules. Anyway, with this change, I'd expect the schema to change the `<xs:documentation>` of both `queue-size` and `queue-flush-interval` attributes. The documentation for the 4.1 schema should say that these attributes are ignored, which is a fairly important change compared to 4.0.

**Comment by pferraro** [comment]
@Ladicek There isn't really a 1:1 correlation between schema and model.  In this case, the model changes involve deprecating 2 attributes.  Technically, any schema version can be used to create a current version of the model - so creating a new schema for a documentation change doesn't really make sense.

**Pull request merged**
