### PR TITLE
[WFLY-13445] Upgrade RESTEasy to 3.12.0.Final

### PR DESCRIPTION
**Pull request by ronsigal**
https://issues.redhat.com/browse/WFLY-13445

### CODE REVIEW

**Comment by bstansberry** [comment]
@ronsigal I don't see this release on nexus, e.g. https://repository.jboss.org/org/jboss/resteasy/resteasy-jaxrs/

**Comment by ronsigal** [comment]
Hi @bstansberry,

I created this pull request just to move along https://issues.redhat.com/browse/EAP7-1386 "Incorporate MicroProfile Config in RESTEasy". I expect to do the release tomorrow. Sorry for the confusion. Still getting used to the EAP process guide.

-Ron

**Comment by fabiobrz** [comment]
Hi @ronsigal (and CC @bstansberry) while evaluating this let's keep in mind that there's https://github.com/smallrye/smallrye-open-api/pull/325 to solve the issues with MP OpenAPI that we've had since we added the `standalone.microprofile.profile` - activated by the `-Dts.standalone.microprofile` property - to RESTEasy test suite configuration and that are currently skipped through the `ExpectedFailingBecauseOfSmallRyeMicroprofileOpenApi11` JUnit category.

**Comment by ronsigal** [comment]
Hey @fabiobrz,

My feeling (feel free to disagree) is that, since the standalone.microprofile.profile profile is about testing, it's not that urgent. I'm eager to release RESTEasy 3.12.0.Final (this evening is my plan) to have a little cushion before the feature freeze. @bstansberry, what do you think?

-Ron

**Comment by fabiobrz** [comment]
> Hey @fabiobrz,
> 
> My feeling (feel free to disagree) is that, since the standalone.microprofile.profile profile is about testing, it's not that urgent. I'm eager to release RESTEasy 3.12.0.Final (this evening is my plan) to have a little cushion before the feature freeze. @bstansberry, what do you think?
> 
> -Ron

Hi @ronsigal, definitely not arguing about your point f view, also because you've got a deeper knowledge about the RESTEasy process than I have, for sure. 
My point was just to make visible that RESTEasy test suite in 3.12.0.Final will skip Wildfly integration tests that are failing due to a SmallRye OpenAPI bug when executed with the `microprofile.standalone.profile`. That's all.
My 2 lire :)

**Comment by bstansberry** [comment]
@ronsigal I have no opinion. :) You gentlemen know best.

**Comment by ronsigal** [comment]
I have tagged and uploaded RESTEasy 3.12.0.Final. I ran a bunch of tests, as described here: https://issues.redhat.com/browse/RESTEASY-2583

**Comment by ronsigal** [comment]
Besides upgrading RESTEasy, I also bumped <version.com.fasterxml.jackson> to 2.10.4. That was at @asoldano's suggestion.

**Review by asoldano — APPROVED** [review]
Thanks Ron

**Comment by ronsigal** [comment]
Thanks, @bstansberry.

**Pull request merged**
