### PR TITLE
WFLY-11749 : Upgrade Hibernate ORM from 5.3.7 to 5.3.8

### PR DESCRIPTION
**Pull request by gbadner**
https://issues.jboss.org/browse/JBEAP-15805
https://issues.jboss.org/browse/WFLY-11749

### CODE REVIEW

**Comment by scottmarlow** [comment]
+1 pending test results :)

**Comment by gsmet** [comment]
Please hold for this one, we will push ByteBuddy 1.9.5 instead.

**Comment by gbadner** [comment]
I just force-pushed a commit that includes the upgrade to ByteBuddy 1.9.5.

**Comment by scottmarlow** [comment]
+1

**Pull request merged**
