### PR TITLE
[WFLY-18604][WFLY-18681] re-evaluated test exclusions for ts.preview and ts.bootable.preview profiles

### PR DESCRIPTION
**Pull request by istudens**
Issue:
https://issues.redhat.com/browse/WFLY-18604
https://issues.redhat.com/browse/WFLY-18681

### CODE REVIEW

**Comment by istudens** [comment]
retest this please

**Comment by bstansberry** [comment]
@istudens This looks fine but needs a rebase and needs to be moved out of draft state.

**Comment by istudens** [comment]
The clustering tests fail due to a weird CNFE issue. 
```
  java.lang.NoClassDefFoundError: okio/BufferedSource
    at okhttp3.internal.Util.<clinit>(Util.java:69)
    at okhttp3.RequestBody.create(RequestBody.java:140)
    at okhttp3.RequestBody.create(RequestBody.java:133)
    at org.infinispan.client.rest.impl.okhttp.RestClientOkHttp.<clinit>(RestClientOkHttp.java:68)
    at org.infinispan.client.rest.RestClient.forConfiguration(RestClient.java:100)
    at org.infinispan.server.test.core.ForkedInfinispanServerDriver.getRestClient(ForkedInfinispanServerDriver.java:273)
    at org.infinispan.server.test.core.ForkedInfinispanServerDriver.stop(ForkedInfinispanServerDriver.java:136)
    at org.infinispan.server.test.core.AbstractInfinispanServerDriver.stop(AbstractInfinispanServerDriver.java:183)
    at org.infinispan.server.test.core.TestServer.stopServerDriver(TestServer.java:45)
    at org.infinispan.server.test.junit4.InfinispanServerRule$1.evaluate(InfinispanServerRule.java:75)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
    at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
    at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
  Caused by: java.lang.ClassNotFoundException: okio.BufferedSource
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
    ... 22 more
```
This looks weird as both `okio.BufferedSource` and `okhttp3.internal.Util` are located in the same `com.squareup.okhttp3` module (although in two separate resource jars of it). It does not matter which test is executed first, it always fails due to this issue.

**Comment by bstansberry** [comment]
@istudens That stack trace shows a client side failure, so the server side module doesn't matter. So it sounds like a missing dependency in the testsuite/integration/clustering module.

**Comment by bstansberry** [comment]
No idea why only ts.preview would be affected though.

**Comment by istudens** [comment]
@bstansberry Thanks, Brian. I missed that line. It looks, however, it might work with the dependency added to the testsuite/integration/clustering/pom.xml.

**Comment by istudens** [comment]
I've added test dependency on com.squareup.okio.okio needed for ejb/timer/remote test-cases which are executed within multiple surefire executions (not only within ts.surefire.clustering.ha).

@pferraro @bstansberry can you review this please? thanks

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @istudens!

**Pull request merged**
