### PR TITLE
WFLY-3064 Removing SwitchIdentityTestCase.java because the alternativ…

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/WFLY-3064

### CODE REVIEW

**Comment by jamezp** [comment]
The `org.jboss.as.test.integration.ejb.container.interceptor.security.api.SwitchIdentityTestCase` needs to be fixed because it references this test. Also there seems to be a lot of duplication between the tests so there should be some analysis on what other components of the test can be deleted.

**Comment by RanabirChakraborty** [comment]
The `org.jboss.as.test.integration.ejb.container.interceptor.security.api.SwitchIdentityTestCase ` has been deplicated from the SwitchIdentityTestCase to demonstrate the new API that should be used.

**Comment by jamezp** [comment]
@RanabirChakraborty If we're going to remove the test we may as well just reconfigure the test to use the new API. At a minimum we need to analyze what other types can be deleted. Also the test won't currently compile because of the dependency of old test on the new test.

**Comment by jamezp** [comment]
This seems okay to me, but @darranl can you give this the okay?

**Comment by RanabirChakraborty** [comment]
@bstansberry Can you please look into this.

**Comment by bstansberry** [comment]
@RanabirChakraborty I'll defer to James and @darranl or @fjuma on this.

**Comment by fjuma** [comment]
@RanabirChakraborty Just wondering if the following files are really still needed in the `testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/container/interceptor/security` directory now that `org.jboss.as.test.integration.ejb.container.interceptor.security.SwitchIdentityTestCase` has been deleted:

* ServerSecurityInterceptor.java
* jboss-ejb3.xml
* permissions.xml

**Comment by RanabirChakraborty** [comment]
> @RanabirChakraborty Just wondering if the following files are really still needed in the `testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/container/interceptor/security` directory now that `org.jboss.as.test.integration.ejb.container.interceptor.security.SwitchIdentityTestCase` has been deleted:
> 
> * ServerSecurityInterceptor.java
> * jboss-ejb3.xml
> * permissions.xml
> 
> Also, it seems like the rest of the files in the `security` directory could just be moved to the `api` directory now.

Okay, sure I'll check on it. Thank you :)

**Comment by RanabirChakraborty** [comment]
@fjuma Thanks for the suggestions! I have changed accordingly

**Comment by kabir** [comment]
@RanabirChakraborty there seems to be problem compiling

**Comment by RanabirChakraborty** [comment]
@kabir Thank you! I have modified it :)

**Comment by RanabirChakraborty** [comment]
Thank you @kabir ! I have modified it and all the checks have passed.

**Review by fjuma — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks, @RanabirChakraborty

**Pull request merged**
