### PR TITLE
[WFLY-5076] WS-Trust/STS tests migrated from JBossWS testsuite

### PR DESCRIPTION
**Pull request by jbliznak**
- new surefire forked execution added so that javax.net.ssl.\* settings
  don't influence other tests

### CODE REVIEW

**Comment by ctomc** [comment]
JKS files should not be part of code repository as they are hard to be maintained.
They should be generated as part of testsuite, similarly as we do for all other key stores.
see keytool-maven-plugin usage in build

**Comment by stuartwdouglas** [comment]
This is ok to test

**Comment by stuartwdouglas** [comment]
@jbliznak do you work for Red Hat?

**Comment by stuartwdouglas** [comment]
In addition to Tomaz comment it looks like the failures are related.

**Comment by jbliznak** [comment]
@stuartwdouglas yes, I work for RH, part-time
I will try to fix these failures and utilize keytool-maven-plugin

**Comment by asoldano** [comment]
Two comments:
1) Jan is from our QA team in Brno, working with Rostislav in WS area
2) with the PR https://github.com/wildfly/wildfly/pull/7935 merged, ws tests should be added to the new ws maven module, not to the basic module.

**Comment by stuartwdouglas** [comment]
Looks like this PR has some IPv6 issues:

Caused by: java.lang.NumberFormatException: For input string: ":1:8080"

**Comment by jbliznak** [comment]
I moved tests to new maven module as per Alessio comment.
I left JKS files in place for now, we can replace them with generated ones for whole module later.

The problem with NumberFormatException was that WF TS is using variables with IPv6 addresses without brackets (like -Dnode0=::1) and they cannot be used in addresses in WSDLs as such. So I left out the maven-resources-plugin execution and introduced simple replacing mechanism. This could be refactored with additional profiles to introduce new IP address variables usable in URLs.

**Comment by jbliznak** [comment]
Apparently, there is still some problem. Trying to reproduce it locally.

**Comment by jbliznak** [comment]
By mistake I formatted code also for non java files before commit which caused the error. All should be fine now (at least locally it works even with -Dipv6)

**Comment by rsvoboda** [comment]
@ctomc @stuartwdouglas can it be merged ?

**Comment by ctomc** [comment]
retest this please

**Pull request merged**
