### PR TITLE
[WFLY-18969] Give the Apache Lucene module access to jdk.unsupported

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-18969

### CODE REVIEW

**Comment by bstansberry** [comment]
@yrodiere Any concerns?

**Review by yrodiere — APPROVED** [review]
I don't see why this removes the comment, but otherwise this makes sense. Thanks!

**Comment by ropalka** [comment]
The comment about fixed JIRA and it's number is not necessary. Git users can gain this information via git blame command if commit is properly documented @yrodiere .

**Comment by yrodiere** [comment]
@ropalka Yes I know of `git blame`. It works until it doesn't, for example when you starting moving lines around. Like in this very PR for example :) https://github.com/wildfly/wildfly/blame/ee60b1e75e31bb1446f2b4045f81be304d857bc6/ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/lucene/main/module.xml#L29

Anyway, I approved the PR, as far as I'm concerned it's good to merge.

**Comment by ropalka** [comment]
You're right @yrodiere !

**Pull request merged**
