### PR TITLE
[WFLY-19644] Upgrade version.jakarta.websocket.jakarta-websocket-api …

### PR DESCRIPTION
**Pull request by soul2zimate**
…from 2.1.0-jbossorg-2 to 2.1.1

Issue: https://issues.redhat.com/browse/WFLY-19644

Upgrade version.jakarta.websocket.jakarta-websocket-api from 2.1.0-jbossorg-2 to 2.1.1

previous PR https://github.com/wildfly/wildfly/pull/17795

### CODE REVIEW

**Comment by bstansberry** [comment]
@ropalka Please review.

**Review by ropalka — APPROVED** [review]

**Comment by ropalka** [comment]
The upgrade is correct @bstansberry

**Comment by bstansberry** [comment]
Thanks @soul2zimate and @ropalka

**Pull request merged**
