### PR TITLE
[WFLY-14930] Remove legacy feature packs and the builds and dists pro…

### PR DESCRIPTION
**Pull request by bstansberry**
…duced from them

https://issues.redhat.com/browse/WFLY-14930

### CODE REVIEW

**Review by rhusar — CHANGES_REQUESTED** [review]
I am afraid you also need to remove a couple of `org.jboss.as.subsystem.test.AbstractSubsystemBaseTest#testSchemaOfSubsystemTemplates` calls.

**Comment by bstansberry** [comment]
Thanks, @rhusar. I wonder why those don't fail locally? Don't really much care though as we'll remove that infrastructure too!

**Comment by darranl** [comment]
Looks like a checkstyle error:

 >[ERROR] /store/work/tc- work/f5da3564a57e9d74/clustering/common/src/test/java/org/jboss/as/clustering/subsystem/ClusteringSubsystemTest.java:36:8: Unused import - org.junit.Test. [UnusedImports]

**Comment by bstansberry** [comment]
@darranl @rhusar seems to be passing npw

**Review by jamezp — APPROVED** [review]

**Review by darranl — APPROVED** [review]
I think we should get this through, looks like it could either cause conflicts later or easily suffer conflicts.

**Review by rhusar — APPROVED** [review]
LGTM now, very exciting!

**Pull request merged**
