### PR TITLE
WFLY-10886: change AbstractJMSContext.getContext from synchronized me…

### PR DESCRIPTION
**Pull request by fbrandaouolinc**
Change AbstractJMSContext.getContext from synchronized method to ConcurrentHashMap for improved performance

https://issues.redhat.com/browse/WFLY-10886

PR for 26.x: https://github.com/wildfly/wildfly/pull/15036

### CODE REVIEW

**Comment by fbrandaouolinc** [comment]
@darranl here is the PR agains main https://github.com/wildfly/wildfly/pull/15036

Reference: https://github.com/wildfly/wildfly/pull/15036

Thanks!

**Comment by bstansberry** [comment]
Hi @fbrandaouolinc -- thanks for your contribution! It looks like this is your first to WildFly, so I have a paperwork question for you:

We require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to the these terms?

**Comment by bstansberry** [comment]
Thanks, @fbrandaouolinc!

**Pull request merged**
