### PR TITLE
[WFLY-16449] Upgrade ASM to 9.3

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-16449

### CODE REVIEW

**Comment by scottmarlow** [comment]
asm.asm module dependencies from searching in EE-9/dist/target:
```
io/smallrye/config/main/module.xml
org/jboss/as/webservices/server/integration/main/module.xml
org/apache/cxf/ws-security/main/module.xml
org/apache/cxf/main/module.xml
org/apache/cxf/services-sts/main/module.xml
org/apache/cxf/impl/main/module.xml
```

**Review by jimma — APPROVED** [review]

**Comment by jimma** [comment]
@scottmarlow  Upgrade to ASM 9.3 is good for webservice. Thanks.

**Comment by ropalka** [comment]
Is ASM upgrade fine from Smallrye PoV @kabir ?

**Review by bstansberry — APPROVED** [review]

**Review by scottmarlow — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @ropalka

**Pull request merged**
