### PR TITLE
[WFLY-5263] Make the JSR77 mbean server plugin filter queryMBeans()

### PR DESCRIPTION
**Pull request by kabir**
https://issues.jboss.org/browse/WFLY-5263

### CODE REVIEW

**Comment by scottmarlow** [comment]
This change isn't ready to merge yet

**Comment by stuartwdouglas** [comment]
Why not?

**Comment by scottmarlow** [comment]
NPE at org.jboss.as.jsr77.managedobject.ManagedObjectHandlerRegistry.queryNames(ManagedObjectHandlerRegistry.java:81) running the JSR77 TCK...

**Comment by scottmarlow** [comment]
Kabir said he was going to look at the NPE in the morning

**Comment by kabir** [comment]
I have worked around the NPE, but let's see what Scott says

**Pull request merged**
