### PR TITLE
WFLY-5393 Using deprecated attribute use-hornetq-store in CLI does not have any effect being set

### PR DESCRIPTION
**Pull request by zhfeng**
https://issues.jboss.org/browse/WFLY-5393

### CODE REVIEW

**Comment by bstansberry** [comment]
Looks good.  JBEAP-1136  will need a separate PR against https://github.com/jbossas/jboss-eap7 -- the 7.x branch.

**Comment by zhfeng** [comment]
Thanks @bstansberry I will send a PR for JBEAP-1136

**Comment by zhfeng** [comment]
It should be sent after the fix has been merged in the upstream, is it right ?

**Comment by bstansberry** [comment]
@zhfeng Please send it now. This fix looks good so the patch is in a state where it's simplest to have both PRs ready, letting Jason merge them when he wants to.

**Pull request merged**
