### PR TITLE
[WFLY-4902] Upgrade to Artemis 1.1.0-wildfly-1

### PR DESCRIPTION
**Pull request by jmesnil**
_Please do not merge this PR without @n1hility's approval._

Artemis community is currently voting for the release of their 1.1.0 version and if the vote is positive, the release should be available on thursday morning and could be used for WFLY 10 CR1.

If the Artemis 1.1.0 release is ready on time, I'll close this PR and open one with the Apache 1.1.0 release.Otherwise, this PR will be merged as it correspond to a fork of Artemis (tagged 1.1.0-wildfly-1  in our [wildlfy organization's fork](https://github.com/wildfly/activemq-artemis)) that we can integrate in WildFly.

In any case, this PR can be reviewed as there is no API change between the candidate 1.1.0 release and this 1.1.0-wildfly-1 fork.

### CODE REVIEW

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
Windows failure are caused by https://issues.apache.org/jira/browse/ARTEMIS-219

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
@n1hility , this PR can be reviewed.

The test failure (TxTimeoutTestCase.test_negativeTxTimeoutVerifyReaperThreadCanceledTxTest ) looks unrelated to the PR.

The integrated version of Artemis is 1.1.0-wildfly-3 that is a fork of the current release candidate for the official Artemis 1.1.0 plus a fix to a regression issue in the Artemis resource adapter: https://github.com/apache/activemq-artemis/compare/1.1.0...wildfly:1.1.0-wildfly-3

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
Retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
I think there is some real issue here, as I just can't get a clean run. Looking at some of the intermittent failures I see things like:

&amp#27;[0m&amp#27;[31m02:52:26,575 ERROR [org.apache.activemq.artemis.core.server] (default I/O-1) AMQ224018: Failed to create session: ActiveMQClusterSecurityException[errorType=CLUSTER_SECURITY_EXCEPTION message=AMQ119099: Unable to authenticate cluster user: ACTIVEMQ.CLUSTER.ADMIN.USER]
    at org.apache.activemq.artemis.core.security.impl.SecurityStoreImpl.authenticate(SecurityStoreImpl.java:116)
    at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.createSession(ActiveMQServerImpl.java:935)

and

&amp#27;[0m&amp#27;[31m02:52:27,017 ERROR [org.apache.activemq.artemis.core.client] (Thread-1 (ActiveMQ-server-ActiveMQServerImpl::serverUUID=340dedf8-5756-11e5-aba0-cb4cd8725ce2-11063078)) AMQ214017: Caught unexpected Throwable: java.lang.NullPointerException
    at org.apache.activemq.artemis.core.server.cluster.ClusterControl.authorize(ClusterControl.java:76)
    at org.apache.activemq.artemis.core.server.cluster.impl.ClusterConnectionImpl.onConnection(ClusterConnectionImpl.java:484)
    at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.getConnection(ClientSessionFactoryImpl.java:863)
    at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.getConnectionWithRetry(ClientSessionFactoryImpl.java:745)
    at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.connect(ClientSessionFactoryImpl.java:231)
    at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.createSessionFactory(ServerLocatorImpl.java:791)
    at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.connect(ServerLocatorImpl.java:649)
    at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.connect(ServerLocatorImpl.java:636)
    at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl$4.run(ServerLocatorImpl.java:1480)
    at org.apache.activemq.artemis.utils.OrderedExecutorFactory$OrderedExecutor$1.run(OrderedExecutorFactory.java:94)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by jmesnil** [comment]
I don't think the failure was related to the PR. The warnings (and ugly NPE...) are due to the lack of messaging cluster authentication. The node see each other but can not authenticate. I've added a commit to fix the server configuration (by passing a common `jboss.messaging.cluster.password`).

I had a clean run with that change. I'll retest it once more for confirmation

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Pull request merged**
