### PR TITLE
[WFLY-17146][WFLY-17147][WFLY-17148] Jastow components upgrade to latest versions

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-17146
https://issues.redhat.com/browse/WFLY-17147
https://issues.redhat.com/browse/WFLY-17148

### CODE REVIEW

**Comment by bstansberry** [comment]
@ropalka What are these upgrades bringing?

https://issues.redhat.com/projects/UNDERTOW/versions/12396157 is empty.

https://issues.redhat.com/projects/UNDERTOW/versions/12393493 isn't so important as we only use the lib to compile, but it links to an issue with an unmerged PR.

Putting a RN and/or github diff link in the JIRA description is what we generally ask for.

**Comment by ropalka** [comment]
Hello @bstansberry my fault, I forgot to add diff and tag info to relevant jastow upgrade JIRAs - fixed.
Generally speaking there is no functionality change in both releases.  The diffs are:
 * Jastow 2.2.4 - requires JDK 11 to build and compile , Java EE API stuff was eliminated there and updated project deps
 * Jastow 2.0.12 - requires JDK 1.8 to build and compile , Jakarta EE API stuff was eliminated there  and updated project deps
Today I run Jakarta 10 TCK for this PR and I can confirm everything passed on 100%.

**Review by bstansberry — APPROVED** [review]
Thanks, @ropalka

**Comment by bstansberry** [comment]
Thanks @ropalka

**Pull request merged**
