### PR TITLE
WFLY-6192 additional permissions for JAXBUsageTestCase

### PR DESCRIPTION
**Pull request by istudens**
https://issues.jboss.org/browse/WFLY-6192

### CODE REVIEW

**Comment by istudens** [comment]
retest this please

**Comment by stuartwdouglas** [comment]
I don't think this is the correct approach, it looks like adding these permissions is just hiding the underling problem.

**Comment by istudens** [comment]
@stuartwdouglas I've replied to the WFLY-6192, please check my comment there.Thanks.

**Comment by kabir** [comment]
Added hold label to stop myself from accidentally merging this. @istudens Please le me know if the status changes

**Comment by kabir** [comment]
@istudens @stuartwdouglas any update on this?

**Comment by kabir** [comment]
@istudens basically what Stuart is saying (now that I've looked a bit more in detail at similar cases) is that when deploying something into a WF instance running with a security manager enabled, the user should not need to add permissions to the deployment for it to run if the protected code is called by the deployers. In this case the underlying libraries need to be fixed to use privileged blocks.

If the user's code (i.e. the deployed application) makes calls to something protected on the other hand,  then adding permissions to the deployment is fine.

**Comment by istudens** [comment]
@kabir The issue is that the first protected call on the stack here belongs to JAXB which is unlikely to accept the fix in decent time, take a look at Alessio's comment on Jira. Thus, I would say this is a similar case like Hibernate for example, where we call a protected code but we are obliged to provide additional permissions to it anyway, because it is a thirdparty code we don't control.
Call stack snippet:
```
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:258)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:229)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:136)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:183)
	at org.jboss.as.test.integration.jaxb.JAXBUsageServlet.doGet(JAXBUsageServlet.java:85)
```
Note that our own `AbstractUnmarshallerImpl.unmarshal` is public.

**Comment by stuartwdouglas** [comment]
I think that if we are going to have tests that fail when run under a security manager it would be better to have some kind of utility like org.jboss.as.test.shared.IntermittentFailure to ignore them on security manager runs, rather than just hiding a problem.

**Comment by istudens** [comment]
Ok, I've created SecurityManagerFailure which can be used in cases like these.

**Comment by istudens** [comment]
@stuartwdouglas could you review this please?

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
