### PR TITLE
Utilization of capabilities and requirements

### PR DESCRIPTION
**Pull request by bstansberry**
This PR introduces some utilization of the capabilities/requirements functionality added in WildFly Core.

The first commit is the most significant one, as it introduces use of capabilities/requirements to mediate the interaction between the iiop and transactions subsystems.

The other commits are simpler, replacing how subsystems needing access to the MBeanServer get it from the JMX subsystem.

### CODE REVIEW

**Comment by bstansberry** [comment]
@tadamski  FYI

@jmesnil I can drop the messaging subsystem commit if you intend to remove the runtime stuff anyway. The artemis integration probably needs something similar.

**Comment by jmesnil** [comment]
@bstansberry you can keep the messaging commit: there may be some time before the new messaging-activemq subsystem is integrated *and* the runtime removed from the legacy one. Until then, we can still build on top of this messaging capability if anyone requires it.

**Comment by bstansberry** [comment]
@jmesnil the names are about namespacing.

org.wildfly namespace is owned by the WildFly and WildFly Core projects
org.wildfly.extension namespace is for capabilities not provided by or used by the "kernel"

The org.wildfly part I think is critical.

It's a good discussion for the mailing list whether separating kernel stuff from extension stuff adds any real value. I'll send up a thread.

**Comment by bstansberry** [comment]
The discussion re: names was at http://lists.jboss.org/pipermail/wildfly-dev/2015-June/004084.html

Consensus there was to get rid of the 'extension' bit, so I'm going to close this and redo it. Also https://github.com/wildfly/wildfly-core/pull/824 gets rid of the 'extension' part in core capabilities so this will need to be updated to reflect that.

**Pull request closed without merging**
