### PR TITLE
WFLY-17763 Upgrade to Hibernate ORM 6.2.0.CR4

### PR DESCRIPTION
**Pull request by scottmarlow**
https://issues.redhat.com/browse/WFLY-17763

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
@scottmarlow The Cloud Tests job fails due to https://github.com/wildfly-extras/wildfly-cloud-tests/issues/56, for which I'll send up a PR in a bit.

HHH-16316 would be a possible candidate for a Windup rule to update persistence.xml files, as the change looks to be a matter of repackaging deprecated classes:

org.hibernate.dialect -> org.hibernate.community.dialect

So a rule could either suggest switching to the non-deprecated variant of the dialect, and note that if the unsupported old dialect has been moved to org.hibernate.community.dialect.

**Comment by bstansberry** [comment]
https://github.com/wildfly-extras/wildfly-cloud-tests/pull/57 is to fix the Cloud Tests.

**Comment by bstansberry** [comment]
Thanks @scottmarlow

**Comment by scottmarlow** [comment]
Thanks for addressing the cloud test #57 failure @bstansberry!  

Good point about HHH-16316 ([pr](https://github.com/hibernate/hibernate-orm/pull/6255)), https://github.com/windup/windup-rulesets/blob/master/rules/rules-reviewed/eap8/eap7/hibernate6.windup.xml#L444 does check for removed dialects that are now in the hibernate-community-dialects artifact:

> <dependency>
>     <groupId>org.hibernate.orm</groupId>
>     <artifactId>hibernate-community-dialects</artifactId>
>     <version>6.2.0.CR4</version>
> </dependency>
> 

I think the https://github.com/windup/windup-rulesets/blob/master/rules/rules-reviewed/eap8/eap7/hibernate6.windup.xml#L444 rule could be worded to reflect that the hibernate-community-dialects module is not included (by WildFly) and such should indicate that the persistence.xml is using a removed dialect.

**Pull request merged**
