### PR TITLE
WFLY-15335 Simplify the processing of ejb timer timeout method params

### PR DESCRIPTION
**Pull request by chengfang**
https://issues.redhat.com/browse/WFLY-15335

* change the column definition for `TIMEOUT_METHOD_DESCRIPTOR` in jboss-ejb-timer table from `varchar` to `char`, because the timeout method param can be either 0 or 1. When it's 1, it must be `javax.ejb.Timer`.
* changes in various places to simplify the processing of timeout method and its params, knowing the timeout method parameters can be either 0 or 1. This saves us from having to comparing, concatenating, parsing individual param one by one, or reflectively loading parameter types.
* add `serialVersionUID` to `TimeoutMethod` class to preserve its serialization compatibility.

### CODE REVIEW

**Comment by chengfang** [comment]
@tadamski  please review.

**Review by tadamski — APPROVED** [review]
LGTM

**Comment by bstansberry** [comment]
@chengfang This one has conflicts now.

**Comment by chengfang** [comment]
@bstansberry  thanks for the note. I've resolved conflicts and re-pushed. Waiting to see the test result since there are quite a few conflicts merged.

**Pull request merged**
