### PR TITLE
WFLY-18306 Default Infinispan remote-timeout should not be less than the default lock-timeout

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-18306

### CODE REVIEW

**Comment by darranl** [comment]
Do we really need a schema bump?  Unless we update the parsers to be schema aware regarding default values this change actually impacts all of the older schema versions.  Maybe just the model bump so tranformers can at least be correct?

**Comment by pferraro** [comment]
> Do we really need a schema bump? Unless we update the parsers to be schema aware regarding default values this change actually impacts all of the older schema versions. Maybe just the model bump so tranformers can at least be correct?

Technically, the default value as defined in the XSD would be wrong otherwise - but I get your point, that configuration migrated from an older version will have the new default applied - contrary to the default value defined in those schemas.
So, maybe the XSD version bump is unnecessary?

**Review by bstansberry — APPROVED** [review]

**Review by rhusar — APPROVED** [review]
👍🏼 LGTM!

**Comment by bstansberry** [comment]
Thanks @pferraro @darranl and @rhusar 

If it turns out we don't need the 17.1 api version we should tweak this before we release WF 30.

**Pull request merged**
