### PR TITLE
WFCORE-1169 JBEAP-2054 make ps1 scripts work from non bin directory

### PR DESCRIPTION
**Pull request by ctomc**
…lower case drive letter (Windows)

### CODE REVIEW

**Comment by bstansberry** [comment]
@stuartwdouglas please approve the undertow template change.

**Comment by stuartwdouglas** [comment]
I think this should be the actual fix, however I am not in front of a windows computer to test it out: https://github.com/wildfly/wildfly/compare/master...stuartwdouglas:WFCORE-1169  (if this does fix it the JIRA will need to be moved etc).

As it stands there will also be issues if JBOSS_HOME contains a symlink as part of the path.

@ctomc can you test this out?

**Comment by ctomc** [comment]
@stuartwdouglas sorry I somehow missed this notification.
Your fix does fix the problem with welcome content, but that is actually workaround for wrongly set ${jboss.home.dir} which comes from startup scripts.
anywhere else in server, jboss.home.dir system property value is still wrong and we might end up with similar problems in other parts of server because of that.
As such I am not fan of workarounds for this.

**Comment by bstansberry** [comment]
@ctomc @stuartwdouglas Is the answer then to change this PR to drop the change to undertow/src/main/resources/subsystem-templates/undertow.xml and just focus on the scripts? Stuart's undertow change to use canonical paths is merged and AFAIK makes the template change unnecessary.

**Comment by ctomc** [comment]
updated PR to remove the undertows change, this is just about scripts now.

**Pull request merged**
