### PR TITLE
Add mixed domain tests

### PR DESCRIPTION
**Pull request by kabir**
https://issues.jboss.org/browse/WFLY-9633

This needs https://github.com/wildfly/wildfly-core/pull/3008 (https://issues.jboss.org/browse/WFCORE-3472) merged and released before it will pass.

testExplodedDeployment() can not  pass on 7.1.0 due to https://issues.jboss.org/browse/WFCORE-3479. and has been conditionally ignored. https://issues.jboss.org/browse/WFLY-9634 has been opened to reenable it.

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
@kabir EAP 7.x tests failed.

**Comment by kabir** [comment]
@ctomc The errors seem to be that 7.1.0 is not in the old versions on the server?

```
[08:53:46][Step 2/3] org.jboss.as.test.integration.domain.mixed.eap710.MixedDomainOverlay710TestSuite  Time elapsed: 0.003 sec  <<< ERROR!
[08:53:46][Step 2/3] java.lang.RuntimeException: java.lang.RuntimeException: Old version not found in /store/legacy-as/jboss-eap-7.1.0.zip
````
CC @bstansberry

**Comment by ctomc** [comment]
@kabir @bstansberry all fixed and passing

**Pull request merged**
