### PR TITLE
[WFLY-15586] Upgrade spullara.mustache.java 0.9.10

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFLY-15586

### CODE REVIEW

**Comment by darranl** [comment]
@boris-unckel sorry another merge conflict.

**Comment by boris-unckel** [comment]
@fl4via Could you check this PR, please?
@darranl fyi merge conflict is resolved

**Review by fl4via — APPROVED** [review]
As far as I can see (a diff in relases from 0.9.6 to 0.9.10 can be seen here: https://github.com/spullara/mustache.java/compare/mustache.java-0.9.6...0.9.10 ) this upgrade should be fine

**Comment by bstansberry** [comment]
Thanks, @boris-unckel

**Pull request merged**
