### PR TITLE
[JBWS-3865] Add ability to consume jboss-webservices.xml located in M…

### PR DESCRIPTION
**Pull request by asoldano**
…ETA-INF of EAR archive

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
This means that jboss-webservices.xml in the ear will override the one in the deployment. Is this the intention? It is not really how other deployment descriptors work.

**Comment by stuartwdouglas** [comment]
Oops, I misread the PR and did not notice that the metadata was being merged rather than overriden.

**Comment by asoldano** [comment]
Right, basically the metadata are merged and the inner jar/war metadata override those in the ear.

**Comment by asoldano** [comment]
Thanks!

**Pull request merged**
