### PR TITLE
WFLY-16959 Upgrade smallrye-open-api to 3.0.0-RC4

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-16959

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]

**Comment by pferraro** [comment]
This needs a jandex upgrade (wildfly-core). Adding hold label.

**Comment by Ladicek** [comment]
Hi @pferraro, SmallRye OpenAPI has a Jakarta release based on Jandex 2.x, it's 3.0.0-RC4. The difference between 3.0.0-RC4 and 3.0.0 is the upgrade to Jandex 3. I suggest you upgrade to 3.0.0-RC4 and I'll bump to 3.0.0 in the Jandex 3.0 upgrade PR.

**Comment by bstansberry** [comment]
Thanks @pferraro

**Pull request merged**
