### PR TITLE
[WFLY-4831] Clean up HornetQ modules

### PR DESCRIPTION
**Pull request by jmesnil**

### CODE REVIEW

**Comment by jmesnil** [comment]
Please, do not merge until someone working on the transactions subsystem (@mmusgrov ?) agreed with the change to the `org.jboss.jts`  module. AFAIK, its dependency to `org.hornetq` module was only for its journal code (now provided by the `org.hornetq.journal` module).

**Comment by jmesnil** [comment]
retest this please

**Comment by n1hility** [comment]
@mmusgrov what do you think?

**Comment by mmusgrov** [comment]
@jmesnil @n1hility  Jeff you are correct, we only ever depended on the journal component so the change you have made to depend on org.hornetq.journal module instead is good. Thank you.

**Comment by jmesnil** [comment]
retest this please

**Pull request merged**
