### PR TITLE
Upgrade Narayana to 5.12.4.Final

### PR DESCRIPTION
**Pull request by mmusgrov**
Resolves https://issues.redhat.com/browse/WFLY-15753
The issue link contains the release tag and the changeset and the release notes.

### CODE REVIEW

**Comment by bstansberry** [comment]
@mmusgrov This has a merge conflict. I'd be happy to resolve it via the GH UI if you'd like.

**Comment by mmusgrov** [comment]
Thanks @bstansberry . But wait, note that 5.12.4.Final has introduced a performance regression of the transaction log store. I've been trying to track it down this week (the perf jobs take the best part of a day to run). In other words, if you do merge it then I think we will need another narayana release before 26.0.0 can be released. So maybe it's best to wait for that first.

**Comment by darranl** [comment]
Just added a hold label whilst the regression is reviewed, we can remove once we are ready to proceed.

**Comment by mmusgrov** [comment]
@darranl will you to do the same with https://github.com/wildfly/wildfly/pull/14975 ([WFLY-15548] [WFLY-15446] transaction subsystem: jakarta namespance) please.

**Comment by bstansberry** [comment]
Hi @mmusgrov -- is 5.12.2 a possible interim step? I *think* doing that would unblock #15017

**Comment by bstansberry** [comment]
Thanks, @mmusgrov!

**Pull request merged**
