### PR TITLE
UNDERTOW-1042 Disabling failover with max-attemps ignored

### PR DESCRIPTION
**Pull request by rpelisse**
Issue: https://issues.jboss.org/browse/JBEAP-10145
Upstream Issue: https://issues.jboss.org/browse/UNDERTOW-1042

### CODE REVIEW

**Review by ctomc — APPROVED** [review]

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
I don't really see how this fixes the linked issue? I also don't want to change the default, I think attempting a failover on failure is a resonable default.

**Comment by rpelisse** [comment]
@stuartwdouglas I think I misread somehow [your comment](https://issues.jboss.org/browse/JBEAP-10145?focusedCommentId=13416947&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13416947) on [JBEAP-10145](https://issues.jboss.org/browse/JBEAP-10145):

> I am ok with setting max-retries to zero for the default config.

That being said, I'm completely fine with keeping the current behavior and simply fix the CLI documentation to make it more clear. As far as I understand the issue is mostly about Undertow [behavior not being documented](https://issues.jboss.org/browse/JBEAP-10145?focusedCommentId=13416856&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13416856).

I'll update my PR right away to remove the configuration and only leave the update on the CLI message.

**Comment by stuartwdouglas** [comment]
Ah, I just looked at the Undertow issue and not the JBEAP one.

I will look at updating Undertow to always use the value from max-attempts and ignore max-retries if max-attempts is specified.

**Comment by kabir** [comment]
@rpelisse As this pull request has  been held up for a long time, I am closing it to get the pull request queue under control again. Since this is very old now, it will be a very long time until this one will be addressed. Also, I don't have much time to spend on this to evaluate on a case by case basis.

If this is something important to you or the project please feel free to recreate the pull request. That way it will come on top of the pile again, and be looked at again sooner. 

If it is a new **feature**, please follow the new process for features. Ping @kabir or @jamez if you are unsure what this means, and we can help. Please do that before opening the pull request though.

Sorry for any inconvenience!

**Pull request closed without merging**
