### PR TITLE
WFLY-16022 - bump jackson version to 2.12.6

### PR DESCRIPTION
**Pull request by trixpan**
WFLY-16022

### CODE REVIEW

**Comment by boris-unckel** [comment]
Hello trixpan, welcome to WildFly. Thanks for contributing. Please check the https://docs.wildfly.org/26/Hacking_On_WildFly.html for conventions of PRs.

* title
* link to Jira
* Github jackson release tag
* git diff-link comparing actual and changed version
* Jira of type component upgrade
* Reference to https://github.com/FasterXML/jackson-databind/issues/3328

**Comment by bstansberry** [comment]
@jamezp @ronsigal @fjuma @pferraro @kabir Is this upgrade suitable for your respective components' use of Jackson?

**Comment by kabir** [comment]
@bstansberry  No problems on my side AFAIK

**Comment by pferraro** [comment]
@bstansberry Upgrade is fine for OpenAPI.

**Review by jamezp — APPROVED** [review]
Okay for RESTEasy. Sorry for the delay.

**Pull request merged**
