### PR TITLE
WFLY-18874 Replace service value captor abstractions from wildfly-clustering-common with variants from wildfly-subsystem

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-18874

### CODE REVIEW

**Comment by jamezp** [comment]
@pferraro I just merged the latest core PR.

**Comment by pferraro** [comment]
@jamezp Thanks.

**Comment by bstansberry** [comment]
I'm looking at this and a bunch of changes are straightforward. I'm going to post a couple "Note to self:" comments for a couple other things that I want to understand better when I have a bit more time than I do now. Paul, please ignore them, they are just reminders for myself, a personal todo list, and don't mean I need explanations or anything.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @pferraro

**Pull request merged**
