### PR TITLE
WFLY-19592 [MP Platform 7] MicroProfile Fault Tolerance 4.1 in WildFly Preview

### PR DESCRIPTION
**Pull request by rhusar**
Resolves
https://issues.redhat.com/browse/WFLY-19592

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]

**Comment by rhusar** [comment]
@bstansberry Do you think it's worthwhile having this in main in preview or should we close this and reopen against our MP 7 branch instead (having this in proper)?

**Comment by bstansberry** [comment]
@rhusar If you don't mind and it passes CI (which I requested just as a refresh) then I'd rather merge it and let it bake in main, where it will get a lot more testing.

I think that only because you already did the work. If it's a hassle for you to migrate from this to what you'll do in mp-7-wip instead of starting from current main, that's fine; just close it.

If it passes I'll merge tomorrow unless you say not to.

**Comment by rhusar** [comment]
> @rhusar If you don't mind and it passes CI (which I requested just as a refresh) then I'd rather merge it and let it bake in main, where it will get a lot more testing.
> 
> I think that only because you already did the work. If it's a hassle for you to migrate from this to what you'll do in mp-7-wip instead of starting from current main, that's fine; just close it.
> 
> If it passes I'll merge tomorrow unless you say not to.

No problem here - you are right, the more bake and visibility, the better!

**Comment by bstansberry** [comment]
Thanks @rhusar

**Pull request merged**
