### PR TITLE
[WFLY-3471] JMSContext injection

### PR DESCRIPTION
**Pull request by jmesnil**
- fix JMSContext injection to use the correct CDI scope (request or
  transaction) depending on the presence of a transaction.
- Inject @RequestScoped and @TransactionScoped beans to let CDI handle
  the bean lifecycle.
- move injection code in the
  org.wildfly.extension.messaging.activemq.deployment.injection package
- add test asserting that a @RequestScoped injected JMSContext is
  properly cleaned up at the end of the request

JIRA: https://issues.jboss.org/browse/WFLY-3471

### CODE REVIEW

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by bstansberry** [comment]
@jmesnil Please advise ASAP if this should be for 10.1.

**Comment by jmesnil** [comment]
@bstansberry this is ok for 10.x

**Pull request merged**
