### PR TITLE
[WFLY-19606] Workaround infinispan ISPN-16346 JDK23 issue

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-19606

### CODE REVIEW

**Comment by pferraro** [comment]
@ropalka How urgent is this to fix?  I ask because we are in the process of migrating these tests to use Infinispan server container images which will also resolve WFLY-19606.

**Comment by ropalka** [comment]
It is not urgent @pferraro - JDK23 GA release will be in second half of September.

**Comment by luck3y** [comment]
Will get SE 23 installedater today, thanks for the reminder.

**Comment by ropalka** [comment]
Closing in favour of https://github.com/wildfly/wildfly/pull/18148

**Pull request closed without merging**
