### PR TITLE
WFLY-16451 [primary/secondary] Problematic Language usage deprecation  and replacement of Java docs/variable names

### PR DESCRIPTION
**Pull request by parsharma**
Issue: https://issues.redhat.com/browse/WFLY-16451

### CODE REVIEW

**Comment by parsharma** [comment]
@yersan pr is ready for review.
Thanks

**Review by yersan — APPROVED** [review]
LGTM, it will be superseded by the wildfly-core upgrade

**Comment by yersan** [comment]
Superseded by https://github.com/wildfly/wildfly/pull/16192

**Comment by bstansberry** [comment]
Closing in favor of #16192. Thanks @parsharma!

**Pull request closed without merging**
