### PR TITLE
WFLY-15989 Simplify BatchThreadPoolDescriptionResolver

### PR DESCRIPTION
**Pull request by chengfang**
https://issues.redhat.com/browse/WFLY-15989

### CODE REVIEW

**Comment by chengfang** [comment]
This PR (draft PR) won't build until the next version of WFCORE brings in the necessary changes to `org.jboss.as.controller.descriptions.StandardResourceDescriptionResolver`.

**Comment by chengfang** [comment]
"Dependency Tree Input Builder" job failed around 20 days ago, but there is no way to retest it. A "retest" comment only triggered all other CI jobs but not this one. But since all other jobs passed, this "Dependency" job should have no reason to fail.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks, @chengfang

**Pull request merged**
