### PR TITLE
[WFLY-9868] added Elytron dependency to wsprovide wscomsume module.xml

### PR DESCRIPTION
**Pull request by rsearls**
Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

### CODE REVIEW

**Comment by rsearls** [comment]
https://issues.jboss.org/browse/WFLY-9868

**Comment by rsvoboda** [comment]
@marekkopecky fyi

**Comment by rsearls** [comment]
David Lloyd required this addition.

On Wed, Feb 21, 2018 at 2:29 PM, Rostislav Svoboda <notifications@github.com

**Comment by rsvoboda** [comment]
We are requiring `org.wildfly.security.elytron-private` even if users can be still using just the old picketbox ?

Unnecessary dependencies can be issue for trimming effort represented by provisioning tool.

**Comment by rsearls** [comment]
@dmlloyd  adding David Lloyd to this discussion

**Comment by dmlloyd** [comment]
Yes we will require elytron-private for every module which can be launched from the command line.  Since we plan to deprecate and ultimately remove picketbox, I don't think we need to worry too much about conserving space in a case where a user wants picketbox but not elytron.

**Review by dmlloyd — APPROVED** [review]

**Comment by rsvoboda** [comment]
> Yes we will require elytron-private for every module which can be launched from the command line

Can you please share here what change in jboss-modules requires that ? 
So all modules used by our scripts will need similar update before  we cut .Final ? 

> Since we plan to deprecate and ultimately remove picketbox ...

Deprecation is ok, but not sure if and when we will be able to pull it away due to current backward compatibility requirements

**Comment by dmlloyd** [comment]
> Can you please share here what change in jboss-modules requires that ?

No change in JBoss Modules requires this.  The Elytron security manager is where WildFlySecurityManager lives now, and in addition to its superior diagnostics, much of our security manager-aware code uses WildFlySecurityManager-specific APIs which do not work as well with the default security manager.

> So all modules used by our scripts will need similar update before we cut .Final ?

I would call it a "strong recommendation".  "Requirement" is probably too strong of a word, in retrospect.

**Pull request merged**
