### PR TITLE
WFLY-12581 Optimize expiration scheduler of distributed web session managers, EJB SimpleCache, and clustered EJB DistributableCache

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-12581

WFLY-12321 optimized the SFSB expiration scheduler used for local, passivating EJB caches.
This PR generalizes the scheduler implementation introduced in WFLY-12321, allowing reuse for the following use cases:

* Embedded Infinispan distributed web session manager
* Remote HotRod distributed web session manager
* Local (non-passivating) EJB SimpleCache
* Clustered EJB DistributableCache

See attached jira for preliminary performance results.
Notably, this PR doubles the performance of local, non-passivating @Stateful EJB invocations under load.

Requires https://github.com/wildfly/wildfly/pull/12734

### CODE REVIEW

**Comment by pferraro** [comment]
@fl4via Please have a look.

**Review by fl4via — APPROVED** [review]
From the algorithm point of view (bearing in mind that I'm not 100% familiar with all cluster details) this looks great to me!

**Comment by bstansberry** [comment]
retest this please

**Review by bstansberry — APPROVED** [review]
I did a comparison of provisioning a server using the cloud-server and also the cloud-server + web-clustering layers with and without this PR and the PR didn't result in any additional modules. so that LGTM.

**Pull request merged**
