### PR TITLE
WFLY-11412 Upgrade Infinispan to 9.4.2.Final

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-11412

### CODE REVIEW

**Review by rhusar — APPROVED** [review]

**Review by jamezp — APPROVED** [review]

**Comment by jamezp** [comment]
@pferraro @rhusar Should this be merged or do we want to wait for 9.4.3.Final?

**Comment by rhusar** [comment]
@jamezp The sooner the better!

**Comment by pferraro** [comment]
@jamezp Yes - while we intend to update to 9.4.3.Final as soon as it is released, we should still merge this upgrade.

**Comment by tommaso-borgato** [comment]
@kabir @pferraro I run some performance tests and performance look OK: at present WildFly behaves like 7.2 after fix #JBEAP-15815

**Comment by rhusar** [comment]
@tommaso-borgato 👍

**Comment by tommaso-borgato** [comment]
@kabir @pferraro basic EJB tests are OK too

**Pull request merged**
