### PR TITLE
[WFLY-13844] upgrading jboss-ejb-client from 4.0.33.Final to 4.0.34.Final

### PR DESCRIPTION
**Pull request by chengfang**
JIRA: https://issues.redhat.com/browse/WFLY-13844

Changes in this version of jboss-ejb-client: https://github.com/wildfly/jboss-ejb-client/compare/4.0.33.Final...4.0.34.Final

This PR has passed 4 rounds of CI tests. So I'd like to request to merge it into WildFly while we're working on some integratin issues of jboss-ejb-client 4.0.35.Final (the latest release).

### CODE REVIEW

**Comment by chengfang** [comment]
all jobs passed in the first attempt.

**Comment by chengfang** [comment]
all jobs passed in the 2nd run (a few unrelated tests failed initially and passed in rerun).

**Comment by chengfang** [comment]
all jobs passed in the 3rd run.

**Comment by pferraro** [comment]
This is looking good so far!  Let's try once more.

**Comment by chengfang** [comment]
Windows JDK 11 had 1 failure (unrelated): ManagedExecutorServiceMetricsTestCase.testActiveRequests

```
java.lang.AssertionError: expected:<0> but was:<1>
  at deployment.arquillian-service//org.junit.Assert.fail(Assert.java:88)
  at deployment.arquillian-service//org.junit.Assert.failNotEquals(Assert.java:834)
  at deployment.arquillian-service//org.junit.Assert.assertEquals(Assert.java:645)
  at deployment.arquillian-service//org.junit.Assert.assertEquals(Assert.java:631)
  at deployment.ManagedExecutorServiceMetricsTestCase.jar//org.jboss.as.test.integration.ee.concurrent.ManagedExecutorServiceMetricsTestCase.testActiveRequestStats(ManagedExecutorServiceMetricsTestCase.java:278)
  at deployment.ManagedExecutorServiceMetricsTestCase.jar//org.jboss.as.test.integration.ee.concurrent.ManagedExecutorServiceMetricsTestCase.testActiveRequests(ManagedExecutorServiceMetricsTestCase.java:174)
```
I've created the issue [WFLY-13957](https://issues.redhat.com/browse/WFLY-13957) to track it.
ManagedExecutorServiceMetricsTestCase.testActiveRequests fails intermittently

**Comment by kabir** [comment]
@chengfang @pferraro I see some discussion between you two. Is this ready?

**Comment by chengfang** [comment]
@kabir I think it's ready. Note that this is not the latest jboss-ejb-client release.

The latest ejb-client release, 4.0.35.Final, has caused some clustering test failures, which we are working on. It will be good to have 4.0.34.Final in WildFly for now.

**Pull request merged**
