### PR TITLE
[WFLY-5949] Use servlet protocol in xts arquillian tests

### PR DESCRIPTION
**Pull request by gytis**
https://issues.jboss.org/browse/WFLY-5949

### CODE REVIEW

**Comment by ctomc** [comment]
looks like arquillian protocol doesn't help, failures are continuing.

**Comment by gytis** [comment]
It's the different failure. It used to be "java.lang.reflect.UndeclaredThrowableException: null". And it used to be intermittent.
I don't recall seeing this one before.

**Comment by gytis** [comment]
I've checked with Alessio about the issue which failed the pull request. He said that it's a known issue in web services and Jim Ma is currently looking into it.
I've moved JBTM-2586 to WFLY-5954, so that we could track the progress.

**Comment by gytis** [comment]
retest this please

**Comment by gytis** [comment]
Could somebody take a look at this, please?

**Comment by ctomc** [comment]
I don't really see any reason for this, as we didn't see any real improvement / degradation with moving to servlet protocol.
Pretty much everything is as without this change

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
meh, CI won't pick it up but I'll just mark it ready for merge and test it on master-ignore as part of merging.

**Comment by gytis** [comment]
Thanks, @bstansberry

**Pull request merged**
