### PR TITLE
WFLY-6642 Automatic IOR transport settings creation

### PR DESCRIPTION
**Pull request by tadamski**
Description in JIRA: https://issues.jboss.org/browse/WFLY-6642

### CODE REVIEW

**Comment by bstansberry** [comment]
This will need a transformer for the new attributes.

Beyond that though it seems like an incompatible change. At a glance it seems good, just a couple settings that drive a lot, rather than a bunch. But if people are not using these new settings they need to get the behavior they got before.

If they are using the new attributes but also set old ones in an inconsistent manner they should get a failure.

How does this affect the jacorb integration?

**Comment by tadamski** [comment]
Yes, the change is incompatible, I was thinking about the possibility of having both server_requires_ssl and transport config tags but I resigned from it, cause it will mean that the problem (incorrect description) will stay.

Currently the main use case of transport config tag is ssl configuration - that is user sets at least one tag eq. confidentiality as required and client knows that the server needs ssl. The problem is that even if this scenario we would often  get incorrect description if user is not diligent enough. 

The only use case when user would need precise transport config descrption would be the case when he needs some ssl features, and he doesn't need the other ones. This seemed rather implausible scenario for me, and what is more the effect will still be the same - if at least one feature is needed ssl would be required. Because of that I decided to remove transport configuration from the new version.

Regarding the transformation: I can check whether declared transport config enforces ssl usage, and if it does set the server-requires-ssl tag accordingly. I can do it in both iiop-openjdk 1.0 -> 1.1 and jacorb -> openjdk 1.1 scenario.

On the other hand if we need to keep the attributes I may add verification which will check wheter the configuration is valid and refuse to start subsystem till user fixes it or decides to use server-require-ssl tags, I can also use the same functionality to decline transforming jacorb->iiop-openjdk if the description is invalid. Maybe this would be the best solution.

**Comment by bstansberry** [comment]
+1 to keeping the old attributes and verifying. We can't break compatibility, at least not until we are talking about code for EAP 8.

**Comment by tadamski** [comment]
retest this please

**Comment by tadamski** [comment]
retest this please

**Comment by tadamski** [comment]
rebased

**Comment by sguilhen** [comment]
I like the changes being made here to simplify the SSL configuration. There is one aspect that we need to consider though: the ior-settings config was originally introduced in jboss-ejb(3).xml to allow each bean to specify the settings for its own IOR. After a while, people started asking for a centralized config that would be applied to all beans and it was then added at the subsystem level - to be more precise, this was originally done for AS5 in one of those *jboss-beans.xml config files.

What this means is that even though the subsystem is now able to validate its own config, there might still be issues when deployments contain ior-settings that are incompatible with the IIOP subsystem settings. So I'm thinking that we should probably consider simplifying the descriptor as well by deprecating the transport config section according to what is being done at the subsystem. And we should also expose this validator somehow to the EJB3 subsystem so it can validate the deployment config and fail the deployment if needed.

**Comment by tadamski** [comment]
Those changes were merged as part of Elytron integration.

**Pull request closed without merging**
