### PR TITLE
[WFLY-9989] Bump messaging-activemq model version to 3.1.0

### PR DESCRIPTION
**Pull request by jmesnil**
Bump its XSD schema to 3.1

There are no changes compared to the previous version but doing the bump
in a separate step will make it simpler for upcoming changes to be
picked up.

JIRA: https://issues.jboss.org/browse/WFLY-9989

### CODE REVIEW

**Comment by rhusar** [comment]
We were always doing major versions for WF releases, is this not the case any more?

**Comment by jmesnil** [comment]
@rhusar that's a good question. I'm not sure if that still applies with our new time-boxed release process (the speed of major releases having increased).

@n1hility Should we continue to bump major version for subsystem between major wildfly release?

**Comment by rhusar** [comment]
Or maybe @bstansberry is interested to comment?

**Comment by bstansberry** [comment]
This is ok. We should do a major bump if we need to leave room for some branch from the previous version to have its own minor stream. But there will be no such branch from the messaging api version in WF 12.

The quarterly release pattern nearly eliminates the possibility of API branches.

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
