### PR TITLE
[WFLY-17177] Configure surefire plugin's 'reportNameSuffix' when test will be executed multiple times

### PR DESCRIPTION
**Pull request by gaol**
Issue: https://issues.redhat.com/browse/WFLY-17177

Thanks for submitting your Pull Request!

Please delete this text, and add a link to the Jira issue solved by this PR.

If this PR is not for the 'main' branch you must add a link to the equivalent change in 'main'.

Remember to use the Jira issue ID in the PR title and any commits.

This PR tries to add `reportNameSuffix>EXECUTION-ID</reportNameSuffix>` to some execution configuration of `maven-surefire-plugin` to avoid the test report being overridden if the test gets executed multiple times.

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]

**Comment by gaol** [comment]
It looks like the `Windows - JDK 11` always fails, not sure if it relates, I will try to check it in a Windows machine this week or next week.

**Comment by gaol** [comment]
I tried to run the tests from a vanilla WildFly main branch, and I got the same errors, so the failure does not relate to this change. 

I checked the build log of  `Windows - JDK 11` for other PRs, which is marked as success, but actually it failed, I think the reason the were marked as success is because the same maven surefire report file was used. This PR actually reveals the problem.

I created https://issues.redhat.com/browse/WFLY-17698 for the test failure, and I plan to add extra commit to this PR to fix it as well, please let me know if it needs a separate PR for it.

**Comment by gaol** [comment]
Added the commit to this PR for https://issues.redhat.com/browse/WFLY-17698

**Comment by bstansberry** [comment]
Thanks @gaol!!!

**Pull request merged**
