### PR TITLE
[WFLY-16854] [WFLY-17023] [WFLY-17024] Update dependencies for Opentelemetry and MicroProfile OpenTracing

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFLY-16854
https://issues.redhat.com/browse/WFLY-17023
https://issues.redhat.com/browse/WFLY-17024

This combines these 3 PRs:

#15961
#16089
#16090

It uses the separate module kotlin artifact packaging approach from #16089 instead of the approach in #15961. I did that because it was easiest to pull things together that way. @jasondlee in the discussion at https://github.com/wildfly/wildfly/pull/15961#discussion_r950076537 it sounded like the #15961 approach was preferable. If so, please follow up with a PR moving to that.

### CODE REVIEW

**Comment by bstansberry** [comment]
Note that these updates break the Cloud Tests. @kabir FYI.

I suspect that has nothing to do with OTel/OT etc, and may be more about dependency management in the Cloud Tests.

**Review by jasondlee — APPROVED** [review]
I think this approach is fine, Brian. My comment about the new module was, iirc, mainly about a new module for jackson-jr-objects, which is unlikely to be needed somewhere else. The Kotlin libs will most likely need to be reused elsewhere as time rolls on.

**Comment by bstansberry** [comment]
@jasondlee @boris-unckel I added a commit that I hope will address the Cloud Tests failure. kotlin-stdlib-jdk8 depends on kotlin-stdlib-jdk7, and the Cloud Tests failure is due to a CNFE for a class in that jar.

**Comment by kabir** [comment]
@bstansberry it looks like you got it passing

**Comment by bstansberry** [comment]
@kabir Yes, I fixed it by taking the liberty of filing and merging https://github.com/wildfly-extras/wildfly-cloud-tests/pull/31.

/me requests forgiveness; asking permission is too much hassle ;)

**Comment by bstansberry** [comment]
Thanks @boris-unckel and @jasondlee

**Pull request merged**
