### PR TITLE
WFLY-19040 Configure SNI hostnames per cluster if possible

### PR DESCRIPTION
**Pull request by pferraro**
As of Infinispan 14.0.18, HotRod client enables hostname validation by default - so we need to configure SNI hostnames per cluster if possible.
Auto-disable hostname validation if unsupported by server configuration.

https://issues.redhat.com/browse/WFLY-19040

### CODE REVIEW

**Comment by pferraro** [comment]
@jmesnil FYI.

**Comment by jmesnil** [comment]
upstream PR: https://github.com/wildfly/wildfly/pull/17643

**Review by rhusar — APPROVED** [review]
LGTM, the fix was also verified by QE.

**Comment by jmesnil** [comment]
@pferraro thanks!

**Pull request merged**
