### PR TITLE
Remove Xalan / Use JAXP for xml processing

### PR DESCRIPTION
**Pull request by ctomc**
Removes xalan as dependency in app server.
other minor changes to improve xml parsing

### CODE REVIEW

**Comment by ctomc** [comment]
retest this please

**Comment by ctomc** [comment]
retest this please

**Comment by ctomc** [comment]
As discussed this would be too big of change for WF 10 to be sufficiently tested.
It should be revisited once JDK9 is out.

**Comment by sake** [comment]
Is the removal of Xalan still a goal, now that JDK 9 has been released? 

I'm asking as I can't find a good way to use the JDK's JAXP implementation without referencing JDK internal classes. The newer JAXP is needed because some software (in our case https://github.com/esig/dss) is using JAXP 1.5+ properties (access_external_dtd) to disable external DTDs in order to mitigate XEE attacks.

**Comment by ctomc** [comment]
@sake this would better be discussed on wildfly-dev mailing list

**Pull request closed without merging**
