### PR TITLE
WFLY-10961 Unify jaeger-thrift and jaeger-core modules

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

JIRA: https://issues.jboss.org/browse/WFLY-10961
From JIRA: 

> One of the last changes made to WF 14 was to split the MP-OpenTracing dependencies into smaller modules. This introduced a bug where the Jaeger Core module can't see a Sender from Jaeger Thrift. This is loaded via the Service Loader, so, Jaeger Core has to be shipped with Jaeger Thrift on the same module, to avoid a circular dependency (as Jaeger Thrift depends on classes defined on Jaeger Core).

- [x] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue(s)
- [x] Pull Request contains description of the issue(s)
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted

### CODE REVIEW

**Comment by jpkrohling** [comment]
cc @jamezp , @jstourac , @objectiser

**Review by objectiser — COMMENTED** [review]
LGTM

**Comment by jamezp** [comment]
The failures were related to the fix in #11627 not this PR.

**Review by jamezp — APPROVED** [review]

**Comment by kabir** [comment]
@jpkrohling This also needs a downsteam PR - I will comment on the JBEAP issue

**Pull request merged**
