### PR TITLE
[WFLY-12070]Upgrade to Apache CXF 3.3.2 and JBossWS 5.3.0.Final

### PR DESCRIPTION
**Pull request by jimma**
- https://issues.jboss.org/browse/WFLY-12070

- This change upgrades CXF 3.3.2, JBossWS 5.3.0 and other relevant dependencies.

### CODE REVIEW

**Comment by jimma** [comment]
retest this please

**Comment by bstansberry** [comment]
@jimma This definitely has problems. The Linux SM job looks like it's found a new permission a deployment would have to have (not good) and the IIOPNamingTestCase failures are consistent but don't happen elsewhere.

**Comment by jimma** [comment]
@bstansberry  Looking at these failures now.

**Comment by asoldano** [comment]
Retest this please

**Comment by asoldano** [comment]
@bstansberry @jimma  If the failures here are consistent, I propose to merge (squash it please) #12297 instead of this. That is the same as this, except it upgrades to Apache CXF 3.3.1 instead of 3.3.2, and it's passing CI. What we really care now is moving to 3.x, we can look at the specific problem with 3.3.2 and security manager, if any, later.

**Comment by asoldano** [comment]
Actually, looking at the "Linux with security manager - JDK8" job, I think all tests passed (thanks to Jim's https://github.com/wildfly/wildfly/pull/12282/commits/9d92dc36335fe19313a59f79d5a9f6ef9c104362 ), even if the build eventually timed out.

**Review by asoldano — APPROVED** [review]

**Comment by asoldano** [comment]
All green :-)

**Comment by jimma** [comment]
@bstansberry  All tests passed and it can be merged. @asoldano  Thanks for looking at this .

**Comment by bstansberry** [comment]
@jimma @asoldano Is adding a permission to the deployment a good solution? That means our users would have to do this even though their deployment has not changed at all.

**Comment by jimma** [comment]
@bstansberry  This is a known issue in CXF : https://issues.apache.org/jira/browse/CXF-8042
I already fixed in CXF upstream. 
Adding this permission is a minor issue given there are couple of permission required to run these XTS tests:


    protected static WebArchive getExecutorServiceArchiveBase() {
        return ShrinkWrap.create(WebArchive.class, EXECUTOR_SERVICE_ARCHIVE_NAME + ".war")
                .addClasses(ExecutorService.class, RemoteService.class, Helpers.class)
                .addAsResource("context-handlers.xml", "context-handlers.xml")
                .addAsManifestResource(new StringAsset("Dependencies: org.jboss.xts, org.jboss.jts"), "MANIFEST.MF")
                .addAsManifestResource(createPermissionsXmlAsset(
                        new SocketPermission("127.0.0.1:8180", "connect,resolve"),
                        new RuntimePermission("org.apache.cxf.permission", "resolveUri"),
                        //TODO:remove this permission when upgrade CXF to 3.3.3 or higher version: WFLY-12087 
                        new RuntimePermission("getClassLoader"),
                        // WSDLFactory#L243 from wsdl4j library needs the following
                        new FilePermission(System.getProperty("java.home") + File.separator + "lib" + File.separator + "wsdl.properties", "read")
                        ), "permissions.xml");
    }
`

After we upgrade CXF to 3.3.3 or higher version , we can remove this permission.  WFLY issue is created to track: this:https://issues.jboss.org/browse/WFLY-12087

**Comment by bstansberry** [comment]
@jimma This has a checkstyle problem in the xts testsuite; that's why CI fails.

+1 to your approach re the permission issue.

**Comment by jimma** [comment]
@bstansberry  thanks. Checkstyle error is fixed.

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
