### PR TITLE
[WFLY-18985] Update WildFly docs to include reload operation required to valid key-store attributes update on Filesystem Security Realm

### PR DESCRIPTION
**Pull request by lvydra**
https://issues.redhat.com/browse/WFLY-18985
https://issues.redhat.com/browse/ELY-2702

### CODE REVIEW

**Comment by lvydra** [comment]
We have tried to run `write-attribute` commands with `reload` operation in batch:
```
batch
/subsystem=elytron/filesystem-realm=integrityfsRealm:write-attribute(name=key-store, value=keystore2)
/subsystem=elytron/filesystem-realm=integrityfsRealm:write-attribute(name=key-store-alias, value=user2)
:reload
run-batch
```
but it seems to not work either. 
So probably the only working solution is the one described in the documentation
```
/subsystem=elytron/filesystem-realm=fsRealm:write-attribute(name=key-store, value=newKeystore)
/subsystem=elytron/filesystem-realm=fsRealm:write-attribute(name=key-store-alias, value=newKeystoreAlias)
reload
/subsystem=elytron/filesystem-realm=fsRealm:update-key-pair()
```
or to run only commands in batch and run reload outside of it
```
batch
/subsystem=elytron/filesystem-realm=integrityfsRealm:write-attribute(name=key-store, value=keystore2)
/subsystem=elytron/filesystem-realm=integrityfsRealm:write-attribute(name=key-store-alias, value=user2)
run-batch
reload
/subsystem=elytron/filesystem-realm=fsRealm:update-key-pair()
```

**Comment by bstansberry** [comment]
@lvydra @Skyllarr if the first two operations should be done atomically, the docs should have them in a batch, i.e. as shown in the last part of Lukas' last comment. They definitely look like something that should be done atomically.

**Comment by lvydra** [comment]
@Skyllarr @bstansberry updated

**Comment by bstansberry** [comment]
@Skyllarr or @fjuma Is this ok?

**Review by fjuma — APPROVED** [review]
Thanks @lvydra!

**Comment by bstansberry** [comment]
Thanks @lvydra, @Skyllarr and @fjuma

**Pull request merged**
