### PR TITLE
[WFLY-11125] Convert weld subsystem module dependencies on security modules to optional

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.jboss.org/browse/WFLY-11125

### CODE REVIEW

**Comment by bstansberry** [comment]
@manovotn @darranl Please review if you get a chance. In particular the 2nd commit. The first is kind of a no-brainer. The 2nd affects code that AFAICT is never used, and even if it was used I think it might be ok as it seems like any picketbox stuff wouldn't work if the legacy security subsystem isn't present. But I'm not an expert.

**Comment by manovotn** [comment]
Yea there were some changes around this, we are now using slightly different approach.
See this [commit](https://github.com/weld/core/commit/d441845e889dbae4c84f083cb94178266706f83e)
or [WELD-2380](https://issues.jboss.org/browse/WELD-2380)

I am currently on PTO, @mkouba could you please give this a look?

**Comment by bstansberry** [comment]
I added a third commit, as we saw that weld-common also has a non-optional dep on org.jboss.as.security.  The commit makes it optional, but there may be a good chance it's not needed at all.

**Comment by mkouba** [comment]
`org.jboss.as.weld.services.bootstrap.WeldSecurityServices.getSecurityContext()` is only used if elytron is not available. It is called by the default `org.jboss.weld.security.spi.SecurityServices.getSecurityContextAssociator()` implementation. See also https://github.com/wildfly/wildfly/blob/master/weld/subsystem/src/main/java/org/jboss/as/weld/services/bootstrap/WeldSecurityServices.java#L106 and https://github.com/weld/api/blob/master/weld-spi/src/main/java/org/jboss/weld/security/spi/SecurityServices.java#L75-L86.

The PR looks good. Unfortunately, I don't have time to test it properly.

**Comment by bstansberry** [comment]
Thanks @mkouba . I (well, IDEA) also was unable to find any uses of SecurityServices.getSecurityContextAssociator(), other than WeldSecurityService's own impl delegating to the default impl.

**Comment by mkouba** [comment]
`SecurityServices.getSecurityContextAssociator()` is used in Weld when notifying async observers; see also https://github.com/weld/core/blob/master/impl/src/main/java/org/jboss/weld/event/ObserverNotifier.java#L334.

**Comment by bstansberry** [comment]
Thanks. It seems I need to be more careful about refreshing IDEA before searching, as that hadn't shown up before.

**Review by jamezp — APPROVED** [review]

**Review by jamezp — APPROVED** [review]

**Comment by bstansberry** [comment]
@jamezp @mareknovotny @mkouba @darranl I removed the commit from this that tried to make the picketbox dependency optional.  Once Martin pointed out the code use I'd missed it didn't seem safe to try and not use SecurityContextAssociation just because the security subsystem is not installed. I see too much other code that is using it without consideration of whether the subsystem is installed. So cleaning that up seems like it should be part of a bigger effort of removing the requirement for picketbox.

**Pull request merged**
