### PR TITLE
WFLY-8473 Fix mod_cluster service name when used with capability

### PR DESCRIPTION
**Pull request by ctomc**
this is follow up on #9858 where mod cluster service name vs capability service name was different and could cause issues

### CODE REVIEW

**Comment by rhusar** [comment]
I don't think this is right.  The right Jira that should be linked here is https://issues.jboss.org/browse/WFLY-8439. In the original Stuart's PR, the dependency is established from the http-invoker to jboss.modcluster.undertow however this is establishing a dependency on jboss.modcluster which is most likely another regression for WFLY-8439 since the invoker and the container integration can shutdown concurrently. I have outlined the proper fix in here https://github.com/wildfly/wildfly/pull/9858#issuecomment-290921270.

**Comment by ctomc** [comment]
@rhusar forget all that, main problem is that mod cluster capability doesn't register its service under the service name of capability. This way no consumer can depend on it.

As for service dependency on adapter goes when capability is present, that is wrong assumption. 
if you are checking of existence of capability (context#hasOptionalCapability) you already tell system you will be needed this capability, and than depending on different service (or even capability) is simply wrong.

**Review by bstansberry — APPROVED** [review]

**Comment by rhusar** [comment]
@ctomc Could you please re-read my comment?

> @rhusar forget all that, main problem is that mod cluster capability doesn't register its service under the service name of capability. This way no consumer can depend on it.
> As for service dependency on adapter goes when capability is present, that is wrong assumption.
> if you are checking of existence of capability (context#hasOptionalCapability) you already tell system you will be needed this capability, and than depending on different service (or even capability) is simply wrong.

Nobody is arguing otherwise, this was my primary concern with the original PR which was reverted.

What I am talking about is that Stuart's fix was adding dependency on the container integration service (see https://github.com/wildfly/wildfly/commit/ca46ebe7820c34818d175079385a83d218b2ad47#diff-3817568e31cc2ff0d8b5f3a5b0416233R56 ) while the changes here are creating dependency on the modcluster service itself. @stuartwdouglas could you please confirm that the dependency needed for the fix is jboss.modcluster.undertow?

**Comment by kabir** [comment]
After speaking a bit more with Rado it seems there is still a problem when running with standalone-ha.xml.

I get 
```
21:14:14,048 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "undertow"),
    ("server" => "default-server"),
    ("host" => "default-host"),
    ("setting" => "http-invoker")
]) - failure description: {
    "WFLYCTL0412: Required services that are not installed:" => ["org.wildfly.mod_cluster"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => ["org.wildfly.undertow.http-invoker.host.default-host.http-invoker is missing [org.wildfly.mod_cluster]"]
}
```
if I try to add it, and if I try to start the server with the modified xml

**Comment by stuartwdouglas** [comment]
Yes, I need a dependency on the Undertow adapter ('jboss.modcluster.undertow'), a dependency on 'jboss.modcluster' is not sufficient.

**Comment by rhusar** [comment]
Thanks for the confirmation Stuart.

**Review by rhusar — CHANGES_REQUESTED** [review]
Does not fix the dependencies needed for WFLY-8439.

**Comment by bstansberry** [comment]
Superceded by #9897

**Pull request closed without merging**
