### PR TITLE
[WFLY-17228] Upgrade ASM to 9.4

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-17228

### CODE REVIEW

**Comment by ropalka** [comment]
@jimma is the ASM upgrade to 9.4 compatible with webservice modules?
@scottmarlow is the ASM upgrade to 9.4 compatible with hibernate modules?
@kabir is the ASM upgrade to 9.4 compatible with smallrye modules?

**Comment by scottmarlow** [comment]
Good question about Hibernate ORM, I think that our ByteBuddy jar has its own copy of ASM, will verify.

**Comment by scottmarlow** [comment]
Yea, looks like only remaining references to ASM project are:
```
grep -rli asm.asm --include=module.xml
system/layers/base/io/smallrye/config/main/module.xml
system/layers/base/org/jboss/as/webservices/server/integration/main/module.xml
system/layers/base/org/apache/cxf/ws-security/main/module.xml
system/layers/base/org/apache/cxf/main/module.xml
system/layers/base/org/apache/cxf/services-sts/main/module.xml
system/layers/base/org/apache/cxf/impl/main/module.xml
```

**Comment by kabir** [comment]
Looks like SmallRye Config upstream is already on 9.4 so it should be good https://github.com/smallrye/smallrye-config/blob/main/pom.xml#L39

**Review by jimma — APPROVED** [review]

**Review by kabir — APPROVED** [review]

**Review by scottmarlow — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @ropalka

**Pull request merged**
