### PR TITLE
[WFLY-17046] Deprecate and reject remaining security-realm references in the Undertow subsystem.

### PR DESCRIPTION
**Pull request by darranl**
https://issues.redhat.com/browse/WFLY-17046

### CODE REVIEW

**Comment by darranl** [comment]
@bstansberry FYI this is not really a blocker until WildFly 28 but the Undertow subsystem appears to contain an unused model bump so may as well use it so we don't need to revert or waste it.

**Review by bstansberry — CHANGES_REQUESTED** [review]
Needs a minor cleanup in LocalDescriptions.properties; otherwise looks good

**Comment by darranl** [comment]
Thanks @bstansberry should be fixed now

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @darranl

**Pull request merged**
