### PR TITLE
WFLY-4792 Add support for session manager statistics for distributable web applications

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-4792

### CODE REVIEW

**Comment by bstansberry** [comment]
Is there any kind of statistics-enabled setting for web statistics?

**Comment by pferraro** [comment]
@bstansberry https://github.com/wildfly/wildfly/blob/master/undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentInfoService.java#L388

**Comment by bstansberry** [comment]
@pferraro I asked because I wasn't clear on how that setting was controlling the behavior of the stats gathering here. For example, this collection happens always:

https://github.com/wildfly/wildfly/pull/7744/files#diff-a7519dd56759f6084e7c0c0bb006353fR106

The other collection stuff looks to be in SimpleStatistics. But I don't see its "record" method being called anywhere, other than in the unit test.

**Comment by pferraro** [comment]
Good point.  Stats are gathered regardless of the statistics-enabled setting in the in-memory session manager as well:
https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/server/session/InMemorySessionManager.java

I'll make sure this stuff is conditional.  Closing for now - until ready.

**Pull request closed without merging**
