### PR TITLE
[WFLY-16591] Remove the org.jboss.resteasy.jose-jwt module

### PR DESCRIPTION
**Pull request by jamezp**
https://issues.redhat.com/browse/WFLY-16591
Signed-off-by: James R. Perkins <jperkins@redhat.com>

### CODE REVIEW

**Comment by darranl** [comment]
@ronsigal can you please give this a quick review so we can get it in for James?

**Comment by jamezp** [comment]
I converted this to a draft for now until we have a decision. It is being discussed and the current idea is we might remove `org.jboss.resteasy.jose-jwt`, but keep `org.jboss.resteasy.resteasty-rxjava2`.

**Comment by ronsigal** [comment]
Hey Darren,

Sorry for the late reply - I was on PTO on Friday. Yes, I'll take a look.

-Ron

**Comment by ronsigal** [comment]
Well, I don't know much about RESTEasy's jose-jwt, but I was involved in the creation of resteasy-rxjava2, and I would be surprised if it were used somewhere in WildFly. It looks like those two got into common-microprofile/pom.xml in https://github.com/wildfly/wildfly/commit/c4d4f89661f95d1506c86faa0ad66ca7b0c22258. James, do you remember where the dependencies there came from?

**Comment by jamezp** [comment]
> Well, I don't know much about RESTEasy's jose-jwt, but I was involved in the creation of resteasy-rxjava2, and I would be surprised if it were used somewhere in WildFly. It looks like those two got into common-microprofile/pom.xml in [c4d4f89](https://github.com/wildfly/wildfly/commit/c4d4f89661f95d1506c86faa0ad66ca7b0c22258). James, do you remember where the dependencies there came from?

@ronsigal It looks like `resteasy-rxjava2` came in via https://github.com/wildfly/wildfly/pull/11378. The referenced commit is just where we upgraded WildFly Preview to RESTEasy 6.0.

Talking in [chat](https://wildfly.zulipchat.com/#narrow/stream/174184-wildfly-developers/topic/Unreferenced.20modules) with @asoldano, it sounds like we should likely keep `org.jboss.resteasy.resteasy-rxjava2` as is for now, but `org.jboss.resteasy.jose-jwt` is likely okay to be removed.

**Comment by ronsigal** [comment]
Thanks, @jamezp. I have no objections.

**Comment by ronsigal** [comment]
Hey @darranl, +1 for this. If you need an official review, just add me as a reviewer and I'll push the button.

**Comment by bstansberry** [comment]
@ronsigal FYI, you don't need to be added as a reviewer to use the github UI to approve a PR.

**Comment by bstansberry** [comment]
@jamezp Needs a rebase

**Comment by bstansberry** [comment]
Thanks @jamezp

**Pull request merged**
