### PR TITLE
[WFLY-6117] Exclude the .xa subpackage from the transaction API

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
```Caused by: java.lang.IllegalArgumentException: ${org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec}```

Isn't the build supposed to be replacing these?  Maybe because the XML namespace is 1.5 in this one?

**Comment by dmlloyd** [comment]
It looks like ```org.wildfly.build.util.ModuleParser#parseResources()``` isn't consuming the content of the ```<artifact>``` element, which probably causes all the deps to get messed up.

**Comment by dmlloyd** [comment]
OK so ServerProvisioner contains this gem:

```                            moduleXmlContents = moduleXmlContents.replaceAll("(\\s*)<artifact\\s+name=\"\\$\\{" + artifactCoords + "\\}\"\\s*/>", "$1<artifact name=\"\\${" + artifactCoords + "}\" />$1<resource-root path=\"" + target.getName() + "\"/>");```

I'll have to finagle this a bit in order to make this work with nested content.  Regex for XML, swell

**Comment by dmlloyd** [comment]
Depends on https://github.com/wildfly/wildfly-build-tools/pull/28 and subsequent release & integration.

**Comment by dmlloyd** [comment]
Depends on:

https://github.com/wildfly/wildfly-core/pull/1414
https://github.com/wildfly/wildfly-core/pull/1403

**Comment by dmlloyd** [comment]
Failures seem unrelated.

**Comment by n1hility** [comment]
retest this please

**Comment by dmlloyd** [comment]
All tests passed; there was a network error which apparently prevented the first test from reporting in but checking Brontes looks like the build is OK.

**Pull request merged**
