### PR TITLE
[WFLY-17095] Drop source transformation for messaging-activemq subsystem

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFLY-17095

This is a cherry-pick of a commit from #16275. That PR is blocked by WFLY-17264, which in turn is blocked by this one.

@jmfinelli FYI

### CODE REVIEW

**Review by ehsavoie — CHANGES_REQUESTED** [review]
A lot of the changes are not related to the transformation but are formatting. Could this be moved to another commit (on the same PR) so we can see the real impact changes as opposed to just formatting ones.

**Comment by bstansberry** [comment]
@ehsavoie Thanks. The formatting changes I believe come from two things:

1) Copying the generated (transformed) source to the primary source tree. It seems the source generation resulted in formatting changes, e.g. replacement of FQCNs with simple class names. This is not something done by Manuel.

2) Copy the pom dependency entries from the source-transform pom to replace the ones in old pom.

Both of these are the most accurate way of doing this as they are a simple move of known-good source to a different location. Trying to do some more complicated port for easier review would be more likely to introduce bugs.

**Review by ehsavoie — APPROVED** [review]
I'll fix my remarks in a following PR

**Comment by bstansberry** [comment]
Thanks @jmfinelli

**Pull request merged**
