### PR TITLE
WFLY-9529: setup ee naming context and platform bindings for ear modu…

### PR DESCRIPTION
**Pull request by emmartins**
…les + add ee concurrency context setup action to weld setup actions

Issue: https://issues.jboss.org/browse/WFLY-9529

### CODE REVIEW

**Comment by emmartins** [comment]
please don't merge, WiP

**Comment by jamezp** [comment]
It's better to kick off custom CI jobs than use the pull queue to run CI jobs. One of the reasons is you can run it as a personal build so it won't mess with the stats of tests.

**Comment by emmartins** [comment]
retest this please

**Comment by emmartins** [comment]
Please unhold this so it may be tested

**Comment by jamezp** [comment]
A hold does not prevent testing. Again though it's better to kick of custom CI jobs rather than using the pull queue for this :)

**Comment by jamezp** [comment]
@emmartins What is the status of this PR? What I mean is do you consider this PR complete and ready for review?

**Comment by emmartins** [comment]
superseeded by #12173

**Pull request closed without merging**
