### PR TITLE
[WFLY-19343][WFLY-19344]  Jakarta API upgrades

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFLY-19343 (Jakarta Authorization)
https://issues.redhat.com/browse/WFLY-19344 (Jakarta Concurrency)

These were tested using the EE11 branch, which focuses on WildFly Preview, using #17890 and #17891.

____

More information about the [wildfly-bot[bot]](https://github.com/wildfly/wildfly-github-bot)

### CODE REVIEW

**Review by fjuma — APPROVED** [review]
Thanks @bstansberry!

**Review by emmartins — APPROVED** [review]
ty

**Comment by bstansberry** [comment]
Thanks @emmartins and @fjuma

**Pull request merged**
