### PR TITLE
WFLY-4255 Allow Arquillian to specify a timeout value for the WildFly clean shutdown mechanism when shutting down a server

### PR DESCRIPTION
**Pull request by rhusar**
Jiras
https://issues.jboss.org/browse/WFLY-4255
https://issues.jboss.org/browse/WFLY-3532

https://issues.jboss.org/browse/ARQ-1976

This requires snapshot of wildfly-arquillian with https://github.com/wildfly/wildfly-arquillian/pull/37 for 1.0.x (master is https://github.com/wildfly/wildfly-arquillian/pull/13)

### CODE REVIEW

**Comment by rhusar** [comment]
Retest this please.

**Comment by rhusar** [comment]
Retest this please. The last runs did not pick up the snapshot versions.

**Comment by rhusar** [comment]
Retest this please.

**Comment by rhusar** [comment]
Retest this please.

**Comment by rhusar** [comment]
This is very odd, the CI did not pick up the changes from the last commit.

**Comment by rhusar** [comment]
Retest this please.

**Comment by rhusar** [comment]
Retest this please.

**Comment by rhusar** [comment]
Retest this please.

**Comment by rhusar** [comment]
Retest this please.

**Comment by stuartwdouglas** [comment]
This should not be merged until it has been updated to use a released version of arquillin

**Comment by rachmatowicz** [comment]
@rhusar Aslak has tagged 1.1.9.Final of Arquillian core which contains https://issues.jboss.org/browse/ARQ-1976

**Comment by rhusar** [comment]
Retest this please. Linux did not pick up the snapshot version...

**Comment by rachmatowicz** [comment]
retest this please

**Comment by stuartwdouglas** [comment]
Please don't open PR's like this that are not ready to be merged (due to snapshot dependencies):
- we might miss the fact that it is broken and break the build for everyone
- we have to keep checking it to see if it is actually ready yet
- even if it is ready there is a good chance we will just ignore it because we assume it is still broken

**Comment by rhusar** [comment]
@stuartwdouglas Apologies. I will run private builds instead. I didn't realize this couldn't be handled by a label.

**Pull request closed without merging**
