### PR TITLE
Update Hibernate ORM from 5.0.1 to 5.0.2.

### PR DESCRIPTION
**Pull request by langfr**

### CODE REVIEW

**Comment by jamezp** [comment]
This error looks related to the upgrade. @scottmarlow any ideas on this?

**Comment by scottmarlow** [comment]
Not sure at this point if this is a regression in Hibernate ORM 5.0.2 or a problem with the failing test.

**Comment by scottmarlow** [comment]
This seems likely to be a Hibernate regression but will see.

**Comment by langfr** [comment]
Just found http://planet.jboss.org/post/hibernate_second_level_cache_improvements where the author says "you should not use eviction, ...".
Perhaps this test should be disabled then?

**Comment by scottmarlow** [comment]
I sent a private email to the author (Radim Vansa), asking for his help with understanding what has changed that leads to the test failure.

**Comment by rvansa** [comment]
@langfr Eviction should not be used if you're using replicated/distributed cache for entities/collections. If you haven't changed your configuration (local or invalidation most likely) you're safe to use it.

**Comment by rvansa** [comment]
@scottmarlow It seems I have to ask you for trace logs, again. Btw., any chance you could port these tests to ORM so that I can see them failing before you try to do the upgrade? I thought it would be great if there was some 2LC TCK that could be easily used from all 2LC impls, so that nobody boasts implementing 2LC when the impl is not working properly.

**Comment by scottmarlow** [comment]
@rvansa wouldn't it be easier to run the WildFly test suite once before a Hibernate release (if there are changes to the hibernate-infinispan module)?  I enable TRACE logging for Infinispan and then Hibernate + Infinispan.  logs.zip is at https://www.dropbox.com/s/cl49nmjzjuejl5u/logs.zip?dl=0

**Comment by scottmarlow** [comment]
the test source is at https://github.com/wildfly/wildfly/blob/master/testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/secondlevelcache/JPA2LCTestCase.java#L238 and the called test bean method is at https://github.com/wildfly/wildfly/blob/master/testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jpa/secondlevelcache/SFSB2LC.java#L313

**Comment by rvansa** [comment]
@scottmarlow Thanks, I'll take a look. I don't think that Steve would fancy the idea of him running WF test suite before release, but I probably should check it out after doing some changes.

**Comment by rvansa** [comment]
@scottmarlow Damned, found the problem, silly mistake. Region used for querying is not used via any RegionAccessStrategy and therefore one initialization step is skipped. Quite easy to fix (I suppose), but I don't see any workaround but calling `BaseTransactionalDataRegion.createAccessDelegate(AccessType.TRANSACTIONAL)` using reflection.
https://hibernate.atlassian.net/browse/HHH-10163

**Comment by scottmarlow** [comment]
Regarding running the WildFly testsuite, I don't think Steve is going to run that himself.  It would be more that you could if you wanted to (after making a change to hibernate-infinispan).  You don't need to run the entire testsuite.  It would be more like the following after building ORM locally (./gradlew clean publishToMavenLocal):

cd wildfly_root_folder
./build.sh clean install -Dversion.org.hibernate=5.0.3-SNAPSHOT -DskipTests=true
cd testsuite/integration/basic
mvn clean install -Dtest=*JPA2LCTestCase*

On my Thinkpad T540 (running Fedora), it took 28 seconds to run the test and just under 3 minutes to build WildFly.

**Comment by scottmarlow** [comment]
This pull request can be closed, due to the HHH-10163 regression.

**Comment by scottmarlow** [comment]
I'll close this, lets try again with Hibernate ORM 5.0.3 (if the HHH-10163 issue is addressed by then).

**Comment by scottmarlow** [comment]
Hmm, I don't have permissions to close, so someone else will need to.

**Comment by jamezp** [comment]
Closing per request.

**Pull request closed without merging**
