### PR TITLE
[WFLY-14932] MP Reactive Messaging Kafka user API

### PR DESCRIPTION
**Pull request by kabir**
https://issues.redhat.com/browse/WFLY-14932 /  https://github.com/wildfly/wildfly-proposals/pull/402.

Requires: #14618 (we currently contain the WFLY-14798 commits which are NOT part of this PR)
This has previously been reviewed in #14475

#14618, #14619 (this PR) and #14620 split up the original #14475 which had all the related work bundled together

### CODE REVIEW

**Review by jstourac — COMMENTED** [review]
some nitpicks added

**Review by jstourac — COMMENTED** [review]
just two another nitpicks

**Comment by kabir** [comment]
@jstourac nitpicks resolved

**Review by jstourac — APPROVED** [review]

**Pull request merged**
