### PR TITLE
WFLY-14497, WFLY-14523 Missing HttpSessionActivationListener notification on startup/shutdown for local, passivating cache configurations

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-14497
https://issues.redhat.com/browse/WFLY-14523

### CODE REVIEW

**Comment by pferraro** [comment]
@rhusar Please review

**Comment by rhusar** [comment]
@pferraro The CI failures appear related, retriggered a couple to make sure.

**Comment by pferraro** [comment]
@rhusar These are likely due to the WFLY-14495 fix, which is being reverted.

**Comment by pferraro** [comment]
Actually, org.jboss.as.test.integration.jsf.flash.FlashScopeDistributedSessionTestCase is failing consistently.  Closing for investigation.

**Pull request closed without merging**
