### PR TITLE
[WFLY-13596] Add missing exclusions for dependencies artifacts

### PR DESCRIPTION
**Pull request by rgdoliveira**
Jira: https://issues.redhat.com/browse/WFLY-13596

### CODE REVIEW

**Comment by rgdoliveira** [comment]
@asoldano  @bstansberry @jamezp those exclusions were required in the product branch and I'm sending them upstream too, to keep them sync.

**Comment by jamezp** [comment]
This isn't compiling. It needs a fix like https://github.com/jamezp/wildfly/commit/ade0143440abfa90374d084fd6a551769320a053.

**Comment by rgdoliveira** [comment]
> This isn't compiling. It needs a fix like [jamezp@ade0143](https://github.com/jamezp/wildfly/commit/ade0143440abfa90374d084fd6a551769320a053).
Thanks @jamezp. I just ammended your fix in my commit.

**Review by jamezp — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks, @rgdoliveira

**Pull request merged**
