### PR TITLE
[WFLY-18348] PermissionUtils should delegate to the WildFly Core variant where possible

### PR DESCRIPTION
**Pull request by lvydra**
https://issues.redhat.com/browse/WFLY-18348

### CODE REVIEW

**Review by rhusar — CHANGES_REQUESTED** [review]
This creates a lot of failures triggered by `Caused by: java.lang.NoClassDefFoundError: nu/xom/Node` since clearly org.jboss.as.test.shared.PermissionUtils is still relying on xom.

**Comment by lvydra** [comment]
Hi @rhusar , thank you for your comment. It seems that the problem is in wildfly-core dependency not yet including changes done in the https://issues.redhat.com/browse/WFCORE-6461.

**Comment by bstansberry** [comment]
When I merged the WFCORE-6461 fix I set the wrong Fix Version. So it's not yet in the core release the WF uses.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @lvydra!

**Pull request merged**
