### PR TITLE
WFLY-18890 docs/schema does not contain orm_3-1.xsd

### PR DESCRIPTION
**Pull request by scottmarlow**
https://issues.redhat.com/browse/WFLY-18890

### CODE REVIEW

**Comment by scottmarlow** [comment]
This change isn't enough, perhaps we need to reference the `jipijapa-xsd` artifact somewhere in the WildFly build.

Output of `jar tf ~/.m2/repository/org/wildfly/jipijapa-xsd/31.0.0.Final-SNAPSHOT/jipijapa-xsd-31.0.0.Final-SNAPSHOT.jar`:
> META-INF/MANIFEST.MF
META-INF/
schema/
META-INF/maven/
META-INF/maven/org.wildfly/
META-INF/maven/org.wildfly/jipijapa-xsd/
schema/orm_3_1.xsd
META-INF/maven/org.wildfly/jipijapa-xsd/pom.xml
META-INF/maven/org.wildfly/jipijapa-xsd/pom.properties
META-INF/INDEX.LIST

**Comment by bstansberry** [comment]
If you just create a jpa/hibernate6/src/main/resources/schema dir and put it there, that's all you should need.

You could also just put it in the existing jpa/subsystem/src/main/resources/schema dir. That's a bit less 'elegant' because the schema is for Hibernate, not the subsystem in general. But it doesn't really matter.

The 'group' element in wildfly-feature-pack.xml refers to a maven groupId, which for full WF modules is the 'org.wildfly' that's already there. No need for a new entry.

**Comment by scottmarlow** [comment]
> If you just create a jpa/hibernate6/src/main/resources/schema dir and put it there, that's all you should need.
> 
> You could also just put it in the existing jpa/subsystem/src/main/resources/schema dir. That's a bit less 'elegant' because the schema is for Hibernate, not the subsystem in general. But it doesn't really matter.
> 
> The 'group' element in wildfly-feature-pack.xml refers to a maven groupId, which for full WF modules is the 'org.wildfly' that's already there. No need for a new entry.

Thanks @bstansberry, I now can see orm_3_1.xsd under dist/target/wildfly-31.0.0.Final-SNAPSHOT/docs/schema!

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @scottmarlow

**Pull request merged**
