### PR TITLE
[WFLY-17850] Upgrade nimbus-jose-jwt to 9.31

### PR DESCRIPTION
**Pull request by anilabhabaral**
Jira: https://issues.redhat.com/browse/WFLY-17850

### CODE REVIEW

**Review by bstansberry — CHANGES_REQUESTED** [review]
Hi @anilabhabaral -- I'll ask @fjuma to approve the upgrade itself, but I have a couple paperwork requests:

1) Please change the commit message and PR title to say "to 9.31" instead of "to more recent version".
2) Same for the title of WFLY-17850.
3) Normally I'd require that you edit the description block of WFLY-17850 to include a git diff link showing the diff between the 9.24.4 tag and the 9.31 tag, or release note links. The git diff is easy to do with github repos, but the Bitbucket variant https://bitbucket.org/connect2id/nimbus-jose-jwt/branches/compare/9.24.4..9.31#diff doesn't show anything. So this is just an FYI for the future.

**Comment by anilabhabaral** [comment]
Hello @bstansberry Thank you for the suggestion.
I made the suggested changes. Please check.

**Review by fjuma — APPROVED** [review]
Thanks for the updates @anilabhabaral! The upgrade itself also looks good to me.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @anilabhabaral and @fjuma

**Pull request merged**
