### PR TITLE
[WFLY-15978] JCA: move Elytron metadata to IronJacamar code

### PR DESCRIPTION
**Pull request by tadamski**
this PR depends on https://github.com/ironjacamar/ironjacamar/pull/750

### CODE REVIEW

**Comment by bstansberry** [comment]
@tadamski Any update on this one? CI failed with compilation problems.

**Comment by tadamski** [comment]
@bstansberry I opened this PR for review purposes but it depends on https://github.com/ironjacamar/ironjacamar/pull/750 and will fail without it - I will update the description to mention that

**Comment by bstansberry** [comment]
@tadamski The GitHub draft PR feature is a good way to do that kind of thing, as it saves the mergers needing to check on it until you are ready to move it out of draft state.

**Comment by tadamski** [comment]
@bstansberry OK, I will close those PRs then

**Pull request closed without merging**
