### PR TITLE
[WFLY-14184] Update joda-time to 2.10.10

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes [WFLY-14184](https://issues.redhat.com/browse/WFLY-14184)

### CODE REVIEW

**Comment by bstansberry** [comment]
@asoldano or @jimma Please review. This is used in the webservices subsystem.

**Comment by jimma** [comment]
joda-time is one of wss4j 2.2.5's transitive dependencies. It's more safe to upgrade 2.10.8 in wss4j and have a check first.

```
[INFO] org.apache.wss4j:wss4j-ws-security-dom:jar:2.2.5
[INFO] +- org.apache.wss4j:wss4j-ws-security-common:jar:2.2.5:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.29:compile
[INFO] |  +- org.apache.santuario:xmlsec:jar:2.1.5:compile
[INFO] |  |  +- com.fasterxml.woodstox:woodstox-core:jar:5.0.3:compile
[INFO] |  |  |  \- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.13:compile
[INFO] |  +- org.opensaml:opensaml-saml-impl:jar:3.3.1:compile
[INFO] |  |  +- org.opensaml:opensaml-profile-api:jar:3.3.1:compile
[INFO] |  |  |  \- org.opensaml:opensaml-core:jar:3.3.1:compile
[INFO] |  |  |     \- io.dropwizard.metrics:metrics-core:jar:3.1.2:compile
[INFO] |  |  +- org.opensaml:opensaml-saml-api:jar:3.3.1:compile
[INFO] |  |  |  +- org.opensaml:opensaml-xmlsec-api:jar:3.3.1:compile
[INFO] |  |  |  \- org.opensaml:opensaml-soap-api:jar:3.3.1:compile
[INFO] |  |  +- org.opensaml:opensaml-security-impl:jar:3.3.1:compile
[INFO] |  |  |  \- org.opensaml:opensaml-security-api:jar:3.3.1:compile
[INFO] |  |  +- org.opensaml:opensaml-xmlsec-impl:jar:3.3.1:compile
[INFO] |  |  \- net.shibboleth.utilities:java-support:jar:7.3.0:compile
[INFO] |  |     +- com.google.guava:guava:jar:19.0:compile
[INFO] |  |     \- joda-time:joda-time:jar:2.9:compile
```

**Comment by bstansberry** [comment]
@jimma I'm not clear on what you'd like re this PR. Would you prefer that it be closed and then you'd do this update along with an update to wss4j whenever you're ready? Or are you looking for @boris-unckel to build/test wss4j with this upgrade and post results?

**Comment by boris-unckel** [comment]
The test was successful:

```diff --git a/ws-security-common/pom.xml b/ws-security-common/pom.xml

index 1137051ab..a4866377a 100644
--- a/ws-security-common/pom.xml
+++ b/ws-security-common/pom.xml
@@ -30,7 +30,7 @@
     
     <properties>
         <wss4j.osgi.import>
-            org.joda.time*;version="[1.6,3)",
+            org.joda.time*;version="[2.10,3)",
             net.shibboleth*;resolution:=optional
         </wss4j.osgi.import>
         <!--
@@ -135,8 +135,18 @@
                     <groupId>org.cryptacular</groupId>
                     <artifactId>cryptacular</artifactId>
                 </exclusion>
+                <exclusion>
+                    <groupId>joda-time</groupId>
+                    <artifactId>joda-time</artifactId>
+                </exclusion>
             </exclusions>
         </dependency>
+        <dependency>
+            <groupId>joda-time</groupId>
+            <artifactId>joda-time</artifactId>
+            <version>2.10.10</version>
+            <scope>compile</scope>
+        </dependency>
```

result of mvn clean install
`[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.wss4j.common.crypto.SKITest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.176 s - in org.apache.wss4j.common.crypto.SKITest
[INFO] Running org.apache.wss4j.common.crypto.AuthorityKeyIdentifierTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.037 s - in org.apache.wss4j.common.crypto.AuthorityKeyIdentifierTest
[INFO] Running org.apache.wss4j.common.crypto.PasswordEncryptorTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 s - in org.apache.wss4j.common.crypto.PasswordEncryptorTest
[INFO] Running org.apache.wss4j.common.crypto.MerlinTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.163 s - in org.apache.wss4j.common.crypto.MerlinTest
[INFO] Running org.apache.wss4j.common.crypto.NameConstraintsTest
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.103 s - in org.apache.wss4j.common.crypto.NameConstraintsTest
[INFO] Running org.apache.wss4j.common.saml.OpenSAMLUtilTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.268 s - in org.apache.wss4j.common.saml.OpenSAMLUtilTest
[INFO] Running org.apache.wss4j.common.cache.ReplayCacheTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.633 s - in org.apache.wss4j.common.cache.ReplayCacheTest
[INFO] Running org.apache.wss4j.common.cache.EHCacheManagerHolderTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.041 s - in org.apache.wss4j.common.cache.EHCacheManagerHolderTest
[INFO] Running org.apache.wss4j.common.attachment.AttachmentTest
[INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 s - in org.apache.wss4j.common.attachment.AttachmentTest
[INFO] Running org.apache.wss4j.common.attachment.CRLFOutputStreamTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.089 s - in org.apache.wss4j.common.attachment.CRLFOutputStreamTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 55, Failures: 0, Errors: 0, Skipped: 0
`

**Comment by jimma** [comment]
@boris-unckel  Thanks for the check. Sorry, I am late to back on this . Unless there is some important issue we need to upgrade joda version in WFLY, I'd like to upgrade this along with wss4j 2.2.7 upgrade. @bstansberry 
I already sent PR to upgrade this in wss4j: https://github.com/apache/ws-wss4j/pull/34.

**Comment by darranl** [comment]
@jimma / @boris-unckel Does this mean we can close this one and align with the wss4j upgrade to come later?

**Comment by boris-unckel** [comment]
@darranl @jimma Yes, I'm fine with it - new one with wss4j.

**Pull request closed without merging**
