### PR TITLE
WFLY-6185 additional permissions to DeploymentOverlayCLITestCase for …

### PR DESCRIPTION
**Pull request by istudens**
…the case of privileged blocks in VFS

https://issues.jboss.org/browse/WFLY-6185

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@ctomc would this still be needed after your VFS permissions fix? (I don't really know the details)

**Comment by bstansberry** [comment]
I don't see anything in what this test is doing that looks like the app should need these permissions, so let's not grant them and hide the problem.

**Comment by istudens** [comment]
I was so engrossed in JBVFS-204 that I did not notice that even VirtualFilePermissions should not be needed. I will take a look at it again.

**Comment by kabir** [comment]
@istudens Please rebase

**Comment by istudens** [comment]
Superseded by https://github.com/wildfly/wildfly-core/pull/1753.

**Pull request closed without merging**
