### PR TITLE
WFLY-2627 test for override transaction type through ejb-jar.xml

### PR DESCRIPTION
**Pull request by hsvabek**
Test for https://issues.jboss.org/browse/WFLY-2627
https://bugzilla.redhat.com/show_bug.cgi?id=1180556

### CODE REVIEW

**Comment by kabir** [comment]
I hit merge too early, reverting

**Comment by kabir** [comment]
@hsvabek it is not clear if you are a Red Hat employee or not. If you are not, please reply "I agree" to the  following statement.

We require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to the these terms?

**Comment by hsvabek** [comment]
Hi, I am Red Hat employee. Anyway I agree with these terms.

**Comment by kabir** [comment]
@hsvabek sorry my revert seems to have caused some problems with being able to reopen this. Would you be able to rebase and open a new one so we can get a testsuite run on the PR.

**Pull request merged**
