### PR TITLE
[XNIO-291] Automated test: remoting API is used to connect/disconnect Wildfly repeatedly

### PR DESCRIPTION
**Pull request by dcihak**
Test enables SSL on remoting/http connector and runs multiple client threads that use remoting API to connect/disconnect Wildfly repeatedly. If the XNIO000017 error occurs test fails.

Upstream JIRA: https://issues.jboss.org/browse/XNIO-291

### CODE REVIEW

**Comment by dcihak** [comment]
Please review the code. According to the Brad's last comment on https://issues.jboss.org/browse/JBEAP-14792 this test should be ran separately from the rest of the testsuite. Please suggest possible ways how to do that, probably some particular profile will be used... Thank you for any advises in advance.

**Comment by dcihak** [comment]
Retest this please

**Comment by jamezp** [comment]
@dmlloyd Can you have a look at this?

**Comment by dcihak** [comment]
Retest this please

**Comment by dcihak** [comment]
@dmlloyd  Can we merge this?

**Comment by dmlloyd** [comment]
This looks like an automated stress test.  How long does this test usually take to run?  It might be better to put this into XNIO itself.

**Comment by dcihak** [comment]
@dmlloyd  It takes more than 1 minute when running locally, I can move into XNIO.

**Comment by jamezp** [comment]
retest this please

**Pull request closed without merging**
