### PR TITLE
[WFLY-12171] toss the ejb-xa-recovery file permissions out of ejb client tests

### PR DESCRIPTION
**Pull request by istudens**
Please don't merge this yet, it needs to be properly tested first.

https://issues.redhat.com/browse/WFLY-12171

### CODE REVIEW

**Comment by istudens** [comment]
retest this please

**Comment by bstansberry** [comment]
@istudens The security manager CI job failure seems related.

**Comment by istudens** [comment]
@bstansberry I've just added permissions required by the failing test. It should be ok now.

**Comment by istudens** [comment]
retest this please

**Comment by bstansberry** [comment]
@istudens Is the "Please don't merge" request in the PR description still valid?

**Comment by istudens** [comment]
retest this please

**Review by kabir — APPROVED** [review]

**Pull request merged**
