### PR TITLE
[WFLY-14062] Adding new grammar with new parameter.

### PR DESCRIPTION
**Pull request by ronsigal**
https://issues.redhat.com/browse/WFLY-14062

DO NOT MERGE: work in progress

### CODE REVIEW

**Comment by yersan** [comment]
Hello @ronsigal , just for your info, you can create draft PR for this purpose, tests are executed on draft PRs as well.

**Comment by jamezp** [comment]
I've converted this to a draft for now. It can't be merged in it's current state.

**Comment by darranl** [comment]
Hi @ronsigal what is the current state of this one?  Do we need this open for now or can it be closed and reopened later?

@bstansberry this one is addressing a bug but making model changes, will we need the RFE process?

**Comment by bstansberry** [comment]
@darranl @ronsigal I believe this is https://issues.redhat.com/browse/WFLY-14559 which is an RFE.

Ron, can you correct the PR title, any commit message and the JIRA link in the PR description please? Thanks. WFLY-14062 is resolved and released so for sure that's not the JIRA we'll use for further work.

**Comment by darranl** [comment]
@ronsigal / @jamezp Are we able to follow up on this one?  It was last updated in April - do we need the PR open at this stage?

**Comment by jamezp** [comment]
I wonder if it should just be included in #14862

**Comment by bstansberry** [comment]
This PR has been inactive for a long time so I'm going to close it. @ronsigal, please create a new PR if appropriate.

**Pull request closed without merging**
