### PR TITLE
[WFLY-15371] Increase MP Config test coverage

### PR DESCRIPTION
**Pull request by kabir**
https://issues.redhat.com/browse/WFLY-15371

### CODE REVIEW

**Comment by bstansberry** [comment]
@kabir I was going to approve this but the test failure on Windows looks related.

**Comment by kabir** [comment]
I thought I'd fixed the Windows problem but it appears not :-( Will look next week

**Comment by kabir** [comment]
@bstansberry this should be ok now - at least I was able to verify on a Windows VM

**Comment by kabir** [comment]
Unrelated failure in clustering

**Review by darranl — APPROVED** [review]

**Pull request merged**
