### PR TITLE
Workaround intermittent failures by forcing test order (e.g. WFARQ-14)

### PR DESCRIPTION
**Pull request by rhusar**
Can help testsuite stability.

### CODE REVIEW

**Review by ctomc — CHANGES_REQUESTED** [review]
This is not proper workarond. It just happens to fix it for a bit. which can change at any point in time.

**Comment by rhusar** [comment]
This is not specific just for the WFARQ-14 (IIUC @kabir 's test runs shown this helped) but rather a general stabilization. I am a bit split here, since ideally I would like the test order to be random (sort of the current default where the order is not random but undefined) but we end up chasing intermittent testsuite framework issues for the sake of testsuite stability. Not sure if its worth the time.

**Comment by kabir** [comment]
I'll take a look about how many clustering failures we see. It might be a bit more stable now than it seemed laste week

**Comment by rhusar** [comment]
@kabir let's close this if not needed?

**Pull request closed without merging**
