### PR TITLE
[WFLY-15978] Enable Elytron security domains for all connectors

### PR DESCRIPTION
**Pull request by bstansberry**
Issue: https://issues.redhat.com/browse/WFLY-15978
Upstream: https://github.com/wildfly/wildfly/pull/15157

### CODE REVIEW

**Comment by bstansberry** [comment]
@tadamski @reinhapa I ported this to the 26.x branch for possible inclusion in WF 26.1.

**Comment by darranl** [comment]
I am going to close for now as the upstream fix is being reviewed, we can either reopen or create a new backport if we think the resulting changes could be included in WildFly 26.1.1

**Comment by reinhapa** [comment]
@darranl sad, so I will have to patch it in this case...

**Comment by tadamski** [comment]
@reinhapa I'm working on alternative PR

**Comment by reinhapa** [comment]
@tadamski any chance to have this in a later 26.1.1?

**Comment by tadamski** [comment]
hi @reinhapa
I have opened PRs which move Elytron configuration metadata to IronJacamar code:
https://github.com/ironjacamar/ironjacamar/pull/750
https://github.com/wildfly/wildfly/pull/15440 
The idea behind those is that you can mark IJ resources as Elytron enabled by adding 'elytron' tag in the configuration. This way such configurations can work with new WildFly/EAP and be verified as Elytron based. OTOH we are avoiding transforming all legacy configs to Elytron under the hood (possibly without the knowledge of the deployment creator).

**Comment by tadamski** [comment]
hi @reinhapa 
I have reopend those PR as draft ones:
https://github.com/ironjacamar/ironjacamar/pull/754
https://github.com/wildfly/wildfly/pull/15556

**Pull request closed without merging**
