### PR TITLE
WFLY-14767 Upgrade to Hibernate Search 5.10.11.Final 

### PR DESCRIPTION
**Pull request by yrodiere**
https://issues.redhat.com/browse/WFLY-14767

cc @scottmarlow , @gbadner , @wolfc 

This pull request is based on #14177: we need the upgrade to Avro 1.10 in order for Hibernate Search 5.10.11 to work correctly. (and vice-versa: we need the upgrade to Hibernate Search 5.10.11 in order to upgrade to Avro 1.10, because Hibernate Search 5.10.10 and below will not work with Avro 1.10).

See the relevant conversation here: https://github.com/wildfly/wildfly/pull/14177#pullrequestreview-626604791

The full changelog since Hibernate Search 5.10.7.Final is available [here](https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20fixVersion%20in%20(5.10.11.Final%2C%205.10.10.Final%2C%205.10.9.Final%2C%205.10.8.Final)%20ORDER%20BY%20updated). To sum up:

* Upgrade to Avro 1.10 / Jackson 2
* Various upgrades to a higher version of ORM 5.3 => no consequences on WildFly
* Various upgrades to tests dependencies and the build => no consequences on WildFly
* [HSEARCH-3767](https://hibernate.atlassian.net/browse/HSEARCH-3767): Elasticsearch date/time bridges throw NPE on projections => not relevant to WildFly, as we don't package the Elasticsearch integration as a module
* [HSEARCH-3801](https://hibernate.atlassian.net/browse/HSEARCH-3801): Hibernate Search blocks loading  => not relevant to WildFly, as we don't package this artifact as a module

### CODE REVIEW

**Review by scottmarlow — APPROVED** [review]
Approving based on the Hibernate Search update part of this pull request via https://github.com/wildfly/wildfly/pull/14281/commits/280ad0073bfbdcbf2e4def353ab26cbfd616feec

**Comment by bstansberry** [comment]
@ronsigal Any concerns?  See #14177 for the main discussion; this PR just adds a necessary 4th commit but one that is unrelated to JAXRS.

**Comment by jamezp** [comment]
What is the reason for the removal of Jackson and the RESTEasy modules? While I don't fully disagree with removing them, as we might be doing that soon anyway, I don't see a reason for it in this PR.

**Comment by bstansberry** [comment]
@jamezp This PR is really just a continuation of #14177; see the discussion there. The overall purpose of the work is to remove the unmaintained except by EAP SET codehaus jackson which long ago was superceded by FasterXML Jackson. The Hibernate Search upgrade was just the last piece in the puzzle.

**Review by jamezp — APPROVED** [review]
My apologies for not reading the comments on the other PR. I'm completely okay with this. The one remaining question I'd have is should we add some documentation about this or maybe add require a release note for WildFly 24 indicating it's been removed.

**Comment by bstansberry** [comment]
@jamezp I filed https://issues.redhat.com/browse/WFLY-14786 to capture suggestions like your previous comment. Thanks!

**Comment by bstansberry** [comment]
Thanks @yrodiere @wolfc !

**Pull request merged**
