### PR TITLE
WFLY-7140 fix EJB injection with "ejb:" lookup prefix.

### PR DESCRIPTION
**Pull request by tremes**
https://issues.jboss.org/browse/WFLY-7140

### CODE REVIEW

**Comment by mkouba** [comment]
Looks good.

**Comment by bstansberry** [comment]
@tremes We can't merge this currently unless a JBEAP issue is filed and a PR against 7.x submitted and linked.

**Comment by tremes** [comment]
https://issues.jboss.org/browse/JBEAP-6312
https://github.com/jbossas/jboss-eap7/pull/827

**Comment by kabir** [comment]
@tremes needs a rebase

**Comment by tremes** [comment]
Rebased.

**Pull request merged**
