### PR TITLE
WFLY-16417 Add MP certification page generation script

### PR DESCRIPTION
**Pull request by xstefank**
https://issues.redhat.com/browse/WFLY-16417

### CODE REVIEW

**Comment by bstansberry** [comment]
@xstefank https://ci.wildfly.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=308057 was a custom CI run with -Dmicroprofile-certification added to the maven params. The script execution failed.

**Comment by xstefank** [comment]
thanks @bstansberry for the job, I will fix it

**Comment by bstansberry** [comment]
@xstefank Ping me in zulip if you need info on how I kicked off that job.

**Comment by xstefank** [comment]
@bstansberry sorry it took me this while. Finally working in CI - https://ci.wildfly.org/buildConfiguration/WF_PullRequest_LinuxMicroProfileJdk11_2/310446?buildTab=buildParameters. We need to add additional parameter `env.MAVEN_REPO_LOCAL=%teamcity.maven.local.repository.path%` which is used in the help plugin to get the spec versions and of course `-Dmicroprofile-certification`. Then just save the certification/target output to get the copy-paste adoc for the certification. Will you set up jobs in CI for JDK 8, 11, 17? No problem to write them myself if I have permissions. Also if I'll have time maybe I will put together another script that pulls the JDK x results together.

**Comment by bstansberry** [comment]
Thanks @xstefank. Sorry it took a while to get to this. I've added the env var to the 'Certifications' jobs under https://ci.wildfly.org/admin/editProject.html?projectId=WF_MainNightlyJobs

To use this for 26.1.2 (probably first half of August) we'd need a PR against 26.x. I've added 'Certification' jobs under https://ci.wildfly.org/project.html?projectId=WF_26xNightlyJobs although I didn't run any of them to check for problems.

**Pull request merged**
