### PR TITLE
[WFLY-6550] Use fromString instead of create when the text may includ…

### PR DESCRIPTION
**Pull request by bstansberry**
…ude a slot

@maeste @jmesnil @pedroigor @darranl @stuartwdouglas please doublecheck the files related to use to confirm I'm doing the right thing.

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
:+1:

**Comment by maeste** [comment]
￼￼LGTM

**Comment by jmesnil** [comment]
+1

**Comment by darranl** [comment]
Looks good

**Comment by bstansberry** [comment]
retest this please

**Pull request merged**
