### PR TITLE
WFLY-17885 Remove the unused Hibernate 6.0 module

### PR DESCRIPTION
**Pull request by scottmarlow**
https://issues.redhat.com/browse/WFLY-17885

Lets remove the ORM 6.0 alias module until there is an actual demand to have it.

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]

**Review by bstansberry — APPROVED** [review]
@scottmarlow Agreed; let's get this removed for 28 Final. In WF 28 we've gone to ORM 6.2 so it's appropriate to drop a 6.0 module as part of that same general transition.

**Comment by bstansberry** [comment]
@scottmarlow This fails because of https://issues.redhat.com/browse/WFLY-17891.  I'll send a PR to your branch with a workaround.

**Comment by bstansberry** [comment]
@scottmarlow Workaround is https://github.com/scottmarlow/wildfly/pull/31

**Comment by scottmarlow** [comment]
> @scottmarlow Workaround is [scottmarlow#31](https://github.com/scottmarlow/wildfly/pull/31)

Thanks for the workaround @bstansberry!

**Comment by bstansberry** [comment]
@scottmarlow There are other test failures though.

**Comment by scottmarlow** [comment]
> @scottmarlow There are other test failures though.

I should of ran the Persistence tests locally.  I'll fix and verify `JpaJarFileTestCase` locally.

**Comment by scottmarlow** [comment]
The `Windows - JDK 11` test failure in org.jboss.as.test.clustering.cluster.web.ConcurrentCoarseWebFailoverTestCase.testGracefulSimpleFailover doesn't look related to this change.

**Comment by bstansberry** [comment]
Thanks @scottmarlow

**Pull request merged**
