### PR TITLE
WFLY-5078 Transaction subsystem attribute 'hornetq-store-enable-async-io' should be renamed for journal

### PR DESCRIPTION
**Pull request by zhfeng**
https://issues.jboss.org/browse/WFLY-5078

### CODE REVIEW

**Comment by bstansberry** [comment]
This is an incompatible change. The old attribute needs to continue to be supported as an alias for the new attribute. It should be deprecated if it isn't already. Use of the new attribute needs to be transformed so legacy hosts in a multi-version managed domain can handle the attribute.

**Comment by zhfeng** [comment]
@bstansberry can you reviews these changes ?

**Comment by bstansberry** [comment]
@jmesnil Please approve.

**Comment by jmesnil** [comment]
looks good to me.

**Pull request merged**
