### PR TITLE
[WFLY-11702] Upgrade yasson to 1.0.3

### PR DESCRIPTION
**Pull request by reinhapa**
https://issues.jboss.org/browse/WFLY-11702

### CODE REVIEW

**Comment by bstansberry** [comment]
@asoldano or @ronsigal Please approve

**Comment by reinhapa** [comment]
@bstansberry hmm, seems that that minor update of `yasson` now needs Java 11 - hmm :-(

**Comment by bstansberry** [comment]
@reinhapa Why do you say that? Looking at the yasson pom I don't see anything different that would mean it requires JDK 11.

**Comment by reinhapa** [comment]
@bstansberry sorry, my bad. Looked into the one on the master branch though..

**Review by asoldano — APPROVED** [review]

**Comment by reinhapa** [comment]
@bstansberry sorry, I missed that somehow... Would be great to have the new version in the next Wildfly though...

**Pull request merged**
