### PR TITLE
[WFLY-7245] Upgrade to Artemis 1.4.0

### PR DESCRIPTION
**Pull request by jmesnil**
JIRA: https://issues.jboss.org/browse/WFLY-7245

### CODE REVIEW

**Comment by jmesnil** [comment]
regression with security manager is caused by https://github.com/apache/activemq-artemis/pull/538/files

**Comment by bstansberry** [comment]
@jmesnil So should that be fixed with a Blocker bug for the next Artemis release, and then for this PR we use org.junit.Assume to ignore the test if the SM is present?

My read of the Artemis change is it's something that artemis should be calling from a privileged block, i.e. the application shouldn't need perms for this.

**Comment by jmesnil** [comment]
@bstansberry you're right. Artemis has already fixed the issue in their master branch (https://github.com/apache/activemq-artemis/pull/847).

If you're ok with that, I'll amend this PR to add calls to Assume to the relevant failing tests with a security manager so we can proceed with Artemis 1.4.0 release.
They are planning to release another release next week which will contain the fix and I'll un-Assume the tests when I integrate this future release.

**Comment by kabir** [comment]
Retest this please

**Comment by jmesnil** [comment]
I'm closing this PR: QE found an issue with Artemis (https://issues.jboss.org/browse/WFLY-7352) that requires a Netty upgrade that in turn creates an issue in the xnio<->netty bridge.
Until this issue is resolved, we can not ugprade to Artemis 1.4.0

**Pull request merged**
