### PR TITLE
WFLY-8533 and WFLY-6194

### PR DESCRIPTION
**Pull request by istudens**
A single PR for both WFLY-8533 and WFLY-6194. The former is a fix in EE subsystem and the latter is a fix in the relevant testcase.

https://issues.jboss.org/browse/WFLY-8533
https://issues.jboss.org/browse/WFLY-6194

### CODE REVIEW

**Comment by istudens** [comment]
@dmlloyd David, could you approve please?

Note that the deployment needs an explicit dependency on ```org.jboss.remoting``` module to be able to load ```RemotingPermission```. See also MODULES-234.

**Comment by darranl** [comment]
Can we please instead have a PR submitted against ladybird instead so we can group with other changes.

**Comment by istudens** [comment]
@darranl where can I find the ladybird?

**Comment by darranl** [comment]
The ladybird branch is here https://github.com/wildfly-security-incubator/wildfly

**Comment by dmlloyd** [comment]
Deployments should never need a remoting permission.  I think this probably points to a missing doPrivileged?

**Comment by istudens** [comment]
Those remoting permissions are needed due to CLI (ManagementClient) usage, see
https://github.com/wildfly/wildfly/blob/master/testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/suspend/EEConcurrencySuspendTestCase.java#L120

**Comment by kabir** [comment]
@istudens Please reopen for ladybird

**Comment by istudens** [comment]
Superseded by https://github.com/wildfly-security-incubator/wildfly/pull/181.

**Pull request closed without merging**
