### PR TITLE
[JBEAP-16664][WFLY-10808] - test for said issues.

### PR DESCRIPTION
**Pull request by baranowb**
Follow up on https://github.com/wildfly/wildfly/pull/11911

### CODE REVIEW

**Comment by jamezp** [comment]
retest this please

**Comment by jamezp** [comment]
This looks like it needs a rebase.

**Comment by jamezp** [comment]
I'm placing a temporary hold on this.

**Review by darranl — CHANGES_REQUESTED** [review]
Can we please use meaningful commit messages, in five years time someone may need to know what 'said issues' are when working on these tests - whilst it is true they could look up the Jira issue when source ends up with a list of messages like this it becomes difficult.

**Comment by baranowb** [comment]
Why include JIRA reference than?
Updated: https://github.com/wildfly/wildfly/pull/12368

**Comment by jamezp** [comment]
With only the JIRA reference it forces you to look up the JIRA.

**Pull request closed without merging**
