### PR TITLE
[WFLY-10060] add jboss-module to jaxws-client to enable apache compil…

### PR DESCRIPTION
**Pull request by rsearls**
…er to work.

https://issues.jboss.org/browse/WFLY-10060

Added module reference to jbossws-client

### CODE REVIEW

**Review by asoldano — APPROVED** [review]

**Review by asoldano — COMMENTED** [review]
Actually, thinking about this again, while it's true that this would not hurt, I'm not really convinced yet it's needed. This is related to how we fix the underlying https://issues.jboss.org/browse/JBWS-4107 issue.

**Comment by kabir** [comment]
@rsearls I am adding the 'hold' label, due to @asoldano 's comment. Please ping me if it is needed, or close it.

**Comment by kabir** [comment]
@rsearls @asoldano I am closing this for now. Feel free to reopen if you decide this is the correct approach

**Comment by asoldano** [comment]
@kabir , a new PR, equivalent to this, has been created at https://github.com/wildfly/wildfly/pull/11101 . I don't see any re-open button, probably Rebecca doesn't either.

**Comment by kabir** [comment]
@asoldano thanks, I guess only mergers can reopen then

**Pull request closed without merging**
