### PR TITLE
WFLY-17292 Upgrade smallrye-open-api to 3.1.2

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-17292

### CODE REVIEW

**Comment by rhusar** [comment]
@pferraro Needs a rebase now.

**Review by rhusar — CHANGES_REQUESTED** [review]
In case you missed it, the TCKs now seem to fail consistently after the rebase with

 >  java.lang.NoSuchMethodError: 'org.hamcrest.Matcher org.hamcrest.Matchers.anEmptyMap()'
 
 and alike.

**Review by rhusar — APPROVED** [review]
LGTM now – but the final word goes to @kabir  :-)

**Comment by kabir** [comment]
Looks good to me :-)

@bstansberry This is part of the RFE tracked by https://github.com/wildfly/wildfly-proposals/pull/499. Can this go in now, or do we need to hold it

**Comment by bstansberry** [comment]
@kabir @pferraro Let's discuss tomorrow.

**Comment by bstansberry** [comment]
Thanks @pferraro, @rhusar and @kabir!

**Pull request merged**
