### PR TITLE
[WFLY-11574] reduced permissions for wsse trust test-cases

### PR DESCRIPTION
**Pull request by istudens**
Issue: https://issues.redhat.com/browse/WFLY-11574

### CODE REVIEW

**Comment by istudens** [comment]
@jamezp can you review this please? thanks

**Comment by jamezp** [comment]
@rsearls or @jimma would be better fit to check this. I'm not too familiar with web services.

**Comment by jimma** [comment]
@istudens This looks good as all tests passed.

**Review by jimma — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @istudens and @jimma

**Pull request merged**
