### PR TITLE
[WFLY-13549] Apply class filtering to remote EJB and Naming invocations

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFLY-13549

Also incorporates necessary upgrades:

https://issues.redhat.com/browse/WFLY-13522
https://issues.redhat.com/browse/WFLY-13551
https://issues.redhat.com/browse/WFLY-13552

@chengfang @tadamski @fl4via @ropalka @asoldano @jamezp FYI

### CODE REVIEW

**Review by jamezp — APPROVED** [review]

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
The LocalViewRemoteInvocationTestCasetestServerInVMInvocationOnLocalViewOfSFSB failures that will be reported are because a call that is expected to fail is indeed failing, but with an EJBException instead of the expected ISE. The message of the EJBException is along the expected lines (complains about local view for a remote bean) so it's perhaps ok, but I don't see why this PR would result in a different call path here. I'm debugging.

**Comment by chengfang** [comment]
The EJBException seen in the failure was reported by ejb client, while the expected IllegalStateException is to be reported by [LocalEjbReceiver](https://github.com/wildfly/wildfly/blob/master/ejb3/src/main/java/org/jboss/as/ejb3/remote/LocalEjbReceiver.java#L104) (judgeing from [AS7-5103](https://issues.redhat.com/browse/AS7-5103)). So looks like the check that should've been performed by `LocalEjbReceiver` was not there and hence the error leaks to and was caught by client.

**Comment by bstansberry** [comment]
@chengfang AIUI EJBClientInvocationContext resolves an EJBReceiver. It loops through the available ones and uses the first that supports the scheme of the destination URL. LocalTransportProvider should be the last one it checks as it's the last added to the list. It only accepts 'local' scheme.  But before it was being selected and now it seems RemoteTransportProvider is.  That implies the URL has a different scheme from before.  I'm not seeing how that happens yet, but it seems like it must be.

A guess I had is this had something to do with the naming changes (different object resolved leads to different state and code paths.). But eliminating the use of the filtering in naming has no effect on this.

**Comment by bstansberry** [comment]
@chengfang Now I suspect this may have something to do with the wildfly-http-client upgrade so I filed #13442 to test that on its own.

The session creation call hits the LocalEjbReceiver but the method invocation goes to RemoteEjbReceiver.  I don't see how my changes could have any bearing on what URL is used for the invocation.

**Comment by chengfang** [comment]
I checked out and rebuild locally with this pull, and ran this test, but it passed locally for me:

```
testsuite/integration/basic > 

mvn test -Dtest=org.jboss.as.test.integration.ejb.remote.view.LocalViewRemoteInvocationTestCase#testServerInVMInvocationOnLocalViewOfSFSB
```

I also tested it in a [sample](https://github.com/chengfang/hello-local-remote.git) with similar scenario (look up local sfsb with ejb: jndi name, and call it), deployed to the WF built above, got the expected `IllegalStateException`.

**Comment by bstansberry** [comment]
@chengfang It's failing every time locally for me. (Another test in testsuite/int/basic always fails for me, some local env issue, and that prevented me realizing the surefire execution this one is in wasn't running.)

The reason it fails is with this PR RemotingEJBDiscoveryProvider is discovering the remote+http URL while with master it does not. (With both this PR and master the local discovery provider from AssociationService also discovers "local:-".) The failure happens because when the bean is invoked it uses the first URL discovered. With master the only one is "local:-" but with this PR it is the remote+http URL.

It's a pain figuring out why this is. I still have no clue how this PR could be the cause. (I've separately tested just the component upgrades, individually and as a set and they don't cause the problem.)

**Comment by bstansberry** [comment]
@chengfang This should fix it:

https://github.com/wildfly/wildfly/pull/13338/files#diff-c8a90d2dcf5f441488f745f6716c16e5R39

The reason I couldn't figure out how adding the filter stuff could affect this is that it didn't. :) It was a new test altering the server's state and thus affecting the other.

**Comment by chengfang** [comment]
> @chengfang This should fix it:
> 
> https://github.com/wildfly/wildfly/pull/13338/files#diff-c8a90d2dcf5f441488f745f6716c16e5R39
> 
> The reason I couldn't figure out how adding the filter stuff could affect this is that it didn't. :) It was a new test altering the server's state and thus affecting the other.

Interesting! I thought each test case starts its own server independent of each other. Anyway, great to sort it out.

**Pull request merged**
