### PR TITLE
WFLY-5450 upgrade to Hibernate ORM 5.0.5

### PR DESCRIPTION
**Pull request by scottmarlow**

### CODE REVIEW

**Comment by scottmarlow** [comment]
https://issues.jboss.org/browse/JBEAP-1604 is linked to this.  Last nights TCK run passed with the Hibernate 5.0.5-SNAPSHOT, so I expect today's EE TCK run to also pass.

**Comment by Sanne** [comment]
Please include PR #8431 with this upgrade as well, and make sure to upgrade Hibernate Commons Annotations to 5.0.1.Final as you'll need it for the ORM upgrade too.

**Comment by scottmarlow** [comment]
I updated this pull request to include Hibernate Commons Annotations 5.0.1.Final (which ORM 5.0.5.Final now uses also).  Thanks for the pointer on that.  I'll repeat my question here that I asked on #8431, why is that needed for WF10?

**Comment by scottmarlow** [comment]
We are currently running the EE TCK with Hibernate ORM 5.0.5.Final.  Tonight, we will run again also with Hibernate Commons Annotations 5.0.1.Final + Hibernate ORM 5.0.5.Final.

**Pull request merged**
