### PR TITLE
WFLY-3838 Wildcard (*) for ejb-name should work for all applicable

### PR DESCRIPTION
**Pull request by sdirbach**
occurences of the ejb-name element

### CODE REVIEW

**Comment by ctomc** [comment]
this is ok to test

**Comment by stuartwdouglas** [comment]
We require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to the these terms?

**Comment by sdirbach** [comment]
Yes, I agree. Should I include my agreement also in future pull requests or is this initial agreement sufficient?

**Comment by stuartwdouglas** [comment]
This initial agreement is sufficient, thanks

**Pull request merged**
