### PR TITLE
WFLY-16827 Restructure the WildFly High Availability Guide

### PR DESCRIPTION
**Pull request by rhusar**
Resolves
https://issues.redhat.com/browse/WFLY-16827

The changes generate the following resulting outline:
https://gist.github.com/rhusar/e05afe57568d200b61a7036ba9640358

and have a structure like this on the FS:
https://gist.github.com/rhusar/a872d933f7e4b3f59c2fafa10fff4fad

### CODE REVIEW

**Comment by rhusar** [comment]
@rachmatowicz @pferraro Please have a look guys.

**Comment by pferraro** [comment]
Some cursory comments:
1. I'm not sure that the directory per section is all that useful, but surely we would not want to number them, as the numbering will change when we add/remove sections, unnecessarily breaking any links to doc source.
2. Rename the "Infinispan subsystem" section to "Infinispan", where the subsystem documentation is a subsection.

**Comment by rhusar** [comment]
> Some cursory comments:
> 
> 1. I'm not sure that the directory per section is all that useful, but surely we would not want to number them, 

This will come down to preference, but I find it highly useful while editing. It immediately gives out an idea where the section is within the guide without need to render.

I don't think there is a better way to order sections on the file system / IDE than numbering. There is a comment about numbering; tldr it's only logical and can be changed liberally.

> as the numbering will change when we add/remove sections, unnecessarily breaking any links to doc source.

False – there are no links referencing the source adoc files. 
* Links within this document are either using `xref:` or `<<notation>> ` referencing static `[[anchors]]`.
* Links from outside of the HA guide are referencing the page + static anchor (e.g. `link:High_Availability_Guide{outfilesuffix}#discovery-for-kubernetes[High Availability Guide, section of Kubernetes discovery]`)


> 2. Rename the "Infinispan subsystem" section to "Infinispan", where the subsystem documentation is a subsection.

Fixed (just forgot to push that last change).

**Comment by pferraro** [comment]
> > Some cursory comments:
> > 
> > 1. I'm not sure that the directory per section is all that useful, but surely we would not want to number them,
> 
> This will come down to preference, but I find it highly useful while editing. It immediately gives out an idea where the section is within the guide without need to render.
> I don't think there is a better way to order sections on the file system / IDE than numbering. There is a comment about numbering; tldr it's only logical and can be changed liberally.

Personally, numbering the sections doesn't help me locate documentation source, as I still need to scan the names.  Rather, file names should be pithy and unambiguous.

> > as the numbering will change when we add/remove sections, unnecessarily breaking any links to doc source.
> 
> False – there are no links referencing the source adoc files.

On the contrary, I link to the source asciidocs all the time, usually within jiras, but occasionally in response to community forum posts (to reference unreleased documentation).
 
> * Links within this document are either using `xref:` or `<<notation>> ` referencing static `[[anchors]]`.
> * Links from outside of the HA guide are referencing the page + static anchor (e.g. `link:High_Availability_Guide{outfilesuffix}#discovery-for-kubernetes[High Availability Guide, section of Kubernetes discovery]`)
> 
> > 2. Rename the "Infinispan subsystem" section to "Infinispan", where the subsystem documentation is a subsection.
> 
> Fixed (just forgot to push that last change).

Thx.

**Comment by rhusar** [comment]
@pferraro @rachmatowicz  Great, as I said at the beginning, this will come to a personal preference, but I have managed to find a solution satisfactory for all. Please see the resulting outline, dir structure and see editors notes how it's structured and intended to evolve. 

Gist: no numbering on the FS; there's an adoc file for each section; if a section has includes, those reside in separate directories.

> > > Some cursory comments:
> > > 
> > > 1. I'm not sure that the directory per section is all that useful, but surely we would not want to number them,
> > 
> > 
> > This will come down to preference, but I find it highly useful while editing. It immediately gives out an idea where the section is within the guide without need to render.
> > I don't think there is a better way to order sections on the file system / IDE than numbering. There is a comment about numbering; tldr it's only logical and can be changed liberally.
> 
> Personally, numbering the sections doesn't help me locate documentation source, as I still need to scan the names. Rather, file names should be pithy and unambiguous.
> 
> > > as the numbering will change when we add/remove sections, unnecessarily breaking any links to doc source.
> > 
> > 
> > False – there are no links referencing the source adoc files.
> 
> On the contrary, I link to the source asciidocs all the time, usually within jiras, but occasionally in response to community forum posts (to reference unreleased documentation).

So you mean 'external links to documentation source files'. Still - please no. That's a horrible antipattern and by no means we should be bending over backwards while structuring our docs to "support" this use case. (e.g. all of those links are broken when we renamed master to main) Especially because this has a fairly simple solution – we need to publish documentation for the `main` branch. Coincidentally, I am wanting to set this up as we have done exactly the same thing with e.g. https://docs.modcluster.io/. So hopefully this particular concern can go away soon.

> > * Links within this document are either using `xref:` or `<<notation>> ` referencing static `[[anchors]]`.
> > * Links from outside of the HA guide are referencing the page + static anchor (e.g. `link:High_Availability_Guide{outfilesuffix}#discovery-for-kubernetes[High Availability Guide, section of Kubernetes discovery]`)
> > 
> > > 2. Rename the "Infinispan subsystem" section to "Infinispan", where the subsystem documentation is a subsection.
> > 
> > 
> > Fixed (just forgot to push that last change).
> 
> Thx.

**Review by pferraro — APPROVED** [review]
Looks great.  Definitely an improvement.

**Comment by pferraro** [comment]
> So you mean 'external links to documentation source files'. Still - please no. That's a horrible antipattern

If know of any other way to reference non-released documentation, let me know.

**Pull request merged**
