### PR TITLE
Enable the tests previously disabled for WFCORE-798

### PR DESCRIPTION
**Pull request by darranl**
This PR is going to be dependent on the following PR being merged to WildFly Core https://github.com/wildfly/wildfly-core/pull/992

### CODE REVIEW

**Comment by darranl** [comment]
@bstansberry I have no idea how this passed!

**Comment by bstansberry** [comment]
@darranl I assume it passes because the entire class has @Ignore("WFLY-5138"). See #7985 and https://github.com/wildfly/wildfly-core/pull/991

**Comment by darranl** [comment]
LOL I missed that one - too focussed on the individual ignores!

**Comment by bstansberry** [comment]
retest this please

**Pull request merged**
