### PR TITLE
[WFLY-16984] Refactoring Batch Subsystem to use new MSC value API

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-16984

### CODE REVIEW

**Comment by chengfang** [comment]
Some service classes are changed to implement MSC 2 Service API, while some others don't. Can you detail what prevents the use of the new Service in those classes? https://issues.redhat.com/browse/WFLY-16930 (Batch subsystem should maintain its own cache of services) could be issue for BatchConfigurationService, and JobOperatorService.

**Comment by ropalka** [comment]
Sure @chengfang , the difference between using org.jboss.msc.Service and org.jboss.msc.service.Service are the following:

Services implementing new API org.jboss.msc.service will throw UnsupportedOperationException when calling the following deprecated methods:
   - ServiceController.[getValue()](https://github.com/jboss-msc/jboss-msc/blob/1.5/src/main/java/org/jboss/msc/service/ServiceControllerImpl.java#L1067)
   - ServiceController.[awaitValue()](https://github.com/jboss-msc/jboss-msc/blob/1.5/src/main/java/org/jboss/msc/service/ServiceControllerImpl.java#L1075)
   - ServiceController.[awaitValue(long,TimeUnit)](https://github.com/jboss-msc/jboss-msc/blob/1.5/src/main/java/org/jboss/msc/service/ServiceControllerImpl.java#L1098)
   - ServiceController.[getService()](https://github.com/jboss-msc/jboss-msc/blob/1.5/src/main/java/org/jboss/msc/service/ServiceControllerImpl.java#L1131)

By implementing deprected org.jboss.msc.service.Service interface aforementioned deprecated methods backward compatibility is maintained.

I didn't refactor these services because my main purpose for this PR was fixing just dependencies declaration.

**Comment by ropalka** [comment]
These ServiceController methods were deprecated because they are exposing MSC runtime internals to API users.

**Review by chengfang — APPROVED** [review]
LGTM, thanks @ropalka !

**Comment by bstansberry** [comment]
Thanks @ropalka

**Pull request merged**
