### PR TITLE
[WFLY-4982] Upgrade Apache DS to latest milestone, which pulls a more…

### PR DESCRIPTION
**Pull request by asoldano**
… recent version of ehcache

### CODE REVIEW

**Comment by asoldano** [comment]
mmh... looks like some tests fail on Windows only because of files that can't be deleted..

**Comment by ctomc** [comment]
great! While you are on this subject, do you mind also removing all traces of maven-bundle-plugin from our root pom.xml 
as it is causing us some problems from time to time and was only there to handle ApacheDS's bundle dependency which is no longer needed / used with version you updated to.

**Comment by asoldano** [comment]
@ctomc I can have a look, yes. But first I need to make those failing tests pass on Windows, which is something I need to rely on TC for, as I don't have a Windows env ;-)

**Comment by ctomc** [comment]
If you are still stuck in the morning, ping me, I can take a look a it.

**Comment by asoldano** [comment]
ok, thanks. I have yet another change to try, will push it in few minutes and let it run during the night; let's see the results tomorrow morning...

**Comment by ctomc** [comment]
it worked :+1:

**Comment by asoldano** [comment]
Indeed :-D I've just rebased everything and also removed the plugin you mentioned. Last test run now, hopefully...

**Comment by asoldano** [comment]
Eureka

**Pull request merged**
