### PR TITLE
[WFLY-16008] use maven parameter with sso image

### PR DESCRIPTION
**Pull request by kstekovi**
https://issues.redhat.com/browse/WFLY-16008

- get maven parameter or use default value
- set image environment variables

### CODE REVIEW

**Comment by bstansberry** [comment]
@fjuma Please review.

@kstekovi Can you add WFLY-16008 to the commit message please? Thanks.

**Review by fjuma — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks, @kstekovi!

Before merging your first WildFly contribution we need to ask a question:

We require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to the these terms?

**Comment by kstekovi** [comment]
yes, I agree to MIT License.

**Comment by bstansberry** [comment]
Thanks, @kstekovi !

**Pull request merged**
