### PR TITLE
[WFLY-19214] Use the wildfly-maven-plugin for build, ee-build and pre…

### PR DESCRIPTION
**Pull request by bstansberry**
…view/build

https://issues.redhat.com/browse/WFLY-19214

Builds on #17805

____

<--- THIS SECTION IS AUTOMATICALLY GENERATED BY WILDFLY GITHUB BOT. ANY MANUAL CHANGES WILL BE LOST. --->

> Wildfly issue links:
> * [WFLY-19222](https://issues.redhat.com/browse/WFLY-19222)

<--- END OF WILDFLY GITHUB BOT REPORT --->

More information about the [wildfly-bot[bot]](https://github.com/wildfly/wildfly-github-bot)

### CODE REVIEW

**Comment by TomasHofman** [comment]
I was trying to test this last week and found a bug in the wildfly-maven-plugin - I'm not able to reference a local manifest file.

With `-Dexternal.wildfly.channels=file:manifest.yaml` the plugin handles the URL as a Maven G:A rather than a URL.

With `-Dexternal.wildfly.channels=file://manifest.yaml` the plugin tries to download the manifest via FTP handler.

I created https://github.com/wildfly/wildfly-maven-plugin/pull/517 which I think should fix this.

**Comment by TomasHofman** [comment]
Then I have one question, why is galleon configured to be in offline mode?

In my trial, I take a manifest generated from sources (from the  feature pack build), then I update one stream (cryptacular from 1.2.5 to 1.2.6) just for test. This I think demonstrates the typical usage - component update from outside. The build then fails with following:

```
[ERROR] Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:5.0.1.Final-SNAPSHOT:provision (server-provisioning) on project wildfly-build: Provisioning failed: Failed to process JBoss module XML template for feature-pack wildfly-ee@maven(org.jboss.universe:community-universe):current#32.0.0.Beta1-SNAPSHOT package org.opensaml: Failed to resolve artifact org.cryptacular:cryptacular:jar:1.2.5: Cannot access jboss-eap-8.0-product-repository (https://download.devel.redhat.com/brewroot/repos/jb-eap-8.0-maven-build/latest/maven/) in offline mode and the artifact org.cryptacular:cryptacular:jar:1.2.6 has not been downloaded from it before. -> [Help 1]
```

Disabling the offline mode I think resolves this.

**Comment by TomasHofman** [comment]
Otherwise it works for me - in the build modules the dep is updated, in the dist modules it is not :+1:

**Comment by yersan** [comment]
@TomasHofman I reproduced the same error you got by reusing the manifest file generated, but then I built from scratch a server bumped with a new version, so I got a new manifest with the new version generated in my local maven repo. Then I was able to switch the component versions of the latest server by using each of manifests as external manifest files.

Notice the weird error you got, you bumped to 1.2.6, but the error complains about 1.2.5:

`Failed to resolve artifact org.cryptacular:cryptacular:jar:1.2.5` so I beleive it is not just to modify the existing manifest and reuse it.

**Pull request merged**
