### PR TITLE
Fix for WFLY-12254, define galleon layers for h2 datasource

### PR DESCRIPTION
**Pull request by jfdenise**
Fix for https://issues.jboss.org/browse/WFLY-12254

- Removed h2-database layer
- Introduced new h2-driver, h2-database,h2-default-database layers
- Refactored existing feature-group
- Updated doc.

### CODE REVIEW

**Review by jamezp — APPROVED** [review]

**Comment by jfdenise** [comment]
@jamezp I am going to make changes. It can't be merged (related to https://github.com/wildfly/wildfly/pull/12417)

**Comment by jfdenise** [comment]
@jamezp , this one should be put on hold until https://github.com/wildfly/wildfly/pull/12417 is merged, I will then make changes to it.

**Comment by jfdenise** [comment]
@jamezp @bstansberry , I fixed the PR.

**Comment by jamezp** [comment]
retest this please

**Comment by jfdenise** [comment]
@jamezp @bstansberry , I need to re-think these h2 layers. They actually bring too much to the config we add them to. They should only bring the features they add. Bringing in transactions and ee can have side effect on the ee/transactions subsystems present in the configuration.

**Comment by jfdenise** [comment]
@jamezp  @bstansberry, I am fine now, very limited content brought by the layers...Sorry for the noise. JF

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
