### PR TITLE
[WFLY-16595] backport webservices changes replacing UsersRolesLoginMo…

### PR DESCRIPTION
**Pull request by rsearls**
…dule

https://issues.redhat.com/browse/WFLY-16595 backport webservices 
      (security) replacement changes for UsersRolesLoginModule

### CODE REVIEW

**Comment by rsearls** [comment]
Is there a reason this can't be merged?  We want to get jbossws-cxf-5.6.x CI working against wfly-26.
This fix is addition and subtractive.  I don't foresee it breaking anything existing.

**Comment by jimma** [comment]
This change also includes the :

- [WFLY-16481]:EndpointService throws NPE when publish ws endpint with EndpintPublisherImpl
- and part of  [WFLY-13889]:Remove unused class which depends on picketbox;Remove the picketbox class from EndpointService

Is it better to improve this PR with 3 commits ?   Two commits for these two backport changes and another commit for WFLY-16595 ?

**Review by jimma — CHANGES_REQUESTED** [review]
This change also includes the :
- [WFLY-16481]:EndpointService throws NPE when publish ws endpint with EndpintPublisherImpl

- and part of [WFLY-13889]:Remove unused class which depends on picketbox;Remove the picketbox class from EndpointService

Is it better to improve this PR with 3 commits ? Two commits for these two backport changes and another commit for WFLY-16595 ?

**Comment by bstansberry** [comment]
@rsearls @jimma Note the #15655 has the WFLY-16481 change, and I plan to merge that soon (assuming a final CI job #15918 completes ok). So rebasing on the #15655 branch, or on 26.x once that PR is merged, will handle the aspect of separating out the WFLY-16481 fix.

**Comment by bstansberry** [comment]
Thanks @rsearls!

**Pull request merged**
