### PR TITLE
Upgrade dom4j from 1.6.1 to 2.1.1

### PR DESCRIPTION
**Pull request by soul2zimate**
Do NOT merge, Just for CI result.

https://issues.jboss.org/browse/WFLY-11000

### CODE REVIEW

**Comment by wolfc** [comment]
@soul2zimate can you file the appropriate issue for this?

**Comment by soul2zimate** [comment]
I have created https://issues.jboss.org/browse/WFLY-11000

**Comment by kabir** [comment]
@soul2zimate Are we going ahead with this? If not, please close. If we are, can you squash the commits and add the Jira id to the message?

**Comment by soul2zimate** [comment]
Although the CI passed, I believe this needs more discussion. Close for the moment.

**Pull request closed without merging**
