### PR TITLE
WFLY-18098 Upgrade JGroups AWS to 3.0.0.Final; expand documentation.

### PR DESCRIPTION
**Pull request by rhusar**
Resolves
https://issues.redhat.com/browse/WFLY-18098

Resolves productization issues around "Project aws-sdk-java version 1 cannot be built with JDK 11 or 17".

### CODE REVIEW

**Review by pferraro — APPROVED** [review]
Looks good, but adding hold label pending internal validation.

**Comment by bstansberry** [comment]
@rhusar Needs a rebase.

**Comment by darranl** [comment]
@rhusar / @pferraro Are we still missing something to proceed on this one?  It is both approved and on hold.

**Comment by pferraro** [comment]
@darranl This is ready.

**Comment by bstansberry** [comment]
Thanks @rhusar and @pferraro

**Pull request merged**
