### PR TITLE
WFLY-12844 Upgrade Narayana to 5.10.1.Final

### PR DESCRIPTION
**Pull request by tomjenkinson**
Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [x] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue(s)
https://issues.jboss.org/browse/WFLY-12844
- [x] Pull Request contains description of the issue(s)
component upgrade to latest Narayana
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

### CODE REVIEW

**Comment by bstansberry** [comment]
@tomjenkinson I don't know if the IIOPTimeoutTestCase failure was relevant to this PR. I suspect not as the same failure happened back in October.

https://ci.wildfly.org/project.html?projectId=WF&buildTypeId=&tab=testDetails&testNameId=-2044053168040138175&order=TEST_STATUS_DESC&branch_WF=__all_branches__&itemsCount=50

But even if it's not relevant to this PR I thought it might be interesting to you as the related server logging has a bunch of stuff related to transaction handling that might be meaningful to you transactions guys.

**Comment by mmusgrov** [comment]
It is not obvious why the test failed but it seems unrelated to the upgrade.
The root cause is CosNaming.NamingContextPackage.NotFound when the test looks up the test bean (TestBeanHome.class, StatelessBean). I am guessing but could the remote WildFly server be down or uncontactable. I have made a note of the issue and will look out for it in future.

In summary I don't think this failure is sufficient to block the narayana upgrade.

**Comment by mmusgrov** [comment]
> I don't think that it is likely related to this upgrade given it happened before in October according to Brians information. However looking at the build I see that [this](https://github.com/wildfly/wildfly/blob/master/testsuite/integration/iiop/src/test/java/org/jboss/as/test/iiop/transaction/timeout/IIOPTimeoutTestCase.java#L134) is the part of the test that fails and that is not transactional itself but I do note that it is the second lookup in that class. @mmusgrov I think [this](https://ci.wildfly.org/repository/download/WF_PullRequest_LinuxJdk11/176876:id/testsuite/integration/iiop/target/jbossas-iiop-client/standalone/log/server.log) is the server log that contains an NPE in JTS, plus [this](https://ci.wildfly.org/viewLog.html?buildId=176876&tab=buildResultsDiv&buildTypeId=WF_PullRequest_LinuxJdk11#testNameId-2044053168040138175) is the test output which contains information that shows `StatelessBean.testTimeout` was called and it times out.
> 
> I also see a failure to enlist the XAResource ("enlistTestXAResource"). I would say we should create a WFLY to investigate making the test more resilient and possibly a JBTM for:
> 
> ```
> &amp#27;[0m&amp#27;[31m06:26:32,517 ERROR [stderr] (p: default-threadpool; w: Idle) java.lang.NullPointerException
> &amp#27;[0m&amp#27;[31m06:26:32,517 ERROR [stderr] (p: default-threadpool; w: Idle) 	at java.base/java.util.ArrayDeque.addFirst(ArrayDeque.java:287)
> &amp#27;[0m&amp#27;[31m06:26:32,518 ERROR [stderr] (p: default-threadpool; w: Idle) 	at java.base/java.util.ArrayDeque.push(ArrayDeque.java:580)
> &amp#27;[0m&amp#27;[31m06:26:32,518 ERROR [stderr] (p: default-threadpool; w: Idle) 	at org.jboss.jts@5.10.1.Final//com.arjuna.ats.internal.arjuna.thread.ThreadActionData.pushAction(ThreadActionData.java:85)
> ```
> 
> * wdyt @mmusgrov ?

@tomjenkinson That NPE means that one of the AtomicActions in the transaction hierarchy associated with the thread is null. There should be no code path where that could happen. So yes I agree we should investigate further.

**Review by bstansberry — APPROVED** [review]
Thanks @tomjenkinson and @mmusgrov. From the discussion it sounds like this shouldn't hold this upgrade up.

BTW the failure in October also had that NPE in the server log during the test execution. 
https://ci.wildfly.org/viewLog.html?buildId=171524&tab=buildResultsDiv&buildTypeId=WF_MasterIPv6

**Pull request merged**
