### PR TITLE
ExecutionContext has been deprecated and Immutable removed

### PR DESCRIPTION
**Pull request by rpelisse**
Upstream Issue: https://issues.jboss.org/browse/WFLY-9627
Issue: https://issues.jboss.org/browse/JBEAP-13801

### CODE REVIEW

**Comment by bstansberry** [comment]
The compile problem in the Linux - elytron test is likely a CI environment problem.

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
@msve or @mchoma is the change in the first file ok? This affects a test fixture I don't pretend to understand. :)

**Comment by rpelisse** [comment]
> @msve or @mchoma is the change in the first file ok? This affects a test fixture I don't pretend to understand. :)

Me too! I actually removed the fixture and run the full tests. As nothing broke, I thought I was safe enough to at least propose thru this PR.

I could find what we are supposed to use instead of ExecutionContext.HTTP_PROXY_HOST. My gut feeling is that now, this is somehow handle transparently by the framework, but I have yet to find a proof of this intuition...

**Comment by bstansberry** [comment]
If ExecutionContext.HTTP_PROXY_HOST still exists and this gets delayed in review more than a couple weeks and that's impacting some deadline, then splitting it up and just getting rid of Immutable in one PR will unblock the upgrade.

**Comment by mchoma** [comment]
I would say it could be safe to remove this, as far as we don't use http proxies in our SPNEGO tests. 

But I can imagine there could be a requirement to have a test with WildFly acting as http proxy, where it can be necessary.

JBossNegotiateScheme seems as fork of NegotiateScheme in particular time in past + some necessary tweaks. So this code can be just feature of NegotiateScheme we don't currently use.

Best long-term solution is to replace custom JBossNegotiateScheme implementation with SPNegoScheme.

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
