### PR TITLE
Fix NPE when delegate cache manager returns null

### PR DESCRIPTION
**Pull request by blaghed**
Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

### CODE REVIEW

**Comment by blaghed** [comment]
Simple NPE fix for a bug detected while using Wildfly 13.0.0.Final
This can be reproduced at runtime if you call "getCache" with "createIfAbsent" false, which will usually result in the delegate manager to return null, falling in the NPE when we then go to the "wrap" method.

**Comment by pferraro** [comment]
Needs a jira.

**Comment by bstansberry** [comment]
Thanks! We'll go with #11988 for this bug.

**Comment by blaghed** [comment]
> Thanks! We'll go with #11988 for this bug.

Great. Could it also be considered for version 13? I would like to avoid migrating to the JEE8 wildfly for now.

**Pull request closed without merging**
