### PR TITLE
[WFLY-16528] JSFDeploymentProcessorTestCase fails with Faces 4

### PR DESCRIPTION
**Pull request by jasondlee**
https://issues.redhat.com/browse/WFLY-16528

Re-enable test

### CODE REVIEW

**Comment by bstansberry** [comment]
@jasondlee This fails checkstyle.

**Comment by jasondlee** [comment]
> @jasondlee This fails checkstyle.

Strange. Not sure how that ran locally, but I've fixed. it. :)

**Comment by bstansberry** [comment]
@jasondlee It fails in the SE 17 job: https://ci.wildfly.org/viewLog.html?buildId=378286&tab=buildResultsDiv&buildTypeId=WF_PullRequest_LinuxJdk17&branch_WF_PullRequest=pull%2F16976

**Comment by jasondlee** [comment]
Seems unrelated?

> Caused by: org.jboss.shrinkwrap.resolver.api.InvalidConfigurationFileException: Found 175 problems while building POM model from /opt/buildAgent/work/e34a6f994de9f7c6/testsuite/integration/basic/pom.xml
> 1/ [ERROR] Non-resolvable import POM: Failed to resolve POM for org.wildfly.core:wildfly-core-parent:21.1.0.Beta1 due to Could not transfer artifact org.wildfly.core:wildfly-core-parent:pom:21.1.0.Beta1 from/to jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/): Error transferring file: Network is unreachable @ org.wildfly:wildfly-common-ee-dependency-management:29.0.0.Beta1-SNAPSHOT

Pretty sure that ran cleanly locally. I'll rerun it here as soon as I can to verify. May restart that job in the interim?

**Comment by darranl** [comment]
This is still failing on the JDK 17 job so removing this PR from Beta

**Comment by jasondlee** [comment]
> This is still failing on the JDK 17 job so removing this PR from Beta

Where is it failing? I see all green.

**Comment by darranl** [comment]
https://ci.wildfly.org/buildConfiguration/WF_PullRequest_LinuxJdk17/378989?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildTestsSection=true

**Comment by jasondlee** [comment]
@darranl That's odd. It's passing locally and here: https://ci.wildfly.org/buildConfiguration/WF_PullRequest_LinuxJdk17/378754?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
This passed on SE 17 three times straight, so I'll merge it. If it proves to be unstable we can re-disable for SE 17.

**Comment by bstansberry** [comment]
Thanks @jasondlee and @darranl

**Pull request merged**
