### PR TITLE
WFLY-17652 Upgrade to Hibernate Search 6.1.8.Final

### PR DESCRIPTION
**Pull request by yrodiere**
https://issues.redhat.com/browse/WFLY-17652

### CODE REVIEW

**Review by scottmarlow — APPROVED** [review]

**Comment by yrodiere** [comment]
I believe the test failure is unrelated (`org.jboss.as.test.clustering.cluster.modcluster.StartWorkersInSuspendedModeTestCase#testWorkerNodeIsRegisteredStopped`) and is just from a flaky test (it failed for JDK 17 but not JDK 11).

**Review by scottmarlow — APPROVED** [review]

**Comment by scottmarlow** [comment]
> I believe the test failure is unrelated (`org.jboss.as.test.clustering.cluster.modcluster.StartWorkersInSuspendedModeTestCase#testWorkerNodeIsRegisteredStopped`) and is just from a flaky test (it failed for JDK 17 but not JDK 11).

Agreed that the one test failure is unrelated:
```
Caused by: java.io.IOException: java.util.concurrent.CancellationException: JBTHR00004: Operation was cancelled
  at org.jboss.as.controller.client.impl.AbstractModelControllerClient.executeForResult(AbstractModelControllerClient.java:149)
  at org.jboss.as.controller.client.impl.AbstractModelControllerClient.execute(AbstractModelControllerClient.java:75)
  at org.jboss.as.controller.client.helpers.DelegatingModelControllerClient.execute(DelegatingModelControllerClient.java:69)
  at org.jboss.as.arquillian.container.CommonManagedDeployableContainer.stopInternal(CommonManagedDeployableContainer.java:212)
  ... 139 more
Caused by: java.util.concurrent.CancellationException: JBTHR00004: Operation was cancelled
  at org.jboss.threads.AsyncFutureTask.get(AsyncFutureTask.java:251)
  at org.jboss.as.controller.client.impl.AbstractDelegatingAsyncFuture.get(AbstractDelegatingAsyncFuture.java:57)
  at org.jboss.as.controller.client.impl.AbstractModelControllerClient.executeForResult(AbstractModelControllerClient.java:147)
```

**Comment by rhusar** [comment]
@scottmarlow @yrodiere Certainly unrelated (BTW briefly looked into this whether to open an issue and this is the only failure like this in the last 1000 runs so this seems environmental).

**Comment by bstansberry** [comment]
Thanks, @yrodiere, @scottmarlow and @rhusar!

**Pull request merged**
