### PR TITLE
[WFLY-13494] Narayana component upgrade for 5.10.5.Final

### PR DESCRIPTION
**Pull request by ochaloup**
https://issues.redhat.com/browse/WFLY-13494

/CC @mmusgrov @bstansberry @kabir

### CODE REVIEW

**Review by darranl — CHANGES_REQUESTED** [review]
Can you please provide release notes for this component upgrade and a link to a GitHub diff between the last release and this release.

It is not clear from the descriptions if this is just pulling in bug fixes or includes any RFEs.

**Comment by ochaloup** [comment]
@darranl 

The link to compare of the version 5.10.1.Final and 5.10.5.Final: https://github.com/jbosstm/narayana/compare/5.10.1.Final...5.10.5.Final
The release notes for 5.10.5.Final is here: https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12310200&version=12344559

The most of the changes are related to Narayana LRA module (https://github.com/eclipse/microprofile-lra) which is not integrated with WildFly and thus changes there has no impact to WildFly.

Narayana component upgrade contains only bug fixes in regard to Wildfly. There is no direct RFE, but one feature is added.
It's feature of context propagation support for the context propagation feature pack that @kabir works on. It's the issue https://issues.redhat.com/browse/JBTM-3246. This change in Narayana is a building block that will be used in the feature pack to process the async handling right later then.

**Comment by bstansberry** [comment]
@mmusgrov or @tomjenkinson OK with you?

**Review by mmusgrov — APPROVED** [review]
@bstansberry  I agree with Ondra's analysis. The upgrade brings:

* a new transaction log store (SlotStore) which is not used in WildFly (ie the WildFly user can still only configure the filesystem, artemis and JDBC stores).
* Ondra's CDI feature to manage context propagation (MP CP style).
* Narayana bug fixes
    25 LRA fixes (LRA features and bug fixes are not part of WildFly)
    11 Narayana quickstart fixes
    10 Miscellaneous fixes

**Pull request merged**
