### PR TITLE
Upgrade Apache HttpComponents to latest version.

### PR DESCRIPTION
**Pull request by langfr**

### CODE REVIEW

**Comment by ctomc** [comment]
wildfly core needs this as well.

**Comment by langfr** [comment]
Done. See https://github.com/wildfly/wildfly-core/pull/567.

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by langfr** [comment]
Seems we have to wait for 4.4.1.
See https://issues.apache.org/jira/browse/HTTPCLIENT-1610 respective https://issues.apache.org/jira/browse/HTTPCLIENT-1609.

**Comment by ctomc** [comment]
4.4.1 is out...

**Comment by langfr** [comment]
Retest this please

**Comment by ctomc** [comment]
still bug in httpclient :(

> java.lang.IllegalStateException: Unsupported cookie spec: default
>     at org.apache.http.cookie.CookieSpecRegistry.getCookieSpec(CookieSpecRegistry.java:110)
>     at org.apache.http.cookie.CookieSpecRegistry$1.create(CookieSpecRegistry.java:163)
>     at org.apache.http.client.protocol.RequestAddCookies.process(RequestAddCookies.java:156)
>     at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:132)
>     at org.apache.http.protocol.HttpRequestExecutor.preProcess(HttpRequestExecutor.java:166)
>     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:485)
>     at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
>     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
>     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
>     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
>     at org.jboss.as.test.integration.web.sso.SSOTestBase.checkAccessDenied(SSOTestBase.java:242)

**Comment by bstansberry** [comment]
This would need a rebase, but it looks pretty clear there will need to be testsuite changes of some sort too. My highly speculative guess is there is some change in cookie handling in the client. The tests that fail look to be session management related and those kinds of tests often use cookie manipulation in the client to simulate various call patterns (e.g. failover).

**Comment by rhusar** [comment]
This PR is superseeded by https://github.com/wildfly/wildfly/pull/7927. Thanks @langfr for bringing this up!

**Comment by stuartwdouglas** [comment]
https://github.com/wildfly/wildfly/pull/7927 upgrades these and fixes the related clustering failures

**Pull request closed without merging**
