### PR TITLE
Update Hibernate to 5.1.12.

### PR DESCRIPTION
**Pull request by langfr**
Update Hibernate from 5.1.10.Final to 5.1.11.Final.

Expectiing test failure with NPE using this new Hibernate version.
At least I got this locally.

### CODE REVIEW

**Comment by langfr** [comment]
Created https://hibernate.atlassian.net/browse/HHH-12233 and sent a PR to fix the issue.

**Comment by langfr** [comment]
Retest this please

**Comment by rsvoboda** [comment]
@wildfly please look at this

**Comment by rsvoboda** [comment]
@wildfly/core please look at this

**Comment by kabir** [comment]
@wildfly/core test

**Comment by rsvoboda** [comment]
@wildfly/mergers-full notification test

**Comment by istudens** [comment]
This is tracked by
https://issues.jboss.org/browse/WFLY-9886

**Comment by stuartwdouglas** [comment]
closing, as there are no plans for an 11.x release

**Pull request closed without merging**
