### PR TITLE
Fixing test failures with sec mgr enabled on JDK11 & JDK12

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.jboss.org/browse/WFLY-11790
https://issues.jboss.org/browse/WFLY-11791

### CODE REVIEW

**Comment by bstansberry** [comment]
[~ropalka] Is there a JDK bug here?  It seems strange that a call to javax.naming.spi.NamingManager.getURLContext() asking for the context for a scheme where the JDK provides the context factory would  fail with 'Permission check failed (permission"("java.lang.RuntimePermission" "accessClassInPackage.com.sun.jndi.url.rmi")"' . That's a pretty obscure permission to need to be able to invoke something the JVM provides.

Arguably the call to NamingManager.getURLContext() would be in a privileged block but that feels wrong too.

This PR is fine; these questions are more about whether this is a workaround or just what any app would have to do.

**Comment by ropalka** [comment]
Good question @bstansberry but I have no answer for you because I am not security expert.
Maybe @dmlloyd or @darranl (our security guys) might shed some light on it?

**Comment by ropalka** [comment]
@Darranl @dmlloyd stack traces are available in comments of WFLY-11790 & WFLY-11791

**Comment by dmlloyd** [comment]
I'm not sure; this would have to be researched.

**Pull request merged**
