### PR TITLE
First step in cleaning up god class code smell by refactoring one feature envy method

### PR DESCRIPTION
**Pull request by shirsub**
JIRA Issue: WFLY-6362 (https://issues.jboss.org/browse/WFLY-6362?filter=-2)
First step in cleaning up god class code smell by refactoring one feature envy method:
Refactored the class JBossServiceConfig in \sar\src\main\java\org\jboss\as\service\descriptor and added a parameterized constructor
Refactored the method parseMBean from the class JBossServiceXmlDescriptorParser to use the new parameterized constructor instead of calling multiple set attribute methods.

### CODE REVIEW

**Comment by ctomc** [comment]
most of change in this PR is reformatting of code, which makes this PR almost unreadable and hard to see what real change is

**Comment by shirsub** [comment]
How do I pass the check style test without making the extra reformatting changes?

The primary change is the parametized constructor defined in line 47 of the JBossServiceConfig class and it's call in line 233 of JBossServiceXmlDescriptorParser. The problem I'm running into is that when I import the formatter and code template files into eclipse, the other reformatting changes are added. If I skip this step the test suite check style fails.

**Comment by shirsub** [comment]
I updated the file to remove the extra reformatting so it is now easier to see the real change

**Comment by dmlloyd** [comment]
This pull request seems to exchange one complexity for an even worse complexity.  I don't think this is an improvement.

**Comment by dmlloyd** [comment]
I'm going to go ahead and close this one out, as it is not a productive or useful change.

**Pull request closed without merging**
