### PR TITLE
[WFLY-16168] Remove the Apache Xerces module dependency from the REST…

### PR DESCRIPTION
**Pull request by jamezp**
…Easy JAXB provider module, org.jboss.resteasy.resteasy-jaxb-provider.

https://issues.redhat.com/browse/WFLY-16168

### CODE REVIEW

**Comment by bstansberry** [comment]
@jamezp I put the 30.x label on this as it doesn't seem urgent enough to go in at the last minute.

**Comment by jamezp** [comment]
@bstansberry Agreed, this is too late for 29 for sure. I need to do some testing to ensure this works as expected. Tests do fail in RESTEasy itself with this, however I do think the tests are invalid. I'm going to rebase for a CI run to get a good view of any possible issues in WildFly.

**Comment by jamezp** [comment]
https://github.com/resteasy/resteasy/pull/3736 fixes the tests in RESTEasy when Xerces is not added to the jaxp-provider.

**Review by ropalka — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @jamezp and @ropalka

**Pull request merged**
