### PR TITLE
Modules Cleanup

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-17931
https://issues.redhat.com/browse/WFLY-17932
https://issues.redhat.com/browse/WFLY-17933
https://issues.redhat.com/browse/WFLY-17934
https://issues.redhat.com/browse/WFLY-17935

### CODE REVIEW

**Review by jamezp — APPROVED** [review]

**Review by jamezp — CHANGES_REQUESTED** [review]
The test failure seems related:
```
Caused by: javax.naming.NamingException: WFLYNAM0027: Failed instantiate InitialContextFactory com.sun.jndi.dns.DnsContextFactory from classloader ModuleClassLoader for Module "org.wildfly.clustering.service" version 29.0.0.Alpha1-SNAPSHOT from local module loader @528c868 (finder: local module finder @466276d8 (roots: /opt/server/modules,/opt/server/modules/system/layers/base)) [Root exception is java.lang.ClassNotFoundException: com.sun.jndi.dns.DnsContextFactory from [Module "org.wildfly.clustering.service" version 29.0.0.Alpha1-SNAPSHOT from local module loader @528c868 (finder: local module finder @466276d8 (roots: /opt/server/modules,/opt/server/modules/system/layers/base))]]
```

**Comment by bstansberry** [comment]
@ropalka Please break this up into 4 PRs. These changes introduce risk and there are different factors that affect our tolerance for the risk that apply differently to the different pieces.

1) The 4th and 5th commits (urn version and javax.xml.strea,.api). These are safe and are good to get in ASAP; these are the kind of refactoring / tidying commits we want to get into 29 Alpha, which hopefully will happen in the next couple weeks.

2) The sun.jdk commit. AFAIK we have no plans to remove this module any time soon, so this change is a purely internal one that should be considered separately with no need to try and get it done in the next week or two for 29 Alpha.

3) The javax.api commit. Same situation as sun.jdk, but should be reviewed separately as it impacts different components, whose leads should be involved. Also, perhaps you want to remove javax.api. If so we should clarify when that would be.

4) The javax.sql.api commit. Same situation as javax.api.

Also I've been chatting with @jamezp, @pferraro and @darranl about module ordering in general and what this PR does with that. That's a general topic sparked by this PR and is something we should discuss. That's something better done on the wildfly-dev list or in zulip though.

**Comment by pferraro** [comment]
> The test failure seems related:
> 
> ```
> Caused by: javax.naming.NamingException: WFLYNAM0027: Failed instantiate InitialContextFactory com.sun.jndi.dns.DnsContextFactory from classloader ModuleClassLoader for Module "org.wildfly.clustering.service" version 29.0.0.Alpha1-SNAPSHOT from local module loader @528c868 (finder: local module finder @466276d8 (roots: /opt/server/modules,/opt/server/modules/system/layers/base)) [Root exception is java.lang.ClassNotFoundException: com.sun.jndi.dns.DnsContextFactory from [Module "org.wildfly.clustering.service" version 29.0.0.Alpha1-SNAPSHOT from local module loader @528c868 (finder: local module finder @466276d8 (roots: /opt/server/modules,/opt/server/modules/system/layers/base))]]
> ```

I opened https://issues.redhat.com/browse/WFLY-17975 to properly address this.

**Comment by pferraro** [comment]
I submitted https://github.com/wildfly/wildfly/pull/16800 which should resolve the cloud test failure.

**Comment by ropalka** [comment]
This PR have been superseded by these 4 PRs:

https://github.com/wildfly/wildfly/pull/16803
https://github.com/wildfly/wildfly/pull/16802
https://github.com/wildfly/wildfly/pull/16805
https://github.com/wildfly/wildfly/pull/16804

**Pull request closed without merging**
