### PR TITLE
[WFLY-16327] Upgrade Apache Avro to 1.10.2

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFLY-16327

### CODE REVIEW

**Comment by boris-unckel** [comment]
@scottmarlow All links are in the Jira, including the alignment with upstream Hibernate. Could you review and approve, please?

**Review by yrodiere — APPROVED** [review]

**Review by scottmarlow — APPROVED** [review]

**Review by scottmarlow — APPROVED** [review]

**Comment by bstansberry** [comment]
@yrodiere Following the merge of #15185, std WildFly is on 1.11.0 in main. We could move the 1.11.0 version property to ee-9/pom.xml to have it only take effect in WFP, and then make this change in std WF. Simply adding ```<version.org.apache.avro>1.11.0</version.org.apache.avro>``` does is enough to get WFP using 1.11.0. Or, if 1.11.0 is fine with the current std WF we could just close this PR as out of date.

Either way #15501 is ok as main being 1.11.0 meets the upstream first requirement for moving 26.x to 1.10.2.

We'll be converting std WF to use the WFP dependency set sometime in the next month.

**Comment by yrodiere** [comment]
> Simply adding <version.org.apache.avro>1.11.0</version.org.apache.avro> is enough to get WFP using 1.11.0.

Note that I also had to make some changes to the Maven exclusions and the JBoss module itself in order to upgrade to Avro 1.11, so changing the version is not *just* about updating the Maven property: https://github.com/wildfly/wildfly/pull/15185/commits/96765275f022d77cc374adc5202e05315a4d8787 . The changes might also work with Avro 1.10, though; I don't know.

> Or, if 1.11.0 is fine with the current std WF we could just close this PR as out of date.

I don't know if it's fine; I didn't test that in Hibernate Search upstream, and it seems we don't have any tests involving Hibernate Search 5 + Avro in WildFly.

However, closing this PR would still be my preference.

I think the intent is to move to Hibernate ORM 6 + Search 6 in the next release of WF based off the main branch, right? If so, the problem (if any) will disappear as we remove Hibernate Search 5 from WildFly.

> Either way https://github.com/wildfly/wildfly/pull/15501 is ok as main being 1.11.0 meets the upstream first requirement for moving 26.x to 1.10.2.

Right, @boris-unckel 's work was necessary whatever we do with this PR: we needed the upgrade to Avro 1.10 in the 26.x branch.

**Pull request closed without merging**
