### PR TITLE
WFLY-16151: module clean-up

### PR DESCRIPTION
**Pull request by michpetrov**
Issue: [WFLY-16151](https://issues.redhat.com/browse/WFLY-16151)

### CODE REVIEW

**Comment by bstansberry** [comment]
@jasondlee Please review

**Comment by darranl** [comment]
@michpetrov Can you please rebase, this presently has a merge conflict.

**Comment by michpetrov** [comment]
rebased

**Review by jasondlee — APPROVED** [review]
This is probably fine. I think at some point we'll need to reintroduce this artifact, but as a module, as the semantic conventions jar is part of the API for OpenTelemetry, so if we're exposing that API to user applications, we should probably include that one as well.

**Review by bstansberry — APPROVED** [review]

**Comment by darranl** [comment]
I have added the ready to merge label as the only failures shown were known issues, CI is quite busy so not going to trigger them again.

**Pull request merged**
