### PR TITLE
[WFLY-14219] Fix ee-8-api...javax/ws/rs/api/main/module.xml for TCK test

### PR DESCRIPTION
**Pull request by boris-unckel**
Fix for https://issues.redhat.com/browse/WFLY-14219?focusedCommentId=15680282&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15680282

### CODE REVIEW

**Comment by scottmarlow** [comment]
Thanks @boris-unckel , I will try running the Jakarta EE 8 signature tests locally with https://github.com/boris-unckel/wildfly/tree/WFLY-14219_fix_jakarta_ee8_testdepth

**Review by scottmarlow — APPROVED** [review]

**Comment by scottmarlow** [comment]
Thanks @boris-unckel the Jakarta EE 8 signature tests passed for me locally with this change!

**Comment by boris-unckel** [comment]
@bstansberry 
This is the fix for an issue found by @scottmarlow with the Jakarta EE 8 TCK regarding the module descriptor. He also tested and approved the fix. Please review and merge.

**Comment by bstansberry** [comment]
Thanks @boris-unckel. I filed https://github.com/wildfly/wildfly/pull/13905 to make the same change in WildFly Preview.

That module.xml duplication is a bit of a maintenance hassle. But generally these spec API modules don't change much so hopefully it won't be a recurring hassle. :)

**Pull request merged**
