### PR TITLE
[WFLY-11868] Documentation for Rest integration with WildFly Elytron …

### PR DESCRIPTION
**Pull request by skyllarr**
https://issues.jboss.org/browse/WFLY-11868

This PR adds community documentation for [EAP7-1219](https://issues.jboss.org/browse/EAP7-1219)

Requires [RESTEASY-2366](https://issues.jboss.org/browse/RESTEASY-2366) and [ELY-1891](https://issues.jboss.org/browse/ELY-1891)

### CODE REVIEW

**Comment by darranl** [comment]
@Skyllarr Are we will missing the ReastEasy component upgrade before this can go in?

**Comment by Skyllarr** [comment]
> @Skyllarr Are we will missing the ReastEasy component upgrade before this can go in?

@darranl This requires RESTEasy 3.13.0.Final. Currently wildfly master is on version 3.12.1.Final. There is also this PR with tests: https://github.com/wildfly/wildfly/pull/13229 that should be merged before this one. Should I increase the version number in my tests PR?

**Comment by darranl** [comment]
@Skyllarr No you don't need to include the component upgrade yourself, once their component upgrade is in we can just run your PR through CI again as CI is performed after merging on top of the latest in master.

**Comment by fjuma** [comment]
Just FYI, this PR depends on https://github.com/wildfly/wildfly/pull/13518.

**Comment by bstansberry** [comment]
@fjuma @darranl Is this ok? This is just docs; the actual java code is in master now.

**Review by fjuma — APPROVED** [review]

**Review by darranl — APPROVED** [review]

**Pull request merged**
