### PR TITLE
WFLY-4714: Upgrade HAL to 2.7.0.Alpha1

### PR DESCRIPTION
**Pull request by hpehl**
https://issues.jboss.org/browse/WFLY-4714

### CODE REVIEW

**Comment by hpehl** [comment]
retest this please

**Comment by hpehl** [comment]
Need to fix none snapshot dependencies first.

**Comment by stuartwdouglas** [comment]
Oops, I just pushed this up without noticing that you had modified it in the meantime. Should I revert?

https://github.com/wildfly/wildfly/commit/6a7396429da34e880f67c466ce3e5b98c271e1bc

**Comment by hpehl** [comment]
No thanks, you don't need to revert. I'll need to fix some dependencies for an EAP DR release. But that shouldn't be a problem for WildFly.

I'll open another PR for WildFly 9 Final and WildFly 10 in the next days anyway.

**Pull request closed without merging**
