### PR TITLE
WFLY-8309 build.sh and integration-tests.sh scripts doesn't work on Solaris SPARC

### PR DESCRIPTION
**Pull request by rpelisse**
Issue: https://issues.jboss.org/browse/JBEAP-13246
Upstream Issue: https://issues.jboss.org/browse/WFLY-8309

### CODE REVIEW

**Comment by rpelisse** [comment]
@ctomc as I know you care about this kind of thing, would you mind approving (or not) this change ? :)

(then I'll nag Brian or somebody else to get it merged).

**Comment by kabir** [comment]
@ctomc @jamezp please approve

**Review by jamezp — CHANGES_REQUESTED** [review]
The JIRA issue in the commit message is the wrong issue number. It should be WFLY-8309.

**Comment by jamezp** [comment]
To be honest I didn't even realize these scripts still existed. I thought at least the `build.sh` was replaced by `mvnw`. Other than the commit message change I've got no issues with this change.

**Comment by kabir** [comment]
@rpelisse Please update the commit message as mentioned by James, then we can get this one merged

**Comment by rpelisse** [comment]
@kabir @jamezp fixed! Soirry the initial comment of James got somehow buried by the email thread, so I did not noticed it.

**Pull request merged**
