### PR TITLE
WFLY-500 - tests for Concurrency Utilities

### PR DESCRIPTION
**Pull request by hsvabek**
tests for Concurrency Utilities: add, remove, functional test
https://issues.jboss.org/browse/WFLY-500

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@emmartins isn't most of this runtime functionality already tested?

Also I don't really think that parameter validation based test should be run as part of our integration test suite, as this is the kind of thing that can be tested by unit tests (I don't think that this kind of test adds anything, unless some kind of special custom validator is in use).

**Comment by emmartins** [comment]
@stuartwdouglas we already test most important functionality at https://github.com/wildfly/wildfly/tree/master/testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/concurrent

Then these tests don't add much, EE Concurrency Utilities instances added through management are used to test functionality, instead of injecting and using the default instances as the tests I referenced above, but we already have there a test for management too...

**Comment by stuartwdouglas** [comment]
@hsvabek can you explain what extra functionality do these tests cover that is not covered by the existing tests, and why could the existing tests not be expanded instead of adding a whole new set of tests?

**Comment by hsvabek** [comment]
Hi @stuartwdouglas, 
EEConcurrencyUtilitiesFunctionTestCase contains functional tests for validating right function with NON-DEFAULT Concurrency utilities (number of threads, using context). 

EEConcurrencyUtilitiesManagementTestCase contains tests for creating and deleting Concurrency utilities with validating that values were set correctly (One colleague had problems with this – set own value and got the default value). Some tests are trying to set invalid properties. 

These tests are in new files because I wanted to split Default Concurrency utilities and these. I can refactor this if necessary

**Comment by stuartwdouglas** [comment]
With regard to testing invalid values I don't think we need tests for this (unless something is using a custom validator, but that does not seem to be the case here), this is core management functionality, if we decided to test this in our integration tests for every single resource our test suite would probably expand by an order of magnitude, and I don't think they would really add any value.

With regard to values not being set this is generally testing in subsystem tests, the subsystem XML that is tested should have all these resources and attributes defined, and if there are problems they will be picked up there. Once again we can't write integration tests for every attribute of every resource, it is simply to slow and should already be covered by the subsystem tests.

With regard to the functional tests I think some of these might be ok (in general it is better to expand existing test cases rather than add new ones, but in this case I am not sure if that is really appropriate). I don't think there is much point in testing things like different sized thread pools, basically if it works with the default number of threads it is reasonable to assume that it will work with any given number of threads.

Testing non-numeric difference is ok though (e.g. context service being set or not set), but in this case the test should actually test that the item behaves as expected with this difference, rather than just asserting that it can be added and used.

**Comment by hsvabek** [comment]
Hi @stuartwdouglas,
thanks for your answer and time. I understand. I close this PR.

**Pull request closed without merging**
