### PR TITLE
WFLY-3854 [JDK9+] move to latest javassist and some cleanup

### PR DESCRIPTION
**Pull request by ctomc**

### CODE REVIEW

**Comment by bstansberry** [comment]
@ctomc Please identify the components that use javaassist and @ ping their component leads asking for review/approval. Thanks.

**Comment by ctomc** [comment]
@scottmarlow can you sign off on this

**Comment by scottmarlow** [comment]
Hibernate ORM 5.3 will default to ByteBuddy, however, Hibernate ORM 5.1 still uses the older Javassist version.

**Comment by ctomc** [comment]
@scottmarlow when will hibernate orm 5.3 land in WildFly?

**Comment by scottmarlow** [comment]
@ctomc ORM 5.3 is not yet ready and some of that is out of our control at the moment.

**Comment by scottmarlow** [comment]
Also, we will still need the current javassist for Hibernate 5.1 in WF.  I see no reason why we couldn't have more than one version of Javassist, in WF.

**Comment by ctomc** [comment]
@scottmarlow is there any known issue with new version of Javassit? 
We can always rollback the component upgrade if issues are found later on.

**Comment by kabir** [comment]
@scottmarlow are you saying Javassist 3.22.0 will not work with Hibernate 5.1.x? Why is this different from another minor upgrade?

**Comment by kabir** [comment]
Retest this please

**Comment by scottmarlow** [comment]
we should at least run the Hibernate ORM 5.1 unit tests with the newer javassist version.  Perhaps someone has done this already but I will do it locally as well.

**Comment by scottmarlow** [comment]
@kabir I tried running the Hibernate 5.1.x unit tests with Javassist 3.22.0 and they pass, which is encouraging (not surprised since Sanne did the same testing before).  In the past, Javassist minor upgrades have included  changes that caused Hibernate regressions, which is one reason why the Hibernate ORM team is cautious about upgrades like this.

@gbadner @sebersole @Sanne any feedback on Javassist 3.22.0-GA being used with Hibernate ORM 5.1.x in WF12?  We would like to decide today.  Thanks!  If problems occur, we will either fix them or bring back Javassist 3.20.0-GA

**Comment by Sanne** [comment]
@scottmarlow aren't you the person maintaining Javassist?

I'll run the ORM 5.1 build with 3.22.0-GA once again, but it would be nice to also have a thourough changelist of Javassist.

**Comment by scottmarlow** [comment]
@Sanne I don't currently have time to learn the javassist internals.  Chiba does the releases and I help push them to maven central.  Is https://github.com/jboss-javassist/javassist/compare/3.20...master what your looking for?

**Comment by Sanne** [comment]
> I don't currently have time to learn the javassist internals

I didn't ask you to learn it? I asked if you were the person maintaining it, as I thought you were.

Anyway, I just run the ORM 5.1 and the Hibernate Search testsuite using 3.22.0-GA and found no issues.
Let's wait for the opinion of @gbadner @sebersole as well though.

IF they agree with the upgrade, I'd like to upgrade the ORM 5.1 branch as well. It's not good that WildFly uses a different set of dependencies than the set we regularly test for.

**Comment by rsvoboda** [comment]
It's FF today, shall we put it in? We still have 2 weeks till the final cut to pull it away.

**Comment by Sanne** [comment]
Agreed, let's merge it. I don't see any problem with it, if I stand corrected by Gail or Steve we'll revert but I think that's a very unlikely case.

**Comment by sebersole** [comment]
Since you already verified that it works.. fine with me

**Comment by gbadner** [comment]
Sorry for being late to the game on this. I'm going to run japi-compliance-checker on the two versions and see if any changes affect Hibernate.

**Comment by Sanne** [comment]
@gbadner Feel free to do that, but I'm not sure if that's useful? We already know that the APIs we use are compatible, as the project compiles when replacing the version.

**Comment by gbadner** [comment]
Ah, OK. I won't bother then.

**Pull request merged**
