### PR TITLE
[WFLY-15407] Convert "Hacking on WildFly" to the standard WF docs

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFLY-15407

The parent doc is Hacking_On_WildFly.adoc, the introduction for the reader is in the first document 
1)_hacking/github_setup.adoc
2) _hacking/contributing.adoc[]
3) _hacking/pullrequest_standards.adoc[]

The PR has a different order for the files. It would be great to receive both feedback regarding good English and fixes for markdown issues and/or best practise.

### CODE REVIEW

**Review by yersan — COMMENTED** [review]
Hello @boris-unckel I've added some comments.

I would also add this new documentation would deserve an entry on the main documentation file: https://github.com/wildfly/wildfly/blob/dc5a12c4d7bb515bdad24267fd9d87bf66a3de25/docs/src/main/asciidoc/index.adoc

At least under the "More Resources" section and maybe also on wildfly.org

**Review by yersan — COMMENTED** [review]
Changes look good to me, thanks @boris-unckel, I've just added some minor points I found when testing it

About if finally, we are going to link it on the index, let's wait from @bstansberry comment about it.

**Review by bstansberry — COMMENTED** [review]
Thanks so much @boris-unckel! I have feedback but the general content is very nice!

**Comment by bstansberry** [comment]
@boris-unckel 

+1 to adding to index.adoc

Re the README, good suggestion. There is no 'latest'. We could work out how to create such a thing, but I think that should be a separate task. And we wouldn't want to update the README until the doc it points to is published, which won't be for a while, as we publish docs with the major releases.

**Comment by boris-unckel** [comment]
@bstansberry I have added the link to the index.adoc. Ready to fly :-)

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
