### PR TITLE
[WFLY-6854] Upgrade to Hibernate ORM 5.1.2

### PR DESCRIPTION
**Pull request by langfr**
Replacement for https://github.com/wildfly/wildfly/pull/8984.

### CODE REVIEW

**Comment by scottmarlow** [comment]
Issue list for this pull request : https://issues.jboss.org/browse/WFLY-6854
https://issues.jboss.org/browse/EAP7-582
https://issues.jboss.org/browse/JBEAP-5678

https://github.com/wildfly/wildfly/pull/8984 also had some discussion for this change.

**Review by rhusar — CHANGES_REQUESTED** [review]
Missing jira in the commit message. Unnecessary formatting changes.

**Comment by scottmarlow** [comment]
Once we have a Hibernate ORM 5.1.3 release, this pull request should be updated to include 5.1.3.  We should also update Javassist to  3.20.0-GA, which Hibernate 5.1.x is using (as well as Jetty).

**Comment by scottmarlow** [comment]
Could this pull request be updated to use 5.1.3.Final?  5.1.3 isn't released yet but will be soon.  That way, we can ask for this pull request to be tested again after Hibernate ORM 5.3.1.Final is released.  Thanks Frank!

**Pull request closed without merging**
