### PR TITLE
[WFLY-14955] Use logger instead of syserr

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFLY-14955

### CODE REVIEW

**Review by rhusar — APPROVED** [review]
@jmesnil as the code author ideal for review. But I think this looks good.

**Comment by boris-unckel** [comment]
@jmesnil Could you please check? Is "ERROR" as log level correct?

**Review by jasondlee — APPROVED** [review]
These changes look good to me.

**Comment by boris-unckel** [comment]
Hello @bstansberry this PR is tested and approved. Could you check and merge, please?

**Pull request merged**
