### PR TITLE
WFLY-6599 JDBC_PING can't use a JNDI database connection because it is closed on shutdown

### PR DESCRIPTION
**Pull request by rhusar**
Jira
https://issues.jboss.org/browse/WFLY-6599

### CODE REVIEW

**Comment by rhusar** [comment]
retest this please

**Comment by pferraro** [comment]
This will need approval by someone from the JCA team.

**Comment by rhusar** [comment]
Hey @jesperpedersen could you have a look when you have a minute? Thanks!

**Comment by jesperpedersen** [comment]
looks ok

**Comment by rhusar** [comment]
retest this please

**Comment by rhusar** [comment]
Ok, if this is for 11.x I need to change the schema to version 5.

**Pull request merged**
