### PR TITLE
WFLY-9920/WFLY-9890 Fix timeouts following topology change

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-9920
https://issues.jboss.org/browse/WFLY-9890

Disable message bundler by default.

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by pferraro** [comment]
Not sure yet why this fails spectacularly on windows.  Closing for now.

**Pull request closed without merging**
