### PR TITLE
[WFLY-17616] Upgrade SmallRye Reactive Messaging to 4.4.0

### PR DESCRIPTION
**Pull request by kabir**
https://issues.redhat.com/browse/WFLY-17616

### CODE REVIEW

**Comment by bstansberry** [comment]
@kabir This has a conflict.

**Comment by kabir** [comment]
@bstansberry 4.4.0 was released in the meantime so I have bumped to that. It now pulls in a bunch of opentelemetry instrumentation jars - I'll double check on email

**Comment by kabir** [comment]
@bstansberry https://github.com/wildfly/wildfly/pull/16330 needs the mentioned opentracing instrumentation jars. I have reworked how I include them to be in line with how #16330 uses them.

CC @jasondlee

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
I put the 'hold' label on this while we validate whether the #16630 roll-back to OTel 1.20 breaks this.  #16633 combines the two in order to validate this.

**Pull request merged**
