### PR TITLE
[WFLY-16554] Increase JVM heap max-size to 100m for JVMServerPropertiesTestCase

### PR DESCRIPTION
**Pull request by gaol**
Issue: https://issues.redhat.com/browse/WFLY-16554

Thanks for submitting your Pull Request!

Please delete this text, and add a link to the Jira issue solved by this PR.

If this PR is not for the 'main' branch you must add a link to the equivalent change in 'main'.

Remember to use the Jira issue ID in the PR title and any commits.

### CODE REVIEW

**Comment by gaol** [comment]
@yersan would you please review? thanks

**Comment by gaol** [comment]
@yersan please on hold, I think we may also increase jvm heap max-size in [domain-standard.xml](https://github.com/wildfly/wildfly/blob/ec69e1cea3ad764159cb8a2456b9d918d8f6624c/testsuite/domain/src/test/resources/domain-configs/domain-standard.xml#L930) which is used in [CloneProfileTestCase](https://github.com/wildfly/wildfly/blob/main/testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/cli/CloneProfileTestCase.java), I can see `OOME` of [CLITestSuite](https://github.com/wildfly/wildfly/blob/main/testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/suites/CLITestSuite.java) in my container based CI. I think it may relate to this.

**Comment by gaol** [comment]
@yersan this is ready for review, thanks :)

**Review by yersan — APPROVED** [review]
Thanks @gaol , LGTM, I would suggest squashing both commits or at least add the Jira number to the second one

**Comment by darranl** [comment]
I have just triggered the three failed jobs, they don't look related.

**Comment by bstansberry** [comment]
Thanks @gaol

**Pull request merged**
