### PR TITLE
[WFLY-15268] Upgrade ByteBuddy to 1.1.15.

### PR DESCRIPTION
**Pull request by langfr**
https://issues.redhat.com/browse/WFLY-15268

### CODE REVIEW

**Comment by bstansberry** [comment]
@scottmarlow Please review

**Comment by scottmarlow** [comment]
@langfr is there a particular change that you think is needed in the 1.1.15 version?  Or is this upgrade to just use the latest?

WildFly aligns the ByteBuddy version to what Hibernate ORM tests with.  Hibernate ORM (main branch) is using [1.1.12](https://github.com/hibernate/hibernate-orm/blob/main/gradle/libraries.gradle#L27) and the same for the [Hibernate ORM 5.3 branch](https://github.com/hibernate/hibernate-orm/blob/5.3/gradle/libraries.gradle#L26).

**Comment by langfr** [comment]
This pull request was intended to upgrade to latest version, saw this in the latest "[wildfly-dev] Possible component upgrades report - Wildfly" mail.

**Comment by scottmarlow** [comment]
@langfr thanks for the help!  

My preference is to keep using the same exact version of ByteBuddy as [Hibernate ORM](github.com/hibernate/hibernate-orm/) is using.

**Pull request closed without merging**
