### PR TITLE
WFLY-9307 use EAP7.0 version string in mixed domain tests

### PR DESCRIPTION
**Pull request by luck3y**

### CODE REVIEW

**Comment by luck3y** [comment]
Note this needs the core-3.x change here: https://github.com/wildfly/wildfly-core/pull/2772

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Pull request merged**
