### PR TITLE
WFLY-6682: Hibernate 5.2.10.

### PR DESCRIPTION
**Pull request by langfr**

### CODE REVIEW

**Comment by scottmarlow** [comment]
Thanks Frank, it will be good to see the results of this.  5.1 might be a better release to merge into WildFly 11, as we need to keep compatibility with Hibernate applications that have deployed on WildFly 10, for a while (mostly, so we don't make changes that will go into product, that breaks compatibility).  For example, on the Hibernate-dev mailing list, some changes to thrown Hibernate exceptions were mentioned, that came about by the merge of hibernate-entitymanager into hibernate-core.  5.2 is looking to be a great Hibernate release, just not sure that WildFly is ready for it yet.  Whether I'm right or wrong about WildFly not being ready for 5.2, +100 for making this code change and getting the test results for this pull request! :)

**Comment by scottmarlow** [comment]
@gbadner fyi ^

**Comment by Sanne** [comment]
@langfr your patch looks great, but I would suggest closing it and waiting at least for `5.2.1.Final` so we can fix a couple of small issues with backwards compatibility which I just bumped into.

**Comment by bstansberry** [comment]
I put a 11.x label on this based on a June 23 comment in the JIRA from Emmanuel Bernard recommending that 5.1 be the default. This is mostly to make it easy to filter this PR out when looking for possible 10.1 changes.

**Comment by langfr** [comment]
Retest this please.

**Comment by langfr** [comment]
Retest this please.

**Comment by scottmarlow** [comment]
Frank, you could also try testing with Hibernate ORM 5.2.3-SNAPSHOT

**Comment by scottmarlow** [comment]
We are currently integrating with Hibernate ORM 5.1.x and have no immediate plans to integrate with ORM 5.2.x.  I'm fine with fixing this pull request so we can keep tabs on whether the latest ORM 5.2.x release passes the WildFly testsuite, however, we won't actually merge this change into WildFly 11.

**Comment by langfr** [comment]
Retest this please.

**Comment by heruan** [comment]
Great to know there's work for this! I'd like to report that [Using the latest Hibernate ORM within WildFly](https://docs.jboss.org/hibernate/orm/5.2/topical/html_single/wildfly/Wildfly.html) does not work with 11.0.0.Alpha1 (see [WFLY-6682](https://issues.jboss.org/browse/WFLY-6682)).

I don't know if this is a WildFly or Hibernate issue, but if version 11 won't include ORM 5.2 as its default JPA provider, I think it should be possibile to add it as an alternative like as in version 10.

**Comment by scottmarlow** [comment]
@langfr fyi https://issues.jboss.org/browse/WFLY-9053 reports a new failure with WildFly master + ORM 5.2

**Comment by kabir** [comment]
@langfr As this pull request has  been held up for a long time, I am closing it to get the pull request queue under control again. Since this is very old now, it will be a very long time until this one will be addressed. Also, I don't have much time to spend on this to evaluate on a case by case basis.

If this is something important to you or the project please feel free to recreate the pull request. That way it will come on top of the pile again, and be looked at again sooner. 

If it is a new **feature**, please follow the new process for features. Ping @kabir or @jamez if you are unsure what this means, and we can help. Please do that before opening the pull request though.

Sorry for any inconvenience!

**Comment by Sanne** [comment]
For people needing such an update, see also:
 - https://docs.jboss.org/hibernate/orm/5.2/topical/html_single/wildfly/Wildfly.html

**Pull request closed without merging**
