### PR TITLE
WFLY-9793 Upgrade Infinispan to 9.2.0.Final

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-9793

Adds new dependency on io.reactivex.rxjava2:rxjava.
Also includes refactoring of hibernate 2nd level cache modules

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by kabir** [comment]
@psakar @Skullman Incoming gradle dependency. The licenses look ok for an upstream project

**Comment by scottmarlow** [comment]
This change looks fine to me.   

@Sanne any feedback about the refactoring of hibernate 2nd level cache modules change?  At the very least, when we create the ORM 5.3 JipiJapa integration code (in the Hibernate repo), we will need similar changes.

**Comment by Sanne** [comment]
@kabir said:
 > @psakar @Skullman Incoming gradle dependency. The licenses look ok for an upstream project

There should be no new artifacts using gradle here? The 2nd level cache implementation of Infinispan was moved to the Infinispan repository, which is built using Maven.

**Comment by kabir** [comment]
@Sanne https://github.com/ReactiveX/RxJava/tree/v2.1.9 seems to be gradle?

**Comment by Sanne** [comment]
> @Sanne https://github.com/ReactiveX/RxJava/tree/v2.1.9 seems to be gradle?

ah right, sorry I thought you referred to the Hibernate artifacts. I missed the RxJava dependency, I stand corrected.

**Pull request merged**
