### PR TITLE
[WFLY-15269] Move WildFly Preview to a native jakarta namespace variant of the wildfly-weld-common, wildfly-weld-spi and wildfly-weld-transactions modules

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFLY-15269

Builds on #14646

### CODE REVIEW

**Comment by yersan** [comment]
WildFly Preview Jobs:

https://ci.wildfly.org/viewLog.html?buildId=277148&buildTypeId=WF_Ee9BootableJarLinuxJdk8
https://ci.wildfly.org/viewLog.html?buildId=277167&buildTypeId=WF_WildFlyPreviewLinuxJdk11
https://ci.wildfly.org/viewLog.html?buildId=277165&buildTypeId=WF_WildFlyPreviewLinuxJdk17

**Comment by bstansberry** [comment]
@manovotn FYI.

This sets up native jakarta namespace variants of 3 of the weld subsystem modules for use in WF Preview. It transforms the source so we have source jars and javadoc jars, and they can be deployed to maven, removing the need for Galleon to transform when it provisions a server.

I expect we'll do this for all the WF and WF Core modules that compile against EE 8 APIs, at least temporarily.

#14647 adds wildfly-weld-beanvalidation to the list.

**Review by manovotn — APPROVED** [review]

**Pull request merged**
