### PR TITLE
WFLY-17199 Replace hsqldb with h2 for Elytron OCSP test and drop hsqldb dependency

### PR DESCRIPTION
**Pull request by soul2zimate**
Issue: https://issues.redhat.com/browse/WFLY-17199

### CODE REVIEW

**Comment by bstansberry** [comment]
@fjuma Can this dependency be replaced with H2? Looking at org.xipki.datasource.DataSourceWrapper it looks like it can handle H2.

BTW @soul2zimate I'm not suggesting not merging this. But if we can drop a dependency we should follow up doing that.

**Comment by fjuma** [comment]
@bstansberry Yes, it does look like H2 could be used instead.

**Comment by soul2zimate** [comment]
Yes, you're correct. I have rebased to replace `hsqldb` with `h2` for Elytron OCSP test and drop `hsqldb` dependency. Thanks.

**Review by bstansberry — APPROVED** [review]
Excellent! Thanks @soul2zimate

**Pull request merged**
