### PR TITLE
WFLY-11000 Upgrade dom4j from 1.6.1 to 2.1.1

### PR DESCRIPTION
**Pull request by soul2zimate**
https://issues.jboss.org/browse/WFLY-11000 Upgrade dom4j from 1.6.1 to 2.1.1

### CODE REVIEW

**Comment by wolfc** [comment]
dom4j:dom4j must be added to the banned dependencies.

**Comment by soul2zimate** [comment]
IIUC, dom4j:dom4j is used in tests in compat testsuite. So I banned it for compile scope in pom.
@scottmarlow  @gbadner Could you please review this ?

**Comment by gbadner** [comment]
@soul2zimate, I tried out your PR and was able to build and run the compat tests that use dom4j successfully. I see that testsuite/compat/target/test-libs/dom4j.jar is 1.6.1.

I the checks failed. I'm not sure what that is about.

**Comment by soul2zimate** [comment]
I have added new org.dom4j:dom4j as test dependency to compat tests. They now passed with old dom4j:dom4j banned.

**Comment by scottmarlow** [comment]
Hibernate ORM 5.3.7.Final contains "HHH-12964 - Upgrade to dom4j 2.1.1", so that community Hibernate release is already using dom4j 2.1.1.  

However, what does it mean that [Jaxen 1.1.6](https://mvnrepository.com/artifact/jaxen/jaxen/1.1.6) has a compile only dependency on dom4j 1.1.6?  It looks like our WildFly org.jaxen module also depends on org.dom4j, as does the org.jboss.log4j.logmanager module.  

Do we need to also upgrade org.jaxen + org.jboss.log4j.logmanager modules to work with a newer versions that are compiled with dom4j 2.1.1?

**Comment by soul2zimate** [comment]
I think you meant WildFly org.jaxen module also depends on dom4j:dom4j (not org.dom4j)? 
I don't have an answer for it. But I don't see a Jaxen newer released version than 1.1.6 on both https://mvnrepository.com/artifact/jaxen/jaxen and https://repo.maven.apache.org/maven2/jaxen/jaxen/

In regard to logmanager, maybe @jamezp can shed some light on it?

**Comment by jamezp** [comment]
The `org.jboss.log4j.logmanager` I've filed an [issue](https://issues.jboss.org/browse/WFCORE-4198) to remove the dependency. My guess is it was added a long time ago when the really the `java.xml` module should be used.

**Comment by bstansberry** [comment]
Re: jaxen:

dom4j 2.1.1 itself depends on the jaxen version we ship, so that's an indication that the dom4j authors are not worried about incompatibility.

Jaxen's use of dom4j is in org.jaxen.dom4j.DocumentNavigator, which an IDEA usage search shows as not being WildFly, neither by the WF code itself or by our libraries. (I searched for DocumentNavigator.getInstance(), which is the only entry point to using the class.)

The jaxen module is private so we don't need to worry about end users using that class.

That's enough for me to say jaxen is not a concern, but here's some more info:

Here's how the jaxen module is used:

{code}
taozi:wildfly bstansberry$ git grep org.jaxen | grep module.xml
feature-pack/src/main/resources/modules/system/layers/base/nu/xom/main/module.xml:        <module name="org.jaxen"/>
feature-pack/src/main/resources/modules/system/layers/base/org/dom4j/main/module.xml:      <module name="org.jaxen"/>
feature-pack/src/main/resources/modules/system/layers/base/org/jaxen/main/module.xml:<module xmlns="urn:jboss:module:1.5" name="org.jaxen">
feature-pack/src/main/resources/modules/system/layers/base/org/jdom/main/module.xml:        <module name="org.jaxen"/>
taozi:wildfly bstansberry$ git grep org.jdom | grep module.xml
feature-pack/src/main/resources/modules/system/layers/base/org/jaxen/main/module.xml:        <module name="org.jdom"/>
feature-pack/src/main/resources/modules/system/layers/base/org/jdom/main/module.xml:<module xmlns="urn:jboss:module:1.5" name="org.jdom">
feature-pack/src/main/resources/modules/system/layers/base/org/jdom/main/module.xml:        <artifact name="${org.jdom:jdom}"/>
taozi:wildfly bstansberry$ git grep nu.xom | grep module.xml
feature-pack/src/main/resources/modules/system/layers/base/nu/xom/main/module.xml:<module xmlns="urn:jboss:module:1.5" name="nu.xom">
feature-pack/src/main/resources/modules/system/layers/base/org/jaxen/main/module.xml:        <module name="nu.xom"/>
{code}

So jaxen is used by org.dom4j, nu.xom and org.jdom.  The latter two are not used outside the same dependency graph.  The jboss.api for nu.xom and org.jaxen is 'private'. Unfortunately, org.jdom doesn't have any jboss.api setting, so users could be directly adding it as a deployment dependency. It looks like it got set to 'unsupported' way back in 2012 but then that was removed shortly after because 'unsupported' is not appropriate for community. I suspect it should have been 'private'. Unless I've missed something we should change it to 'private'.  It's 'unsupported' in EAP, so we are free to just make it 'private' there.  I suppose we could make it 'deprecated' in WF for a release and then 'private' but I don't see any point in that. The only thing these settings do is result in a log WARN if a deployment uses a module, and 'deprecated' vs 'private' only results in slightly different WARN text.

**Review by bstansberry — APPROVED** [review]

**Review by jamezp — APPROVED** [review]

**Comment by jamezp** [comment]
I think this is okay as well. I'm not sure whether or not we should mark the `org.dom4j` module as private or not. It's the number 1 conflict I see in questions when included in deployments on users are seeing `ClassCastException`'s.

**Pull request merged**
