### PR TITLE
[WFLY-7862] Outdated deployment-scanner xml snippet in deployments readme.txt

### PR DESCRIPTION
**Pull request by psakar**
issue https://issues.jboss.org/browse/WFLY-7862

### CODE REVIEW

**Review by jmesnil — COMMENTED** [review]
maybe the <deployment-scanner> snippet should be updated to follow the correct serialization order for attributes (path, relative-to, scan-interval, auto-deploy-zipped, auto-deploy-exploded)

**Review by bstansberry — CHANGES_REQUESTED** [review]
The correct fix for this is to remove this file entirely. WildFly Core's core-feature-pack provides this file and its variant is what we should use. Removing this file makes that happen.

Any suggested changes should be made to the WildFly Core file.

**Comment by bstansberry** [comment]
@jmesnil +1 re order. @ehsavoie can you fix that in core please? 

That should be a separate issue from this one, with no JBEAP needed. At this point this is driven by a JBEAP that would have already been fixed by a core change, except the presence of this duplicate file in servlet-feature-path is overriding the corrected file from core.

**Comment by ehsavoie** [comment]
ok, done in https://github.com/wildfly/wildfly-core/pull/2067

**Comment by psakar** [comment]
@bstansberry file deleted

**Pull request merged**
