### PR TITLE
Remove surefire timeouts so that stack traces can be obtained by TC

### PR DESCRIPTION
**Pull request by n1hility**

### CODE REVIEW

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by rhusar** [comment]
Looks like all these changes are already part of submitted https://github.com/wildfly/wildfly/pull/8622

**Comment by n1hility** [comment]
@rhusar thanks, yeah the extra stuff in #8622 causes regressions, this PR succeeds it

**Comment by rhusar** [comment]
Ah, ok. Well TBH I wondered whether removing the ${node0} stuff was correct, since it was in place to workaround a bug where those props would not be propagated.. well, looking at the failure it looks like that's the reason.

**Pull request merged**
