### PR TITLE
[WFLY-4672][WFLY-6212]  Adding integration testcases on transaction timeout

### PR DESCRIPTION
**Pull request by ochaloup**
Adding testcases for checking behavior of container during transaction timeout.

Idea to create these basic test cases came from GSS who communicates some troubles with users on JBoss EAP 6.x.

JIRA: https://issues.jboss.org/browse/WFLY-4672
JIRA: https://issues.jboss.org/browse/WFLY-6212

### CODE REVIEW

**Comment by ochaloup** [comment]
retest this please

**Comment by ochaloup** [comment]
retest this please

**Comment by ochaloup** [comment]
retest this please

_problem was in shutdown of client orb instance when following tests need to use it_

**Comment by ochaloup** [comment]
retest this please

**Comment by ochaloup** [comment]
retest this please

**Comment by ochaloup** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by ochaloup** [comment]
I'm closing this pull request as @tadamski prepared fix for the issues found by the tests. After wildfly#9112 and jbosstm/narayana#1044/ will be part of the WildFly distribution I will clean the tests and make a new PR

**Comment by tadamski** [comment]
After initial intermittent error was fixed another one (less probable :) ) appeared. There is also another fix https://github.com/jbosstm/narayana/pull/1049. After that I can see no errors.

**Comment by ochaloup** [comment]
@tadamski ok, nice. thank you for letting me know!

**Comment by ochaloup** [comment]
Tests can be added to testsuite when
https://github.com/wildfly/wildfly/pull/9112
is merged

**Pull request closed without merging**
