### PR TITLE
[WFLY-18047]:Remove legacy Xerces dependency from webservice modules

### PR DESCRIPTION
**Pull request by jimma**
https://issues.redhat.com/browse/WFLY-18047

### CODE REVIEW

**Review by asoldano — CHANGES_REQUESTED** [review]
@jimma you seem to need to remove an unused import of org.jboss.wsf.spi.deployment.Endpoint in the WSDependenciesProcessor.java

**Comment by jimma** [comment]
> @jimma you seem to need to remove an unused import of org.jboss.wsf.spi.deployment.Endpoint in the WSDependenciesProcessor.java

Ah,Yes. Fixed and pushed again.  Thanks @asoldano

**Review by asoldano — APPROVED** [review]

**Comment by jbliznak** [comment]
Could this test be allowed again after these fixes? https://github.com/wildfly/wildfly/blob/main/testsuite/integration/ws/src/test/java/org/jboss/as/test/integration/ws/wsrm/ReliableServiceTestCase.java#L49

**Comment by jimma** [comment]
Thanks for bring this up @jbliznak. Yes. That's the test I am going to have a look after all other tests are passed.

**Comment by bstansberry** [comment]
@jimma To fix the LayersTestCase failures you need to update org.jboss.as.test.shared.LayersTestBase.NOT_USED_COMMON.  This PR eliminates the last use of the org.apache.xerces module by any layer, so the test demands that we account for why the module still exists. The NOT_USED_COMMON array is where we do that. Basically the fix would be adding an element to the array preceded by an explanatory comment.

The reason the module still exists is because it is a public module. It was deprecated in WF 29, but it's still public.

We can/should discuss what we want to do with the module on wildfly-dev but I think doing anything about that is out of scope for the JIRA you're fixing here.

**Comment by jimma** [comment]
Done. Thanks @bstansberry

**Pull request merged**
