### PR TITLE
Revert "[WFLY-10655] SEVERE error on deploy of ear: "Unable to obtain…

### PR DESCRIPTION
**Pull request by rhusar**
… CDI 1.1 utilities for Mojarra""

Jira
https://issues.jboss.org/browse/WFLY-10739

Regression cased by: https://issues.jboss.org/browse/WFLY-10655

### CODE REVIEW

**Comment by treblereel** [comment]
@rhusar how did you find this regression ? which test fails ?

**Comment by rhusar** [comment]
@treblereel Caused regression blocking further testing in QE's @tommaso-borgato tests.

**Comment by rhusar** [comment]
@treblereel Better question is where is the test used to verify your fix? I don't see one.

**Comment by treblereel** [comment]
@rhusar there is a reproducer attached to the issue

**Comment by rhusar** [comment]
@treblereel Please check with @tommaso-borgato  who also reported the regression with the same reproducer.

**Comment by tommaso-borgato** [comment]
@treblereel I have a reproducer; attaching it here
[Reproducer.zip](https://github.com/wildfly/wildfly/files/2257022/Reproducer.zip)

**Pull request merged**
