### PR TITLE
WFLY-13653 Upgrade smallrye-health to 2.2.2

### PR DESCRIPTION
**Pull request by xstefank**
https://issues.redhat.com/browse/WFLY-13653

The implementation was rewritten to be fully reactive (based on Mutiny).

### CODE REVIEW

**Review by bstansberry — COMMENTED** [review]
@jmesnil Please review.

**Comment by jmesnil** [comment]
Diff to the previous integrated release: https://github.com/smallrye/smallrye-health/compare/2.2.0...2.2.2

**Comment by jmesnil** [comment]
Based on the diff, I see some changes that needs to be taken into consideration:
* this version of smallrye-health consumes `smallrye-config:1.8.1` and adds a dependency to `smallrye-common:1.0.2`
* the `smallrye-health`artifact depends on `smallrye-health-api` which adds a new dependency to `mutiny`
* new experimental features (async health check, wellness) have been introduced to smallrye-health.
* there is no change in the supported version of Eclipse MicroProfile Health.
* I have not see any critical bug fix or higher


@bstansberry I don't think that there is a need to bump this version of smallrye-health that would incorporate new dependencies as we will not expose the new experimental smallrye features in WildFly for the time being.
I suggest we bump `smallrye-health` when a new version of `microprofile-health` is released.

**Comment by xstefank** [comment]
fair enough. I really just wanted to test mutiny based impl against wildfly on all platforms. Closing.

**Pull request closed without merging**
