### PR TITLE
Test case for WFLY-4864

### PR DESCRIPTION
**Pull request by spyrkob**
Test failing when run with -Dsecurity.manager property. Depends on fix for WFLY-4864

### CODE REVIEW

**Comment by ctomc** [comment]
this is ok to test

**Comment by kwart** [comment]
This case was originally covered in secman testsuite module. I plan to re-introduce it with https://issues.jboss.org/browse/WFLY-4858 

The `secman` module will test permissions based on `permissions.xml` (or `jboss-permissions.xml`) deployment descriptor.

**Comment by ctomc** [comment]
mergers, don't merge this, I will include this commit together with a fix for the failing testsuite

**Comment by ctomc** [comment]
#7717 supersedes this PR by also fixing the failures

**Comment by bstansberry** [comment]
@spyrkob please have a look at #7717 and if the changes there are fine please close this one. Thanks.

**Pull request closed without merging**
