### PR TITLE
Fix for WFLY-15057, Reactivate SecurityCommands Test

### PR DESCRIPTION
**Pull request by jfdenise**
Fix for: https://issues.redhat.com/browse/WFLY-15057
* Reactivated and updated tests to cover new behavior and options.
* Update community doc.

### CODE REVIEW

**Comment by bstansberry** [comment]
@fjuma or @darranl  Please review

**Comment by darranl** [comment]
Just running CI again then we can see if we can merge

**Review by darranl — APPROVED** [review]

**Comment by lvxinzhi** [comment]
OPVDX001：standalone-full.xml 中的验证错误 --------------------------------------------
|
|  1: <?xml version="1.0" ?>
|  2: 
|  3: <server xmlns="urn:jboss:domain:19.0">
|     ^^^^ Unexpected element '{urn:jboss:domain:19.0}server'
|
|  4:     <extensions>
|  5:         <extension module="org.jboss.as.clustering.infinispan"/>
|  6:         <extension module="org.jboss.as.connector"/>
|
| 主要的底层错误消息为：
| > ParseError at [row,col]:[3,1]
| > Message: Unexpected element '{urn:jboss:domain:19.0}server'
|

**Comment by lvxinzhi** [comment]
2021-12-20 14:31:16,052 ERROR [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0055: Caught exception during boot: org.jboss.as.controller.persistence.ConfigurationPersistenceException: WFLYCTL0085: Failed to parse configuration
	at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:137)
	at org.jboss.as.server.ServerService.boot(ServerService.java:400)
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:417)
	at java.lang.Thread.run(Thread.java:748)

**Comment by lvxinzhi** [comment]
OPVDX001：standalone-full.xml 中的验证错误 --------------------------------------------
|
|  1: <?xml version="1.0" ?>
|  2: 
|  3: <server xmlns="urn:jboss:domain:19.0">
|     ^^^^ Unexpected element '{urn:jboss:domain:19.0}server'
|
|  4:     <extensions>
|  5:         <extension module="org.jboss.as.clustering.infinispan"/>
|  6:         <extension module="org.jboss.as.connector"/>
|
| 主要的底层错误消息为：
| > ParseError at [row,col]:[3,1]
| > Message: Unexpected element '{urn:jboss:domain:19.0}server'
|
|-------------------------------------------------------------------------------

2021-12-20 14:31:16,052 ERROR [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0055: Caught exception during boot: org.jboss.as.controller.persistence.ConfigurationPersistenceException: WFLYCTL0085: Failed to parse configuration
	at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:137)
	at org.jboss.as.server.ServerService.boot(ServerService.java:400)
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:417)
	at java.lang.Thread.run(Thread.java:748)

**Pull request merged**
