### PR TITLE
WFLY-13899 Fix wrong digester version

### PR DESCRIPTION
**Pull request by beikov**
https://issues.redhat.com/browse/WFLY-13899

### CODE REVIEW

**Comment by fjuma** [comment]
@beikov This one looks good. Please update the commit message to reference the WFLY JIRA issue (WFLY-13899). Thanks!

**Comment by beikov** [comment]
I updated the commit message @fjuma

**Review by fjuma — APPROVED** [review]
Thanks @beikov!

**Comment by bstansberry** [comment]
Hi @beikov,

Thanks for the patch! Before merging your first substantial patch, I need to ask a question:

We require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to the these terms?

**Comment by bstansberry** [comment]
BTW if I asked that elsewhere, I apologize. I thought I'd already asked here but don't see it so I fear I put the comment on some random other PR.

**Comment by beikov** [comment]
I agree to these terms, yes.

**Comment by bstansberry** [comment]
Thanks, @beikov!

**Pull request merged**
