### PR TITLE
[WFLY-13091] Upgrade HAL to 3.2.6.Final

### PR DESCRIPTION
**Pull request by hpehl**
https://issues.redhat.com/browse/WFLY-13091

### CODE REVIEW

**Comment by luck3y** [comment]
retest this please

**Comment by bstansberry** [comment]
@hpehl If this should be in WF 19, please file a separate PR against the 19.0.x branch. If not please change the Fix Version on the JIRA. Thanks!

**Review by bstansberry — APPROVED** [review]

**Comment by hpehl** [comment]
I'll file a separate PR against WF19 and changed the fix version in https://issues.redhat.com/browse/WFLY-13091

Please wait before merging this and the new PR. I'd like to include more domain related fixes and take a look at HAL-1663 which was reopened by @yersan. 

The PRs should be ready by Thursday 20th of February latest. Does that work for you?

**Comment by bstansberry** [comment]
Sure @hpehl That works.

**Comment by hpehl** [comment]
Accidentally rebased commits. Closing this and open a new PR

**Pull request closed without merging**
