### PR TITLE
[WFLY-10532] Disable tests in clustering.web

### PR DESCRIPTION
**Pull request by jmesnil**
These tests are frequently failing.

JIRA: https://issues.jboss.org/browse/WFLY-10532

### CODE REVIEW

**Comment by rhusar** [comment]
@jmesnil @luck3y Do we have a job setup to run with the flag to enable intermittent failures? I cannot find it.

**Comment by jmesnil** [comment]
@rhusar no, there's no special job for that you have to create a custom run with the `jboss.test.enableIntermittentFailingTests` system property

**Comment by rhusar** [comment]
@jmesnil That is not sufficient. We need a job that runs at a reasonable frequency to be able to still (a) obtain the data for investigation and (b) should the test start to fail consistently, find out what broke it.

**Comment by rhusar** [comment]
Please hold on merging this – I have a working theory what might be wrong with the tests.

**Pull request merged**
