### PR TITLE
WFLY-6791 Upgrade to Hibernate Search 5.5.4.Final

### PR DESCRIPTION
**Pull request by Sanne**
https://issues.jboss.org/browse/WFLY-6791

### CODE REVIEW

**Comment by Sanne** [comment]
Hi @scottmarlow I believe this needs your blessing.

It's fully backwards compatible, I'd suggest to include it in all active branches.

**Comment by scottmarlow** [comment]
@gbadner what do you think about this change?  I like the "Fully backwards compatible, yet has some nice performance improvements and a bugfix." :-)  I don't think that WildFly 10.1 is open for further changes at this point.  If I'm right, how about for WildFly 11.0?

**Comment by scottmarlow** [comment]
@Sanne looks good to me, lets see what feedback @gbadner has on this change as well.

**Comment by gbadner** [comment]
@Sanne, @scottmarlow this looks good to me.

**Pull request merged**
