### PR TITLE
WFLY-16797 Drop jakarta transformation of wildfly-microprofile-fault-tolerance-smallrye modules

### PR DESCRIPTION
**Pull request by rhusar**
Resolves
https://issues.redhat.com/browse/WFLY-16797

### CODE REVIEW

**Comment by rhusar** [comment]
Created Jira for the SingletonDeploymentDescriptorTestCase failure above https://issues.redhat.com/browse/WFLY-16845. That issue is still alive :-(

**Review by bstansberry — APPROVED** [review]
Thanks @rhusar Needs a rebase. Please ping me in chat when you do and it completes CI and I'll merge it.

**Comment by bstansberry** [comment]
Thanks @rhusar

**Pull request merged**
