### PR TITLE
WFLY-6336 request-limit should have its attributes as 'required'

### PR DESCRIPTION
**Pull request by ctomc**
https://issues.jboss.org/browse/WFLY-6336
https://github.com/jbossas/jboss-eap7/pull/404

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
This would need a subsystem micro model version bump as it currently stands, unless we decide to update the Undertow schema for 10.1

**Comment by ctomc** [comment]
@stuartwdouglas not micro, that is reserved for actual micro releases.
This could be merged if and after https://github.com/wildfly/wildfly/pull/8862 is merged that bumps model to 4.0

**Comment by ctomc** [comment]
retest this please

**Comment by ctomc** [comment]
model versions ware bumped for WF 11, so this can now go in.

**Pull request merged**
