### PR TITLE
[9.x] WFLY-4601 Upgrade Infinispan to 7.2.1.Final

### PR DESCRIPTION
**Pull request by pferraro**
Also updates hibernate-search to 5.2.0.Final.
Fixes some critical issues with:
- Deadlocking with state transfer on topology change
- Local TM fixes.

https://issues.jboss.org/browse/WFLY-4601

### CODE REVIEW

**Comment by scottmarlow** [comment]
Is ISPN-5443 going to be resolved before this is merged?

**Comment by pferraro** [comment]
The Infinispan team is cutting a 7.2.1 release tonight that fixes ISPN-5443.  I'll update this PR once it is available.

**Comment by Sanne** [comment]
I don't think you should apply those changes to the 'infinispan-directory-provider', why was that needed?

**Comment by pferraro** [comment]
infinispan-query has a source dependency on org.infinispan:infinispan-directory-provider, that's why that additional dependency is necessary.

**Comment by pferraro** [comment]
Unrelated failure - retest this please.

**Comment by Sanne** [comment]
> infinispan-query has a source dependency on org.infinispan:infinispan-directory-provider, that's why that additional dependency is necessary.

@gustavonalle can yo help me to double-check how to refactor the wildfly modules then. We should also make sure the two modules don't depend on each other, at most to have a test scoped dependency. We could avoid even that one, and move integration tests in an appropriate module?

**Comment by scottmarlow** [comment]
when the ORM 4.3.x branch (snapshot or release), is updated for Infinispan 7.2.1, ping me to run the tck, to pre-check this pr.

**Comment by bstansberry** [comment]
I added the Hold label as this needs a corresponding Hibernate update to prevent breaking the Hibernate 2LC clear() function.

**Comment by scottmarlow** [comment]
The Hibernate ORM 4.3.10-SNAPSHOT should be available now, I'll look to run the TCK later today (with the pferraro:9.x branch) after last nights TCK run completes.

**Comment by scottmarlow** [comment]
Hibernate 4.3.10.Final is expected to be released some time today.

**Comment by Sanne** [comment]
- http://in.relation.to/Bloggers/HibernateORM4310FinalReleased

**Comment by scottmarlow** [comment]
I forked this PR via https://github.com/wildfly/wildfly/pull/7478 but didn't create a master pr yet.

**Pull request merged**
