### PR TITLE
[WFCORE-1713]:  Migrate ModelControllerMBeanTestCase from wildfly test suite to core test suite.

### PR DESCRIPTION
**Pull request by ehsavoie**
Removing test duplicates.

Jira: https://issues.jboss.org/browse/WFCORE-1713

### CODE REVIEW

**Comment by bstansberry** [comment]
JIRA for Windows failure: https://issues.jboss.org/browse/WFCORE-1721

**Comment by bstansberry** [comment]
retest this please

**Comment by pferraro** [comment]
That last test failure is fixed by https://github.com/wildfly/wildfly/pull/9134

**Comment by kabir** [comment]
Retest this please

**Pull request merged**
