### PR TITLE
[WFLY-10353] anonymous authentication for ejbs using legacy configu…

### PR DESCRIPTION
**Pull request by JiriOndrusek**
…ration - test

Issue: https://issues.jboss.org/browse/WFLY-10353

Test for core issue: https://issues.jboss.org/browse/WFCORE-3826

Needs changes fromj core: https://github.com/wildfly/wildfly-core/pull/3282

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

### CODE REVIEW

**Comment by darranl** [comment]
@kabir I believe this fails CI as the corresponding changes are in core, I will kick off an experimental job to check.

**Comment by kabir** [comment]
Ah @darranl / @JiriOndrusek  I didn't see the mention of the needed core PR

**Comment by darranl** [comment]
https://ci.wildfly.org/viewLog.html?buildId=106218&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments

**Comment by JiriOndrusek** [comment]
Replaced with https://github.com/wildfly/wildfly/pull/11432

**Pull request closed without merging**
