### PR TITLE
Update fasterxml.jackson from 2.5.4 to 2.7.1

### PR DESCRIPTION
**Pull request by langfr**

### CODE REVIEW

**Comment by langfr** [comment]
retest this please

**Comment by langfr** [comment]
Resteasy has to updated to 3.0.14 or later for this.
See https://issues.jboss.org/browse/RESTEASY-1202.

**Comment by ctomc** [comment]
It was. Rebase this pr and it should work

**Comment by langfr** [comment]
retest this please

**Comment by langfr** [comment]
retest this please

**Comment by langfr** [comment]
retest this please

**Comment by langfr** [comment]
retest this please

**Comment by stuartwdouglas** [comment]
https://github.com/wildfly/wildfly/pull/8827 updates to 2.7.3 and also add support for jdk8 and jsr310 types

**Pull request closed without merging**
