### PR TITLE
[WFLY-10253] ConcurrentModificationException on startup

### PR DESCRIPTION
**Pull request by treblereel**
JIRA: https://issues.jboss.org/browse/WFLY-10253

@scottmarlow do you agree with this fix ?

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
I think this is probably a symptom of a different problem, deployers should not be iterating over lists that are in the process of being concurrently changed, as that may give inconsistent deployment results.

**Comment by kabir** [comment]
@treblereel Adding the hold label until @scottmarlow (or you) has had a chance to see if this can be solved as per Stuart's comments

**Comment by scottmarlow** [comment]
@stuartwdouglas regarding the different problem, if turns out to be the case, it might be better to only support packaging persistence providers in the top level deployment.  In most of the cases that I have seen so far, users have included the persistence provider in the top level deployment.

Also, @treblereel mentioned to me before that the real root issue is explained in Collections.synchronizedList javadoc that I missed originally: https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#synchronizedCollection(java.util.Collection):
```
public static <T> Collection<T> synchronizedCollection(Collection<T> c)

Returns a synchronized (thread-safe) collection backed by the specified collection. In order to guarantee serial access, it is critical that all access to the backing collection is accomplished through the returned collection.

It is imperative that the user manually synchronize on the returned collection when iterating over it:

  Collection c = Collections.synchronizedCollection(myCollection);
     ...
  synchronized (c) {
      Iterator i = c.iterator(); // Must be in the synchronized block
      while (i.hasNext())
         foo(i.next());
  }
 
```
So the workaround suggested by the pr seems fine for persistence providers that are deployed in the top level deployment.  Even for subdeployments, as long as there is just one persistence provider and other subdeployments persistence units that depend on that provider, have component dependencies on the persistence unit service, we might be okay.  Even still, we could deprecate persistence provider jars being in the subdeployment (e.g. log a deprecation warning if we see one and suggest moving to the top level deployment and in a later release, throw a deployment error).

**Comment by scottmarlow** [comment]
I approve this change, but lets see what else @stuartwdouglas has to say though, he may be seeing different problems than I am.

**Comment by stuartwdouglas** [comment]
The underlying issue is that this is stored in a top level deployment, and then it is both written to and read from in the same phase. 

This means that when reading it is not deterministic what sub deployments will see, as other sub deployments may or may not have added a provider to the list (i.e. it is racey). This could result in the same deployment not being deterministic in picking providers.

**Comment by scottmarlow** [comment]
Good point @stuartwdouglas, thanks!  Maybe we should switch to a simple ArrayList and synchronize reading/writing to the list.  Could probably establish the (top level deployment) ArrayList earlier in an earlier phase.  Could also be a Map<String providerClassName,PersistenceProvider>, instead a list.

**Comment by treblereel** [comment]
retest this please

**Comment by treblereel** [comment]
hmmm, nice, can't run tests because of "Canceled with comment: Build revision not found
"

**Comment by rhusar** [comment]
@treblereel This is a known issue https://issues.jboss.org/browse/WFCI-2.

**Pull request merged**
