### PR TITLE
[WFLY-18009] Add jars needed for compression of Kafka

### PR DESCRIPTION
**Pull request by kabir**
https://issues.redhat.com/browse/WFLY-18009

### CODE REVIEW

**Review by xstefank — APPROVED** [review]
LGTM, just a few year fixes and why do you need a logging dependency for the new modules?

**Comment by kabir** [comment]
@xstefank One of them used logging in the source code, but really it was just an old habit. I guess the log manager stuff we do on boot works anyway, and whatever was using logging was using JUL so perhaps it will work without.

What did you mean by 'year'? :-)

**Comment by kabir** [comment]
@xstefank it worked locally without the logging dependencies, so I have removed them

**Review by bstansberry — APPROVED** [review]

**Comment by kabir** [comment]
@bstansberry I fixed the compile error locally after a rebase. Should be fine now

**Comment by bstansberry** [comment]
Thanks @kabir and @xstefank

**Pull request merged**
