### PR TITLE
[WFLY-8767]Changing the max-pool-size of the datasource pool should i…

### PR DESCRIPTION
**Pull request by vkamble60**
possible fix for :

https://issues.jboss.org/browse/WFLY-8767

### CODE REVIEW

**Comment by bstansberry** [comment]
this is ok to test

**Comment by gaol** [comment]
@vkamble60 I investigated it a bit and I think the `pool-fair` should be flagged as `reload-required` as well, `min-pool-size` is not necessary though,  please take a look at: https://github.com/ironjacamar/ironjacamar/blob/1.4/core/src/main/java/org/jboss/jca/core/connectionmanager/pool/AbstractPool.java#L157, the Semaphore instance is created with the `fairness` parameter, once it is updated in WildFly CLI, it won't take affect without re-creating the instance.
@maeste  WDYT?

**Comment by vkamble60** [comment]
@gaol | Thank you. 

I guess `min-pool-size` too requires reload.
Scenario : When `pool-prefill` set to true, `ActiveCount` must be same as min-pool-size. However if we change value of min-pool-size without server reload it does not reflect ActiveCount. 

I am not sure about `pool-fair` should be flagged as reload-required. If requires I will modify this pull  request.

**Comment by maeste** [comment]
@gaol I agree w/ @vkamble60

**Comment by gaol** [comment]
Right,makes sense! I am ok with this pr now!

**Comment by kabir** [comment]
@vkamble60 @maeste Closing due to inactivity. Feel free to reopen, or create a new one once fixed

**Pull request closed without merging**
