### PR TITLE
[WFLY-12786] Upgrade RESTEasy to 3.9.1.Final

### PR DESCRIPTION
**Pull request by asoldano**
https://issues.jboss.org/browse/WFLY-12786

### CODE REVIEW

**Comment by asoldano** [comment]
retest this please

**Comment by bstansberry** [comment]
@asoldano This PR affects Hibernate, Hibernate Validator, Infinispan and Narayana RTS:

https://paste.fedoraproject.org/paste/QZgF-8azMi3ylcj~XGxkEA

**Comment by bstansberry** [comment]
@scottmarlow @gsmet @tomjenkinson FYI in case you have concerns about the upgrades here.

**Comment by gsmet** [comment]
Right. Please don't merge that right away because even master of HV is using classmate 1.3 and not 1.4. I need to check that the tests are running fine with 1.4. I'll get back to you ASAP.

**Comment by gsmet** [comment]
@Sanne this might be of some interest to you for the ORM side.

**Comment by scottmarlow** [comment]
[Did we switch to be able to use the pluggable TypeResolver cache, like ConcurrentTypeCache?](https://github.com/FasterXML/java-classmate/commit/df395934cb58c6c5a766aa53eb661f654e70a920)

**Comment by Sanne** [comment]
Is the classmate upgrade necessary? Hibernate ORM is also using the older version.

**Comment by Sanne** [comment]
Seems like 1.4.0 is not that recent; latest is 1.5.1 : is there a reason why we're not going directly for the `1.5x` series ?

**Comment by gsmet** [comment]
I ran the HV test suite with Classmate 1.4.0 and 1.5.1 and it worked fine. What I haven't tested though is the binary compatibility i.e. testing HV compiled with Classmate 1.3 and have it run with 1.4/1.5.

There is at least one HV test in the WildFly test suite, it should cover that.

**Comment by Sanne** [comment]
ORM test is fine, I upgraded master. But like Guillaume, I also haven't tested binary compatibility.

@gbadner I flagged https://hibernate.atlassian.net/browse/HHH-13730 to be considered for backport.
It seems to work without needing any changes, but it would be safest for you to do a 5.3 release.
 - https://github.com/hibernate/hibernate-orm/pull/3098

Also please let me know why not upgrade to classmate 1.5.1 ?
I'll do that for ORM / master : https://hibernate.atlassian.net/browse/HHH-13731

**Comment by mmusgrov** [comment]
The wildfly RTS module is fine too. I upgraded the versions of the Narayana RTS dependencies (in the Narayana repo) and retested against this PR - both the narayana RTS tests and the wildfly RTS tests pass.

**Comment by asoldano** [comment]
Thanks for all the checks.
@Sanne , I'm finishing testing RESTEasy with classmate 1.5.1, so far no problems. I'll update the PR here as soon as I'm done and ping you.

**Comment by asoldano** [comment]
@Sanne , RESTEasy is OK with classmate 1.5.1, updating this PR.

**Comment by Sanne** [comment]
thanks @asoldano . Is everyone else fine with classmate 1.5.1 as well?

**Comment by scottmarlow** [comment]
We should also verify that the Hibernate ORM 5.3 branch testsuite passes with classmate 1.5.1.  @gbadner did you try that?

**Comment by scottmarlow** [comment]
I tried running the testsuite for ORM 5.3 branch locally with classmate 1.5.1, I did get 3 failures but probably not classmate induced failures:
```
org.hibernate.test.locking.warning.LockNoneWarmingTest > testQuerySetLockModeNONEDoNotLogAWarnMessageWhenTheDialectUseFollowOnLockingIsTrue FAILED
    java.net.ConnectException

org.hibernate.test.criteria.CriteriaLockingTest > testSetLockModeDifferentFromNONELogAWarnMessageWhenTheDialectUseFollowOnLockingIsTrue FAILED
    java.net.ConnectException

org.hibernate.test.criteria.CriteriaLockingTest > testSetLockModeNONEDoNotLogAWarnMessageWhenTheDialectUseFollowOnLockingIsTrue FAILED
    java.net.ConnectException

9637 tests completed, 3 failed, 1288 skipped
```

**Comment by gbadner** [comment]
I just ran the 5.3 tests locally with classmate 1.5.1 and I'm not seeing any failures.

**Comment by bstansberry** [comment]
Superceded by #12818

**Pull request closed without merging**
