### PR TITLE
[WFLY-6199] Fix NPE in HTTPUpgradeService

### PR DESCRIPTION
**Pull request by jmesnil**
Check if ActiveMQ remotingService is started before transferring the
channel to its acceptor.
The remotingService may be stopped (and the acceptor null) if ActiveMQ
is shutdown while the client performs an HTTP upgrade handshake.

JIRA: https://issues.jboss.org/browse/WFLY-6199

### CODE REVIEW

**Comment by jmesnil** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
@n1hility Could you merge this PR please? (it already went to eap7)

**Pull request merged**
