### PR TITLE
[WFLY-4335] ArquillianService incorrectly sets TCCL

### PR DESCRIPTION
**Pull request by tdiesler**
https://issues.jboss.org/browse/WFLY-4335

### CODE REVIEW

**Comment by ctomc** [comment]
home of wildfly arquillian container is now at https://github.com/wildfly/wildfly-arquillian we don't maintain 8.x stuff anymore.

**Comment by tdiesler** [comment]
In case there is another 8.2 release, I'd need this in.

**Comment by ctomc** [comment]
test failures are result of this change ^^

**Comment by stuartwdouglas** [comment]
The current behaviour is correct, and relied upon by our test suite.

**Pull request closed without merging**
