### PR TITLE
[26.x][WFLY-16849] Upgrade JGroups to 4.2.21.Final

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFLY-16849

Upstream https://github.com/wildfly/wildfly/pull/15424

### CODE REVIEW

**Comment by boris-unckel** [comment]
Please find all links to release notes, git tags, github-diff in the Jira.

**Comment by rhusar** [comment]
@boris-unckel This is fine now - but going forward - when back-porting from upstream use `git cherry-pick` instead of creating new commits.

**Comment by boris-unckel** [comment]
@rhusar Sorry, my fault, it works here. I'll check for all future cases.

**Review by rhusar — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @boris-unckel

**Pull request merged**
