### PR TITLE
WFLY-6538 https-listener should allow proxy-address-forwarding and ce…

### PR DESCRIPTION
**Pull request by ctomc**
…rtificate-forwarding

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
This now need a schema bump + transformers etc

**Comment by ctomc** [comment]
@stuartwdouglas no it doesn't, schema bump (to 3.1) was already done on master (for 10.x) 
Transformers with tests cannot be be done yet as we don't have test framework in place to test legacy EAP7.0 controller.
This is being worked on for wildfly core 3.

If this doesn't go to 10.x, than schema bump will be needed.

**Comment by ctomc** [comment]
3.1 schema was introduced in fddcb310dd99526b562bc13b2a002b97d047e9ae which was after 10.0.0.Final tag, and is for now still "latest"

**Comment by stuartwdouglas** [comment]
It needs to be bumped to 4.0, 3.1 was the EAP7 schema.

**Comment by ctomc** [comment]
@stuartwdouglas you are right, that is not good at all. it messes with way to many things.
4.0 should for next major, so 3.2 could be used here, but I am not sure how would that affect eap 7.0.x.
it would be fine if we won't backport anything related to schema / model but it is too early block that.

**Comment by ctomc** [comment]
Maybe it would be just better if we would defer this for 11 and use 4.0 model.

**Comment by stuartwdouglas** [comment]
4.0 is fine

**Comment by ctomc** [comment]
updated to use 4.0 schema & model.

**Comment by ctomc** [comment]
@stuartwdouglas @bstansberry given this now has 11.x tag, is there any reason for that?
Current model version bump is meant for 10.1 for 11 we need different version.

**Comment by ctomc** [comment]
PR was updated to use 4.0 model that was introduced by elytron changes.

**Comment by kabir** [comment]
@ctomc I don't see any transformers or tests for those? I think they are needed?

**Comment by ctomc** [comment]
@kabir yes it would need transformers. I am preparing a separate PR that will focus just on transformers in undertow subsystems as there are also other changes(also already merged) beyond this one that needs it.

**Pull request merged**
