### PR TITLE
[WFLY-6223] compare with resolved current value.

### PR DESCRIPTION
**Pull request by soul2zimate**
https://issues.jboss.org/browse/WFLY-6223

it should compare resolved current value with a resolved new value to determine whether attribute value is really changed.

### CODE REVIEW

**Comment by soul2zimate** [comment]
retest this please

**Comment by soul2zimate** [comment]
retest this please

**Comment by soul2zimate** [comment]
retest this please

**Comment by soul2zimate** [comment]
retest this please

**Comment by stuartwdouglas** [comment]
Retest this please

**Pull request merged**
