### PR TITLE
WFLY-4218 Fix EJB3 Compiler Warnings

### PR DESCRIPTION
**Pull request by marschall**
The EJB3 subsystem contains quite a few compiler warnings that are easy
to fix (raw types, unused imports, unused variables, deprecated code).

Issue: WFLY-4218
https://issues.jboss.org/browse/WFLY-4218

### CODE REVIEW

**Comment by marschall** [comment]
Is there a way to get more information about the failure?

**Comment by stuartwdouglas** [comment]
[18:42:05][org.wildfly:wildfly-ejb3] /opt/buildAgent/work/340a2b56aab3b1db/ejb3/src/main/java/org/jboss/as/ejb3/component/messagedriven/MessageDrivenComponent.java:30:8: Unused import - javax.resource.spi.ResourceAdapter.
[18:42:05][org.wildfly:wildfly-ejb3] Audit done.
[18:42:05][org.wildfly:wildfly-ejb3] 
[18:42:05][org.wildfly:wildfly-ejb3] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.12.1:checkstyle (check-style) on project wildfly-ejb3: An error has occurred in Checkstyle report generation.

**Comment by stuartwdouglas** [comment]
MessageDrivenComponent.java has an unused import

**Comment by bstansberry** [comment]
Superceded by #7154 (the rebase.) Thanks!

**Pull request closed without merging**
