### PR TITLE
Hardcode licenses for artifacts hardcoded in module.xml in addendum.html

### PR DESCRIPTION
**Pull request by kabir**
https://issues.jboss.org/browse/WFLY-10403
https://issues.jboss.org/browse/WFLY-10402

### CODE REVIEW

**Comment by Sanne** [comment]
@kabir I expected you'd edit my commit to add the JIRA reference?

**Comment by kabir** [comment]
@Sanne yeah it got lost during rebasing onto your fix

**Comment by kabir** [comment]
@Sanne Ignore the ws failures, they are known and due to an expired certificate. However, without checking too carefully, I'd hazard a guess and say that introducing the hibernate-jpa-2.1-api as a dependency pollutes the classpath used for testsuite/integration/basic, causing the compile errors. Perhaps it is better to remove this commit anyway, and for me to hardcode that license too

**Comment by Sanne** [comment]
oh, ok. I thought this pom was only used to define the feature pack?

Sorry not familiar with the WF build, in my other projects we strictly refrain from defining libraries "globally".

**Pull request merged**
