### PR TITLE
[WFLY-8832] Introduce srcdeps

### PR DESCRIPTION
**Pull request by ppalaga**
https://issues.jboss.org/browse/WFLY-8832

See http://lists.jboss.org/pipermail/wildfly-dev/2017-January/005718.html and related https://github.com/wildfly/wildfly-core/pull/2122

### CODE REVIEW

**Comment by ppalaga** [comment]
@kabir @bstansberry is there something missing in this PR? Otherwise, could it please be merged?

**Comment by ppalaga** [comment]
@kabir @bstansberry could this please be merged? Me and other team members would like to start using srcdeps in their PRs.

**Comment by ppalaga** [comment]
fb95e3b upgrades to the latest srcdeps version

**Comment by stuartwdouglas** [comment]
It looks like agreement on how this should be handled has not been reached, and with the process this is a big enough change that it should go through the wildfly-proposals process. I am closing this for now until agreement has been reached on how it should go forward.

**Pull request closed without merging**
