### PR TITLE
[WFLY-15004] Use Arquillian 1.7.0.Alpha10 and the WildFly Arquillian …

### PR DESCRIPTION
**Pull request by jamezp**
…Adapter 5.0.0.Alpha1 for testing with WildFly Preview.

https://issues.redhat.com/browse/WFLY-15004

### CODE REVIEW

**Comment by jamezp** [comment]
Jakarta EE 9 Preview Run: https://ci.wildfly.org/buildConfiguration/WF_WildflyPreviewNightly/263275

**Comment by bstansberry** [comment]
@jamezp The CI failures on this are relevant to the PR.

**Comment by jamezp** [comment]
Interesting. It's defined in the parent pom. I'll do some checking.

**Comment by jamezp** [comment]
Should be fixed now. AT least RTS and XTS now pass locally :) Sorry about that. I was sure I check that.

**Comment by jamezp** [comment]
Another preview run: https://ci.wildfly.org/buildConfiguration/WF_WildflyPreviewNightly/268516

**Comment by bstansberry** [comment]
@jamezp Needs a rebase.

**Comment by darranl** [comment]
@jamezp Are these versions still correct or in this time do we have later versions?

**Comment by jamezp** [comment]
@darranl There is a 5.0.0.Alpha2 of WildFly Arquillian, but it only contains https://issues.redhat.com/browse/WFARQ-99. We could upgrade to it in the PR though.

**Review by darranl — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks, @jamezp

**Pull request merged**
