### PR TITLE
WFLY-15607 Remove the Hibernate ORM 5.1 => 5.3 bytecode transformer

### PR DESCRIPTION
**Pull request by scottmarlow**
https://issues.redhat.com/browse/WFLY-15607

Signed-off-by: Scott Marlow <smarlow@redhat.com>

### CODE REVIEW

**Comment by darranl** [comment]
@scottmarlow FYI we have a merge conflict on this one.

**Comment by scottmarlow** [comment]
Synced with latest WildFly `main` and removed conflicts.

**Comment by bstansberry** [comment]
@scottmarlow if you rebase this and ping me when CI is done, I'll merge it then.

**Review by bstansberry — APPROVED** [review]

**Comment by scottmarlow** [comment]
@bstansberry I assume the (Linux with security manager - JDK 8) clustering failure (https://ci.wildfly.org/viewLog.html?buildId=291801&buildTypeId=WF_PullRequest_LinuxSm shows SingletonDeploymentJBossAllTestCase.test failing)  is unrelated.  

I'm not sure of the cause of WildFly Preview - Linux JDK17 failures (https://ci.wildfly.org/viewLog.html?buildId=291808&buildTypeId=WF_PullRequest_WildFlyPreviewLinuxJdk17) but they don't look to be caused by removal of the Hibernate ORM 5.1 => 5.3 compatibility transformer.

**Comment by bstansberry** [comment]
@scottmarlow I went ahead and re-ran the WF Preview job. I don't expect the failures are relevant but with over 1,000 failures the result is basically meaningless so I re-ran it.  I'm not concerned about the 1 Linux SM job failure.

**Comment by scottmarlow** [comment]
Thanks @bstansberry looks good now (we only are getting the SingletonDeploymentJBossAllTestCase.test  failure which isn't related to this pr)!

**Comment by bstansberry** [comment]
Thanks, @scottmarlow

**Pull request merged**
