### PR TITLE
[WFLY-17069] Unlock preview features from underlying JDKs by default

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-17069

### CODE REVIEW

**Comment by bstansberry** [comment]
This will need some discussion. https://wildfly.zulipchat.com/#narrow/stream/174184-wildfly-developers/topic/JDK.20Preview.20features

**Comment by bstansberry** [comment]
Once we decide to include a change like this, I think it should be enabled via a profile.

That said, the property you're editing here is used client-side.

**Comment by yersan** [comment]
It is related to https://github.com/wildfly/wildfly-core/pull/5229

**Comment by bstansberry** [comment]
@ropalka I'm going to close this and https://github.com/wildfly/wildfly-core/pull/5229 as the JGroups problem has been corrected. If you want to continue to pursue the topic as a general thing to think about, let's do it on the wildfly-dev mail list.

**Comment by bstansberry** [comment]
Thanks again @ropalka for identifying and raising this problem!

**Pull request closed without merging**
