### PR TITLE
[WFLY-14266] Add resource adapter subsystem dependencies based on cap…

### PR DESCRIPTION
**Pull request by tadamski**
…ability

### CODE REVIEW

**Comment by scottmarlow** [comment]
I ran the Jakarta EE 8 Platform TCK tests that previously failed without this PR and they passed:
```
PASSED........com/sun/ts/tests/ejb32/mdb/modernconnector/Client.java#testModernConnector
PASSED........com/sun/ts/tests/connector/deployment/DeploymentClient.java#testRarInEar
```

**Comment by bstansberry** [comment]
Closing as we won't be making non-critical fixes to 26.x.

**Pull request closed without merging**
