### PR TITLE
WFLY-5606 ManagementOnlyModeTestCase uses non-standard reload idioms

### PR DESCRIPTION
**Pull request by ctomc**

### CODE REVIEW

**Comment by bstansberry** [comment]
:+1:

**Comment by bstansberry** [comment]
I put the 11.x label on this for now. If it gets acked for EAP, either via JBEAP or BZ, please ping me.

**Comment by baranowb** [comment]
@bstansberry I would say it require https://github.com/baranowb/jboss-eap7/commit/252c71c9e5b3f0906435347230f07d69ce1bad7a

**Comment by bstansberry** [comment]
@ctomc baranowb's point is valid, as this test will leave the server in reload-required. You can avoid the need for the reload though by adding the allow-resource-service-restart header to the op at L98:

op = createOpNode("subsystem=undertow/server=default-server/http-listener=test", REMOVE);

**Comment by ctomc** [comment]
@baranowb @bstansberry fixed.

**Comment by ctomc** [comment]
@bstansberry @baranowb using allow-resource-service-restart header or reload on the end of the test.
makes whole testsuite explode with failures you see above.
I can reproduce it locally, but cannot find any reasonable explanation why this happens.
Even renaming listeners & socket bindings didn't change anything.
It looks like the only way to make it work is to not reload or not remove with headers.

**Comment by bstansberry** [comment]
@ctomc Weird. Let's talk about it in today's meeting.

**Comment by ctomc** [comment]
closing for now

**Comment by ctomc** [comment]
follow up https://github.com/wildfly/wildfly/pull/9122

**Pull request closed without merging**
