### PR TITLE
[WFLY-10224] Narayana component upgrade for 5.8.1.Final

### PR DESCRIPTION
**Pull request by ochaloup**
https://issues.jboss.org/browse/WFLY-10224

Narayana component upgrade with a fix of NPE in XTS (JBTM-3007).

### CODE REVIEW

**Comment by kabir** [comment]
Retest this please

**Comment by kabir** [comment]
@ochaloup Not sure if it is a timing issue but the original run couldn't find the artifact. Am trying a rerun now

**Comment by ochaloup** [comment]
@kabir ok, that is probably my fault as the artifact was already on nexus (I've checked that) but I missed that the replication to maven central and general availability could take some time. I think now the artifact is already available (http://search.maven.org/#artifactdetails%7Corg.jboss.narayana%7Cnarayana-all%7C5.8.1.Final%7Cpom).

**Comment by ochaloup** [comment]
Retest this please

**Pull request merged**
