### PR TITLE
Upgrade jsoup from 1.7.1 to 1.8.1 for bug fixes and better speed

### PR DESCRIPTION
**Pull request by fnasser**
No <dependency> for rhino anywhere in this POM

### CODE REVIEW

**Comment by ctomc** [comment]
this is ok to test

**Comment by ctomc** [comment]
[18:32:19][Step 2/3] [ERROR]   The project org.wildfly:wildfly-ts-integ-picketlink:9.0.0.CR1-SNAPSHOT (/opt/buildAgent/work/a31d203e70e89f90/testsuite/integration/picketlink/pom.xml) has 1 error
[18:32:19][Step 2/3] [ERROR]     'dependencies.dependency.version' for rhino:js:jar must be a valid version but is '${version.rhino.js}'. @ org.wildfly:wildfly-ts-integ-picketlink:[unknown-version], /opt/buildAgent/work/a31d203e70e89f90/testsuite/integration/picketlink/pom.xml, line 52, column 30
[18:32:19][Step 2/3] [ERROR]

**Comment by fnasser** [comment]
How should we fix this?  perhaps moving the dependency from this testsuite/integration/picketlink/pom.xml to the wildly pom.xml with scope test?
How do we handle this cases?  Having the property here and the dependency there does not make much sense...

**Comment by bstansberry** [comment]
@hferentschik Please approve/disapprove this change. AFAICT, the reason we have jsoup in WildFly is because of Hibernate Validator, so you guys should control the version we use. Ideally a change like this would come in as part of an upgrade of Hibernate Validator, but if you're ok with it happening separately, that's fine. Thanks.

**Comment by bstansberry** [comment]
Scott Marlow
10:06 AM
@BrianStansberry  @FernandoNasser the jsoup upgrade to 1.8.1 looks right to me.  Looks like HV-817 addressed SafeHTML for HibernateValidator 5.1.0 and HV-703 upgraded jsoup to 1.8.1 a while back for HV 5.0.0.

**Comment by hferentschik** [comment]
+1 for the upgrade. As you say, ideally the version upgrade should come in with a Validator upgrade, but I am fine with an upgrade like this as well. A Hibernate Validator 5.2.0.Final is only a couple of weeks away, so there will be a Validator upgrade soon as well.

**Pull request merged**
