### PR TITLE
[JBEAP-1223]-JDR report contains reference to AS7

### PR DESCRIPTION
**Pull request by ranjithpulluru**
Proposal fix for JBEAP-1223, Please review

### CODE REVIEW

**Comment by spyrkob** [comment]
WFLY JIRA: https://issues.jboss.org/browse/WFLY-5464

**Comment by wolfc** [comment]
The hardcoded `wildfly` (or for that matter `as7`) is bad. This class does not dictate the server type name.

**Comment by jamezp** [comment]
Why not use something generic like `server`, `container`, `java-ee-7-container`, etc.?

**Comment by bstansberry** [comment]
Superceded by #8922.

**Pull request closed without merging**
