### PR TITLE
[WFLY-17496] Bumping SR OpenAPI to 3.2.0 to fix regression when loading big static files

### PR DESCRIPTION
**Pull request by fabiobrz**
JIRA: https://issues.redhat.com/browse/WFLY-17496

### CODE REVIEW

**Comment by fabiobrz** [comment]
Hi @pferraro - I submitted this one but I see you'd have plans [1] for a SR OpenAPI `3.1.3`release, although the project doesn't include such branch ATM. 
Actually this is the reason why I did not backport the fix, the `3.1.3` milestone was suddenly renamed to `3.2`.
I'll keep the draft, feel free to let me know what you think.

[1]
https://issues.redhat.com/browse/WFLY-17601

**Comment by rhusar** [comment]
@fabiobrz FYI as is, this causes the TCK runs to fail (`NoClassDefFoundError: org/yaml/snakeyaml/LoaderOptions`).

**Comment by fabiobrz** [comment]
Thanks for your input, @rhusar.

That missing class was actually introduced in the SnakeYaml version that fixed the CVE.

Will have a look asap.

**Comment by fabiobrz** [comment]
> @fabiobrz FYI as is, this causes the TCK runs to fail (`NoClassDefFoundError: org/yaml/snakeyaml/LoaderOptions`).

Hi @rhusar, this should be fine now. Tests - TCKs as well - pass locally and it seems the cloud tests checks fail due to a HTTP 404 when downloading the JDK.

**Review by pferraro — APPROVED** [review]

**Comment by rhusar** [comment]
Thanks @fabiobrz!

**Comment by rhusar** [comment]
@fabiobrz Just a quick note - make sure to add the Jira ID next time, namely WFLY-17601, to the git commit message. Thanks!

**Pull request merged**
