### PR TITLE
[WFLY-19835][WFLY-19836] Rm otel integration followup

### PR DESCRIPTION
**Pull request by kabir**
Fixes the comments in #18320. The other PR should go in first

https://issues.redhat.com/browse/WFLY-19835
https://issues.redhat.com/browse/WFLY-19836

### CODE REVIEW

**Review by bstansberry — CHANGES_REQUESTED** [review]
@kabir I assume the 2 scratch_#.json files were unintentional additons.

**Comment by kabir** [comment]
@bstansberry ooops, yes. Removed

**Review by bstansberry — APPROVED** [review]

**Review by xstefank — APPROVED** [review]
Not sure why the bot pinged me for this PR, but LGTM.

**Review by rhusar — APPROVED** [review]
Thanks @kabir, this addresses all feedback I left on the original PR.

**Comment by bstansberry** [comment]
Thanks @kabir @rhusar @xstefank

**Pull request merged**
