### PR TITLE
[WFLY-16929] ForwardedHandlerTestCase fails with security manager

### PR DESCRIPTION
**Pull request by jasondlee**
https://issues.redhat.com/browse/WFLY-16929

Add permissions.xml to allow DNS lookups

### CODE REVIEW

**Review by ropalka — APPROVED** [review]

**Comment by darranl** [comment]
Do we have the actual error anywhere of the failed permissions check?

I would like to see what is the justification that these permissions need to be granted to the deployment,

**Review by darranl — CHANGES_REQUESTED** [review]
Before we merge I would like to double check why these permissions are needed.

**Comment by jasondlee** [comment]
> Before we merge I would like to double check why these permissions are needed.

@darranl I don't have a specific error message to stacktrace. I was comparing the deployments for the test that was working with the ones that were not and noticed the discrepancy. I can dig down deeper into the server to find where that might be failing and report back.

**Comment by bstansberry** [comment]
@jasondlee @darranl @fl4via @ropalka This is likely the problem:

https://github.com/wildfly/wildfly/blob/main/testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/handlers/ForwardedTestHelperServlet.java#L43

ServletRequest.getLocalName() will attempt to do a reverse DNS lookup and will return the raw IP if that fails. If that is what Undertow does, then its behavior is correct and this is a test issue where the test is expected the DNS lookup to work. If it wants it to work it needs to give itself permission.

From ServletRequest.getLocalName() javadoc:

```
Returns the fully qualified name of the address returned by getLocalAddr(). If the engine cannot or chooses not to resolve the hostname (to improve performance), this method returns the IP address.
```

So this is a case of 'cannot'. That seems allowable per the method javadoc. It could also be allowable under the 'chooses not  to... (to improve performance)' rationale, as setting up a privileged block to make it work would have a perf cost.

**Comment by bstansberry** [comment]
Note that https://issues.redhat.com/secure/attachment/13063081/stacktrace.log shows the logging of the failed permission check. It's only at DEBUG, which indicates the failure is handled. It's in forwarded-servlet-no-ut-handlers.war which only contains the servlet I mentioned. The test failure is due to an unexpected value from that req.getLocalName() call.

**Review by bstansberry — APPROVED** [review]

**Review by darranl — APPROVED** [review]
Brian has explained why the deployment needs the permission to be granted.

**Comment by ropalka** [comment]
Thank you @bstansberry for detailed justification!

**Comment by bstansberry** [comment]
Thanks @jasondlee, @ropalka and @darranl

**Pull request merged**
