### PR TITLE
Un-@Ignore messaging HA tests

### PR DESCRIPTION
**Pull request by jmesnil**
The upstream issues have been fixed in Artemis 1.1.0-wildfly-6
- https://issues.apache.org/jira/browse/ARTEMIS-138 for shared-store
- https://issues.apache.org/jira/browse/ARTEMIS-103 for replication

### CODE REVIEW

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by bstansberry** [comment]
@jmesnil The PR @pferraro mentioned ^^^ has been merged.

**Comment by jmesnil** [comment]
superseded by https://github.com/wildfly/wildfly/pull/8454

**Pull request closed without merging**
