### PR TITLE
[WFLY-5532] LinkageError when loading CXF NamespaceHandler

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by bstansberry** [comment]
@asoldano please approve

**Comment by asoldano** [comment]
@tdiesler @bstansberry mmh... I'm not really sure here. We used to have a bunch of optional dependencies to the org.springframework.spring module in the past, which were removed when we eventually got rid of the Spring based deployment approach in JBossWS 5. Now, I assume this removal is hurting other components (camel integration?). The question is, should we restore the full set of spring module dependencies (the dependencies only, not the whole stuff using that in JBossWS) or apply this single change here?

**Comment by tdiesler** [comment]
From my perspective this only needs to work in the context of the camel integration. The camel-cxf component calls into cxf for spring descriptors, which in turn needs the (optional) dependency on that spring module, which we also define in the fuse layer.

**Comment by asoldano** [comment]
@tdiesler @bstansberry OK, let's apply this.

**Comment by bstansberry** [comment]
retest this please

**Pull request merged**
