### PR TITLE
[WFLY-19110] Connector: restore application security configuration

### PR DESCRIPTION
**Pull request by tadamski**
https://issues.redhat.com/browse/WFLY-19110

### CODE REVIEW

**Comment by istudens** [comment]
can this one be reviewed? downstream depends on it, thanks

**Comment by bstansberry** [comment]
@fjuma @darranl @Skyllarr Can one of you review this? Thanks.

**Review by fjuma — APPROVED** [review]
Thanks @tadamski!

**Comment by bstansberry** [comment]
Thanks @tadamski and @fjuma

**Pull request merged**
