### PR TITLE
[WFLY-4748] Singleton service fails to start after repetitive cluster…

### PR DESCRIPTION
**Pull request by TomasHofman**
… split with "Failed to reach quorum of 1"
- wrong annotation - @Merged needs to be used instead of @ViewChanged to receive merge events

### CODE REVIEW

**Comment by bstansberry** [comment]
@pferraro please approve

**Comment by pferraro** [comment]
Actually, we need both @ViewChanged and @Merged - I'll fix.

**Comment by pferraro** [comment]
Obsoleted by https://github.com/wildfly/wildfly/pull/7747

**Comment by TomasHofman** [comment]
Thanks for correction :)

**Pull request closed without merging**
