### PR TITLE
[WFLY-4308] Don't include ISecurityManagement in Serialization

### PR DESCRIPTION
**Pull request by darranl**
Instead as this class tends to have process specific configuration a singleton is registered and the reference to it is transient - after deserialization if the reference is null we can obtain the a reference to the registered singleton.

### CODE REVIEW

**Comment by darranl** [comment]
@emmartins The security serialization error is gone - do you want to look into the next error we have?  Alternatively I could remove your commit from this  PR so my fix goes in and you continue with the rest.

**Comment by emmartins** [comment]
Don’t include the test, the EJB context stuff is transient thus the failure. I will work out a proper test later.

—E

**Comment by emmartins** [comment]
@darranl seems there is an issue with this PR, the web build/dist supports the EE Concurrency Utilities spec, but serialization of the security context there fails, due to missing classes.

Test that shows the PR issue (and also fails with the original issue, so you may merge it in your final PR): https://github.com/wildfly/wildfly/compare/master...emmartins:WFLY-4308-test?expand=1

**Comment by darranl** [comment]
Can probably remove all labels now and see how the test runs go.

**Comment by darranl** [comment]
Retest this please

**Comment by darranl** [comment]
Retest this please

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by darranl** [comment]
Retest this please

**Pull request merged**
