### PR TITLE
[WFLY-12190]: Add EjbOverHttpWrongCredentialsTestCase

### PR DESCRIPTION
**Pull request by zhantemirov**
_EJB over HTTP discovery configuration_

https://issues.redhat.com/browse/EAP7-1236
https://issues.redhat.com/browse/WFLY-12190

Based on https://github.com/wildfly/wildfly/pull/12887/ PR. The latest commit here can be cherry-picked afterwards. 

Changes: 

- basic invocation test has been extended with failed discovery and rediscovery checks.
- added test scenario with incorrect wildfly-config.xml authentication credentials.

@tadamski

### CODE REVIEW

**Comment by bstansberry** [comment]
Hi @zhantemirov. Please discuss with @tadamski and get this added to #12887 so all the review work related to the feature can be done in one place. Thanks!

**Comment by bstansberry** [comment]
Also, please add [WFLY-12190] to the commit message.

**Comment by tadamski** [comment]
hi @bstansberry @zhantemirov 
I have pushed some fixes to wildfly-http-client (https://github.com/wildfly/wildfly-http-client/pull/38) - when those are merged and released I will add the upgrade to this PR and merge Sultan's tests on top of it

**Comment by bstansberry** [comment]
@zhantemirov @tadamski I'm going to close this one so this change can be handled as part of the other PR.

**Comment by tadamski** [comment]
@bstansberry ok, this test will be incorporated in my PR

**Pull request closed without merging**
