### PR TITLE
WFLY-6733 Improve toString() representation of web session cache keys…

### PR DESCRIPTION
**Pull request by rhusar**
… (org.wildfly.clustering.infinispan.spi.distribution.Key subclasses)

Jira
https://issues.jboss.org/browse/WFLY-6733

### CODE REVIEW

**Comment by bstansberry** [comment]
@pferraro please approve

**Comment by pferraro** [comment]
@bstansberry :+1:

**Comment by rhusar** [comment]
Anything holding this back?

**Comment by pferraro** [comment]
@rhusar This is out of date.  I already snuck in a fix for this in an earlier PR.

**Pull request closed without merging**
