### PR TITLE
[WFLY-17785] Fix intermittent failures in OidcIdentityPropagationTestCase

### PR DESCRIPTION
**Pull request by fjuma**
https://issues.redhat.com/browse/WFLY-17785
https://issues.redhat.com/browse/WFLY-18161

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]

**Comment by fjuma** [comment]
Going to go ahead and merge this one since we've already had complete successful runs on this PR and since QE has confirmed that the intermittent failures no longer occur with this fix.

**Pull request merged**
