### PR TITLE
WFLY-18036 Marshalling optimizations are not getting applied to @SessionScoped @Stateful EJBs

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-18036

### CODE REVIEW

**Comment by pferraro** [comment]
Rebasing so that we can test this along with recent fixes.

**Comment by darranl** [comment]
@rhusar looks like one more here asking for your review I may be able to bundle in if you are Ok with it?

**Review by rhusar — APPROVED** [review]
I think this looks good (also we have pretested this in a subset of QE tests) - cc @darranl

**Pull request merged**
