### PR TITLE
Fix for WFLY-8990. Add unit tests for CLI completion

### PR DESCRIPTION
**Pull request by jfdenise**
That is a follow up for WFCORE-2993.

### CODE REVIEW

**Comment by kabir** [comment]
This is ok to test

**Comment by bstansberry** [comment]
@jfdenise I don't see why this test shouldn't be in WildFly Core.

**Comment by kabir** [comment]
Retest this please

**Comment by jfdenise** [comment]
@bstansberry , I wanted to add this test in WildFly to take benefit of the test domain setup that is similar to the reported issue (adding a connector to remoting subsystem). We have some other Capability completion tests in core.
If that makes things easier to manage, I could recreate this setup in a core domain test.

**Pull request closed without merging**
