### PR TITLE
WFLY-13840 Problematic Language usage deprecation and replacement in ejb3 subsystem and tests

### PR DESCRIPTION
**Pull request by chengfang**
JIRA: https://issues.redhat.com/browse/WFLY-13840
Related: https://issues.redhat.com/browse/EAP7-1558

Replaced problematic language in ejb areas only.

### CODE REVIEW

**Comment by chengfang** [comment]
Windows JDK11 had 1 failure:

`MeterTest.testRates  org.eclipse.microprofile.metrics.tck.metrics`, which looks an intermittent failure, reported in [WFLY-14038](https://issues.redhat.com/browse/WFLY-14038) Intermittent failure MeterTest.testRates org.eclipse.microprofile.metrics.tck.metrics

**Comment by darranl** [comment]
I wonder if we should start somewhere with a high level preferred terminology for WildFly, obviously individual third party libraries may make their own decisions but maybe we should aim for some consistency across the view we provide of the application server.

Personally I wouldn't suggest blockList as a viable alternative but we probably don't want each PR to need a round of analysing the language.

**Comment by chengfang** [comment]
I think [EAP7-1558](https://issues.redhat.com/browse/EAP7-1558), or a WildFly umbrella jira issue is a good place to collect analysis. Tasks for WildFly components can reference that jira as a high-level analysis and decision document.

**Comment by kabir** [comment]
+1 it would be great to have some kind of 'dictionary'

**Comment by pferraro** [comment]
Additionally, the clustering subsystems have long since standardized on "primary/backups" as a more appropriate alternative to "master/slaves", rather than "primary/secondary", which otherwise implies a cardinality of 2.

**Comment by bstansberry** [comment]
Thanks, for this @chengfang. 99% of this is my doing; code I wrote probably a few weeks before this topic came up.

+1 to a dictionary. I created https://issues.redhat.com/browse/WFLY-14053.

**Comment by kabir** [comment]
Adding the hold label since it looks like we need to come up with a common terminology first

**Review by bstansberry — APPROVED** [review]

**Comment by chengfang** [comment]
I'll resolve the conflicts.

**Comment by chengfang** [comment]
@bstansberry conflict resolved, and tests are passing.

**Comment by bstansberry** [comment]
Thanks @chengfang!

**Pull request merged**
