### PR TITLE
[WFLY-14691] Tests the data source statistics attribute MaxWaitCount during waiting requests.

### PR DESCRIPTION
**Pull request by dcihak**
Test enables statistics, sets min/max pool size on the ExampleDS datasource and tests the data source statistics attribute MaxWaitCount during waiting requests.

[WFLY-14691](https://issues.redhat.com/browse/WFLY-14691)

### CODE REVIEW

**Comment by dcihak** [comment]
Please do not merge now, waits for the fix (https://github.com/ironjacamar/ironjacamar/pull/720) to be merged.

**Comment by rhusar** [comment]
BTW @dcihak You can convert the PR to a draft which is not mergeable. The other option is to add a test as @ Ignore-d and reenable on component upgrade.

**Comment by bstansberry** [comment]
@dcihak @moulalis @tadamski I see various tests of pool statistics in IronJacamar in the core/src/test/java/org/jboss/jca/core/connectionmanager/pool package. This seems like something that should be tested there, not in WildFly.

**Comment by dcihak** [comment]
@rhusar Thank's for the information. @bstansberry I will move the testcase to the Ironjacamar TS if it's more suitable there.

**Comment by bstansberry** [comment]
Thanks, @dcihak. If this can be tested in IJ instead I'd prefer it.

**Comment by dcihak** [comment]
Retest this please.

**Comment by dcihak** [comment]
@bstansberry @moulalis @tadamski org.jboss.as.test.integration.jca.statistics.DataSourceJdbcStatisticsTestCase and org.jboss.as.test.integration.jca.statistics.DataSourcePoolStatisticsTestCase seem to be very similar coverage, that's why I supposed this is the right place.

**Comment by bstansberry** [comment]
@dcihak That test looks to be a simple smoke test that the management API is exposing statistics. This is a much more complex test that is relying on fairly complex timing, and which will take a fair bit of time to run, both of which add fragility to the WF testsuite. If there are regressions in the behavior being tested they are highly unlikely to be in the WildFly code exposing the IJ numbers. Those regressions would not be found when testing IJ; they'd be noticed only when an IJ upgrade is tested in WF, which is too late.

**Comment by dcihak** [comment]
@bstansberry Thank's for clarification. Nevertheless, I will have to move the tests into our [internal testsuite](https://gitlab.hosts.mwqe.eng.bos.redhat.com/jbossqe-eap/tests-jca) as there is not a sufficient support in the ironjacamar repo or the adjustments wouldn't be trivial.

**Pull request merged**
