### PR TITLE
WFLY-15401 Simplify NonFunctionalTimerService and exclude it from Tim…

### PR DESCRIPTION
**Pull request by chengfang**
…erServiceRegistry

https://issues.redhat.com/browse/WFLY-15401

### CODE REVIEW

**Comment by chengfang** [comment]
we should wait for https://github.com/wildfly/wildfly/pull/14757 to be merged and retest this PR.

**Comment by chengfang** [comment]
@tadamski  please review.

**Review by tadamski — APPROVED** [review]
LGTM

**Pull request merged**
