### PR TITLE
WFLY-6898 ConcurrentModificationException when returning from JMS onM…

### PR DESCRIPTION
**Pull request by stuartwdouglas**
…essage() MBean

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@jmesnil Does this look ok to you? The two beans that this method was attempting to destroy already have @PreDestroy methods, so they should be cleaned up anyway.

There is a slight change of behavior here though, previously if the JMSContext was injected into a bean with a smaller scope than request (such as transactional) the request scoped context would be cleared when the transaction finished. I am not sure if this was intended behavior but I think it was probably a bug.

**Comment by jmesnil** [comment]
This change looks good. I remember tweaking this code to pass a TCK test but the current code might be over cautious. 

I'm in PTO and can't access my laptop to check the TCK with that change. 

--
Jeff Mesnil
jmesnil@gmail.com
http://jmesnil.net/

**Comment by jmesnil** [comment]
Iirc the jms 2.0 spec states that the scope of the injected jms context depends on the presence of a transaction ( it's either transactional or request scoped).

--
Jeff Mesnil
jmesnil@gmail.com
http://jmesnil.net/

**Comment by stuartwdouglas** [comment]
@scottmarlow has done a TCK run and confirmed that it passes with the change. 

With the current code there is a small chance the request scope could be cleared half way through a request, so I think this actually fixes a bug there as well.

**Pull request merged**
