### PR TITLE
[WFLY-13508] Fix layer name for naming, it should be 'naming' instead …

### PR DESCRIPTION
**Pull request by yersan**
…of 'ee'

Jira issue: https://issues.redhat.com/browse/WFLY-13508

### CODE REVIEW

**Review by kabir — APPROVED** [review]

**Review by jfdenise — APPROVED** [review]
Good catch.

**Comment by rhusar** [comment]
> This is not a problem at all since currently layers names are discovered by the directory name it resides, however, the wrong name here could lead to confusion.

Hm, so these aren't used? What was the intention for them then?

**Comment by yersan** [comment]
I asked about the intentionality on Zulip as well, see it on Galleon stream, not sure about the reason or if it is a bug.

**Comment by bstansberry** [comment]
Thanks @yersan.

JIRA isn't working for me right now so please check back on the JIRA and resolve it if it remains unresolved.

**Pull request merged**
