### PR TITLE
[WFLY-6784] Add possibility to enable websocket compression via management model

### PR DESCRIPTION
**Pull request by iweiss**
Issue: https://issues.jboss.org/browse/WFLY-6784

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
This needs transformers

**Comment by stuartwdouglas** [comment]
This will conflict with https://github.com/wildfly/wildfly/pull/8586

**Comment by ctomc** [comment]
yes, this should be closed until we get master open and with model/parser bumped to 4.0, aka #8586
at that point it will need transformers.

**Comment by iweiss** [comment]
So let me close this for now. I will revisit this once master opens.

**Pull request closed without merging**
