### PR TITLE
WFLY-4999 XSiteBackupForTestCase tests fail on Windows with IPv6

### PR DESCRIPTION
**Pull request by rhusar**
Jira
https://issues.jboss.org/browse/WFLY-4999

### CODE REVIEW

**Comment by rhusar** [comment]
Retest this please.

ReplicationForNegotiationAuthenticatorTestCase(SYNC-tcp).testGracefulUndeployFailover should not have been affected by these changes.

**Comment by rhusar** [comment]
Ok, this is good to go by me, please @rachmatowicz as an original author of those tests, please ack this change. In summary, the change is that the remote site stack is not using the default udp stack, but rather a copied tcp stack (called tcp-bridge used by the bridge channel) while keeping the udp groups the same (for MPING/PING).

**Comment by pferraro** [comment]
+1

**Comment by rachmatowicz** [comment]
+1

**Comment by rhusar** [comment]
@rachmatowicz Please go ahead, but the only actual difference here should be UDP+PING being replaced by TCP+MPING on the same multicast groups which fixes the intermittent failing when using a udp stack for all communication.

Possibly, the test case can be a regular part of the tcp/udp combinations (-DextendedTests) rather than an extra execution as originally implemented.

**Comment by rachmatowicz** [comment]
Looks good.

**Pull request merged**
