### PR TITLE
WFLY-8941 Fix model versions for all subsystems so transformers can be properly written

### PR DESCRIPTION
**Pull request by ctomc**

### CODE REVIEW

**Comment by ctomc** [comment]
@pferraro @jmesnil @maeste @rhusar @asoldano can you approve changes

**Comment by asoldano** [comment]
+1 for the jaxrs subsystem

**Comment by jmesnil** [comment]
@ctomc what's the rule to change the major version of a subsystem? 

For the messaging-activemq subsystem, we've only introduced new resources and attributes and change 1 default value for an attribute. Does that require a bump of the major version?

**Comment by ctomc** [comment]
@jaikiran any model change requires version bump. if it is major or minor is more related to in what version of WildFly does it appear first. 
If it is in new major version such as in this case  WF 11, than version bump should be major, as minors are reserved for minor version (10.2 for example)

as otherwise if we would do 10.2 and have changed messaging-activemq model, it would need to be bumped to what? 1.1? 1.2? as micro version are always reserved for EAP only.

**Comment by rhusar** [comment]
@ctomc mod_cluster changes look good (even with missing underscore in the commit message :-) ). Surely, this will need a corresponding EAP PR.

**Comment by jmesnil** [comment]
@ctomc +1 for the messaging-activemq subsystem

**Review by jmesnil — APPROVED** [review]

**Comment by jmesnil** [comment]
@ctomc given your arguments, should I also bump the messaging-activemq xsd from 1.1 to 2.0?

**Review by pferraro — APPROVED** [review]
+1 for Infinispan subsystem

**Comment by rhusar** [comment]
@jmesnil that shouldn't be necessary if you haven't done any changes to the xsd.

**Comment by ctomc** [comment]
@jmesnil you are right, also xsd needs to be updated (with related changes) 
I was focused only on model version that I forgot to check also this.

I can fix it in separate PR.

**Pull request merged**
