### PR TITLE
WFLY-11866 Exception can not be passed-by-reference

### PR DESCRIPTION
**Pull request by wfink**
https://issues.jboss.org/browse/WFLY-11866 is a regression of WFLY-2949.

Exceptions are not passed-by-reference if enabled, this cause issues if the Exception is not marked as Serializable.

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

### CODE REVIEW

**Comment by bstansberry** [comment]
@chengfang or @tadamski Please review.

**Comment by tadamski** [comment]
@bstansberry Apparently there was some problem with exception cloning (commit 2a5561b39855b77411de2f29056f293d56405eef) so IMO we should find out what it was before merging it. @stuartwdouglas Do you remember why the change above was needed?

**Comment by jaikiran** [comment]
> @bstansberry Apparently there was some problem with exception cloning (commit 2a5561b) 
@tadamski I'm just guessing here - looking at Stuart's commit there, the previous issue seems to be that the exception cloning was being passed a "target type" of the invoked method's return type instead of the `Exception` class and I think that's what Stuart fixed.

Having looked at @wfink's commit here, to me, the changes seem fine. However, given how often this part of code is runinng into issue and also looking at the linked JIRA, how (relatively) easy it's to reproduce this, I think adding a testcase for this issue would help prevent regressions.

**Comment by tmiyargi** [comment]
@jaikiran test in https://github.com/wildfly/wildfly/pull/12191

**Review by tadamski — APPROVED** [review]

**Comment by bstansberry** [comment]
@tadamski @wfink @tmiyargi 

Both the commits here were approved so once CI is done if results look good I'll merge it.

**Comment by tadamski** [comment]
@bstansberry thanks!

**Pull request merged**
