### PR TITLE
[WFLY-16382] Microprofile JWT configuration properties are out of date

### PR DESCRIPTION
**Pull request by anilabhabaral**
Issue Link: https://issues.redhat.com/browse/WFLY-16382

### CODE REVIEW

**Review by fjuma — APPROVED** [review]
Thanks @anilabhabaral! Looks good.

**Comment by bstansberry** [comment]
Thanks @anilabhabaral

**Comment by anilabhabaral** [comment]
Thank you @bstansberry @fjuma !

**Pull request merged**
