### PR TITLE
WFLY-11316 Remove unused dependencies from org.jberet.jberet-core

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/WFLY-11316

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Comment by RanabirChakraborty** [comment]
@bstansberry I have done the restest and it has passed all the the checks.

**Comment by darranl** [comment]
@RanabirChakraborty FYI when someone says those three words on a PR it is a trigger for CI to run again, not a request for the contributor to perform more testing.

**Comment by RanabirChakraborty** [comment]
@darranl oh! my bad, Thanks for the info :+1:

**Comment by bstansberry** [comment]
Thanks, @RanabirChakraborty

**Comment by bstansberry** [comment]
The CI integration has a more 'command looking' way of telling it what to do, like /retest. I need to get in the habit of using that instead of the old style English language commands!

**Pull request merged**
