### PR TITLE
[WFLY-4813]: Use XaPool / DsXaPool always in XMLXaDataSourceRuntimeHandler

### PR DESCRIPTION
**Pull request by langfr**

### CODE REVIEW

**Comment by langfr** [comment]
Retest this please.

**Comment by langfr** [comment]
Retest this please.

**Comment by jamezp** [comment]
retest this please

**Comment by jamezp** [comment]
@maeste or @jesperpedersen is this okay?

**Comment by jesperpedersen** [comment]
@jamezp LGTM

**Pull request merged**
