### PR TITLE
[WFLY-15055] Use javax module alias instead of the jakarta modules on…

### PR DESCRIPTION
**Pull request by yersan**
… the Bouncy Castle Jakarta Mail module

Jira issue: https://issues.redhat.com/browse/WFLY-15055

### CODE REVIEW

**Comment by yersan** [comment]
https://ci.wildfly.org/viewLog.html?buildId=265385&buildTypeId=WF_WildFlyPreviewLinuxJdk11
https://ci.wildfly.org/viewLog.html?buildId=265396&buildTypeId=WF_Ee9BootableJarLinuxJdk8

**Comment by chengfang** [comment]
Is it required to use javax alias module, or is it both will work but alias is better?

https://github.com/wildfly/wildfly/pull/14502 is similar in this regard, so we may also need to make the same change there.

**Comment by bstansberry** [comment]
@chengfang I'm going to post on wildfly-dev about this in a minute.

**Comment by bstansberry** [comment]
The post: https://lists.jboss.org/archives/list/wildfly-dev@lists.jboss.org/thread/LE6CBNDI3GNXWVX4DOZLU5QNPZQWFJ7K/

**Pull request merged**
