### PR TITLE
[[WFLY-19619] Fix MP Reactive Messaging test failures on JDK23

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-19619

### CODE REVIEW

**Review by kabir — APPROVED** [review]
Thanks @ropalka !

**Comment by bstansberry** [comment]
@ropalka This seems to break things in the testsuite. :)

**Comment by kabir** [comment]
Duh, I hadn't looked at all the jobs 🤦

**Comment by ropalka** [comment]
All is fixed now @kabir @bstansberry

**Review by kabir — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @ropalka and @kabir

**Pull request merged**
