### PR TITLE
[WFLY-16956] Move jboss-ejb-client-legacy to the standard-ee bom as s…

### PR DESCRIPTION
**Pull request by bstansberry**
…ome deliverables associated with WildFly include it

https://issues.redhat.com/browse/WFLY-16956

### CODE REVIEW

**Comment by jbliznak** [comment]
Is anything blocking this one from being merged?

**Comment by bstansberry** [comment]
@jbliznak It needs someone to approve it. You're welcome to do that. :)

**Review by jbliznak — APPROVED** [review]
OK, I thought you don't need one :)

this is the difference in particular BOM after the change https://github.com/jbliznak/test-boms/compare/aa52228fba547e382093f0aa841711e8ad43feb2...bfcd43132fb3be1ea0e64d5a418c4f97c9ea4e2b

it is a bit more than expected and order of dependencies can matter but it still looks ok to me, non-legacy BOM (https://repo1.maven.org/maven2/org/wildfly/wildfly-ejb-client-bom/27.0.0.Alpha4/wildfly-ejb-client-bom-27.0.0.Alpha4.pom) also has those jakarta APIs in there before actual client dependency so at least they are now more similar.

**Comment by bstansberry** [comment]
Thanks for the review / test of the result @jbliznak!

The folks who have permissions to merge things try to resist the temptation to merge our own stuff if it hasn't gotten a review. I think we're mostly successful. ;)

**Pull request merged**
