### PR TITLE
WFLY-4554: Remove unneeded, extra double quotes in jconsole.sh

### PR DESCRIPTION
**Pull request by rpelisse**

### CODE REVIEW

**Comment by darranl** [comment]
Please don't merge - I am still working on this one.

**Comment by rpelisse** [comment]
Let me know i I can help !

On 24 April 2015 at 14:36, Darran Lofthouse <notifications@github.com>
wrote:

> Please don't merge - I am still working on this one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wildfly/wildfly/pull/7385#issuecomment-95919059>.
>



-- 
Romain PELISSE,
*"The trouble with having an open mind, of course, is that people will
insist on coming along and trying to put things in it" -- Terry Pratchett*
Belaran ins Prussia (blog) <http://blog.wordpress.belaran.eu/>     (...
finally up and running !)

**Comment by darranl** [comment]
This PR can be closed as superseded by https://github.com/wildfly/wildfly/pull/7386

**Comment by kabir** [comment]
Closing in line with Darran's comment

**Pull request closed without merging**
