### PR TITLE
[WFLY-12440]:Upgrade jboss-jaxws-api_2.3_spec from 1.0.0.Final to 2.0…

### PR DESCRIPTION
**Pull request by jimma**
….0.CR1
https://issues.jboss.org/browse/WFLY-12440

### CODE REVIEW

**Comment by jimma** [comment]
retest this please

**Comment by kabir** [comment]
@jimma I have not been able to get a clean run - can you check it out?

**Comment by bstansberry** [comment]
@jimma 


[19:26:39][Step 2/3] org.wildfly:wildfly-ts-integ-smoke
[19:26:39][Step 2/3] Importing data from '/store/work/tc-work/bb15431f347cd651/testsuite/integration/smoke/target/surefire-reports/TEST-*.xml' (not existing file) with 'surefire' processor
[19:26:39][Step 2/3] Importing data from '/store/work/tc-work/bb15431f347cd651/testsuite/integration/smoke/target/failsafe-reports/TEST-*.xml' (not existing file) with 'surefire' processor
[19:26:39][Step 2/3] Failed to execute goal on project wildfly-ts-integ-smoke: Could not resolve dependencies for project org.wildfly:wildfly-ts-integ-smoke:jar:18.0.0.Beta1-SNAPSHOT: Failure to find jakarta.jws:jakarta.jws-api:jar:2.1.0

**Comment by kabir** [comment]
Retest this please

**Comment by jimma** [comment]
Retest this please

**Comment by jimma** [comment]
Retest this please.

**Pull request merged**
