### PR TITLE
[WFLY-4724] Port SingletonTunnelTestCase from EAP6 to Wildfly

### PR DESCRIPTION
**Pull request by TomasHofman**

### CODE REVIEW

**Comment by rhusar** [comment]
Make sure to go to the CI server and trigger a build that actually runs the test by adding a run parameter (-DextendedTests).

**Comment by TomasHofman** [comment]
I know the test is failing, but I created the PR anyway, because so far I believe there really is a problem in WF and because the test is not part of standard testsuite runs. After reconsideration I'm closing the PR until we have a fix (or determine that the test is broken).

**Comment by rhusar** [comment]
I don't really see a problem having this test merged as @Ignored add a comment to https://issues.jboss.org/browse/WFLY-4674 and I will enable it upon JGroups upgrade...

**Comment by TomasHofman** [comment]
That sounds good, thanks!

**Pull request closed without merging**
