### PR TITLE
[WFLY-16538] Remove support for log4j 1.x. Removed dependencies and d…

### PR DESCRIPTION
**Pull request by jamezp**
…ocumentation.

https://issues.redhat.com/browse/WFLY-16538

### CODE REVIEW

**Comment by jamezp** [comment]
The `ClusteredJPA2LCTestCase.testEntityCacheReplication` keeps failing for some reason on this PR, however I don't see how it's related. It's failing for me locally on main as well as this branch.

**Comment by yersan** [comment]
Weird, I've just kicked it off again since it has passed and failed for other Jobs, it looks like a flaky test. Also kicked off one for the main branch: https://ci.wildfly.org/viewLog.html?buildId=312657

**Comment by yersan** [comment]
Some additional integration Jobs:

https://ci.wildfly.org/viewLog.html?buildId=312914 (Galleon Layers)
https://ci.wildfly.org/viewLog.html?buildId=312910 (Linux JDK11)
https://ci.wildfly.org/viewLog.html?buildId=312912 (Windows JDK11)

**Review by darranl — APPROVED** [review]

**Review by yersan — APPROVED** [review]
LGTM, integration Jobs with wildfly-core look good, @darranl would it be possible to merge this asap so I can continue with the dependent work on wildfly-core?

**Comment by darranl** [comment]
@yersan merging now

**Pull request merged**
