### PR TITLE
[26.x][WFLY-16303] Upgrade Apache cxf to 3.4.7

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFLY-16303

Upstream (different minor CFX release): https://github.com/wildfly/wildfly/pull/15467

### CODE REVIEW

**Comment by boris-unckel** [comment]
@jimma Could you review and approve, please? Here it's the 26.x version.

**Comment by jimma** [comment]
@boris-unckel  @bstansberry  This looks good to me . Thanks for the upgrade.

**Review by jimma — APPROVED** [review]
This looks good to me.

**Comment by bstansberry** [comment]
Thanks @boris-unckel

**Pull request merged**
