### PR TITLE
WFLY-4941 Numerous "WFLYCLEJBINF0005: Failed to cancel[schedule] expi…

### PR DESCRIPTION
**Pull request by rhusar**
…ration/passivation of bean UnknownSessionID on primary owner.: ExecutionException: TimeoutException: timeout sending message"

Jira
https://issues.jboss.org/browse/WFLY-4941

### CODE REVIEW

**Comment by pferraro** [comment]
FYI - I opened https://issues.jboss.org/browse/ISPN-6238 to address the above failure.

**Comment by rhusar** [comment]
Great, thanks.

**Comment by rhusar** [comment]
retest this please

**Comment by rhusar** [comment]
retest this please

**Comment by n1hility** [comment]
@rhusar @pferraro not sure how chatty these messages are, but if they are directly proportional to load (e.g. 300 requests = 300 log messages) then trace is better than debug.

**Comment by rhusar** [comment]
@n1hility @pferraro I think debug is fine as the logging can only happen during small time window around membership change.

**Pull request merged**
