### PR TITLE
WFLY-19632 Upgrade to Hibernate Search 7.2.0.Final

### PR DESCRIPTION
**Pull request by marko-bekhta**
https://issues.redhat.com/browse/WFLY-19632
https://issues.redhat.com/browse/WFLY-19633
https://issues.redhat.com/browse/WFLY-19631
https://issues.redhat.com/browse/WFLY-19630

This update will require both Hibernate ORM 6.6 and JBoss Logging 3.6.0, hence opening just as a draft for now.

I see that WildFly is still at Hibernate 6.4. Do you want me to send a PR for the 6.6 upgrade, or is it maybe in progress somewhere? 

See also https://hibernate.org/search/releases/7.2#whats-new for overview of what's in the 7.2 series

### CODE REVIEW

**Comment by jamezp** [comment]
This requires https://github.com/wildfly/wildfly-core/pull/6058 which is failing on Windows currently for unknown reasons.

**Comment by marko-bekhta** [comment]
we'll need this one first https://github.com/wildfly/wildfly/pull/18129

**Comment by bstansberry** [comment]
@marko-bekhta I believe this is no longer needed so I'm closing it.

**Pull request closed without merging**
