### PR TITLE
[WFLY-6241] Setting of non-existing factory class to connector service can cause ActiveMQ crash

### PR DESCRIPTION
**Pull request by gaol**
Jira: https://issues.jboss.org/browse/WFLY-6241

Created new OperationHandlers to valid `factory-class` on both add and update operations.

### CODE REVIEW

**Comment by gaol** [comment]
retest this please

**Comment by gaol** [comment]
The build: [Linux with security manager](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=91201&buildTypeId=WF_PullRequest_LinuxSm) passed, why the status is not updated?

**Comment by n1hility** [comment]
@jmesnil can I get your ok on this one?

**Comment by jmesnil** [comment]
@n1hility :+1: 

By looking at this PR, I created https://issues.jboss.org/browse/WFLY-6269 to be able to specify from which module these connector service classes must be loaded (WFLY-6269 will require a new management version, XSD, transformers)

**Comment by gaol** [comment]
Again, The build: [Linux with security manager](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=91201&buildTypeId=WF_PullRequest_LinuxSm) passed, the status is still pending...

**Comment by jmesnil** [comment]
retest this please

**Pull request merged**
