### PR TITLE
WFLY-17718 Leverage SubsystemResourceDescriptionResolver in bean-validation subsystem

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-17718

### CODE REVIEW

**Comment by bstansberry** [comment]
@pferraro Can you rebase this? It's easy to resolve the conflict in the github UI but the fact it pops up as a conflict tells me the resulting history would be untidy.

Perhaps put this and the other b-v one in the same PR so they don't conflict with each other.

**Comment by pferraro** [comment]
They won't conflict as soon as I rebase.  Give me a sec.

**Comment by pferraro** [comment]
Rebased on top of https://github.com/wildfly/wildfly/pull/16587

**Review by jasondlee — APPROVED** [review]
Thanks, @pferraro.

**Comment by bstansberry** [comment]
Thanks @pferraro and @jasondlee

**Pull request merged**
