### PR TITLE
[WFLY-20035] Initialize the Vert.x LoggerFactory in the WF Extension classes that use Vert.x

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFLY-20035

This also merges in @rhusar 's branch from #18452 as that branch seems to reveal the bug this attempts to fix.

____

<--- THIS SECTION IS AUTOMATICALLY GENERATED BY WILDFLY GITHUB BOT. ANY MANUAL CHANGES WILL BE LOST. --->

> Wildfly issue links:
> * [WFLY-20030](https://issues.redhat.com/browse/WFLY-20030)

<--- END OF WILDFLY GITHUB BOT REPORT --->

More information about the [wildfly-bot[bot]](https://github.com/wildfly/wildfly-github-bot)

### CODE REVIEW

**Review by kabir — APPROVED** [review]
@bstansberry Thank you! I was worrying about where to fix this stuff, but remember now that we've done this kind of stuff before.

There was an issue with the migrate operation in the opentelemetry unit tests. The test adds the OTel extension where the call to initialise the Vert.X logger factory did not work. I used my admin privileges to add a commit fixing that by including vert.x on the classpath

**Review by rhusar — APPROVED** [review]
LGTM

**Review by jasondlee — APPROVED** [review]

**Comment by rhusar** [comment]
The SM failure is in, let's see if that's intermittent or not..

```
  [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 17.611 s <<< FAILURE! - in org.wildfly.test.integration.observability.micrometer.multiple.MultipleWarTestCase
16:17:06   [ERROR] checkPingCount(org.wildfly.test.integration.observability.micrometer.multiple.MultipleWarTestCase)  Time elapsed: 1.746 s  <<< FAILURE!
16:17:06   java.lang.AssertionError: expected:<2> but was:<1>
```

**Comment by kabir** [comment]
> The SM failure is in, let's see if that's intermittent or not..
> 
> ```
>   [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 17.611 s <<< FAILURE! - in org.wildfly.test.integration.observability.micrometer.multiple.MultipleWarTestCase
> 16:17:06   [ERROR] checkPingCount(org.wildfly.test.integration.observability.micrometer.multiple.MultipleWarTestCase)  Time elapsed: 1.746 s  <<< FAILURE!
> 16:17:06   java.lang.AssertionError: expected:<2> but was:<1>
> ```

I found some other instances of this failure. It is not related to this PR

**Comment by rhusar** [comment]
I see now - https://ci.wildfly.org/test/-3337280265004991669?currentProjectId=WF_PullRequest&expandTestHistoryChartSection=true&orderBy=status&order=desc (it wasn't processed when I was looking at CI yet). I think we are good to go.

**Comment by bstansberry** [comment]
Thanks @rhusar @kabir and @jasondlee

**Pull request merged**
