### PR TITLE
[WFLY-20084] Fix the build; main moved on while the new poms did not

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFLY-20084

### CODE REVIEW

**Review by rhusar — APPROVED** [review]
LGTM

**Comment by rhusar** [comment]
@bstansberry But how come that dependency tree builder failed with https://github.com/wildfly/wildfly/actions/runs/12285446754/job/34283460542?pr=18508 the following? Is it not testing the actual PR code?

```[FATAL] Non-resolvable parent POM for org.wildfly:wildfly-ts-build-demander-base:35.0.0.Beta1-SNAPSHOT: Could not find artifact org.wildfly:wildfly-parent:pom:35.0.0.Beta1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 25, column 13
[FATAL] Non-resolvable parent POM for org.wildfly:wildfly-testsuite-aggregator-base:35.0.0.Beta1-SNAPSHOT: Could not find artifact org.wildfly:wildfly-parent:pom:35.0.0.Beta1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 19, column 13
[FATAL] Non-resolvable parent POM for org.wildfly:wildfly-ts-build-demander-expansion:35.0.0.Beta1-SNAPSHOT: Could not find artifact org.wildfly:wildfly-parent:pom:35.0.0.Beta1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 25, column 13
[FATAL] Non-resolvable parent POM for org.wildfly:wildfly-testsuite-aggregator-expansion:35.0.0.Beta1-SNAPSHOT: Could not find artifact org.wildfly:wildfly-parent:pom:35.0.0.Beta1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line [19](https://github.com/wildfly/wildfly/actions/runs/12285446754/job/34283460542?pr=18508#step:11:20), column 13
```

**Comment by bstansberry** [comment]
@rhusar The dependency tree job first builds main then builds the merge branch and compares what artifacts are different.

So the 'build main' part will fail.

**Comment by rhusar** [comment]
Ah Gotcha.

**Comment by bstansberry** [comment]
Thanks @rhusar

**Pull request merged**
