### PR TITLE
WFLY-15039 Cluster intermittently fails to reestablish after a node is restarted

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-15039

### CODE REVIEW

**Comment by pferraro** [comment]
@ehsavoie Please review.

**Comment by pferraro** [comment]
Found an issue with fix. Adding hold label.

**Comment by rhusar** [comment]
Do you recon the failed test in the windows run {{ReplicatedFailoverTestCase.testBackupFailoverAfterFailback}} is related?

**Comment by pferraro** [comment]
That windows failure looked like a network issue.

**Comment by bstansberry** [comment]
@ehsavoie Once you settle in from PTO if you could have a look at this one it would be good, as these tests have been regularly failing for quite a while now.

**Review by ehsavoie — APPROVED** [review]

**Pull request merged**
