### PR TITLE
[WFLY-5596] Make MDB delivery activation thread safe.

### PR DESCRIPTION
**Pull request by doctau**
This may not be suitable for merging as-is.

The activate() and deactivate() calls invoke user (resource adapter) code, so doing that while inside a synchronized section could potentially be a deadlock risk since the user code way try to take other locks.

Checking the 'deliveryActive' flag inside a synchronized block (or using AtomicBoolean) would solve part of the problem, but by itself it would still allow problems where activate()/deactivate() get called in the wrong order if one thread called stopDelivery() concurrently with a startDelivery() or start() call (and vice versa).

The activation could be done asychronously but orders, however then the delivery status would not actually have been changed when the call returns, which may cause other problems. I'm not sure what the best course of action is here.

### CODE REVIEW

**Comment by doctau** [comment]
@fl4via: you had been doing work on the MDB delivery control, do you have any ideas on the concurrency issue https://issues.jboss.org/browse/WFLY-5596 ?

**Comment by doctau** [comment]
I accidentally inverted a boolean condition in the merge with the delivery service changes. Fixed

**Comment by doctau** [comment]
I added an additional flag to track whether the component is started, so that start/stopDelivery() do not activate or deactivate the endpoint when start() has never been called.

The deadlock risk is still there, and I'm not sure what to do about that

**Comment by baranowb** [comment]
retest this please

**Comment by doctau** [comment]
If the RA is coded in such a way that the deadlock is actually possible, it is also possible to deadlock right now due to the race condition (reproduced by controlling threads with a debugger):
 - two threads can concurrently enter the activation, the first already holding a lock L1
 - the RA code takes a lock L2, and the second thread acquires L2 first due to the race
 - The first thread blocks waiting for L2, and the second thread attempts to acquire L1 which is the same deadlock trigger as my code.

The change in code may affect the probability of it occurring due to timing, but I don't believe there is any new deadlock risk, only the one that is already present, so I no longer hold that concern about my change (but maybe it could be documented).


Working it out on paper, I think that problem will exist as long as all three of these conditions hold:
 1) Activation and deactivation can only alternate. They cannot run concurrently, be doubled or missed, or re-ordered (fixing the current problem)
 2) If a start* method causes (started && deliveryActive) to change from false to true at some point during execution, the endpoint must be activated at least once before the method finished ("at least once" because other threads may be calling start/stop too). Similarly for stop*.

Relaxing (1) means keeping the current problem.
Relaxing (2) naively means the container could shut down the RA before it the MDB has stopped or similar problems.
Relaxing (2) in a better way to deal with the asynchronous behaviour would require quite large changes to support Component.start() being asynchronous and similar changes in the start/stopDevliery() code.


So I do not think there is a way to remove that risk, short of a large re-design of the EJB code to do things asynchronously. Given that the risk already exists with the current code, I don't think that should block the change.

Obviously the change still needs normal review.

**Comment by fl4via** [comment]
I'm reviewing this to check if that solves the issue, thanks a lot for your fix @doctau !

**Comment by doctau** [comment]
Hi @fl4via, did you have a chance to look over it?

**Comment by fl4via** [comment]
Yes, I had. It all looks okay, I inclusively ran a few tests with it. Thanks!
Regarding the observation on the deadlock scenarios, yes, I agree, we are dealing with external code when it comes to RA, and we cannot control the conditions that could lead to a deadlock, unless we start doing things asynchronously.

**Comment by doctau** [comment]
@bstansberry is the above enough to clear the ee-review flag?

**Comment by bstansberry** [comment]
@doctau Yes. :)

**Comment by bmaxwell** [comment]
Is this ok to merge? We are looking to include downstream if so.

**Comment by bmaxwell** [comment]
retest this please!!
downstreams are passing

**Comment by doctau** [comment]
There are some differences from downstream EAP 6 - the graceful shutdown part, and that it's even possible to trigger the bug without a custom subsystem, but none of those appear to be causing the test failure.  The failure does not occur locally for me, and I assume not for Flavia either.

**Comment by bmaxwell** [comment]
@doctau i had it retest and all checks are passing now

**Pull request merged**
