### PR TITLE
[WFLY-12949] Upgrade WildFly Http Client to 1.0.20.Final

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-12949

This component upgrade incorporates:
    
Bug fixes:
     * [WEJBHTTP-31] Notify waiters when WildflyClientInputStream read listener reads 0 regardless of whether pooled.getBuffer().hasRemaining() returns true or false
     * [WEJBHTTP-32] Remove duplicate notifyAll invocation from WildflyClientInputStream read listener

### CODE REVIEW

**Comment by darranl** [comment]
Can you please add some release notes so we can see what is included in the release?  Is this one pulling in a feature?

**Comment by ropalka** [comment]
Updated both @darranl - commit and pull request description

**Comment by darranl** [comment]
@ropalka Is the new EJB over HTTP discovery something that could be used in a stand alone client or is it only possible to activate this within the application server?

**Comment by ropalka** [comment]
This is question for @tadamski who implemented it @darranl

**Comment by tadamski** [comment]
@darranl the new discovery could be use from standalone client but the configuration on the client side is not yet implemented

**Comment by darranl** [comment]
@tadamski can they activate it programatiaclly using the APIs?

**Comment by tadamski** [comment]
@darranl I have added this ability to the PR

**Comment by ivassile** [comment]
@tadamski / @ropalka According to Darran [1], the new feature should be moved to another branch because 1.0 branch is used for EAP maintenance. This upgrade is also scheduled for 7.2.7 [1] which we need to tag on Monday (1/20) and PROD already built the component. Can we remove the RFE from 1.0 and release new tag so we can rebuild? Thanks!

[1] https://github.com/jbossas/jboss-eap7/pull/3326#issuecomment-574552893
[2] https://issues.jboss.org/browse/JBEAP-18160

**Comment by darranl** [comment]
@ivassile TBH the issue is there is no 1.0 branch.

Probably best thing to do is create a 1.0.x branch from the last known "safe point" for maintenance and tag 1.0.x releases from there and update master to use 1.1.x releases.

**Comment by ivassile** [comment]
@darranl Sorry didn't check, I thought that we already have 1.0.x branch. We build it directly from master. I agree with you that the best is to have 1.0.x branch for maintenance.

**Comment by bstansberry** [comment]
Agreed. @tadamski or @ropalka Please produce a 1.0.20 from a 1.0.x maintenance branch and remove the WEJBHTTP-34 feature from it. Micro releases should not include features and features should be pre-checked before inclusion in a Final/GA minor release.

**Comment by ropalka** [comment]
Done @bstansberry  
- I created 1.0 maintenance branch and released 1.0.20.Final (without EJB over HTTP discovery)
- this PR upgrades to 1.1.0.Final (includes EJB over HTTP discovery)
FYI @darranl @fl4via @ivassile @tadamski ^^^^

**Comment by bstansberry** [comment]
@ropalka Please change this to 1.0.20.Final. We need that in WF now while the WEJBHTTP-34 feature is not ready for merge.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
I cancelled the jobs that were testing 1.1. New jobs testing 1.0.20 then started, although the github ui doesn't accurately show that at the moment. But they are running.

**Comment by bstansberry** [comment]
The Linux with security manager job hung due to an Undertow deadlock (see comment on https://issues.redhat.com/browse/WFLY-12822).  I'll restart that one.

**Comment by bstansberry** [comment]
The restarted job failed with test failures that don't seem obviously irrelevant.

**Comment by ivassile** [comment]
@bstansberry I tested this upgrade in EAP 7.2.7 and all tests + TCK passed. I'm planing to tag the release this weekend.

**Pull request merged**
