### PR TITLE
WFLY-5035 ClusteredMessagingTestCase.testClusteredQueue fails intermittently

### PR DESCRIPTION
**Pull request by rhusar**
Jira
https://issues.jboss.org/browse/WFLY-5035

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
The test still fails

**Comment by rhusar** [comment]
Retest this please.

Looks like this is it ,the problem is with using the udp stack..

**Comment by rhusar** [comment]
This looks promising, I will clean this up shortly.

**Comment by jmesnil** [comment]
this looks good

**Comment by rhusar** [comment]
Please remove fixme label. Thanks.

**Pull request merged**
