### PR TITLE
[hold] WFLY-5471 Expose Infinispan's replicationQueue thread pool configuration

### PR DESCRIPTION
**Pull request by rhusar**
Jira
https://issues.jboss.org/browse/WFLY-5471

### CODE REVIEW

**Comment by rhusar** [comment]
Retest this please.

**Comment by rhusar** [comment]
retest this please

**Comment by rhusar** [comment]
Please hold this off, we are still discussing whether to include this or not.

**Comment by rhusar** [comment]
[23:45:01]Problem while loading patch data stream: Failed to obtain stream from server. Server status: 504 (Gateway Time-out)
[23:45:01]
java.io.IOException: Failed to obtain stream from server. Server status: 504 (Gateway Time-out)

**Comment by n1hility** [comment]
@pferraro @rhusar wdyt?

**Comment by pferraro** [comment]
Let's not bother with this.  The replication queue is likely going to be removed as its functionality is duplicated by JGroups message bundling.

**Comment by rhusar** [comment]
Closing.

**Pull request closed without merging**
