### PR TITLE
[WFLY-11783] Refactoring some EE services to don't use deprecated MSC API

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.jboss.org/browse/WFLY-11783

### CODE REVIEW

**Comment by ropalka** [comment]
The windows failures are unrelated.

**Comment by bstansberry** [comment]
This looks fine but https://issues.jboss.org/browse/WFLY-11841 should be done first, or at least before the ee concurrency part of this.

For example CapabilityServiceTarget is missing an non-deprecated-MSC-friendly addCapability variant, so whoever does WFLY-11841 shouldn't be the one who has to sort that out.

**Comment by bstansberry** [comment]
retest this please

**Comment by darranl** [comment]
Looks like CI is insistent at claiming this changed some dependencies but there are presently merge conflicts before we can run this again.

**Comment by darranl** [comment]
@ropalka I am just trying to clean up some of the backlog in the PR queue so we can see the PRs that need our attention, are you able to get this one up to date or should we close for now and re-open once you are ready?

**Pull request closed without merging**
