### PR TITLE
[WFLY-5583] Special logging for jta=false data sources

### PR DESCRIPTION
**Pull request by gaol**
Jira: https://issues.jboss.org/browse/WFLY-5583

Added a log statement at INFO level when deploying a jta=false data source.

### CODE REVIEW

**Comment by jesperpedersen** [comment]
@gaol This doesn't look right - see where SUBSYSTEM_DATASOURCES_LOGGER.boundDataSource is used, and the "if" needs to be around those

**Comment by gaol** [comment]
@jesperpedersen could you please check it again? Thanks!~

**Comment by jesperpedersen** [comment]
LGTM

**Comment by bstansberry** [comment]
:+1:

**Comment by jamezp** [comment]
retest this please

**Pull request merged**
