### PR TITLE
WFLY-15922 TimerServiceImpl should clone the ScheduleExpression from …

### PR DESCRIPTION
**Pull request by chengfang**
…the user input

https://issues.redhat.com/browse/WFLY-15922

This PR should fix the 5 tck ejb timer test failures.

### CODE REVIEW

**Comment by chengfang** [comment]
@tadamski please review.

**Comment by bstansberry** [comment]
@chengfang Please file a PR against 26.x as well.

**Comment by chengfang** [comment]
@bstansberry looks like 26.x is not affected by this issue.

**Review by tadamski — APPROVED** [review]
@chengfang LGTM

**Pull request merged**
