### PR TITLE
WFCORE-2011 Inconsistency of formatter and named-formatter in console…

### PR DESCRIPTION
**Pull request by tedwon**
… logging handler

https://github.com/wildfly/wildfly-core/pull/2001

This PR is tightly related with https://github.com/wildfly/wildfly-core/pull/2001 to get tests to pass in CI.
To pass tests, this PR's wildfly-core dependency should base on https://github.com/wildfly/wildfly-core/pull/2001 branch (https://github.com/tedwon/wildfly-core/tree/WFCORE-2011).
It requires merging https://github.com/wildfly/wildfly-core/pull/2001 first before merging this PR.

### CODE REVIEW

**Comment by jamezp** [comment]
this is okay to test

**Comment by kabir** [comment]
Needs a downstream PR to to get considered atm

**Comment by JiriOndrusek** [comment]
In a case that difference mentioned in https://github.com/wildfly/wildfly-core/pull/2001 will be added to that PR, there will be probably no need to change TransactionSubsystemTestCase.java

**Comment by kabir** [comment]
@tedwon As this pull request has  been held up for a long time, I am closing it to get the pull request queue under control again. Since this is very old now, it will be a very long time until this one will be addressed. Also, I don't have much time to spend on this to evaluate on a case by case basis.

If this is something important to you or the project please feel free to recreate the pull request. That way it will come on top of the pile again, and be looked at again sooner. 

If it is a new **feature**, please follow the new process for features. Ping @kabir or @jamez if you are unsure what this means, and we can help. Please do that before opening the pull request though.

Sorry for any inconvenience!

**Pull request closed without merging**
