### PR TITLE
[WFLY-13003] Add SameSiteCookieHandler test

### PR DESCRIPTION
**Pull request by fl4via**
Jira: https://issues.redhat.com/browse/WFLY-13003
19.0.x PR: https://github.com/wildfly/wildfly/pull/13237
This requires Undertow 2.1.0.Final: https://issues.redhat.com/browse/WFCORE-4934

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Review by bstansberry — APPROVED** [review]
Approved, assuming it still passes now that the code it tests is merged. (It passed manual custom runs before.)

**Comment by jamezp** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Pull request merged**
