### PR TITLE
[WFLY-16075] Upgrade WildFly Preview to Mojarra 3.0.2.SP01

### PR DESCRIPTION
**Pull request by jasondlee**
https://issues.redhat.com/browse/WFLY-16075

Update jsf-impl version to 3.0.2.SP01

### CODE REVIEW

**Review by bstansberry — CHANGES_REQUESTED** [review]
@jasondlee Could you add a revert of the test exclusions in https://github.com/wildfly/wildfly/pull/15254/commits/b16d77a7c513c80a13fcde83439f6f08ddd4d1a1 to this PR? That will validate the upgrade does what's expected.

EDIT: Just a manual revert of the JSF ones; not a full commit revert.

**Comment by jasondlee** [comment]
> @jasondlee Could you add a revert of the test exclusions in [b16d77a](https://github.com/wildfly/wildfly/commit/b16d77a7c513c80a13fcde83439f6f08ddd4d1a1) to this PR? That will validate the upgrade does what's expected.

I can do that. I believe that's how it was in 3.0.0.SP, so I left it as is. Have things regarding that changed recently? (Still trying to understand the current state of things ;)

**Comment by bstansberry** [comment]
The test exclusions I linked were a workaround to https://issues.redhat.com/browse/WFLY-16061 problem, but the fix I did that should be in 3.0.0.SP2 should remove the need for that workaround.

**Comment by jasondlee** [comment]
> The test exclusions I linked were a workaround to https://issues.redhat.com/browse/WFLY-16061 problem, but the fix I did that should be in 3.0.0.SP2 should remove the need for that workaround.

Changes pushed.

**Review by bstansberry — APPROVED** [review]

**Review by manovotn — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks, @jasondlee

**Pull request merged**
