### PR TITLE
WFLY-16300 Intermittent failures in StopFromDifferentNodeTestCase

### PR DESCRIPTION
**Pull request by chengfang**
https://issues.redhat.com/browse/WFLY-16300

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
@chengfang The changes seems fine but the test still failed with the H2 problem:

```
Caused by: org.h2.jdbc.JdbcSQLException: Remote connections to this server are not allowed, see -tcpAllowOthers [90117-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:89)
	at java.base/java.lang.Thread.run(Thread.java:829)

	at com.h2database.h2@1.4.197//org.h2.engine.SessionRemote.done(SessionRemote.java:623)
	at com.h2database.h2@1.4.197//org.h2.engine.SessionRemote.initTransfer(SessionRemote.java:132)
	at com.h2database.h2@1.4.197//org.h2.engine.SessionRemote.connectServer(SessionRemote.java:447)
	at com.h2database.h2@1.4.197//org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:332)
	at com.h2database.h2@1.4.197//org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at com.h2database.h2@1.4.197//org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at com.h2database.h2@1.4.197//org.h2.Driver.connect(Driver.java:69)
	at org.jboss.ironjacamar.jdbcadapters@1.5.5.Final//org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:335)
```

Some diagnostic logging of what address h2Server is bound to and of h2Server.getURL() might shed some light on this. @tadamski what would be the client-side address of the JDBC connection opened here?

**Comment by chengfang** [comment]
According to [h2 ErrorCode class](https://github.com/h2database/h2database/blob/968b6c15a6abed641327aab4b5d9e06e9d9c239e/h2/src/main/org/h2/api/ErrorCode.java#L1797),  looks like we should use something like `Server.createTcpServer("-tcpAllowOthers")` instead of no-arg version.

**Comment by chengfang** [comment]
The 1 test failure in Windows JDK 11 job (org.jboss.as.test.manualmode.messaging.ha.ReplicatedFailoverTestCase.testBackupFailoverAfterFailback [WFLY-14481](https://issues.redhat.com/browse/WFLY-14481)) seems unrelated to this PR. Other CI jobs and tests all passed.

**Review by bstansberry — APPROVED** [review]
I still don't understand why -tcpAllowOthers is needed or what changed, but we do it elsewhere in the TS and this has taken enough time, so LGTM!

**Comment by bstansberry** [comment]
Thanks, @chengfang

**Pull request merged**
