### PR TITLE
WFLY-9601 upgrade version of checkstyle to latest

### PR DESCRIPTION
**Pull request by rpelisse**
Issue: https://issues.jboss.org/browse/JBEAP-13800
Upstream Issue: https://issues.jboss.org/browse/WFLY-9601

As discussed on [PR10696](https://github.com/wildfly/wildfly/pull/10696), the rule RedundantModifier has been disabled.

DO NOT MERGE BEFORE Checkstyle-config has been properly updated (see [PR10](https://github.com/wildfly/wildfly-checkstyle-config/pull/10)) and released.

### CODE REVIEW

**Comment by rpelisse** [comment]
retest this please

**Comment by rpelisse** [comment]
retest this please

**Comment by rpelisse** [comment]
As discussed with @ctomc on https://github.com/wildfly/wildfly-checkstyle-config/pull/10 I've added back the RedundantModifiers rules, but tuned it to the bare minimal. We still need to fix some redundant 'final' modifier here and there, however (those required modification are part of the PR)

**Comment by rpelisse** [comment]
As discussed on https://github.com/wildfly/wildfly-checkstyle-config/pull/10, I've removed the EqualsHashCode check from the Checkstyle config and thus update this pull request accordingly (removing the two associated "ignores" statement)

**Comment by rpelisse** [comment]
retest this please

**Comment by rpelisse** [comment]
retest this please

**Comment by rpelisse** [comment]
retest this please

**Comment by kabir** [comment]
@rpelisse This seems to still be failing. Adding the fixme label so I don't have to keep looking at this, ping me when it works for you locally

**Comment by rpelisse** [comment]
@kabir Sorry I should have ask for so much retest, because this *can't* work. It needs a new version of wildfly-checkstyle-config to be released first.

**Pull request closed without merging**
