### PR TITLE
Wfly 4870 Component upgrade Hibernate ORM to 5.0.0.CR2

### PR DESCRIPTION
**Pull request by scottmarlow**
Also removed Hibernate 3.x integration (we now include Hibernate integration for releases {4.1.x, 4.3.x, 5.0}).

### CODE REVIEW

**Comment by scottmarlow** [comment]
https://github.com/wildfly/wildfly/pull/7707 addresses the HibernateSearchJPATestCasetest failure

**Comment by scottmarlow** [comment]
hmm, org.jboss.as.test.integration.jpa.hibernate.classfiletransformertest.ClassFileTransformerTestCase passed for me.  I'll run that test a few times locally.

**Comment by scottmarlow** [comment]
org.jboss.as.test.integration.jpa.hibernate.classfiletransformertest.ClassFileTransformerTestCase passes locally.

**Comment by scottmarlow** [comment]
I saved a copy of the org.jboss.as.test.integration.jpa.hibernate.classfiletransformertest.ClassFileTransformerTestCase deployment time exception here https://gist.github.com/scottmarlow/c56cfe07f2ea514354aa

**Comment by scottmarlow** [comment]
This could be a legitimate failure

**Comment by scottmarlow** [comment]
interesting that the failure only occurred on Windows.

**Comment by scottmarlow** [comment]
retest this please so we can see if the error recreates on Windows.

**Comment by Sanne** [comment]
Yes let's disable that test temporarily, we badly need a WF tag with ORM 5 to move on with many other improvements to come.

**Comment by scottmarlow** [comment]
Test is disabled and will later be enabled when HHH-9907 is fixed in ORM CR3.  WFLY-4895 is for enabling the ClassFileTransformerTestCase test again.  Thanks for the thumbs up @Sanne

**Pull request merged**
