### PR TITLE
[WFLY-13048] Upgrade MicroProfile Health 2.2

### PR DESCRIPTION
**Pull request by jmesnil**
JIRA: https://issues.redhat.com/browse/WFLY-13048

Diff to previous version integrated in WildFly: https://github.com/eclipse/microprofile-health/compare/2.1...2.2

Signed-off-by: Jeff Mesnil <jmesnil@redhat.com>

### CODE REVIEW

**Comment by jmesnil** [comment]
I'm putting this PR on hold. It could potentially be merged as-is but I want to get a version of smallrye-health that depends on MP Health 2.2 to be consistent (although, I don't expect changes in smallrye-health itself).
This smallrye-health upgrade will fix the exclusion of `java.enterprise:cdi-api` and use MP Config 1.4.

**Comment by jmesnil** [comment]
Dev analysis is at https://github.com/wildfly/wildfly-proposals/pull/284

**Comment by fabiobrz** [comment]
> I'm putting this PR on hold. It could potentially be merged as-is but I want to get a version of smallrye-health that depends on MP Health 2.2 to be consistent (although, I don't expect changes in smallrye-health itself).
> This smallrye-health upgrade will fix the exclusion of `java.enterprise:cdi-api` and use MP Config 1.4.

Hi @jmesnil, are you referring to a further release of https://github.com/eclipse/microprofile-health/releases/tag/2.2?

**Comment by jmesnil** [comment]
> Hi @jmesnil, are you referring to a further release of https://github.com/eclipse/microprofile-health/releases/tag/2.2?

No, I'm holding this PR until I have a release of `smallrye-health` based on MP Health 2.2.

**Comment by fabiobrz** [comment]
> > Hi @jmesnil, are you referring to a further release of https://github.com/eclipse/microprofile-health/releases/tag/2.2?
> 
> No, I'm holding this PR until I have a release of `smallrye-health` based on MP Health 2.2.

Ah great, I see it now, I was just looking at specs version while you were referring to the component. Thanks for making this clear.

**Comment by bstansberry** [comment]
@jmesnil When this is ready please file a matching PR against 19.0.x and put the 19.x label on that one rather than this one.

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
