### PR TITLE
[WFLY-15231] JCA: validate security attributes in ConnectionDefinitio…

### PR DESCRIPTION
**Pull request by tadamski**
…n instead of Ra node

https://issues.redhat.com/browse/WFLY-15231

### CODE REVIEW

**Comment by darranl** [comment]
CI looks good if you can find someone @tadamski to review.

**Comment by tadamski** [comment]
hi @bstansberry, the change was suggested by you in the JIRA (https://issues.redhat.com/browse/WFLY-15231). Could you please review?

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks, @tadamski

**Pull request merged**
