### PR TITLE
WFLY-12615 Upgrade jboss-ejb-client from 4.0.23 to 4.0.25

### PR DESCRIPTION
**Pull request by chengfang**
JIRA: https://issues.jboss.org/browse/WFLY-12615

Diff between jboss-ejb-client 4.0.23 and 4.0.25: https://github.com/wildfly/jboss-ejb-client/compare/4.0.23.Final...4.0.25.Final

### CODE REVIEW

**Comment by bstansberry** [comment]
@chengfang In the past when CI fails like this for xxx-client upgrades it's been because CI uses -Dipv6 and that exposes a problem in IPv6 handling in the upgrade.

Or it could just be that the upgrade broke one thing as it seems the same test is failing everywhere.

**Comment by chengfang** [comment]
@bstansberry this looks like a legit failure (see more info https://issues.jboss.org/browse/JBEAP-17344).  I'm looking into this.

**Comment by jamezp** [comment]
@chengfang What is the status of this? It's holding up an EAP PR as well.

**Comment by chengfang** [comment]
We're working on a more complete fix for [EJBCLIENT-347](https://issues.jboss.org/browse/EJBCLIENT-347) , which was the issue causing the regression.  cc @tadamski

**Comment by bstansberry** [comment]
Superceded by #12816

**Pull request closed without merging**
