### PR TITLE
WFLY-11447 Management model does not show mod_cluster bound ports

### PR DESCRIPTION
**Pull request by rhusar**
Jira
https://issues.jboss.org/browse/WFLY-11447

### CODE REVIEW

**Comment by rhusar** [comment]
@bstansberry Would you mind reviewing since you brought [this](https://issues.jboss.org/browse/JBEAP-15739?focusedCommentId=13654586&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13654586) up? Thanks!

**Review by bstansberry — CHANGES_REQUESTED** [review]
@rhusar This doesn't do cleanup in stop(). I think that can be done by having ProxyConfigurationServiceConfigurator implement Consumer<ModClusterConfiguration> and having build(ServiceTarget) pass 'this' as a 4th param ('destroyer') to new FunctionalService.

**Comment by bstansberry** [comment]
@rhusar Any update?

**Comment by rhusar** [comment]
@bstansberry Coincidentally I was just testing the changes locally... updated the PR now. Your solution is correct, though I didn't think its needed since the resource is reload required, but let's do this correctly.

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
