### PR TITLE
[WFLY-11987] Upgrade RESTEasy to 3.7.0.Final

### PR DESCRIPTION
**Pull request by ronsigal**
https://issues.jboss.org/browse/WFLY-11987

### CODE REVIEW

**Review by asoldano — COMMENTED** [review]
@ronsigal , I believe we should also update the relevant modules under feature-pack/src/main/resources/modules/system/layers/base/org/jboss/resteasy (you can get a cumulative diff for 3.7.0 at https://github.com/resteasy/Resteasy/compare/3.6.3.Final...3.7.0.Final , look for the changes in jboss-module dir there).

**Comment by ronsigal** [comment]
@asoldano, ah, I didn't know about that. Ok, thanks.

**Comment by kabir** [comment]
This is ok to test

**Comment by darranl** [comment]
Do we have any release notes with a list of changes in this version?

**Comment by ronsigal** [comment]
I just pushed the feature-pack module changes mentioned by @asoldano.

**Comment by ronsigal** [comment]
Hi @darranl,

Release notes: https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12310560&version=12340592

**Comment by ronsigal** [comment]
I can't login to TeamCity to see the failures ...

**Comment by darranl** [comment]
@ronsigal ignore that last failure, I will kick off again - looks like the race condition where TeamCity could not find the commit to build.

**Comment by ronsigal** [comment]
Ah. Thanks, @darranl.

**Comment by darranl** [comment]
This may take a few minutes, CI seems a bit overloaded today ;-)

**Comment by darranl** [comment]
@ronsigal Some delays but the jobs are starting to run again now.

**Comment by ronsigal** [comment]
Yayyy!!

**Comment by ronsigal** [comment]
Aaaarrrrgggghhhh

**Comment by ronsigal** [comment]
Is it something I did?

**Comment by asoldano** [comment]
@ronsigal I don't think it's because of your changes, but you can check TravisCI by using the guest login option.

**Comment by ronsigal** [comment]
@asoldano, thanks for the tip. I didn't see that.

It turns out that pom.xml and feature-pack/pom.xml were still referencing resteasy-validator-provider-11.

**Comment by ronsigal** [comment]
Also galeon-pack/pom.xml. About to commit that.

**Comment by asoldano** [comment]
@ronsigal mmh... maybe some exclusions are needed in the poms?

**Comment by ronsigal** [comment]
@asoldano, yes, I've excluded jboss-logging in galleon-pack and feature-pack. I'm running the build now.

I should have tested before submitting the PR, but the build was failing for what looked like irrelevant problems. :{

**Comment by ronsigal** [comment]
The succeeded except for some seemingly irrelevant failures in the testsuite. I've pushed the circularity fixes. Can we try again?

**Comment by asoldano** [comment]
Retest this please

**Comment by ronsigal** [comment]
Well, this is disturbing. The first test (Linux - JDK 11) shows 6 failures:
```

BeanValidationConfiguredGloballyTestCase.testInvalidRequestsAreAcceptedDependingOnGlobalValidationConfiguration
--
BeanValidationIntegrationTestCase.testInvalidRequest
BeanValidationIntegrationTestCase.testInvalidRequestCausingPropertyConstraintViolation
BeanValidationIntegrationTestCase.testInvalidRequestsAreAcceptedDependingOnValidationConfiguration
BeanValidationIntegrationTestCase.testInvalidResponse

```
When I clone a clean copy of wildfly master and merge the pull request, they all pass.

**Comment by ronsigal** [comment]
Same comment for Linux - elytron - JDK 8.

**Comment by ronsigal** [comment]
Well, with
```
<include>org/jboss/as/test/integration/jaxrs/**/*TestCase*.java</include>
```
I get the same failures. Something to look at, anyway.

**Comment by ronsigal** [comment]
I set up BeanValidationIntegrationTestCase so that I could step through the code on the server, but it passes. AARRGGHH.

**Comment by ronsigal** [comment]
Ok, after playing around, not changing anything substantive, as far as I can tell, now the tests pass when I run
```
<configuration>
    <!-- Tests to execute. Overriden in webProfileExclusion.profile . -->
     <includes>
         <include>org/jboss/as/test/integration/jaxrs/**/*TestCase*.java</include
```
I'm bewildered. Suggestions welcome.

**Comment by ronsigal** [comment]
I'm trying to rerun the tests, and I get
```
Cannot find commit 896730e28af18c543f2ea3d854f21b7b2a8e1bc7 in the https://github.com/wildfly/wildfly.git repository, possible reason: refs/pull/12280/merge branch was updated and the commit selected for the build is not reachable anymore  
Failed to perform checkout on agent: Cannot find commit 896730e28af18c543f2ea3d854f21b7b2a8e1bc7 in the https://github.com/wildfly/wildfly.git repository, possible reason: refs/pull/12280/merge branch was updated and the commit selected for the build is not reachable anymore
```
I don't know how to tell it to look for a newer commit ...

**Comment by ronsigal** [comment]
I'm going to close this PR and create a new one.

**Comment by ronsigal** [comment]
Replaced by https://github.com/wildfly/wildfly/pull/12293

**Pull request closed without merging**
