### PR TITLE
WFLY-16060 README.md contains broken link to contributing doc, and incorrect java versioin

### PR DESCRIPTION
**Pull request by parsharma**
Issue: https://issues.redhat.com/browse/WFLY-16060

### CODE REVIEW

**Comment by chengfang** [comment]
another line in readme needs change:
`2. Make sure Xmx in eclipse.ini is at least 1280M, and it's using Java 8`

**Comment by chengfang** [comment]
Though it could be a separate issue, it may be easier just to also update `contributing.adoc` to reflect current java version requirement:

`Building WildFly requires Java 8 or newer. Make sure you have JAVA_HOME set to point to the JDK8 installation. Build uses Maven 3.`

`* OpenJDK 8 (eight!) You can use any distribution in example Eclipse`

**Comment by parsharma** [comment]
@chengfang I have updated the files, In case there are more places where we need to update the java version, I think we should log another Jira Issue for it.

Thanks

**Review by chengfang — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks, @parsharma

**Pull request merged**
