### PR TITLE
[WFLY-18520]:Upgrade CXF to 4.0.3

### PR DESCRIPTION
**Pull request by jimma**
https://issues.redhat.com/browse/WFLY-18520

### CODE REVIEW

**Comment by bstansberry** [comment]
@jimma It looks like the new org.apache.cxf.transport.http.HttpClientHTTPConduit class requires a module dependency on the java.net.http module.

**Comment by jimma** [comment]
Thanks @bstansberry . Added and wait to see the CI result.

**Comment by jimma** [comment]
It looks we have to add NetPermission("getProxySelector") to these failed tests.

**Comment by bstansberry** [comment]
@jimma These failures looks like a CXF bug, as ServletClient isn't doing anything that should require a permission. It's just trying to invoke an interface. The interface impl is trying to do something internal that needs the permission. (HttpClientHTTPConduit calls ProxySelector.getDefault().)

**Comment by jimma** [comment]
Now each http request like getting the WSDL requires this permission in the new HttpClientHTTPConduit: 
```
 at java.base/java.net.ProxySelector.getDefault(ProxySelector.java:96)
  at org.apache.cxf.impl//org.apache.cxf.transport.http.HttpClientHTTPConduit$ProxyFactoryProxySelector.select(HttpClientHTTPConduit.java:330)
  at java.net.http/jdk.internal.net.http.HttpRequestImpl.retrieveProxy(HttpRequestImpl.java:287)
  at java.net.http/jdk.internal.net.http.HttpRequestImpl.<init>(HttpRequestImpl.java:133)
  at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:603)
  at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:586)
  at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:578)
  at java.net.http/jdk.internal.net.http.HttpClientFacade.sendAsync(HttpClientFacade.java:129)
```
It needs to add doPrivileged block to the HttpClientHTTPConduit.  I already sent a PR to fix this issue in CXF: https://issues.apache.org/jira/browse/CXF-8933

**Comment by jimma** [comment]
Sent another PR to fix the security permission issue: https://github.com/apache/cxf/pull/1453
`Caused by: java.io.IOException: java.security.AccessControlException: Permission check failed (permission "("java.net.URLPermission" "http://127.0.0.1:8080/wsse-policy-trust-sts/SecurityTokenService" "POST:Accept,Content-Type,SOAPAction,User-Agent")"
    at org.apache.cxf.impl//org.apache.cxf.transport.http.HttpClientHTTPConduit$HttpClientWrappedOutputStream.getResponse(HttpClientHTTPConduit.java:590)
    at org.apache.cxf.impl//org.apache.cxf.transport.http.HttpClientHTTPConduit$HttpClientWrappedOutputStream.getResponseCode(HttpClientHTTPConduit.java:601)
    at org.apache.cxf.impl//org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.doProcessResponseCode(HTTPConduit.java:1653)
at org.apache.cxf.impl//org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1684)
    at org.apache.cxf.impl//org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1626)
    at org.apache.cxf.impl//org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1420)
    at org.apache.cxf@4.0.3//org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
    at org.apache.cxf.impl//org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:717)
    at org.apache.cxf.impl//org.apache.cxf.transport.http.HttpClientHTTPConduit.close(HttpClientHTTPConduit.java:112)`

**Comment by jimma** [comment]
There is another memory leakage issue is found by community :  https://issues.apache.org/jira/browse/CXF-8946. 
It's better that we directly upgrade CXF to 4.0.4.

**Pull request closed without merging**
