### PR TITLE
[WFLY-12003] Update jboss-ejb-client to 4.0.17.Final

### PR DESCRIPTION
**Pull request by tadamski**
https://issues.jboss.org/browse/WFLY-12003
Core PR:
https://issues.jboss.org/browse/WFCORE-4433

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

### CODE REVIEW

**Comment by kabir** [comment]
@tadamski This needs to reference a Jira in the commit message, and also the PR should have a link to the Jira issue

**Comment by tadamski** [comment]
@kabir ok will do, but could you please hold up this PR; we would need core update for that - I will clarify it in the JIRA

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
@tadamski WF Core has been updated but this still has lots of test failures.

**Comment by rachmatowicz** [comment]
FYI, i'm running this locally against Wildfly master on Fedora/JDK 8 and I don't see these failures.

**Comment by bstansberry** [comment]
retest this please

In case the above failures were something strange

**Comment by bstansberry** [comment]
@rachmatowicz on the off chance it's relevant, the CI jobs run with -Dipv6, which most people don't do when testing locally.

**Pull request closed without merging**
