### PR TITLE
WFLY-15550 move Weld subsystem to Jakarta namespace variant

### PR DESCRIPTION
**Pull request by manovotn**
JIRA link - https://issues.redhat.com/browse/WFLY-15550

### CODE REVIEW

**Comment by manovotn** [comment]
Started this as a draft because there are some open questions that I asked in a separate email discussion. I will update this PR once I get the answer.

**Comment by manovotn** [comment]
The failures so far don't seem related, it's:
>   Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.3.0:wget (ts.config-as.configure-infinispan-server) on project wildfly-ts-integ-clustering: IO Error

I have no idea what's the cause since the URL it attempts to download is OK.

**Comment by manovotn** [comment]
This PR now contains changes for Weld subsystem as well as `wildfly-weld-jpa` module, both as a separate commit.

**Comment by manovotn** [comment]
@bstansberry this PR should now be reviewable

**Comment by bstansberry** [comment]
@manovotn re the wget problem, I've seen it elsewhere now and started a discussion -- https://wildfly.zulipchat.com/#narrow/stream/174184-wildfly-developers/topic/wget.20failures.20in.20testsuite

**Comment by bstansberry** [comment]
The PR status block doesn't reflect this but I reran the two failed jobs and they passed.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @manovotn!

**Comment by manovotn** [comment]
My pleasure.
Thanks for making such detailed guide for this @bstansberry :-)

**Pull request merged**
