### PR TITLE
Upgrade Netty to 4.0.42.FINAL

### PR DESCRIPTION
**Pull request by tobiasstadler**
JIRA: https://issues.jboss.org/browse/WFLY-7375

### CODE REVIEW

**Comment by ctomc** [comment]
this is ok to test

**Comment by jmesnil** [comment]
This is not OK to merge. We can not upgrade Netty until https://issues.jboss.org/browse/WFLY-7352 is fixed

**Comment by ctomc** [comment]
I think this can be closed now, as netty was upgraded to 4.1.x

**Comment by jmesnil** [comment]
This PR is no longer relevant: Netty is now at 4.1.5.Final

**Pull request closed without merging**
