### PR TITLE
WFLY-16605 remove Hibernate 5.1 + EclipseLink, OpenJPA compat tests as interested parties could create external feature packs for those.

### PR DESCRIPTION
**Pull request by scottmarlow**
https://issues.redhat.com/browse/WFLY-16605
Signed-off-by: Scott Marlow <smarlow@redhat.com>

In summary, testsuite/compat proved its worth for many years but as we head towards EE 10, there is little value in keeping EE 8 (javax namespace) testing of OpenJPA, EclipseLink, Hibernate ORM 5.1 in place.  Best to have these integrations be externally available (e.g. feature packs) in a way that might transform the `javax` namespace to `jakarta` and tested there as well.

### CODE REVIEW

**Comment by darranl** [comment]
@scottmarlow we have a merge conflict on this one, this sounds like one we want to get reviewed and merged for the ongoing Jakarta EE work?

**Comment by scottmarlow** [comment]
> @scottmarlow we have a merge conflict on this one, this sounds like one we want to get reviewed and merged for the ongoing Jakarta EE work?

Thanks @darranl, the merge conflict is now resolved.

**Comment by scottmarlow** [comment]
synced with latest main changes.

**Comment by bstansberry** [comment]
@scottmarlow Can you resolve the conflict and change the JIRA # on commit msgs and the PR title to https://issues.redhat.com/browse/WFLY-16605? Thanks.

I don't think this is urgent.

**Comment by bstansberry** [comment]
I changed the target for this to big-bang.

**Comment by scottmarlow** [comment]
Thanks Brian, just resolved the conflict and updated the jira # references on commit + pr title.

**Review by bstansberry — APPROVED** [review]
LGTM but I'm going to put a hold on this as I'll merge #15762 which is this + the merge conflict resolved.

**Comment by bstansberry** [comment]
Thanks, @scottmarlow

**Pull request merged**
