### PR TITLE
Allow minimum session-id-length of 16 bytes - which is the minimum OW…

### PR DESCRIPTION
**Pull request by rhusar**
…ASP recommendation and the EAP 6.x setting (WFLY-3642)

### CODE REVIEW

**Comment by rhusar** [comment]
Hey @stuartwdouglas, any reason why we would disallow configuring the session id length to the EAP 6.x default value or the minimum OWASP recommendation? cc @pferraro @mvinkler

**Comment by rhusar** [comment]
Unrelated failures.

**Comment by rhusar** [comment]
Retest this please.

**Comment by kabir** [comment]
Retest this please

**Pull request merged**
