### PR TITLE
[WFLY-17007] Upgrade JBoss Metadata to 15.2.0.Beta2

### PR DESCRIPTION
**Pull request by bstansberry**
Signed-off-by: Brian Stansberry <brian.stansberry@redhat.com>

https://issues.redhat.com/browse/WFLY-17007

This is really just to test a new job I added to the CI set. #16069 is the real PR.

### CODE REVIEW

**Comment by bstansberry** [comment]
@ehsavoie @chengfang I see there is ongoing discussion on #16069, which is good. Do either of you see any issue with merging this (just the component upgrade) while that discussion continues?  If the upgrade itself is ok (i.e. better than 15.2.0.Beta1) I'd like to get it in to get it exposed to CI runs and TCK runs.

**Comment by chengfang** [comment]
@bstansberry that sounds good to me.

**Pull request merged**
