### PR TITLE
WFLY-4243: adding bindings not component scoped to module (instead of cl...

### PR DESCRIPTION
**Pull request by emmartins**
...ass) binding configurations

### CODE REVIEW

**Comment by jmesnil** [comment]
Shouldn't a similar change be done for resources defined in the XML descriptors?

I confirm that your PR fixes the issues in the TCK resourcedefs/annotations tests but the resourcedefs/descriptor (which are the same tests except the JMS resources are defined in the XML descriptors) still fail.

**Comment by jmesnil** [comment]
actually, scratch my comment: the resourcedefs/descriptor also passes (the failures I noticed where due to a pb in my environment. once I fixed it, theses tests also passed).

This looks good to merge, thanks!

**Comment by emmartins** [comment]
retest this please

**Comment by stuartwdouglas** [comment]
This PR breaks quite a bit of stuff. The bindings belong to the class, not the module, and this is important because classes can be used by components from multiple modules (resulting in a single class level definition creating different java:module bindings in different modules). 

What is the underlying reason for this change? Not all bindings make sense to be present in the app client, it is not a full server.

**Comment by jmesnil** [comment]
@stuartwdouglas This PR was about fixing a regression in JMS TCK dealing with JMS resource definitions that are defined in app client archives.

The regression started with https://github.com/wildfly/wildfly/commit/3a3c044e344b542dbdce5f4e6f7e5978e6944714 .

Before that, I added the bindings to the module too for war and appclient deployments.
When @emmartins generalized the code in the ee subsystem, this special case disappeared.
This PR was generalizing this special case to any bindings. If that's not acceptable, I need a hook to be able to handle the JMS resource definition binding appropriately.

Is that acceptable?

**Comment by emmartins** [comment]
1) This PR is only for resource definition annotations (EE.5.18) not on java:comp, these are specific pure metadata and must be bound in every module. Having these on "standard" class bind configs results on not being processed for some components (e.g. app client) as it is mandated by the spec

2) I did not notice any issue with the change, can you please indicate what it breaks so I have a look? If this is fact breaks something then we need to change how class bindings are processed, cause @jmesnil  hack was not correct yet the tick tests will continue to fail if we continue to rely on this single process of these special binding annotations

**Comment by emmartins** [comment]
just to clarify why the previous hack was not correct, it was being applied just to JMS resource definitions on war and app client, and the "process" must be the same for all resource definition annotations, and the bindings were being copied to both class and module binding configs

**Pull request closed without merging**
