### PR TITLE
WFLY-4653 Weld thread pool should be wildfly global

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by stuartwdouglas** [comment]
Failure is related, possibly some kind of race in weld that is exposed by the different executor?

Caused by: java.lang.Exception: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"ejb3-ear-servlet.ear\".WeldStartService" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"ejb3-ear-servlet.ear\".WeldStartService: Failed to start service
    Caused by: org.jboss.weld.exceptions.DefinitionException: WELD-001517: The type of the resource producer field [[BackedAnnotatedField] @EJB org.jboss.as.test.integration.ejb.servlet.EJBServletEar.injectedSession] does not match the resource type org.jboss.as.test.integration.ejb.servlet.Session30BusinessRemote"}}

**Comment by jharting** [comment]
I am going to investigate

**Comment by jharting** [comment]
I forgot to deal with TCCL in the executor

**Comment by jharting** [comment]
Should be fixed now

**Pull request merged**
