### PR TITLE
WFLY-13436 Combine AbstractDeploymentUnitProcessor and AnnotatedEJBCo…

### PR DESCRIPTION
**Pull request by chengfang**
JIRA: https://issues.redhat.com/browse/WFLY-13436

Combine ejb3 AbstractDeploymentUnitProcessor and AnnotatedEJBComponentDescriptionDeploymentUnitProcessor, since the latter is the only subclass of the former.

### CODE REVIEW

**Comment by chengfang** [comment]
@darranl please review.

**Comment by bstansberry** [comment]
This LGTM, other than the optional point that the protected methods in the DUP, other than getEjbJarDescription, can all now be private.

I get a strange pleasure from seeing the 'protected' keyword disappear from java code. ;)

**Comment by chengfang** [comment]
Changed those protected methods to private in `AnnotatedEJBComponentDescriptionDeploymentUnitProcessor`.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
@chengfang I'm fine with merging this. It's a holiday in Europe today. If there's something where you need Darran's review I'm fine waiting, otherwise we can get it in.

**Comment by chengfang** [comment]
@bstansberry it's more of a FYI for Darran.  Yes, please go ahead merge it when ready.

**Pull request merged**
