### PR TITLE
WFLY-19079 Upgrade Infinispan to 14.0.26.Final

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-19079

### CODE REVIEW

**Review by rhusar — CHANGES_REQUESTED** [review]
LGTM - but restarted the failed runs in the meantime.

**Comment by bstansberry** [comment]
@pferraro I'm going to add the 'hold' label on this to take it off the radar screen, given the high number of CI failures.

**Comment by rhusar** [comment]
All 4 runs are hung again even with .26, last time the did with 14.0.25.Final the hung was in: https://gist.github.com/rhusar/93e2c11df00d4d32f60fe63343b898a9#file-invalidation-log-L741-L774

**Review by rhusar — APPROVED** [review]
Excellent, LGTM now.

**Comment by bstansberry** [comment]
Thanks @pferraro and @rhusar

**Pull request merged**
