### PR TITLE
[WFLY-14842] / [WFLY-13889] Remove JCA dependency on PicketBox.

### PR DESCRIPTION
**Pull request by darranl**
Submitting as a draft as the following PR needs to be approved first:
    https://github.com/wildfly/wildfly/pull/14945

https://issues.redhat.com/browse/WFLY-14842

### CODE REVIEW

**Comment by darranl** [comment]
@tadamski could you please review the last commit in this PR?
    https://github.com/wildfly/wildfly/pull/14958/commits/4f33943b355698aa5704e2a93e58afda403f6217

Don't worry about the other commits as they are being reviewed in their old PR but that last commit removes the dependencies on PicketBox from IronJacamar.

**Review by tadamski — APPROVED** [review]
LGTM but I think we would have to discuss whether Elytron/connector/IronJacamar integration is feasible and should be implemented at some point

**Comment by darranl** [comment]
Superseded by https://github.com/wildfly/wildfly/pull/15156

**Pull request closed without merging**
