### PR TITLE
Update Hibernate Search & Apache Lucene, remove Infinispan Directory modules

### PR DESCRIPTION
**Pull request by Sanne**
This addresses both following issues, as they are strongly related:
- https://issues.jboss.org/browse/WFLY-5313
- https://issues.jboss.org/browse/WFLY-5315

And by side effect this upgrade will also resolve:
- https://issues.jboss.org/browse/WFLY-5036

### CODE REVIEW

**Comment by scottmarlow** [comment]
This change looks good to me.  Nice to see Hibernate Search 5.5.0.CR1, is 5.5.0.Final expected soon?

**Comment by Sanne** [comment]
> is 5.5.0.Final expected soon?

yes, a matter of days

**Comment by pferraro** [comment]
:+1: Looks good.

**Comment by gunnarmorling** [comment]
FYI, I've filed PR #8125 for updating to Hibernate Search 5.5.0.Final.

**Pull request merged**
