### PR TITLE
WFLY-6464 JPA 2.2 container support (Hibernate ORM 5.3 will be separate)

### PR DESCRIPTION
**Pull request by scottmarlow**

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Why is this being submitted seperate to the hibernate upgrade? Won't this just cause issues in preview mode if not using a hibernate that is aware of the new API?

**Comment by scottmarlow** [comment]
@stuartwdouglas the JPA 2.2 container is expected to work with JPA 2.1 persistence providers (especially Hibernate ORM 5.1).  Plus, we should include this change, since it is ready and separate.

For Hibernate 5.3, the JipiJapa integration module (for Hibernate ORM 5.3) is moving into the Hibernate ORM project.  The Hibernate ORM 5.3 module definitions will also be in the Hibernate project.  We will include their modules in WildFly 13.

**Comment by scottmarlow** [comment]
As a further check, I started some testing for today.

**Comment by scottmarlow** [comment]
I cannot talk about my testing results here but I still think this change is okay.  :)  Having this in, will also simplify our Hibernate ORM 5.3 testing.

**Pull request merged**
