### PR TITLE
[WFLY-19368] Don't duplicate the otel otlp and exporter jars

### PR DESCRIPTION
**Pull request by kabir**
https://issues.redhat.com/browse/WFLY-19368

____

More information about the [wildfly-bot[bot]](https://github.com/wildfly/wildfly-github-bot)

### CODE REVIEW

**Comment by kabir** [comment]
Putting this on hold, so @jasondlee, who should be more familiar, can take a look

**Review by jasondlee — APPROVED** [review]
LGTM. Thanks, @kabir!

**Comment by jasondlee** [comment]
> LGTM. Thanks, @kabir!

Except for those test failures I hadn't noticed. Would you like me to check out your PR and take a look?

**Comment by kabir** [comment]
@jasondlee yes please :-)

**Comment by jasondlee** [comment]
> > LGTM. Thanks, @kabir!
> 
> Except for those test failures I hadn't noticed. Would you like me to check out your PR and take a look?

I think the issue is that Glow either isn't seeing that otel is being used, or (more likely, since it works without this change) the change in the module structure is confusing the scanner. @jfdenise, any thoughts?

**Comment by kabir** [comment]
@jasondlee We actually have some guards in the tests to make sure that the layers discovered don't change. This is with -Dts.bootable

> Starting Scanner in forked process
[INFO] Expected errors found in glow scanning results.  The test execution should fix them (eg: add missing datasources)
[INFO] [cdi, ee-integration, ejb, ejb-lite, h2-datasource, jaxrs, jpa, jsonp, micrometer, microprofile-config, microprofile-fault-tolerance, microprofile-health, microprofile-jwt, microprofile-lra-coordinator, microprofile-lra-participant, microprofile-openapi, microprofile-reactive-messaging, microprofile-reactive-messaging-amqp, microprofile-reactive-messaging-kafka, microprofile-reactive-streams-operators, microprofile-rest-client, microprofile-telemetry, naming, opentelemetry, transactions]==>ee-core-profile-server,ejb,h2-datasource,jpa,micrometer,microprofile-fault-tolerance,microprofile-health,microprofile-jwt,microprofile-lra-coordinator,microprofile-lra-participant,microprofile-openapi,microprofile-reactive-messaging-amqp,microprofile-reactive-messaging-kafka,microprofile-rest-client,microprofile-telemetry


It looks like some CDI beans aren't available.

One thought I had was, that perhaps we need to import/export things better between the modules after these changes. But that doesn't explain why it works in other cases :-)

Another thing could be perhaps we're missing some hard module dependencies from the layer/subsystem to the modules? But looking, all the three modules I've changed are in the modules directory. And it looks like -Dts.layers passes, and that also uses Glow. 

So, it is quite odd.

**Pull request closed without merging**
