### PR TITLE
[WFLY-4902] Upgrade to Artemis 1.1.0-wildfly-4

### PR DESCRIPTION
**Pull request by jmesnil**
**please do not merge without @n1hility's approval.**

This PR uses our WildFly fork for Artemis with commits cherry-picked that were causing regression in our tests https://github.com/apache/activemq-artemis/compare/1.1.0...wildfly:1.1.0-wildfly-4

### CODE REVIEW

**Comment by jmesnil** [comment]
now with fork https://github.com/apache/activemq-artemis/compare/1.1.0...wildfly:1.1.0-wildfly-5

**Comment by jmesnil** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Pull request merged**
