### PR TITLE
Move some javax.* to jakarta.*

### PR DESCRIPTION
**Pull request by jamezp**
This includes a temporary commit to add the jakarta.json module to full. This module lives in core which for testing purposes should wait for this to be merged, then reverted once merged into core and core is released. This also pertains to the jakarta.inject dependency as well.

This includes the following as to not cause conflicts with having these separate commits:

- https://issues.jboss.org/browse/WFLY-12499
- https://issues.jboss.org/browse/WFLY-12501
- https://issues.jboss.org/browse/WFLY-12502

### CODE REVIEW

**Review by bstansberry — CHANGES_REQUESTED** [review]
@jamezp I don't want new modules, definitely not 'jakarta.xxx' ones. These modules provide code in particular packages, and those packages are javax.xxx not 'jakarta.xxx'.  There's no need to change their names just because the source of an included resource has changed. Even org.glassfish.javax->org.glassfish.jakarta would require a fair bit of convincing.

When we need to deal with Jakarta EE 9 and there's a ton of package renaming we will probably need new modules. But if we introduce them now, when we have no strong plan for how we'll deal with EE 9, we'll have added complexity to our current life and may have closed off ways to deal with supporting both EE 8 and EE 9 by burning module names.

**Comment by jamezp** [comment]
@bstansberry Okay no problem. I'll revert that part. I saw that EL created a new module and I should have just asked rather than assuming :)

**Comment by bstansberry** [comment]
@jamezp what is the EL change you are referring to?

**Comment by jamezp** [comment]
Ah I see. It's just the implementation module that changes from `org.glassfish.javax.el` to `org.glassfish.jakarta.el`. Do we want the implementation modules renamed?

**Comment by jamezp** [comment]
The branch for the revert is: https://github.com/wildfly/wildfly/compare/master...jamezp:WFLY-12501-WFLY-12502-revert?expand=1

A PR can be opened for this once https://github.com/wildfly/wildfly-core/pull/3947 is done and a core upgrade is merged.

**Comment by bstansberry** [comment]
@jamezp Can you add a commit adding the no-longer wanted GAs to the maven-enforcer-plugin ban-bad-dependencies execution in the root pom?

That will result in a failure if any of our deps are pulling that in without us having added an exclude in dependencyManagement.

I don't think that needs to be part of the commits we plan to revert as banning the deps in full is valid even though the versions we want will come in via core.

What's here LGTM. I think the org.glassfish.jakarta is ok. Not my favorite but I don't have a good argument and we've already done it for el.

**Review by bstansberry — APPROVED** [review]
Ignore my last request; it's easier to do that in a batch once these are all in.

**Pull request merged**
