### PR TITLE
WFLY-8335 - User should be informed when switching between JDBC and journal store in transactions subsystem

### PR DESCRIPTION
**Pull request by rpelisse**
Issue: [JBEAP-6449](https://issues.jboss.org/browse/JBEAP-6449)
Upstream Issue: [WFLY-8335](https://issues.jboss.org/browse/WFLY-8335)

This PR superseeds [PR 9772](https://github.com/wildfly/wildfly/pull/9772).

Following tips from @claudio4j I've used the setAlternatives to enforce the proper behavior / validation. Below is the new CLI behavior:

```
[standalone@localhost:9990 /] /subsystem=transactions:write-attribute(name=use-journal-store, value=true)
{
    "outcome" => "success",
    "response-headers" => {
        "operation-requires-restart" => true,
        "process-state" => "restart-required"
    }
}
[standalone@localhost:9990 /] /subsystem=transactions:write-attribute(name=use-jdbc-store, value=true)
{
    "outcome" => "failed",
    "failure-description" => "WFLYTX0032: jdbc-store-datasource must be defined if use-jdbc-store is 'true'.",
    "rolled-back" => true,
    "response-headers" => {"process-state" => "restart-required"}
}
[standalone@localhost:9990 /] /subsystem=transactions:write-attribute(name=jdbc-st, value=true)
jdbc-state-store-drop-table  jdbc-state-store-table-prefix  jdbc-store-datasource  
[standalone@localhost:9990 /] /subsystem=transactions:write-attribute(name=jdbc-store-datasource, value=java:jboss/datasources/ExampleDS)
{
    "outcome" => "success",
    "response-headers" => {
        "operation-requires-restart" => true,
        "process-state" => "restart-required"
    }
}
[standalone@localhost:9990 /] /subsystem=transactions:write-attribute(name=use-jdbc-store, value=true)
{
    "outcome" => "failed",
    "failure-description" => "WFLYCTL0105: use-journal-store is invalid in combination with use-jdbc-store",
    "rolled-back" => true,
    "response-headers" => {"process-state" => "restart-required"}
}

```
@tomjenkinson I think this answer your requirements of having the a warning if the jdbc-store is not defined.

@rhusar no longer any need for i18n 

I hope this PR is "ready to go", but of course, any feedbacks for enhacement are welcomed.

PS: I meant to update PR 9772 rather than close it, but a bad push on my part closed it. Sorry about that.

### CODE REVIEW

**Comment by rpelisse** [comment]
test again please

**Comment by rpelisse** [comment]
retest this please

**Comment by rpelisse** [comment]
retest this please

**Comment by kabir** [comment]
Needs a downstream PR to to get considered atm

**Comment by rpelisse** [comment]
@kabir OK I was waiting for this to be accepted to make the downstream PR :) ! So I'll make the downstream PR tomorrow.

**Comment by rpelisse** [comment]
retest this please

**Comment by rpelisse** [comment]
@kabir here the downpstream [PR 1509](https://github.com/jbossas/jboss-eap7/pull/1509)

**Comment by kabir** [comment]
The test failures seem valid

**Comment by rpelisse** [comment]
@kabir right, I did not see that (it fails so often, I just assumed it was random errors):

```
"org.jboss.as.test.manualmode.transaction.ObjectStoreTypeTestCase.testJdbcObjectStore: java.lang.AssertionError: Failed to execute line '/subsystem=transactions:write-attribute(name=use-journal-store, value=false)': org.jboss.as.cli.CommandLineException: {
    "outcome" => "failed",
    "failure-description" => "WFLYCTL0105: use-journal-store is invalid in combination with use-jdbc-store",
    "rolled-back" => true,
    "response-headers" => {"process-state" => "restart-required"}
}
	at org.jboss.as.test.integration.management.util.CLIWrapper.sendLine(CLIWrapper.java:166)
	at org.jboss.as.test.integration.management.util.CLIWrapper.sendLine(CLIWrapper.java:188)
	at org.jboss.as.test.manualmode.transaction.ObjectStoreTypeTestCase.setDefaultObjectStore(ObjectStoreTypeTestCase.java:282)
	at org.jboss.as.test.manualmode.transaction.ObjectStoreTypeTestCase.testJdbcObjectStore(ObjectStoreTypeTestCase.java:137)
------- Stdout: -------"
```

I'll take a look and see if I can't update the test accordingly.

**Comment by rpelisse** [comment]
retest this please

**Pull request closed without merging**
