### PR TITLE
WFLY-15077 ProtoStream marshaller throws StackOverflowError if an object references itself

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-15077

### CODE REVIEW

**Comment by pferraro** [comment]
@rhusar Please review

**Comment by bstansberry** [comment]
@rhusar Is that thumbs up an approval or acknowledging the request to review?

**Comment by rhusar** [comment]
@bstansberry Haha, that's a thumbs up only acknowledging the request to review, but will finish the review shortly.

**Review by rhusar — APPROVED** [review]
LGTM!

**Pull request merged**
