### PR TITLE
[WFLY-11828]: Bump messaging schema version to 7.0

### PR DESCRIPTION
**Pull request by ehsavoie**
Bumping version to 7.0

Jira: https://issues.jboss.org/browse/WFLY-11828

### CODE REVIEW

**Comment by kabir** [comment]
@ehsavoie adding the hold label for the same reason as mentioned on https://github.com/wildfly/wildfly/pull/12145. It is fine to keep this in a PR so it is 'ready' but the commit should be pulled into a PR that changes the model.

**Comment by darranl** [comment]
As multiple engineers could submit PRs making use of this version bump the version bump commit needs to retain it's SHA which is 'c25e0614dd376be56e862774f5b128f959b58d18'

**Review by jamezp — APPROVED** [review]

**Comment by jamezp** [comment]
This needs to get in as #11918 changed the model and we somehow missed the version bump there.

**Comment by darranl** [comment]
The flow on these subsystem bumps where multiple engineers work on the bumped version needs to be: -

1. Create a topic branch for the bump and share it somewhere (PR with Hold label is fine)
2. All engineers fork the first branch and add their changes but NEVER rebase.

If a sync with upstream is required use git merge to avoid breaking the history.

**Comment by ehsavoie** [comment]
@darranl i agree, except that a feature that changed the model was merged without the proper bump in it.

**Pull request merged**
