### PR TITLE
Fix attribute registration of JPA providers

### PR DESCRIPTION
**Pull request by ctomc**
This allows us to remove https://github.com/wildfly/wildfly-core/commit/f65bfc8eaf9af2c082f2277a6f17fb0da01907b3

### CODE REVIEW

**Comment by bstansberry** [comment]
@scottmarlow please approve/disapprove. Looks ok to me.

**Comment by scottmarlow** [comment]
I assume that this is targeted at WF10, like we talked about on hipchat?  After we merge the jipijapa project source back into wildfly, Hibernate (JPA) deployments should be the only persistence provider that show up in the management console (others could be added in theory, so best to remove the capability for multiple providers in the console).

**Comment by scottmarlow** [comment]
Ahh, Tomaz did ask if we could "hardcode only one provider there for now?"  For the call to ManagementAdaptor#getIdentificationLabel().

**Comment by scottmarlow** [comment]
I'll try building this pr locally and deploy a test app and then check cli/console.

**Comment by scottmarlow** [comment]
JPA looks good in the console runtime deployment.  PR is approved @bstansberry :)

**Comment by ctomc** [comment]
@scottmarlow I later found out that I don't need to hardcode anything, just add the missing attribute registration. so yeah I hope this gets into 9, as it blocks some cleanup in core.

**Pull request merged**
