### PR TITLE
[WFLY-5739]  Subject not populated with groups/roles when authenticated via JASPIC

### PR DESCRIPTION
**Pull request by stoty**
This copies the Role information from JbossSecurityContext to the subject's ROLES_IDENTIFIER principal during authentication, so that JACC also sees the roles.

Fixes the errors in the jacc-propagation module of the jaspic test suite at
https://github.com/javaee-samples/javaee7-samples/tree/master/jaspic ,
as well as the test case attached in ticket

### CODE REVIEW

**Comment by ggam** [comment]
I've tested it locally and works correctly. Running Arjan Tijms JASPIC tests (http://arjan-tijms.omnifaces.org/2016/06/the-state-of-portable-authentication-in.html) against this WF branch gives all sucessful results except for the two JSF tests, that are likely a Mojarra's bug.

Would be great to have this in 10.1

**Comment by stoty** [comment]
I provide this patch under the terms of the MIT license. 
http://www.opensource.org/licenses/mit-license.php

**Comment by bstansberry** [comment]
Thanks. No need to mention the MIT license going forward; we just need to check once.

**Comment by bstansberry** [comment]
I put a 10.x label on this so it stays visible in filtered queries of open pull requests as we finalize work on the release. But it's up to @stuartwdouglas or @n1hility whether it can go in.

**Comment by bstansberry** [comment]
@darranl FYI

**Comment by sguilhen** [comment]
This looks ok to me.

**Comment by bstansberry** [comment]
Thanks @stoty! If you'd like, if you mail me your JIRA id I'd be happy to assign this and WFLY-6579 to you so JIRA gives you credit for the fixes.

**Pull request merged**
