### PR TITLE
WFLY-4467, WFLY-4468 Remove support for mixed-domain transforming to < 7.3.0 versions

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-4467
https://issues.jboss.org/browse/WFLY-4468

These are sub-tasks covering JGroups and Infinispan subsystems as part of https://issues.jboss.org/browse/WFLY-3564

### CODE REVIEW

**Comment by rhusar** [comment]
I guess these can be also removed from org.jboss.as.subsystem.test.KnownVersions class.

**Comment by ctomc** [comment]
@rhusar all this transformers tests are already ignored and don't get run, based on what is in KnownVersions. they will be removed after *all* subsystems stop using it.

**Comment by rhusar** [comment]
@pferraro btw this needs a rebase now.

**Comment by pferraro** [comment]
Anything in particular preventing this from being merged?

**Pull request merged**
