### PR TITLE
[WFLY-13054] : Upgrade of jackson databind to 2.10.3 ...

### PR DESCRIPTION
**Pull request by panossot**
[WFLY-13054] : https://issues.redhat.com/projects/WFLY/issues/WFLY-13054

### CODE REVIEW

**Comment by jmesnil** [comment]
@panossot could you please amend the commit message to reference https://issues.redhat.com/browse/WFLY-13054?

**Comment by bstansberry** [comment]
@asoldano @ronsigal @pferraro is this ok for RESTEasy and OpenAPI?

**Comment by ronsigal** [comment]
I'm running the RESTEasy testsuite right now.

The versions of all of the com.fasterxml.jackson.core modules are set by 
${version.com.fasterxml.jackson}, so you're saying all of them will be 
upgraded, right?

**Comment by bstansberry** [comment]
@ronsigal Yes; this will affect everything using that property.

**Comment by ronsigal** [comment]
Ok, just checking.

**Comment by ronsigal** [comment]
RESTEasy testsuite passes.

**Comment by pferraro** [comment]
@bstansberry This is OK for MP OpenAPI.

**Pull request merged**
