### PR TITLE
Hibernate stack updates:  microfixes

### PR DESCRIPTION
**Pull request by Sanne**
https://issues.jboss.org/browse/WFLY-10460

Individual changelogs:

 - https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HSEARCH%20AND%20fixVersion%20%3D%205.10.1.Final
 - https://hibernate.atlassian.net/issues/?jql=project%20%3D%20HHH%20AND%20fixVersion%20%3D%205.3.1
 - https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.8.12

### CODE REVIEW

**Comment by Sanne** [comment]
@kabir @scottmarlow : ready from our POV.

Thanks!

**Comment by psakar** [comment]
@Sanne @kabir  Given you are deleting license file "gnu lesser general public license v2.1 only.txt",
have you checked that no other project consumed by feature pack is using this license ?
I can see many other projects referencing it.
Would it be possible to inform prod teda license changes, so we can update our internal database, otherwise the information would be wrong in maven repository license file ?

**Comment by kabir** [comment]
@psakar @Sanne +1 we should not remove the "gnu lesser general public license v2.1 only.txt" file, I see it being used in the resulting wildfly-13/docs/licenses/licenses.html at least

**Comment by Sanne** [comment]
thanks @kabir and @psakar !

Sorry, I removed that as I couldn't find other references to it. Certainly no problem to remove that commit - I kept it separate for this reason.

**Comment by scottmarlow** [comment]
+1 on these component upgrades

**Pull request merged**
