### PR TITLE
[WFLY-2492] <valid-connection-checker> does not have module attribute

### PR DESCRIPTION
**Pull request by gaol**
Jira: https://issues.jboss.org/browse/WFLY-2492

This feature adds the capability to load customized JCA extension classes from their own JBoss module.

Both `module` and `module-slot` attributes are added for all `extensionType` defined in new XSD: `wildfly-resource-adapters_4_0.xsd` and `wildfly-datasources_4_0.xsd`.

### CODE REVIEW

**Comment by jesperpedersen** [comment]
The transformers for `:resource-adapters:` and `:datasources:` needs to be reject transformers, as we can' t guarantee the functionality otherwise.

Otherwise looks good.

**Comment by gaol** [comment]
@jesperpedersen could you please check whether the reject transformers are correct at: https://github.com/gaol/wildfly/commit/42d87cb98146032caeb4054fd5ad1a156c2df24e

**Comment by jesperpedersen** [comment]
@gaol Yup, try that -- squash and rebase. @maeste needs to make sure that there are no other cases that you need to cover

**Comment by gaol** [comment]
Done of squash and rebase. Could @jesperpedersen and @maeste check it again? Thank you ! :-)

**Comment by jesperpedersen** [comment]
@gaol I think we are ready for a test run followed by a review

Could one of the admins approve for test run ?

**Comment by jesperpedersen** [comment]
@stuartwdouglas Stuart, could you give this one a poke ? TIA

**Comment by n1hility** [comment]
this is ok to test

**Comment by gaol** [comment]
All tests are passed, could someone please check it when you get any time? Thank you. :-)

**Comment by n1hility** [comment]
Why is this defining a custom aggregate class loader? All that should be needed is the ability to pass a classloader (which is the module's class loader) to IJ (or alternatively a module name if it wants to directly link against jboss modules) for each of these custom classes

**Comment by jesperpedersen** [comment]
Its multiple of modules linked together with the IronJacamar + org.jboss.as.connector modules

**Comment by jesperpedersen** [comment]
Ala
```
 <connection-listener class-name="xyz" module="com.acme.ourapp"/>
```

**Comment by n1hility** [comment]
The problem is that violates the whole point of modularity and creates a mini-big-ball of mud. The bit of code that does classloader.loadClass() should accept an arbitrary classloader instance and that instance should be the module that contains the class loaded

**Comment by jesperpedersen** [comment]
Each deployment may need different modules depending on configuration, and they need visibility within the activation. As there are multiple extension points these need to be connected somehow, which this PR does

**Comment by n1hility** [comment]
If my code does <connection-listener class-name="xyz" module="com.acme.ourapp"/> I shouldn't get an xyz defined by some other random module.

**Comment by jesperpedersen** [comment]
Hence the optional 'module' attribute. Let @bstansberry look it over, as he requested it for WFLY 10.

**Comment by n1hility** [comment]
But i did specify I module. I said load "xyz" from com.acme.ouapp", and thats not what is going to happen its going to load it from any number of places.

**Comment by n1hility** [comment]
At some point the data source system needs to stop being a big pile of ugly hacks.

**Comment by n1hility** [comment]
What I mean is I totally understand reality, and sometimes we need to merge a hack to get the job done, but that can't last forever. Where do we draw the line?

**Comment by gaol** [comment]
@n1hility Hi, my initial idea was trying to call `ModuleSpecification.addSystemDependency` like what RarDependencyProcessor[1] does in `Phase.DEPENDENCIES` for a `data-source` deployment.

But a `data-source` is deployed when the resource definition in data-source subsystem is parsed[2][3], it is not a WildFly `DeploymentUnit`, so this way does not work for data-source.

It seems there is no way to re-compose a `Module` in the `AbstractDataSourceService` too, as the system modules: `org.jboss.ironjacamar.*` have been loaded already in this case, we can't change the class-loading anymore after the module has been loaded, right?

And let the system modules depend on user defined modules are always wrong.

So there are 2 options left I think:
- Create a dynamic module for a `data-source`, link the module dependencies to current caller module and other extension modules which this feature requires.

> The only purpose of this created dynamic module is to use the ModuleClassLoader of this module. And we need to consider the removal of the module on the data-source removal.

- Create an aggregated class loader to delegate class loading to current class loader(the current caller module class loader) and module class loaders defined in each extensions. This is the one I adopted in this PR.

The aggregated class loader([LinkedClassLoader.java](https://github.com/gaol/wildfly/blob/WFLY-2492V4/connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/LinkedClassLoader.java)) in this PR delegates class loading to other ModuleClassLoaders, for each concrete class, it's class loader is the ModuleClassLoader that defines the module, not other arbitrary class loaders. Maybe I can change it a bit to allow only ModuleClassLoader to be delegated if it is a reason. :-)

[1] https://github.com/wildfly/wildfly/blob/master/connector/src/main/java/org/jboss/as/connector/deployers/ra/processors/RarDependencyProcessor.java#L75

[2] https://github.com/wildfly/wildfly/blob/master/connector/src/main/java/org/jboss/as/connector/subsystems/datasources/AbstractDataSourceAdd.java#L116
[3] https://github.com/wildfly/wildfly/blob/master/connector/src/main/java/org/jboss/as/connector/subsystems/datasources/AbstractDataSourceService.java#L146

**Comment by gaol** [comment]
Changed the aggregated class-loader so that it delegates class loading to ModuleClassLoader only. Rebased.

Could you please check it again?

If it still not acceptable, could you please give me some instructions on how to avoid violating the modularity to implement this feature? Thank you. :-)

**Comment by stuartwdouglas** [comment]
We should not need an aggregate class loader at all. In the config a class name and a module name have been specified, you should be just looking up that module, getting its class loader, and then loading the class with it.

**Comment by gaol** [comment]
Postponed, needs IJ changes first.

**Pull request closed without merging**
