### PR TITLE
[WFLY-14169] Remove the wildfly-ee feature pack dependency on wildfly…

### PR DESCRIPTION
**Pull request by bstansberry**
…-servlet

https://issues.redhat.com/browse/WFLY-14169

### CODE REVIEW

**Review by yersan — COMMENTED** [review]
Hello @bstansberry , for your info, I've just done a review doing a configuration comparison between master and master+these changes and I've found notable differences mainly in the domain configurations. I'm not sure yet about the exact reason of these differences.

**Comment by bstansberry** [comment]
Thank you for doing that @yersan!

**Comment by bstansberry** [comment]
What I see is a diff in the host.xml and host-slave.xml files in the installations produced in the 'build' dir.  (Plus a lot of license file differences which are expected, although maybe I need some smart idea to avoid that.)

The ee-9/build and build-legacy installations seem ok.

```

diff -ruw build/target/wildfly-22.0.0.Beta1-SNAPSHOT/domain/configuration/host-slave.xml ../wf2/wildfly/build/target/wildfly-22.0.0.Beta1-SNAPSHOT/domain/configuration/host-slave.xml
--- build/target/wildfly-22.0.0.Beta1-SNAPSHOT/domain/configuration/host-slave.xml	2020-12-10 15:39:31.000000000 -0600
+++ ../wf2/wildfly/build/target/wildfly-22.0.0.Beta1-SNAPSHOT/domain/configuration/host-slave.xml	2020-12-10 17:20:43.000000000 -0600
@@ -75,6 +75,9 @@
         <interface name="public">
             <inet-address value="${jboss.bind.address:127.0.0.1}"/>
         </interface>
+        <interface name="unsecure">
+            <inet-address value="${jboss.bind.address.unsecure:127.0.0.1}"/>
+        </interface>
     </interfaces>
     <jvms>
         <jvm name="default">
diff -ruw build/target/wildfly-22.0.0.Beta1-SNAPSHOT/domain/configuration/host.xml ../wf2/wildfly/build/target/wildfly-22.0.0.Beta1-SNAPSHOT/domain/configuration/host.xml
--- build/target/wildfly-22.0.0.Beta1-SNAPSHOT/domain/configuration/host.xml	2020-12-10 15:39:30.000000000 -0600
+++ ../wf2/wildfly/build/target/wildfly-22.0.0.Beta1-SNAPSHOT/domain/configuration/host.xml	2020-12-10 17:20:42.000000000 -0600
@@ -68,6 +68,9 @@
         <interface name="public">
             <inet-address value="${jboss.bind.address:127.0.0.1}"/>
         </interface>
+        <interface name="unsecure">
+            <inet-address value="${jboss.bind.address.unsecure:127.0.0.1}"/>
+        </interface>
     </interfaces>
     <jvms>
         <jvm name="default">
```

Also

Only in ../wf2/wildfly/build/target/wildfly-22.0.0.Beta1-SNAPSHOT/modules/system/layers/base/org/jboss/as/product: wildfly-core

**Comment by yersan** [comment]
@bstansberry check not only the build/dist variants but also the ee-dist / ee-build. I confirm I get the same you described for dist/build but for the ee-variants also the domain.xml file is affected.

**Comment by bstansberry** [comment]
Thanks; I looked at build, build-legacy, ee-9/build and forgot 'ee-build'!

**Comment by bstansberry** [comment]
I'm going to close this because I want to do WFLY-14170 in the same PR.

**Pull request closed without merging**
