### PR TITLE
[WFLY-6579] When JASPIC's register session is used, Subject not propa…

### PR DESCRIPTION
**Pull request by stoty**
…gated to EJB

This implements the fix suggested by the Arjan Tims in WFLY-6579.

It fixes the errors in the register-sessions module of the jaspic test suite at
https://github.com/javaee-samples/javaee7-samples/tree/master/jaspic

### CODE REVIEW

**Comment by arjantijms** [comment]
Thanks for doing this PR @stoty 

I've been testing the change on which the PR is based privately for quite some time now and found no issues yet.

**Comment by bstansberry** [comment]
@stuartwdouglas is this ok for 10.1?

@stoty We require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to the these terms?

**Comment by bstansberry** [comment]
I've put 10.x on it for now so it stays on the radar in filtered PR queries; change to 11.x if desired.

**Comment by stoty** [comment]
@bstansberry Yes, I do agree to the terms of MIT license.

**Pull request merged**
