### PR TITLE
[WFLY-14077] Some tests hang indefinitely when using security manager…

### PR DESCRIPTION
**Pull request by spyrkob**
JIRA: https://issues.redhat.com/browse/WFLY-14077

### CODE REVIEW

**Review by darranl — CHANGES_REQUESTED** [review]
Please add a complete stack trace somewhere of the failure that leads to this permission being required.

This does not look like a permission we would expect end users to be needing to grant to their deployment.

**Comment by spyrkob** [comment]
@darranl I attached the stacktrace to WFLY-14077

**Comment by bstansberry** [comment]
@spyrkob This does not look like a missing deployment permission. It looks like a JBoss Marshalling bug where it cannot initialize internal classes. The Protocol class has a static field of type Unsafe which results in failure to initialize if deployment classes are on the stack.

@ropalka FYI.

**Comment by ropalka** [comment]
Did you see testsuite/integration/iiop/src/test/java/org/jboss/as/test/iiop/security/IIOPSecurityInvocationTestCase.java @spyrkob how to add missing / additional permissions?

**Comment by spyrkob** [comment]
@ropalka yes I followed that for this PR, but it sounds like this is not the way to go if I understand @bstansberry's comment right. 
Should I close this PR and open a bug in Marshalling?

**Comment by ropalka** [comment]
Aha, I see. I didn't have a look to your PR proposal.

**Comment by ropalka** [comment]
How could I reproduce the problem @spyrkob ? I'm running: 
---

cd wildfly/testsuite/integration/manualmode
mvn clean  test -Dtest=**/seccontext/*TestCase -DallTests -Dsecurity.manager=true

---

but no luck

**Comment by spyrkob** [comment]
@ropalka are you using Java 11? 

I'm getting failures for example on `mvn clean test -Dtest=AuthenticationForwardingSFSFTestCase#testServletBasicToEjbForwardedIdentity -DallTests -Dsecurity.manager`

**Comment by ropalka** [comment]
@spyrkob you can close this PR - I have a proper marshalling fix ready

**Comment by spyrkob** [comment]
Thanks @ropalka

**Pull request closed without merging**
