### PR TITLE
[WFLY-10237] Upgrade HAL to 3.0.0.Alpha3

### PR DESCRIPTION
**Pull request by hpehl**
https://issues.jboss.org/browse/WFLY-10237

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by stuartwdouglas** [comment]
Failure looks related:


[15:43:42][Step 2/3] Surefire report watcher
[15:43:42][Step 2/3] [INFO] Downloading: http://repository.ci.wildfly.org/content/groups/public/org/jboss/hal/hal-console/3.0.0.Alpha3/hal-console-3.0.0.Alpha3.pom
[15:43:44][Step 2/3] [INFO] Downloading: http://repository.jboss.org/nexus/content/groups/public/org/jboss/hal/hal-console/3.0.0.Alpha3/hal-console-3.0.0.Alpha3.pom
[15:43:44][Step 2/3] [INFO] Downloading: https://repo.maven.apache.org/maven2/org/jboss/hal/hal-console/3.0.0.Alpha3/hal-console-3.0.0.Alpha3.pom
[15:43:44][Step 2/3] [WARNING] The POM for org.jboss.hal:hal-console:jar:resources:3.0.0.Alpha3 is missing, no dependency information available
[15:43:44][Step 2/3] [INFO] Downloading: http://repository.ci.wildfly.org/content/groups/public/org/jboss/hal/hal-console/3.0.0.Alpha3/hal-console-3.0.0.Alpha3-resources.jar
[15:43:44][Step 2/3] [INFO] Downloading: http://repository.jboss.org/nexus/content/groups/public/org/jboss/hal/hal-console/3.0.0.Alpha3/hal-console-3.0.0.Alpha3-resources.jar
[15:43:44][Step 2/3] [INFO] Downloading: https://repo.maven.apache.org/maven2/org/jboss/hal/hal-console/3.0.0.Alpha3/hal-console-3.0.0.Alpha3-resources.jar
[15:43:44][Step 2/3] Failed to execute goal on project wildfly-feature-pack: Could not resolve dependencies for project org.wildfly:wildfly-feature-pack:pom:13.0.0.Alpha1-SNAPSHOT: Could not find artifact org.jboss.hal:hal-console:jar:resources:3.0.0.Alpha3 in brontes-mirror (http://repository.ci.wildfly.org/content/groups/public/)
[15:43:44][Step 2/3] [INFO]                                                                         
[15:43:44][Step 2/3] [INFO] --------------------------

**Comment by kabir** [comment]
@hpehl did you forget to deploy it?

**Comment by hpehl** [comment]
@kabir I need to check...

**Comment by hpehl** [comment]
I deployed to the wrong repository. Artefacts should now be in https://repository.jboss.org/nexus/

**Comment by hpehl** [comment]
Retest this please

**Comment by hpehl** [comment]
I need to adjust tests in `org.jboss.as.test.integration.management.console`

**Comment by hpehl** [comment]
Retest this please

**Comment by hpehl** [comment]
The test which still fails is `org.jboss.as.test.integration.jca.metrics.DataSourceCfgMetricUnitTestCase.testStatistics` and seems not related to the console upgrade.

**Pull request merged**
