### PR TITLE
[WFLY-13984] Upgrade IronJacamar to 1.4.24.Final

### PR DESCRIPTION
**Pull request by tadamski**
https://issues.redhat.com/browse/WFLY-13984

This issue add the Jakarta EE connector 2.0 parsing:
https://issues.redhat.com/browse/WFLY-13964

### CODE REVIEW

**Comment by bstansberry** [comment]
@tadamski CI is failing because it looks like the release is not available in nexus.

**Comment by tadamski** [comment]
@bstansberry I forgot to click the release; retest this please

**Comment by tadamski** [comment]
failing test seems unrelated - I can't reproduce it

**Comment by bstansberry** [comment]
@tadamski I filed https://issues.redhat.com/browse/WFLY-13990

**Comment by bstansberry** [comment]
Thanks, @tadamski !

**Pull request merged**
