### PR TITLE
WFLY-17495 - Update `resteasy-spring` to `3.0.1.Final`

### PR DESCRIPTION
**Pull request by liweinan**

### CODE REVIEW

**Comment by liweinan** [comment]
A prerequisite of this PR is to update `resteasy` to `6.2.2.Final`. @jamezp If you need me to do the RESTEasy update pls let me know.

**Comment by liweinan** [comment]
Ah okay I found this PR is already created: https://github.com/wildfly/wildfly/pull/16372

@jamezp Thanks for the work on this!

**Comment by jamezp** [comment]
> A prerequisite of this PR is to update `resteasy` to `6.2.2.Final`. @jamezp If you need me to do the RESTEasy update pls let me know.

There is a PR for that already https://github.com/wildfly/wildfly/pull/16372. However, I don't understand why that would be a prerequisite.

**Comment by liweinan** [comment]
> > A prerequisite of this PR is to update `resteasy` to `6.2.2.Final`. @jamezp If you need me to do the RESTEasy update pls let me know.
> 
> There is a PR for that already #16372. However, I don't understand why that would be a prerequisite.

The `resteasy-spring 3.0.1.Final` adopts `resteasy 6.2.2.Final`.

**Comment by jamezp** [comment]
> > > A prerequisite of this PR is to update `resteasy` to `6.2.2.Final`. @jamezp If you need me to do the RESTEasy update pls let me know.
> > 
> > 
> > There is a PR for that already #16372. However, I don't understand why that would be a prerequisite.
> 
> The `resteasy-spring 3.0.1.Final` adopts `resteasy 6.2.2.Final`.

That shouldn't block this IMO as it should work work with any 6.2.x version.

**Review by jamezp — APPROVED** [review]

**Pull request merged**
