### PR TITLE
WFLY-17327 Upgrade JGroups to 5.2.10.Final

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-17327

### CODE REVIEW

**Review by rhusar — CHANGES_REQUESTED** [review]
No! 

This version of jgroups has yet again broken JDK20 compatibility.

```
11:38:12,843 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 90) MSC000001: Failed to start service org.wildfly.clustering.jgroups.channel.ee: org.jboss.msc.service.StartException in service org.wildfly.clustering.jgroups.channel.ee: java.lang.IllegalStateException: java.lang.IllegalArgumentException: failed initializing component ThreadPool in protocol UDP: java.lang.IllegalStateException: failed to create virtual thread pool: java.lang.UnsupportedOperationException: Preview Features not enabled, need to run with --enable-preview
	at org.wildfly.clustering.service@28.0.0.Beta1-SNAPSHOT//org.wildfly.clustering.service.FunctionalService.start(FunctionalService.java:66)
	at org.wildfly.clustering.service@28.0.0.Beta1-SNAPSHOT//org.wildfly.clustering.service.AsyncServiceConfigurator$AsyncService.lambda$start$0(AsyncServiceConfigurator.java:117)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:1591)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: java.lang.IllegalStateException: java.lang.IllegalArgumentException: failed initializing component ThreadPool in protocol UDP: java.lang.IllegalStateException: failed to create virtual thread pool: java.lang.UnsupportedOperationException: Preview Features not enabled, need to run with --enable-preview
	at org.jboss.as.clustering.jgroups@28.0.0.Beta1-SNAPSHOT//org.jboss.as.clustering.jgroups.subsystem.ChannelServiceConfigurator.get(ChannelServiceConfigurator.java:122)
	at org.jboss.as.clustering.jgroups@28.0.0.Beta1-SNAPSHOT//org.jboss.as.clustering.jgroups.subsystem.ChannelServiceConfigurator.get(ChannelServiceConfigurator.java:60)
	at org.wildfly.clustering.service@28.0.0.Beta1-SNAPSHOT//org.wildfly.clustering.service.FunctionalService.start(FunctionalService.java:63)
	... 7 more
Caused by: java.lang.IllegalArgumentException: failed initializing component ThreadPool in protocol UDP: java.lang.IllegalStateException: failed to create virtual thread pool: java.lang.UnsupportedOperationException: Preview Features not enabled, need to run with --enable-preview
	at org.jgroups@5.2.10.Final//org.jgroups.stack.ProtocolStack.lambda$initComponents$7(ProtocolStack.java:861)
	at org.jgroups@5.2.10.Final//org.jgroups.util.Util.forAllComponents(Util.java:3368)
	at org.jgroups@5.2.10.Final//org.jgroups.stack.ProtocolStack.initComponents(ProtocolStack.java:839)
	at org.jgroups@5.2.10.Final//org.jgroups.stack.ProtocolStack.initProtocolStack(ProtocolStack.java:795)
	at org.jgroups@5.2.10.Final//org.jgroups.stack.ProtocolStack.initProtocolStack(ProtocolStack.java:781)
	at org.jgroups@5.2.10.Final//org.jgroups.stack.ProtocolStack.init(ProtocolStack.java:777)
	at org.jgroups@5.2.10.Final//org.jgroups.JChannel.<init>(JChannel.java:155)
	at org.jboss.as.clustering.jgroups@28.0.0.Beta1-SNAPSHOT//org.jboss.as.clustering.jgroups.JChannelFactory.createChannel(JChannelFactory.java:118)
	at org.jboss.as.clustering.jgroups@28.0.0.Beta1-SNAPSHOT//org.jboss.as.clustering.jgroups.subsystem.ChannelServiceConfigurator.get(ChannelServiceConfigurator.java:98)
	... 9 more
```

**Comment by rhusar** [comment]
That is caused by https://issues.redhat.com/browse/JGRP-2660

**Comment by pferraro** [comment]
Thanks @rhusar . I filed https://issues.redhat.com/browse/JGRP-2665.

**Comment by rhusar** [comment]
Looking at the Jira, lets try with 'TP.use_virtual_threads="false"'

**Comment by rhusar** [comment]
@pferraro Ran a quick test with

`/subsystem=jgroups/stack=udp/transport=UDP:map-put(name=properties,key=use_virtual_threads,value=false)`

and it does the trick.

**Pull request merged**
