### PR TITLE
[26.x][WFLY-16829] Upgrade Apache cxf to 3.4.8

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFLY-16829

Upstream 
1. https://github.com/wildfly/wildfly/pull/15467 (3.5.2)
2. https://github.com/wildfly/wildfly/commit/61c1db90ddacf1faf3978dc9fcd8ff4400be5bde#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8 (3.5.2-jbossorg)
3. https://github.com/wildfly/wildfly/commit/78d2a0fbaec760e8b946b3c505a95015ff1348d1 (3.5.2-jbossorg-1)

### CODE REVIEW

**Comment by boris-unckel** [comment]
Please find all links to release notes, git tags, github-diff in the Jira.

**Comment by jimma** [comment]
@boris-unckel  Thanks for the PR, again!  I'll look at the tck result before this upgrade. Can you please give me some time to have a tck check locally for this version ?

**Comment by boris-unckel** [comment]
@jimma It seems there is a deadline for WF26x: https://github.com/wildfly/wildfly/pull/15962#issuecomment-1223382011

**Comment by bstansberry** [comment]
It is unlikely we'd include this one in 26.1.2. A CXF upgrade is a pretty large thing to do at the last minute and the change log doesn't show anything particularly critical.

**Comment by boris-unckel** [comment]
@bstansberry I don't consider this one critical [CXF-7996 Jakarta EE TCKs and compatibility](https://issues.apache.org/jira/browse/CXF-7996) but there is a long list of fixes behind. They have been solved incremental (previous versions contain fixes, too) and the work has been finalized in this minor.

**Comment by jimma** [comment]
- @boris-unckel  I've gone through all the commits in CXF 3.4.8.  These two commits are we need to  have a fully tck test , especially the first one : 

- https://github.com/apache/cxf/commit/bb4d26f15b604b51c57a14194eb9af646ab10ff1 
- https://github.com/apache/cxf/commit/0d586e44d858a950e2dc92c141500f6acdf57c9c 

Except these two changes, there are all related to jaxrs change , component upgrade and test fix.

**Comment by bstansberry** [comment]
> * @boris-unckel  I've gone through all the commits in CXF 3.4.8.  These two commits are we need to  have a fully tck test , especially the first one :
> * [apache/cxf@bb4d26f](https://github.com/apache/cxf/commit/bb4d26f15b604b51c57a14194eb9af646ab10ff1)

This caused a regression, to be fixed in 3.4.9: 

https://issues.apache.org/jira/browse/CXF-8733

> * [apache/cxf@0d586e4](https://github.com/apache/cxf/commit/0d586e44d858a950e2dc92c141500f6acdf57c9c)
> 

This is an Improvement, not a bug fix.

https://issues.apache.org/jira/browse/CXF-8699

> Except these two changes, there are all related to jaxrs change , component upgrade and test fix.

**Comment by boris-unckel** [comment]
@jimma @bstansberry Thanks for time investigating this. It seems this has not enough benefit for the release. Even downstream I would wait for 3.4.9.

**Pull request closed without merging**
