### PR TITLE
WFLY-7544 @Startup @Singleton fails to invoke EJB via Remote interface in PostConstruct

### PR DESCRIPTION
**Pull request by kurobako**
https://issues.jboss.org/browse/WFLY-7544

### CODE REVIEW

**Comment by kurobako** [comment]
EJBClientDescriptorTestCase.testLocalAndRemoteReceiversClientConfig consistently works fine for me, but failed in the last Linux build. Might be a race (I wonder how, tho), I will look into details. Meanwhile...

**Comment by kurobako** [comment]
retest this please

**Comment by kurobako** [comment]
retest this please

**Comment by kurobako** [comment]
retest this please

**Comment by kurobako** [comment]
retest this please

**Comment by kurobako** [comment]
retest this please

**Comment by kurobako** [comment]
org.jboss.as.test.integration.domain.management.cli.DomainDeploymentOverlayTestCase.testSimpleOverrideWithRedeployAffected: org.jboss.as.cli.CommandLineException: The controller is not available at [::1]:9999 seems not quite related.
Anyway, I will dig into the details more and provide new info soon.

**Comment by kabir** [comment]
@kurobako we have some intermittent failures at the moment, although it should be better since Friday

**Comment by kabir** [comment]
Retest this please

**Comment by kabir** [comment]
@stuartwdouglas Please approve

**Comment by kurobako** [comment]
@kabir @stuartwdouglas I would like to note that DeploymentRepository modifications (widening the scope of synchronized block) are kinda experimental: without these this PR seems to cause previously dormant race to appear:
> org.jboss.as.test.integration.ejb.client.descriptor.EJBClientDescriptorTestCase.testLocalAndRemoteReceiversClientConfig: java.lang.IllegalStateException: EJBCLIENT000025: No EJB receiver available for handling [appName:, moduleName:ejb-client-descriptor-with-local-and-remote-receivers-test, distinctName:] combination for invocation context org.jboss.ejb.client.EJBClientInvocationContext@11ae8a4
I will continue investigating what exactly races with what and hopefully update this PR with more directed solution to the issue.

**Comment by kabir** [comment]
As noted in https://github.com/jbossas/jboss-eap7/pull/982 I think the EJBClientDescriptorTestCase failure is due to the intermittent failures introduced in https://github.com/jbossas/jboss-eap7/pull/968 last week, for which an upgrade https://github.com/jbossas/jboss-eap7/pull/968 fixing most of the intermittent failures was merged on Friday

**Comment by kurobako** [comment]
retest this please

**Comment by kabir** [comment]
@kurobako Stuart who would normally approve this is on PTO this week, and I am not familiar with this code. Can you explain a little bit how this fixes the problem, to help me merge it?

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
This will mean partially deployed EJB's will be exposed, which causes clustering problems. The partial deployment will be advertised as available to the cluster, and may start attempting to process requests even though it is not ready yet.

**Review by stuartwdouglas — APPROVED** [review]
Looks like I was wrong with my initial review, and this is actually correct.

**Comment by kurobako** [comment]
There are some elusive test failures on EAP6/7 counterparts of this PR, so let us consider this PR being on hold until we reasons become clear.

**Comment by gaol** [comment]
Any progress? :smiley:   @kurobako

**Comment by kurobako** [comment]
@gaol I think it is all clear now. Test failures in EAP were caused by unrelated issue which is fixed in wfly already.

**Pull request merged**
