### PR TITLE
WFLY-4695 Remove infinispan-query module and its dependencies

### PR DESCRIPTION
**Pull request by Sanne**
For @pferraro to review, although he's technically the patch author: I based on his work and reverted a section, as discussed on
- https://issues.jboss.org/browse/WFLY-4695

### CODE REVIEW

**Comment by rhusar** [comment]
Hi @Sanne, this needs a rebase.

**Comment by Sanne** [comment]
Ok, looks like I have to resolve conflicts with other changes of myself..

**Comment by Sanne** [comment]
Rebased it

**Comment by rhusar** [comment]
@Sanne ah, needs a rebase again :-(

**Comment by pferraro** [comment]
Obsoleted by https://github.com/wildfly/wildfly/pull/7739

**Pull request closed without merging**
