### PR TITLE
[WFLY-9946] Add the JSON-B implementation to deployments explicitly and remove the dependency from the API.

### PR DESCRIPTION
**Pull request by jamezp**
https://issues.jboss.org/browse/WFLY-9946

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Shouldn't the eclipse module just be added to the deployment via a DUP, rather than the API having an explicit dependency on it?

**Comment by jamezp** [comment]
Either way would really work. I thought we generally tried to only add the API module in the DUP, but I can change it in either place.

**Comment by stuartwdouglas** [comment]
In general we try and avoid exports, as it gives more flexibility. With exports in use like this we are tied to our implementation. If a dependency is added via a DUP you should be able to exclude our implementation and include a different one.

**Comment by jamezp** [comment]
That actually makes a lot of sense. I'll update the PR to explicitly add the implementation.

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
