### PR TITLE
[WFLY-15195] Missing dependency in jberet-core module

### PR DESCRIPTION
**Pull request by jycchoi**
Issue: https://issues.redhat.com/browse/WFLY-15195

### CODE REVIEW

**Comment by chengfang** [comment]
@jycchoi  thanks for the patch. I'll review it. I also added a comment to the jira https://issues.redhat.com/browse/WFLY-15195.

**Comment by darranl** [comment]
@chengfang was this one ready to review or are you asking for follow up changes?

**Comment by chengfang** [comment]
@jycchoi  can you respond to comment in https://issues.redhat.com/browse/WFLY-15195, if you think there is still a jberet bug?

**Comment by jycchoi** [comment]
@chengfang I am still making an independent test case to simulate the issue, however, so far the test case cannot trigger the issue as in the original program.  I will see if I have time to finish the test case in this week, or otherwise I will close the issue first until I have a repeatable test setup to proceed.

**Comment by jycchoi** [comment]
I will close the issue at this moment until I have a repeatable test setup prepared.

**Pull request closed without merging**
