### PR TITLE
WFLY-9601 upgrade version of checkstyle to latest

### PR DESCRIPTION
**Pull request by ctomc**
See discussion on https://issues.jboss.org/browse/JBEAP-13800

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Instead of making so many changes what about just dropping the RedundantModifiers check? I don't think it really buys us much in terms of code quality.

**Comment by bstansberry** [comment]
I saw we just eliminate whatever rule is leading to the need for this many changes.

**Comment by rpelisse** [comment]
I've done that locally when I started the discussion on WFLY-9601, so let me set up a PR for that.

(@ctomc see why I did NOT wanted to modify the private constructor before approval ;) )

**Comment by jmesnil** [comment]
I looked at the messaging-activemq subsystem. Some changes are OK (removing unused code), some are not (the RedundantModifiers check style).
We are in the process of upgrade Artemis in the subsystem with #10641 and I prefer to avoid having to rebase my long-running branch for cosmetic changes.

**Comment by rpelisse** [comment]
@jmesnil sorry, I forgot to add my PR to this thread: https://github.com/wildfly/wildfly/pull/10698

This version simply remove the RedundantModifiers rule and fix only the misplaced brackets.

**Pull request closed without merging**
