### PR TITLE
[WFLY-15609] added new http handler for transaction timeout cleanup

### PR DESCRIPTION
**Pull request by istudens**
Issue: https://issues.redhat.com/browse/WFLY-15609

### CODE REVIEW

**Comment by istudens** [comment]
@fl4via could you review this fix please? 
It brings a new dependency on `org.wildfly.transaction.client` module due to `ContextTransactionManager` usage. Tests are passing as well as the reproducer, but I am not completely sure about this new dependency and its potential influence. I have to mark it `optional` since it won't compile the `wildfly-servlet-galleon-pack` otherwise.

**Comment by darranl** [comment]
Should we really be adding further dependencies to the servlet feature pack?

As we work more with feature packs and layers this feels like the kind of handler that should be dynamically added based on the presence of other layers allowing the overall set of handlers in the resulting servlet container to be defined by the provisioned server.

**Comment by istudens** [comment]
@darranl Is there any example of such an approach you mentioned in WildFly which I can look at?

**Comment by xstefank** [comment]
retest this please

**Comment by xstefank** [comment]
@istudens @darranl @fl4via can you take a look at this, please? Getting stale.

**Comment by istudens** [comment]
I will open discussion regarding this issue.

**Comment by fl4via** [comment]
@istudens I am also unsure about the addition of a new dependency for this. I would go with this solution if it is the only way to do fix the bug.
Have you started discussion about this somewhere? I cannot find it?

**Pull request closed without merging**
