### PR TITLE
WFLY-16807 - Update `resteasy-spring` to `3.0.0.Final`

### PR DESCRIPTION
**Pull request by liweinan**
The `resteasy-spring` is moved from `preview-ee` back to `standard-ee`.

[WFLY-16807](https://issues.redhat.com/browse/WFLY-16807)

Tag: https://github.com/resteasy/resteasy-spring/releases/tag/3.0.0.Final
Diff: https://github.com/resteasy/resteasy-spring/compare/3.0.0.Beta2...3.0.0.Final

### CODE REVIEW

**Comment by jamezp** [comment]
I've placed a hold on this as a build of this server has errors when testing with https://github.com/resteasy/resteasy-spring/tree/main/testsuite/integration-tests-spring-web/deployment

**Comment by liweinan** [comment]
@jamezp I'll check the problem.

**Comment by liweinan** [comment]
After several days working with James, here is a possible solution: https://github.com/resteasy/resteasy-spring/pull/67/files

**Review by jamezp — APPROVED** [review]
Spring does not work with CDI. There are some new resources which are triggering CDI beans to be created and causing failures in in resteasy-spring's test suite. However, this is not an issue with resteasy-spring or WildFly. Some modules and subsystems just need to be exclude to work with Spring.

A review the docs written should be done by someone other then me. However, I'm approving the other parts.

**Comment by liweinan** [comment]
@jamezp Thanks for checking!

**Comment by bstansberry** [comment]
Thanks @liweinan

**Comment by liweinan** [comment]
relative PR for reference: https://github.com/resteasy/resteasy-spring/pull/71

**Pull request merged**
