### PR TITLE
Remove licenses for artifacts that are not part of final zip

### PR DESCRIPTION
**Pull request by rgdoliveira**

### CODE REVIEW

**Comment by rgdoliveira** [comment]
@bstansberry @jamezp if you can please review this one.

**Review by jamezp — APPROVED** [review]
This seems okay to me, but I'd like to get @scottmarlow and @jfdenise to review as well to make sure these aren't meant to end up in the final distribution.

**Comment by jfdenise** [comment]
@jamezp , the artifacts are not in the zip, +1 to remove them from the licenses.

**Review by jfdenise — APPROVED** [review]

**Review by bstansberry — APPROVED** [review]
Hibernate 5.3 is what goes in the dist; 5.1 is an option in the source that people can install themselves.

**Pull request merged**
