### PR TITLE
[WFLY-13279] Support for multiple security realms - Distributed Identities Community docs

### PR DESCRIPTION
**Pull request by nekdozjam**
https://issues.redhat.com/browse/WFLY-13279

### CODE REVIEW

**Comment by OndrejKotek** [comment]
@nekdozjam It could be useful to add a new section providing more context for this new realm, like in case of [failover-realm](https://github.com/wildfly/wildfly/pull/13045/files).

**Comment by darranl** [comment]
@nekdozjam Looks like we have a merge conflict in the docs, ping me if you unable to address and I will clean it up so we can get it in.

**Comment by nekdozjam** [comment]
@darranl should be up to date with master now

**Comment by bstansberry** [comment]
I cancelled CI as we need the CI capacity. Nothing tests docs changes. :)

**Comment by bstansberry** [comment]
@darranl or @fjuma Please approve.

**Review by fjuma — APPROVED** [review]

**Pull request merged**
