### PR TITLE
[WFLY-16766] Migrate the service used on the Extending WildFly documentation to the new MSC API

### PR DESCRIPTION
**Pull request by anilabhabaral**
Issue Link: https://issues.redhat.com/browse/WFLY-16766

### CODE REVIEW

**Review by bstansberry — CHANGES_REQUESTED** [review]
Hi @anilabhabaral 

The class declaration on L573 should be changed as well as org.jboss.msc.Service is not generic.

s/Service<TrackerService>/Service/g

**Comment by anilabhabaral** [comment]
Sure @bstansberry I will make the changes.

**Comment by anilabhabaral** [comment]
Hello @bstansberry i made the suggested changes. Could you please check ?

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @anilabhabaral

**Pull request merged**
