### PR TITLE
[WFLY-13273] Add tests for WFCORE-4860. The tests are required here a…

### PR DESCRIPTION
**Pull request by jamezp**
…s multiple deployments are required for testing.

https://issues.redhat.com/browse/WFLY-13273

Tests for https://github.com/wildfly/wildfly-core/pull/4112. This can be merged before as the tests should currently pass to prove the behavior is the same between the current implementation and the changed implementation.

### CODE REVIEW

**Comment by jamezp** [comment]
These failures seem legitimate. I'll try to reproduce locally.

**Comment by jamezp** [comment]
These failures are due to no EJB subsystem in the configs used. These will either need to be ignored or modified to either no use EJB's or know the subsystem is not present and ignore those missing messages.

**Review by bstansberry — APPROVED** [review]
The exclude was the right way to handle ts.layers.

Tests could check for system props ts.layers or ts.standalone.microprofile and if either is present behave differently, but I don't know if that's worth it. The logging subsystem is the same with all of these setups so there's not a lot of value in repeating the tests.

**Comment by bstansberry** [comment]
@jamezp If this can be merged the core-upgrade-needed label can be removed.

**Pull request merged**
