### PR TITLE
WFLY-6965 Audit @Ignore-d clustering integration tests

### PR DESCRIPTION
**Pull request by rhusar**
Unignores 3 test cases by fixing the test cases or removing no longer necessary ignores.

Jira
https://issues.jboss.org/browse/WFLY-6965

### CODE REVIEW

**Comment by rhusar** [comment]
^Unrelated failure.

**Comment by rhusar** [comment]
Removing workaround for StatefulFailoverTestCase#persistenceFailover since @mmusgrov is fixing WFLY-835 expected to reach WF shortly.

**Comment by rhusar** [comment]
Ready to go by my.

**Comment by mmusgrov** [comment]
@rhusar the PR (https://github.com/wildfly/wildfly/pull/9137 ) for WFLY-835 has been merged.

**Comment by rhusar** [comment]
The above ^ failure is being fixed as https://issues.jboss.org/browse/WFLY-7139, the other problems are being investigated and tracked as https://issues.jboss.org/browse/WFLY-7029.

**Pull request merged**
