### PR TITLE
JMX/Messaging-ActiveMQ Capabilities and Requirements

### PR DESCRIPTION
**Pull request by jmesnil**

### CODE REVIEW

**Comment by scottmarlow** [comment]
Thanks Jeff!

**Comment by bstansberry** [comment]
In ServerAdd, after you register the attributes you need to register the capability:

```
context.registerCapability(ACTIVEMQ_SERVER_CAPABILITY.fromBaseCapability(context.getCurrentAddressValue()), null);
```

In ServerRemove you need to deregister the capability before removing the resource:

```
context.deregisterCapability(ACTIVEMQ_SERVER_CAPABILITY.getDynamicName(context.getCurrentAddressValue()));
```

**Comment by jmesnil** [comment]
@bstansberry sorry about that, I cherry-picked an old commit that required more massaging.

I've fixed the code (and extended `Abstract{Add|Remove}Handler` to add and remove the server resource)

**Comment by jmesnil** [comment]
retest this please

**Comment by scottmarlow** [comment]
retest this please

**Pull request merged**
