### PR TITLE
[SECURITY-896] test for said JIRA

### PR DESCRIPTION
**Pull request by baranowb**
https://issues.jboss.org/browse/SECURITY-901

Test to see if user name is being parsed properly wrt user name begin and end string

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Comment by stuartwdouglas** [comment]
In addition to fixing the the failures you commit message should:
- Reference a WFLY JIRA not one from another project
- Include a description of what it is testing, so we don't have to look up the JIRA

**Comment by baranowb** [comment]
Weird. This should be in PR top comment, along with links. Will fix it once I have a spare minute.

**Comment by baranowb** [comment]
https://issues.jboss.org/browse/SECURITY-901, AKA WFLY-5120 - for some reason it has been changed into "another project". How can I link relevant JIRA if they get shazzamed into "another project". There is also the original EAP one but since there is no doc with actual process...

**Pull request merged**
