### PR TITLE
[WFLY-18370] Remove the workaround sar dependency, and add test

### PR DESCRIPTION
**Pull request by kabir**
https://issues.redhat.com/browse/WFLY-18370

This needs https://github.com/wildfly/wildfly-core/pull/5637 to be merged

### CODE REVIEW

**Comment by bstansberry** [comment]
@kabir This needs a rebase.

**Comment by kabir** [comment]
@bstansberry done (weirdly enough the rebase applied cleanly here)

**Comment by bstansberry** [comment]
@kabir Thanks. I find that happens fairly often with my own PRs.

**Comment by bstansberry** [comment]
Thanks @kabir

**Pull request merged**
