### PR TITLE
[WFLY-8298] Not able to undefine initial-pool-size attribute of datas…

### PR DESCRIPTION
**Pull request by treblereel**
…ource

JIRA: https://issues.jboss.org/browse/WFLY-8298
downstream: https://github.com/jbossas/jboss-eap7/pull/1531

### CODE REVIEW

**Review by maeste — APPROVED** [review]

**Comment by treblereel** [comment]
retest this please

**Comment by hpehl** [comment]
> it should work after JBEAP-9299 gets done

@treblereel Did I miss anything? It does not depend on JBEAP-9299. Instead JBEAP-9299 depends on this issue (WFLY-8298 / JBEAP-9298) to be fixed.

**Comment by treblereel** [comment]
retest this please

**Comment by treblereel** [comment]
@hpehl yeap, sorry, you right

**Comment by treblereel** [comment]
retest this please

**Comment by treblereel** [comment]
retest this please

**Comment by treblereel** [comment]
retest this please

**Comment by kabir** [comment]
Needs a downstream PR to to get considered atm

**Pull request merged**
