### PR TITLE
WFLY-7562 statistics-enabled attribute of webservices subsystem could allow expressions

### PR DESCRIPTION
**Pull request by TomasHofman**
https://issues.jboss.org/browse/WFLY-7562
https://issues.jboss.org/browse/JBEAP-6868

EAP 7.1 PR: https://github.com/jbossas/jboss-eap7/pull/1066

### CODE REVIEW

**Review by rhusar — CHANGES_REQUESTED** [review]
-1

This seems to be introducing a whole new schema version while it is only necessary to introduce a new model version (if that hasn't been done in master already).

**Comment by TomasHofman** [comment]
Updated so that only model version is changed, schema stays.

It's all in a single commit now as the version bump commit would only contain one line...

**Comment by jmesnil** [comment]
You'll need to create a PR against the EAP 7.x branch that references the corresponding JBEAP issue to get it merged.

**Comment by TomasHofman** [comment]
@jmesnil thanks, PR is https://github.com/jbossas/jboss-eap7/pull/1066

**Pull request merged**
