### PR TITLE
[WFLY-14358] Upgrade ironjacamar to 1.4.27.Final

### PR DESCRIPTION
**Pull request by tadamski**
https://issues.redhat.com/browse/WFLY-14358

Upgrade because of https://issues.redhat.com/browse/JBEAP-20573/https://issues.redhat.com/browse/JBEAP-20520/https://issues.redhat.com/browse/JBJCA-1413

### CODE REVIEW

**Comment by bstansberry** [comment]
@tadamski It looks like this isn't available in maven.

**Comment by tadamski** [comment]
@bstansberry Yes, I fogot to release it. Sorry. I had also made another version because we decided to revert JBJCA-1397.

**Pull request merged**
