### PR TITLE
[WFLY-19636]: Upgrading Apache Artemis to 2.37.0

### PR DESCRIPTION
**Pull request by ehsavoie**
* Upgrading Artemis components to 2.37.0.
* Upgrading commons-codec to 1.17.1

https://activemq.apache.org/components/artemis/download/release-notes-2.36.0
https://activemq.apache.org/components/artemis/download/release-notes-2.37.0

Jira: https://issues.redhat.com/browse/WFLY-19636
      https://issues.redhat.com/browse/WFLY-19726

____

<--- THIS SECTION IS AUTOMATICALLY GENERATED BY WILDFLY GITHUB BOT. ANY MANUAL CHANGES WILL BE LOST. --->

> Wildfly issue links:
> * [WFLY-19726](https://issues.redhat.com/browse/WFLY-19726)

<--- END OF WILDFLY GITHUB BOT REPORT --->

More information about the [wildfly-bot[bot]](https://github.com/wildfly/wildfly-github-bot)

### CODE REVIEW

**Comment by bstansberry** [comment]
@ehsavoie Please file an issue for the commons-code change. It's a broadly used dependency:

```
$ git grep org.apache.commons.codec | grep module.xml 
ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/commons/codec/main/module.xml:<module xmlns="urn:jboss:module:1.9" name="org.apache.commons.codec">
ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/httpcomponents/main/module.xml:        <module name="org.apache.commons.codec"/>
ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/santuario/xmlsec/main/module.xml:      <module name="org.apache.commons.codec"/>
ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/apache/ws/security/main/module.xml:      <module name="org.apache.commons.codec"/>
ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/elasticsearch/client/rest-client/main/module.xml:        <module name="org.apache.commons.codec" export="true"/>
ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/as/webservices/server/integration/main/module.xml:        <module name="org.apache.commons.codec"/>
ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/resteasy/resteasy-client/main/module.xml:        <module name="org.apache.commons.codec" />
ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/jboss/ws/cxf/jbossws-cxf-server/main/module.xml:        <module name="org.apache.commons.codec" />
ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/opensaml/main/module.xml:      <module name="org.apache.commons.codec"/>
jsf/multi-jsf-installer/src/main/resources/myfaces-impl-module.xml:        <module name="org.apache.commons.codec"/>
jsf/subsystem/src/test/resources/modules/jakarta/faces/impl/myfaces/module.xml:        <module name="org.apache.commons.codec"/>
jsf/subsystem/src/test/resources/modules2/jakarta/faces/impl/myfaces2/module.xml:        <module name="org.apache.commons.codec"/>
```

**Comment by bstansberry** [comment]
@jimma @jamezp @yrodiere If you have any concerns about the commons-code change here please advise ASAP. I'd like to get the Artemis upgrade that brings it into WF next week in time for WF 34 Beta.

**Review by jamezp — APPROVED** [review]
Looks good to me.

**Comment by yrodiere** [comment]
> @yrodiere If you have any concerns about the commons-code change here please advise ASAP. I'd like to get the Artemis upgrade that brings it into WF next week in time for WF 34 Beta.

@marko-bekhta will confirm but AFAICS Hibernate Search 7.2, which we want to be in WF 34, use already using commons codec 1.17.0, so it should be fine.

We'll need to speed up that upgrade to ORM 6.6 / Search 7.2 in WF though; I'll look into that.

**Comment by marko-bekhta** [comment]
> > @yrodiere If you have any concerns about the commons-code change here please advise ASAP. I'd like to get the Artemis upgrade that brings it into WF next week in time for WF 34 Beta.
> 
> @marko-bekhta will confirm but AFAICS Hibernate Search 7.2, which we want to be in WF 34, is already using commons codec 1.17.0, so it should be fine.
> 
> We'll need to speed up that upgrade to ORM 6.6 / Search 7.2 in WF though; I'll look into that.

Hey, the upgrade to commons-codec happened as part of the Avro upgrade under https://hibernate.atlassian.net/browse/HSEARCH-5212 and the version Search has is `1.17.1`

**Review by bstansberry — APPROVED** [review]
This seems fine. I see that CXF main is using 1.17.1 and the 4.0.5 we use has 1.17.0, so this certainly brings us closer to CXF than the current 1.15

The Santuario 3.0.4 tag builds / passes mvn verify when commons-codec is updated from 1.16.1 to 1.17.1.

**Comment by jimma** [comment]
@ehsavoie @bstansberry  This looks good to me .

**Comment by bstansberry** [comment]
Thanks @ehsavoie

**Pull request merged**
