### PR TITLE
[WFLY-10898] Opentracing extension does not follow xxx-smallrye pattern naming

### PR DESCRIPTION
**Pull request by yersan**
The legacy feature pack template used to generate the domain.xml file is correct, but the domain.host-exclude feature spec for Galleon is using a wrong name for Opentracing extension.

Jira issue: https://issues.jboss.org/browse/WFLY-10898

### CODE REVIEW

**Comment by yersan** [comment]
Errors are related, checking

**Review by kabir — CHANGES_REQUESTED** [review]
@yersan I think we should rename the extension instead so it follows the xxx-smallrye pattern

**Comment by yersan** [comment]
@kabir makes sense to me too. I think it would be also more in line with the artifactId of this module: `wildfly-microprofile-opentracing-smallrye` and with a module name used by the extension: `org.wildfly.microprofile.opentracing-smallrye`

@jamezp @jpkrohling Do you agree on this change?

**Comment by jpkrohling** [comment]
I followed the pattern from other non-MP extensions where they would mention the spec, but not the implementation (CDI, JPA, JMS, ...) The implementation (SmallRye) is an implementation detail, IMO.

That said, I'm OK with changing it to follow the pattern from the other MP extensions.

**Comment by bstansberry** [comment]
+1. @yersan please add a commit doing the rename.

**Comment by jamezp** [comment]
The name change seems reasonable to me as well.

**Comment by yersan** [comment]
@kabir. Just for the sake of completeness, I renamed the extension, the subsystem, and the xml namespace. I can squash what we need once it is approved.

**Comment by kabir** [comment]
@yersan I think it looks fine thanks! @jpkrohling Can you double check?

**Review by jpkrohling — APPROVED** [review]
LGTM. I also ran the TCK and it passes.

**Review by kabir — APPROVED** [review]

**Pull request merged**
