### PR TITLE
WFLY-5113 NoClassDefFoundError in web migrate op

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by bstansberry** [comment]
The attribute names are all in ModelDescriptionConstants in controller module, which is a valid dependency for a subsystem.

I don't mind this all that much if you're in a hurry, so feel free to merge. I mostly just don't like the precedent/bad example for others.

**Comment by stuartwdouglas** [comment]
They appear to be in the org.jboss.as.domain.management.ModelDescriptionConstants, not the controller one. I could just hard code the strings I guess, it is not like they are likely to change.

**Comment by stuartwdouglas** [comment]
https://github.com/wildfly/wildfly-core/pull/961

I think I might just merge this for now, but file a JIRA to change it to the ModelDescriptionConstants once that PR is in

**Comment by stuartwdouglas** [comment]
https://issues.jboss.org/browse/WFLY-5118

**Pull request merged**
