### PR TITLE
WFLY-9284 Correct MVN env variable to mvnw.cmd

### PR DESCRIPTION
**Pull request by awesomebjt**

### CODE REVIEW

**Comment by jmesnil** [comment]
this is ok to test

**Comment by kabir** [comment]
This is ok to test

**Comment by kabir** [comment]
@praxeo 
We require that all contributions be made under the terms of the MIT License, http://www.opensource.org/licenses/mit-license.php. Do you agree to the these terms?

**Comment by praxeo** [comment]
@kabir
Yes I do, thanks for checking.

**Pull request merged**
