### PR TITLE
[WFLY-19890] Upgrade protobuf-java to 4.28.3

### PR DESCRIPTION
**Pull request by darranl**
https://issues.redhat.com/browse/WFLY-19890

Please see the referenced Jira issue for more information regarding how protobuf versions are handled and for associated diffs.

### CODE REVIEW

**Comment by bstansberry** [comment]
@jasondlee Please review

**Review by jasondlee — APPROVED** [review]
I'm not aware of any reason not to update and the tests seem happy, so I'm good with this.

**Comment by darranl** [comment]
@bstansberry / @jasondlee FYI I have updated the Jira issue with information about the versioning of this project and the tags we can reference / use.

**Comment by bstansberry** [comment]
Thanks @darranl and @jasondlee

**Pull request merged**
