### PR TITLE
[WFLY-18970] Upgrade ASM to 9.6

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-18970

### CODE REVIEW

**Comment by ropalka** [comment]
@jimma is the ASM upgrade compatible with webservice modules?
@scottmarlow is the ASM upgrade compatible with hibernate modules?
@kabir is the ASM upgrade compatible with smallrye modules?

**Comment by kabir** [comment]
@ropalka Fine from a SmallRye point of view

**Comment by scottmarlow** [comment]
@ropalka yes as Hibernate does not depend on the asm.asm module (Hibernate uses ByteBuddy which has its own copy of ASM).

**Review by jimma — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @ropalka, @kabir, @scottmarlow and @jimma

**Pull request merged**
