### PR TITLE
WFLY-10606 Remove ee8.preview.mode support for Weld.

### PR DESCRIPTION
**Pull request by manovotn**
JIRA - https://issues.jboss.org/browse/WFLY-10606

This PR contains all the WFLY-side changes needed to get rid of `cdi-api-bridge` and fully switch to CDI 2.0 APIs.

I have also removed the smoke/sanity tests which were related to Weld in preview mode.

Note that after this change, WFLY will no longer pass signature TCK test for EE 7. All other tests are expected to pass (CDI TCK 1.2 and 2.0 do work for sure).

### CODE REVIEW

**Comment by manovotn** [comment]
@mkouba @nziakova take a look at this as well if you have few spare minutes.

Also needs `ee8` label but I apparently don't have rights to add it.

**Review by mkouba — APPROVED** [review]
Looks good!

**Review by nziakova — APPROVED** [review]

**Review by kabir — DISMISSED** [review]
@manovotn @mkouba How do you feel about moving the ee8 test into testsuite/integration/basic?

**Comment by manovotn** [comment]
@kabir I suppose you are talking about `CDI20SanityTest.java`? If that's the case then I feel it's redundant.
The test only checked that `ee8` mode works, e.g.  that you can use some CDI 2.0 specific feature.
I see no way of *not* having this functionality (breaking this test) now that you only have CDI 2.0 API and Weld 3 (which was CDI 2.0 impl in the first place and we added hacks to make it work with bridge and 1.2 API).

Besides we have CI set up to test on nightly WFLY builds and run whole CDI TCK and even more tests, so I would say it's covered.

**Comment by kabir** [comment]
@manovotn It needs a rebase

**Comment by manovotn** [comment]
@kabir done

**Review by jamezp — APPROVED** [review]

**Pull request merged**
