### PR TITLE
Remove duplicate dependency on jboss-invocation causing build warnings.

### PR DESCRIPTION
**Pull request by rhusar**
Introduced over the weekend via https://github.com/wildfly/wildfly/pull/15913 (FYI @yersan)

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]

**Review by yersan — CHANGES_REQUESTED** [review]
Thanks, @rhusar, I came into adding the dependencies when I was testing building wildly full with https://github.com/wildfly/wildfly-core/pull/5171 and I added those dependencies thinking that they were not there.

It seems the order matters here, so, could you remove the other duplicate on [L129-L132](https://github.com/wildfly/wildfly/blob/main/ee/pom.xml#L129-L132)

The same for the ejb3 module.

**Comment by rhusar** [comment]
@yersan Good point, agreed, and done. Although – the `ejb3/pom.xml` dependencies are *very* out of order.

**Comment by yersan** [comment]
Ok, my interpretation of the order issue is that `org.jboss.invocation:jboss-invocation-jakarta` is brought in as transitive dependency by `org.wildfly.core:wildfly-server`, so it will place common classes before in the classpath, making the compilation to fail when used in conjunction with https://github.com/wildfly/wildfly-core/pull/5171

Both solutions should work, either exclude `org.jboss.invocation:jboss-invocation-jakarta` from `org.wildfly.core:wildfly-server` or place `org.jboss.invocation:jboss-invocation` at the beginning, as you did now.

**Review by yersan — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @rhusar

**Pull request merged**
