### PR TITLE
[WFLY-12516] TestCase to check EJBContext principal after invoking another EJB using a different Security Domain

### PR DESCRIPTION
**Pull request by fmarchioni**
- This Testcase verifies that, when invoking multiple EJBs with different legacy Security Domains, the  EJBContext principal is correctly popped back.
- JIRA: https://issues.redhat.com/browse/WFLY-12516
- Please don't merge this until this PR is completed: https://github.com/wildfly/wildfly/pull/12903

### CODE REVIEW

**Comment by jamezp** [comment]
retest this please

**Comment by jamezp** [comment]
this is okay to test

**Comment by fmarchioni** [comment]
@jamezp  in order to pass the test it's required that https://github.com/wildfly/wildfly/pull/12903 is merged. I think it's not ready to be merged now in the master branch as it results in compilation failure:
```
[ERROR] ./wildfly-WFLY-12516_v10/security/subsystem/src/main/java/org/jboss/as/security/service/SimpleSecurityManager.java:[378,73] cannot find symbol
[ERROR]   symbol:   method clone()
[ERROR]   location: interface org.jboss.security.identity.RoleGroup
```
I've added a note in the description.

**Comment by jamezp** [comment]
@fmarchioni Can we combine those by chance then?

**Comment by fmarchioni** [comment]
@jamezp  I'll check it with @baranowb . At the moment, I'm not able to build his branch (https://github.com/baranowb/wildfly/tree/WFLY-12516_v10) either. I'll let you know.

**Comment by darranl** [comment]
The better two approaches are to discuss with the engineer that wrote the fix and either ask them to add the test commits to their PR or branch from their topic branch and add the tests on top of that.  For the latter just ask them not to rebase.

**Comment by jamezp** [comment]
this is ok to test

@fmarchioni Okay thank you. I'm trying to get this running on CI to add you to the white list :)

**Comment by bstansberry** [comment]
Hi @fmarchioni.  The PR queue is out of control so I am going to close this. Please coordinate with @baranowb to get the tests added to #12903.

**Pull request closed without merging**
