### PR TITLE
WFLY-10856 Hibernate51CompatibilityTransformer#transform should always return null if no class change is made

### PR DESCRIPTION
**Pull request by scottmarlow**
https://issues.jboss.org/browse/WFLY-10856
This corrects the Hibernate51CompatibilityTransformer to be a little faster for deploying Hibernate native applications that do not need class transformations to be made.

### CODE REVIEW

**Review by gbadner — COMMENTED** [review]
Rather than setting `transformedState.setClassTransformed(true)` in each `if` and `else if` block, could you instead:

* stash the original `desc` reference at the top of `visitMethod` (e.g., final String descOrig = desc;)
* at the bottom, just before calling `return new MethodAdapter(...)`, setting `transformedState.setClassTransformed(desc != descOrig)`

**Review by gbadner — COMMENTED** [review]
Also, it appears that `rewriteSessionImplementor` can be set to `true` when `SessionImplementor` may not have been replaced (unless I'm missing something).

**Comment by scottmarlow** [comment]
@gbadner sure, we could do something like that, just need to ensure that we don't call setClassTransformed with false, after it was already set to true, so probably only should call setClassTransformed(true) if desc != descOrig.

Regarding rewriteSessionImplementor, I left that separate so that any method in the user type implementation that calls an ORM method that expects SessionImplementor, will instead expect SharedSessionContractImplementor to be used.  @gsmet what do you recommend?

**Comment by gsmet** [comment]
> Regarding rewriteSessionImplementor, I left that separate so that any method in the user type implementation that calls an ORM method that expects SessionImplementor, will instead expect SharedSessionContractImplementor to be used. @gsmet what do you recommend?

Yes that was the original intent. In any considered type, we rewrite all the calls to `org.hibernate` methods with `SharedSessionContractImplementor`.

**Comment by scottmarlow** [comment]
The linux elytron failure doesn't seem related:
```
java.lang.AssertionError: CF1 not found
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.jboss.as.test.smoke.deployment.rar.tests.multiactivation.MultipleActivationTestCase.testConfiguration(MultipleActivationTestCase.java:126)

**Pull request merged**
