### PR TITLE
[WFLY-20011] Remove all non-breaking uses of ModuleIdentifier in Naming Subsystem

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-20011

### CODE REVIEW

**Comment by bstansberry** [comment]
I put the hold label on this pending resolution of https://wildfly.zulipchat.com/#narrow/channel/174184-wildfly-developers/topic/ModuleIdentifier.20deprecation/near/484590414

**Review by bstansberry — CHANGES_REQUESTED** [review]
I added the core-upgrade-needed label because this needs to use something like https://github.com/wildfly/wildfly-core/pull/6270 to handle module name strings passed in from outside.

**Comment by bstansberry** [comment]
@ropalka The https://github.com/wildfly/wildfly-core/pull/6270 API is now available.

**Comment by ropalka** [comment]
Thanks for info @bstansberry - it is fixed now.

**Review by bstansberry — APPROVED** [review]
This breaks the API of ModularReference, which in theory could be used by extension authors outside the main WF code base. (The org.jboss.as.naming module is used in many extensions, but not the ModularReference class.)

I think it's ok; if this breaks someone they have a path to adapt, by using the create methods instead of constructors, and by dealing with a canonical string form of a module identifier themselves.

**Comment by bstansberry** [comment]
Thanks @ropalka

**Pull request merged**
