### PR TITLE
[WFLY-11930] Allow Java EE Subsystem to enable/disable descriptor bas…

### PR DESCRIPTION
**Pull request by yersan**
…ed property replacement for permissions descriptors

wildfly counterpart of https://github.com/wildfly/wildfly-core/pull/4002. It requires a wildfly-core upgrade including that PR to make this to pass.

Jira issue: https://issues.jboss.org/browse/WFLY-11930

### CODE REVIEW

**Comment by darranl** [comment]
The doc commit could probably benefit from a slightly more descriptive message, if everyone used a similar message a `git log` command in the docs folder would show a list that keeps saying "Community Docs"

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
#12912 is testing this.

**Comment by bstansberry** [comment]
@yersan The test here has a failure on Windows:

https://ci.wildfly.org/viewLog.html?buildId=182041&tab=buildResultsDiv&buildTypeId=WF_PullRequest_WindowsJdk11&branch_WF_PullRequest=pull%2F12912

```
java.nio.file.InvalidPathException: Illegal char <:> at index 126: C:\BuildAgent\work\bb15431f347cd651\testsuite\integration\secman/../../../build/target/wildfly-19.0.0.Beta1-SNAPSHOT/modules;C:\BuildAgent\work\bb15431f347cd651\testsuite\integration\secman/target/modules
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at org.jboss.as.testsuite.integration.secman.propertypermission.PermissionParserExpressionsTestCase.test(PermissionParserExpressionsTestCase.java:71)
```

**Comment by yersan** [comment]
retest this please

**Pull request merged**
