### PR TITLE
WFLY-19801 Revert "WFLY-19606 Add a workaround for ISPN-16703." - partially; kee…

### PR DESCRIPTION
**Pull request by rhusar**
…p the structure but remove the overridden shell script.

Fixup of WFLY-19801 Upgrade Infinispan from 14.0.31.Final to 14.0.33.Final. - https://issues.redhat.com/browse/WFLY-19801

This reverts commit 7aa2999bec922dd88ad323b0da5bafa798465e0f.

____

<--- THIS SECTION IS AUTOMATICALLY GENERATED BY WILDFLY GITHUB BOT. ANY MANUAL CHANGES WILL BE LOST. --->

> Wildfly issue links:
> * [WFLY-19606](https://issues.redhat.com/browse/WFLY-19606)
> * [WFLY-19801](https://issues.redhat.com/browse/WFLY-19801)

<--- END OF WILDFLY GITHUB BOT REPORT --->

More information about the [wildfly-bot[bot]](https://github.com/wildfly/wildfly-github-bot)

### CODE REVIEW

**Comment by rhusar** [comment]
@pferraro FYI this was missed on Infinispan 14.0.33.Final upgrade.

**Comment by pferraro** [comment]
Blech - I had hoped these tests would be containerised by now...

**Review by pferraro — APPROVED** [review]
Thanks @rhusar !

**Comment by rhusar** [comment]
> Blech - I had hoped these tests would be containerised by now...

We will, soon! 🤞🏼

**Comment by bstansberry** [comment]
Thanks @rhusar and @pferraro

**Pull request merged**
