### PR TITLE
[WFLY-17953] Migrate to using the Shrinkwrap Resolvers for resolving …

### PR DESCRIPTION
**Pull request by jamezp**
…test artifacts rather than using non-public JBoss Modules utilities.

https://issues.redhat.com/browse/WFLY-17953

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]
The MP LRA tck pom change concerns me, but if the TCK passes, then it doesn't. :)

**Comment by kabir** [comment]
@bstansberry the LRA stuff is due to upstream wanting a newer versions


```
 --- maven-dependency-plugin:3.1.1:tree (default-cli) @ wildfly-ts-integ-mp-lra ---
[INFO] org.wildfly:wildfly-ts-integ-mp-lra:jar:29.0.0.Alpha1-SNAPSHOT
[INFO] +- org.eclipse.microprofile.lra:microprofile-lra-api:jar:2.0:test
[INFO] +- org.eclipse.microprofile.lra:microprofile-lra-tck:jar:2.0:test
[INFO] |  +- org.hamcrest:hamcrest-all:jar:1.3:test
[INFO] |  \- org.jboss.arquillian.junit:arquillian-junit-container:jar:1.7.0.Alpha13:test
[INFO] |     +- org.jboss.arquillian.test:arquillian-test-api:jar:1.7.0.Alpha13:compile
[INFO] |     +- org.jboss.arquillian.container:arquillian-container-test-api:jar:1.7.0.Alpha13:compile
[INFO] |     |  \- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-api-base:jar:2.0.0:compile
[INFO] |     +- org.jboss.arquillian.container:arquillian-container-test-spi:jar:1.7.0.Alpha13:compile
[INFO] |     |  \- org.jboss.arquillian.container:arquillian-container-spi:jar:1.7.0.Alpha13:compile
[INFO] |     +- org.jboss.arquillian.core:arquillian-core-impl-base:jar:1.7.0.Alpha13:test
[INFO] |     +- org.jboss.arquillian.test:arquillian-test-impl-base:jar:1.7.0.Alpha13:test
[INFO] |     +- org.jboss.arquillian.container:arquillian-container-impl-base:jar:1.7.0.Alpha13:test
[INFO] |     |  +- org.jboss.arquillian.config:arquillian-config-api:jar:1.7.0.Alpha13:compile
[INFO] |     |  +- org.jboss.arquillian.config:arquillian-config-impl-base:jar:1.7.0.Alpha13:compile
[INFO] |     |  |  \- org.jboss.arquillian.config:arquillian-config-spi:jar:1.7.0.Alpha13:compile
[INFO] |     |  \- org.jboss.shrinkwrap.descriptors:shrinkwrap-descriptors-spi:jar:2.0.0:compile
[INFO] |     \- org.jboss.arquillian.container:arquillian-container-test-impl-base:jar:1.7.0.Alpha13:compile
[INFO] +- org.jboss.narayana.rts:lra-test-arquillian-extension:jar:6.0.0.Final:test
[INFO] |  +- org.jboss.narayana.rts:narayana-lra:jar:6.0.0.Final:test
[INFO] |  +- org.jboss.narayana.rts:lra-coordinator-jar:jar:6.0.0.Final:test
[INFO] |  +- org.jboss.narayana.rts:lra-client:jar:6.0.0.Final:test
[INFO] |  +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-api:jar:3.1.4:test
[INFO] |  +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-impl-maven:jar:3.1.4:test
[INFO] |  |  +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-api-maven:jar:3.1.4:test
[INFO] |  |  +- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-spi-maven:jar:3.1.4:test
[INFO] |  |  |  \- org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-spi:jar:3.1.4:test
```

**Comment by jamezp** [comment]
> The MP LRA tck pom change concerns me, but if the TCK passes, then it doesn't. :)

This was only done because I did't see it used and didn't want it to add confusion :)

**Comment by jamezp** [comment]
> resolv

As far as I know you can't override a dependency like that with a property though. The property would only be overwritten in a parent POM, not in imported one.

**Pull request merged**
