### PR TITLE
WFLY-13538 Port Java 9+ version of ConcurrentDirectDeque from Undertow

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-13538

Ports the Java 9+ variant of FastConcurrentDirectDeque from Undertow and uses a multi-release jar for the org.wildfly:wildfly-clustering-ee-cache module.

### CODE REVIEW

**Comment by bstansberry** [comment]
@dosoudil FYI and comment.

@pferraro This should be discussed on the dev list. When we release WildFly we build using JDK 8. That's a pretty substantial thing to change for one class.

**Comment by darranl** [comment]
I mentioned on the dev list thread as well but wouldn't this be better in wildfly-common where a multi-release jar is already possible then WildFly can use it without a change to the WildFly build.

**Comment by pferraro** [comment]
To reiterate what was said on the dev list thread, I already pursued the option of housing these collections in wildfly-common, and it was decided to keep wildfly-common free of collection implementations.

**Comment by scottmarlow** [comment]
We do have other collections included in WildFly already, probably more in components.

wildfly:
```
ag -rli doug.*lea
web-common/src/main/java/org/jboss/as/web/common/ConcurrentReferenceHashMap.java
naming/src/main/java/org/jboss/as/naming/util/FastCopyHashMap.java
security/subsystem/src/main/java/org/jboss/as/security/lru/PortableConcurrentDirectDeque.java
security/subsystem/src/main/java/org/jboss/as/security/lru/FastConcurrentDirectDeque.java
clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/scheduler/PortableConcurrentDirectDeque.java
clustering/ee/cache/src/main/java/org/wildfly/clustering/ee/cache/scheduler/FastConcurrentDirectDeque.java
```
wildfly-core:
```
ag -rli doug.*lea
controller/src/main/java/org/jboss/as/controller/registry/FastCopyHashMap.java
```

**Comment by kabir** [comment]
Adding the hold label so noone accidentally merges this. It looks like it needs discussion

**Comment by pferraro** [comment]
Removed hold label, since the discussion has come to a resolution.

**Pull request merged**
