### PR TITLE
[WFLY-8742] Fix tests to install Elytron provider

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
Depends on #10156 (will probably need a re-test then)

**Comment by darranl** [comment]
Is this really needed?  The AuthenticationConfiguration default should be able to discover the provider automatically.

**Comment by dmlloyd** [comment]
Emperically, no, it does not seem to do so.  This patch allows the test to proceed where previously it failed.

**Comment by kabir** [comment]
Retest this please

**Comment by darranl** [comment]
This is the logging I can get out of the server: -

2017-06-07 19:17:41,085 TRACE [org.jboss.remoting.remote] (default I/O-7) No message ready; returning
2017-06-07 19:17:41,618 TRACE [org.wildfly.security] (default I/O-11) Permission mapping: identity [anonymous] with roles [] implies ("org.wildfly.security.auth.permission.LoginPermission" "") = false
2017-06-07 19:17:41,629 ERROR [org.apache.activemq.artemis.core.server] (default I/O-11) AMQ224018: Failed to create session: ActiveMQSecurityException[errorType=SECURITY_EXCEPTION message=AMQ119031: Unable to validate user]
	at org.apache.activemq.artemis.core.security.impl.SecurityStoreImpl.authenticate(SecurityStoreImpl.java:144)
	at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.createSession(ActiveMQServerImpl.java:1283)
	at org.apache.activemq.artemis.core.protocol.core.impl.ActiveMQPacketHandler.handleCreateSession(ActiveMQPacketHandler.java:156)

**Comment by darranl** [comment]
Based on my comments in the Jira issues I think this PR should be closed until the next Elytron version is included, at that point when the tests are re-enabled IMO some work is also required on the tests to ensure the anonymous identity is granted the LoginPermission to allow the connection to be established.

**Comment by dmlloyd** [comment]
Yeah that's fine.

**Pull request closed without merging**
