### PR TITLE
[WFLY-19543] Upgrade ByteBuddy to 1.14.18

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-19543

### CODE REVIEW

**Comment by ropalka** [comment]
@scottmarlow is the ByteBuddy upgrade compatible with JPA/Hibernate modules?

**Comment by scottmarlow** [comment]
We are using Hibernate ORM 6.4.4.Final currently which is using ByteBuddy 1.14.11 as per https://github.com/hibernate/hibernate-orm/blob/6.4/settings.gradle#L68 

Hibernate ORM 6.6.0.CR1 is using ByteBuddy 1.14.15 https://github.com/hibernate/hibernate-orm/blob/6.6.0.CR1/settings.gradle#L71 but not quite the same as 1.14.18.  

I'll try submitting a few upstream pull requests for ORM 7.0 + 6.6 to update to the latest to see if there are any test failures with ORM 7.0/6.6.

**Comment by ropalka** [comment]
Thank you @scottmarlow for pushing this forward on Hibernate project side!

**Comment by bstansberry** [comment]
@ropalka @scottmarlow I'm going to put the 'hold' label on this to save mergers needing to check in on it while the activity described in the comments above happens. Please just remove the label when that is done and the PR is approved and start a thread in https://wildfly.zulipchat.com/#narrow/stream/274477-Pull-requests to let us know it's ready to go.

Also, if it turns out your expectation is this PR will not go in, but instead the upgrade will become part of some larger PR (say integration ORM 6.6 or 7), then please close this and track the discussions around the upgrade elsewhere.

**Comment by scottmarlow** [comment]
The upgrade to 1.14.18 for Hibernate ORM was merged (see https://github.com/hibernate/hibernate-orm/blob/main/settings.gradle#L71C58-L71C65) which we could use by upgrading WildFly main to ORM 6.6 when that is released.

The Hibernate ORM 7.0 branch upgrade to 1.14.18 was also merged (see https://github.com/hibernate/hibernate-orm/blob/wip/7.0/settings.gradle#L76C58-L76C65) which we will look at upgrading WildFly Preview to use.

> Also, if it turns out your expectation is this PR will not go in, but instead the upgrade will become part of some larger PR (say integration ORM 6.6 or 7), then please close this and track the discussions around the upgrade elsewhere.

Sounds like we to close this and track elsewhere.

**Comment by scottmarlow** [comment]
The Hibernate ORM release 6.6.0.Final is available and includes the upgrade to ByteBuddy 1.14.18.  I think we should start integrating that.

**Comment by ropalka** [comment]
This PR is the last remaining bit to start passing WF test suite on JDK 23 GA @bstansberry  that was released today

**Comment by scottmarlow** [comment]
Echoing here that WF is waiting for https://github.com/jakartaee/persistence/issues/644 to be resolved so we can understand the impact on certifying WildFly 34 as Jakarta EE 10 compatible.

**Review by scottmarlow — APPROVED** [review]

**Pull request merged**
