### PR TITLE
add test for WFCORE-544 inconsistent system property handling

### PR DESCRIPTION
**Pull request by hsvabek**
Test for https://issues.jboss.org/browse/WFCORE-544
https://bugzilla.redhat.com/show_bug.cgi?id=1192467

### CODE REVIEW

**Comment by hsvabek** [comment]
Some problem, I commit here same code like to EAP -> but there are some differences.

**Comment by hsvabek** [comment]
Please retest.

**Comment by stuartwdouglas** [comment]
Given that this is already tested by a unit test in the DMR code base adding (slow) domain mode test seems like overkill.

**Comment by stuartwdouglas** [comment]
Also I think this test belongs in Wildfly core rather than Wildfly, it does not seem to rely on anything that is not present in core.

**Comment by bstansberry** [comment]
Yes, it needs to go to core; the full WildFly testsuite/domain is being reserved for tests involving subsystems in full.

Please fix the commit message to reference WFCORE-544 instead of the internal QA JIRA. The latter is inaccessible to community.

**Comment by bstansberry** [comment]
I think adding the integration test though is valid; thanks for it. These tests are slow and generally I prefer avoiding them when lower level tests cover things, but for this one why it happened where it did and only where it did and why the DMR-18 fix was appropriate for it required a ton of analysis, so I can see how the integration is vulnerable to regression and can use an integration test.

**Comment by bstansberry** [comment]
Please submit this as change to the master branch of https://github.com/wildfly/wildfly-core. It doesn't belong in full WildFly as it is testing WildFly Core functionality. Thanks.

**Comment by hsvabek** [comment]
I created new PR in Wildfly-core
https://github.com/wildfly/wildfly-core/pull/612

**Pull request closed without merging**
