### PR TITLE
WFLY-8504 EJB over HTTP sesion id does not include the JVM route

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Also needs a HTTP client component upgrade

### CODE REVIEW

**Comment by kabir** [comment]
@stuartwdouglas As well as the 'normal' test failures, the test fails with -Delytron. @ctomc also notes that HttpRemoteIdentityTestCase fails when run with -Delytron: https://ci.wildfly.org/project.html?projectId=WF&testNameId=3545770804807136221&tab=testDetails

**Comment by kabir** [comment]
Retest this please

**Comment by kabir** [comment]
Retest this please

**Comment by kabir** [comment]
There are some failures in the test on windows https://ci.wildfly.org/viewLog.html?buildId=53911&buildTypeId=WF_PullRequest_Windows. Before yesterday's retest there was a failure on linux https://ci.wildfly.org/viewLog.html?buildId=53738&tab=buildResultsDiv&buildTypeId=WFPR

**Comment by pferraro** [comment]
FYI, https://github.com/wildfly/wildfly/pull/9908 will change how this PR acquires its route.  The route will be available from the Server.getRoute() method.

**Comment by pferraro** [comment]
@stuartwdouglas Once you rebase against master, you can apply https://github.com/pferraro/wildfly/commit/4d7fe0bddf67a94a171eb60a0342ea3e9be44cc6 to pull the route from the correct source.

**Pull request merged**
