### PR TITLE
[WFLY-5458] Do not allow expressions for jgroup-stack and groups-channel attributes

### PR DESCRIPTION
**Pull request by jmesnil**
These attributes may referenceother management resources (cf. WFLY-5189) and must not
allow expressions.

JIRA: https://issues.jboss.org/browse/WFLY-5458

### CODE REVIEW

**Comment by jmesnil** [comment]
retest this please

**Comment by rhusar** [comment]
:+1: Looks good to me.

**Comment by bstansberry** [comment]
Should the migrate op warn about this? The legacy subsystem allowed expressions on these.

**Comment by jmesnil** [comment]
The `migrate` op will fail if the legacy subsystem has expressions in it as the `add` operations for the new subsystem will not allow the expressions.
The user will then be able to "fix" the legacy subsystems by removing the expressions from there.

**Comment by n1hility** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Pull request merged**
