### PR TITLE
Update Hibernate ORM to 5.0.3.

### PR DESCRIPTION
**Pull request by langfr**

### CODE REVIEW

**Comment by scottmarlow** [comment]
I already ran the WF testsuite earlier today and got the same failure as we saw with 5.0.2:

2015-10-28 09:56:54,705 SEVERE [org.jboss.arquillian.protocol.jmx.JMXTestRunner] (pool-392-thread-1) Failed: org.jboss.as.test.integration.jpa.secondlevelcache.JPA2LCTestCase.testEvictQueryCache: java.lang.AssertionError: Expected 1 miss in cache(hitCount=1, missCount=0, putCount=0). expected:<1> but was:<0>

**Comment by Sanne** [comment]
+1
I'd love to see this upgrade in WildFly 10 as well

**Comment by codylerum** [comment]
Maybe this PR https://github.com/hibernate/hibernate-orm/pull/1096 got missed.

https://hibernate.atlassian.net/browse/HHH-10163

**Comment by langfr** [comment]
Yes, unfortunately the PR was not merged and this issue is still open.
Waiting for the fourth bug-fix release of ORM 5.0.

**Comment by scottmarlow** [comment]
Hibernate ORM 5.0.4 should be released today.  I created WFLY-5700 for bringing 5.0.4 into WildFly.  I'm going to run the WF testsuite locally with 5.0.4 and if that passes, will create a pr.

**Comment by scottmarlow** [comment]
pull request is at https://github.com/wildfly/wildfly/pull/8412

**Pull request closed without merging**
