### PR TITLE
WFLY-16331 TimerServiceResource locking performance improvement

### PR DESCRIPTION
**Pull request by chengfang**
https://issues.redhat.com/browse/WFLY-16331

### CODE REVIEW

**Comment by pferraro** [comment]
FYI, https://github.com/wildfly/wildfly/pull/15053 already includes changes to the Resource implementation to accommodate distributed timers.  The new implementation should address your concerns about locking performance, I think.  For details, see these commits:
https://github.com/wildfly/wildfly/pull/15053/commits/b44038423cb94fe696ab043ff7a6b740be0103c3
https://github.com/wildfly/wildfly/pull/15053/commits/b0c6ac2e383d48e46c32d187ae51484449baeac9

**Comment by chengfang** [comment]
@pferraro  thanks for pointer to the distributed timer. The fix in this PR is strictly scoped for this issue only so imho is good to include it in WF now, and in subsequent releases we can upgrade to the one used in distributed timer.

**Comment by pferraro** [comment]
This issue was addressed by https://github.com/wildfly/wildfly/commit/a832daabac13112ab7ce7eb43931d18ccaccccc4

**Pull request closed without merging**
