### PR TITLE
[WFLY-13824] adding adjust timeout calls for JMS receive calls

### PR DESCRIPTION
**Pull request by ochaloup**
https://issues.redhat.com/browse/WFLY-13824

### CODE REVIEW

**Comment by ehsavoie** [comment]
Please rebase.

**Comment by ochaloup** [comment]
@bstansberry I verified the failed tests and I can't reproduce them on my local machine. What I can see they are the `DeploymentOverlayCLITestCase` and `ElytronRemoteOutboundConnectionTestCase` that were unstable on other recent PRs. As well the code changes here do not touch the failed test case. I think these are intermittent failures not connected with this PR.

**Review by bstansberry — APPROVED** [review]
Thanks, @ochaloup . I think this is fine. I re-ran the Windows job but not for any great reason as I don't think the failures relates to this PR.

**Pull request merged**
