### PR TITLE
WFLY-9540 Add session operations and details to the Undertow subsystem

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Analysis doc: https://github.com/wildfly/wildfly-proposals/pull/9
https://issues.jboss.org/browse/EAP7-858
https://issues.jboss.org/browse/WFLY-9540

### CODE REVIEW

**Comment by kabir** [comment]
@stuartwdouglas it looks like @jstourac has some feedback on the analysis.
@jstourac is the test coverage adequate from your POV?

**Comment by kabir** [comment]
@jstourac I was about to merge this, but wanted to check with you that this has been preverified and that there is sufficient test coverage somewhere?

**Comment by jstourac** [comment]
@kabir sorry, I missed your comments here. Please wait with the merge, I am going to send an update to this. I'll notify you here then.

**Comment by jstourac** [comment]
I have created PR https://github.com/stuartwdouglas/wildfly/pull/6 that adds some negative tests to this PR. Otherwise this seems good.

**Comment by stuartwdouglas** [comment]
retest this please

**Pull request merged**
