### PR TITLE
WFLY-9793 Upgrade Infinispan to 9.2.0.Final

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-9793

Adds new dependency on io.reactivex.rxjava2:rxjava.
Also includes refactoring of hibernate 2nd level cache modules

### CODE REVIEW

**Comment by jmesnil** [comment]
retest this please

**Review by rjanik114 — APPROVED** [review]

**Comment by rhusar** [comment]
retest this please

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
Failures look related

**Comment by pferraro** [comment]
Closing for investigation.

**Pull request closed without merging**
