### PR TITLE
[WFLY-17404] Upgrade RESTEasy to 6.2.2.Final

### PR DESCRIPTION
**Pull request by jamezp**
https://issues.redhat.com/browse/WFLY-17404

Tag: https://github.com/resteasy/resteasy/releases/tag/6.2.2.Final
Diff: https://github.com/resteasy/resteasy/compare/6.2.1.Final...6.2.2.Final

### CODE REVIEW

**Review by asoldano — APPROVED** [review]

**Comment by jamezp** [comment]
https://issues.redhat.com/browse/RESTEASY-3247 needs to be thought over again. When the `org.jboss.resteasy.microprofile.config`is present, it will load the `org.jboss.resteasy.microprofile.config.ConfigConfiguration`. However, if the `microprofile-smallrye-config` subsystem is not present, the implementation cannot be found.

**Comment by jamezp** [comment]
I've pushed a second commit, but I'm not 100% sure this is how we want to handle it. It some ways it does make sense to handle this way. It works and makes sense to allow different configurations per-deployment though.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @jamezp and @asoldano

**Pull request merged**
