### PR TITLE
[WFLY-17666] Deployments using JNDI over RMI must define dependency on jdk.naming.rmi JPMS module

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-17666

### CODE REVIEW

**Comment by bstansberry** [comment]
@ropalka Can you add a description to the JIRA? Reviewers and maintainers need to have explanations for why changes to existing code are being made.

**Review by darranl — CHANGES_REQUESTED** [review]
Changes requested to Jira issue,

**Comment by ropalka** [comment]
Added @bstansberry - could you review this PR?

**Comment by bstansberry** [comment]
Thanks @ropalka

**Pull request merged**
