### PR TITLE
[WFLY-15046] Add support for connect-timeout in remote cache store (Infinispan)

### PR DESCRIPTION
**Pull request by thomasdarimont**
See: https://issues.redhat.com/browse/WFLY-15046
This introduces support for a `connect-timeout` configuration option to the underlying infinispan remote cache.

Previously Wildfly did not support to configure a `connect-timeout` for
caches with a configured remote store, only `socket-timeout` was supported.
However the underlying infinispan remote store model supports `connect-timeout`.

Having support for timeout allows remote cache configurations such as:
```
# See https://docs.jboss.org/infinispan/11.0/configdocs/infinispan-cachestore-remote-config-11.0.html
echo SETUP: Configure Remote Keycloak cache: work
batch
/subsystem=infinispan/cache-container=keycloak/replicated-cache=work:add()
/subsystem=infinispan/cache-container=keycloak/replicated-cache=work/store=remote:add( \
   cache=work, \
   remote-servers=[ispn-remote-1,ispn-remote-2], \
   passivation=false, \
   fetch-state=false, \
   purge=false, \
   preload=false, \
   shared=true, \
   socket-timeout=${env.KEYCLOAK_REMOTE_ISPN_SOCK_TIMEOUT}, \
   connect-timeout=${env.KEYCLOAK_REMOTE_ISPN_CONN_TIMEOUT} \
)
/subsystem=infinispan/cache-container=keycloak/replicated-cache=work/store=remote:write-attribute(name=properties,value={ \
    rawValues=true, \
    marshaller=org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory, \
    infinispan.client.hotrod.auth_username=${env.KEYCLOAK_REMOTE_ISPN_USERNAME:keycloak}, \
    infinispan.client.hotrod.auth_password=${env.KEYCLOAK_REMOTE_ISPN_PASSWORD:password}, \
    infinispan.client.hotrod.auth_realm=${env.KEYCLOAK_REMOTE_ISPN_REALM:default}, \
    infinispan.client.hotrod.auth_server_name=${env.KEYCLOAK_REMOTE_ISPN_SERVER:infinispan}, \
    infinispan.client.hotrod.trust_store_file_name=${env.KEYCLOAK_REMOTE_ISPN_TRUSTSTORE_PATH:/opt/jboss/keycloak/standalone/configuration/ispn-truststore.jks}, \
    infinispan.client.hotrod.trust_store_type=${env.KEYCLOAK_REMOTE_ISPN_TRUSTSTORE_TYPE:JKS}, \
    infinispan.client.hotrod.trust_store_password=${env.KEYCLOAK_REMOTE_ISPN_TRUSTSTORE_PASSWORD:password} \
    })
run-batch
```

Signed-off-by: Thomas Darimont <thomas.darimont@googlemail.com>

### CODE REVIEW

**Comment by rhusar** [comment]
@thomasdarimont The remote-store is already deprecated. You should be using hotrod store with 'jboss' marshaller (marshaller="jboss") associated with the keycloak module (module="...") instead which allows for configuring connection timeout. Is there any reason why you can't use the hotrod store?

**Comment by thomasdarimont** [comment]
@rhusar thanks for taking a look! I couldn't get the hotrod store configuration to work and only noticed about the deprecation of the remote store while looking [at the code of RemoteStoreServiceConfigurator](https://github.com/thomasdarimont/wildfly/blob/WFLY-15046-Support-Connect-Timeout-for-ispn-remote-cache-store/clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/RemoteStoreServiceConfigurator.java#L53).

I'll try to rework [my configuration for remote cache storage](https://github.com/thomasdarimont/keycloak-project-example/blob/main/deployments/local/cluster/haproxy-external-ispn/cli/0100-onstart-setup-remote-caches.cli) but I think having the connect-timeout support for the old store might still be useful :)

Do you have a link for an example for the hotrod store configuration?

**Comment by darranl** [comment]
@rhusar / @thomasdarimont Do we have a next step for this one?  I am just trying to clean up PRs that don't need to be in the queue yet - is this still being considered?

**Review by rhusar — CHANGES_REQUESTED** [review]
The `store=remote` is deprecated and we don't generally add new features to deprecated resources. 

As a resolution use `store=hotrod` which already supports `connect-timeout` or use a property on the deprecated store instead.

**Pull request closed without merging**
