### PR TITLE
[WFLY-18345] added jdk.security.jgss to module

### PR DESCRIPTION
**Pull request by gaol**
Issue: https://issues.redhat.com/browse/WFLY-18345

### CODE REVIEW

**Comment by jimma** [comment]
Would it be better that we make this dependency as optional ?

**Comment by bstansberry** [comment]
@gaol Thanks! And good news. It looks like this module can reasonably safely be regarded as a 'JRE' module.  @fjuma or @darranl FYI in case you disagree.

For further context, please see https://lists.jboss.org/archives/list/wildfly-dev@lists.jboss.org/thread/U2MYHTRWBDCZ22XT6DIIVETYPFZ2P7DO/ Basically all the 'JRE' distributions I checked include the jdk.security.jgss module.

**Comment by jimma** [comment]
@gaol @bstansberry  This looks good to me as this module exists in all java runtimes.

**Review by jimma — APPROVED** [review]

**Comment by gaol** [comment]
Updated to fix format.

**Pull request merged**
