### PR TITLE
[WFLY-11748] Upgrade hibernate components

### PR DESCRIPTION
**Pull request by langfr**
Upgrade Hibernate components
- Core 5.3.7 --> 5.3.8
- Commons Annotations 5.0.4 --> 5.0.5
- Search 5.10.3 --> 5.10.5

Linked to https://issues.jboss.org/browse/WFLY-11748

### CODE REVIEW

**Comment by bstansberry** [comment]
Thanks! We'll handle any ORM change via #12091.

**Comment by bstansberry** [comment]
@scottmarlow @Sanne Is this ok for WF 16?

**Comment by Sanne** [comment]
@bstansberry looks good. @yrodiere is leading Search now; Yoann you're fine with the Search upgrade?

**Comment by yrodiere** [comment]
@bstansberry @Sanne Yes the Search upgrade is fine. It's mainly changes in the build, an upgrade of ORM dependencies, and a few bugfixes.

**Comment by scottmarlow** [comment]
Hibernate ORM 5.3.8, is using hibernate-common-annotations 5.0.4.Final, not 5.0.5.Final.  @yrodiere does HibernateSearch 5.10.5 work with hibernate-common-annotations 5.0.4.Final?

**Comment by Sanne** [comment]
> Hibernate ORM 5.3.8, is using hibernate-common-annotations 5.0.4.Final, not 5.0.5.Final. @yrodiere does HibernateSearch 5.10.5 work with hibernate-common-annotations 5.0.4.Final?

The only difference is `5.0.5.Final` was compiled with JBoss Logging 3.3.2.Final. I would suggest using `5.0.5.Final`.

**Comment by yrodiere** [comment]
@scottmarlow As Sanne said, `5.0.5.Final` is essentially `5.0.4.Final` compiled against a different JBoss Logging version, no other change: https://github.com/hibernate/hibernate-commons-annotations/compare/5.0.4.Final...5.0.5.Final
So yes it would work, but I think you will want to use `5.0.5.Final` in WildFly.

**Comment by scottmarlow** [comment]
> @scottmarlow @Sanne Is this ok for WF 16?

@bstansberry as per above feedback on hibernate-commons-annotations, the upgrade to version 5.0.5.Final, is fine to include in WF16, as well as the Search  + ORM upgrades.

**Comment by bstansberry** [comment]
Thanks!

**Pull request merged**
