### PR TITLE
WFLY-8389: check for "ssl" and "ssl-context" conflict during add/writ…

### PR DESCRIPTION
**Pull request by michpetrov**
…e-attribute

Issue: [WFLY-8389](https://issues.jboss.org/browse/WFLY-8389)

### CODE REVIEW

**Comment by bstansberry** [comment]
Hi @michpetrov. Thanks for this. There are a couple things that need to be changed. First we don't want to do model validation in performRuntime, as that runs in Stage.RUNTIME and we need to know the model is valid when operation execution exits Stage.MODEL.[1]

Second, when validating across attributes or resources we want to do the validation in an added step. Doing that ensures that validation occurs after all steps that the user as part of a composite op get a chance to run; then we validate the final result. For example a write-attribute and a remove in a composite could end up in a correct state but if we validate in the main write-attribute step, the remove hasn't had a chance to run.

The 2nd commit in https://github.com/wildfly/wildfly/compare/master...bstansberry:pullRequest9816 shows how to do the things I've described. Feel free to squash it into your PR. That commit also makes a small optimization to ModClusterConfigResourceDefinition that isn't really related to this but I something I noticed when looking at your fix.

[1] https://docs.jboss.org/author/display/WFLY/Extending+WildFly#ExtendingWildFly-OperationExecutionandthe%7B%7BOperationContext%7D%7D

**Comment by michpetrov** [comment]
I was looking at how other subsystems do it and e.g. [AbstractDataSourceAdd](https://github.com/wildfly/wildfly/blob/master/connector/src/main/java/org/jboss/as/connector/subsystems/datasources/AbstractDataSourceAdd.java#L120) does some validation inside performRuntime, so I assumed that's the place to do it.

I guess I'm still not clear on how the composite operation is meant to be handled, does the order of steps not matter?

**Comment by bstansberry** [comment]
@michpetrov doing model validation in performRuntime is wrong, so, yes, AbstractDataSourceAdd is wrong there.

Re: order of steps, if it's possible to make it not matter, then that's what we want. It's not intuitively obvious to the user that the write-attribute must come after the remove, and it's possible to not make the order matter, so we should do that.

**Comment by bstansberry** [comment]
Actually, AbstractDataSourceAdd isn't wrong. ELYTRON_ENABLED allows expressions, and expressions can't necessarily be resolved correctly until Stage.RUNTIME, so there is no choice but to wait there.

**Pull request merged**
