### PR TITLE
[WFLY-19073] fix schema link jboss-app_7_0.xsd

### PR DESCRIPTION
**Pull request by baranowb**
Issue: https://issues.redhat.com/browse/WFLY-19073

### CODE REVIEW

**Review by rhusar — APPROVED** [review]
LGTM, TLDR the old link doesn't resolve, the new one does.

**Review by bstansberry — CHANGES_REQUESTED** [review]
@baranowb Please just delete this file. With this change this file becomes the same as the one in JBoss Metadata.

I don't know why this one file was treated differently from all the other schemas that come from JBoss Metadata; I suspect it's just a leftover that was meant to be deleted long ago but was missed. In any case, since the file in JBM has the correct content there's no reason to have the wildfly repo continue to manage this schema.

**Comment by bstansberry** [comment]
LOL @baranowb! I got curious about the reason for this and I find:

https://github.com/wildfly/wildfly/commit/21f50b2535bb93a3d7175020b3e3e23bf83262c5

Commit message is:

'AS7-3401 Temporarily include the jboss-app_7_0.xsd within the AS7 source. Once a new version of JBoss Metadata is released, we'll fetch it from that jar'

I suppose 12 years still counts as 'Temporarily'. :-D

**Review by rhusar — CHANGES_REQUESTED** [review]
Just checking the link fixed in the metadata project and it's correct in there - https://github.com/jboss/metadata/blob/main/ear/src/main/resources/schema/jboss-app_7_0.xsd#L56 - so yes, just delete the file altogether.

**Review by rhusar — APPROVED** [review]
LGTM now

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @baranowb and @rhusar

**Pull request merged**
