### PR TITLE
Add EAP6.2 transformers w/ tests and remove legacy from ejb3 & jca subsystems 

### PR DESCRIPTION
**Pull request by ctomc**
added EAP6.2 tests & transformers for connector subsystems, drop older transformers

Mostly removing to be able to cleanup threads subsystem in core. https://github.com/wildfly/wildfly-core/pull/739

### CODE REVIEW

**Comment by maeste** [comment]
looks good to me

**Comment by bstansberry** [comment]
I just checked out the EAP_6.2.0.GA tag. Looking at JcaExtension I see:

{code}
    private static final int MANAGEMENT_API_MAJOR_VERSION = 1;
    private static final int MANAGEMENT_API_MINOR_VERSION = 2;
    private static final int MANAGEMENT_API_MICRO_VERSION = 0;
{code}

In EJB3Extension it's:

{code}
    private static final int MANAGEMENT_API_MAJOR_VERSION = 1;
    private static final int MANAGEMENT_API_MINOR_VERSION = 2;
    private static final int MANAGEMENT_API_MICRO_VERSION = 1;
{code}

**Comment by ctomc** [comment]
yes, but that both already use Threads 1.1, we are only removing transforming to threads 1.0. 
ejb parser https://github.com/jbossas/jboss-eap/blob/EAP_6.2.0.GA/ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem12Parser.java#L711
jca 
https://github.com/jbossas/jboss-eap/blob/EAP_6.2.0.GA/connector/src/main/java/org/jboss/as/connector/subsystems/jca/JcaExtension.java

**Comment by ctomc** [comment]
ah nevermind my comment, now i see what you meant

**Comment by ctomc** [comment]
this is what fooled me in EJB subsystem:
    @Test
    public void testTransformerEAP610() throws Exception {
        testTransformer_1_2_x(ModelTestControllerVersion.EAP_6_1_0, 1);
    }
which led to believe that 1.2.x was part of 6.1 not 6.2

**Comment by ctomc** [comment]
@bstansberry rebased PR and fixed the code to not remove the wrong transformers.
I also added proper EAP 6.2 transformers & tests for them. Just to make sure we don't break anything.

**Comment by bstansberry** [comment]
@maeste Does this look good? There have been some changes since before.

**Comment by maeste** [comment]
@bstansberry  yup it seems good

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
I asked for the retest because now the job includes the mixed domain tests, and there's a failure there:

http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=59884&buildTypeId=WFPR

**Comment by ctomc** [comment]
looks like the failure is actually correct behavior. before this change there was no transformer to model version 1.2.0 (EAP 6.2.0) 
Will investigate bit more. Could be that it just needs some adjusting for the mixed domain testing

**Pull request merged**
