### PR TITLE
WFLY-19606 Add a workaround for ISPN-16703

### PR DESCRIPTION
**Pull request by rhusar**
Resolves
https://issues.redhat.com/browse/WFLY-19606

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]

**Comment by rhusar** [comment]
Adding hold and testing in our lab.

**Comment by bstansberry** [comment]
@rhusar Can you associate https://issues.redhat.com/browse/WFLY-19606 with this commit and PR? If it fixes the issue that meets the goal of the issue and we can resolve it. Integrating any ISPN-16703 fix would have a corresponding component upgrade JIRA anyway.

**Comment by rhusar** [comment]
> @rhusar Can you associate https://issues.redhat.com/browse/WFLY-19606 with this commit and PR? If it fixes the issue that meets the goal of the issue and we can resolve it. Integrating any ISPN-16703 fix would have a corresponding component upgrade JIRA anyway.

Agreed, updated.

**Comment by rhusar** [comment]
> Adding hold and testing in our lab.
> 
> Update, job: https://ci.wildfly.org/buildConfiguration/WF_MainNightlyJobs_StandardLinuxJdk23?branch=%2FWFLY-19606%3B%2Frhusar&buildTypeTab=overview

@bstansberry Removing hold, the custom build above is finishing any minute now and appears all green. All passed here too. 

So yeah, @luck3y apparently we have a mismatch between JAVA_HOME and the java on the PATH in our CI lab which causes/uncovers this problem.

**Review by pferraro — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @rhusar @pferraro

**Pull request merged**
