### PR TITLE
[WFCORE-639] : ManagementPermissionAuthorizer is limited to the standard roles for its authorizeJmxOperation impl

### PR DESCRIPTION
**Pull request by ehsavoie**
Updating the JSR77ManagementMBeanServer with the new methods.
Requires https://github.com/wildfly/wildfly-core/pull/662

Jira: https://issues.jboss.org/browse/WFCORE-639

### CODE REVIEW

**Comment by ctomc** [comment]
needs rebase, core CR1 is now used in master

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
@ehsavoie It looks like this one got out of sync with the final changes to core.

**Comment by bstansberry** [comment]
This change isn't needed any more; the ultimate WFCORE-639 solution did not add these methods to MBeanServerPlugin.

**Pull request closed without merging**
