### PR TITLE
[WFLY-19530] Add jakarta.activation:jakarta.activation-api to the tes…

### PR DESCRIPTION
**Pull request by bstansberry**
…tsuite/integration/microprofile classpath

https://issues.redhat.com/browse/WFLY-19530

### CODE REVIEW

**Comment by bstansberry** [comment]
@jamezp Please review

**Review by jamezp — APPROVED** [review]
Sorry, I totally thought I did this already. I know I looked at it :)

**Comment by bstansberry** [comment]
Thanks @jamezp

**Pull request merged**
