### PR TITLE
[WFLY-4748] Singleton service fails to start after cluster split

### PR DESCRIPTION
**Pull request by TomasHofman**
... with "Failed to reach quorum of 1"

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
@pferraro does this look ok to you?

**Comment by pferraro** [comment]
ServiceProviderRegistration isn't meant to respond to "channel" group membership changes, but rather "cache" group membership changes.  The appropriate listener registration already exists on line 69.
If there's a bug here (and I suspect there is), it is probably in org.wildfly.clustering.server.group.CacheGroup, i.e. the class responsible for triggering the membershipChanged(...) event.  I'll take a closer look.
@TomasHofman Do you have a test that reproduces the problem?

**Comment by pferraro** [comment]
@stuartwdouglas Please close this PR.  This needs a different fix.

**Comment by pferraro** [comment]
This PR is superceded by https://github.com/wildfly/wildfly/pull/7587

**Pull request closed without merging**
