### PR TITLE
[WFLY-13283] suspending WFTC transaction on response of REST-AT bridge

### PR DESCRIPTION
**Pull request by ochaloup**
https://issues.redhat.com/browse/WFLY-13283

+ enhancing comments related to XTS filters and their ordering
https://issues.redhat.com/browse/WFLY-9455

replaces PR: https://github.com/wildfly/wildfly/pull/13140

### CODE REVIEW

**Comment by ochaloup** [comment]
@asoldano can you please take a look? This is an update of the of discussed PR#13140.

**Comment by darranl** [comment]
@asoldano is this one for you to review?

**Comment by ochaloup** [comment]
@asoldano do you think you may take a look, please?

**Review by asoldano — APPROVED** [review]
Hi @ochaloup and sorry again for the late follow-up. From a REST subsystem perspective this looks ok to me. I'm no sure if the javadoc changes in the WildflyTransactionClientTxBridgeIntegrationHandler.java are related though.

**Comment by ochaloup** [comment]
@asoldano the changes in javadoc is releated in the regards as it talks about the filter ordering and it talks about wrongly to how the process goes. I joint the both changes to this one PR as they both are about filtering of the incoming messages and processing the translational context.
If you think I should create a new WFLY issue I can do so and create a separate PR. WDYT?

**Comment by ochaloup** [comment]
@bstansberry what do you think about merging this? :)

**Comment by bstansberry** [comment]
@ochaloup i kicked off CI again as it hasn't been tested for a while. If it's ok please merge it @asoldano

**Comment by bstansberry** [comment]
It passed before i went to bed so....

**Pull request merged**
