### PR TITLE
[WFLY-9915] Narayana component upgrade to 5.8.0.Final

### PR DESCRIPTION
**Pull request by ochaloup**
https://issues.jboss.org/browse/WFLY-9915

Feature is https://issues.jboss.org/browse/WFLY-9818

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Needs a rebase

**Comment by ochaloup** [comment]
@stuartwdouglas rebased

**Comment by stuartwdouglas** [comment]
Is this actually the feature PR? I have not merged this as I was waiting for the relevant QE analysis + test development to be done, however it sounds like the feature will be something that will need to be enabled via the XTS subsystem?

In that case I think we can just call this a component upgrade rather than a feature, and have a seperate PR for the XTS subsystem changes+tests to enable this new feature.

**Comment by ochaloup** [comment]
@stuartwdouglas : yes, true, this should be called just component upgrade. I'm sorry as I made some mess in the description.
It's as you described. The XTS part needs to be enabled in the XTS subsystem and there will come separate PR for that. The feature request PR enabling the feature will need to be confirmed by QE analysis.

In summary - this is a component upgrade consisting several bug fixes and preparation for the XTS feature being enabled in the WFLY code.

**Pull request merged**
