### PR TITLE
[WFLY-15305] Add the OpenTelemetry extension to the set for which the…

### PR DESCRIPTION
**Pull request by bstansberry**
… wildfly-preview feature pack generates feature specs

https://issues.redhat.com/browse/WFLY-15305

### CODE REVIEW

**Comment by bstansberry** [comment]
WFP tests:

https://ci.wildfly.org/viewLog.html?buildId=273169&tab=buildResultsDiv&buildTypeId=WF_Ee9BootableJarLinuxJdk8
https://ci.wildfly.org/viewLog.html?buildId=273167&tab=buildResultsDiv&buildTypeId=WF_WildFlyPreviewLinuxJdk11

**Comment by jasondlee** [comment]
FWIW, it looks good to me. Hopefully, TC agrees. :)

**Comment by bstansberry** [comment]
It does. The tests that were failing passed on the jobs I linked.

**Comment by jasondlee** [comment]
Ah, OK. I should have guessed. Or clicked through. :)

**Comment by bstansberry** [comment]
I think when you made your "Hopefully" comment they weren't complete yet. :)

**Comment by bstansberry** [comment]
My previous WFP tests were misconfigured; used the wrong branch. I redid them yesterday but the problem was not fixed:

https://ci.wildfly.org/viewLog.html?buildId=273720&buildTypeId=WF_WildFlyPreviewLinuxJdk11
https://ci.wildfly.org/viewLog.html?buildId=273749&tab=buildResultsDiv&buildTypeId=WF_WildFlyPreviewLinuxJdk17

**Review by jasondlee — APPROVED** [review]

**Pull request merged**
