### PR TITLE
[WFLY-15721] Remove org.apache.commons.cli and org.apache.commons.lang3 modules and update wildfly-elytron-tool.jar

### PR DESCRIPTION
**Pull request by fjuma**
https://issues.redhat.com/browse/WFLY-15721

Depends on https://github.com/wildfly/wildfly-core/pull/4879

### CODE REVIEW

**Comment by gaol** [comment]
Downstream PR passed CI with corresponding wildfly-core upgrade, is there a way to test this with the latest main branch of core?

**Comment by yersan** [comment]
@gaol You could use the WildFly integration experiment Jobs to integrate WildFly full with wildly core, as an example for this PR, I've kicked off this one:

https://ci.wildfly.org/viewLog.html?buildId=286134&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments

Sadly, there is no out of the box way to run the Galleon and Bootable Jar Jobs integrated, but if you are interested on those specifics, you can tweak the maven parameters to run those sets by using the "Integration Core experiments" Jobs (e.g adding `-Dts.layers` or `-Dts.bootable`)

**Comment by fjuma** [comment]
@gaol Just re-triggered it.

**Comment by gaol** [comment]
Thank you @fjuma , from the error logs:
```
[INFO] Downloading from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public/org/wildfly/core/wildfly-core-parent/18.0.0.Beta4/wildfly-core-parent-18.0.0.Beta4.pom
[INFO] Downloaded from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public/org/wildfly/core/wildfly-core-parent/18.0.0.Beta4/wildfly-core-parent-18.0.0.Beta4.pom (122 kB at 166 kB/s)
```
I realized that github action uses your branch instead of PR on top of WildFly main branch, so would you please rebase? :)

**Comment by fjuma** [comment]
I've rebased this now.

**Comment by gaol** [comment]
Thanks @fjuma , looks like the test failure this time is temporary because of MRRC unavailability, it should be good if it can be run again, but I don't have permission to re-trigger it. :)

**Comment by fjuma** [comment]
Re-triggered it :)

**Review by darranl — APPROVED** [review]

**Pull request merged**
