### PR TITLE
[19.0.x] WFLY-12681 Provide a 'microprofile' Galleon layer

### PR DESCRIPTION
**Pull request by rhusar**
https://issues.redhat.com/browse/WFLY-12681

Upstream
https://github.com/wildfly/wildfly/pull/12948

### CODE REVIEW

**Comment by luck3y** [comment]
retest this please

**Comment by rhusar** [comment]
retest this please

**Comment by rhusar** [comment]
retest this please

**Comment by rhusar** [comment]
@bstansberry I assume we don't need this either for 19.x, lets close this?

**Comment by bstansberry** [comment]
Closing as this kind of feature work on 19 is done.

**Pull request closed without merging**
