### PR TITLE
WFLY-13159 Datasource resolution fails for application layer alias when using Hibernate bytecode enhancement

### PR DESCRIPTION
**Pull request by scottmarlow**
https://issues.redhat.com/browse/WFLY-13159
https://issues.redhat.com/browse/JBEAP-18803

This is a bug fix that addresses applications that use bytecode enhancing and a DataSource defined by the application (e.g. resource reference).

### CODE REVIEW

**Comment by bstansberry** [comment]
@scottmarlow Perhaps a test case?

**Comment by scottmarlow** [comment]
@bstansberry org.jboss.as.test.integration.jpa.datasourcedefinition.DataSourceDefinitionJPATestCase reproduces the (application datasource via @DataSourceDefinition) bug but we could add additional tests as well that use a resource reference.

**Comment by scottmarlow** [comment]
added test case that uses resource reference.

**Comment by scottmarlow** [comment]
retest this please

**Comment by scottmarlow** [comment]
The resourceref.DataSourceResourceReferenceTestCase failure looks relevant, I'll see if I can recreate that locally.

**Comment by scottmarlow** [comment]
I fixed the added test case that was added for this, so we now have coverage of the two forms of application datasource with JPA bytecode enabled (DataSourceDefinition + resource ref).

**Comment by scottmarlow** [comment]
The Linux JDK11 failure is in XSiteSimpleTestCase.test, that doesn't seem related to this pr.

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
