### PR TITLE
[WFLY-12236] Turn off the INFO Artemis audit logging.

### PR DESCRIPTION
**Pull request by jamezp**
https://issues.jboss.org/browse/WFLY-12236

### CODE REVIEW

**Comment by kabir** [comment]
Please ignore comment - the dep tree analyser job is configured globally to use master as the upstream branch

**Comment by bstansberry** [comment]
@ehsavoie please approve
@jamezp this needs a PR for master once the details are approved

**Review by ehsavoie — APPROVED** [review]

**Comment by bstansberry** [comment]
@jamezp we both dislike these kinds of tests but i wonder if we should add a testsuite/integration/basic test to scan the logs for "org.apache.activemq.audit". Trick is to get it to run late enough in the suite that the messaging tests will have had a chance to generate unwanted logs.

A test like that could be dropped in the future; it would just a be a temporary guard until we're comfortable with how this logging is integrated.

**Comment by jamezp** [comment]
@bstansberry I was actually wondering if I should look at a test that would read a log file and check for repeated messages, with some kind of tolerance, so we could find other messages like this sooner.

That said, sure I could write a test for that. I can pick a test it runs on normally and ensure it runs last.

With regard to the master. I thought @ehsavoie was doing fixing this by updating the configs. If I'm wrong there please let me know and I'll create one.

**Comment by bstansberry** [comment]
@jamezp -- We need the same fix for master. Any downstream change must go upstream first.

Some other change can overwrite that when it's ready. TBH though I suspect some variant of this will remain as I'm extremely reluctant to have this functionality enabled without at least a boolean attribute in the subsystem to turn it on. We'll also have to work through how this relates to things like JSON logging to stdout on the cloud where we want a bit of metadata to allow for discrimination between different 'types' of output. IOW WildFly has an overall logging architecture and we don't just ignore that and throw out whatever.

**Comment by jamezp** [comment]
@bstansberry Okay I created a master PR #12395 and added a test to both.

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
