### PR TITLE
[WFLY-20066] Remove the unused Namespace class

### PR DESCRIPTION
**Pull request by bstansberry**
This addresses a couple non-blocking comments I made on https://github.com/wildfly/wildfly/pull/18470

____

<--- THIS SECTION IS AUTOMATICALLY GENERATED BY WILDFLY GITHUB BOT. ANY MANUAL CHANGES WILL BE LOST. --->

> Wildfly issue links:
> * [WFLY-20066](https://issues.redhat.com/browse/WFLY-20066)

<--- END OF WILDFLY GITHUB BOT REPORT --->

More information about the [wildfly-bot[bot]](https://github.com/wildfly/wildfly-github-bot)

### CODE REVIEW

**Review by xstefank — COMMENTED** [review]
@tomjenkinson I suppose, this will be closed?

**Comment by bstansberry** [comment]
@tomjenkinson @xstefank sure I can rebase this and turn it into just dropping that class.

It's not urgent though so I'll put this on hold to avoid wasting peoples' time.

**Comment by bstansberry** [comment]
@xstefank @tomjenkinson I converted this into just a remove of the cruft Namespace class.

**Review by marcosgopen — APPROVED** [review]
Thank you Brian for removing the unused class.

**Pull request merged**
