### PR TITLE
IIOP Subsystem: attribute groups refactor + migrate operation

### PR DESCRIPTION
**Pull request by tadamski**

### CODE REVIEW

**Comment by bstansberry** [comment]
I created #7399 with just the 1st commit here, as the migration ops stuff needs further review and we don't want to block the 1st commit for it. The migration is more appropriate for WF 10.

**Comment by bstansberry** [comment]
I added the hold flag, until we move master to WF 10.

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Pull request closed without merging**
