### PR TITLE
[WFLY-3659] Enable Digest authentication for web applications backed by JAAS security domains.

### PR DESCRIPTION
**Pull request by darranl**

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

(since I just merged a bunch of other PRs)

**Comment by n1hility** [comment]
retest this please

**Comment by darranl** [comment]
Retest this please

I would struggle to see how this caused any regression as Digest authentication was not working at all previously no tests could be relying on it.  I am just going to rebase anyway so these commits are on top of upstream.

**Comment by darranl** [comment]
Retest this please

**Pull request merged**
