### PR TITLE
WFLY-6604 Clustering API does not expose a proper capability contract

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-6604

Capability support for clustering subsystems, phase 3 of 3:
~~Phase 1: JGroups subsystem~~
~~Phase 2: Infinispan subsystem~~
**Phase 3: Clustering API**

### CODE REVIEW

**Comment by kabir** [comment]
Retest this please

**Comment by kabir** [comment]
@rachmatowicz @rhusar Can one of you please approve? I've had a look, but it is quite big

**Comment by kabir** [comment]
@pferraro Needs some fixing after @rhusar 's transformers PR got merged.

**Comment by pferraro** [comment]
@kabir rebased and fixed.

**Comment by pferraro** [comment]
CI is screwy again. Retest this please.

**Comment by rhusar** [comment]
Missing pull request to https://github.com/wildfly/wildfly-capabilities

**Pull request merged**
