### PR TITLE
[WFLY-18693] Upgrade to SmallRye Reactive Messaging 4.11.0

### PR DESCRIPTION
**Pull request by kabir**
https://issues.redhat.com/browse/WFLY-18693

### CODE REVIEW

**Comment by bstansberry** [comment]
@kabir This kind of thing is going to be problematic for the 'experimental features' thing, as it would lead to flagging up an entire MP interface.

https://github.com/smallrye/smallrye-reactive-messaging/compare/4.9.0..4.10.1#diff-338d8d1e1e397b9122f2f07ea57524bbc47dbaed04afeccd496cd60e89d0750dR73-R75

BTW do we still need to use io.smallrye.reactive:smallrye-reactive-messaging-api for the org.eclipse.microprofile.reactive-messaging.api module?

**Comment by kabir** [comment]
Good catch. I will check if we need to use the API still. I think so since other  stuff relies on that, and I can't see a way to pull in just sections of classes.

**Comment by kabir** [comment]
@bstansberry I've realised this is actually fine. We have a few occurrences of this sort of stuff already, which I dealt with in my initial prototype

**Comment by bstansberry** [comment]
Thanks @kabir

**Pull request merged**
