### PR TITLE
[WFLY-20033] Upgrade WildFly Core to 27.0.0.Beta4

### PR DESCRIPTION
**Pull request by yersan**
Jira issue: https://issues.redhat.com/browse/WFLY-20033

Includes:
 - https://issues.redhat.com/browse/WFLY-19502
 - https://issues.redhat.com/browse/WFLY-16644

---

Tag: https://github.com/wildfly/wildfly-core/releases/tag/27.0.0.Beta4
Diff: https://github.com/yersan/wildfly-core/compare/27.0.0.Beta3...27.0.0.Beta4

---

<details>
<h2>        Bug
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFCORE-7011'>WFCORE-7011</a>] -         Invalid asumption of the remote host stability level when the reported stability level is null
</li>
<li>[<a href='https://issues.redhat.com/browse/WFCORE-7066'>WFCORE-7066</a>] -         Incorrect descriptions for upload-deployment-bytes, upload-deployment-url, upload-deployment-stream
</li>
<li>[<a href='https://issues.redhat.com/browse/WFCORE-7070'>WFCORE-7070</a>] -         Wrong model version for EAP 8.0 exclusions
</li>
<li>[<a href='https://issues.redhat.com/browse/WFCORE-7074'>WFCORE-7074</a>] -         Do not use the ModuleIdentifier.create() method where a module string with a slot can be passed in
</li>
</ul>
    
<h2>        Task
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFCORE-6497'>WFCORE-6497</a>] -         Move JVMServerPropertiesTestCase from WildFly to WildFly Core
</li>
<li>[<a href='https://issues.redhat.com/browse/WFCORE-6904'>WFCORE-6904</a>] -         Bump the kernel management API version to 28.0.0
</li>
<li>[<a href='https://issues.redhat.com/browse/WFCORE-7067'>WFCORE-7067</a>] -         Remove unused Phase.STRUCTURE_APP_CLIENT constant
</li>
</ul>
                                                                                                                                            
<h2>        Component Upgrade
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFCORE-7054'>WFCORE-7054</a>] -         Upgrade BouncyCastle from 1.78.1 to 1.79
</li>
<li>[<a href='https://issues.redhat.com/browse/WFCORE-7068'>WFCORE-7068</a>] -         Upgrade JBoss Modules to 2.1.6.Final
</li>
<li>[<a href='https://issues.redhat.com/browse/WFCORE-7069'>WFCORE-7069</a>] -         Upgrade WildFly Launcher to 1.0.0.Beta2
</li>
<li>[<a href='https://issues.redhat.com/browse/WFCORE-7075'>WFCORE-7075</a>] -         Upgrade WildFly Launcher to 1.0.0.Beta3
</li>
</ul>
        
<h2>        Enhancement
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WFCORE-7063'>WFCORE-7063</a>] -         Remove useless code related to JDK version detection
</li>
<li>[<a href='https://issues.redhat.com/browse/WFCORE-7064'>WFCORE-7064</a>] -         Do not configure testsuite Security Manager options on JDK24+
</li>
<li>[<a href='https://issues.redhat.com/browse/WFCORE-7065'>WFCORE-7065</a>] -         Migrate JBoss Modules module identifier validator from wildfly-clustering-common
</li>
</ul>
</details>

### CODE REVIEW

**Comment by yersan** [comment]
It is built on top of #18430. Mixed domain tests for EAP8 are expected to fail if EAP 8 server has not been included yet in the mixed domain dir.

**Comment by yersan** [comment]
@luck3y Jobs are still complaining about the same error:

`java.lang.RuntimeException: Old version not found in /store/legacy-as/jboss-eap-8.0.0.zip`

Do you have any clue about that? Was EAP 8 added with a different file name?

**Comment by luck3y** [comment]
@yersan I checked them when I copied them earlier, will double check, might have forgotten permissions or something.

**Comment by luck3y** [comment]
Found the issue, I forgot to rsync they agents, I've scripted it now, so shouldn't happen again.

**Comment by luck3y** [comment]
i've requeued those 3 jobs, hopefully will be ok now.

**Review by bstansberry — APPROVED** [review]

**Comment by luck3y** [comment]
@yersan This didn't fail for the same reason, but I'm going to requeue it anyway to see if its just flaky

**Comment by bstansberry** [comment]
Thanks @yersan and @luck3y

**Pull request merged**
