### PR TITLE
WFLY-11897, WFLY-11970 Fix memory leaks caused by SFSB expiration failures

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-11897
https://issues.jboss.org/browse/WFLY-11970

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
@pferraro Sorry; I'd have merged this yesterday but it looked like the CI jobs were still running.

But clicking through the links for the "pending" CI jobs, they all finished (passing) two weeks ago.

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
Triggered a retest since the weird jobs above are fairly old results.

**Comment by pferraro** [comment]
@bstansberry FYI - I've replaced the ready for merge label with a hold label, as I'm going to include WFLY-11970 on top of this.

**Pull request merged**
