### PR TITLE
[WFLY-16923] Correct problematic language in the Credential Store doc…

### PR DESCRIPTION
**Pull request by anilabhabaral**
https://issues.redhat.com/browse/WFLY-16923

### CODE REVIEW

**Review by darranl — APPROVED** [review]

**Comment by anilabhabaral** [comment]
Thanks @darranl . But it needs one of the admins to verify this patch with /ok-to-test in a comment. Could you please do that ?

**Comment by darranl** [comment]
@anilabhabaral TBH the test is not needed, it just takes up CI resources.

**Comment by anilabhabaral** [comment]
Thanks @darranl . Is this PR ready for merge ?

**Comment by bstansberry** [comment]
Thanks @anilabhabaral

**Comment by anilabhabaral** [comment]
Thank you @bstansberry

**Pull request merged**
