### PR TITLE
WFLY-8728 Add support for EJB over HTTP using the legacy security realms

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Review by darranl — CHANGES_REQUESTED** [review]
I really do not want new features to be encouraging further use of the legacy security realms - these are now deprecated ready to be removed in a subsequent release.

They were used for EJB authentication that came in over Remoting but this is now further increasing their visibility at a time we have implement a replacement security project to entirely replace them.

**Comment by stuartwdouglas** [comment]
Failures appear to be caused by https://issues.jboss.org/browse/REM3-275, however I am not sure why they only show up in this PR

**Comment by kabir** [comment]
Retest this please

**Comment by stuartwdouglas** [comment]
This PR will need https://github.com/jboss-remoting/jboss-remoting/pull/112 to fix the failing test

**Comment by kabir** [comment]
Retest this please

**Comment by kabir** [comment]
Retest this please

**Pull request merged**
