### PR TITLE
[WFLY-9107] IIOP: block CLEAR-TEXT socket when secured connections re…

### PR DESCRIPTION
**Pull request by tadamski**
…quired

### CODE REVIEW

**Comment by kabir** [comment]
Retest this please

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
@tadamski I put the fixme label on this as the test failures are recurring. Please ping me when they're gone and I'll remove the label.

**Comment by tadamski** [comment]
I'm refactoring the IIOP SSL testsuite - will reopen when ready.

**Pull request closed without merging**
