### PR TITLE
Ignore intermittently failing DistributedTimerServiceTestCase

### PR DESCRIPTION
**Pull request by bstansberry**
Ignore until WFLY-19139 is resolved.

### CODE REVIEW

**Review by rhusar — APPROVED** [review]
LGTM :( The test is very timing sensitive, especially if we run on slow servers like these

**Review by rhusar — CHANGES_REQUESTED** [review]
Actually, please fix the ignore this using the following:

```
    @BeforeClass
    public static void beforeClass() {
        IntermittentFailure.thisTestIsFailingIntermittently("WFLY-19139");
    }
```

**Comment by bstansberry** [comment]
@rhusar Done

**Review by rhusar — APPROVED** [review]
LGTM now, thanks!

**Review by pferraro — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @rhusar and @pferraro

**Pull request merged**
