### PR TITLE
WFLY-17133 Ensure server socket channels created by NioServer can rebind to the same port on restart.

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-17133

UPDATE: This will require a 5.2.9 JGroups release that contains a fix for https://issues.redhat.com/browse/JGRP-2648

### CODE REVIEW

**Comment by pferraro** [comment]
Adding HOLD label, as I want this validated first by several CI runs.

**Comment by rhusar** [comment]
No need to retest as this requires a (not yet existent) 5.2.9.Final JGroups release and thus is labeled 'hold'.

**Comment by pferraro** [comment]
Removing HOLD label, now that a temporary, yet sufficient workaround is in place.

**Comment by bstansberry** [comment]
Thanks @pferraro

**Pull request merged**
