### PR TITLE
[WFLY-10148] Upgrade Build Tools in preparation for removal

### PR DESCRIPTION
**Pull request by dmlloyd**
https://issues.jboss.org/browse/WFLY-10148

### CODE REVIEW

**Review by jamezp — APPROVED** [review]

**Comment by jamezp** [comment]
retest this please

**Comment by dmlloyd** [comment]
retest this please

**Comment by dmlloyd** [comment]
I don't think the failures are related.

**Comment by dmlloyd** [comment]
The JDK9 failure is known, fixed by https://github.com/wildfly/wildfly/pull/11077

**Pull request merged**
