### PR TITLE
[WFLY-15353] Remove the security-integration module.

### PR DESCRIPTION
**Pull request by darranl**
This follows up on https://github.com/wildfly/wildfly/pull/14714 but I didn't want to delay the main conversion of the subsystem.

https://issues.redhat.com/browse/WFLY-15353

### CODE REVIEW

**Review by bstansberry — DISMISSED** [review]

**Comment by bstansberry** [comment]
The last commit LGTM. Perhaps the CI failures relate to the others.

Anyway, a custom job is at 

https://ci.wildfly.org/viewLog.html?buildId=274761&tab=buildResultsDiv&buildTypeId=WF_WildFlyPreviewLinuxJdk11

**Comment by darranl** [comment]
@bstansberry CI is running again.  I would not say this is a blocker for WildFly 25 - it was just as I was working on converting the subsystem I saw this one was a small follow up step.

**Comment by darranl** [comment]
Added the hold label, lets merge after WildFly 25 is tagged.

**Review by bstansberry — APPROVED** [review]
@darranl This LGTM other than the pom conflict due to my changing the version in the pom you remove. Once you update this please feel free to merge it. I have a great passion for removing stuff this week. :)

**Pull request merged**
