### PR TITLE
[WFLY-14960] Upgrade commons-io from 2.5 to 2.10.0

### PR DESCRIPTION
**Pull request by gaol**
Thanks for submitting your Pull Request!

Please delete this text, and add a link to the Jira issue solved by this PR.

Remember to use the Jira issue ID in the PR title, and any commits.

Issue: https://issues.redhat.com/browse/WFLY-14960

### CODE REVIEW

**Comment by gaol** [comment]
@bstansberry @jimma @jamezp May I ask from you to evaluate this upgrade? thanks :)

**Comment by jimma** [comment]
@gaol  This is good for webservice subsystem.

**Comment by bstansberry** [comment]
@gaol I submitted https://github.com/wildfly/wildfly-core/pull/4650 to see if the core testsuite failure that sparked our hesitancy about moving on from 2.5 is still there. My impression though is that it is.

If it is we're going to have to decide what to do. The biggest issue before was that failure made us concerned about other failures, but if our actual production use of commons-io is looks ok we can deal with the core test thing in some other way.

**Review by jamezp — APPROVED** [review]
I'm sorry. I'm not sure how I missed this notification. This should be fine for RESTEasy.

**Pull request merged**
