### PR TITLE
[WFLY-14261] Integrate MP Health 3.0 into EAP

### PR DESCRIPTION
**Pull request by xstefank**
https://issues.redhat.com/browse/WFLY-14261
https://github.com/wildfly/wildfly-proposals/pull/357

### CODE REVIEW

**Comment by bstansberry** [comment]
I removed the 'missing reqs' label from this because I'm not really controlling this branch and I'll defer to the mergers who are to decide if that label is / is not meaningful for them.

**Comment by kabir** [comment]
@jmesnil this looks fine to me, can you please approve it?

**Review by jmesnil — APPROVED** [review]
this looks good to me

**Pull request merged**
