### PR TITLE
[WFLY-5621] Cleanup messaging XSD schemas

### PR DESCRIPTION
**Pull request by jmesnil**
Remove the jboss-as-messaging-deployment_1_0.xsd schema that is no
longer used. The messaging subsystem has no runtime and these files can
not be used anymore by deployments.

The others XSD files are kept as it is possible to use them to edit
messaging subsystem XML configurations (either for legacy slaves or for
admin-only server prior to migration).

JIRA: https://issues.jboss.org/browse/WFLY-5621

### CODE REVIEW

**Comment by bstansberry** [comment]
:+1 -- only issue is what release to merge it into.

**Comment by bstansberry** [comment]
@jmesnil I'm putting a 11.x label on this just because it doesn't seem critical to remove this in a minor but if you think it should be in 10.1 just ping me. I don't have a strong opinion at all.

**Comment by jmesnil** [comment]
I'm fine with removing these schemas in 11.x

**Comment by jmesnil** [comment]
retest this please

**Pull request merged**
