### PR TITLE
[WFLY-15747] / [WFLY-13889] Remove PicketBox dependency from iiop-openjdk.

### PR DESCRIPTION
**Pull request by darranl**
Raising as a DRAFT as this depends on the following PR:
    https://github.com/wildfly/wildfly/pull/14945

This removes the dependency on PicketBox and removes the legacy code which was using the PicketBox APIs.

### CODE REVIEW

**Comment by darranl** [comment]
@tadamski would it be possible to please review the last commit in relation to iiop-openjdk:
    https://github.com/wildfly/wildfly/pull/14948/commits/3c01a7a867736a92260d380986c52f9cab4b3f71

**Comment by darranl** [comment]
Hi @tadamski if we can please get a review on the last commit on this one I think we can get this merged, this will also mean PicketBox will be out of the way for the Jakarta EE tranformation.

**Review by tadamski — CHANGES_REQUESTED** [review]
hi @darranl LGTM but I believe SECURITY_CLIENT and  SECURITY_IDENTITY would have to be removed from IIOPInitializer as well.

**Comment by darranl** [comment]
Superseded by https://github.com/wildfly/wildfly/pull/15136

**Pull request closed without merging**
