### PR TITLE
WFLY-13900 - Update MyFaces version to 2.3.6

### PR DESCRIPTION
**Pull request by beikov**
https://issues.redhat.com/browse/WFLY-13900

### CODE REVIEW

**Comment by fjuma** [comment]
Thanks @beikov! Just one more change needed for this one - the MyFaces version (`version.org.apache.myfaces.core`) should also be updated from 2.3.1 to 2.3.6 in `wildfly/pom.xml`.

**Comment by fjuma** [comment]
Perfect, thanks. One more small request, please squash the two commits into a single commit.

**Comment by beikov** [comment]
I didn't checkout the repository @fjuma and I'd like to avoid that if possible. Can you squash it through the squash and merge feature of github or do I need to checkout the repository to squash it on the CLI?

**Comment by fjuma** [comment]
It would be better if you could squash it or at least update the second commit message to reference the WFLY JIRA issue. Thanks!

**Comment by beikov** [comment]
I squashed the commits @fjuma

**Review by fjuma — APPROVED** [review]
Thanks very much, @beikov!

**Comment by fjuma** [comment]
Just FYI for other reviewers, the MyFaces 2.3.6 release notes can be found here:

https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=10600&version=12346352

**Comment by bstansberry** [comment]
Thanks, @beikov!

**Comment by erickdeoliveiraleal** [comment]
2.3.7 is out https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=10600&version=12346352

**Comment by fjuma** [comment]
Thanks, @erickdeoliveiraleal. I've created https://github.com/wildfly/wildfly/pull/13797 to upgrade to 2.3.7.

**Pull request merged**
