### PR TITLE
WFLY-15886 Using Objects.equals() in ejb3 DeploymentModuleIdentifier.equals()

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/WFLY-15886

### CODE REVIEW

**Comment by RanabirChakraborty** [comment]
@chengfang Can you review this please?

**Review by chengfang — APPROVED** [review]

**Comment by chengfang** [comment]
@RanabirChakraborty  I updated the JIRA title to be 

"Using Objects.equals() in ejb3 DeploymentModuleIdentifier.equals()"

to make it a bit easier to follow. Can you update the PR title, if you agree?

**Comment by RanabirChakraborty** [comment]
The new Title looks good :) thanks! @chengfang I have updated it.

**Comment by bstansberry** [comment]
Thanks, @RanabirChakraborty

**Pull request merged**
