### PR TITLE
[WFLY-13507] WSBACCoordinator permissions for IBM JDK

### PR DESCRIPTION
**Pull request by baranowb**
Issue: https://issues.redhat.com/browse/WFLY-13057

### CODE REVIEW

**Comment by darranl** [comment]
Issues like this would be easier to review if we could please have stack traces showing the failed permissions checks so we can see the path in relation to the test.

**Review by ochaloup — CHANGES_REQUESTED** [review]
The changes seem reasonable and if needed particularly for the IBM security manager then it's fine.
But, I think similar changeset would be needed for other tests in the XTS testsuite module, wouldn't be?
Or, there is needed to run only this particular test with security manager and it's not necessary for other ones?

**Comment by baranowb** [comment]
Required by other tests as well:
new PropertyPermission("arquillian.debug", "read"),
new PropertyPermission("node0", "read")),

new ReflectPermission("suppressAccessChecks"),
[0m[31m08:18:06,904 ERROR [stderr] (default task-2) java.security.AccessControlException: WFSM000001: Permission check failed (permission "("java.lang.reflect.ReflectPermission" "suppressAccessChecks")" in code source "(vfs:/content/wsba-coordinatorcompletition-test.war/WEB-INF/lib/arquillian-core.jar <no signer certificates>)" of "ModuleClassLoader for Module "deployment.wsba-coordinatorcompletition-test.war" from Service Module Loader")
[0m[31m08:18:06,904 ERROR [stderr] (default task-2) 	at org.wildfly.security.manager.WildFlySecurityManager.checkPermission(WildFlySecurityManager.java:304)
[0m[31m08:18:06,905 ERROR [stderr] (default task-2) 	at org.wildfly.security.manager.WildFlySecurityManager.checkPermission(WildFlySecurityManager.java:201)
[0m[31m08:18:06,905 ERROR [stderr] (default task-2) 	at java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.java:143)
[0m[31m08:18:06,905 ERROR [stderr] (default task-2) 	at org.jboss.arquillian.container.test.spi.util.ServiceLoader.createInstance(ServiceLoader.java:199)
[0m[31m08:18:06,905 ERROR [stderr] (default task-2) 	at org.jboss.arquillian.container.test.spi.util.ServiceLoader.reload(ServiceLoader.java:168)
[0m[31m08:18:06,905 ERROR [stderr] (default task-2) 	at org.jboss.arquillian.container.test.spi.util.ServiceLoader.getProviders(ServiceLoader.java:256)
[0m[31m08:18:06,906 ERROR [stderr] (default task-2) 	at org.jboss.arquillian.container.test.spi.util.TestRunners.getTestRunner(TestRunners.java:57)
[0m[31m08:18:06,906 ERROR [stderr] (default task-2) 	at org.jboss.arquillian.container.test.spi.util.TestRunners.getTestRunner(TestRunners.java:43)
[0m[31m08:18:06,906 ERROR [stderr] (default task-2) 	at org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.executeTest(ServletTestRunner.java:138)
[0m[31m08:18:06,906 ERROR [stderr] (default task-2) 	at org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.execute(ServletTestRunner.java:117)
[0m[31m08:18:06,906 ERROR [stderr] (default task-2) 	at org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.doGet(ServletTestRunner.java:86)


new RuntimePermission("accessDeclaredMembers"),
WildFlySecurityManager.checkPermission(Permission, AccessControlContext) line: 304	
WildFlySecurityManager.checkPermission(Permission) line: 201	
Class<T>.checkMemberAccess(SecurityManager, ClassLoader, int) line: 242	
Class<T>.getDeclaredMethods() line: 972	
MethodSorter.getDeclaredMethods(Class<?>) line: 54	
TestClass.scanAnnotatedMembers(Map<Class<Annotation>,List<FrameworkMethod>>, Map<Class<Annotation>,List<FrameworkField>>) line: 65	
TestClass.<init>(Class<?>) line: 57	
Arquillian(ParentRunner<T>).createTestClass(Class<?>) line: 88	
Arquillian(ParentRunner<T>).<init>(Class<?>) line: 83	
Arquillian(BlockJUnit4ClassRunner).<init>(Class<?>) line: 65	
Arquillian.<init>(Class<?>) line: 58	
NativeConstructorAccessorImpl.newInstance0(Constructor<?>, Object[]) line: not available [native method]	
NativeConstructorAccessorImpl.newInstance(Object[]) line: 83	
DelegatingConstructorAccessorImpl.newInstance(Object[]) line: 57	
Constructor<T>.newInstance(Object...) line: 437	
AnnotatedBuilder.buildRunner(Class<Runner>, Class<?>) line: 104	
AnnotatedBuilder.runnerForClass(Class<?>) line: 86	
AnnotatedBuilder(RunnerBuilder).safeRunnerForClass(Class<?>) line: 59	
AllDefaultPossibilitiesBuilder.runnerForClass(Class<?>) line: 26	
AllDefaultPossibilitiesBuilder(RunnerBuilder).safeRunnerForClass(Class<?>) line: 59	
ClassRequest.getRunner() line: 33	
FilterRequest.getRunner() line: 36	
JUnitCore.run(Request) line: 115	


new RuntimePermission("getClassLoader") - not critical it seems?
WildFlySecurityManager.checkPermission(Permission, AccessControlContext) line: 304	
WildFlySecurityManager.checkPermission(Permission) line: 201	
Class<T>.getClassLoader() line: 501	
JAXBUtils.createEscapeHandler(Class<?>, String) line: 1585	
JAXBUtils.createMininumEscapeHandler(Class<?>) line: 1563	
JAXBDataBinding.setContext(JAXBContext) line: 255	
JAXBDataBinding.initialize(Service) line: 359	
JaxWsServiceFactoryBean(AbstractServiceFactoryBean).initializeDataBindings() line: 86	
JaxWsServiceFactoryBean(ReflectionServiceFactoryBean).buildServiceFromWSDL(String) line: 425	
JaxWsServiceFactoryBean(ReflectionServiceFactoryBean).initializeServiceModel() line: 527	
JaxWsServiceFactoryBean(ReflectionServiceFactoryBean).create() line: 262	
JaxWsServiceFactoryBean.create() line: 199	
JaxWsClientFactoryBean(AbstractWSDLBasedEndpointFactory).createEndpoint() line: 103	
JaxWsClientFactoryBean(ClientFactoryBean).create() line: 91	
JaxWsProxyFactoryBean(ClientProxyFactoryBean).create() line: 159	
JaxWsProxyFactoryBean.create() line: 142	
ProviderImpl$JBossWSServiceImpl(ServiceImpl).createPort(QName, EndpointReferenceType, Class<T>, WebServiceFeature...) line: 492	
ProviderImpl$JBossWSServiceImpl.createPort(QName, EndpointReferenceType, Class<T>, WebServiceFeature...) line: 580	
ProviderImpl$JBossWSServiceImpl(ServiceImpl).getPort(QName, Class<T>, WebServiceFeature...) line: 358	
ProviderImpl$JBossWSServiceImpl(ServiceImpl).getPort(QName, Class<T>) line: 349	
Service.getPort(QName, Class<T>) line: 139	
BACoordinatorCompletionClient.newInstance(String, String) line: 60	
BACoordinatorCompletionClient.newInstance(String) line: 49	
BACoordinatorCompletionTestCase.setupTest() line: 110	
NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
NativeMethodAccessorImpl.invoke(Object, Object[]) line: 90	
DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 55	
Method.invoke(Object, Object...) line: 508	
FrameworkMethod$1.runReflectiveCall() line: 50	
FrameworkMethod$1(ReflectiveCallable).run() line: 12	
FrameworkMethod.invokeExplosively(Object, Object...) line: 47	
RunBefores.evaluate() line: 24	
Arquillian$StatementLifecycleExecutor.invoke() line: 378	



new RuntimePermission("accessClassInPackage.com.sun.org.apache.xerces.internal.jaxp"),
WildFlySecurityManager.checkPermission(Permission, AccessControlContext) line: 304	
WildFlySecurityManager.checkPermission(Permission) line: 201	
SecurityManager.checkPackageAccess(String) line: 1655	
WildFlySecurityManager.checkPackageAccess(String) line: 500	
FactoryFinder.newInstance(String, ClassLoader, boolean) line: not available	
DocumentBuilderFactory.newInstance(String, ClassLoader) line: not available	
SOAPDocumentImpl.createDocument() line: 105	
SOAPDocumentImpl.<init>(SOAPPartImpl) line: 99	
SOAPPart1_1Impl(SOAPPartImpl).<init>(MessageImpl) line: 134	
SOAPPart1_1Impl.<init>(MessageImpl) line: 69	
Message1_1Impl.getSOAPPart() line: 97	
SAAJOutInterceptor.handleMessage(SoapMessage) line: 126	
SOAPHandlerInterceptor.handleMessage(SoapMessage) line: 117	
SOAPHandlerInterceptor.handleMessage(Message) line: 70	
PhaseInterceptorChain.doIntercept(Message) line: 308	
ClientImpl.doInvoke(ClientCallback, BindingOperationInfo, Object[], Map<String,Object>, Exchange) line: 530	
ClientImpl.invoke(BindingOperationInfo, Object[], Map<String,Object>, Exchange) line: 441	
ClientImpl.invoke(BindingOperationInfo, Object[], Exchange) line: 356	
ClientImpl.invoke(BindingOperationInfo, Object...) line: 314	
JaxWsClientProxy(ClientProxy).invokeSync(Method, BindingOperationInfo, Object[]) line: 96	
JaxWsClientProxy.invoke(Object, Method, Object[]) line: 140	
$Proxy184.saveData(ServiceCommand[]) line: not available	
BACoordinatorCompletionTestCase.testWSBACoordinatorCannotComplete() line: 151	



FilePerms:
WildFlySecurityManager.checkPermission(Permission, AccessControlContext) line: 304	
WildFlySecurityManager.checkPermission(Permission) line: 201	
SecurityManager.checkRead(String) line: 901	
WildFlySecurityManager.checkRead(String) line: 369	
UnixPath.checkRead() line: 815	
LinuxFileSystemProvider(UnixFileSystemProvider).checkAccess(Path, AccessMode...) line: 302	
Files.exists(Path, LinkOption...) line: 2396	
FactoryFinder.fromJDKProperties(String, String, ClassLoader) line: 193	
FactoryFinder.find(Class<T>, String) line: 65	
Provider.provider() line: 66	
Service.<init>(URL, QName) line: 82	
Service.create(URL, QName) line: 735	
BACoordinatorCompletionClient.newInstance(String, String) line: 58	


For some reason with current ibm JDK file perms are not critical, though before test did fail.

**Comment by baranowb** [comment]
update with rebase and minor change to two other tests in xts. Mind that for some tests(iirc) inclusion of FilePerms is not required, but it does throw violation during runtime.

**Review by ochaloup — APPROVED** [review]
It seems good to me. From what I can see I would use it as it is.
Thanks for the fix and the update.

**Pull request merged**
