### PR TITLE
[WFLY-18298] Upgrade H2 from 2.2.220 to 2.2.224

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFLY-18928

This aligns us with ORM 6.4

### CODE REVIEW

**Comment by bstansberry** [comment]
@scottmarlow @tadamski please review

**Comment by scottmarlow** [comment]
Hibernate ORM 6.4.* is also using `2.2.224` so this change will be aligned with that.  

https://github.com/h2database/h2database/issues/3944 was reported with 2.2.224 but not clear it the reported `database corruption` can happen with earlier versions as well so that is something to be aware of but still I think we should move forward to 2.2.224.

**Review by scottmarlow — APPROVED** [review]

**Review by tadamski — APPROVED** [review]
I don't see any problems with that update too

**Comment by bstansberry** [comment]
Thanks @scottmarlow and @tadamski

**Pull request merged**
