### PR TITLE
WFLY-10783 Ensure shared transport is always enabled on 7.2.x hosts to avoid port conflicts when multiple channels reference the same protocol stack.

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-10783

### CODE REVIEW

**Review by rhusar — APPROVED** [review]

**Comment by kabir** [comment]
@pferraro I'm afraid I don't see how this relates to the Jira issue? The Jira seems to mention there are problems loading old configs into WF14, but this fix looks like it is in the transformers which implies that the config is loaded ok into WF14 and there is a problem pushing this to older hosts.

**Review by kabir — CHANGES_REQUESTED** [review]
I spoke to Rado. Is the right Jira linked? He also thinks the Jira and the fix don't seem to be the same thing

**Review by rhusar — COMMENTED** [review]
Looking at the Jira now, unless I am overlooking something, the test case does not involve a domain so transformation will not fix the issue.

**Comment by rhusar** [comment]
@pferraro Sounds like we could to read the legacy profile (which relied on transport sharing) and set shared="true" explicitly... or rework how we create those channels.

**Comment by pferraro** [comment]
@rhusar You're right - the use case in the jira only invokes reading an old config - no transformations.  I'll rework this.

**Pull request closed without merging**
