### PR TITLE
Add a workaround for WFLY-20030 ReactiveMessaging* tests fail with podman-machine (macOS/Windows)

### PR DESCRIPTION
**Pull request by rhusar**
Workaround for https://issues.redhat.com/browse/WFLY-20030 until we find a proper solution.

### CODE REVIEW

**Review by kabir — APPROVED** [review]
Just to emphasise, this issue is not happening on CI. It is during local development using podman.

**Comment by rhusar** [comment]
There's a bunch of [issues](https://ci.wildfly.org/buildConfiguration/WF_PullRequest_LinuxSmJdk17/470525?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&expandBuildTestsSection=true&hideProblemsFromDependencies=false&expandBuildChangesSection=true) in the JDK 17 SM job, kick off a few reruns...

**Comment by rhusar** [comment]
Bad news @kabir - these fail consistently and do appear to be a legitimate security manager issue with reactive messaging. Opened https://issues.redhat.com/browse/WFLY-20035 - so sadly, this workaround approach is currently not viable so our tests remain problematic with podman-machine :-(

**Comment by bstansberry** [comment]
@rhusar @kabir I don't get why this would cause SM failures. IOW I'm concerned we have problems elsewhere and somehow this exposed them. The io.vertx.core.logging.LoggerFactory reading the TCCL in a static initializer goes back a long way though, so perhaps this change is somehow causing that static initializer to be run from deployment code whereas before it's always first run from subsystem code.

**Comment by bstansberry** [comment]
Never mind my question; I just read https://issues.redhat.com/browse/WFLY-20035

**Comment by bstansberry** [comment]
Maybe https://github.com/wildfly/wildfly/pull/18466 will fix it.

**Pull request merged**
