### PR TITLE
[WFLY-7300]: OperationHandlers that register DeploymentProcessor should do it only on boot.

### PR DESCRIPTION
**Pull request by ehsavoie**
Extending AbstractBoottimeAddStepHandler instead of AbstractAddStepHandler.

Jira: https://issues.jboss.org/browse/WFLY-7300

### CODE REVIEW

**Comment by kabir** [comment]
This causes all subsystems which could be added post-boot before to now require a reload following an add. @bstansberry I think that warrants a version bump for these subsystems (the version is the same as in the previous eap release)?

**Comment by bstansberry** [comment]
@kabir @ehsavoie What triggers an API version bump is a change in the published API description, not a change in behavior to match the description. So what needs to happen here is the registration of these add handlers needs to be checked, with a correction added for any that don't record themselves as requiring reload. And then a version bump for those.

In reality I think it's likely all of these don't get registered correctly.

I'm not sure what we can do to prevent this kind of mistake being made in the future. Perhaps AbstractDeploymentChainStep can fail with an ISE if !context.isBooting().

**Comment by kabir** [comment]
@bstansberry A quick scan of the operation descriptions for :add operations implemented using AbstractBoottimeAddStepHandler shows that *none* of them report requiring reload, so I think that is a separate issue, and this PR is good.

I've created https://issues.jboss.org/browse/WFLY-7326 to look at using requires-reload for the operations. Since most of these are automagically it would be good if this flag could be added without users needing to create their own OperationDefinitions to create the one created in the background.

**Comment by bstansberry** [comment]
@kabir ok, I agree with what you are saying and this should go in. I filed WFCORE-1871 as well to improve the handling of AbstractDeploymentChainStep that I mentioned in my last comment.

**Comment by bstansberry** [comment]
@ehsavoie I dropped the Ready for Merge from this as it needs to fix more things. org.wildfly.extension.batch.BatchSubsystemDefinition has the same issue as the batch/jberet variant. I don't know if there are others. The test failure on https://github.com/wildfly/wildfly-core/pull/1861 alerted me to the batch problem.

**Comment by ehsavoie** [comment]
This should fix the batch failure.

**Pull request merged**
