### PR TITLE
[23.x][WFLY-14709] Upgrade WF Preview's Glassfish JAXB to 3.0.0 and Istack …

### PR DESCRIPTION
**Pull request by bstansberry**
…to 4.0.0

https://issues.redhat.com/browse/WFLY-14709
Upstream: #14224

### CODE REVIEW

**Comment by bstansberry** [comment]
EE 9 tests:

https://ci.wildfly.org/viewLog.html?buildId=252708&tab=buildResultsDiv&buildTypeId=WF_WildFlyPreviewLinuxJdk11
https://ci.wildfly.org/viewLog.html?buildId=252705&tab=buildResultsDiv&buildTypeId=WF_Ee9BootableJarLinuxJdk8

**Review by ropalka — APPROVED** [review]
LGTM

**Review by scottmarlow — APPROVED** [review]

**Comment by bstansberry** [comment]
@ropalka @jimma @asoldano @darranl @scottmarlow 

The EE 9 tests I linked above are reporting failures.  The two 'org.jboss.as.test.integration.jaxb.unit' ones I have a fix for, no problem.

The others I'm seeing appear to be due to the GlassFish JAXB impl classes having repackaged classes (out of com.sun.xml.bind... into org.glassfish.jaxb.runtime...). And along with this they 'repackaged' some configuration properties (i.e. changed the name of properties users can configure such that they follow the new package names.)

This is problematic in two ways:

1) CXF seems to be using some of these properties:

```
$ git grep \"com.sun.xml.bind | grep -v \/samples\/ | grep -v \/test\/ 
core/src/main/java/org/apache/cxf/common/jaxb/JAXBContextCache.java:            map.put("com.sun.xml.bind.defaultNamespaceRemap", defaultNs);
core/src/main/java/org/apache/cxf/common/jaxb/JAXBContextCache.java:            String pfx = "com.sun.xml.bind.";
core/src/main/java/org/apache/cxf/common/jaxb/JAXBContextCache.java:                fact = ClassLoaderUtils.loadClass("com.sun.xml.bind.v2.ContextFactory",
core/src/main/java/org/apache/cxf/common/jaxb/JAXBContextCache.java:                if (map.containsKey("com.sun.xml.bind.defaultNamespaceRemap")
core/src/main/java/org/apache/cxf/common/jaxb/JAXBContextCache.java:                    && ex.getMessage().contains("com.sun.xml.bind.defaultNamespaceRemap")) {
core/src/main/java/org/apache/cxf/common/jaxb/JAXBContextCache.java:                            map.remove("com.sun.xml.bind.defaultNamespaceRemap"));
core/src/main/java/org/apache/cxf/common/jaxb/JAXBUtils.java:                marshaller.setProperty("com.sun.xml.bind.namespacePrefixMapper",
core/src/main/java/org/apache/cxf/common/jaxb/JAXBUtils.java:            String pkg = "com.sun.xml.bind.";
core/src/main/java/org/apache/cxf/common/jaxb/JAXBUtils.java:                cls = Class.forName("com.sun.xml.bind.api.JAXBRIContext");
core/src/main/java/org/apache/cxf/common/jaxb/JAXBUtils.java:        } else if (className.contains("com.sun.xml.bind")
rt/databinding/jaxb/src/main/java/org/apache/cxf/jaxb/JAXBContextInitializer.java:                unmarshallerProperties.put("com.sun.xml.bind.ObjectFactory", factory);
rt/databinding/jaxb/src/main/java/org/apache/cxf/jaxb/JAXBContextInitializer.java:            refClass = ClassLoaderUtils.loadClass("com.sun.xml.bind.api.TypeReference",
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/AbstractJAXBProvider.java:    protected static final String NS_MAPPER_PROPERTY_RI = "com.sun.xml.bind.namespacePrefixMapper";
rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/provider/JAXBElementProvider.java:    private static final String XML_PI_PROPERTY_RI = "com.sun.xml.bind.xmlHeaders";
```

2) The JBoss fork of the jaxb spec API hard codes some of the  com.sun.xml classes as defaults.

#2 we could potentially solve by updating the JBoss spec fork, either by creating a new branch based on the eclipse EE 9 project, or by a hack that detects whether the jakarta.* namespace is in use (i.e. a class checks its own package name) and then adjusts the default class name accordingly.  The latter is faster but more hacky.

#1 I don't think we can wait for a CXF release, so it seems like something that would need transformer correction via Batavia.  And if we are doing that, it might be the simplest short term fix for #2 as well.

**Comment by scottmarlow** [comment]
With the Batavia approach, do we want to rename the old properties to use the new property names?

Do we want to rename the class references from `com.sun.xml.bind` to `org.glassfish.jaxb.runtime`?

**Comment by bstansberry** [comment]
@scottmarlow The batavia approach won't work. CXF is heavily reliant on the jaxb-ri 2.3.x package structure. Full of code that's dynamically creating class name strings in the com.sun.xml package namespace.

I'm going to close this as it's not really workable.

**Pull request closed without merging**
