### PR TITLE
[WFLY-12931] Upgrade Undertow schema, improve documentation and tests

### PR DESCRIPTION
**Pull request by fl4via**
Upgrade schema and other small tasks needed for WFLY-12473

Jiras:
https://issues.redhat.com/browse/WFLY-12931
https://issues.redhat.com/browse/WFLY-12932
https://issues.redhat.com/browse/WFLY-12933

### CODE REVIEW

**Comment by fl4via** [comment]
The previous build can not be retrieved in CI to be rerun inditidually, because it is too old. I'm asking for a restest because of this

**Comment by fl4via** [comment]
Retest this please

**Comment by bstansberry** [comment]
@fl4via I suspect if this is rebased it can be merged, yes?

**Comment by darranl** [comment]
@fl4via I think this PR is redundant now?  It looks like version 11 of the schema and model has already been committed - can we close this one?

**Comment by fl4via** [comment]
@darranl  Yes, we can. I'll reopen it to submit a PR for the improvements in documentation that it included.

**Pull request closed without merging**
