### PR TITLE
[WFLY-15549] Move WildFly Preview to native Jakarta namespace variant of the Undertow subsystem module

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-15549

### CODE REVIEW

**Comment by ropalka** [comment]
@fl4via @darranl or @bstansberry please review

**Review by yersan — COMMENTED** [review]
@ropalka Would you mind updating the [wildfly-undertow dependency](https://github.com/wildfly/wildfly/blob/62fda980eb93d16b3c23ba3e53e1627e77150ee6/ee-9/source-transform/jaxrs/pom.xml#L88) used by JAX-RS to use the new -jarkarta one as well? I think it makes sense to do it all with this PR.

**Comment by ropalka** [comment]
Fixed @yersan , thanks for pointing that out. I oversaw that JAX-RS dependency.

**Review by yersan — APPROVED** [review]
Adding a symbolic approval looks fine, at least to me.

**Pull request merged**
