### PR TITLE
[WFLY-15150][WFLY-14888] Hibernate ORM to support JDK 17

### PR DESCRIPTION
**Pull request by Sanne**

### CODE REVIEW

**Comment by Sanne** [comment]
for @scottmarlow

**Review by scottmarlow — APPROVED** [review]

**Comment by scottmarlow** [comment]
Thank you very much @Sanne!!! Very much appreciated!

**Comment by scottmarlow** [comment]
This is for https://issues.redhat.com/browse/WFLY-15150

**Comment by bstansberry** [comment]
Here's a run with WF Preview and JDK 17:

https://ci.wildfly.org/viewLog.html?buildId=268937&tab=buildResultsDiv&buildTypeId=WF_WildFlyPreviewLinuxJdk17

**Pull request merged**
