### PR TITLE
WFLY-12164 SSL_KEY_EXCHANGE JGroups protocol should be configured from Elytron capabilities

### PR DESCRIPTION
**Pull request by rhusar**
Jira
https://issues.jboss.org/browse/WFLY-12164
https://issues.jboss.org/browse/EAP7-1333

Proposal
https://github.com/wildfly/wildfly-proposals/pull/244

Schema/model bump
https://github.com/wildfly/wildfly/pull/12504

Blocked by 
~~https://issues.jboss.org/browse/WFLY-12395 Upgrade JGroups to 4.1.4.Final (thus draft PR and CI will fail with compilation error until then)~~

### CODE REVIEW

**Comment by rhusar** [comment]
@jamezp hey James, what else do you need from me to get this merged?

**Comment by jamezp** [comment]
@rhusar The following are still in TODO:

- Community Docs
- Test Plan
- Test Development
- Pre-Check

Those all need to be done before a feature can be merged.

**Comment by darranl** [comment]
@rhusar is this one going to be picked up again to see if a feature team can be formed?

**Comment by darranl** [comment]
@rhusar I think this one doesn't look like a priority at the moment?  Rather than pinging you on the merge conflicts could we close this one and reopen once we are ready to attempt to form a feature team?

**Comment by rhusar** [comment]
Closing for now, we have discussed with @pferraro how to resolve outstanding issues with have with this approach (having to use legacy protocol address to use this).

**Pull request closed without merging**
