### PR TITLE
[WFLY-16944] Clean up references to JSoup

### PR DESCRIPTION
**Pull request by jasondlee**
https://issues.redhat.com/browse/WFLY-16944

- Remove optional module dep on module that doesn't exist 
- Change scope to test

### CODE REVIEW

**Comment by bstansberry** [comment]
@jasondlee @kabir https://github.com/wildfly-extras/wildfly-cloud-tests/pull/28 *may* fix the Cloud Tests job failure we see here.

**Comment by bstansberry** [comment]
I merged https://github.com/wildfly-extras/wildfly-cloud-tests/pull/28 so I kicked off another run of the Cloud Tests job.

**Review by bstansberry — APPROVED** [review]

**Comment by jasondlee** [comment]
> I merged [wildfly-extras/wildfly-cloud-tests#28](https://github.com/wildfly-extras/wildfly-cloud-tests/pull/28) so I kicked off another run of the Cloud Tests job.

Thanks, @bstansberry!

**Comment by bstansberry** [comment]
Thanks @jasondlee

**Pull request merged**
