### PR TITLE
[WFLY-13492] Upgrade WildFly HTTP Client to 1.1.1.Final

### PR DESCRIPTION
**Pull request by fl4via**
Jira: https://issues.redhat.com/browse/WFLY-13492

        Release Notes - WildFly EJB HTTP Client - Version 1.1.1.Final
        
<h2>        Component Upgrade
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WEJBHTTP-38'>WEJBHTTP-38</a>] -         Upgrade components to be in sync with WildFly
</li>
</ul>
                                                                                                                        
<h2>        Bug
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WEJBHTTP-35'>WEJBHTTP-35</a>] -         Discovery result is not completed if no HTTP connections are configured
</li>
</ul>
        
<h2>        Task
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/WEJBHTTP-34'>WEJBHTTP-34</a>] -         Implement discovery for EJB over HTTP
</li>
</ul>

### CODE REVIEW

**Comment by fl4via** [comment]
The reason we are skipping 1.1.0.Final is because the RFE WEJBHTTP-34 was incomplete in that release.

**Comment by bstansberry** [comment]
This is an aspect of https://issues.redhat.com/browse/WFLY-12190, hence the 'feature' label.

**Review by bstansberry — CHANGES_REQUESTED** [review]
@fl4via I believe this would now need to be 1.1.2.

**Comment by bstansberry** [comment]
@fl4via @tadamski AIUI the upgrade to undertow 1.1 is needed to support https://issues.redhat.com/browse/WFLY-12190, so can the upgrade be added in a commit on #12887?

**Comment by fl4via** [comment]
@bstansberry sure, lets add this to the other PR I'm closing this PR and I'm updating the Jira to reflect that the version to be used for wildfly-http-client is now 1.1.2.Final. @tadamski , please go ahead and add the upgrade to #12887 .

**Comment by tadamski** [comment]
@fl4via thanks, I have upgraded my PR but it seems there is no 1.1.2.Final in Nexus yet

**Pull request closed without merging**
