### PR TITLE
Upgrade WildFly Core to 3.0.0.Alpha7

### PR DESCRIPTION
**Pull request by bstansberry**

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
Core release seems to not be visible on nexus.

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by sguilhen** [comment]
retest this please

**Comment by kabir** [comment]
Retest this please

**Pull request merged**
