### PR TITLE
[WFLY-11279] Remove unused dependencies from org.jboss.as.jpa

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.jboss.org/browse/WFLY-11279

### CODE REVIEW

**Comment by yersan** [comment]
I cannot see any direct dependency to the resources exported by these modules from wildfly-jpa.jar, so I think we can increase the list of unused dependencies with:
- javax.annotation.api 
- javax.resource.api
- javax.servlet.api
- org.hibernate.validator
- org.jboss.common-beans
- org.jboss.threads
- org.jboss.msc (This one is used by wildfly-jpa.ja but I think it is redundant since it is being exported by org.jboss.as.server)

I'm not sure if reducing to the extreme the jboss modules dependencies is a good idea, a change in wildfly-jpa code could end up requiring a removed jboss module dependency that will be shown only at runtime, hiding this requirement to the developer at compiler time. Maybe exluding the maven dependencies can help too, but I'm not sure if it is worth the effor.

**Comment by bstansberry** [comment]
@yersan Thanks!  Let's see how discussion of this PR proceeds; if it starts to take a long time I'll ask you to file a separate JIRA for others. Otherwise we can update this one. There was already a discussion about the ones in this PR.

Re: reducing to the extreme, in general if something is unused it shouldn't be listed.  If we don't have sufficient test coverage to detect that a dependency is missing at runtime we should correct that. If there's something subtle about a specific dependency perhaps we can be cautious but even there that's a sign that something overly complex is being done.

I don't mind leaving the org.jboss.msc dependency though. It's rather unfortunate that org.jboss.as.server exports it.  History shows that goes all the way back to 2011, added to solve some testsuite problem.

**Review by pferraro — APPROVED** [review]

**Comment by jamezp** [comment]
My little usage utility shows pretty much what @yersan listed:

- javax.annotation.api
- javax.api
- javax.resource.api
- javax.servlet.api
- org.jboss.common-beans
- org.jboss.threads

The `org.hibernate.validator` _might_ be required by the `org.jboss.as.jpa.validator.WildFlyProviderResolver`. It's a hard-coded string, but may require it runtime too.

**Comment by yersan** [comment]
Yes, you're right @jamezp `org.hibernate.validator` is necessary, thanks for looking at this. From your list, I'm in doubt with  `javax.api`, is not that one exporting the `java.se` and then always required?

**Comment by jamezp** [comment]
@yersan Oops yeah, `javax.api` shouldn't be on my list. It just has no JAR's so it always shows up in my scan.

**Review by jamezp — APPROVED** [review]

**Pull request merged**
