### PR TITLE
WFLY-12318 removing unuseful push/pull in SecurityManager

### PR DESCRIPTION
**Pull request by maeste**
Jira link: https://issues.jboss.org/browse/WFLY-12318

### CODE REVIEW

**Comment by darranl** [comment]
I think CI was playing up, just kicked off the builds again.

**Comment by bstansberry** [comment]
@maeste This is failing CI due to a checkstyle problem:

[10:36:31][Step 2/4] [INFO] --- maven-checkstyle-plugin:3.0.0:checkstyle (check-style) @ wildfly-connector ---
[10:36:32][Step 2/4] [INFO] Starting audit...
[10:36:32][Step 2/4] [ERROR] /store/work/tc-work/bb15431f347cd651/connector/src/main/java/org/jboss/as/connector/services/resourceadapters/deployment/AbstractResourceAdapterDeploymentService.java:31:8: Unused import - javax.security.auth.Subject. [UnusedImports]
[10:36:32][Step 2/4] Audit done.
[10:36:32][Step 2/4] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:checkstyle (check-style) on project wildfly-connector: An error has occurred in Checkstyle report generation.

**Comment by bmaxwell** [comment]
Need to remove 
-import javax.security.auth.Subject;

**Comment by maeste** [comment]
retest this please

**Review by fl4via — APPROVED** [review]

**Pull request merged**
