### PR TITLE
Update Hibernate ORM from 5.0.0 to 5.0.1.

### PR DESCRIPTION
**Pull request by langfr**

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Failure looks related

**Comment by scottmarlow** [comment]
I can recreate this locally by running the ClassFileTransformerTestCase test and then the JPA2LCTestCase test (against the same already running WildFly server instance).

**Comment by scottmarlow** [comment]
Can also recreate now by only running the JPA2LCTestCase test repeatedly.  I don't think we should merge 5.0.1.Final into WildFly 10 with this failure.

**Comment by bstansberry** [comment]
Closing, as it looks like 5.0.1 should not be merged.

**Comment by scottmarlow** [comment]
fyi, I opened https://github.com/wildfly/wildfly/pull/8083 which includes a test workaround for the 2lc failure.  It turned out that two tests were using the same application name, entity classes and query cache.  Locally, I was able to recreate a problem where the query cache contained old results.  I was able to workaround this by changing the second test to use a newer timestamp than the previous test (by sleeping 1 second before creating the Hibernate session).  After verifying the workaround, I changed one of the tests to use a unique application name.

**Pull request closed without merging**
