### PR TITLE
[WFLY-6899] Upgrade to RESTEasy 3.1.0.Beta1

### PR DESCRIPTION
**Pull request by asoldano**
https://issues.jboss.org/browse/WFLY-6899

### CODE REVIEW

**Comment by asoldano** [comment]
mmh... looks like we need Narayana to be update to use RESTEasy 3 api, it's still using RESTEasy 2 api (which are deprecated and eventually removed in 3.1)
@gytis any idea who I can talk with about this?

**Comment by zhfeng** [comment]
It looks like the rest-tx uses it and maybe @mmusgrov have some input here

**Comment by gytis** [comment]
@asoldano , I've raised a JIRA to update Narayana.

**Comment by asoldano** [comment]
@gytis @zhfeng thanks!
I'm closing this PR for now.

**Pull request closed without merging**
