### PR TITLE
WFLY-14216 Update Extended StAX API 1.8.3

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes [WFLY-14216](https://issues.redhat.com/browse/WFLY-14216)

### CODE REVIEW

**Comment by bstansberry** [comment]
@jimma Please review. This used by SAAJ.

**Comment by boris-unckel** [comment]
@jimma Could you please review this? Tests passed.

**Comment by jimma** [comment]
+1 for this upgrade. Thanks @boris-unckel

**Comment by boris-unckel** [comment]
@bstansberry Another one with passed tests and review. Please check and merge.

**Comment by bstansberry** [comment]
Thanks @boris-unckel

**Pull request merged**
