### PR TITLE
[WFLY-18172] Upgrade ASM to 9.5

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-18172

### CODE REVIEW

**Comment by ropalka** [comment]
@jimma is the ASM upgrade compatible with webservice modules?
@scottmarlow is the ASM upgrade compatible with hibernate modules?
@kabir is the ASM upgrade compatible with smallrye modules?

**Review by kabir — APPROVED** [review]
SR uses 9.5 already, e.g  https://github.com/smallrye/smallrye-config/blob/main/pom.xml#L39

**Comment by scottmarlow** [comment]
> @scottmarlow is the ASM upgrade compatible with hibernate modules?

Yes as [Hibernate ORM](https://github.com/wildfly/wildfly/blob/main/ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/org/hibernate/main/module.xml#L26) + Hibernate Search do not depend on ASM (Hibernate ORM 5.3 did but Hibernate ORM 6.0 only depends on bytebuddy which private packages its own copy of ASM).

**Review by scottmarlow — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @ropalka

**Pull request merged**
