### PR TITLE
[WFLY-14186] Update netty.io 4.1.58

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes [WFLY-14186](https://issues.redhat.com/browse/WFLY-14186)
Please find diff and release notes in the Jira ticket.

### CODE REVIEW

**Comment by pferraro** [comment]
:+1: this is fine re: Infinispan.
@ehsavoie Can you review on behalf of ActiveMQ Artemis?

**Comment by ehsavoie** [comment]
@pferraro Artemis team wants to test that version more thoroughly, we should postpone this upgrade

**Comment by pferraro** [comment]
@ehsavoie No problem.  Adding Hold label.

**Comment by boris-unckel** [comment]
@ehsavoie Could you already check ActiveMQ Artemis aspects? All tests for 4.1.58 passed.

**Review by ehsavoie — APPROVED** [review]

**Comment by boris-unckel** [comment]
@pferraro Could you please review for Infinispan again? The version raised to 4.1.58 and all tests passed.

**Comment by pferraro** [comment]
@boris-unckel
> Could you please review for Infinispan again? The version raised to 4.1.58 and all tests passed.

This version looks ok for use with Infinispan.

**Comment by boris-unckel** [comment]
@bstansberry This PR has passed tests and review. Please check and merge.

**Comment by bstansberry** [comment]
Nice. :)

**Pull request merged**
