### PR TITLE
[WFLY-11406] Use new ClassFactory API to fix all remaining JDK12 issues

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.jboss.org/browse/WFLY-11406

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
@ropalka I'm a bit concerned about the failure in the Windows job (https://ci.wildfly.org/viewLog.html?buildId=141340&buildTypeId=WF_PullRequest_WindowsJdk11) as the failed test hasn't failed elsewhere.

I'm starting a new run of that to see if it repeats.

I also ran a bunch of custom jobs with this branch using JDK 12:

https://ci.wildfly.org/viewLog.html?buildId=141375&buildTypeId=WF_MasterElytron (passed)
https://ci.wildfly.org/viewLog.html?buildId=141373&buildTypeId=WF_MasterSecurityManager (2 failures that haven't failed before)
https://ci.wildfly.org/viewLog.html?buildId=141369&buildTypeId=WF_MasterLinuxJdk12 (16 mixed-domain failures; it's known those will not pass so we can ignore that)
https://ci.wildfly.org/viewLog.html?buildId=141371&tab=buildResultsDiv&buildTypeId=WF_MasterWindowsJdk12 (in progress; will have the same mixed-domain failures; has others too)

The WF_MasterSecurityManager one is interesting.

**Comment by bstansberry** [comment]
I kicked off new runs of the two JDK 12 jobs that had 'interesting' results to see if the interesting things recur:

https://ci.wildfly.org/viewLog.html?buildId=141396&buildTypeId=WF_MasterSecurityManager
https://ci.wildfly.org/viewLog.html?buildId=141394&tab=buildResultsDiv&buildTypeId=WF_MasterWindowsJdk12

**Comment by ropalka** [comment]
Hi @bstansberry I believe Windows job failure is not related to this pull request.

**Comment by bstansberry** [comment]
The two failures on the security manager job recur.

WildFlyRootContext.getProviderContext is returning NamingUtils.emptyContext for the "rmi://" scheme. I don't know why.

**Comment by ropalka** [comment]
Trying to reproduce it locally ...

**Comment by bstansberry** [comment]
Good news, bad news...

Good news is the security manager job failure has nothing to do with this PR or with JDK 12. Running the job against master but configured for JDK 11 shows the same failures:

https://ci.wildfly.org/viewLog.html?buildId=141414&buildTypeId=WF_MasterSecurityManager&tab=buildResultsDiv

Bad news is that fails on JDK 11 too.

This is good to merge.

**Pull request merged**
