### PR TITLE
WFLY-10877 Use non-shadow version of Jaeger

### PR DESCRIPTION
**Pull request by jpkrohling**
JIRA: https://issues.jboss.org/browse/WFLY-10877

This PR consumes a new version of Jaeger, whose Thrift version isn't shaded anymore.

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

Please make sure your PR meets the following requirements:
- [x] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue(s)
- [x] Pull Request contains description of the issue(s)
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted

### CODE REVIEW

**Comment by jpkrohling** [comment]
cc @jstourac

**Comment by kabir** [comment]
@psakar I think the licences look ok but okio and libthrift seem to be gradle builds

**Review by kabir — COMMENTED** [review]
@jpkrohling You need to add the licenses for these new dependencies into full-feature-pack-licenses.xml

**Comment by kabir** [comment]
I meant to request changes in my previous comment, adding the fixme label instead

**Comment by kabir** [comment]
Adding the hold label until we have clarified whether @dosoudil and @psakar prefer the shaded or non-shaded option

**Review by jstourac — APPROVED** [review]
Thank you. Looks good to me. It also moves gson to its own module, which is part of the WFLY-10876.

**Comment by jpkrohling** [comment]
Looks like there are two failures, but I don't think they are related to this PR. Are they known to be intermittent?

```
RaTestConnectionTestCase.flushConnections
RaTestConnectionTestCase.testConnection
```

**Pull request merged**
