### PR TITLE
WFLY-11033 mod_cluster custom load metrics fail to load

### PR DESCRIPTION
**Pull request by rhusar**
Jira
https://issues.jboss.org/browse/WFLY-11033

### CODE REVIEW

**Comment by rhusar** [comment]
@honza-kasik Please verify.

**Comment by honza-kasik** [comment]
@rhusar Thanks! I am on it!

**Comment by kabir** [comment]
@honza-kasik please comment when you are done

**Comment by honza-kasik** [comment]
@kabir @rhusar Verified, that custom load metric is now being loaded with both default settings and using custom module with `module` attribute in mod_cluster subsystem.

**Comment by rhusar** [comment]
Thank you @honza-kasik for verification. I have opened a Jira to get a test for this in our testsuite to avoid problems like that.

**Pull request merged**
