### PR TITLE
[WFLY-14841]:Remove dependency on PicketBox from Web Services

### PR DESCRIPTION
**Pull request by jimma**
https://issues.redhat.com/browse/WFLY-14841

### CODE REVIEW

**Comment by fjuma** [comment]
Thanks for working on this, @jimma! It looks like at least some of the failures here are due to some checkstyle issues. Once that's sorted out, if CI passes, one option might be to submit a PR against Darran's branch to get the fixes incorporated into his PR.

**Comment by jimma** [comment]
@fjuma  Looks these checkstyle errors are fixed.

**Comment by bstansberry** [comment]
@jimma Can this be squashed down to 1 or two commits? Thanks.

**Comment by jimma** [comment]
@bstansberry Done.

**Comment by darranl** [comment]
Superseded by https://github.com/wildfly/wildfly/pull/15139

**Pull request closed without merging**
