### PR TITLE
WFLY-5478 allow custom scoped persistence unit name hint (jboss.as.jpa.scopedname) in persistence unit definition.

### PR DESCRIPTION
**Pull request by scottmarlow**
if there is time to merge WFLY-5478 into WildFly 10, let me know so I can update the jira to be fixed in WildFly 10.  We would like to address a Jon issue with EAP 6, by backporting this change (could also go into WildFly 11).

### CODE REVIEW

**Comment by scottmarlow** [comment]
speaking of intermittent failures, retest this please :)

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
restest this please

**Comment by n1hility** [comment]
retest this please

**Pull request merged**
