### PR TITLE
WFLY-11590 Cancelled timer not removed from internal cache when using…

### PR DESCRIPTION
**Pull request by jbaesner**
Fixed issue by removing the timer from the internal timers instance Map

[https://issues.jboss.org/browse/WFLY-11590](https://issues.jboss.org/browse/WFLY-11590)

### CODE REVIEW

**Comment by bstansberry** [comment]
this is ok to test

**Comment by bstansberry** [comment]
@tadamski or @fl4via Please review.

**Review by tadamski — APPROVED** [review]

**Comment by tadamski** [comment]
The PR looks good to me. Failing tests are unrelated.

**Review by bstansberry — APPROVED** [review]
Yep; those failures are definitely unrelated. :)

**Comment by fl4via** [comment]
Retest this please

**Comment by bstansberry** [comment]
@fl4via @tadamski The failure in https://ci.wildfly.org/viewLog.html?buildId=136611&buildTypeId=WF_PullRequest_LinuxSm is probably unrelated to this PR but I wanted to point it out to you regardless.  There's the "Cannot outflow the remote transaction...as its timeout elapsed" problem, which I *may* have seen elsewhere lately. And then there's the permission check failure on tx rollback, which doesn't look good. I'm not familiar enough with FileSystemXAResourceRegistry to know whether it should be doing its file deletion work in a privileged block.

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by fl4via** [comment]
@bstansberry Nice catch. I'm creating Jiras for both issues, the cannot outflow is a bug in the conversion of the timeout, and the security permission to the file should be simple to fix (but that file was created to solve a very important bug, so it is important to have all this ironed out).

**Comment by fl4via** [comment]
@bstansberry I created https://issues.jboss.org/browse/WFTC-56 and https://issues.jboss.org/browse/WFTC-57
If you need WFLY issues for those failures as well, please let me know

**Pull request merged**
