### PR TITLE
WFLY-8664 - Update description of binary-keyed-jdbc-store and mixed-keyed-jdbc-store

### PR DESCRIPTION
**Pull request by rpelisse**
Upstream Issue: [WFLY-8664](https://issues.jboss.org/browse/WFLY-8664)
Issue: [JBEAP-10553](https://issues.jboss.org/browse/JBEAP-10553)

Note that as the changes modifies the schema, I've bump the version to 4.1. I do expect the changes to the subsys are "big enough" to warrant bumping to 5.0, but I may be utterly wrong on that. I also removed a test on a no longer supported storage.

### CODE REVIEW

**Review by pferraro — CHANGES_REQUESTED** [review]
Only changes that affect the parser require a schema version bump.

**Comment by rpelisse** [comment]
@pferraro  OK, so I really need to figure out why not bumping the version lead to some unit test to fail. i assume, wrongly apparently, this was done by designs, to ensure that any changes to the XSD would lead to a version bump. Clearly I'm wrong :)

I'll give it an other stab and let you know.

**Comment by rpelisse** [comment]
Superseed by https://github.com/wildfly/wildfly/pull/10224 - @pferraro As suggested by @kabir I've simply update the XSD to mention the deprecation of the two attributes, rather than removing them from the schema.

**Comment by rpelisse** [comment]
Superseeded by https://github.com/wildfly/wildfly/pull/10224 now merged.

**Pull request closed without merging**
