### PR TITLE
[WFLY-19831] unstable-api-annotation-index package should be provisio…

### PR DESCRIPTION
**Pull request by yersan**
…ned only when preview stability level is enabled

Jira issue: https://issues.redhat.com/browse/WFLY-19831

The tricky part is that dist/build verifications depend on the galleon-pack stability level configuration, so as soon as we change the galleon-pack provisioning all to "community", these verification files will fail since this annotation-index package won't be provisioned. I think it is ok since what we are verifying is what we are provisioning, although making them more dynamic would be better, I guess it could be done with multiple properties (per galleon pack) in the main pom.xml

### CODE REVIEW

**Comment by bstansberry** [comment]
@yersan I don't understand your 'tricky part' comment. Please post some code links or something to illustrate.

The change itself seems ok, but I don't understand the broader context you're discussing.

**Comment by yersan** [comment]
@bstansberry sure, let me try to explain it:

My comment comes from the fact that we are running the `maven-verifier-plugin` for the dist/build maven modules, and these verifications depend on the Galleon Feature Pack stability level configuration. So, as soon as we change the WildFly Galleon Pack stability levels, we will need to change the verifications we are doing, for example, when we move the server from `community` to `default` stability levels. Or even with lower stability levels.

For example, here we are verifying that the annotation index package is provisioned:

https://github.com/wildfly/wildfly/blob/main/dist/src/verifier/verifications.xml#L36-L39

As soon as we change the WildFly Feature Pack `package-stability-level` configuration from `experimental` to `community`, we will need to adjust the `verifications.xml` file to assert the new provisioning. Ideally, a change in the WildFly Feature Pack stability levels should automatically change the `verifications.xml` assertions. That would make it easier to move the server configuration from one stability level to another. 

And, I just wanted to mention that "tricky" possibility I did not investigate further, because I think it is ok since what we are verifying is what we are provisioning, although making them more dynamic would be better.

**Comment by bstansberry** [comment]
@yersan Ok, thanks. I got confused because I looked at the 'build' module verifications.xml, and not 'dist'. And 'build' doesn't include the verifications you're talking about. So then I wasn't confident I understood what you meant.

We can also revert https://github.com/wildfly/wildfly/commit/477d928d37af1b6b2abe90810ac1f901095a6ca6 and update the restored test to do a check of  /core-service=server-environment 'permissible-stability-levels' and throw AssumptionViolatedException. I suggested using verfications.xml but perhaps that was a bad idea.

**Review by bstansberry — DISMISSED** [review]

**Comment by yersan** [comment]
Windows - JDK 17 is unrelated to this. @bstansberry just FYI, this one is blocking the WildFly Core counterpart, I am done with this

**Review by kabir — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @yersan

**Pull request merged**
