### PR TITLE
WFLY-12265 Warning when singleton EJB implements SessionBean interface

### PR DESCRIPTION
**Pull request by TomasHofman**
https://issues.jboss.org/browse/WFLY-12265

### CODE REVIEW

**Comment by TomasHofman** [comment]
Looks test case is failing with security manager.

**Review by chengfang — CHANGES_REQUESTED** [review]
I think the warning message should indicate that implementing SessionBean interface is ignored (the action taken by ejb container), and what the application should do to fix it (remove the implement SessionBean clause).

**Comment by TomasHofman** [comment]
@chengfang I updated the message to:

> [EJB3.2 spec, section 4.9.2] Singleton session beans are not allowed to implement 'javax.ejb.SessionBean' interface. This interface on bean '%s' is going to be ignored and should be removed.

**Review by chengfang — APPROVED** [review]

**Comment by TomasHofman** [comment]
Rebased.

**Pull request merged**
