### PR TITLE
WFLY-5497 Add <distributable/> to shared-session-config schema

### PR DESCRIPTION
**Pull request by pferraro**
JIRA:
https://issues.jboss.org/browse/WFLY-5497
Design doc:
https://github.com/wildfly/wildfly-proposals/pull/114

Requires:
https://github.com/wildfly/wildfly/pull/11476

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
The 2 commits in this PR that go beyond what's in #11476 LGTM.

**Review by simkam — CHANGES_REQUESTED** [review]
There is one more place in upstream documentation that probably deserves update to new schema version - https://github.com/wildfly/wildfly/blob/master/docs/src/main/asciidoc/_developer-guide/Web_(Undertow)_Reference_Guide.adoc

**Comment by pferraro** [comment]
> There is one more place in upstream documentation that probably deserves update to new schema version - https://github.com/wildfly/wildfly/blob/master/docs/src/main/asciidoc/_developer-guide/Web_(Undertow)_Reference_Guide.adoc

Done.

**Review by simkam — APPROVED** [review]
QE approves, two commits on top of #11476. Should be merged after #11476.

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
