### PR TITLE
[WFLY-6402] Propagate startup execution privilege to asynchronous methods

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
@kurobako please let me know if anything in here does not look right.

**Comment by dmlloyd** [comment]
Supercedes #8989.

**Comment by dmlloyd** [comment]
We're good to go now!

**Comment by mr-rycho** [comment]
Hello, I've recently came across this code and I think there may be a bug in there. In short: is the ordering below correct?
STARTUP_AWAIT_INTERCEPTOR = 0x248;
SINGLETON_CONTAINER_MANAGED_CONCURRENCY_INTERCEPTOR = 0x240; 
Because I think I have a situation that causes a deadlock. The scenario is as follows:
- startup singleton A's initialization starts and completes successfully
- startup singleton B is initializing and during that it starts a task X via managedThreadExecutor
- X wants to access A and is blocked by StartupCountdown.await
- meanwhile B continues initializing and wants to access A but X already holds a lock on A (I can see ContainerManagedConcurrencyInterceptor.processInvocation in the tread dump) hence after 5000ms B's initialization fails as well as whole deployment
I think that this may be solved by switching the ordering of these two interceptors.
There still is a thing I cannot understand: this task X is accesing bean C that in turn accesses A. So before the execution goes inside C, the thread is on hold on the startupAwait interceptor - this is fine. However I also have a startup singleton bean D that sets up a timer and in the timeout method it accesses A. The weird thing is the thread goes inside D and stops when it tries to access A. Shouldn't StartupAwaitInterceptor block enetering D as well? Because I've seen it's registered for D inside StartupAwaitDeploymentUnitProcessor ... unless timeout interceptors are different and do not contain this startup await interceptor, do they?

**Comment by mr-rycho** [comment]
I could reproduce it on 20.0.1 and reported it here: https://issues.redhat.com/browse/WFLY-13686

**Pull request merged**
