### PR TITLE
[WFLY-12275] Add documentation for the enhanced audit logging - RFC support and Configuring Reconnects

### PR DESCRIPTION
**Pull request by justinmcook**
https://issues.jboss.org/browse/WFLY-12275

Depends on https://github.com/wildfly/wildfly-core/pull/3856

### CODE REVIEW

**Comment by fjuma** [comment]
@justinmcook Please update the description here just to indicate that this PR requires your Core PR to be merged. Thanks!

**Comment by justinmcook** [comment]
@fjuma Updated the description

**Review by jamezp — CHANGES_REQUESTED** [review]
I'm requesting just a couple of changes because of the change in the behavior of the Elytron implementation. I don't want this to hold up the feature being merged as it's a minor documentation fix is all.

**Comment by justinmcook** [comment]
@jamezp Updated the documentation to reflect the changes in Elytron

**Review by jamezp — APPROVED** [review]

**Pull request merged**
