### PR TITLE
WFLY-5646 Stabilize SingletonServiceTestCase

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-5646

Also code cleanup: Use default methods to eliminate duplicate enum logic.

### CODE REVIEW

**Comment by pferraro** [comment]
Oh, you bastard....
Let me fix this test once and for all.

**Comment by rhusar** [comment]
:+1: Looks good.

**Comment by pferraro** [comment]
So far so good - let's run a few more times to make sure.  Retest this please.

**Comment by pferraro** [comment]
Good - again.  Retest this please.

**Comment by pferraro** [comment]
Retest this please.

**Pull request merged**
