### PR TITLE
[WFLY-9472] added test for Jbeap-13298

### PR DESCRIPTION
**Pull request by jstourac**
Issue: https://issues.jboss.org/browse/WFLY-9472

### CODE REVIEW

**Review by darranl — CHANGES_REQUESTED** [review]
As this is to the upstream repo only WFLY Jiras should be referenced not JBEAP Jiras.

**Comment by kabir** [comment]
@jstourac please amend the commit messages

**Comment by jstourac** [comment]
Thank you @daran and @kabir for looking into this. I have updated commit message to mention WFLY Jira only. Please review.

**Comment by jstourac** [comment]
Windows job states 'execution timeout'. Although, as only update in this PR since last testrun was just commit message update and previous testrun was successful for all jobs, I believe this is just a glitch.

**Pull request merged**
