### PR TITLE
[JBWS-3797]:More refactor

### PR DESCRIPTION
**Pull request by jimma**

### CODE REVIEW

**Comment by jimma** [comment]
retest this please

**Comment by jimma** [comment]
retest this please

**Comment by bstansberry** [comment]
@asoldano please approve.

The org.jboss.as.test.integration.jpa.cfgfile.CfgFileTestCase failure is unrelated.

**Comment by asoldano** [comment]
As long as this introduces no regressions in AS and JBWS testsuite, it's approved. Thanks Jim.

**Comment by kabir** [comment]
@jimma Can you confirm the JBWS testsuite passes?

**Comment by jimma** [comment]
@kabir Yes. I can confirm this won't break JBWS testsuite. Thanks.

**Pull request merged**
