### PR TITLE
WFLY-13942 Remove the modules supporting Hibernate ORM 4.1 and 4.3

### PR DESCRIPTION
**Pull request by Sanne**
https://issues.redhat.com/browse/WFLY-13942

Please @scottmarlow could you review, and decide which version should have this. I've left the "fix versions" field in JIRA unspecified.

cc/ @bstansberry @pferraro FYI

### CODE REVIEW

**Comment by kabir** [comment]
@scottmarlow Can you please take a look? 
@Sanne this conflicts now (probably just because those deleted pom files had the version updated), can you rebase?

**Comment by Sanne** [comment]
Rebased. It's in your hands @scottmarlow ! Thanks

**Comment by Sanne** [comment]
Is this a good time?

**Comment by scottmarlow** [comment]
> Is this a good time?

@Sanne yes now is a good time to make this change.

**Comment by Sanne** [comment]
Thanks @scottmarlow . I've now rebased it - but haven't tested it locally, I'm a bit rusty regarding WildFly code so I hope we can rely on your review and CI tests.

**Comment by scottmarlow** [comment]
> Thanks @scottmarlow . I've now rebased it - but haven't tested it locally, I'm a bit rusty regarding WildFly code so I hope we can rely on your review and CI tests.

:+1:

**Review by scottmarlow — APPROVED** [review]

**Comment by darranl** [comment]
@scottmarlow does this have any impact on community documentation / EAP documentation or any testing undertaken by QE?

**Comment by scottmarlow** [comment]
> @scottmarlow does this have any impact on community documentation / EAP documentation or any testing undertaken by QE?

Good question @darranl, the [EAP documentation](https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.4/html/migration_guide/application_migration_changes#hibernate_and_jpa_migration_changes) will be impacted.  

Regarding community documentation that needs some changes:
- https://github.com/wildfly/wildfly/blob/master/docs/src/main/asciidoc/_developer-guide/How_do_I_migrate_my_application_from_AS7_to_WildFly.adoc 
- https://github.com/wildfly/wildfly/blob/master/docs/src/main/asciidoc/_developer-guide/Spring_applications_development_and_migration_guide.adoc 
- https://github.com/wildfly/wildfly/blob/master/docs/src/main/asciidoc/_developer-guide/Class_Loading_in_WildFly.adoc

There should be no test effort impact as EAP doesn't support use of Hibernate 4.x.

**Pull request merged**
