### PR TITLE
[WFLY-16087] Remove unsupported test jars from Wildfly source zip

### PR DESCRIPTION
**Pull request by moulalis**
Issue: https://issues.redhat.com/browse/WFLY-16087

### CODE REVIEW

**Comment by bstansberry** [comment]
Please use draft pull requests for things not ready for review: https://github.blog/2019-02-14-introducing-draft-pull-requests/

Please look into the Shrinkwrap Resolver. https://dzone.com/articles/using-shrinkwrap-maven. I haven't used it myself but I see that the MP OpenTracing TCK does and it seems cleaner than copying files around.

**Comment by moulalis** [comment]
> Please use draft pull requests for things not ready for review: https://github.blog/2019-02-14-introducing-draft-pull-requests/
> 
> Please look into the Shrinkwrap Resolver. https://dzone.com/articles/using-shrinkwrap-maven. I haven't used it myself but I see that the MP OpenTracing TCK does and it seems cleaner than copying files around.

Thanks for the info @bstansberry

**Comment by gaol** [comment]
@moulalis or you can try with the [MavenResolver from jboss-module](https://github.com/jboss-modules/jboss-modules/blob/1.12.0.Final/src/main/java/org/jboss/modules/maven/MavenResolver.java#L39), like:
```
war.addAsLibrary(MavenResolver.createDefaultResolver().resolveJarArtifact(new ArtifactCoordinates("groupId", "artifactId", "version")));
```

**Review by darranl — CHANGES_REQUESTED** [review]
Can we please loose the references to EAP, this is the WildFly source zip being affected by this PR.

**Comment by xstefank** [comment]
@darranl should be ready for review again

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks, @moulalis

**Pull request merged**
