### PR TITLE
TEST ONLY clustering failures test

### PR DESCRIPTION
**Pull request by tadamski**
Thanks for submitting your Pull Request!

Please delete this text, and add a link to the Jira issue solved by this PR.

Remember to use the Jira issue ID in the PR title, and any commits.

### CODE REVIEW

**Comment by tadamski** [comment]
retest this please

**Comment by kabir** [comment]
@tadamski From the title it looks like it should not be merged so I am adding the hold label. If that is wrong let me know

**Comment by tadamski** [comment]
@kabir  yes, this should not be merged - I will close it soon

**Comment by bstansberry** [comment]
@tadamski Should this be closed?

**Comment by tadamski** [comment]
@bstansberry  yes, I forgot to close it; closing now

**Pull request closed without merging**
