### PR TITLE
WFLY-5422/WFLY-5473 SSO is not destroyed after session invalidation or after all associated sessions timeout.

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-5422
https://issues.jboss.org/browse/WFLY-5473

This PR requires wildfly-core 2.0.0.CR9 containing Undertow 1.3.4.Final pulling in this fix:
https://github.com/undertow-io/undertow/pull/340

This PR modifies our distributable session manager to delegate expiration events to undertow session listeners (including SingleSignOnAuthenticationMechanism's SessionInvalidationListener) rather than notifying the application listeners directly. This results in overlapping tx contexts between the SSOManager and the SessionManager - which is now properly handled.

Includes the test case contained in #8210

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by pferraro** [comment]
This PR might need some slight adjustments to adapt to some of the other recent commits that were merged.

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by pferraro** [comment]
OK - this looks good now.

**Pull request merged**
