### PR TITLE
WFLY-13566 Ensure that Jandex indexes are released from JPA deployment memory after deployment completes

### PR DESCRIPTION
**Pull request by scottmarlow**
https://issues.redhat.com/browse/WFLY-13566

### CODE REVIEW

**Comment by scottmarlow** [comment]
The org.jboss.as.test.integration.ejb.management.deployments.EjbInvocationStatisticsTestCase test passes for me locally and it doesn't use JPA, so it appears unrelated to this pr.  

```
mvn clean install -Dtest=org.jboss.as.test.integration.ejb.management.deployments.EjbInvocationStatisticsTestCase

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
BUILD SUCCESS
```

**Comment by scottmarlow** [comment]
Retest this please.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @scottmarlow.

JIRA isn't working for me right now so please check back on the JIRA and resolve it if it remains unresolved.

**Comment by scottmarlow** [comment]
Thanks @bstansberry JIRA is back up, I resolved the https://issues.redhat.com/browse/WFLY-13566 issue.

**Pull request merged**
