### PR TITLE
WFLY-7618: fix code not to use default platform dependant encoding

### PR DESCRIPTION
**Pull request by michpetrov**
Issue: https://issues.jboss.org/browse/WFLY-7618

### CODE REVIEW

**Comment by kabir** [comment]
@michpetrov The same tests appear to fail on all platforms, so I presume it is caused by this PR

**Comment by michpetrov** [comment]
@kabir fixed and rebased

**Comment by kabir** [comment]
@michpetrov checkstyle problems in testsuite/integration/basic

**Comment by michpetrov** [comment]
rebased again

**Comment by jamezp** [comment]
retest this please

**Comment by bstansberry** [comment]
I corrected the problems in #11835 and merged this. Thanks!

**Pull request closed without merging**
