### PR TITLE
WFLY-16819 Upgrade SmallRye Fault Tolerance to 6.0.0

### PR DESCRIPTION
**Pull request by rhusar**
Resolves
https://issues.redhat.com/browse/WFLY-16819

### CODE REVIEW

**Review by kabir — APPROVED** [review]
You beat me to it :-)

(I've been doing most of the other upgrades)

**Review by kabir — APPROVED** [review]

**Comment by rhusar** [comment]
@kabir Haha, though, honestly, these are ideally best left to the component owners.

**Comment by bstansberry** [comment]
@rhusar Well, since these are best left to the component owner, can you fix the merge conflict? Otherwise I'd have done it via the github ui. ;-D

**Comment by rhusar** [comment]
@bstansberry Haha, that's our daily routine anyway by now :-)

**Comment by bstansberry** [comment]
Thanks @rhusar

**Pull request merged**
