### PR TITLE
WFLY-11767 Remove unused dependencies from org.jboss.as.connector

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/WFLY-11767

### CODE REVIEW

**Comment by bstansberry** [comment]
@maeste Any concerns?

The org.jboss.jts module provides org.jboss.narayana.jts:narayana-jts-idlj and none of the packages in that artifact are used by org.wildfly:wildfly-connector. The org.jboss.narayana.jts:narayana-jts-idlj artifact's META-INF/services has an entry for the CDI Extension interface, but that's not something org.wildfly:wildfly-connector would be loading. So this looks unused to me.

**Comment by maeste** [comment]
@bstansberry LGTM

**Comment by bstansberry** [comment]
Thanks @RanabirChakraborty.

JIRA isn't working for me right now so please check back on the JIRA and resolve it if it remains unresolved.

**Comment by RanabirChakraborty** [comment]
Thank you! @bstansberry I have marked it as Resolved.

**Pull request merged**
