### PR TITLE
WFLY-19070 Remove the narayana compensations module

### PR DESCRIPTION
**Pull request by TomasHofman**
https://issues.redhat.com/browse/WFLY-19070

### CODE REVIEW

**Comment by mmusgrov** [comment]
@TomasHofman the PR looks reasonable, I do not have a great deal of knowledge of this module but if the tests pass I will be ok approving it. @marcosgopen do you see any potential issues with Thomas' PR?

Thomas, you say it is "Work in progress", what other work will it take to complete the task?

**Comment by TomasHofman** [comment]
@mmusgrov mainly I wanted to see the complete test results, and I'm looking for any remaining bits. I think I can see some license files etc that should be pruned. But the main piece of work is done I believe.

**Comment by TomasHofman** [comment]
The license file appears to be clean after all, they contain much less stuff than on the EAP side.

**Comment by TomasHofman** [comment]
Ccing also @marekkopecky , if he wants to review.

**Comment by istudens** [comment]
@marcosgopen @marekkopecky can this one be reviewed please? downstream depends on it

**Comment by marekkopecky** [comment]
This PR seems to be in sync with the decisions on WFLY-19070 and related jiras.

**Review by marcosgopen — APPROVED** [review]
Thanks @TomasHofman for your PR, LGTM.

**Comment by bstansberry** [comment]
Thanks @TomasHofman and @marcosgopen

**Pull request merged**
