### PR TITLE
WFLY-5317 Upgrade to jboss-el-api_3.0_spec 1.0.5.Final (bean properties map is now allowed to be cleared)

### PR DESCRIPTION
**Pull request by scottmarlow**

### CODE REVIEW

**Comment by scottmarlow** [comment]
@stuartwdouglas @jamezp are there any other changes that go with the https://github.com/jboss/jboss-el-api_spec/commit/643296ef56423c81b9a6ef8c9d8bd8632d58b99e fix?

**Comment by n1hility** [comment]
Retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
Retest this please

**Comment by n1hility** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Pull request merged**
