### PR TITLE
[WFLY-11354] Refactoring webservices subsystem to use non deprecated ServiceBuilder methods

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.jboss.org/browse/WFLY-11354

### CODE REVIEW

**Comment by ropalka** [comment]
Please review @asoldano .

**Comment by asoldano** [comment]
@ropalka what's the goal and gain with these changes?

**Comment by ropalka** [comment]
The goal is to get rid of MSC deprecated methods in near future @asoldano .

**Comment by ropalka** [comment]
I forgot to mention that I reviewed all usages of webservices subsystem in all dependent products and it is safe to refactor it.

**Review by asoldano — COMMENTED** [review]
@ropalka , it looks like no regression is introduced by these changes (QA verified with the whole JBWS testsuite); I'm still not really grasping the benefit here, however if all the subsystems are going to be refactored this way for a reason, I'm fine.

**Comment by ropalka** [comment]
Yes @asoldano , all subsystems are going to be changed thsi way.
SAR subsystem is already refactored (and merged), WEBSERVICES subsystem is here
and I have WELD subsystem refactoring finished locally (will send PR today).
Others are going soon.

**Comment by rsvoboda** [comment]
> QA verified with the whole JBWS testsuite

This is not true, we executed server management tests for ws subsytem. Not the JBWS testsuite.

And there is regression due to this PR, Jan commented on https://issues.jboss.org/browse/WFLY-11354
There is test failing with NPE - https://github.com/jbossws/jbossws-cxf/blob/master/modules/testsuite/shared-tests/src/test/java/org/jboss/test/ws/publish/EndpointPublishTestCase.java

**Comment by kabir** [comment]
@ropalka / @asoldano - please see @rsvoboda 's comment above about a regression

**Comment by asoldano** [comment]
@rsvoboda sorry, misunderstood what you told me.

**Comment by ropalka** [comment]
Fixed @kabir @asoldano @rsvoboda in https://github.com/wildfly/wildfly/pull/11866

**Pull request merged**
