### PR TITLE
WFLY-6576 mod_cluster advertise="false" does not disable advertise if…

### PR DESCRIPTION
**Pull request by rhusar**
… there are no proxies configured

Jira
https://issues.jboss.org/browse/WFLY-6576

### CODE REVIEW

**Comment by bstansberry** [comment]
Looks good to me. @pferraro please approve.

**Comment by rhusar** [comment]
@jfclere Any problem with this "functionality" going away?

**Comment by stuartwdouglas** [comment]
@pferraro @jfclere do either of you have anything to add?

**Comment by jfclere** [comment]
That looks good for me. @pferraro any comments?

**Comment by pferraro** [comment]
:+1:

**Pull request merged**
