### PR TITLE
[WFLY-19924] - OpenTelemetry quickstart application logs warning with NoClassDefFoundError exceptionafter URL request

### PR DESCRIPTION
**Pull request by jasondlee**
https://issues.redhat.com/browse/WFLY-19924

Add netty module dep
Set netty default logger factory

### CODE REVIEW

**Review by emmartins — APPROVED** [review]
LGTM, opentelemetry tracing qs provisioned with this branch no longer throws the exception

**Review by jamezp — COMMENTED** [review]
LGTM. Should we also do `org.wildfly.extension.microprofile.telemetry.MicroProfileTelemetryExtension` as well? It also uses `io.smallrye.opentelemetry` which has a dependency on `io.vertx.core` which in turn as a dependency on `io.netty.netty-common`.

**Comment by jasondlee** [comment]
> LGTM. Should we also do `org.wildfly.extension.microprofile.telemetry.MicroProfileTelemetryExtension` as well? It also uses `io.smallrye.opentelemetry` which has a dependency on `io.vertx.core` which in turn as a dependency on `io.netty.netty-common`.

All the MP Telemetry module does is allow a deployment to override otel server config via MP Config. All the real work is still done by the `opentelemetry` subsystem, so I don't think it's necessary to update both.

**Review by jamezp — APPROVED** [review]

**Review by jamezp — APPROVED** [review]

**Comment by jamezp** [comment]
FYI I've queued a new CI job for the failed Galleon Linux run as it doesn't look related.

**Comment by bstansberry** [comment]
Thanks @jasondlee and @jamezp

**Pull request merged**
