### PR TITLE
JBEAP-12014 WFLY-8418 update spec jars to include proper licence info

### PR DESCRIPTION
**Pull request by ctomc**

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
@ctomc if this passes CI and I don't come back to merge it, please ping me. I'm making one of my occasional dives into the WF full PR queue but I tend to not come back for a while and leave things hanging.

**Comment by bstansberry** [comment]
@ctomc Is the only diff in any of these releases the license info stuff? If so I'll merge it on my own. Otherwise, @stuartwdouglas @asoldano @darranl please approve.

**Comment by ctomc** [comment]
@bstansberry This updates only have license info stuff changed, noting else was change at the time.

**Comment by darranl** [comment]
My only comment is this should really have a WFLY Jira not a JBEAP Jira.

**Comment by ctomc** [comment]
@darranl it does have it now, 
@stuartwdouglas rebased

**Pull request merged**
