### PR TITLE
[WFLY-17349] cloned org.jboss.as.test.integration.jpa.hibernate.entit…

### PR DESCRIPTION
**Pull request by istudens**
…y entities into seperate entities for webtxem tests

Issue: https://issues.redhat.com/browse/WFLY-17349

### CODE REVIEW

**Comment by istudens** [comment]
@scottmarlow can you review it please? thanks

**Review by scottmarlow — APPROVED** [review]

**Review by rhusar — APPROVED** [review]
I am also under impression that this will fix the issue - basically what's happening is we are creating/deleting and recreating the same tables in rapid succession in H2 and their related structures, but it's just racey in H2. Using different entities should solve the situation. Although this solution is not exactly elegant, I would prefer to e.g. implement a custom table mapping or use a different schema name.

Also note that while this might not fail frequently in our lab it fails quite frequently on faster machines which makes this very annoying :-)

Rerunning the failed unrelated tests to give this a chance to get in eventually.

**Comment by bstansberry** [comment]
Thanks @istudens, @scottmarlow and @rhusar

**Comment by rhusar** [comment]
I am afraid this did not help afterall :-(

> Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement [Table "WEBTXEMFLIGHT" not found; SQL statement:

**Pull request merged**
