### PR TITLE
WFLY-18233 Optimize payload of ATTRIBUTE granularity mapping in distributed session manager using Infinispan's Cache.compute(...)

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-18233

Requires https://github.com/wildfly/wildfly/pull/17238

### CODE REVIEW

**Comment by pferraro** [comment]
Adding HOLD label.  There is either a passivation/activation event timing regression, or the test expectations need to be changed.

**Comment by pferraro** [comment]
Adding hold label - this needs to be rebased on top of https://github.com/wildfly/wildfly/pull/17238

**Comment by pferraro** [comment]
Rebase complete.

**Comment by pferraro** [comment]
Rebased against main.

**Review by rhusar — APPROVED** [review]
👍🏼  LGTM

**Pull request merged**
