### PR TITLE
WFLY-18912 Fix capability name resolution issues in undertow subsystem

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-18912

Includes additional commits removing usage of deprecated APIs.

____

More information about the [wildfly-bot[bot]](https://github.com/wildfly/wildfly-github-bot)

### CODE REVIEW

**Comment by pferraro** [comment]
@fl4via Please review.

**Review by fl4via — CHANGES_REQUESTED** [review]
The PR looks great! I think you improved the code consistency by a mile!
There is only a typo in the title of the last commit, number 7b9501f186b5974d79bdb5c8f6f5a7845fa16cd

**Comment by pferraro** [comment]
Thanks so much for the review @fl4via.  I'll fix the commit message typo and rebase the branch against master so that we get another CI run.

**Comment by pferraro** [comment]
Rebasing once more.

**Pull request merged**
