### PR TITLE
[WFLY-15018] Manage the BouncyCastle Jakarta Mail dependency with Wil…

### PR DESCRIPTION
**Pull request by yersan**
…dFly Core

Jira issue: https://issues.redhat.com/browse/WFLY-15018

Requires https://github.com/wildfly/wildfly-core/pull/4670

### CODE REVIEW

**Comment by yersan** [comment]
`core-upgrade-needed` label can be removed, the failure on the Dependency Tree is because this PR was created requiring the core upgrade, it could be ignored now

**Comment by bstansberry** [comment]
@yersan The WF Preview jobs fail with this:

https://ci.wildfly.org/viewLog.html?buildId=267211&buildTypeId=WF_WildFlyPreviewLinuxJdk11&tab=buildLog
https://ci.wildfly.org/viewLog.html?buildId=267213&buildTypeId=WF_Ee9BootableJarLinuxJdk8&tab=buildLog

**Comment by yersan** [comment]
@bstansberry The problem with the EE 9 Jobs was the Jobs are not using a merge commit and were executed with my topic branch behind the WildFly Core upgrade that incorporates the required changes; I should have rebased the changes before as soon as core as merged in full. I've rebased and pushed them up, here are the new links:

https://ci.wildfly.org/viewLog.html?buildId=267372&buildTypeId=WF_WildFlyPreviewLinuxJdk11&tab=buildParameters
https://ci.wildfly.org/viewLog.html?buildId=267374&buildTypeId=WF_Ee9BootableJarLinuxJdk8&tab=buildParameters

They should be fine now, we have even run an integration Job for EE9 preview even before merging the wildfly core changes, let's see how they go now.

**Pull request merged**
