### PR TITLE
WFLY-19441 Decouple SNI host name configuration from physical hostnames and auto-disable hostname validation when unspecified.

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-19441

### CODE REVIEW

**Review by rhusar — APPROVED** [review]
LGTM (though I will mention it's missing a rejection test :-) )

**Comment by pferraro** [comment]
@rhusar Good point. I've added the missing rejection test.

**Comment by rhusar** [comment]
> @rhusar Good point. I've added the missing rejection test.

Excellent! (I did mention explicitly since we have the model version branch for EAP which makes things a little bit complicated)

**Review by rhusar — APPROVED** [review]
LGTM now. 👍🏼

**Comment by pferraro** [comment]
I split this jira into 2.  Subsystem model changes will be tracked by WFLY-19505.

**Comment by bstansberry** [comment]
Thanks @pferraro and @rhusar

**Pull request merged**
