### PR TITLE
[WFLY-14825] Removing unnecessary permissions in DatabaseTimerServiceMultiNodeTestCase

### PR DESCRIPTION
**Pull request by khermano**
Issue: https://issues.redhat.com/browse/WFLY-14825

____

More information about the [wildfly-bot[bot]](https://github.com/wildfly/wildfly-github-bot)

### CODE REVIEW

**Review by bstansberry — CHANGES_REQUESTED** [review]
@khermano The JIRA description describes removing two permissions, but it looks like since it was filed a 3rd was added 

https://github.com/wildfly/wildfly/pull/14584/commits/5b8c709406ed834f5dd200468510164daa3c4e62

and the test fails without that:

```
 Suppressed: java.security.AccessControlException: WFSM000001: Permission check failed (permission "("java.io.FilePermission" "/opt/buildAgent/work/e34a6f994de9f7c6/testsuite/integration/multinode/target/wildfly/standalone/tmp/auth/local14244497676088082442.challenge" "read")" in code source "(vfs:/content/testTimerServiceSimple.war/WEB-INF/classes <no signer certificates>)" of "ModuleClassLoader for Module "deployment.testTimerServiceSimple.war" from Service Module Loader")
      at org.wildfly.security.elytron-base@2.4.1.Final//org.wildfly.security.manager.WildFlySecurityManager.checkPermission(WildFlySecurityManager.java:309)
      at org.wildfly.security.elytron-base@2.4.1.Final//org.wildfly.security.manager.WildFlySecurityManager.checkPermission(WildFlySecurityManager.java:201)
      at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:661)
      at org.wildfly.security.elytron-base@2.4.1.Final//org.wildfly.security.manager.WildFlySecurityManager.checkRead(WildFlySecurityManager.java:374)
      at java.base/java.io.FileInputStream.<init>(FileInputStream.java:146)
      at org.wildfly.security.elytron-base@2.4.1.Final//org.wildfly.security.sasl.localuser.LocalUserClient.evaluateMessage(LocalUserClient.java:94)
      at org.wildfly.security.elytron-base@2.4.1.Final//org.wildfly.security.sasl.util.AbstractSaslParticipant.evaluateMessage(AbstractSaslParticipant.java:206)
      at org.wildfly.security.elytron-base@2.4.1.Final//org.wildfly.security.sasl.util.AbstractSaslClient.evaluateChallenge(AbstractSaslClient.java:79)
      at org.wildfly.security.elytron-base@2.4.1.Final//org.wildfly.security.sasl.util.AbstractDelegatingSaslClient.evaluateChallenge(AbstractDelegatingSaslClient.java:54)
      at org.wildfly.security.elytron-base@2.4.1.Final//org.wildfly.security.sasl.util.PrivilegedSaslClient.lambda$evaluateChallenge$0(PrivilegedSaslClient.java:55)
      at java.base/java.security.AccessController.doPrivileged(Native Method)
      at org.wildfly.security.elytron-base@2.4.1.Final//org.wildfly.security.sasl.util.PrivilegedSaslClient.evaluateChallenge(PrivilegedSaslClient.java:55)
      at org.jboss.remoting@5.0.28.Final//org.jboss.remoting3.remote.ClientConnectionOpenListener$Authentication.lambda$handleEvent$0(ClientConnectionOpenListener.java:674)
      at org.jboss.remoting@5.0.28.Final//org.jboss.remoting3.EndpointImpl$TrackingExecutor.lambda$execute$0(EndpointImpl.java:993)
      at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
      at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
      at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
      at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
      at org.jboss.xnio@3.8.14.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
      at java.base/java.lang.Thread.run(Thread.java:829)
```

So I think that needs to be restored.

**Comment by bstansberry** [comment]
@khermano I put the hold label on this because the test fails without these permissions, and I'm not sure it can be made to work. So the label stops random mergers spending time looking into this. Please remove it when this passes CI and is thus mergeable. Reach out to people indiividually if you want review. Perhaps close this and re-open if there's a working fix.

This fails because the timer service on the server node is opening a database connection to persist the timer. It needs the perm to do that. There's a longstanding discussion / JIRA about whether its appropriate to require a user permission to do that as the timer service is an internal detail.  @tadamski would know where that JIRA is.  IIRC there's a rough consensus that a user perm should not be needed for this, but it's not clear how the IronJacamar or datasource subsystem code could distinguish requests.

Perhaps @tadamski can suggest some tweaks in the datasource this test adds to work around that problem, e.g. pool prefill settings such that by the time the test requests a connection with deployment classes on the stack the connection is already connected, so need for the perms needed to connect.

**Comment by khermano** [comment]
Hi @bstansberry , sorry for the late response.
Thank you very much for the review and all of the information. I will check this, but I would rather not close the PR for now because I could not reproduce these errors locally.

**Comment by bstansberry** [comment]
@khermano When you ran locally did you include -Dsecurity.manager in you call to mvn?

**Comment by khermano** [comment]
Thank you for this note, I did indeed forgot to include security manager. I am closing this PR and I will open the new one when/if I get rid of this issue.

**Review by tadamski — COMMENTED** [review]
I think that the we can remove the SecurityPermission but the FilePermission has to stay. The reason for that is that timers can be executed on both client and server nodes. When the timer is executed on server node LocalEjbReceiver is used and no FilePermissions are needed, OTOH when the timer is executed on the client node then remote Elytron authentication is necessary and it seems to me that it implies the FilePermission. I believe that the permission is Elytron related and is not related to timer persistence. Because of that this PR looks good to me. IMHO we can only remove the SecurityPermission.

BTW the test is pretty convoluted because of invocation between client and two nodes and synchronization of timers via database between the nodes. I have created WFLY-19433 and I'm planning to add some explanatory notes after this PR is merged.

**Comment by khermano** [comment]
@tadamski, sorry for the delay. I was on sick leave.
Thank you very much for the feedback. Unfortunately, there is this test failing for the Windows JDK 11 test suite now after removing the SecurityPermission. Before that, I tried to remove both SecurityPermission and SocketPermission, and that resulted in these tests failing:
             - https://ci.wildfly.org/buildConfiguration/WF_PullRequest_LinuxSmJdk11/437939?buildTab=tests&status=failed&expandedTest=build%3A%28id%3A437939%29%2Cid%3A2000002959
             - https://ci.wildfly.org/buildConfiguration/WF_PullRequest_WildFlyPreviewLinuxJdk17/437937?buildTab=tests&status=failed&expandedTest=build%3A%28id%3A437937%29%2Cid%3A2000002522
             - https://ci.wildfly.org/buildConfiguration/WF_PullRequest_WindowsJdk11/437935?buildTab=tests&status=failed&expandedTest=build%3A%28id%3A437935%29%2Cid%3A2000002023.

It seems like these changes in DatabaseTimerServiceMultiNodeTestCase propagate themselves into other test cases. Should it be like that? I am not sure what I should do next.

**Comment by khermano** [comment]
@tadamski, I am very sorry for the delay. 
Thank you very much for the feedback. Unfortunately, there is this test failing for the Windows JDK 11 test suite now after removing the SecurityPermission. Before that, I tried to remove both SecurityPermission and SocketPermission, and that resulted in these tests failing:
             - https://ci.wildfly.org/buildConfiguration/WF_PullRequest_LinuxSmJdk11/437939?buildTab=tests&status=failed&expandedTest=build%3A%28id%3A437939%29%2Cid%3A2000002959
             - https://ci.wildfly.org/buildConfiguration/WF_PullRequest_WildFlyPreviewLinuxJdk17/437937?buildTab=tests&status=failed&expandedTest=build%3A%28id%3A437937%29%2Cid%3A2000002522
             - https://ci.wildfly.org/buildConfiguration/WF_PullRequest_WindowsJdk11/437935?buildTab=tests&status=failed&expandedTest=build%3A%28id%3A437935%29%2Cid%3A2000002023.

It seems like these changes in DatabaseTimerServiceMultiNodeTestCase propagate themselves into other test cases. Should it be like that? I am not sure what I should do next.

**Comment by tadamski** [comment]
retest this please (the logs have dissapeared - have to retest)

**Comment by tadamski** [comment]
@khermano now the failures are gone... imho it is highly probable that they were unrelated

**Comment by khermano** [comment]
@tadamski, thank you very much for your feedback and help. :) @bstansberry, what do you think about that?

**Comment by tadamski** [comment]
@khermano I believe the PR is good now. @bstansberry could you please merge the PR or are there still some issues that have to be fixed?

**Comment by bstansberry** [comment]
Thanks @khermano and @tadamski

**Comment by bstansberry** [comment]
@tadamski @khermano BTW, I'm pretty sure my comment https://github.com/wildfly/wildfly/pull/17924#issuecomment-2145913517 was primarily about the socket permission. That's the troublesome one where a WildFly internal detail (connecting a socket to a db to persist a timer) requires the user to include a permission in their deployment.

But I'm fine with not correcting that as part of this work.

**Comment by khermano** [comment]
Thanks @bstansberry and @tadamski for all the info and help with this.

**Pull request merged**
