### PR TITLE
WFLY-2480 Fix ordering in Infinispan..Writer and test files to validate against XSDs

### PR DESCRIPTION
**Pull request by rhusar**
Throwing it out here if anyone has an opinion.

Can we move to XSD 1.1 to address the ordering problems of XSD 1.0?

### CODE REVIEW

**Comment by rhusar** [comment]
I am not comfortable with XSD 1.1 as most IDEs are still lacking proper support for it.

**Comment by bstansberry** [comment]
I suggest you post on the dev list, as who looks at a PR is really random and definitely doesn't cover the set of people who may have useful input.

**Comment by pferraro** [comment]
As for the PR itself, this looks good to me.

**Comment by bstansberry** [comment]
Ah, I realize now the question about XSD 1.1 doesn't need to be answered for this PR to go in.

**Pull request merged**
