### PR TITLE
WFLY-15573 Always use concurrent data structure - to prevent ConcurrentModificationException during state transfer, even for lockOnRead cache configurations.

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-15573

### CODE REVIEW

**Comment by pferraro** [comment]
@rhusar Please review.

**Comment by darranl** [comment]
Hi @rhusar if you have time to give this a quick review we can get it in for Paul.

**Review by rhusar — APPROVED** [review]
LGTM!

**Comment by darranl** [comment]
Thank you @rhusar

**Pull request merged**
