### PR TITLE
WFLY-13311 Upgrade Weld to 3.1.4.Final.

### PR DESCRIPTION
**Pull request by manovotn**
JIRA issue - https://issues.redhat.com/browse/WFLY-13311

### CODE REVIEW

**Comment by manovotn** [comment]
JDK 11 fails with - `Canceled with comment: Build and agent have finished unexpectedly or were killed. Please check agent logs for details.`

I don't have TC account to restart just that job, is there another way?

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
@manovotn -- @luck3y can get you set up with a TC account.

**Comment by luck3y** [comment]
@manovotn I created an account for you and emailed you the details. Let me know if you need anything else.

**Comment by manovotn** [comment]
@luck3y thanks!

**Pull request merged**
