### PR TITLE
[WFLY-5401] Add version 4.0 of the Undertow Subsystem Model / Schema

### PR DESCRIPTION
**Pull request by darranl**
:exclamation: Commits from this branch are used in numerous other topic branches so please do not cherry-pick or rebase. :exclamation:

### CODE REVIEW

**Comment by darranl** [comment]
Retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
I think this one is likely a bit out of date. I know I did quite a bit of reorganization of persistence order recently, and I didn't look closely but my impression is this doesn't have the cert generation stuff.

**Comment by darranl** [comment]
I have already updated the schema to match the changes you made.  For each version bump PR after merging the latest from upstream I have also compared the new schema with the last scheme to ensure that apart from the namespaces for the version at the top of the file they are identical.

Regarding certificate generation that is within the security realms not the Undertow subsystem.

**Comment by darranl** [comment]
Actually I see what you mean, this one still needs the actual parser porting over - will correct.

**Comment by jamezp** [comment]
This is ready to merge. I've added a hold tag waiting for the EAP PR and waiting for @kabir to give the okay to merge.

**Pull request merged**
