### PR TITLE
[WFLY-17802] Upgrade ironjacamar to 3.0.1.Final

### PR DESCRIPTION
**Pull request by tadamski**
https://issues.redhat.com/browse/WFLY-17802

### CODE REVIEW

**Comment by jbliznak** [comment]
@tadamski could you look at it please? it seems you need to include changes from https://issues.redhat.com/browse/WFLY-17180 too

**Comment by tadamski** [comment]
@jbliznak it seems to me that those changes were merged and are present (commit dc6a760a85883ae5e942ca62e6093dd343dc1939)

**Comment by istudens** [comment]
@tadamski It needs the following commit.
https://github.com/istudens/wildfly/commit/4ad6187194a167ae659a9aced6988f1aff6ee454

I can create a composed PR.

**Comment by tadamski** [comment]
@istudens 
could you please create a PRs then. I guess I would have to close this one then and do another release.

**Comment by jbliznak** [comment]
> dc6a760a85883ae5e942ca62e6093dd343dc1939

this is the commit in ironjacamar, but we need https://github.com/istudens/wildfly/commit/4ad6187194a167ae659a9aced6988f1aff6ee454 included in WF itself. 

IIUC there is no need to create another release of ironjacamar because of this.

**Comment by istudens** [comment]
@jbliznak @tadamski take a look at https://github.com/wildfly/wildfly/pull/16670 please

**Pull request closed without merging**
