### PR TITLE
[WFLY-18326] Verify that jboss.server.name can be resolved as a JVM o…

### PR DESCRIPTION
**Pull request by yersan**
…ption in a managed server

Jira issue: https://issues.redhat.com/browse/WFLY-18326

### CODE REVIEW

**Comment by bstansberry** [comment]
@yersan Why is this in full WF? It seems like something WildFly Core can test.

**Comment by yersan** [comment]
@bstansberry It takes advantage of existing test cases available in the WildFly Test Suite. The test case deploys a Servlet and I think that was the original intention of placing the test cases in WildFly instead of wildfly core, to avoid dealing with Undertow and activate it on WildFly Core.

**Comment by yersan** [comment]
@bstansberry , yes, reading the EAP7-823 test plan, the original intention was to add the test cases in WildFly instead of WildFly Core just because Undertow was already prepared out of the box to process .war files in WildFly and I think I wanted to avoid more complications dealing with this detail in Core.

If that's not an option, looking at it after some time, it seems that we could try to move all of them to WildFly Core (the EAP7-823 and this enhancement), we only need a servlet deployed, and that seems doable.

Maybe, could we get this done in the WildFly test suite now and later move everything to WildFly Core? Does it make sense to you? in any case, I've just noticed this PR missed add the new resolvable property to the WildFly documentation

**Review by bstansberry — APPROVED** [review]
Sorry, @yersan -- this is fine. I hadn't had enough coffee when I looked at this and it didn't register that this was a minor update to an existing test.

**Comment by bstansberry** [comment]
@yersan Note that I think JVMServerPropertiesTestCase could be easily enough moved to WildFly Core. Just create a UndertowServiceActivator subclass and override getHttpHandler(). There are a number of tests in core that do this. There's no need to use a servlet.

But that's a nice to have for someone to do some day. Not at all urgent or in scope for this issue.

**Comment by yersan** [comment]
Yes @bstansberry , thanks, you're right, we only would need a way to verify the expected system properties on each managed server. I think when I prepared them the first time I went directly to WildFly full because I was thinking of a war application returning the properties, and at that time I thought wildfly core was unable to do something like that. I'll create a follow-up Jira to move those tests once this part is finally merged.

**Comment by yersan** [comment]
Converted to draft since it still needs a WF Core upgrade, I'm now going to add the pending Javadocs

**Review by bstansberry — APPROVED** [review]

**Comment by yersan** [comment]
@bstansberry , this one seems to be ready to go, I've created https://issues.redhat.com/browse/WFCORE-6497 as follow up once this is merged.

**Comment by bstansberry** [comment]
Thanks @yersan

**Pull request merged**
