### PR TITLE
WFLY-10607 Fix EJBForwardingTestCase keeping it ignored due to remaining issues

### PR DESCRIPTION
**Pull request by rhusar**
Fixes the test itself, but leaves it still essentially ignored for which there's Jira - https://issues.redhat.com/browse/WFLY-10607

### CODE REVIEW

**Comment by pferraro** [comment]
No luck: https://ci.wildfly.org/viewLog.html?buildId=242872&buildTypeId=WF_PullRequest_GalleonLinuxJdk11

**Comment by rhusar** [comment]
@pferraro I see what's going on – that's a galleon build which doesn't support legacy security and thus these tests cannot be supported. Fixed now.

**Comment by pferraro** [comment]
Still fails: https://ci.wildfly.org/viewLog.html?buildId=243540&buildTypeId=WF_PullRequest_LinuxSm

**Comment by rhusar** [comment]
@pferraro As discussed a while ago I have updated the PR to fix the test itself but still leaving it as 'intermittently failing' essentially meaning disabled on CI. Please review/merge, thanks and leave the Jira open and the EJB client failures for investigation for @rachmatowicz (Jira assignee).

**Pull request merged**
