### PR TITLE
[WFLY-16226] Upgrade com.fasterxml.woodstox 6.2.8

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFLY-16226

### CODE REVIEW

**Comment by boris-unckel** [comment]
@jimma Please find the links for release notes and git-diff in the Jira. Could you review and approve, please?

**Comment by boris-unckel** [comment]
@jimma Could you have a look at this, please? I'm hoping to backport it to 26.1.1.Final, not knowing a deadline.

**Comment by jimma** [comment]
@boris-unckel  @bstansberry  This looks good. Thanks for the PR.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @boris-unckel

**Pull request merged**
