### PR TITLE
[WFLY-15579] Upgrade google guava 31.0.1-jre

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFLY-15579

### CODE REVIEW

**Review by chengfang — APPROVED** [review]

**Comment by bstansberry** [comment]
@jasondlee @ehsavoie @jamezp @ronsigal @jimma @fl4via Module dependency analysis shows this change is relevant to all of you.

**Comment by jasondlee** [comment]
This looks good to me.

**Review by jasondlee — APPROVED** [review]

**Comment by jamezp** [comment]
FWIW I'm not ignoring this, I just haven't had time to test it. I'm sure it will be fin, but I've not run the RESTEasy test suite with it.

**Review by ehsavoie — APPROVED** [review]

**Comment by jimma** [comment]
This looks good to me.

**Review by jamezp — APPROVED** [review]
No issues with RESTEasy integration.

**Comment by darranl** [comment]
@fl4via if you could please add your review I think we can get this one in.

**Pull request merged**
