### PR TITLE
[WFLY-9659] Upgrade IronJacamar to 1.4.7.Final

### PR DESCRIPTION
**Pull request by dosoudil**
https://issues.jboss.org/browse/WFLY-9659

### CODE REVIEW

**Comment by kabir** [comment]
Retest this please

**Comment by kabir** [comment]
Retest this please

I am putting ready for merge on this so it can be merged once tests pass

**Comment by kabir** [comment]
Retest this please

**Comment by kabir** [comment]
@dosoudil @maeste This consistently fails on CI. Seems to be caused by:

[Step 2/3] Failed to execute goal on project wildfly-connector: Could not resolve dependencies for project org.wildfly:wildfly-connector:jar:12.0.0.Alpha1-SNAPSHOT: The following artifacts could not be resolved: org.jboss.ironjacamar:ironjacamar-core-api:jar:1.4.7.Final, org.jboss.ironjacamar:ironjacamar-core-impl:jar:1.4.7.Final, org.jboss.ironjacamar:ironjacamar-common-api:jar:1.4.7.Final, org.jboss.ironjacamar:ironjacamar-common-spi:jar:1.4.7.Final, org.jboss.ironjacamar:ironjacamar-common-impl:jar:1.4.7.Final, org.jboss.ironjacamar:ironjacamar-deployers-common:jar:1.4.7.Final, org.jboss.ironjacamar:ironjacamar-jdbc:jar:1.4.7.Final, org.jboss.ironjacamar:ironjacamar-validator:jar:1.4.7.Final: Could not find artifact org.jboss.ironjacamar:ironjacamar-core-api:jar:1.4.7.Final in brontes-mirror (http://repository.ci.wildfly.org/content/groups/public/)
[05:32:21][

**Comment by dosoudil** [comment]
The artifacts of [IronJacamar 1.4.7.Final](https://github.com/ironjacamar/ironjacamar/releases/tag/ironjacamar-1.4.7-Final) has not been deployed to jboss.org maven repository yet.

@maeste Stefano, could you please take care about the deployment of that? Thanks a lot.

**Comment by maeste** [comment]
@dosoudil @kabir done. asking retest again

**Comment by maeste** [comment]
Retest this please

**Comment by dosoudil** [comment]
retest this please

**Pull request merged**
