### PR TITLE
[WFLY-17042] JCA: set elytron-enabled to true by default

### PR DESCRIPTION
**Pull request by tadamski**
https://issues.redhat.com/browse/WFLY-17042

### CODE REVIEW

**Comment by darranl** [comment]
Where do these constants get used?  Just in Runtime checks or could they influence the model state?

**Comment by tadamski** [comment]
Actually the are used only in attribute definition file and are equivalent to setDefault(ModelNode.TRUE).
Maybe I will change it this way for clarity.

**Comment by darranl** [comment]
If this changes the model I don't think it will be feasible as we need to support older configuration in domain mode.

A model change like this would likely need a version bump but also we would need to consider the meaning when parsing older XML, additionally there would be a transformer requirement but as this attribute has a default value I am not sure we could reliable write transformers.

**Comment by tadamski** [comment]
I guess the only solution then would be to deprecated elytron-enabled attribute and document that is this being ignored. Is it acceptable?

**Comment by darranl** [comment]
I think we do have other code where at runtime we know Elytron is the only solution around, in this case now there is no choice available that runtime just assumes if they need security it is Elytron security.

That would at least keep is compatible for domain mode as well where older hosts can make their own runtime check.

**Comment by tadamski** [comment]
OK. I'm going to close this PR then and update the docs in WFLY-17559 to make sure that is it clear that elytron-enabled setting has no effect.

**Pull request closed without merging**
