### PR TITLE
[WFLY-18039] Remove uses of deprecated AttributeDefinition API

### PR DESCRIPTION
**Pull request by bstansberry**
https://github.com/bstansberry/wildfly/pull/new/WFLY-18039

### CODE REVIEW

**Comment by yersan** [comment]
Failed test are unrelated to this Jira; added an integration Job to get a bit more confidence 

https://ci.wildfly.org/buildConfiguration/WF_WildFlyCoreIntegrationExperiments/371856

**Comment by pferraro** [comment]
Rather than need to reference each attribute twice per read/write, I would suggest adding a utility methods to the parsers/writers to both reduce verbosity and likelihood of bugs/regressions, e.g.
https://github.com/wildfly/wildfly/blob/main/clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsSubsystemXMLReader.java#L945
https://github.com/wildfly/wildfly/blob/main/clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/JGroupsSubsystemXMLWriter.java#L232

**Review by pferraro — CHANGES_REQUESTED** [review]
Everything looks technically correct, but see my comment above.

**Comment by bstansberry** [comment]
@pferraro Thanks. I added a commit to clean out the dual use of the same constant in one line.

**Review by pferraro — APPROVED** [review]

**Review by yersan — APPROVED** [review]

**Pull request merged**
