### PR TITLE
[WFLY-13635] Upgrade Apache CXF to 3.3.7

### PR DESCRIPTION
**Pull request by spyrkob**
Issue: https://issues.redhat.com/browse/WFLY-13635

### CODE REVIEW

**Comment by spyrkob** [comment]
@jimma could you review please?

**Comment by bstansberry** [comment]
@ronsigal Please review as well as a resteasy module depends on the commons-codec and commons-lang. Thanks.

**Comment by ronsigal** [comment]
Ok, sure.

**Comment by jimma** [comment]
@spyrkob  Looks xmlshema is updated in cxf  : https://github.com/apache/cxf/blob/cxf-3.3.7/parent/pom.xml#L223 . We include this upgrade too ?

**Comment by spyrkob** [comment]
@jimma thanks, I missed it. Updated the PR to include it now.

**Comment by ronsigal** [comment]
I ran the RESTEasy testsuite from branch 3.14, which should go into WF 21, with commons-codec upgraded. I don't see where RESTEasy depends on commons-lang. In any case, the testsuite passed.

**Comment by bstansberry** [comment]
Thanks, @ronsigal. Sorry, my mistake re commons-lang; I thought there was a module.xml dependency but there is not.

**Comment by ronsigal** [comment]
@bstansberry, +1.

**Comment by bstansberry** [comment]
@jimma ok now?

**Comment by jimma** [comment]
@bstansberry  Looks good to me now.

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
