### PR TITLE
WFLY-3858 Infinispan cache configuration is not always applied to sec…

### PR DESCRIPTION
**Pull request by spyrkob**
…urity-domain

JIRA: https://issues.jboss.org/browse/WFLY-3858

### CODE REVIEW

**Comment by bstansberry** [comment]
@pferraro Please approve. I believe this could benefit from using capabilities instead of checking the model, but since this is meant for backport, I think this approach is fine, at least for now.

The check by the security subsystem of the infinispan subsystem model is safe, even with parallel subsystem processing at boot, because the check is in Stage.RUNTIME. All model changes are complete before any subsystem starts Stage.RUNTIME

**Comment by bstansberry** [comment]
https://issues.jboss.org/browse/WFLY-8198 is to use capabilities.

**Comment by pferraro** [comment]
@bstansberry This would be fine for 8.x, but I'd rather not merge this into master.  I'll put something together for WFLY-8198.

**Comment by bstansberry** [comment]
@pferraro I don't think there are any plans to do any 8.x releases.

**Comment by pferraro** [comment]
Superseded by https://github.com/wildfly/wildfly/pull/9736

**Comment by kabir** [comment]
Closing since this seems to have been supeseded

**Pull request closed without merging**
