### PR TITLE
Upgrade to JAXB 2.3 / JBossWS 5.2 / CXF 3.2

### PR DESCRIPTION
**Pull request by asoldano**
Upgrade to JAXB 2.3 / JBossWS 5.2 / CXF 3.2 for better Java 9 compatibility.

### CODE REVIEW

**Comment by asoldano** [comment]
retest this please

**Comment by asoldano** [comment]
retest this please (last time a stale snapshot was fetched from the repo...)

**Comment by ctomc** [comment]
@asoldano this could probably be merged now, you only need to update PR to use released version of component.

**Comment by asoldano** [comment]
@ctomc yes, actually I'm planning to also upgrade JBossWS in the same PR, hopefully by the end of this week.

**Comment by asoldano** [comment]
retest this please

**Comment by asoldano** [comment]
retest this please

**Comment by asoldano** [comment]
retest this please

**Comment by asoldano** [comment]
retest this please

**Comment by stuartwdouglas** [comment]
Looks like the alpha is just the spec jar, I am guessing it just needs to be released as a .Final?

**Comment by asoldano** [comment]
Indeed, it's just the spec jar being alpha. You can name the way you want, though. I wouldn't be that picky with version names in this case. Just my 2cents, though, let's see what @n1hility  says.

**Comment by ctomc** [comment]
IMO at this point .AlphaX component versions should be fine.
Otherwise we can just re-release same component with .Final name "just so we can merge it" but that would be dishonest. 
Spec api jars that got updates for EE8, are new and we didn't have much testing for them beyond few or our testsuites passing, so having alpha is reasonable.

**Comment by asoldano** [comment]
@bstansberry @n1hility , so what are doing here?

**Comment by bstansberry** [comment]
@asoldano @ctomc Unless you hear otherwise from Jason, this needs to be a .Final. He's had time to reply here with something different from what he's told me before is his general policy and he hasn't, so the general policy stands. If you disagree it's better to raise it up on wildfly-dev. It's a valid topic, i.e. how to determine that something is good enough to go in without using master as a test bed. My guess is for a spec jar a TCK run is sufficient.

**Comment by asoldano** [comment]
@bstansberry ok, brought this to the mailing list. It's not really a matter of disagreeing or not... at this point I don't want to push / fight for this; wildfly needs the changes in this PR, so let's get together and decide how to move forward and deal with situations like this.

**Comment by asoldano** [comment]
@bstansberry @stuartwdouglas , the PR is now pulling the same spec jar, but released as final. Please review again :-)

**Review by stuartwdouglas — APPROVED** [review]

**Comment by bstansberry** [comment]
I removed the Ready for Merge as we saw TCK issues.

**Comment by kabir** [comment]
@asoldano This needs a rebase now
@msve ok from your side?

**Comment by asoldano** [comment]
@kabir yes, this needs a rebase... and another CXF upgrade to deal with the tck regression. The new cxf version is being voted now, will update the PR here as soon as the vote is completed and the artifacts promoted.

**Comment by msve** [comment]
@kabir ok from our side, since it's only jdk9 related changes (once the rebase is ready of course)

**Comment by kabir** [comment]
Unrelated clustering failure

**Pull request merged**
