### PR TITLE
[WFLY-13375] JNDI view does not show implementation classes for connection factories and destinations registered by 3rd party resource adapters.

### PR DESCRIPTION
**Pull request by parsharma**
Issue: https://issues.redhat.com/browse/WFLY-13375

### CODE REVIEW

**Comment by bstansberry** [comment]
@emmartins Please review.

**Comment by emmartins** [comment]
@bstansberry @parsharma LGTM

**Comment by parsharma** [comment]
Hi, I am improving this PR by adding a test case. Please don't merge as of now.

**Comment by jamezp** [comment]
@parsharma This was merged 3 days ago.

**Pull request merged**
