### PR TITLE
 WFLY-11839 Missing transformer for default protocol version change of remote-cache-container

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-11839

### CODE REVIEW

**Review by bstansberry — APPROVED** [review]

**Review by rhusar — APPROVED** [review]

**Comment by kabir** [comment]
@pferraro is covering this in the subsystem transformer tests doable?

**Comment by rhusar** [comment]
@kabir Good point actually, probably not reasonably with the current setup. However, the idea is to redo the infinispan subsystem testing same way as jgroups or mod_cluster if you read the description - https://issues.jboss.org/browse/WFLY-11719 - @pferraro do you want to do this as part of this or lets create a Jira and do it separately?

**Comment by pferraro** [comment]
@rhusar @kabir Let's handle the overhaul of the transformer testing of this subsystem separately.  This specific transformation is trivial enough.

**Comment by rhusar** [comment]
@pferraro @kabir Opened https://issues.jboss.org/browse/WFLY-11872 to address this.

**Pull request merged**
