### PR TITLE
WFLY-5390 Fix ClusteredMessagingTestCase: ensure cluster topology is established before running the tests

### PR DESCRIPTION
**Pull request by rhusar**
Resolves
https://issues.redhat.com/browse/WFLY-5390

### CODE REVIEW

**Comment by rhusar** [comment]
@pferraro if you have a minute... thanks!

**Comment by pferraro** [comment]
I'm going to wait for a number of CI runs of https://github.com/wildfly/wildfly/pull/14492 - which may make these changes unnecessary.

**Comment by rhusar** [comment]
@pferraro Lets stick a hold label on this until then.

**Comment by rhusar** [comment]
The https://github.com/wildfly/wildfly/pull/14492 should resolve this - we can reopen this if really needed. Closing now.

**Pull request closed without merging**
