### PR TITLE
WFLY-5951 pending-puts cache configuration + TRACE logging for addinglocal/jpa cache/ configuration

### PR DESCRIPTION
**Pull request by scottmarlow**

### CODE REVIEW

**Comment by n1hility** [comment]
@scottmarlow @pferraro is this ready to go?

**Comment by scottmarlow** [comment]
Just thinking about doing some debugging to verify that the simplecache is hit.

**Comment by scottmarlow** [comment]
in jconsole, I see simpleCache=true for the different caches but I don't know how reliable that is.

**Comment by pferraro** [comment]
@n1hility Looks good to me.  It's a shame that the cache configuration name is hardcoded, but that would need to be fixed in hibernate-infinispan.
@scottmarlow that jconsole output is reliable - the property is read from the runtime configuration of the given cache

**Comment by scottmarlow** [comment]
@n1hility I'm fine with the change (did some debugging and could see around 9 SimpleCaches created and many calls in from timestamp, query, cache code paths).

**Comment by rvansa** [comment]
@scottmarlow So you need to define explicitly `hibernate.cache.infinispan.pending-puts.cfg=pending-puts` when you want to set the configuration for this cache in WF config?

**Comment by scottmarlow** [comment]
@rvansa yes, "hibernate.cache.infinispan.pending-puts.cfg=pending-puts" must be hard coded to pending-puts or it won't match the name that Hibernate looks for.  If Hibernate changes to allow overriding the name "pending-puts", we will still be in sync.  We talked about introducing a "wildfly.pending-puts=true" setting but that isn't consistent with the way that we configure the other caches.  What do you think?

**Pull request merged**
