### PR TITLE
[WFLY-6790] - Typo in datasource and resource adapters subsystem conf…

### PR DESCRIPTION
**Pull request by xstefank**
…iguration

JIRA: https://issues.jboss.org/browse/WFLY-6790

### CODE REVIEW

**Comment by dmlloyd** [comment]
lol

**Comment by dmlloyd** [comment]
This is okay to test

**Comment by xstefank** [comment]
@dmlloyd Hi, sorry the PR was closed, can you comment again please ?

**Comment by dmlloyd** [comment]
This is okay to test

**Comment by dmlloyd** [comment]
I'm not certain that I'm an admin though :)

**Comment by dmlloyd** [comment]
This is ok to test

**Comment by dmlloyd** [comment]
If that doesn't work then I'm definitely not an admin :)

**Comment by dmlloyd** [comment]
There it goes!

**Comment by xstefank** [comment]
@dmlloyd Thank you.

**Pull request merged**
