### PR TITLE
WFLY-13132 Wrong/Incomplete CLUSTER_TOPOLOGY update sent to EJB client

### PR DESCRIPTION
**Pull request by pferraro**
... when clients connect to the same server/cluster using different protocols.
https://issues.redhat.com/browse/WFLY-13132

Includes subtasks:
Provide SPI and implementation for building a client mappings registry per connector
https://issues.redhat.com/browse/WFLY-13470

Requires:
https://github.com/wildfly/wildfly/pull/13289
https://github.com/wildfly/wildfly/pull/13339

### CODE REVIEW

**Comment by pferraro** [comment]
@rachmatowicz This causes org.jboss.as.test.integration.security.loginmodules.RemotingLoginModuleTestCase to hang.

**Comment by pferraro** [comment]
@rachmatowicz As this didn't make it into WF20, we need to bump the model/schema versions for WF21.  You'll want to do this in a separate commit.

**Comment by pferraro** [comment]
Also, there seem to be 1 more test hanging that needs resolution: SSLEJBRemoteClientTestCase

**Comment by rachmatowicz** [comment]
@pferraro Why when I checkout the wildfly-clustering/WFLY-13132 branch I don't see my commit?

**Comment by rachmatowicz** [comment]
@pferraro I upgraded the model version and fixed the test case and merged the changes into wildfly-clustering/wildfly

**Comment by rachmatowicz** [comment]
retest please

**Comment by rachmatowicz** [comment]
Closing this PR due to endless problems in adjusting the content. I have created a new PR which represents the same content: https://github.com/wildfly/wildfly/pull/13360

**Comment by rachmatowicz** [comment]
I'm not even able to close this PR.....

**Comment by pferraro** [comment]
@tadamski @chengfang Please review.

**Review by chengfang — APPROVED** [review]

**Comment by chengfang** [comment]
Can you also update `_admin-guide/subsystem-configuration/EJB3.adoc` where `connector-ref` is used?

**Comment by rachmatowicz** [comment]
> Can you also update `_admin-guide/subsystem-configuration/EJB3.adoc` where `connector-ref` is used?

Done.

**Pull request merged**
