### PR TITLE
[WFLY-15978] Enable Elytron domain security for EAR deployed connectors

### PR DESCRIPTION
**Pull request by reinhapa**
https://issues.redhat.com/browse/WFLY-15978

### CODE REVIEW

**Review by darranl — DISMISSED** [review]
As this is a single change not connected to anything else can you please rebase to remove the merge commit.

Also as you are doing this can you please add the Jira ID to the commit message.

**Comment by reinhapa** [comment]
@darranl I will do this with the next commit as I removed all legacy checks in the connector space to always use Elytron security...

**Review by tadamski — APPROVED** [review]
After discussion with Patrick I think this PR is good. There is no need to distinguish between elytron security domain and legacy one and because of that we can treat each security domain configured directly in IronJacamar as Elytron one.

@fjuma @darranl does this makes sense from security perspective?

**Review by fjuma — APPROVED** [review]
Thanks @reinhapa!

**Comment by bstansberry** [comment]
Thanks, @reinhapa!

**Pull request merged**
