### PR TITLE
[WFLY-5759]:Local web-app.xsd can't be loaded to validate web.xml

### PR DESCRIPTION
**Pull request by maerqiang**

### CODE REVIEW

**Comment by maerqiang** [comment]
retest this please

**Comment by wolfc** [comment]
The other option would be not to use ```XMLResourceLoader```, but rather do an implementation that either loads out of docs/schema or uses the proper module class loader to load things up.
Changing the TCCL might have unwarranted side-effects.

**Comment by wolfc** [comment]
Also note that validation should be implemented as a cross-cutting concern, not directly onto only the ```WebParsingDeploymentProcessor```. But that probably warrants a new issue.

**Review by stuartwdouglas — APPROVED** [review]
Once this has been rebased I think it is good to merge.

**Comment by bstansberry** [comment]
@maerqiang FYI ^^^

**Comment by jimma** [comment]
@bstansberry @stuartwdouglas  Already rebased.

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
