### PR TITLE
[JBEAP-15063] Tests for NullPointerException in ELFlash.get

### PR DESCRIPTION
**Pull request by spyrkob**
JIRA: https://issues.jboss.org/browse/WFLY-10746

**Note: this is a test for Mojarra fix https://github.com/jboss/mojarra/pull/20 and requires Mojarra upgrade**

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

### CODE REVIEW

**Comment by jamezp** [comment]
Added the fixme label because a component upgrade is required.

**Comment by kabir** [comment]
@spyrkob @fjuma  is there any reason this PR has been opened without the required upgrade?

**Comment by kabir** [comment]
@spyrkob @fjuma I am closing this as there has been no activity for a while and I don't think we have upgraded mojarra

**Comment by fjuma** [comment]
@spyrkob Just FYI, I've now created the Mojarra component upgrade PR:

https://github.com/wildfly/wildfly/pull/11551

**Pull request closed without merging**
