### PR TITLE
WFLY-7668 Singleton subsystem downgrades in XML configuration file co…

### PR DESCRIPTION
**Pull request by rhusar**
…mpared to initial state when configuration change is performed on server

Jira
https://issues.jboss.org/browse/WFLY-7668

### CODE REVIEW

**Comment by rhusar** [comment]
@pferraro Looking at the changes again, I wouldn't qualify changing a default value for a new schema version to begin with. This is still only in master (https://github.com/wildfly/wildfly/commit/15098b7bfc072930736a1621e701b72bb6a81010) so we still have time to revert this altogether.

```
[rhusar@syrah wildfly]$ diff /Users/rhusar/wildfly/clustering/singleton/extension/src/main/resources/schema/wildfly-singleton_1_0.xsd /Users/rhusar/wildfly/clustering/singleton/extension/src/main/resources/schema/wildfly-singleton_2_0.xsd
2c2
< <xs:schema targetNamespace="urn:jboss:domain:singleton:1.0"
---
> <xs:schema targetNamespace="urn:jboss:domain:singleton:2.0"
4c4
<             xmlns:tns="urn:jboss:domain:singleton:1.0"
---
>             xmlns:tns="urn:jboss:domain:singleton:2.0"
7c7
<             version="1.0">
---
>             version="2.0">
59c59
<         <xs:attribute name="cache" type="xs:string" default="default">
---
>         <xs:attribute name="cache" type="xs:string">
```

**Comment by ctomc** [comment]
This needs a subsystem test.
Which would catch this problem in first place already.

**Comment by pferraro** [comment]
@rhusar Agreed. Let's remove the 2.0 schema altogether.

**Comment by rhusar** [comment]
@ctomc Can you point me to a test that is supposed to test this? I am not aware that we have a test that would hit this. The standard subsystem test doesn't test this which is in place (in this subsystem the test is org.wildfly.extension.clustering.singleton.SingletonSubsystemParsingTestCase).

**Comment by rhusar** [comment]
Superseeded by https://github.com/wildfly/wildfly/pull/9417.

**Comment by ctomc** [comment]
@rhusar your tests are actually ignoring this kind of problem
see https://github.com/wildfly/wildfly/blob/master/clustering/common/src/test/java/org/jboss/as/clustering/subsystem/ClusteringSubsystemTest.java#L76

**Pull request closed without merging**
