### PR TITLE
[WFLY-16869] Drop source transformation for the Transactions subsystem (and other modules)

### PR DESCRIPTION
**Pull request by jmfinelli**
This PR should be considered after [WFLY-17264](https://issues.redhat.com/browse/WFLY-17264) is merged

[WFLY-17290](https://issues.redhat.com/browse/WFLY-17290)
[WFLY-17291](https://issues.redhat.com/browse/WFLY-17291)
[WFLY-17265](https://issues.redhat.com/browse/WFLY-17265)
[WFLY-17258](https://issues.redhat.com/browse/WFLY-17258)
[WFLY-17095](https://issues.redhat.com/browse/WFLY-17095)
[WFLY-16869](https://issues.redhat.com/browse/WFLY-16869)
[WFLY-17261](https://issues.redhat.com/browse/WFLY-17261)

### CODE REVIEW

**Comment by bstansberry** [comment]
@jmfinelli #16287 is merged so this PR doesn't need to handle it.

**Comment by mmusgrov** [comment]
@bstansberry We cannot migrate narayana to jakarta native until these issues are resolved.
Can you advise on how we should proceed, for example should we be splitting up the PR into more meaningful chunks (@jmfinelli is that feasible or are all of these issues mutually dependent).

**Comment by jmfinelli** [comment]
This PR is closed to make space for #16310

**Pull request closed without merging**
