### PR TITLE
WFLY-9771 SingletonPartitionTestCase.testSingletonService fails intermittently

### PR DESCRIPTION
**Pull request by rhusar**
Jira
https://issues.jboss.org/browse/WFLY-9771

### CODE REVIEW

**Comment by rhusar** [comment]
@pferraro  Would you agree with enabling the test? The Jira does not contain indication of what the failure has been https://issues.jboss.org/browse/WFLY-9771 and the linked job has been deleted. I don't see other way than just reenabling the test.

**Comment by rhusar** [comment]
retest this please

**Comment by pferraro** [comment]
@rhusar No problems - so long as we can demonstrate it to be stable.

**Comment by rhusar** [comment]
Thanks.

I wish you best of luck, SingletonPartitionTestCase!

**Pull request merged**
