### PR TITLE
[WFLY-18454] Upgrade FasterXML Jackson to 2.15.2

### PR DESCRIPTION
**Pull request by ivassile**
Issue: https://issues.redhat.com/browse/WFLY-18454

Core PR: https://github.com/wildfly/wildfly-core/pull/5666

### CODE REVIEW

**Review by jasondlee — APPROVED** [review]

**Comment by bstansberry** [comment]
I'm looking for oks from the various component areas that depend on Jackson.

@asoldano / @ronsigal -- RESTEasy
@pferraro -- OpenAPI
@rhusar -- AWS
@jasondlee -- OTel
@yrodiere -- Hibernate Search
@kabir -- Vertx

I believe the driver for this is https://github.com/FasterXML/jackson-core/pull/827.

**Comment by yrodiere** [comment]
Currently testing upstream: https://github.com/hibernate/hibernate-search/pull/3731
Will report back once the build ends.

**Review by kabir — APPROVED** [review]
vert.x 4.4.1 is on 2.14 while main is on 2.15. But as the WildFly tests pass, I think this is fine

**Review by yrodiere — APPROVED** [review]
This is safe as far as Hibernate Search is concerned.

**Review by rhusar — APPROVED** [review]
> I'm looking for oks from the various component areas that depend on Jackson.
> 
> @rhusar -- AWS

Uh, the `software.amazon.awssdk.s3` module actually uses their own fork with GAV `software.amazon.awssdk:third-party-jackson-core` with changed package names, bleh! So, this is fine for jgroups-aws.

**Review by pferraro — APPROVED** [review]

**Comment by bstansberry** [comment]
@Skyllarr Do you have any concerns about this from the elytron-oidc-client perspective? Sorry, I forgot to @ ping you yesterday.

**Comment by Skyllarr** [comment]
@bstansberry no problem, this LGTM

**Review by skyllarr — APPROVED** [review]

**Review by asoldano — COMMENTED** [review]
I think the upgrade to 2.15 series should be fine for RESTEasy, given on resteasy main (7.0.x) the same change has been done several months ago and both the 2.14.3 -> 2.15.0 and 2.15.0->2.15.2 upgrades did not imply actual code changes. @jimma , would you please be able to run a quick check? (/cc @jamezp, for when you'll be back)

**Comment by jimma** [comment]
@bstansberry @asoldano  I checked Resteasy 6.2.5.Final with this upgrade and there is no issue.

**Comment by bstansberry** [comment]
Thanks everyone!

**Pull request merged**
