### PR TITLE
[WFLY-15574] Upgrade com.squareup.okhttp3 3.14.9

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFLY-15574

### CODE REVIEW

**Review by rhusar — CHANGES_REQUESTED** [review]
If we can upgrade this will need to remove this workaround as well - https://github.com/wildfly/wildfly/blob/main/testsuite/integration/clustering/pom.xml#L50-L51

**Review by jasondlee — APPROVED** [review]
@rhusar's requests aside, this looks fine to me.

**Comment by rhusar** [comment]
I didn't get to updating my review before the merge, the changes I requested are good.

However, @jasondlee @boris-unckel I am wondering why this specific version for upgrade? If I am looking at the right places, we are consuming jaeger 1.6 which already uses v4.9.0? 

https://github.com/jaegertracing/jaeger-client-java/blob/v1.6.0/build.gradle#L28
https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp

**Comment by boris-unckel** [comment]
@rhusar The 3.x series stays Java based, the 4.x starts with Kotlin. The update was focusing on "latest minor" in terms of bugfixing. I don't know the Kotlin dependencies / consequences.

**Comment by rhusar** [comment]
@boris-unckel OK I see the logic (I was a bit surprised when I was using older version of the library with infinispan server driver library that it was failing silently (just timing out) so that's why I needed that upgrade in there).

**Comment by rhusar** [comment]
@bstansberry BTW do we have a specific policy against consuming "non-Java" dependencies, e.g. libraries written in Kotlin? TBH I am not aware if we consume anything non-Java at the moment.

**Comment by bstansberry** [comment]
@rhusar Before doing anything like that we'd need to discuss with folks like @rgdoliveira.

**Comment by rgdoliveira** [comment]
@bstansberry @rhusar (cc @dosoudil @dbkreling) PNC has now an environment with Kotlin, so I believe it is possible to productize a Kotlin project, but we haven't tried yet as we didn't have any projects like this before.

**Pull request merged**
