### PR TITLE
[WFLY-19542] Upgrade ASM to 9.7

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-19542

### CODE REVIEW

**Comment by ropalka** [comment]
@jimma is the ASM upgrade compatible with webservice modules?
@kabir is the ASM upgrade compatible with smallrye modules?

**Comment by kabir** [comment]
SmallRye Config is on 9.7 and the upgrade needed no tweaks https://github.com/smallrye/smallrye-config/pull/1142/files

**Comment by bstansberry** [comment]
@jimma @kabir Please use the github approval feature. Reading comments looking for approvals is no fun. :)

**Review by kabir — APPROVED** [review]

**Review by jimma — APPROVED** [review]

**Comment by jimma** [comment]
@ropalka  This upgrade looks good for webservice subsystem.

**Comment by bstansberry** [comment]
Thanks @ropalka, @kabir and @jimma

**Pull request merged**
