### PR TITLE
[WFLY-13026] Upgrade jboss-ejb-client 4.0.30.Final

### PR DESCRIPTION
**Pull request by tadamski**
https://issues.redhat.com/browse/WFLY-13026

Upgrade because of:
https://issues.redhat.com/browse/EAPSUP-37 (https://issues.redhat.com/browse/EJBCLIENT-361)

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

### CODE REVIEW

**Comment by jmesnil** [comment]
@tadamski failures in the CI jobs looks related to the PR. Could you please confirm?

**Comment by tadamski** [comment]
@jmesnil looking

**Comment by mackaypeter** [comment]
@tadamski we're also seeing these failures in our regression tests for the EAPSUP-37 one-off, so definitely related.
Looks like the negative testing scenarios are getting the nodes blacklisted, causing failures in subsequent tests.

**Comment by tadamski** [comment]
@mackaypeter your are right; I have updated ejb-client library with a fix

**Pull request merged**
