### PR TITLE
[WFLY-17818] Update EJBDefaultSecurityDomainProcessor#isVirtualDomain to handle the case where the defined security domain is empty

### PR DESCRIPTION
**Pull request by fjuma**
https://issues.redhat.com/browse/WFLY-17818

### CODE REVIEW

**Review by scottmarlow — APPROVED** [review]

**Comment by scottmarlow** [comment]
Looks good to me, I'll do some local TCK testing and give feedback here.

**Comment by scottmarlow** [comment]
Thanks @fjuma for the fix!  I verified locally that the Jakarta EE 10 Platform TCK connector/localTx/msginflow tests are now passing with this change, so great to have this pr!

**Comment by fjuma** [comment]
Great, thanks for confirming that @scottmarlow!

**Comment by bstansberry** [comment]
Thanks @fjuma and @scottmarlow

**Pull request merged**
