### PR TITLE
Set appropriate language for source blocks and set nowrap option

### PR DESCRIPTION
**Pull request by sgilda**
Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

### CODE REVIEW

**Comment by sgilda** [comment]
This is a WIP to set the appropriate language for source blocks and set the nowrap option so the build of the documentation is formatted correctly. There is a lot more work to be done with this.

**Comment by bstansberry** [comment]
@sgilda When you say this is a WIP do you mean you plan to make further changes to this PR, or that you plan other PRs?

**Comment by sgilda** [comment]
@bstansberry : Sorry. This won't fix all the display issues, so I plan to submit additional PRs. This does fix most of them though.

**Comment by kabir** [comment]
@sgilda this needs a rebase now

**Pull request merged**
