### PR TITLE
[WFLY-7020] JSF implementation in main slot it is not used when defa…

### PR DESCRIPTION
**Pull request by treblereel**
…ult-jsf-impl-slot is set back to it
JIRA: https://issues.jboss.org/browse/WFLY-7020
JBEAP: https://issues.jboss.org/browse/JBEAP-5600

7.x pr: https://github.com/jbossas/jboss-eap7/pull/842

### CODE REVIEW

**Comment by bstansberry** [comment]
This fix works but the root cause of the bug is the way JSFSubsystemAdd and JSFVersionProcessor work is non-standard. We have standard idioms for resolving a value from the management model that handles default values, and JSFSubsystemAdd should use that.

{code}
    @Override
    protected void performBoottime(OperationContext context, ModelNode operation, final ModelNode model) throws OperationFailedException {
        final String defaultJSFSlot = JSFResourceDefinition.DEFAULT_JSF_IMPL_SLOT.resolveModelAttribute(context, model).asString();
        context.addStep(new AbstractDeploymentChainStep() {
            protected void execute(DeploymentProcessorTarget processorTarget) {
                processorTarget.addDeploymentProcessor(JSFExtension.SUBSYSTEM_NAME, Phase.PARSE, Phase.PARSE_JSF_VERSION, new JSFVersionProcessor(defaultJSFSlot));
{code}

JSFVersionProcessor should directly use the provide defaultJSFSlot string.

**Comment by treblereel** [comment]
retest this please

**Comment by treblereel** [comment]
@bstansberry is that what you mean ?

**Comment by bstansberry** [comment]
@treblereel No, what I wrote is what I meant. :) I wasn't clear though -- JSFVersionProcessor would need to be changed so its constructor just takes a String instead of a ModelNode. It doesn't need to mess around with a ModelNode when what it's trying to get is the string. In general, the OperationStepHandlers should deal with messing with ModelNode and just provide data to other code in simple form.

**Comment by treblereel** [comment]
retest this please

**Comment by bstansberry** [comment]
That's it! Thanks; besides fixing this bug now the code is more "proper". :)

**Comment by bstansberry** [comment]
This is good to go once Kabir confirms.

**Comment by bstansberry** [comment]
retest this please

**Comment by bstansberry** [comment]
Please file an equivalent 7.x PR for this as we currently are not merging fixes here without a corresponding update to 7.x

**Comment by treblereel** [comment]
@bstansberry done

**Pull request merged**
