### PR TITLE
[WFLY-12892] Upgrade JAXB from 2.3.1 to 2.3.3-b02

### PR DESCRIPTION
**Pull request by gaol**
Issue: https://issues.redhat.com/browse/WFLY-12892

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

### CODE REVIEW

**Comment by darranl** [comment]
@asoldano @jimma @ronsigal I assume this one is fine as porting a bug fix - do any of you need to double check?

**Comment by bstansberry** [comment]
@scottmarlow FYI as the org.hibernate module depends on the com.sun.xml.bind module.

**Comment by bstansberry** [comment]
Note that although this is a micro version bump it looks to be a move from a release produced by Oracle to eclipse-ee4j, so the code diff is likely quite large due to the things done to move to Eclipse, i.e.

https://github.com/eclipse-ee4j/jaxb-ri/compare/afa88da..2.3.3-b02-RI

I don't have any reason to think that's a problem for WildFly and it's good to get onto the Eclipse releases. But this seems like one where if the external project testsuites can validate this upgrade, that's worthwhile.

**Comment by bstansberry** [comment]
Tangent: There's one project (eclipse-eej4/jaxb-ri) that produces 8 artifacts we use that involve 2 different maven groupIds and that are spread over 5 JBoss Modules modules. AFAICT we should be able to live with 1 module, so I filed https://issues.redhat.com/browse/WFLY-12913 to see if we can simplify this.

**Comment by scottmarlow** [comment]
I checked that the Hibernate ORM (5.3 branch) testsuite seems to pass with gradle/libraries.gradle updated with jaxbRuntimeVersion = '2.3.3-b02'.

CC @gbadner

**Comment by ivassile** [comment]
JAXB upgrade is scheduled for EAP 7.2.7[1] which will be tagged next week. Can we work on approving and merging this upgrade in master? Thanks!

[1] https://issues.redhat.com/browse/JBEAP-18292

**Comment by gaol** [comment]
@ivassile sorry for late update, I think it makes sense to upgrade `version.com.sun.istack` to `3.0.10` as well to align with `jaxb-ri:2.3.3-b02`. I tried TCK tests last week and it passed, please refer to the https://issues.redhat.com/browse/JBEAP-18292 for the detail TCK links.

**Comment by ivassile** [comment]
@gaol Thanks for the info. I updated EAP 7.2.7 CU issue. 

@bstansberry Is it possible to merge this upgrade so we can proceed with EAP 7.2.7 upgrade? Thanks!

**Comment by bstansberry** [comment]
@ivassile I'll give @jimma and @ronsigal until tomorrow AM to comment and then merge if no objections.

**Comment by ronsigal** [comment]
@bstansberry, @gaol, sorry, I missed this one. I'm running wildfly tests right now, but as soon as they're done, I'll run the RESTEasy testsuite with JAXB upgraded to 2.3.3-b02 and see what happens.

**Comment by ronsigal** [comment]
RESTEasy testsuite passed.

**Comment by bstansberry** [comment]
I'm going to go ahead and merge this so it can get in the next TCK run.

**Comment by jimma** [comment]
@bstansberry  @gaol  @darranl  I am late to look at this. FYI, I  created https://github.com/apache/cxf/pull/625 in CXF to check this upgrade.

**Comment by asoldano** [comment]
Thanks @ronsigal and @jimma  for the checks.

**Pull request merged**
