### PR TITLE
[WFLY-11092] xts logger fails to compile on jdk11 as javax package was removed from jdk

### PR DESCRIPTION
**Pull request by ochaloup**
https://issues.jboss.org/browse/WFLY-11092

### CODE REVIEW

**Comment by kabir** [comment]
@ochaloup needs a backport too :)

**Review by rsvoboda — CHANGES_REQUESTED** [review]
Seems XtsAsLogger.java doesn't need any update, just xts/pom.xml

**Review by jamezp — APPROVED** [review]
The pom is really the only necessary change. The other change is minor enough though.

**Comment by kabir** [comment]
Closing as mentioned on the JBEAP issue

**Comment by kabir** [comment]
I closed the wrong one, I am merging this one :)

**Pull request merged**
