### PR TITLE
JSON-P, JSON-B and JAX-RS upgrades 

### PR DESCRIPTION
**Pull request by jamezp**
# Overview
This PR includes changes for JSON-P, JSON-B and JAX-RS with the Java EE 8 tech preview. It also replaces/includes #10819. @asoldano could you please give this your approval? @stuartwdouglas please let me know if the module configurations look correct as well.

## JSON-P 1.1 [WFLY-6460](https://issues.jboss.org/browse/WFLY-6460)
This replaces JSON-P 1.0 with JSON-P 1.1 when the `ee8.preview.mode` system property is set to `true`. One thing to note about this is the system property only seems to work when the user specifies it in the `JAVA_OPTS`. This may be because elytron accesses the module before the property is set.

Also note that in the JMS client we hard-code the version to 1.0.4 since client itself still relies on JSON-P 1.0. This library is shaded into the client which is the reason for doing this.

Also note that JSON-P 1.0 implementation library includes both the API and the implementation which is my the `module.xml` exports only the `javax.json.*` packages.

## JSON-B 1.0 [WFLY-7185](https://issues.jboss.org/browse/WFLY-7185)
This introduces the new JSON-B 1.0 API. The module itself will be added to all deployments however the resource will only be added if the `ee8.preview.mode` system property is set to `true`.

There are currently not tests for JSON-B however I did test manually and I will follow up with tests after #10833 gets merged.

## JAX-RS Upgrade Information
This is a preview of the upgrade that I'm soon submitting for bringing JAX-RS 2.1 RESTEasy implementation in WildFly. I'd like the reviewers to start having a look and letting me know of any additional requirements / changes needed for merging before I tag 3.5.0.Final.
I'm dealing with the needed analysis / test plan in the mean time; besides JSR 370 (JAX-RS 2.1), the RESTEasy component upgrade also pulls few other planned new features.

Few JIRA links:
https://issues.jboss.org/browse/WFLY-9789
https://issues.jboss.org/browse/WFLY-6459
https://issues.jboss.org/browse/WFLY-9786
https://issues.jboss.org/browse/WFLY-9787

Dev analysis:
wildfly/wildfly-proposals#16
wildfly/wildfly-proposals#18
wildfly/wildfly-proposals#19

### CODE REVIEW

**Comment by jamezp** [comment]
Looks like I must have messed something up in the rebase. These failures look like this PR caused the issue.

**Comment by kabir** [comment]
@jamezp @asoldano I guess what James is saying is the reason for JaxrsTestCase blowing up here

**Comment by rsvoboda** [comment]
@jamezp I was not able to cherry-pick json-b commit on top of current master, json-p one went fine, there is conflict in pom.xml

**Comment by jamezp** [comment]
@kabir @asoldano That's correct. Because of the hard dependency on JSON-B the tests fail because the JSON-B resource is not loaded.

**Comment by jamezp** [comment]
@rsvoboda Yeah, it looks like the group ID change PR caused conflicts. I'll rebase it.

**Comment by jamezp** [comment]
@rsvoboda I've rebased. I also have https://github.com/jamezp/wildfly/tree/WFLY-6460 which is just the two JSON commits.

**Comment by rsvoboda** [comment]
@jamezp I have prepared test for json-p - look at https://github.com/rsvoboda/wildfly/commits/jsonp

I had to modify `server.jvm.args` to include `-Dee8.preview.mode=true`, otherwise JSON-P 1.1 was not loaded. I think it's the same as JAVA_OPTS you had to set in your case.

Feel free to cherry-pick https://github.com/rsvoboda/wildfly/commit/b17bc6970f5bb9aef6422c851908e34d3c0df387 commit or add comments if you spot something which should be fixed in the commit.

**Comment by rsvoboda** [comment]
hmm, JSON-B stuff doesn't need `server.jvm.args` tuned, modify-ee8-config.cli with `/system-property=ee8.preview.mode:add(value=true)` seems to be enough.

**Pull request closed without merging**
