### PR TITLE
[WFLY-5531] Fix intermittent failure in messaging HA tests

### PR DESCRIPTION
**Pull request by jmesnil**
- reenable SharedStoreFailoverTestCase and MulticastReplicatedFailoverTestCase (that uses Artemis' own UDP stack)
- continue to @Ignore ReplicatedFailoverTestCase (that uses JGroups) as
  it is always failing (WFLY-5762)

JIRA: https://issues.jboss.org/browse/WFLY-5531

### CODE REVIEW

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by jamezp** [comment]
retest this please

**Comment by bstansberry** [comment]
retest this please

**Comment by stuartwdouglas** [comment]
Failures look related

**Comment by jmesnil** [comment]
I'll close the PR until the tests are actually fixed reliably

**Pull request closed without merging**
