### PR TITLE
WFLY-5769 register ProbeExtension for every deployment when developme…

### PR DESCRIPTION
**Pull request by tremes**
…nt mode is enabled.

### CODE REVIEW

**Comment by jamezp** [comment]
This seems okay. I'd have to look more in to the CDI spec I think to fully understand it. Unless there's a strong argument I think this should go into 11.x as well.

**Comment by tremes** [comment]
I am affraid that you won't find anything about Probe in the CDI spec. It is development tool (extension) which allows you to inspect CDI deployments see http://docs.jboss.org/weld/reference/latest/en-US/html_single/#probe. This PR is basically about registering Probe filter.

**Comment by kabir** [comment]
@stuartwdouglas please check this

**Comment by kabir** [comment]
nm, I see you commented on the downstream one

**Pull request merged**
