### PR TITLE
[WFLY-10578] Eliminating usages of deprecated DependencyType enum - round 2.

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.jboss.org/browse/WFLY-10578

### CODE REVIEW

**Comment by ropalka** [comment]
@stuartwdouglas please review EJB3 & WELD subsystem changes.
@maeste please review JCA subsystem changes.
@bstansberry please review capabality API usages.

**Review by maeste — APPROVED** [review]

**Comment by kabir** [comment]
@ropalka The same tests failed in the linux and windows jobs 
https://ci.wildfly.org/viewLog.html?buildId=110275&tab=buildResultsDiv&buildTypeId=WFPR
https://ci.wildfly.org/viewLog.html?buildId=110274&tab=buildResultsDiv&buildTypeId=WF_PullRequest_Windows

I am retesting to see if this is a real problem or not

**Comment by ropalka** [comment]
It is real problem @kabir , I'm trying to reproduce it locally.

**Comment by ropalka** [comment]
Fixed @kabir could you please schedule new CI job to verify the fix?

**Pull request closed without merging**
