### PR TITLE
[WFLY-20163][WFLY-20191] Reuse forks when running testsuite/integration/elytron

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFLY-20163
https://issues.redhat.com/browse/WFLY-20191

### CODE REVIEW

**Comment by bstansberry** [comment]
@fjuma Please review.

**Review by fjuma — APPROVED** [review]
Thanks @bstansberry!

**Review by rhusar — CHANGES_REQUESTED** [review]
Looks like this makes the `org.wildfly.test.integration.elytron.realm.FilesystemRealmEncryptedWrongSecretKeyTestCase` test fail because it's missing a reload:

```
java.lang.AssertionError: Failed to execute line '/subsystem=elytron/secret-key-credential-store=mycredstore:add(path=mycredstore.cs, relative-to=jboss.server.config.dir, create=true, populate=true)'
org.jboss.as.cli.CommandLineException: {
    "outcome" => "failed",
    "failure-description" => "WFLYCTL0436: Cannot register capability 'org.wildfly.security.credential-store-api.mycredstore' at location '[
    (\"subsystem\" => \"elytron\"),
    (\"secret-key-credential-store\" => \"mycredstore\")
]' as it is already registered in context 'global' at location(s) '[[
    (\"subsystem\" => \"elytron\"),
    (\"secret-key-credential-store\" => \"mycredstore\")
]]'",
    "rolled-back" => true,
    "response-headers" => {"process-state" => "reload-required"}
}
```

Although, why does this have 100% failure rate? Odd.

https://ci.wildfly.org/test/-4739449645391971445?currentProjectId=WF_PullRequest&expandTestHistoryChartSection=true

**Comment by bstansberry** [comment]
@rhusar 

> Although, why does this have 100% failure rate? Odd.

It's always like that for class level failures. TC doesn't seem to track success at the class level, only the individual test method level.

**Comment by bstansberry** [comment]
@rhusar Thanks.

I'll see if I can easily fix that test; if not I'll tweak this and change https://github.com/wildfly/wildfly/pull/18569/files#diff-16653cf23553258b76452eb02be79fc3d93668abe53bd164f0f3dd10a09a9fe7R54 to false and take advantage of https://github.com/wildfly/wildfly/pull/18569/files#diff-16653cf23553258b76452eb02be79fc3d93668abe53bd164f0f3dd10a09a9fe7R54

My main short term goal here was to do a short-term workaround to stabilize ts.bootable tests until WFCORE-7097 is done.

@fjuma FYI

**Comment by bstansberry** [comment]
@fjuma @rhusar I prepended a commit to fix https://issues.redhat.com/browse/WFLY-20191, which hopefully fixes the problem Rado found.

Locally it insists on running -Dtest=FilesystemRealmEncryptedTestCase,FilesystemRealmEncryptedWrongSecretKeyTestCase in the opposite order so I haven't confirmed it will. :) I guess CI does the same except for the Windows job.

**Comment by bstansberry** [comment]
TC status tracker: https://ci.wildfly.org/project.html?projectId=WF_PullRequest&branch_WF_PullRequest=pull%2F18569

**Comment by bstansberry** [comment]
Thanks @rhusar and @fjuma

**Pull request merged**
