### PR TITLE
[WFLY-10944] Added script for mariadb

### PR DESCRIPTION
**Pull request by ruromero**
Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>

Added timer script for MariaDB

Fix https://issues.jboss.org/browse/WFLY-10944

### CODE REVIEW

**Comment by kabir** [comment]
@stuartwdouglas please approve and add @ruromero to the whitelist if you approve

**Comment by stuartwdouglas** [comment]
This is ok to test

**Comment by stuartwdouglas** [comment]
This should really have a WFLY JIRA associated with it rather than a RHPAM one

**Comment by ruromero** [comment]
@stuartwdouglas done

**Pull request merged**
