### PR TITLE
WFLY-14177 Update Apache commons codec 1.15

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes [WFLY-14177](https://issues.redhat.com/browse/WFLY-14177)

### CODE REVIEW

**Comment by bstansberry** [comment]
@asoldano @ronsigal @jimma This is used by components for the jaxrs and webservices subsystem. Is this ok?

**Comment by ronsigal** [comment]
@bstansberry, The RESTEasy 3.14.0.Final testsuite passes with commons codec 1.15.

**Comment by jimma** [comment]
@bstansberry  This upgrade should be good for webservice subsystem.

**Pull request merged**
