### PR TITLE
Drop out of date "in progress" note from the docs.

### PR DESCRIPTION
**Pull request by rhusar**
It's been in progress sufficiently long enough :-)

### CODE REVIEW

**Comment by rhusar** [comment]
(cancelled CI for this manually)

**Review by bstansberry — APPROVED** [review]
Is it really out of date?

:-D

**Comment by rhusar** [comment]
All the docs are always in progress! So it's more of being redundant. But really - it's silly and also from the git history, it doesn't seem to be actively in progress per se.

**Comment by bstansberry** [comment]
I totally agree; that's long annoyed me; glad to see it removed.

**Comment by bstansberry** [comment]
Thanks @rhusar

**Pull request merged**
