### PR TITLE
[WFLY-14799] Upgrade netty to 4.1.65

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/WFLY-14799

### CODE REVIEW

**Comment by boris-unckel** [comment]
Central vs. local build issue. It's hopefully solved soon: [https://github.com/netty/netty/issues/11272](https://github.com/netty/netty/issues/11272)
I'll provide the fix then.

**Comment by boris-unckel** [comment]
Hopefully I'm at the right adress regarding the components :-) Hello @pferraro @ehsavoie could you please review the upgrade? Diff is linked in the JIRA. Thanks in advance

**Comment by pferraro** [comment]
👍 This is fine wrt Infinispan.

**Comment by ehsavoie** [comment]
:+1: from artemis

**Comment by boris-unckel** [comment]
@bstansberry Hello Brian, tests passed, component review is done. Could you please check and merge?

**Review by pferraro — APPROVED** [review]

**Comment by bstansberry** [comment]
@boris-unckel I'll merge this later after CI runs again. I retested since there's been a lot of change in master since the last run. I don't expect any problems.

**Comment by bstansberry** [comment]
Thanks, @boris-unckel

**Pull request merged**
