### PR TITLE
WFLY-15865 Replace deprecated EnumValidator constructors and methods

### PR DESCRIPTION
**Pull request by clara0**
https://issues.redhat.com/browse/WFLY-15865

Changes made for equivalent results:
Constructors:
```java
EnumValidator(Class, boolean, E...) --> EnumValidator(Class, E...)
EnumValidator(Class, boolean, boolean) --> create(Class, E...)
EnumValidator(Class, boolean, boolean, E...) --> EnumValidator(Class, E...)
```

Methods:
```java
create(Class, boolean, E...) --> create(Class, E...)
create(Class, boolean, boolean) --> create(Class, E...)
create(Class, boolean, boolean, E...) --> create(Class, E...)
create(Class, boolean, boolean, E...) --> create(Class, EnumSet)
```

### CODE REVIEW

**Comment by darranl** [comment]
Thank you for your PR, if you can it would be better if we could split the different subsystems into different issues and different PRs to make it easier to get the reviews from the individual teams.

**Comment by clara0** [comment]
@darranl ok, will do

**Comment by clara0** [comment]
This PR has been split up into several sub-PRs corresponding to their respective components.
See the Jira for more details: https://issues.redhat.com/browse/WFLY-15865

**Comment by bstansberry** [comment]
Thanks, @clara0 -- since you filed the other ones I'll close this one.

**Pull request closed without merging**
