### PR TITLE
WFLY-6901 Add checkstyle testing also to tests classes in wildfly

### PR DESCRIPTION
**Pull request by ctomc**
This PR enables checkstyle also for test code.
All non testsuite test code was fixed to apply to the checkstyle.
all testsuites ware fixed and now run checkstyle by default.

### CODE REVIEW

**Comment by rhusar** [comment]
I am skeptical if this is really the right time for this change given the PR queue is above 100 unmerged PRs...

**Comment by ctomc** [comment]
@rhusar it is never right time to do it. It is long overdue, it was agreed it should wait till EAP7 is out, that was back when we split core out, which got all this enabled for years.

**Comment by rsvoboda** [comment]
I agree with Tomaz, sooner is better. There is no "right" time for such change. Rado, don't be afraid, I bet clustering will win ;)

**Comment by rsvoboda** [comment]
This is huge, probably the largest PR ;) Good work!

**Comment by ctomc** [comment]
I have updated this PR to include all checkstyle fixes for whole testsuite code we have,
It is possible to merge this with just some commits as they are separate for each testsuite we have.
just first 4 should go in together, others can be done separately.

**Comment by bstansberry** [comment]
@darranl Will this mess with Elytron integration?

**Comment by darranl** [comment]
We will be fine - probably better to get this merge out the way ASAP so everyone has time to adapt.

**Comment by kabir** [comment]
Retest this please

**Pull request merged**
