### PR TITLE
[WFLY-4585] Provide JMS forward compatibility

### PR DESCRIPTION
**Pull request by jmesnil**
- add support for JMS forward compatibility so that legacy JMS clients
  (with HornetQ client libraries) can lookup HornetQ-based JMS resources
  from JNDI and connect to the Artemis server using its HORNETQ
  protocol.
- for JMS destinations (jms-queue and jms-topic), a new attribute
  legacy-entries can be used to bind the HornetQ-based destinations to
  JNDI.
- for connection factories, a new resource (legacy-connection-factory)
  has been added. It is different from the connection-factory resource
  used by Artemis client.
- add org.hornetq.client module. The messaging-activemq subsystem depends
  on it to create HornetQ managed resources for forward interoperability.
- add test for legacy (HornetQ) clients connecting to resources managed
  by the messaging-activemq subystem

JIRA: https://issues.jboss.org/browse/WFLY-4585

### CODE REVIEW

**Comment by n1hility** [comment]
Needs a rebase

**Comment by n1hility** [comment]
Retest this please

**Comment by jmesnil** [comment]
retest this please

**Comment by jmesnil** [comment]
PR has been rebased, the `rebase-this` label can be removed

**Pull request merged**
