### PR TITLE
servlet-feature-pack-licenses: merge org.wildfly.core:wildfly-event-logger licenses in one entry only

### PR DESCRIPTION
**Pull request by rgdoliveira**

### CODE REVIEW

**Comment by rgdoliveira** [comment]
@jamezp @bstansberry can you please take a look in this one?

**Comment by bstansberry** [comment]
@rgdoliveira Eliminating the duplicate declaration is fine but it seems wrong that org.wildfly.core:wildfly-event-logger and org.wildfly.core:wildfly-elytron-integration are in this file at all. They are already in core-feature-pack-license.

**Comment by rgdoliveira** [comment]
@bstansberry I'm afraid we need those 2 licenses there.

If we remove them, the maven license plugin will try to inject them in the licenses.xml generated (docs/licenses/licenses.xml) and the URL for the apache license, for example, would be [1] instead of [2] making the URL inconsistent as it is defined in core-feature-pack-licenses.xml as [2].

[1] http://repository.jboss.org/licenses/apache-2.0.txt
[2] http://www.apache.org/licenses/LICENSE-2.0

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks, @rgdoliveira

**Pull request merged**
