### PR TITLE
Add parent pom for microprofile modules.

### PR DESCRIPTION
**Pull request by pferraro**
Allows microprofile subsystem developers to more easily build all microprofile modules.

### CODE REVIEW

**Comment by darranl** [comment]
This kind of change is likely better either before or after development to add more new MP subsystems ;-)

**Review by rhusar — APPROVED** [review]
LGTM

**Comment by rhusar** [comment]
@darranl +1 for merging timely.

**Comment by pferraro** [comment]
Yeah - the idea was to get this in sooner rather than later...

**Comment by pferraro** [comment]
@jmesnil @ehsavoie @kabir Any objections?

**Pull request merged**
