### PR TITLE
[WFLY-11847] Upgrading ASM to 7.1

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.jboss.org/browse/WFLY-11847

### CODE REVIEW

**Comment by ropalka** [comment]
The windows failure is unrelated.

**Comment by kabir** [comment]
@scottmarlow Please approve - I made a quick comment on the Jira

**Comment by scottmarlow** [comment]
List of current dependencies on asm.asm is:
org/jboss/as/webservices/server/integration/main/module.xml
org/apache/cxf/main/module.xml
org/apache/cxf/impl/main/module.xml
org/apache/cxf/services-sts/main/module.xml
org/apache/cxf/ws-security/main/module.xml
org/hibernate/main/module.xml
org/hibernate/bytecodetransformer/main/module.xml

I don't think org/hibernate/main/module.xml actually needs asm.asm module dependency anymore, as Hibernate is using Javassist + ByteBuddy, ByteBuddy includes its own copy of ASM 7.1 classes.  We could either remove ASM from org/hibernate/main/module.xml for this pr or do that as a separate change.

I didn't see anything of concern when Hibernate upgraded to ASM 7.1.  @ropalka where there any ASM commits that you are concerned about?  I assume not since you didn't mention any, but just checking.

@asoldano @jimma can jboss/as/webservices/server/integration/* + cxf work with ASM 7.1?

**Comment by bstansberry** [comment]
@scottmarlow Thank you for that analysis. @ropalka (and @ everyone really) please do that kind of thing when proposing an upgrade for a component you don't 'own'. It's what identifies who needs to be asked for approval.

Scott, please file a JIRA and do a separate change re dropping unneeded dependencies.

**Comment by ropalka** [comment]
Not concerned @scottmarlow about particular commit but demanding commit:
https://gitlab.ow2.org/asm/asm/commit/fc2fa0bedc9cd43680b758602149f433fc4c7948
so we can run WildFly on top of JDK13 without ASM choking on "Unsupported class file major version "
I will do this kind of analysis ( @scottmarlow did ) next time @bstansberry .

**Comment by scottmarlow** [comment]
Created [https://issues.jboss.org/browse/WFLY-11874] for reviewing Hibernate ORM dependencies like ASM and remove unneeded ASM dependency.

**Comment by jimma** [comment]
@ropalka @scottmarlow @bstansberry   ASM 7.1 works with CXF 3.2.7 and JBossWS.

**Pull request merged**
