### PR TITLE
WFLY-5734 Upgrade to Hibernate Search 5.5.1.Final and Hibernate Commo…

### PR DESCRIPTION
**Pull request by Sanne**
…ns Annotations 5.0.1.Final

https://issues.jboss.org/browse/WFLY-5734

Also relates to: JBEAP-1746 . Please consider for inclusion in WildFly 10.

### CODE REVIEW

**Comment by scottmarlow** [comment]
Does Hibernate Search 5.5.1.Final require Hibernate Commons Annotations 5.0.1.Final?  I tried locally building the ORM 5.0 branch with HCANN 5.0.1.Final and got the below compile error:

hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/DynamicProperty.java:20: error: DynamicProperty is not abstract and does not override abstract method invoke(Object) in XMember
public class DynamicProperty implements XProperty {

**Comment by Sanne** [comment]
> Does Hibernate Search 5.5.1.Final require Hibernate Commons Annotations 5.0.1.Final?

Yes

**Comment by Sanne** [comment]
> I tried locally building the ORM 5.0 branch with HCANN 5.0.1.Final and got the below compile error [..]

Good catch. I fixed ORM now, but I'm afraid this implies we need another ORM release to be included in WildFly.

https://hibernate.atlassian.net/browse/HHH-10335
https://hibernate.atlassian.net/browse/HHH-10336

**Comment by Sanne** [comment]
@scottmarlow This is required for #8453

**Comment by scottmarlow** [comment]
@Sanne why is #8431 needed for #8453?  I heard that we need EAP7 issues (e.g. JBEAP-1604) at this point, for WF10 changes.

**Comment by scottmarlow** [comment]
I updated #8453 to also include HCANN 5.0.1.Final.

**Comment by Sanne** [comment]
Rebased this as the Hibernate HCANN upgrade was already integrated together with the Hibernate ORM upgrade.

**Comment by Sanne** [comment]
@scottmarlow the main reason to integrate this is JBEAP-1746.
It's also the only one fully tested with that HCANN change, which makes me a bit nervous hence why I said you should apply this as a consequence for having applied #8453

**Comment by Sanne** [comment]
@scottmarlow created a dedicated EAP issue to track this: https://issues.jboss.org/browse/JBEAP-2176

**Comment by scottmarlow** [comment]
Makes sense Sanne, thanks for explaining.

**Pull request merged**
