### PR TITLE
Enable ssl invocation during corbaloc lookup

### PR DESCRIPTION
**Pull request by tadamski**

### CODE REVIEW

**Comment by tadamski** [comment]
retest this please

**Comment by tadamski** [comment]
I'm unable to reproduce the errors on my local branch.

**Comment by n1hility** [comment]
@tadamski these look like legitimate failures

**Comment by tadamski** [comment]
looking again

**Comment by tadamski** [comment]
I have hardcoded hostname in one place of the test
headbang_80_anim_gif
now everything works correctly

**Comment by n1hility** [comment]
@tadamski can you rebase this??

Thanks!

**Comment by tadamski** [comment]
retest this please

**Comment by n1hility** [comment]
retest this please

**Pull request merged**
