### PR TITLE
[WFLY-5993] Add test for WFCORE-1226

### PR DESCRIPTION
**Pull request by soul2zimate**
https://issues.jboss.org/browse/WFLY-5993
add a testcase for WFCORE-1226

### CODE REVIEW

**Comment by soul2zimate** [comment]
retest this please

**Comment by soul2zimate** [comment]
retest this please

**Comment by stuartwdouglas** [comment]
Why is this test not in Wildfly core?

**Comment by soul2zimate** [comment]
The issue https://issues.jboss.org/browse/WFCORE-1226 is about deployment/undeployment for same runtime-name, it's more straightforward to put it into this DeployWithRuntimeNameTestCase

**Comment by bstansberry** [comment]
This whole class should be reworked to not require servlets and moved to core.

But, that's not your task.

**Pull request merged**
