### PR TITLE
WFLY-16573 Convert testsuite/integration/clustering to the jakarta.* namespace

### PR DESCRIPTION
**Pull request by darranl**
https://issues.redhat.com/browse/WFLY-16573

This follows up on Paul's PR as we had a merge conflict:
    https://github.com/wildfly/wildfly/pull/15730

### CODE REVIEW

**Comment by darranl** [comment]
@rhusar if it would be possible to please get a review on this one so we can get it merged that would be great.

**Comment by rhusar** [comment]
@darranl Sure – back from PTO/holidays today – I will target to review today.

**Comment by rhusar** [comment]
@darranl There's a failure in the bootable jar job – `Failed to execute goal org.wildfly.plugins:wildfly-jar-maven-plugin:7.0.0.Final:package (bootable-jar-cloud-profile-packaging) on project wildfly-ts-integ-clustering: Provisioning failed`. Do you want to fix the PR (or should I)?

**Comment by darranl** [comment]
@rhusar if you are able to submit a fix that would be great, if you wanted to submit a PR to my topic branch I can add it to this PR?  I am going to be on a couple of other tasks before I come back to this later today.

**Comment by rhusar** [comment]
@darranl Replacing the PR would be easier - lets see how https://github.com/wildfly/wildfly/pull/15754 goes.

**Comment by darranl** [comment]
Closing as we have a follow up PR from @rhusar

**Pull request closed without merging**
