### PR TITLE
WFLY-5152 Explicit declaration of iiop subsystem ports

### PR DESCRIPTION
**Pull request by tadamski**

### CODE REVIEW

**Comment by bstansberry** [comment]
Grr; I thought I posted this last week but must not have hit the button. :(
 
Removing the default values will break existing configs or cli scripts that rely on the previous behavior.

I haven't checked, but I also assume IIOP can't work properly if at least one of these doesn't have a value provided. But both the attributes now say they allow null, but don't have a default value to pass to the runtime if the user doesn't provide a value. So the allow null = true setting isn't really correct.

I think the attribute definitions should be left as is, and the change should be limited to changing the standard config files to explicitly declare the attribute.

**Comment by tadamski** [comment]
@bstansberry Yes those fields are necessary for the system to start. A litte problem with them is that they point to the name of another resource which can be arbitrary so as a result of that if someone removes iiop sockets in his config then default port names would point to unexistent name which may be quite confusing. Anyway, for now I have reverted the definition change so that they still have default value.

**Comment by bstansberry** [comment]
@tadamski Thanks. I understand the concern. When we start using capabilities and requirements in IIOP that should help with providing a useful error message if the user makes this mistake. It will also reject the change.

Another small thing you can do is to make the attribute required in the WF 10 version of the xsd, and then configure the AttributeDefinition such that it will write the default value to xml even if the user didn't configure it. (Writing the default value ensures we don't write configs that are invalid per the xsd.) But the parser for older xsd versions cannot require the attribute to be present.

What this would do is have the xsd help document the preferred way of configuring.

Are these AttributeDefinitions used for subsystem=jacorb as well?

**Comment by bstansberry** [comment]
I'll merge this now; any further changes based on the discussion can be a separate PR.

**Comment by tadamski** [comment]
@bstansberry OK. I will prepare the xsd fix then and note down that further changes should be made when capabilities are present. I have the same attributes in jacorb too - will prepare alike fix for it.

**Pull request merged**
