### PR TITLE
Fix for WFLY-10890, CLI client in jconsole doesn't work with JDK11

### PR DESCRIPTION
**Pull request by jfdenise**
Fix for https://issues.jboss.org/browse/WFLY-10890
Fixed jconsole.bat, jconsole.sh and  jconsole.ps1
NB: The jconsole context is modular, when running with JConsole class in the classpath the problem doesn't show up.

### CODE REVIEW

**Comment by kabir** [comment]
@jfdenise We probably (unfortunately) also need the ps1 script too?

**Comment by marekkopecky** [comment]
PowerShell needs to be fixed as well. This PR works correctly on Windows 2016 and Linux. But as Kabir mentioned, this is just workaroud. I don't think WF (WildFlySecurityManager) should depend on jdk.unsupported module.

**Comment by jfdenise** [comment]
@marekkopecky , can you observe the problem on Windows without the fix applied (both .bat and .ps1)? I manage to run jconsole without any change with JDK11 using .ps1.

**Comment by marekkopecky** [comment]
I see the same exception on ps with JDK11, using:
```
PS C:\Users\Administrator\playground\wfly\wildfly\bin> java -version
openjdk version "11-ea" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11-ea+26)
OpenJDK 64-Bit Server VM 18.9 (build 11-ea+26, mixed mode)
PS C:\Users\Administrator\playground\wfly\wildfly\bin>
```

**Comment by jfdenise** [comment]
@marekkopecky , I fixed .ps1 file. I guess that the fix is right but on my Windows 2012 server it works without the fix.

**Comment by marekkopecky** [comment]
@jfdenise Ps1 works on W2016, thank you

**Review by kabir — APPROVED** [review]

**Pull request merged**
