### PR TITLE
[WFLY-15983] Upgrade SmallRye Health to 3.2.0

### PR DESCRIPTION
**Pull request by xstefank**
https://issues.redhat.com/browse/WFLY-15983

### CODE REVIEW

**Comment by xstefank** [comment]
test failures seem unrelated to me

**Comment by xstefank** [comment]
@bstansberry should I restart failed jobs? I don't think it's necessary.

**Comment by bstansberry** [comment]
@xstefank Not necessary.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks, @xstefank

**Pull request merged**
