### PR TITLE
[WFLY-15267] Upgrade Netty to 4.1.68.

### PR DESCRIPTION
**Pull request by langfr**
https://issues.redhat.com/browse/WFLY-15267

### CODE REVIEW

**Comment by bstansberry** [comment]
@ehsavoie @pferraro Please review

**Comment by pferraro** [comment]
:+1:  wrt Infinispan.

**Comment by ehsavoie** [comment]
:+1 from Artemis

**Comment by pferraro** [comment]
@langfr Can you resolve this merge conflict?  Otherwise, ready to merge.

**Comment by bstansberry** [comment]
Thanks, @langfr !

**Pull request merged**
