### PR TITLE
[WFLY-15735] / [WFLY-15356] Remove the security-api module.

### PR DESCRIPTION
**Pull request by darranl**
https://issues.redhat.com/browse/WFLY-15735

### CODE REVIEW

**Comment by darranl** [comment]
@fjuma would it be possible to give this one a review please?

**Comment by fjuma** [comment]
Looks good. I think there's one more occurrence of `wildfly-security-api` in `ee-feature-pack/common/src/main/resources/license/ee-feature-pack-common-licenses.xml` that should be removed too.

**Comment by darranl** [comment]
Thanks @fjuma I always forget that file.

**Comment by darranl** [comment]
@fjuma that is pushed now

**Review by fjuma — APPROVED** [review]

**Pull request merged**
