### PR TITLE
[WFLY-19888] Move to SE 17 as the minimum SE version

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFLY-19888

### CODE REVIEW

**Review by jasondlee — APPROVED** [review]
lgtm

**Review by jamezp — APPROVED** [review]

**Comment by jamezp** [comment]
LGTM

**Comment by bstansberry** [comment]
Thanks @jasondlee and @jamezp

**Comment by darranl** [comment]
@bstansberry FYI the root README will also need an update as this specifies Java 11 as the minimum.

**Pull request merged**
