### PR TITLE
[WFLY-7885] Persistent calendar timer force logging for each invocation if the deployed-class has changed

### PR DESCRIPTION
**Pull request by iweiss**
Issue: https://issues.jboss.org/browse/WFLY-7885

### CODE REVIEW

**Comment by iweiss** [comment]
I don't believe the failures to be related to the patch

**Comment by wfink** [comment]
Fix will work for the file persistence, but the database persistence is missing

**Comment by iweiss** [comment]
From my tests this doesn't show up when using database persistence. When using database persistence it throws a `java.lang.NoSuchMethodException` only once, requiring a manual database cleanup. Should we clean it up as all?

**Comment by wfink** [comment]
Works for me for File and DB persistence as expected

**Pull request merged**
