### PR TITLE
WFLY-20139 Upgrade otel/opentelemetry-collector image to 0.115.1 and jaegertracing/all-in-one to 1.64.0

### PR DESCRIPTION
**Pull request by rhusar**
Resolves
https://issues.redhat.com/browse/WFLY-20139

Another chuck of work to stabilize our OpenTelemetry testing, cleanup and improve javadoc/comments.

### CODE REVIEW

**Review by jasondlee — APPROVED** [review]
lgtm

**Comment by bstansberry** [comment]
Team City CI status: https://ci.wildfly.org/project.html?projectId=WF_PullRequest&branch_WF_PullRequest=pull%2F18550

**Review by jasondlee — APPROVED** [review]

**Comment by rhusar** [comment]
(last push only rebased, no changes)

**Comment by bstansberry** [comment]
No more rebases please. :)

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @rhusar

**Pull request merged**
