### PR TITLE
WFLY-4338 - JConsole script builds wrong path

### PR DESCRIPTION
**Pull request by avlemos**
Fixes WFLY-4338. Pulling as per suggested by kabirkhan.

### CODE REVIEW

**Comment by ctomc** [comment]
this is ok to test

**Comment by jamezp** [comment]
This essentially reverts the work done for https://issues.jboss.org/browse/WFLY-3829. This isn't an issue for me on Linux.

**Comment by darranl** [comment]
This PR should be closed, an alternative fix has already been merged.

**Comment by jamezp** [comment]
Thanks for catching that @darranl

**Pull request closed without merging**
