### PR TITLE
WFLY-8326 Enabling statistics on caches shouldn't require reload of server

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/WFLY-8326

### CODE REVIEW

**Review by rhusar — APPROVED** [review]

**Comment by bstansberry** [comment]
Bouncing the cache service means bouncing the deployment, right?

**Comment by pferraro** [comment]
@bstansberry Yes - which is why we only do this when the operation specifies the {allow-resource-service-restart=true} flag.

**Comment by bstansberry** [comment]
Technically, this PR is ok since AIUI all it does is cause the op to respect allow-resource-service-restart=true if the attribute definition says it will. Not doing that is a bug, either in the handler or in the attribute definition. So the following isn't really about the PR per se.

IMO we should not be responding to this kind of QE input by bouncing services. Bouncing services is likely a worse solution for the user vs a reload. With no deployment a reload takes 200 ms. Shaving time off that is pointless, and the extra time it takes the user to request service restart vs a reload likely dwarfs any time savings. With a deployment, well, bouncing services very likely means the deployment bounces, so there is no added time benefit. 

So likely no meaningful time benefit, with the cost that the user who triggers a service restart quite likely doesn't understand the impact of that. The effect of a reload is pretty obvious. For a resource service restart, well, I'm about as expert as it gets and I just had to ask the effect. ;)

Supporting service restart technically like this PR does isn't so terrible. But if we start going around telling people they can avoid an evil reload by using allow-resource-service-restart=true we are doing our users a disservice by giving them bad advice.

**Comment by pferraro** [comment]
@bstansberry In this particular case, the services providing cache configuration start passively - so the service restart is necessary even when there are no deployments that depend on the specific service.

While you assessment is technically true, the real world use case for this PR is for setting up the configuration for a new deployment, and allowing the associated services to restart (instead of reloading the server) thus being able to apply the change without affecting the existing deployments (which may depend on other cache configuration services).

**Comment by bstansberry** [comment]
@pferraro Yes, that's a valid real world use case, and a reason to support the header. But I expect typically people setting up something would configure it correctly via the add. Or they wouldn't be bringing new deployments into a running production server.

I think the PR is fine. I expect when the related JIRA is verified, the response will be that reload-required still happens with a plain write-attribute. The answer there shouldn't be that allow-resource-service-restart=true is a good option because except for in some fairly narrow cases it's a bad idea. It's a power-user option. The basically UX concern driving these JBEAPs is the fact that we  can't live update the running services.

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
