### PR TITLE
WFLY-19550 Distributed timer service implementation should not schedule timers while server is suspended.

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-19550

Requires https://github.com/wildfly/wildfly-core/pull/6117

### CODE REVIEW

**Comment by pferraro** [comment]
Blech - something broke in the last rebase.

**Review by rachmatowicz — APPROVED** [review]
Reviewed this code to the extent possible. Looks good.

**Comment by pferraro** [comment]
Rebased to resolve conflicts.

**Comment by bstansberry** [comment]
Thanks @pferraro and @rachmatowicz

**Pull request merged**
