### PR TITLE
[WFLY-8418] Enhance the way licenses are presented

### PR DESCRIPTION
**Pull request by psakar**
issue: https://issues.jboss.org/browse/WFLY-8418

### CODE REVIEW

**Comment by jamezp** [comment]
This may need to be reverted. It creates a problem when the `prepare-package` goal, e.g. `package`, `install`, etc., is executed. It will update the `license.xml` file and create a new untracked `license.xml` file. We can't do this as it will mess up the commit the developer is working on.

This is from a `mvn clean install -DskipTests` on master with no other changes.
```
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   feature-pack/src/main/resources/content/docs/licenses/licenses.xml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	feature-pack/src/main/resources/content/docs/licenses/licenses.html

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by dmlloyd** [comment]
The general rule is, don't modify things under src/ during build.  There is a generated-sources directory which might be appropriate (or might not be).

**Comment by jamezp** [comment]
This won't need to be reverted as https://github.com/wildfly/wildfly/pull/10148 will fix it.

**Comment by psakar** [comment]
@dmlloyd I'm not happy to find out I did it wrong, but there was reason for doing it this way.  There is now plenty of time to solve with the way that would satisfy all requirements.

**Pull request merged**
