### PR TITLE
[WFLY-9181]ReadOnly user able to perform runtimeOnlly operations on J…

### PR DESCRIPTION
**Pull request by shailendra14k**
Possible Fix for:-
https://issues.jboss.org/browse/WFLY-9181

### CODE REVIEW

**Comment by bstansberry** [comment]
Thanks! You're on the right track for sure.

Instead of a hard coded list of operation names, though, this can be done

boolean readOnly = context.getResourceRegistration().getOperationFlags(PathAddress.EMPTY_ADDRESS, operationNames).contains(OperationEntry.Flag.READ_ONLY);

However, for this to work correctly, in AbstractQueueControlHandler.registerOperations the definition for each of these ops needs to be configured correctly. Specifically, for all the read-only ops, the builder needs to have a call to setReadOnly() added. The fact that call is missing is a bug itself. Not having it means the CLI read-operation-description and read-resource-description output for these ops is incorrect.

**Comment by jmesnil** [comment]
@shailendra14k, thanks for the patch.

I have opened a related PR (https://github.com/wildfly/wildfly/pull/10399) to make sure that all queue operations that are read-only are properly described.
You can then update your patch as @bstansberry to check the Flag.READ_ONLY flag.

**Comment by shailendra14k** [comment]
@bstansberry @jmesnil  Thank you for the review.

I will update this patch once  #10399 PR (https://github.com/wildfly/wildfly/pull/10399) get merged.

**Comment by shailendra14k** [comment]
@bstansberry I did some analysis, if I am correct I don't think AbstractQueueControlHandler.registerOperations needs to have a call to setReadOnly() added, as all the operations are already marked correctly by calling the method *runtimeReadOnlyOperation* and *runtimeOnlyOperation*.

Below readOnly flag should work without any changes.
~~~~~
boolean readOnly = context.getResourceRegistration().getOperationFlags(PathAddress.EMPTY_ADDRESS, operationNames).contains(OperationEntry.Flag.READ_ONLY);
~~~~~

**Comment by jmesnil** [comment]
@shailendra14k you are right and I closed the #10399 PR.

**Comment by shailendra14k** [comment]
Updated the PR, removed hard coded list of operation names and added readOnly flag.

**Comment by shailendra14k** [comment]
Updated the PR, as all these changes are also required for Topic.

**Pull request merged**
