### PR TITLE
WFLY-9867 JBMETA-405 Upgrade metadata to 12.0.0.Beta1

### PR DESCRIPTION
**Pull request by ctomc**
jira https://issues.jboss.org/browse/WFLY-9867
https://issues.jboss.org/browse/JBMETA-405

It upgrades to metadata that doesn't have split-package problem anymore. as result some packages ware moved around in metadata, and this PR upgrades to newer version and fixes imports accordingly.

With this version of metadata we can consume it also in JDK 9 modular enviroment.

Please make sure your PR meets the following requirements:
- [x] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue(s)
- [x] Pull Request contains description of the issue(s)
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted

### CODE REVIEW

**Comment by ctomc** [comment]
@stuartwdouglas please approve

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by stuartwdouglas** [comment]
Assuming CI passes this looks good to me

**Comment by jamezp** [comment]
I think we should revert this. This breaks backwards compatibility with parsing the `jboss-ejb3.xml` as the `integrity`, `confidentiality`, `establish-trust-in-client` and `establish-trust-in-target` were changed from elements to attributes.

**Pull request merged**
