### PR TITLE
WFLY-9469 - Assumes in SPNEGOLoginModuleTestCase doen's make sense

### PR DESCRIPTION
**Pull request by rpelisse**
Issue: https://issues.jboss.org/browse/JBEAP-8791
Upstream Issue: https://issues.jboss.org/browse/WFLY-9469

### CODE REVIEW

**Comment by bstansberry** [comment]
retest this please

**Comment by rpelisse** [comment]
retest this please

**Comment by rpelisse** [comment]
retest this please

**Comment by rpelisse** [comment]
Only the "Linux - elytron" tests are systematically failing. I'm trying a 3rd time, maybe this time, they will all pass.

**Comment by rpelisse** [comment]
retest this please

**Comment by stuartwdouglas** [comment]
Have you verified that this passes on the IBM JDK (this is not part of our regular CI)?

**Comment by rpelisse** [comment]
@stuartwdouglas yes, I did:

```
$ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 8.0.5.0 - pxi3280sr5-20170905_01(SR5))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux x86-32 20170901_363591 (JIT enabled, AOT enabled)
J9VM - d56eb84
JIT  - tr.open_20170901_140853_d56eb84
OMR  - b033a01)
JCL - 20170823_01 based on Oracle jdk8u144-b01
$ javac -version
javac 1.8.0
$ which javac
/home/rpelisse/Repositories/redhat/issues/JBEAP-8791/ibm-java-i386-80/bin/javac
...
[INFO] WildFly Test Suite: Aggregator ..................... SUCCESS [  0.015 s]
[INFO] WildFly Test Suite: Integration (parent) ........... SUCCESS [  0.327 s]
[INFO] WildFly Test Suite: Integration - Web .............. SUCCESS [01:03 min]
[INFO] WildFly Test Suite: Integration - Smoke ............ SUCCESS [02:07 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14:03 min
[INFO] Finished at: 2017-11-09T11:49:07+01:00
[INFO] Final Memory: 453M/829M
[INFO] ------------------------------------------------------------------------
```

For the sake of double checking, I also verify the test environnements, to be sure mvn did not somehow used an other JVM:

```
$ grep -e java.home connector/target/surefire-reports/*.xml
connector/target/surefire-reports/TEST-org.jboss.as.connector.annotations.repository.jandex.AnnotationsTestCase.xml:    <property name="java.home" value="/home/rpelisse/Repositories/redhat/issues/JBEAP-8791/ibm-java-i386-80/jre"/>
...
```
But that being said, it is only one IBM JVM and my system (Linux/Fedora). I am hoping some more wide spread testing will be done, down the road...

**Review by darranl — APPROVED** [review]

**Pull request merged**
