### PR TITLE
WFLY-13975 Add Infinispan subsystem schema 9.1 and model 11.1.0 intro…

### PR DESCRIPTION
**Pull request by rhusar**
…duced in EAP 7.3.4

Resolves 
https://issues.redhat.com/browse/WFLY-13975

Changes pending to be introduced are in this PR:
https://github.com/jbossas/jboss-eap7/pull/3725

### CODE REVIEW

**Comment by rhusar** [comment]
@pferraro For review.

**Review by pferraro — APPROVED** [review]

**Comment by kabir** [comment]
Adding the hold label so it doesn't accidentally get merged without the actual subsystem changes

**Comment by pferraro** [comment]
@kabir FYI, this isn't a traditional version bump for upstream changes.  This is a backport of a model bump for EAP 7.3.4.

**Comment by kabir** [comment]
@pferraro hmm, in that case should we get it in sooner rather than later?

**Comment by rhusar** [comment]
The https://github.com/jbossas/jboss-eap7/pull/3725 is now merged, so these changes are required now as well.

**Pull request merged**
